# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PositionPanel.ui'
#
# Created: Sun May 15 10:19:10 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(372, 136)
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.hLayoutGroupBox = QtGui.QHBoxLayout(self.groupBox)
        self.hLayoutGroupBox.setSpacing(0)
        self.hLayoutGroupBox.setMargin(0)
        self.hLayoutGroupBox.setObjectName(_fromUtf8("hLayoutGroupBox"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hLayoutGroupBox.addItem(spacerItem)
        self.basicFrame = QtGui.QFrame(self.groupBox)
        self.basicFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.basicFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.basicFrame.setObjectName(_fromUtf8("basicFrame"))
        self.hLayout_basicFrame = QtGui.QHBoxLayout(self.basicFrame)
        self.hLayout_basicFrame.setSpacing(6)
        self.hLayout_basicFrame.setMargin(0)
        self.hLayout_basicFrame.setObjectName(_fromUtf8("hLayout_basicFrame"))
        self.framePositionContents = QtGui.QFrame(self.basicFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePositionContents.sizePolicy().hasHeightForWidth())
        self.framePositionContents.setSizePolicy(sizePolicy)
        self.framePositionContents.setFrameShape(QtGui.QFrame.StyledPanel)
        self.framePositionContents.setFrameShadow(QtGui.QFrame.Raised)
        self.framePositionContents.setObjectName(_fromUtf8("framePositionContents"))
        self.vLayoutPositionContents = QtGui.QVBoxLayout(self.framePositionContents)
        self.vLayoutPositionContents.setSpacing(6)
        self.vLayoutPositionContents.setMargin(0)
        self.vLayoutPositionContents.setObjectName(_fromUtf8("vLayoutPositionContents"))
        self.frameID = QtGui.QFrame(self.framePositionContents)
        self.frameID.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameID.setFrameShadow(QtGui.QFrame.Raised)
        self.frameID.setObjectName(_fromUtf8("frameID"))
        self.hLayoutID = QtGui.QHBoxLayout(self.frameID)
        self.hLayoutID.setSpacing(0)
        self.hLayoutID.setMargin(0)
        self.hLayoutID.setObjectName(_fromUtf8("hLayoutID"))
        self.frameIDContent = QtGui.QFrame(self.frameID)
        self.frameIDContent.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameIDContent.setFrameShadow(QtGui.QFrame.Raised)
        self.frameIDContent.setObjectName(_fromUtf8("frameIDContent"))
        self.hLayoutIDContent = QtGui.QHBoxLayout(self.frameIDContent)
        self.hLayoutIDContent.setSpacing(0)
        self.hLayoutIDContent.setMargin(0)
        self.hLayoutIDContent.setObjectName(_fromUtf8("hLayoutIDContent"))
        self.labelID = QtGui.QLabel(self.frameIDContent)
        self.labelID.setMinimumSize(QtCore.QSize(50, 0))
        self.labelID.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelID.setFont(font)
        self.labelID.setObjectName(_fromUtf8("labelID"))
        self.hLayoutIDContent.addWidget(self.labelID)
        self.txtIID = QtGui.QLineEdit(self.frameIDContent)
        self.txtIID.setMinimumSize(QtCore.QSize(100, 0))
        self.txtIID.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtIID.setFont(font)
        self.txtIID.setObjectName(_fromUtf8("txtIID"))
        self.hLayoutIDContent.addWidget(self.txtIID)
        self.hLayoutID.addWidget(self.frameIDContent)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hLayoutID.addItem(spacerItem1)
        self.vLayoutPositionContents.addWidget(self.frameID)
        self.frameXY_LL = QtGui.QFrame(self.framePositionContents)
        self.frameXY_LL.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameXY_LL.setFrameShadow(QtGui.QFrame.Raised)
        self.frameXY_LL.setObjectName(_fromUtf8("frameXY_LL"))
        self.hLayoutXYLL = QtGui.QHBoxLayout(self.frameXY_LL)
        self.hLayoutXYLL.setSpacing(0)
        self.hLayoutXYLL.setMargin(0)
        self.hLayoutXYLL.setObjectName(_fromUtf8("hLayoutXYLL"))
        self.frameXY = QtGui.QFrame(self.frameXY_LL)
        self.frameXY.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameXY.setFrameShadow(QtGui.QFrame.Raised)
        self.frameXY.setObjectName(_fromUtf8("frameXY"))
        self.vLayoutXY = QtGui.QVBoxLayout(self.frameXY)
        self.vLayoutXY.setSpacing(6)
        self.vLayoutXY.setMargin(0)
        self.vLayoutXY.setObjectName(_fromUtf8("vLayoutXY"))
        self.frameX = QtGui.QFrame(self.frameXY)
        self.frameX.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameX.setFrameShadow(QtGui.QFrame.Raised)
        self.frameX.setObjectName(_fromUtf8("frameX"))
        self.hLayoutX = QtGui.QHBoxLayout(self.frameX)
        self.hLayoutX.setSpacing(0)
        self.hLayoutX.setMargin(0)
        self.hLayoutX.setObjectName(_fromUtf8("hLayoutX"))
        self.labelX = QtGui.QLabel(self.frameX)
        self.labelX.setMinimumSize(QtCore.QSize(50, 0))
        self.labelX.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelX.setFont(font)
        self.labelX.setObjectName(_fromUtf8("labelX"))
        self.hLayoutX.addWidget(self.labelX)
        self.txtPointX = QtGui.QLineEdit(self.frameX)
        self.txtPointX.setMinimumSize(QtCore.QSize(100, 0))
        self.txtPointX.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPointX.setFont(font)
        self.txtPointX.setObjectName(_fromUtf8("txtPointX"))
        self.hLayoutX.addWidget(self.txtPointX)
        self.vLayoutXY.addWidget(self.frameX)
        self.frameY = QtGui.QFrame(self.frameXY)
        self.frameY.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameY.setFrameShadow(QtGui.QFrame.Raised)
        self.frameY.setObjectName(_fromUtf8("frameY"))
        self.hLayoutY = QtGui.QHBoxLayout(self.frameY)
        self.hLayoutY.setSpacing(0)
        self.hLayoutY.setMargin(0)
        self.hLayoutY.setObjectName(_fromUtf8("hLayoutY"))
        self.labelY = QtGui.QLabel(self.frameY)
        self.labelY.setMinimumSize(QtCore.QSize(50, 0))
        self.labelY.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelY.setFont(font)
        self.labelY.setObjectName(_fromUtf8("labelY"))
        self.hLayoutY.addWidget(self.labelY)
        self.txtPointY = QtGui.QLineEdit(self.frameY)
        self.txtPointY.setMinimumSize(QtCore.QSize(100, 0))
        self.txtPointY.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPointY.setFont(font)
        self.txtPointY.setObjectName(_fromUtf8("txtPointY"))
        self.hLayoutY.addWidget(self.txtPointY)
        self.vLayoutXY.addWidget(self.frameY)
        self.hLayoutXYLL.addWidget(self.frameXY)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hLayoutXYLL.addItem(spacerItem2)
        self.vLayoutPositionContents.addWidget(self.frameXY_LL)
        self.frameAlitude = QtGui.QFrame(self.framePositionContents)
        self.frameAlitude.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameAlitude.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAlitude.setObjectName(_fromUtf8("frameAlitude"))
        self.hLayoutAltitude = QtGui.QHBoxLayout(self.frameAlitude)
        self.hLayoutAltitude.setSpacing(0)
        self.hLayoutAltitude.setMargin(0)
        self.hLayoutAltitude.setObjectName(_fromUtf8("hLayoutAltitude"))
        self.labelAltitude = QtGui.QLabel(self.frameAlitude)
        self.labelAltitude.setMinimumSize(QtCore.QSize(50, 0))
        self.labelAltitude.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelAltitude.setFont(font)
        self.labelAltitude.setObjectName(_fromUtf8("labelAltitude"))
        self.hLayoutAltitude.addWidget(self.labelAltitude)
        self.frameAltitudeVal = QtGui.QFrame(self.frameAlitude)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameAltitudeVal.sizePolicy().hasHeightForWidth())
        self.frameAltitudeVal.setSizePolicy(sizePolicy)
        self.frameAltitudeVal.setMinimumSize(QtCore.QSize(0, 0))
        self.frameAltitudeVal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameAltitudeVal.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAltitudeVal.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAltitudeVal.setObjectName(_fromUtf8("frameAltitudeVal"))
        self.hLayoutAltitudeVal = QtGui.QHBoxLayout(self.frameAltitudeVal)
        self.hLayoutAltitudeVal.setSpacing(0)
        self.hLayoutAltitudeVal.setMargin(0)
        self.hLayoutAltitudeVal.setObjectName(_fromUtf8("hLayoutAltitudeVal"))
        self.txtAltitudeM = QtGui.QLineEdit(self.frameAltitudeVal)
        self.txtAltitudeM.setMinimumSize(QtCore.QSize(100, 20))
        self.txtAltitudeM.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitudeM.setFont(font)
        self.txtAltitudeM.setObjectName(_fromUtf8("txtAltitudeM"))
        self.hLayoutAltitudeVal.addWidget(self.txtAltitudeM)
        self.labelM = QtGui.QLabel(self.frameAltitudeVal)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelM.setFont(font)
        self.labelM.setObjectName(_fromUtf8("labelM"))
        self.hLayoutAltitudeVal.addWidget(self.labelM)
        self.txtAltitudeFt = QtGui.QLineEdit(self.frameAltitudeVal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAltitudeFt.sizePolicy().hasHeightForWidth())
        self.txtAltitudeFt.setSizePolicy(sizePolicy)
        self.txtAltitudeFt.setMinimumSize(QtCore.QSize(100, 20))
        self.txtAltitudeFt.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitudeFt.setFont(font)
        self.txtAltitudeFt.setObjectName(_fromUtf8("txtAltitudeFt"))
        self.hLayoutAltitudeVal.addWidget(self.txtAltitudeFt)
        self.labelFt = QtGui.QLabel(self.frameAltitudeVal)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelFt.setFont(font)
        self.labelFt.setObjectName(_fromUtf8("labelFt"))
        self.hLayoutAltitudeVal.addWidget(self.labelFt)
        self.hLayoutAltitude.addWidget(self.frameAltitudeVal)
        spacerItem3 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hLayoutAltitude.addItem(spacerItem3)
        self.vLayoutPositionContents.addWidget(self.frameAlitude)
        self.hLayout_basicFrame.addWidget(self.framePositionContents)
        self.btnCapture = QtGui.QPushButton(self.basicFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCapture.sizePolicy().hasHeightForWidth())
        self.btnCapture.setSizePolicy(sizePolicy)
        self.btnCapture.setMinimumSize(QtCore.QSize(25, 0))
        self.btnCapture.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btnCapture.setText(_fromUtf8(""))
        self.btnCapture.setObjectName(_fromUtf8("btnCapture"))
        self.hLayout_basicFrame.addWidget(self.btnCapture)
        self.btnCalculater = QtGui.QPushButton(self.basicFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCalculater.sizePolicy().hasHeightForWidth())
        self.btnCalculater.setSizePolicy(sizePolicy)
        self.btnCalculater.setMinimumSize(QtCore.QSize(25, 0))
        self.btnCalculater.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btnCalculater.setText(_fromUtf8(""))
        self.btnCalculater.setObjectName(_fromUtf8("btnCalculater"))
        self.hLayout_basicFrame.addWidget(self.btnCalculater)
        self.hLayoutGroupBox.addWidget(self.basicFrame)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hLayoutGroupBox.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.groupBox)

        self.frameLL = Frame(self.frameXY_LL)
        self.frameLL.Spacing = 3
        self.frameXY_LL.Add = self.frameLL

        self.txtLat = TextBoxPanel(self.frameLL)
        self.txtLat.Caption = "Latitude"
        self.txtLat.LabelWidth = 60
        self.txtLat.textBox.setMaximumWidth(100)
        self.txtLat.textBox.setMinimumWidth(100)
        self.frameLL.Add = self.txtLat

        self.txtLong = TextBoxPanel(self.frameLL)
        self.txtLong.Caption = "Longitude"
        self.txtLong.LabelWidth = 60
        self.txtLong.textBox.setMaximumWidth(100)
        self.txtLong.textBox.setMinimumWidth(100)
        self.frameLL.Add = self.txtLong

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.labelID.setText(_translate("Form", "ID :", None))
        self.labelX.setText(_translate("Form", "X :", None))
        self.labelY.setText(_translate("Form", "Y :", None))
        self.labelAltitude.setText(_translate("Form", "Altitude:", None))
        self.labelM.setText(_translate("Form", "m", None))
        self.labelFt.setText(_translate("Form", "ft", None))

