# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RnavTolerancesPanel.ui'
#
# Created: Wed Apr 23 10:06:05 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(403, 94)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_Tolerance = QtGui.QFrame(Form)
        self.frame_Tolerance.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Tolerance.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Tolerance.setObjectName(_fromUtf8("frame_Tolerance"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_Tolerance)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame_2 = QtGui.QFrame(self.frame_Tolerance)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_Att = QtGui.QFrame(self.frame_2)
        self.frame_Att.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_Att.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Att.setObjectName(_fromUtf8("frame_Att"))
        self.horizontalLayout_70 = QtGui.QHBoxLayout(self.frame_Att)
        self.horizontalLayout_70.setSpacing(0)
        self.horizontalLayout_70.setMargin(0)
        self.horizontalLayout_70.setObjectName(_fromUtf8("horizontalLayout_70"))
        self.label_78 = QtGui.QLabel(self.frame_Att)
        self.label_78.setMinimumSize(QtCore.QSize(240, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_78.setFont(font)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.horizontalLayout_70.addWidget(self.label_78)
        self.frame_APV_12 = QtGui.QFrame(self.frame_Att)
        self.frame_APV_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_12.setObjectName(_fromUtf8("frame_APV_12"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.frame_APV_12)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.txtAtt = QtGui.QLineEdit(self.frame_APV_12)
        self.txtAtt.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAtt.setFont(font)
        self.txtAtt.setObjectName(_fromUtf8("txtAtt"))
        self.horizontalLayout_16.addWidget(self.txtAtt)
        self.horizontalLayout_70.addWidget(self.frame_APV_12)
        self.verticalLayout_3.addWidget(self.frame_Att)
        self.frame_Xtt = QtGui.QFrame(self.frame_2)
        self.frame_Xtt.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_Xtt.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Xtt.setObjectName(_fromUtf8("frame_Xtt"))
        self.horizontalLayout_72 = QtGui.QHBoxLayout(self.frame_Xtt)
        self.horizontalLayout_72.setSpacing(0)
        self.horizontalLayout_72.setMargin(0)
        self.horizontalLayout_72.setObjectName(_fromUtf8("horizontalLayout_72"))
        self.label_80 = QtGui.QLabel(self.frame_Xtt)
        self.label_80.setMinimumSize(QtCore.QSize(240, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_80.setFont(font)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.horizontalLayout_72.addWidget(self.label_80)
        self.frame_APV_14 = QtGui.QFrame(self.frame_Xtt)
        self.frame_APV_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_14.setObjectName(_fromUtf8("frame_APV_14"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.frame_APV_14)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.txtXtt = QtGui.QLineEdit(self.frame_APV_14)
        self.txtXtt.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtXtt.setFont(font)
        self.txtXtt.setObjectName(_fromUtf8("txtXtt"))
        self.horizontalLayout_18.addWidget(self.txtXtt)
        self.horizontalLayout_72.addWidget(self.frame_APV_14)
        self.verticalLayout_3.addWidget(self.frame_Xtt)
        self.frame_Aws = QtGui.QFrame(self.frame_2)
        self.frame_Aws.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_Aws.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Aws.setObjectName(_fromUtf8("frame_Aws"))
        self.horizontalLayout_71 = QtGui.QHBoxLayout(self.frame_Aws)
        self.horizontalLayout_71.setSpacing(0)
        self.horizontalLayout_71.setMargin(0)
        self.horizontalLayout_71.setObjectName(_fromUtf8("horizontalLayout_71"))
        self.label_79 = QtGui.QLabel(self.frame_Aws)
        self.label_79.setMinimumSize(QtCore.QSize(240, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_79.setFont(font)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.horizontalLayout_71.addWidget(self.label_79)
        self.frame_APV_13 = QtGui.QFrame(self.frame_Aws)
        self.frame_APV_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_13.setObjectName(_fromUtf8("frame_APV_13"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.frame_APV_13)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.txtAsw = QtGui.QLineEdit(self.frame_APV_13)
        self.txtAsw.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAsw.setFont(font)
        self.txtAsw.setObjectName(_fromUtf8("txtAsw"))
        self.horizontalLayout_17.addWidget(self.txtAsw)
        self.horizontalLayout_71.addWidget(self.frame_APV_13)
        self.verticalLayout_3.addWidget(self.frame_Aws)
        self.horizontalLayout.addWidget(self.frame_2)
        self.btnDropDown = QtGui.QToolButton(self.frame_Tolerance)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDropDown.sizePolicy().hasHeightForWidth())
        self.btnDropDown.setSizePolicy(sizePolicy)
        self.btnDropDown.setMinimumSize(QtCore.QSize(0, 0))
        self.btnDropDown.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnDropDown.setText(_fromUtf8(""))
        self.btnDropDown.setObjectName(_fromUtf8("btnDropDown"))
        self.horizontalLayout.addWidget(self.btnDropDown)
        self.verticalLayout.addWidget(self.frame_Tolerance)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_78.setText(_translate("Form", "ATT (nm):", None))
        self.txtAtt.setText(_translate("Form", "180", None))
        self.label_80.setText(_translate("Form", "XTT (nm):", None))
        self.txtXtt.setText(_translate("Form", "180", None))
        self.label_79.setText(_translate("Form", "1/2 A/W (nm):", None))
        self.txtAsw.setText(_translate("Form", "180", None))

