# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BaroVNavDlg.ui'
#
# Created: Wed Mar 25 13:45:48 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BaroV_Dialog(object):
    def setupUi(self, BaroV_Dialog):
        BaroV_Dialog.setObjectName(_fromUtf8("BaroV_Dialog"))
        BaroV_Dialog.resize(678, 663)
        self.horizontalLayout = QtGui.QHBoxLayout(BaroV_Dialog)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabBaroV = QtGui.QTabWidget(BaroV_Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.tabBaroV.setFont(font)
        self.tabBaroV.setAutoFillBackground(False)
        self.tabBaroV.setStyleSheet(_fromUtf8(""))
        self.tabBaroV.setObjectName(_fromUtf8("tabBaroV"))
        self.tab_General = QtGui.QWidget()
        self.tab_General.setObjectName(_fromUtf8("tab_General"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.tab_General)
        self.horizontalLayout_29.setMargin(3)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_General)
        self.groupBox_11.setTitle(_fromUtf8(""))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_11.setFont(font)
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_5.setMargin(5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frame_33 = QtGui.QFrame(self.groupBox_11)
        self.frame_33.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_33.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_33.setObjectName(_fromUtf8("frame_33"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.frame_33)
        self.horizontalLayout_30.setSpacing(3)
        self.horizontalLayout_30.setMargin(0)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.groupBox_22 = QtGui.QGroupBox(self.frame_33)
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_22)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_23 = QtGui.QGroupBox(self.groupBox_22)
        self.groupBox_23.setObjectName(_fromUtf8("groupBox_23"))
        self.horizontalLayout_61 = QtGui.QHBoxLayout(self.groupBox_23)
        self.horizontalLayout_61.setSpacing(0)
        self.horizontalLayout_61.setMargin(0)
        self.horizontalLayout_61.setObjectName(_fromUtf8("horizontalLayout_61"))
        self.frame_68 = QtGui.QFrame(self.groupBox_23)
        self.frame_68.setMinimumSize(QtCore.QSize(60, 0))
        self.frame_68.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_68.setBaseSize(QtCore.QSize(60, 0))
        self.frame_68.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_68.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_68.setObjectName(_fromUtf8("frame_68"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame_68)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_71 = QtGui.QLabel(self.frame_68)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_71.setFont(font)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.verticalLayout_10.addWidget(self.label_71)
        self.label_72 = QtGui.QLabel(self.frame_68)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.verticalLayout_10.addWidget(self.label_72)
        self.label_73 = QtGui.QLabel(self.frame_68)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.verticalLayout_10.addWidget(self.label_73)
        self.horizontalLayout_61.addWidget(self.frame_68)
        self.frame_4 = QtGui.QFrame(self.groupBox_23)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.txtARPX = QtGui.QLineEdit(self.frame_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtARPX.setFont(font)
        self.txtARPX.setObjectName(_fromUtf8("txtARPX"))
        self.verticalLayout_11.addWidget(self.txtARPX)
        self.txtARPY = QtGui.QLineEdit(self.frame_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtARPY.setFont(font)
        self.txtARPY.setObjectName(_fromUtf8("txtARPY"))
        self.verticalLayout_11.addWidget(self.txtARPY)
        self.frame_70 = QtGui.QFrame(self.frame_4)
        self.frame_70.setMinimumSize(QtCore.QSize(60, 22))
        self.frame_70.setMaximumSize(QtCore.QSize(180, 16777215))
        self.frame_70.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_70.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_70.setObjectName(_fromUtf8("frame_70"))
        self.horizontalLayout_62 = QtGui.QHBoxLayout(self.frame_70)
        self.horizontalLayout_62.setSpacing(0)
        self.horizontalLayout_62.setMargin(0)
        self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        self.txtARPAltM = QtGui.QLineEdit(self.frame_70)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtARPAltM.setFont(font)
        self.txtARPAltM.setObjectName(_fromUtf8("txtARPAltM"))
        self.horizontalLayout_62.addWidget(self.txtARPAltM)
        self.label_74 = QtGui.QLabel(self.frame_70)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_62.addWidget(self.label_74)
        self.txtARPAltFt = QtGui.QLineEdit(self.frame_70)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtARPAltFt.setFont(font)
        self.txtARPAltFt.setObjectName(_fromUtf8("txtARPAltFt"))
        self.horizontalLayout_62.addWidget(self.txtARPAltFt)
        self.label_75 = QtGui.QLabel(self.frame_70)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.horizontalLayout_62.addWidget(self.label_75)
        self.verticalLayout_11.addWidget(self.frame_70)
        self.horizontalLayout_61.addWidget(self.frame_4)
        self.btnCaptureCoordARP = QtGui.QToolButton(self.groupBox_23)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCaptureCoordARP.sizePolicy().hasHeightForWidth())
        self.btnCaptureCoordARP.setSizePolicy(sizePolicy)
        self.btnCaptureCoordARP.setMaximumSize(QtCore.QSize(16777215, 81))
        self.btnCaptureCoordARP.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCaptureCoordARP.setIcon(icon)
        self.btnCaptureCoordARP.setObjectName(_fromUtf8("btnCaptureCoordARP"))
        self.horizontalLayout_61.addWidget(self.btnCaptureCoordARP)
        self.verticalLayout_2.addWidget(self.groupBox_23)
        self.frame_72 = QtGui.QFrame(self.groupBox_22)
        self.frame_72.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_72.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_72.setObjectName(_fromUtf8("frame_72"))
        self.horizontalLayout_63 = QtGui.QHBoxLayout(self.frame_72)
        self.horizontalLayout_63.setSpacing(0)
        self.horizontalLayout_63.setContentsMargins(2, 0, 0, 0)
        self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        self.label_76 = QtGui.QLabel(self.frame_72)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_76.setFont(font)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.horizontalLayout_63.addWidget(self.label_76)
        self.txtMinTemperature = QtGui.QLineEdit(self.frame_72)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMinTemperature.setFont(font)
        self.txtMinTemperature.setObjectName(_fromUtf8("txtMinTemperature"))
        self.horizontalLayout_63.addWidget(self.txtMinTemperature)
        self.verticalLayout_2.addWidget(self.frame_72)
        self.horizontalLayout_30.addWidget(self.groupBox_22)
        self.groupBox_18 = QtGui.QGroupBox(self.frame_33)
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_18)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_19 = QtGui.QGroupBox(self.groupBox_18)
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.horizontalLayout_43 = QtGui.QHBoxLayout(self.groupBox_19)
        self.horizontalLayout_43.setSpacing(0)
        self.horizontalLayout_43.setMargin(0)
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.frame_48 = QtGui.QFrame(self.groupBox_19)
        self.frame_48.setMinimumSize(QtCore.QSize(60, 0))
        self.frame_48.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_48.setBaseSize(QtCore.QSize(60, 0))
        self.frame_48.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_48.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_48.setObjectName(_fromUtf8("frame_48"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_48)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_48 = QtGui.QLabel(self.frame_48)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.verticalLayout_8.addWidget(self.label_48)
        self.label_49 = QtGui.QLabel(self.frame_48)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.verticalLayout_8.addWidget(self.label_49)
        self.label_50 = QtGui.QLabel(self.frame_48)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.verticalLayout_8.addWidget(self.label_50)
        self.horizontalLayout_43.addWidget(self.frame_48)
        self.frame_5 = QtGui.QFrame(self.groupBox_19)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.txtThrX = QtGui.QLineEdit(self.frame_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtThrX.setFont(font)
        self.txtThrX.setObjectName(_fromUtf8("txtThrX"))
        self.verticalLayout_9.addWidget(self.txtThrX)
        self.txtThrY = QtGui.QLineEdit(self.frame_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtThrY.setFont(font)
        self.txtThrY.setObjectName(_fromUtf8("txtThrY"))
        self.verticalLayout_9.addWidget(self.txtThrY)
        self.frame_50 = QtGui.QFrame(self.frame_5)
        self.frame_50.setMinimumSize(QtCore.QSize(60, 22))
        self.frame_50.setMaximumSize(QtCore.QSize(180, 16777215))
        self.frame_50.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_50.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_50.setObjectName(_fromUtf8("frame_50"))
        self.horizontalLayout_44 = QtGui.QHBoxLayout(self.frame_50)
        self.horizontalLayout_44.setSpacing(0)
        self.horizontalLayout_44.setMargin(0)
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        self.txtThrAltM = QtGui.QLineEdit(self.frame_50)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtThrAltM.setFont(font)
        self.txtThrAltM.setObjectName(_fromUtf8("txtThrAltM"))
        self.horizontalLayout_44.addWidget(self.txtThrAltM)
        self.label_51 = QtGui.QLabel(self.frame_50)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.horizontalLayout_44.addWidget(self.label_51)
        self.txtThrAltFt = QtGui.QLineEdit(self.frame_50)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtThrAltFt.setFont(font)
        self.txtThrAltFt.setObjectName(_fromUtf8("txtThrAltFt"))
        self.horizontalLayout_44.addWidget(self.txtThrAltFt)
        self.label_52 = QtGui.QLabel(self.frame_50)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.horizontalLayout_44.addWidget(self.label_52)
        self.verticalLayout_9.addWidget(self.frame_50)
        self.horizontalLayout_43.addWidget(self.frame_5)
        self.btnCaptureCoordThr = QtGui.QToolButton(self.groupBox_19)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCaptureCoordThr.sizePolicy().hasHeightForWidth())
        self.btnCaptureCoordThr.setSizePolicy(sizePolicy)
        self.btnCaptureCoordThr.setMaximumSize(QtCore.QSize(16777215, 81))
        self.btnCaptureCoordThr.setIcon(icon)
        self.btnCaptureCoordThr.setObjectName(_fromUtf8("btnCaptureCoordThr"))
        self.horizontalLayout_43.addWidget(self.btnCaptureCoordThr)
        self.verticalLayout.addWidget(self.groupBox_19)
        self.frame_52 = QtGui.QFrame(self.groupBox_18)
        self.frame_52.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_52.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_52.setObjectName(_fromUtf8("frame_52"))
        self.horizontalLayout_45 = QtGui.QHBoxLayout(self.frame_52)
        self.horizontalLayout_45.setSpacing(0)
        self.horizontalLayout_45.setMargin(0)
        self.horizontalLayout_45.setObjectName(_fromUtf8("horizontalLayout_45"))
        self.label_53 = QtGui.QLabel(self.frame_52)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_53.setFont(font)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.horizontalLayout_45.addWidget(self.label_53)
        self.txtRwyDir = QtGui.QLineEdit(self.frame_52)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtRwyDir.setFont(font)
        self.txtRwyDir.setObjectName(_fromUtf8("txtRwyDir"))
        self.horizontalLayout_45.addWidget(self.txtRwyDir)
        self.btnCaptureDirRwy = QtGui.QToolButton(self.frame_52)
#         self.btnCaptureDirRwy.setMinimumSize(QtCore.QSize(0, 23))
        self.btnCaptureDirRwy.setIcon(icon)
        self.btnCaptureDirRwy.setObjectName(_fromUtf8("btnCaptureDirRwy"))
        self.horizontalLayout_45.addWidget(self.btnCaptureDirRwy)
        self.verticalLayout.addWidget(self.frame_52)
        self.horizontalLayout_30.addWidget(self.groupBox_18)
        self.verticalLayout_5.addWidget(self.frame_33)
        self.frame_37 = QtGui.QFrame(self.groupBox_11)
        self.frame_37.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_37.setObjectName(_fromUtf8("frame_37"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_37)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_20 = QtGui.QGroupBox(self.frame_37)
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_20)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_53 = QtGui.QFrame(self.groupBox_20)
        self.frame_53.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_53.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_53.setObjectName(_fromUtf8("frame_53"))
        self.horizontalLayout_46 = QtGui.QHBoxLayout(self.frame_53)
        self.horizontalLayout_46.setSpacing(0)
        self.horizontalLayout_46.setMargin(0)
        self.horizontalLayout_46.setObjectName(_fromUtf8("horizontalLayout_46"))
        self.label_54 = QtGui.QLabel(self.frame_53)
        self.label_54.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.horizontalLayout_46.addWidget(self.label_54)
        self.cmbISType = QtGui.QComboBox(self.frame_53)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbISType.setFont(font)
        self.cmbISType.setObjectName(_fromUtf8("cmbISType"))
        self.horizontalLayout_46.addWidget(self.cmbISType)
        self.txtISHeight = QtGui.QLineEdit(self.frame_53)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtISHeight.setFont(font)
        self.txtISHeight.setObjectName(_fromUtf8("txtISHeight"))
        self.horizontalLayout_46.addWidget(self.txtISHeight)
        self.verticalLayout_3.addWidget(self.frame_53)
        self.frame_54 = QtGui.QFrame(self.groupBox_20)
        self.frame_54.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_54.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_54.setObjectName(_fromUtf8("frame_54"))
        self.horizontalLayout_47 = QtGui.QHBoxLayout(self.frame_54)
        self.horizontalLayout_47.setSpacing(0)
        self.horizontalLayout_47.setMargin(0)
        self.horizontalLayout_47.setObjectName(_fromUtf8("horizontalLayout_47"))
        self.label_55 = QtGui.QLabel(self.frame_54)
        self.label_55.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.horizontalLayout_47.addWidget(self.label_55)
        self.txtISMoc = QtGui.QLineEdit(self.frame_54)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtISMoc.setFont(font)
        self.txtISMoc.setObjectName(_fromUtf8("txtISMoc"))
        self.horizontalLayout_47.addWidget(self.txtISMoc)
        self.verticalLayout_3.addWidget(self.frame_54)
        self.frame_55 = QtGui.QFrame(self.groupBox_20)
        self.frame_55.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_55.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_55.setObjectName(_fromUtf8("frame_55"))
        self.horizontalLayout_48 = QtGui.QHBoxLayout(self.frame_55)
        self.horizontalLayout_48.setSpacing(0)
        self.horizontalLayout_48.setMargin(0)
        self.horizontalLayout_48.setObjectName(_fromUtf8("horizontalLayout_48"))
        self.label_56 = QtGui.QLabel(self.frame_55)
        self.label_56.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.horizontalLayout_48.addWidget(self.label_56)
        self.txtRDHatTHR = QtGui.QLineEdit(self.frame_55)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtRDHatTHR.setFont(font)
        self.txtRDHatTHR.setObjectName(_fromUtf8("txtRDHatTHR"))
        self.horizontalLayout_48.addWidget(self.txtRDHatTHR)
        self.verticalLayout_3.addWidget(self.frame_55)
        self.frame_56 = QtGui.QFrame(self.groupBox_20)
        self.frame_56.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_56.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_56.setObjectName(_fromUtf8("frame_56"))
        self.horizontalLayout_49 = QtGui.QHBoxLayout(self.frame_56)
        self.horizontalLayout_49.setSpacing(0)
        self.horizontalLayout_49.setMargin(0)
        self.horizontalLayout_49.setObjectName(_fromUtf8("horizontalLayout_49"))
        self.label_57 = QtGui.QLabel(self.frame_56)
        self.label_57.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.horizontalLayout_49.addWidget(self.label_57)
        self.cmbVerticalPathAngle = QtGui.QComboBox(self.frame_56)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbVerticalPathAngle.sizePolicy().hasHeightForWidth())
        self.cmbVerticalPathAngle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbVerticalPathAngle.setFont(font)
        self.cmbVerticalPathAngle.setObjectName(_fromUtf8("cmbVerticalPathAngle"))
        self.horizontalLayout_49.addWidget(self.cmbVerticalPathAngle)
        self.verticalLayout_3.addWidget(self.frame_56)
        self.frame_57 = QtGui.QFrame(self.groupBox_20)
        self.frame_57.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_57.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_57.setObjectName(_fromUtf8("frame_57"))
        self.horizontalLayout_50 = QtGui.QHBoxLayout(self.frame_57)
        self.horizontalLayout_50.setSpacing(0)
        self.horizontalLayout_50.setMargin(0)
        self.horizontalLayout_50.setObjectName(_fromUtf8("horizontalLayout_50"))
        self.label_58 = QtGui.QLabel(self.frame_57)
        self.label_58.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.horizontalLayout_50.addWidget(self.label_58)
        self.txtTHRtoFAWP = QtGui.QLineEdit(self.frame_57)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtTHRtoFAWP.setFont(font)
        self.txtTHRtoFAWP.setObjectName(_fromUtf8("txtTHRtoFAWP"))
        self.horizontalLayout_50.addWidget(self.txtTHRtoFAWP)
        self.verticalLayout_3.addWidget(self.frame_57)
        self.frame_58 = QtGui.QFrame(self.groupBox_20)
        self.frame_58.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_58.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_58.setObjectName(_fromUtf8("frame_58"))
        self.horizontalLayout_51 = QtGui.QHBoxLayout(self.frame_58)
        self.horizontalLayout_51.setSpacing(0)
        self.horizontalLayout_51.setMargin(0)
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.label_59 = QtGui.QLabel(self.frame_58)
        self.label_59.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_59.setFont(font)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.horizontalLayout_51.addWidget(self.label_59)
        self.cmbAircraftCategory = QtGui.QComboBox(self.frame_58)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAircraftCategory.sizePolicy().hasHeightForWidth())
        self.cmbAircraftCategory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbAircraftCategory.setFont(font)
        self.cmbAircraftCategory.setObjectName(_fromUtf8("cmbAircraftCategory"))
        self.horizontalLayout_51.addWidget(self.cmbAircraftCategory)
        self.verticalLayout_3.addWidget(self.frame_58)
        self.frame_59 = QtGui.QFrame(self.groupBox_20)
        self.frame_59.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_59.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_59.setObjectName(_fromUtf8("frame_59"))
        self.horizontalLayout_52 = QtGui.QHBoxLayout(self.frame_59)
        self.horizontalLayout_52.setSpacing(0)
        self.horizontalLayout_52.setMargin(0)
        self.horizontalLayout_52.setObjectName(_fromUtf8("horizontalLayout_52"))
        self.label_60 = QtGui.QLabel(self.frame_59)
        self.label_60.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_60.setFont(font)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.horizontalLayout_52.addWidget(self.label_60)
        self.txtMaxIAS = QtGui.QLineEdit(self.frame_59)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMaxIAS.setFont(font)
        self.txtMaxIAS.setObjectName(_fromUtf8("txtMaxIAS"))
        self.horizontalLayout_52.addWidget(self.txtMaxIAS)
        self.verticalLayout_3.addWidget(self.frame_59)
        self.frame_64 = QtGui.QFrame(self.groupBox_20)
        self.frame_64.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_64.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_64.setObjectName(_fromUtf8("frame_64"))
        self.horizontalLayout_57 = QtGui.QHBoxLayout(self.frame_64)
        self.horizontalLayout_57.setSpacing(0)
        self.horizontalLayout_57.setMargin(0)
        self.horizontalLayout_57.setObjectName(_fromUtf8("horizontalLayout_57"))
        self.label_67 = QtGui.QLabel(self.frame_64)
        self.label_67.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.horizontalLayout_57.addWidget(self.label_67)
        self.txtMaxIASatTHR = QtGui.QLineEdit(self.frame_64)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMaxIASatTHR.setFont(font)
        self.txtMaxIASatTHR.setObjectName(_fromUtf8("txtMaxIASatTHR"))
        self.horizontalLayout_57.addWidget(self.txtMaxIASatTHR)
        self.verticalLayout_3.addWidget(self.frame_64)
        self.frame_62 = QtGui.QFrame(self.groupBox_20)
        self.frame_62.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_62.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_62.setObjectName(_fromUtf8("frame_62"))
        self.horizontalLayout_55 = QtGui.QHBoxLayout(self.frame_62)
        self.horizontalLayout_55.setSpacing(0)
        self.horizontalLayout_55.setMargin(0)
        self.horizontalLayout_55.setObjectName(_fromUtf8("horizontalLayout_55"))
        self.label_64 = QtGui.QLabel(self.frame_62)
        self.label_64.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_64.setFont(font)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.horizontalLayout_55.addWidget(self.label_64)
        self.txtHeightLoss = QtGui.QLineEdit(self.frame_62)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtHeightLoss.setFont(font)
        self.txtHeightLoss.setObjectName(_fromUtf8("txtHeightLoss"))
        self.horizontalLayout_55.addWidget(self.txtHeightLoss)
        self.verticalLayout_3.addWidget(self.frame_62)
        self.frame_61 = QtGui.QFrame(self.groupBox_20)
        self.frame_61.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_61.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_61.setObjectName(_fromUtf8("frame_61"))
        self.horizontalLayout_54 = QtGui.QHBoxLayout(self.frame_61)
        self.horizontalLayout_54.setSpacing(0)
        self.horizontalLayout_54.setMargin(0)
        self.horizontalLayout_54.setObjectName(_fromUtf8("horizontalLayout_54"))
        self.label_62 = QtGui.QLabel(self.frame_61)
        self.label_62.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_62.setFont(font)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.horizontalLayout_54.addWidget(self.label_62)
        self.cmbAPV = QtGui.QComboBox(self.frame_61)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbAPV.setFont(font)
        self.cmbAPV.setObjectName(_fromUtf8("cmbAPV"))
        self.horizontalLayout_54.addWidget(self.cmbAPV)
        self.frame_APV = QtGui.QFrame(self.frame_61)
        self.frame_APV.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV.setObjectName(_fromUtf8("frame_APV"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_APV)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_63 = QtGui.QLabel(self.frame_APV)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_63.setFont(font)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.horizontalLayout_5.addWidget(self.label_63)
        self.txtAPV = QtGui.QLineEdit(self.frame_APV)
        self.txtAPV.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAPV.setFont(font)
        self.txtAPV.setObjectName(_fromUtf8("txtAPV"))
        self.horizontalLayout_5.addWidget(self.txtAPV)
        self.btnAPV = QtGui.QToolButton(self.frame_APV)
#         self.btnAPV.setMinimumSize(QtCore.QSize(0, 23))
        self.btnAPV.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAPV.setIcon(icon1)
        self.btnAPV.setObjectName(_fromUtf8("btnAPV"))
        self.horizontalLayout_5.addWidget(self.btnAPV)
        self.horizontalLayout_54.addWidget(self.frame_APV)
        self.verticalLayout_3.addWidget(self.frame_61)
        self.frame_63 = QtGui.QFrame(self.groupBox_20)
        self.frame_63.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_63.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_63.setObjectName(_fromUtf8("frame_63"))
        self.horizontalLayout_56 = QtGui.QHBoxLayout(self.frame_63)
        self.horizontalLayout_56.setSpacing(0)
        self.horizontalLayout_56.setMargin(0)
        self.horizontalLayout_56.setObjectName(_fromUtf8("horizontalLayout_56"))
        self.label_65 = QtGui.QLabel(self.frame_63)
        self.label_65.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_65.setFont(font)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.horizontalLayout_56.addWidget(self.label_65)
        self.cmbMissedAppPoint = QtGui.QComboBox(self.frame_63)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbMissedAppPoint.setFont(font)
        self.cmbMissedAppPoint.setObjectName(_fromUtf8("cmbMissedAppPoint"))
        self.horizontalLayout_56.addWidget(self.cmbMissedAppPoint)
        self.frame_MissApPt = QtGui.QFrame(self.frame_63)
        self.frame_MissApPt.setEnabled(True)
        self.frame_MissApPt.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_MissApPt.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_MissApPt.setObjectName(_fromUtf8("frame_MissApPt"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_MissApPt)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_66 = QtGui.QLabel(self.frame_MissApPt)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.horizontalLayout_6.addWidget(self.label_66)
        self.txtMissedAppPoint = QtGui.QLineEdit(self.frame_MissApPt)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMissedAppPoint.setFont(font)
        self.txtMissedAppPoint.setText(_fromUtf8(""))
        self.txtMissedAppPoint.setObjectName(_fromUtf8("txtMissedAppPoint"))
        self.horizontalLayout_6.addWidget(self.txtMissedAppPoint)
        self.btnMAPoint = QtGui.QToolButton(self.frame_MissApPt)
#         self.btnMAPoint.setMinimumSize(QtCore.QSize(0, 23))
        self.btnMAPoint.setText(_fromUtf8(""))
        self.btnMAPoint.setIcon(icon1)
        self.btnMAPoint.setObjectName(_fromUtf8("btnMAPoint"))
        self.horizontalLayout_6.addWidget(self.btnMAPoint)
        self.horizontalLayout_56.addWidget(self.frame_MissApPt)
        self.verticalLayout_3.addWidget(self.frame_63)
        self.frame_60 = QtGui.QFrame(self.groupBox_20)
        self.frame_60.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_60.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_60.setObjectName(_fromUtf8("frame_60"))
        self.horizontalLayout_53 = QtGui.QHBoxLayout(self.frame_60)
        self.horizontalLayout_53.setSpacing(0)
        self.horizontalLayout_53.setMargin(0)
        self.horizontalLayout_53.setObjectName(_fromUtf8("horizontalLayout_53"))
        self.label_61 = QtGui.QLabel(self.frame_60)
        self.label_61.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_61.setFont(font)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.horizontalLayout_53.addWidget(self.label_61)
        self.txtMissedAppClimb = QtGui.QLineEdit(self.frame_60)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMissedAppClimb.setFont(font)
        self.txtMissedAppClimb.setObjectName(_fromUtf8("txtMissedAppClimb"))
        self.horizontalLayout_53.addWidget(self.txtMissedAppClimb)
        self.verticalLayout_3.addWidget(self.frame_60)
        self.frame_66 = QtGui.QFrame(self.groupBox_20)
        self.frame_66.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_66.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_66.setObjectName(_fromUtf8("frame_66"))
        self.horizontalLayout_59 = QtGui.QHBoxLayout(self.frame_66)
        self.horizontalLayout_59.setSpacing(0)
        self.horizontalLayout_59.setMargin(0)
        self.horizontalLayout_59.setObjectName(_fromUtf8("horizontalLayout_59"))
        self.label_69 = QtGui.QLabel(self.frame_66)
        self.label_69.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.horizontalLayout_59.addWidget(self.label_69)
        self.txtMissedAppMOC = QtGui.QLineEdit(self.frame_66)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMissedAppMOC.setFont(font)
        self.txtMissedAppMOC.setObjectName(_fromUtf8("txtMissedAppMOC"))
        self.horizontalLayout_59.addWidget(self.txtMissedAppMOC)
        self.verticalLayout_3.addWidget(self.frame_66)
        self.frame_65 = QtGui.QFrame(self.groupBox_20)
        self.frame_65.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_65.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_65.setObjectName(_fromUtf8("frame_65"))
        self.horizontalLayout_58 = QtGui.QHBoxLayout(self.frame_65)
        self.horizontalLayout_58.setSpacing(0)
        self.horizontalLayout_58.setMargin(0)
        self.horizontalLayout_58.setObjectName(_fromUtf8("horizontalLayout_58"))
        self.label_68 = QtGui.QLabel(self.frame_65)
        self.label_68.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_58.addWidget(self.label_68)
        self.cmbMissedAppEvalution = QtGui.QComboBox(self.frame_65)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMissedAppEvalution.sizePolicy().hasHeightForWidth())
        self.cmbMissedAppEvalution.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbMissedAppEvalution.setFont(font)
        self.cmbMissedAppEvalution.setObjectName(_fromUtf8("cmbMissedAppEvalution"))
        self.horizontalLayout_58.addWidget(self.cmbMissedAppEvalution)
        self.verticalLayout_3.addWidget(self.frame_65)
        self.frame_67 = QtGui.QFrame(self.groupBox_20)
        self.frame_67.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_67.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_67.setObjectName(_fromUtf8("frame_67"))
        self.horizontalLayout_60 = QtGui.QHBoxLayout(self.frame_67)
        self.horizontalLayout_60.setSpacing(0)
        self.horizontalLayout_60.setMargin(0)
        self.horizontalLayout_60.setObjectName(_fromUtf8("horizontalLayout_60"))
        self.label_70 = QtGui.QLabel(self.frame_67)
        self.label_70.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.horizontalLayout_60.addWidget(self.label_70)
        self.cmbConstructionType = QtGui.QComboBox(self.frame_67)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConstructionType.sizePolicy().hasHeightForWidth())
        self.cmbConstructionType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbConstructionType.setFont(font)
        self.cmbConstructionType.setObjectName(_fromUtf8("cmbConstructionType"))
        self.horizontalLayout_60.addWidget(self.cmbConstructionType)
        self.verticalLayout_3.addWidget(self.frame_67)
        self.horizontalLayout_2.addWidget(self.groupBox_20)
        self.verticalLayout_5.addWidget(self.frame_37)
        self.horizontalLayout_29.addWidget(self.groupBox_11)
        self.frame_38 = QtGui.QFrame(self.tab_General)
        self.frame_38.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_38.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_38.setObjectName(_fromUtf8("frame_38"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_38)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.btnOpenData = QtGui.QPushButton(self.frame_38)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnOpenData.setFont(font)
        self.btnOpenData.setObjectName(_fromUtf8("btnOpenData"))
        self.btnOpenData.setToolTip(_fromUtf8("Open Data"))
        self.verticalLayout_7.addWidget(self.btnOpenData)
        self.btnSaveData = QtGui.QPushButton(self.frame_38)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnSaveData.setFont(font)
        self.btnSaveData.setObjectName(_fromUtf8("btnSaveData"))
        self.btnSaveData.setToolTip(_fromUtf8("Save Data"))
        self.verticalLayout_7.addWidget(self.btnSaveData)
        self.btnConstruct = QtGui.QPushButton(self.frame_38)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnConstruct.setFont(font)
        self.btnConstruct.setObjectName(_fromUtf8("btnConstruct"))
        self.btnConstruct.setToolTip(_fromUtf8("Constuct"))
        self.verticalLayout_7.addWidget(self.btnConstruct)
        self.btnPDCheck = QtGui.QPushButton(self.frame_38)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPDCheck.setFont(font)
        self.btnPDCheck.setObjectName(_fromUtf8("btnPDCheck"))
        self.btnPDCheck.setToolTip(_fromUtf8("PDT Check"))
        self.verticalLayout_7.addWidget(self.btnPDCheck)
        self.btnUpdateQA = QtGui.QPushButton(self.frame_38)
        self.btnUpdateQA.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnUpdateQA.setFont(font)
        self.btnUpdateQA.setObjectName(_fromUtf8("btnUpdateQA"))
        self.verticalLayout_7.addWidget(self.btnUpdateQA)
        self.btnEvaluate = QtGui.QPushButton(self.frame_38)
        self.btnEvaluate.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnEvaluate.setFont(font)
        self.btnEvaluate.setObjectName(_fromUtf8("btnEvaluate"))
        self.btnEvaluate.setToolTip(_fromUtf8("Evaluate"))
        self.verticalLayout_7.addWidget(self.btnEvaluate)
        self.btnClose = QtGui.QPushButton(self.frame_38)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnClose.setFont(font)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.btnClose.setToolTip(_fromUtf8("Close"))
        self.verticalLayout_7.addWidget(self.btnClose)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout_29.addWidget(self.frame_38)
        self.tabBaroV.addTab(self.tab_General, _fromUtf8(""))
        self.tab_Results = QtGui.QWidget()
        self.tab_Results.setObjectName(_fromUtf8("tab_Results"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_Results)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setMargin(3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.tab_Results)
        self.groupBox.setFont(font)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setMargin(3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_32 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_32.setObjectName(_fromUtf8("groupBox_32"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_32)
        self.verticalLayout_16.setContentsMargins(-1, 0, -1, 3)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.frame_2 = QtGui.QFrame(self.groupBox_32)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_19.setMargin(0)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.frame_107 = QtGui.QFrame(self.frame_3)
        self.frame_107.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_107.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_107.setObjectName(_fromUtf8("frame_107"))
        self.horizontalLayout_94 = QtGui.QHBoxLayout(self.frame_107)
        self.horizontalLayout_94.setSpacing(0)
        self.horizontalLayout_94.setMargin(0)
        self.horizontalLayout_94.setObjectName(_fromUtf8("horizontalLayout_94"))
        self.label_115 = QtGui.QLabel(self.frame_107)
        self.label_115.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_115.setFont(font)
        self.label_115.setObjectName(_fromUtf8("label_115"))
        self.horizontalLayout_94.addWidget(self.label_115)
        self.txtID = QtGui.QLineEdit(self.frame_107)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.txtID.setFont(font)
        self.txtID.setObjectName(_fromUtf8("txtID"))
        self.horizontalLayout_94.addWidget(self.txtID)
        self.verticalLayout_19.addWidget(self.frame_107)
        self.frame_109 = QtGui.QFrame(self.frame_3)
        self.frame_109.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_109.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_109.setObjectName(_fromUtf8("frame_109"))
        self.horizontalLayout_96 = QtGui.QHBoxLayout(self.frame_109)
        self.horizontalLayout_96.setSpacing(0)
        self.horizontalLayout_96.setMargin(0)
        self.horizontalLayout_96.setObjectName(_fromUtf8("horizontalLayout_96"))
        self.label_119 = QtGui.QLabel(self.frame_109)
        self.label_119.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_119.setFont(font)
        self.label_119.setObjectName(_fromUtf8("label_119"))
        self.horizontalLayout_96.addWidget(self.label_119)
        self.txtX = QtGui.QLineEdit(self.frame_109)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.txtX.setFont(font)
        self.txtX.setObjectName(_fromUtf8("txtX"))
        self.horizontalLayout_96.addWidget(self.txtX)
        self.verticalLayout_19.addWidget(self.frame_109)
        self.frame_110 = QtGui.QFrame(self.frame_3)
        self.frame_110.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_110.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_110.setObjectName(_fromUtf8("frame_110"))
        self.horizontalLayout_97 = QtGui.QHBoxLayout(self.frame_110)
        self.horizontalLayout_97.setSpacing(0)
        self.horizontalLayout_97.setMargin(0)
        self.horizontalLayout_97.setObjectName(_fromUtf8("horizontalLayout_97"))
        self.label_120 = QtGui.QLabel(self.frame_110)
        self.label_120.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_120.setFont(font)
        self.label_120.setObjectName(_fromUtf8("label_120"))
        self.horizontalLayout_97.addWidget(self.label_120)
        self.txtY = QtGui.QLineEdit(self.frame_110)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.txtY.setFont(font)
        self.txtY.setObjectName(_fromUtf8("txtY"))
        self.horizontalLayout_97.addWidget(self.txtY)
        self.verticalLayout_19.addWidget(self.frame_110)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.toolButton = QtGui.QToolButton(self.frame_2)
        self.toolButton.setMaximumSize(QtCore.QSize(25, 250))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/mActionZoomFullExtent.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon2)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_4.addWidget(self.toolButton)
        self.verticalLayout_16.addWidget(self.frame_2)
        self.frame_108 = QtGui.QFrame(self.groupBox_32)
        self.frame_108.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_108.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_108.setObjectName(_fromUtf8("frame_108"))
        self.horizontalLayout_95 = QtGui.QHBoxLayout(self.frame_108)
        self.horizontalLayout_95.setSpacing(0)
        self.horizontalLayout_95.setMargin(0)
        self.horizontalLayout_95.setObjectName(_fromUtf8("horizontalLayout_95"))
        self.label_116 = QtGui.QLabel(self.frame_108)
        self.label_116.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_116.setFont(font)
        self.label_116.setObjectName(_fromUtf8("label_116"))
        self.horizontalLayout_95.addWidget(self.label_116)
        self.txtAltitude = QtGui.QLineEdit(self.frame_108)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.txtAltitude.setFont(font)
        self.txtAltitude.setObjectName(_fromUtf8("txtAltitude"))
        self.horizontalLayout_95.addWidget(self.txtAltitude)
        self.label_117 = QtGui.QLabel(self.frame_108)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_117.setFont(font)
        self.label_117.setObjectName(_fromUtf8("label_117"))
        self.horizontalLayout_95.addWidget(self.label_117)
        self.txtAltitudeM = QtGui.QLineEdit(self.frame_108)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.txtAltitudeM.setFont(font)
        self.txtAltitudeM.setObjectName(_fromUtf8("txtAltitudeM"))
        self.horizontalLayout_95.addWidget(self.txtAltitudeM)
        self.label_118 = QtGui.QLabel(self.frame_108)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_118.setFont(font)
        self.label_118.setObjectName(_fromUtf8("label_118"))
        self.horizontalLayout_95.addWidget(self.label_118)
        self.verticalLayout_16.addWidget(self.frame_108)
        self.frame_111 = QtGui.QFrame(self.groupBox_32)
        self.frame_111.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_111.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_111.setObjectName(_fromUtf8("frame_111"))
        self.horizontalLayout_98 = QtGui.QHBoxLayout(self.frame_111)
        self.horizontalLayout_98.setSpacing(0)
        self.horizontalLayout_98.setMargin(0)
        self.horizontalLayout_98.setObjectName(_fromUtf8("horizontalLayout_98"))
        self.label_121 = QtGui.QLabel(self.frame_111)
        self.label_121.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_121.setFont(font)
        self.label_121.setObjectName(_fromUtf8("label_121"))
        self.horizontalLayout_98.addWidget(self.label_121)
        self.txtSurface = QtGui.QLineEdit(self.frame_111)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.txtSurface.setFont(font)
        self.txtSurface.setObjectName(_fromUtf8("txtSurface"))
        self.horizontalLayout_98.addWidget(self.txtSurface)
        self.verticalLayout_16.addWidget(self.frame_111)
        self.verticalLayout_6.addWidget(self.groupBox_32)
        self.groupBox_33 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_33.setObjectName(_fromUtf8("groupBox_33"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.groupBox_33)
        self.verticalLayout_17.setContentsMargins(-1, 0, -1, 3)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.frame_112 = QtGui.QFrame(self.groupBox_33)
        self.frame_112.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_112.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_112.setObjectName(_fromUtf8("frame_112"))
        self.horizontalLayout_99 = QtGui.QHBoxLayout(self.frame_112)
        self.horizontalLayout_99.setSpacing(0)
        self.horizontalLayout_99.setMargin(0)
        self.horizontalLayout_99.setObjectName(_fromUtf8("horizontalLayout_99"))
        self.label_122 = QtGui.QLabel(self.frame_112)
        self.label_122.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_122.setFont(font)
        self.label_122.setObjectName(_fromUtf8("label_122"))
        self.horizontalLayout_99.addWidget(self.label_122)
        self.cmbUnits = QtGui.QComboBox(self.frame_112)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbUnits.sizePolicy().hasHeightForWidth())
        self.cmbUnits.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.cmbUnits.setFont(font)
        self.cmbUnits.setEditable(False)
        self.cmbUnits.setObjectName(_fromUtf8("cmbUnits"))
        self.horizontalLayout_99.addWidget(self.cmbUnits)
        self.verticalLayout_17.addWidget(self.frame_112)
        self.frame_113 = QtGui.QFrame(self.groupBox_33)
        self.frame_113.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_113.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_113.setObjectName(_fromUtf8("frame_113"))
        self.horizontalLayout_100 = QtGui.QHBoxLayout(self.frame_113)
        self.horizontalLayout_100.setSpacing(0)
        self.horizontalLayout_100.setMargin(0)
        self.horizontalLayout_100.setObjectName(_fromUtf8("horizontalLayout_100"))
        self.txtOCH = QtGui.QLineEdit(self.frame_113)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.txtOCH.setFont(font)
        self.txtOCH.setObjectName(_fromUtf8("txtOCH"))
        self.horizontalLayout_100.addWidget(self.txtOCH)
        self.txtOCHResults = QtGui.QLineEdit(self.frame_113)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.txtOCHResults.setFont(font)
        self.txtOCHResults.setObjectName(_fromUtf8("txtOCHResults"))
        self.horizontalLayout_100.addWidget(self.txtOCHResults)
        self.verticalLayout_17.addWidget(self.frame_113)
        self.frame_114 = QtGui.QFrame(self.groupBox_33)
        self.frame_114.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_114.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_114.setObjectName(_fromUtf8("frame_114"))
        self.horizontalLayout_101 = QtGui.QHBoxLayout(self.frame_114)
        self.horizontalLayout_101.setSpacing(0)
        self.horizontalLayout_101.setMargin(0)
        self.horizontalLayout_101.setObjectName(_fromUtf8("horizontalLayout_101"))
        self.txtOCA = QtGui.QLineEdit(self.frame_114)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.txtOCA.setFont(font)
        self.txtOCA.setObjectName(_fromUtf8("txtOCA"))
        self.horizontalLayout_101.addWidget(self.txtOCA)
        self.txtOCAResults = QtGui.QLineEdit(self.frame_114)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.txtOCAResults.setFont(font)
        self.txtOCAResults.setObjectName(_fromUtf8("txtOCAResults"))
        self.horizontalLayout_101.addWidget(self.txtOCAResults)
        self.verticalLayout_17.addWidget(self.frame_114)
        self.verticalLayout_6.addWidget(self.groupBox_33)
        self.groupBox_34 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_34.setObjectName(_fromUtf8("groupBox_34"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.groupBox_34)
        self.verticalLayout_18.setContentsMargins(-1, 0, -1, 3)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.frame_115 = QtGui.QFrame(self.groupBox_34)
        self.frame_115.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_115.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_115.setObjectName(_fromUtf8("frame_115"))
        self.horizontalLayout_102 = QtGui.QHBoxLayout(self.frame_115)
        self.horizontalLayout_102.setSpacing(0)
        self.horizontalLayout_102.setMargin(0)
        self.horizontalLayout_102.setObjectName(_fromUtf8("horizontalLayout_102"))
        self.label_123 = QtGui.QLabel(self.frame_115)
        self.label_123.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_123.setFont(font)
        self.label_123.setObjectName(_fromUtf8("label_123"))
        self.horizontalLayout_102.addWidget(self.label_123)
        self.cmbSurface = QtGui.QComboBox(self.frame_115)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSurface.sizePolicy().hasHeightForWidth())
        self.cmbSurface.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.cmbSurface.setFont(font)
        self.cmbSurface.setObjectName(_fromUtf8("cmbSurface"))
        self.horizontalLayout_102.addWidget(self.cmbSurface)
        self.verticalLayout_18.addWidget(self.frame_115)
        self.tblObstacles = QtGui.QTableView(self.groupBox_34)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.tblObstacles.setFont(font)
        self.tblObstacles.setObjectName(_fromUtf8("tblObstacles"))
        self.verticalLayout_18.addWidget(self.tblObstacles)
        self.verticalLayout_6.addWidget(self.groupBox_34)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.frame = QtGui.QFrame(self.tab_Results)
#         self.frame.setMinimumSize(QtCore.QSize(105, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.btnEvaluate_2 = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnEvaluate_2.setFont(font)
        self.btnEvaluate_2.setObjectName(_fromUtf8("btnEvaluate_2"))
#         self.btnClose.setToolTip(_fromUtf8("Close"))
        self.verticalLayout_4.addWidget(self.btnEvaluate_2)
        self.btnUpdateQA_2 = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnUpdateQA_2.setFont(font)
        self.btnUpdateQA_2.setObjectName(_fromUtf8("btnUpdateQA_2"))
        self.verticalLayout_4.addWidget(self.btnUpdateQA_2)
        self.btnClose_2 = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnClose_2.setFont(font)
        self.btnClose_2.setObjectName(_fromUtf8("btnClose_2"))
        self.btnClose_2.setToolTip(_fromUtf8("Close"))
#         sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.cmbSurface.sizePolicy().hasHeightForWidth())
#         self.btnClose_2.setSizePolicy(sizePolicy)
        self.verticalLayout_4.addWidget(self.btnClose_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.frame)
        self.tabBaroV.addTab(self.tab_Results, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabBaroV)
        
        self.btnUpdateQA_2.setToolTip(_fromUtf8("Export Result"))
        self.btnEvaluate_2.setToolTip(_fromUtf8("Locate"))
        
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/openData.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpenData.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/saveData.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveData.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/construct.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConstruct.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/evaluate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEvaluate.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/locate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEvaluate_2.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/pdtCheck.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPDCheck.setIcon(icon)
        icon = QtGui.QIcon()        
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose_2.setIcon(icon)
        self.iconEvaluate = QtGui.QIcon()        
        self.iconEvaluate.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/exportResult.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        
        self.retranslateUi(BaroV_Dialog)
        self.tabBaroV.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BaroV_Dialog)

    def retranslateUi(self, BaroV_Dialog):
        BaroV_Dialog.setWindowTitle(_translate("BaroV_Dialog", "APV/Baro-VNAV Surfaces", None))
        self.groupBox_22.setTitle(_translate("BaroV_Dialog", "Aerodrome", None))
        self.groupBox_23.setTitle(_translate("BaroV_Dialog", "Reference Point(ARP)", None))
        self.label_71.setText(_translate("BaroV_Dialog", "X:", None))
        self.label_72.setText(_translate("BaroV_Dialog", "Y:", None))
        self.label_73.setText(_translate("BaroV_Dialog", "Altitude:", None))
        self.label_74.setText(_translate("BaroV_Dialog", "m", None))
        self.label_75.setText(_translate("BaroV_Dialog", "ft", None))
        self.label_76.setText(_translate("BaroV_Dialog", "MinimumTemperature(°):", None))
        self.groupBox_18.setTitle(_translate("BaroV_Dialog", "Runway", None))
        self.groupBox_19.setTitle(_translate("BaroV_Dialog", "Threshold Position", None))
        self.label_48.setText(_translate("BaroV_Dialog", "X:", None))
        self.label_49.setText(_translate("BaroV_Dialog", "Y:", None))
        self.label_50.setText(_translate("BaroV_Dialog", "Altitude:", None))
        self.label_51.setText(_translate("BaroV_Dialog", "m", None))
        self.label_52.setText(_translate("BaroV_Dialog", "ft", None))
#         self.btnCaptureCoordThr.setText(_translate("BaroV_Dialog", "...", None))
        self.label_53.setText(_translate("BaroV_Dialog", "Direction(°):", None))
#         self.btnCaptureDirRwy.setText(_translate("BaroV_Dialog", "...", None))
        self.groupBox_20.setTitle(_translate("BaroV_Dialog", "Parameters", None))
        self.label_54.setText(_translate("BaroV_Dialog", "Intermediate Segment(ft):", None))
        self.label_55.setText(_translate("BaroV_Dialog", "Intermediate Segment MOC(m):", None))
        self.label_56.setText(_translate("BaroV_Dialog", "RDH at THR(m):", None))
        self.label_57.setText(_translate("BaroV_Dialog", "Vertical Path Angle [VPA]:", None))
        self.label_58.setText(_translate("BaroV_Dialog", "THR to FAWP Distance (nm):", None))
        self.label_59.setText(_translate("BaroV_Dialog", "Aircraft Category:", None))
        self.label_60.setText(_translate("BaroV_Dialog", "Max. IAS (kts):", None))
        self.label_67.setText(_translate("BaroV_Dialog", "Max. IAS at THR (kts):", None))
        self.label_64.setText(_translate("BaroV_Dialog", "Height Loss (m):", None))
        self.label_62.setText(_translate("BaroV_Dialog", "APV Segment Termination:", None))
        self.label_63.setText(_translate("BaroV_Dialog", " Dist. (nm): ", None))
        self.label_65.setText(_translate("BaroV_Dialog", "Missed Approach Point:", None))
        self.label_66.setText(_translate("BaroV_Dialog", " Dist. (nm): ", None))
        self.label_61.setText(_translate("BaroV_Dialog", "Missed Approach Climb Gradient (%):", None))
        self.label_69.setText(_translate("BaroV_Dialog", "Missed Approach MOC (m):", None))
        self.label_68.setText(_translate("BaroV_Dialog", "Missed Approach Evaluation:", None))
        self.label_70.setText(_translate("BaroV_Dialog", "Construction Type:", None))
#         self.btnOpenData.setText(_translate("BaroV_Dialog", "OpenData", None))
#         self.btnSaveData.setText(_translate("BaroV_Dialog", "SaveData", None))
#         self.btnConstruct.setText(_translate("BaroV_Dialog", "Construct", None))
#         self.btnPDCheck.setText(_translate("BaroV_Dialog", "PDCheck", None))
#         self.btnUpdateQA.setText(_translate("BaroV_Dialog", "Update QA", None))
#         self.btnEvaluate.setText(_translate("BaroV_Dialog", "Evaluate", None))
#         self.btnClose.setText(_translate("BaroV_Dialog", "Close", None))
        self.tabBaroV.setTabText(self.tabBaroV.indexOf(self.tab_General), _translate("BaroV_Dialog", "General", None))
        self.groupBox_32.setTitle(_translate("BaroV_Dialog", "The Most Critical Obstacle", None))
        self.label_115.setText(_translate("BaroV_Dialog", "ID:", None))
        self.label_119.setText(_translate("BaroV_Dialog", "X:", None))
        self.label_120.setText(_translate("BaroV_Dialog", "Y:", None))
        self.toolButton.setText(_translate("BaroV_Dialog", "...", None))
        self.label_116.setText(_translate("BaroV_Dialog", "Altitude:", None))
        self.label_117.setText(_translate("BaroV_Dialog", " m ", None))
        self.label_118.setText(_translate("BaroV_Dialog", "ft", None))
        self.label_121.setText(_translate("BaroV_Dialog", "Surface:", None))
        self.groupBox_33.setTitle(_translate("BaroV_Dialog", "Results", None))
        self.label_122.setText(_translate("BaroV_Dialog", "Units:", None))
        self.groupBox_34.setTitle(_translate("BaroV_Dialog", "Checked Ostacles", None))
        self.label_123.setText(_translate("BaroV_Dialog", "Surface:", None))
#         self.btnEvaluate_2.setText(_translate("BaroV_Dialog", "Locate", None))
#         self.btnUpdateQA_2.setText(_translate("BaroV_Dialog", "Update QA", None))
#         self.btnClose_2.setText(_translate("BaroV_Dialog", "Close", None))
        self.tabBaroV.setTabText(self.tabBaroV.indexOf(self.tab_Results), _translate("BaroV_Dialog", "Results/Checked Obstacles", None))

