# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FlightPlannerBaseDifferentTab.ui'
#
# Created: Fri Jan 29 09:43:00 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FlightPlannerBaseDifferentTab(object):
    def setupUi(self, FlightPlannerBaseDifferentTab):
        FlightPlannerBaseDifferentTab.setObjectName(_fromUtf8("FlightPlannerBaseDifferentTab"))
        FlightPlannerBaseDifferentTab.resize(685, 663)
        self.horizontalLayout = QtGui.QHBoxLayout(FlightPlannerBaseDifferentTab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabCtrlGeneral = QtGui.QTabWidget(FlightPlannerBaseDifferentTab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.tabCtrlGeneral.setFont(font)
        self.tabCtrlGeneral.setAutoFillBackground(False)
        self.tabCtrlGeneral.setStyleSheet(_fromUtf8(""))
        self.tabCtrlGeneral.setObjectName(_fromUtf8("tabCtrlGeneral"))
        self.tab_General = QtGui.QWidget(FlightPlannerBaseDifferentTab)
        self.tab_General.setObjectName(_fromUtf8("tab_General"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.tab_General)
        self.horizontalLayout_29.setMargin(3)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.grbGeneral = QtGui.QGroupBox(self.tab_General)
        self.grbGeneral.setTitle(_fromUtf8(""))
        self.grbGeneral.setObjectName(_fromUtf8("grbGeneral"))
        self.vlGeneral = QtGui.QVBoxLayout(self.grbGeneral)
        self.vlGeneral.setMargin(5)
        self.vlGeneral.setObjectName(_fromUtf8("vlGeneral"))
        self.horizontalLayout_29.addWidget(self.grbGeneral)
        self.frmGeneralButtons = QtGui.QFrame(self.tab_General)
        self.frmGeneralButtons.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frmGeneralButtons.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmGeneralButtons.setFrameShadow(QtGui.QFrame.Raised)
        self.frmGeneralButtons.setObjectName(_fromUtf8("frmGeneralButtons"))
        self.vlGeneralBtns = QtGui.QVBoxLayout(self.frmGeneralButtons)
        self.vlGeneralBtns.setObjectName(_fromUtf8("vlGeneralBtns"))
        self.btnOpenData = QtGui.QPushButton(self.frmGeneralButtons)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnOpenData.setFont(font)
        self.btnOpenData.setObjectName(_fromUtf8("btnOpenData"))
        self.vlGeneralBtns.addWidget(self.btnOpenData)
        self.btnSaveData = QtGui.QPushButton(self.frmGeneralButtons)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnSaveData.setFont(font)
        self.btnSaveData.setObjectName(_fromUtf8("btnSaveData"))
        self.vlGeneralBtns.addWidget(self.btnSaveData)
        self.btnConstruct = QtGui.QPushButton(self.frmGeneralButtons)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnConstruct.setFont(font)
        self.btnConstruct.setObjectName(_fromUtf8("btnConstruct"))
        self.vlGeneralBtns.addWidget(self.btnConstruct)
        self.btnPDTCheck = QtGui.QPushButton(self.frmGeneralButtons)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPDTCheck.setFont(font)
        self.btnPDTCheck.setObjectName(_fromUtf8("btnPDTCheck"))
        self.vlGeneralBtns.addWidget(self.btnPDTCheck)
        self.btnEvaluate = QtGui.QPushButton(self.frmGeneralButtons)
        self.btnEvaluate.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnEvaluate.setFont(font)
        self.btnEvaluate.setObjectName(_fromUtf8("btnEvaluate"))
        self.vlGeneralBtns.addWidget(self.btnEvaluate)
        self.btnExportResult = QtGui.QPushButton(self.frmGeneralButtons)
        self.btnExportResult.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnExportResult.setFont(font)
        self.btnExportResult.setObjectName(_fromUtf8("btnExportResult"))
        self.vlGeneralBtns.addWidget(self.btnExportResult)
        self.btnClose = QtGui.QPushButton(self.frmGeneralButtons)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnClose.setFont(font)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.vlGeneralBtns.addWidget(self.btnClose)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vlGeneralBtns.addItem(spacerItem)
        self.horizontalLayout_29.addWidget(self.frmGeneralButtons)
        self.tabCtrlGeneral.addTab(self.tab_General, _fromUtf8(""))
        self.tab_Results = QtGui.QWidget(FlightPlannerBaseDifferentTab)
        self.tab_Results.setObjectName(_fromUtf8("tab_Results"))
        self.hlResults = QtGui.QHBoxLayout(self.tab_Results)
        self.hlResults.setSpacing(3)
        self.hlResults.setMargin(3)
        self.hlResults.setObjectName(_fromUtf8("hlResults"))
        self.grbResult = QtGui.QGroupBox(self.tab_Results)
        self.grbResult.setTitle(_fromUtf8(""))
        self.grbResult.setObjectName(_fromUtf8("grbResult"))
        self.vlResultGroup = QtGui.QVBoxLayout(self.grbResult)
        self.vlResultGroup.setMargin(3)
        self.vlResultGroup.setObjectName(_fromUtf8("vlResultGroup"))
        self.hlResults.addWidget(self.grbResult)
        self.frmGeneralButtons_2 = QtGui.QFrame(self.tab_Results)
        self.frmGeneralButtons_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frmGeneralButtons_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmGeneralButtons_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frmGeneralButtons_2.setObjectName(_fromUtf8("frmGeneralButtons_2"))
        self.vlGeneralBtns_2 = QtGui.QVBoxLayout(self.frmGeneralButtons_2)
        self.vlGeneralBtns_2.setObjectName(_fromUtf8("vlGeneralBtns_2"))
        self.btnOpenData_2 = QtGui.QPushButton(self.frmGeneralButtons_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnOpenData_2.setFont(font)
        self.btnOpenData_2.setObjectName(_fromUtf8("btnOpenData_2"))
        self.vlGeneralBtns_2.addWidget(self.btnOpenData_2)
        self.btnSaveData_2 = QtGui.QPushButton(self.frmGeneralButtons_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnSaveData_2.setFont(font)
        self.btnSaveData_2.setObjectName(_fromUtf8("btnSaveData_2"))
        self.vlGeneralBtns_2.addWidget(self.btnSaveData_2)
        self.btnConstruct_2 = QtGui.QPushButton(self.frmGeneralButtons_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnConstruct_2.setFont(font)
        self.btnConstruct_2.setObjectName(_fromUtf8("btnConstruct_2"))
        self.vlGeneralBtns_2.addWidget(self.btnConstruct_2)
        self.btnEvaluate_2 = QtGui.QPushButton(self.frmGeneralButtons_2)
        self.btnEvaluate_2.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnEvaluate_2.setFont(font)
        self.btnEvaluate_2.setObjectName(_fromUtf8("btnEvaluate_2"))
        self.vlGeneralBtns_2.addWidget(self.btnEvaluate_2)
        self.btnExportResult_2 = QtGui.QPushButton(self.frmGeneralButtons_2)
        self.btnExportResult_2.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnExportResult_2.setFont(font)
        self.btnExportResult_2.setObjectName(_fromUtf8("btnExportResult_2"))
        self.vlGeneralBtns_2.addWidget(self.btnExportResult_2)
        self.btnClose_2 = QtGui.QPushButton(self.frmGeneralButtons_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnClose_2.setFont(font)
        self.btnClose_2.setObjectName(_fromUtf8("btnClose_2"))
        self.vlGeneralBtns_2.addWidget(self.btnClose_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vlGeneralBtns_2.addItem(spacerItem1)
        self.hlResults.addWidget(self.frmGeneralButtons_2)
        self.tabCtrlGeneral.addTab(self.tab_Results, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabCtrlGeneral)

        self.retranslateUi(FlightPlannerBaseDifferentTab)
        self.tabCtrlGeneral.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FlightPlannerBaseDifferentTab)

    def retranslateUi(self, FlightPlannerBaseDifferentTab):
        FlightPlannerBaseDifferentTab.setWindowTitle(_translate("FlightPlannerBaseDifferentTab", "APV/Baro-VNAV Surfaces", None))
        self.btnOpenData.setText(_translate("FlightPlannerBaseDifferentTab", "Open Data", None))
        self.btnSaveData.setText(_translate("FlightPlannerBaseDifferentTab", "Save Data", None))
        self.btnConstruct.setText(_translate("FlightPlannerBaseDifferentTab", "Construct", None))
        self.btnPDTCheck.setText(_translate("FlightPlannerBaseDifferentTab", "PDT Check", None))
        self.btnEvaluate.setText(_translate("FlightPlannerBaseDifferentTab", "Evaluate", None))
        self.btnExportResult.setText(_translate("FlightPlannerBaseDifferentTab", "Export Result", None))
        self.btnClose.setText(_translate("FlightPlannerBaseDifferentTab", "Close", None))
        self.tabCtrlGeneral.setTabText(self.tabCtrlGeneral.indexOf(self.tab_General), _translate("FlightPlannerBaseDifferentTab", "1", None))
        self.btnOpenData_2.setText(_translate("FlightPlannerBaseDifferentTab", "Open Data", None))
        self.btnSaveData_2.setText(_translate("FlightPlannerBaseDifferentTab", "Save Data", None))
        self.btnConstruct_2.setText(_translate("FlightPlannerBaseDifferentTab", "Construct", None))
        self.btnEvaluate_2.setText(_translate("FlightPlannerBaseDifferentTab", "Evaluate", None))
        self.btnExportResult_2.setText(_translate("FlightPlannerBaseDifferentTab", "Export Result", None))
        self.btnClose_2.setText(_translate("FlightPlannerBaseDifferentTab", "Close", None))
        self.tabCtrlGeneral.setTabText(self.tabCtrlGeneral.indexOf(self.tab_Results), _translate("FlightPlannerBaseDifferentTab", "2", None))

import Resources_rc
