# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_RnavDmeDme.ui'
#
# Created: Tue Jul 07 16:22:27 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RnavDmeDme(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(474, 484)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbParameters = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.gbParameters.setFont(font)
        self.gbParameters.setObjectName(_fromUtf8("gbParameters"))
        self.vl_gbParameters = QtGui.QVBoxLayout(self.gbParameters)
        self.vl_gbParameters.setObjectName(_fromUtf8("vl_gbParameters"))
        self.frame_58 = QtGui.QFrame(self.gbParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_58.sizePolicy().hasHeightForWidth())
        self.frame_58.setSizePolicy(sizePolicy)
        self.frame_58.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_58.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_58.setObjectName(_fromUtf8("frame_58"))
        self.horizontalLayout_58 = QtGui.QHBoxLayout(self.frame_58)
        self.horizontalLayout_58.setSpacing(0)
        self.horizontalLayout_58.setMargin(0)
        self.horizontalLayout_58.setObjectName(_fromUtf8("horizontalLayout_58"))
        self.label_66 = QtGui.QLabel(self.frame_58)
        self.label_66.setMinimumSize(QtCore.QSize(200, 0))
#         self.label_66.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.horizontalLayout_58.addWidget(self.label_66)
        self.cmbRnavSpecification = QtGui.QComboBox(self.frame_58)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRnavSpecification.sizePolicy().hasHeightForWidth())
        self.cmbRnavSpecification.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbRnavSpecification.setFont(font)
        self.cmbRnavSpecification.setObjectName(_fromUtf8("cmbRnavSpecification"))
        self.horizontalLayout_58.addWidget(self.cmbRnavSpecification)
        self.vl_gbParameters.addWidget(self.frame_58)
        self.frame_59 = QtGui.QFrame(self.gbParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_59.sizePolicy().hasHeightForWidth())
        self.frame_59.setSizePolicy(sizePolicy)
        self.frame_59.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_59.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_59.setObjectName(_fromUtf8("frame_59"))
        self.horizontalLayout_59 = QtGui.QHBoxLayout(self.frame_59)
        self.horizontalLayout_59.setSpacing(0)
        self.horizontalLayout_59.setMargin(0)
        self.horizontalLayout_59.setObjectName(_fromUtf8("horizontalLayout_59"))
        self.label_67 = QtGui.QLabel(self.frame_59)
        self.label_67.setMinimumSize(QtCore.QSize(200, 0))
#         self.label_67.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.horizontalLayout_59.addWidget(self.label_67)
        self.cmbDmeCount = QtGui.QComboBox(self.frame_59)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDmeCount.sizePolicy().hasHeightForWidth())
        self.cmbDmeCount.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbDmeCount.setFont(font)
        self.cmbDmeCount.setObjectName(_fromUtf8("cmbDmeCount"))
        self.horizontalLayout_59.addWidget(self.cmbDmeCount)
        self.vl_gbParameters.addWidget(self.frame_59)
        self.chbUse2Waypoints = QtGui.QCheckBox(self.gbParameters)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbUse2Waypoints.setFont(font)
        self.chbUse2Waypoints.setObjectName(_fromUtf8("chbUse2Waypoints"))
        self.vl_gbParameters.addWidget(self.chbUse2Waypoints)
#         self.gbVorDmePosition = QtGui.QGroupBox(self.gbParameters)
#         font = QtGui.QFont()
#         font.setBold(False)
#         font.setWeight(50)
#         self.gbVorDmePosition.setFont(font)
#         self.gbVorDmePosition.setObjectName(_fromUtf8("gbVorDmePosition"))
#         self.verticalLayoutVoeDmePosition = QtGui.QVBoxLayout(self.gbVorDmePosition)
#         self.verticalLayoutVoeDmePosition.setObjectName(_fromUtf8("verticalLayoutVoeDmePosition"))
#         self.vl_gbParameters.addWidget(self.gbVorDmePosition)
        self.gbWaypoint1 = QtGui.QGroupBox(self.gbParameters)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.gbWaypoint1.setFont(font)
        self.gbWaypoint1.setObjectName(_fromUtf8("gbWaypoint1"))
        self.verticalLayoutWaypoint1 = QtGui.QVBoxLayout(self.gbWaypoint1)
        self.verticalLayoutWaypoint1.setObjectName(_fromUtf8("verticalLayoutWaypoint1"))
        self.frame_60 = QtGui.QFrame(self.gbWaypoint1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_60.sizePolicy().hasHeightForWidth())
        self.frame_60.setSizePolicy(sizePolicy)
        self.frame_60.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_60.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_60.setObjectName(_fromUtf8("frame_60"))
        self.horizontalLayout_62 = QtGui.QHBoxLayout(self.frame_60)
        self.horizontalLayout_62.setSpacing(0)
        self.horizontalLayout_62.setMargin(0)
        self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        self.label_70 = QtGui.QLabel(self.frame_60)
        self.label_70.setMinimumSize(QtCore.QSize(190, 0))
#         self.label_70.setMaximumSize(QtCore.QSize(190, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.horizontalLayout_62.addWidget(self.label_70)
        self.cmbFlightPhase1 = QtGui.QComboBox(self.frame_60)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFlightPhase1.sizePolicy().hasHeightForWidth())
        self.cmbFlightPhase1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbFlightPhase1.setFont(font)
        self.cmbFlightPhase1.setObjectName(_fromUtf8("cmbFlightPhase1"))
        self.horizontalLayout_62.addWidget(self.cmbFlightPhase1)
        self.verticalLayoutWaypoint1.addWidget(self.frame_60)
        self.frame_Altitude = QtGui.QFrame(self.gbWaypoint1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Altitude.sizePolicy().hasHeightForWidth())
        self.frame_Altitude.setSizePolicy(sizePolicy)
        self.frame_Altitude.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Altitude.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Altitude.setObjectName(_fromUtf8("frame_Altitude"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.frame_Altitude)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setMargin(0)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_17 = QtGui.QLabel(self.frame_Altitude)
        self.label_17.setMinimumSize(QtCore.QSize(190, 0))
#         self.label_17.setMaximumSize(QtCore.QSize(190, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_27.addWidget(self.label_17)
        self.txtAltitude1 = QtGui.QLineEdit(self.frame_Altitude)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAltitude1.sizePolicy().hasHeightForWidth())
        self.txtAltitude1.setSizePolicy(sizePolicy)
        self.txtAltitude1.setMinimumSize(QtCore.QSize(105, 0))
        self.txtAltitude1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitude1.setFont(font)
        self.txtAltitude1.setObjectName(_fromUtf8("txtAltitude1"))
        self.horizontalLayout_27.addWidget(self.txtAltitude1)
        self.verticalLayoutWaypoint1.addWidget(self.frame_Altitude)
        self.vl_gbParameters.addWidget(self.gbWaypoint1)
        self.gbWaypoint2 = QtGui.QGroupBox(self.gbParameters)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.gbWaypoint2.setFont(font)
        self.gbWaypoint2.setObjectName(_fromUtf8("gbWaypoint2"))
        self.verticalLayoutWaypoint2 = QtGui.QVBoxLayout(self.gbWaypoint2)
        self.verticalLayoutWaypoint2.setObjectName(_fromUtf8("verticalLayoutWaypoint2"))
        self.frame_61 = QtGui.QFrame(self.gbWaypoint2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_61.sizePolicy().hasHeightForWidth())
        self.frame_61.setSizePolicy(sizePolicy)
        self.frame_61.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_61.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_61.setObjectName(_fromUtf8("frame_61"))
        self.horizontalLayout_64 = QtGui.QHBoxLayout(self.frame_61)
        self.horizontalLayout_64.setSpacing(0)
        self.horizontalLayout_64.setMargin(0)
        self.horizontalLayout_64.setObjectName(_fromUtf8("horizontalLayout_64"))
        self.label_72 = QtGui.QLabel(self.frame_61)
        self.label_72.setMinimumSize(QtCore.QSize(190, 0))
#         self.label_72.setMaximumSize(QtCore.QSize(190, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.horizontalLayout_64.addWidget(self.label_72)
        self.cmbFlightPhase2 = QtGui.QComboBox(self.frame_61)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFlightPhase2.sizePolicy().hasHeightForWidth())
        self.cmbFlightPhase2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbFlightPhase2.setFont(font)
        self.cmbFlightPhase2.setObjectName(_fromUtf8("cmbFlightPhase2"))
        self.horizontalLayout_64.addWidget(self.cmbFlightPhase2)
        self.verticalLayoutWaypoint2.addWidget(self.frame_61)
        self.frame_Altitude_2 = QtGui.QFrame(self.gbWaypoint2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Altitude_2.sizePolicy().hasHeightForWidth())
        self.frame_Altitude_2.setSizePolicy(sizePolicy)
        self.frame_Altitude_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Altitude_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Altitude_2.setObjectName(_fromUtf8("frame_Altitude_2"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.frame_Altitude_2)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setMargin(0)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_18 = QtGui.QLabel(self.frame_Altitude_2)
        self.label_18.setMinimumSize(QtCore.QSize(190, 0))
#         self.label_18.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_28.addWidget(self.label_18)
        self.txtAltitude2 = QtGui.QLineEdit(self.frame_Altitude_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAltitude2.sizePolicy().hasHeightForWidth())
        self.txtAltitude2.setSizePolicy(sizePolicy)
        self.txtAltitude2.setMinimumSize(QtCore.QSize(105, 0))
        self.txtAltitude2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitude2.setFont(font)
        self.txtAltitude2.setObjectName(_fromUtf8("txtAltitude2"))
        self.horizontalLayout_28.addWidget(self.txtAltitude2)
        self.verticalLayoutWaypoint2.addWidget(self.frame_Altitude_2)
        self.vl_gbParameters.addWidget(self.gbWaypoint2)
        
        self.frame_TrackFrom = QtGui.QFrame(self.gbParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_TrackFrom.sizePolicy().hasHeightForWidth())
        self.frame_TrackFrom.setSizePolicy(sizePolicy)
        self.frame_TrackFrom.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_TrackFrom.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_TrackFrom.setObjectName(_fromUtf8("frame_TrackFrom"))
        self.horizontalLayout_63 = QtGui.QHBoxLayout(self.frame_TrackFrom)
        self.horizontalLayout_63.setSpacing(0)
        self.horizontalLayout_63.setMargin(0)
        self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        self.label_71 = QtGui.QLabel(self.frame_TrackFrom)
        self.label_71.setMinimumSize(QtCore.QSize(240, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_71.setFont(font)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.horizontalLayout_63.addWidget(self.label_71)
        self.frame_APV_6 = QtGui.QFrame(self.frame_TrackFrom)
        self.frame_APV_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_6.setObjectName(_fromUtf8("frame_APV_6"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frame_APV_6)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.txtTrack = QtGui.QLineEdit(self.frame_APV_6)
        self.txtTrack.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtTrack.setFont(font)
        self.txtTrack.setObjectName(_fromUtf8("txtTrack"))
        self.horizontalLayout_10.addWidget(self.txtTrack)
        self.btnCaptureTrack = QtGui.QToolButton(self.frame_APV_6)
        self.btnCaptureTrack.setText(_fromUtf8(""))
        self.btnCaptureTrack.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCaptureTrack.setIcon(icon)
        self.btnCaptureTrack.setObjectName(_fromUtf8("btnCaptureTrack"))
        self.horizontalLayout_10.addWidget(self.btnCaptureTrack)
        self.horizontalLayout_63.addWidget(self.frame_APV_6)
        self.vl_gbParameters.addWidget(self.frame_TrackFrom)
        
        self.verticalLayout.addWidget(self.gbParameters)
        self.gbResults = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbResults.sizePolicy().hasHeightForWidth())
        self.gbResults.setSizePolicy(sizePolicy)
        self.gbResults.setObjectName(_fromUtf8("gbResults"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gbResults)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gbResultsWaypoint1 = QtGui.QGroupBox(self.gbResults)
        self.gbResultsWaypoint1.setObjectName(_fromUtf8("gbResultsWaypoint1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbResultsWaypoint1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_70 = QtGui.QFrame(self.gbResultsWaypoint1)
        self.frame_70.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_70.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_70.setObjectName(_fromUtf8("frame_70"))
        self.horizontalLayout_75 = QtGui.QHBoxLayout(self.frame_70)
        self.horizontalLayout_75.setSpacing(0)
        self.horizontalLayout_75.setMargin(0)
        self.horizontalLayout_75.setObjectName(_fromUtf8("horizontalLayout_75"))
        self.label_83 = QtGui.QLabel(self.frame_70)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_83.sizePolicy().hasHeightForWidth())
        self.label_83.setSizePolicy(sizePolicy)
        self.label_83.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_83.setFont(font)
        self.label_83.setFrameShadow(QtGui.QFrame.Plain)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.horizontalLayout_75.addWidget(self.label_83)
        self.txtXtt1 = QtGui.QLineEdit(self.frame_70)
        self.txtXtt1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtXtt1.sizePolicy().hasHeightForWidth())
        self.txtXtt1.setSizePolicy(sizePolicy)
        self.txtXtt1.setMinimumSize(QtCore.QSize(0, 0))
        self.txtXtt1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtXtt1.setFont(font)
        self.txtXtt1.setObjectName(_fromUtf8("txtXtt1"))
        self.horizontalLayout_75.addWidget(self.txtXtt1)
        self.verticalLayout_2.addWidget(self.frame_70)
        self.frame_71 = QtGui.QFrame(self.gbResultsWaypoint1)
        self.frame_71.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_71.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_71.setObjectName(_fromUtf8("frame_71"))
        self.horizontalLayout_76 = QtGui.QHBoxLayout(self.frame_71)
        self.horizontalLayout_76.setSpacing(0)
        self.horizontalLayout_76.setMargin(0)
        self.horizontalLayout_76.setObjectName(_fromUtf8("horizontalLayout_76"))
        self.label_84 = QtGui.QLabel(self.frame_71)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_84.sizePolicy().hasHeightForWidth())
        self.label_84.setSizePolicy(sizePolicy)
        self.label_84.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_84.setFont(font)
        self.label_84.setFrameShadow(QtGui.QFrame.Plain)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.horizontalLayout_76.addWidget(self.label_84)
        self.txtAtt1 = QtGui.QLineEdit(self.frame_71)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAtt1.sizePolicy().hasHeightForWidth())
        self.txtAtt1.setSizePolicy(sizePolicy)
        self.txtAtt1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAtt1.setFont(font)
        self.txtAtt1.setObjectName(_fromUtf8("txtAtt1"))
        self.horizontalLayout_76.addWidget(self.txtAtt1)
        self.verticalLayout_2.addWidget(self.frame_71)
        self.frame_72 = QtGui.QFrame(self.gbResultsWaypoint1)
        self.frame_72.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_72.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_72.setObjectName(_fromUtf8("frame_72"))
        self.horizontalLayout_77 = QtGui.QHBoxLayout(self.frame_72)
        self.horizontalLayout_77.setSpacing(0)
        self.horizontalLayout_77.setMargin(0)
        self.horizontalLayout_77.setObjectName(_fromUtf8("horizontalLayout_77"))
        self.label_85 = QtGui.QLabel(self.frame_72)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_85.sizePolicy().hasHeightForWidth())
        self.label_85.setSizePolicy(sizePolicy)
        self.label_85.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_85.setFont(font)
        self.label_85.setFrameShadow(QtGui.QFrame.Plain)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.horizontalLayout_77.addWidget(self.label_85)
        self.txtAsw1 = QtGui.QLineEdit(self.frame_72)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAsw1.sizePolicy().hasHeightForWidth())
        self.txtAsw1.setSizePolicy(sizePolicy)
        self.txtAsw1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAsw1.setFont(font)
        self.txtAsw1.setObjectName(_fromUtf8("txtAsw1"))
        self.horizontalLayout_77.addWidget(self.txtAsw1)
        self.verticalLayout_2.addWidget(self.frame_72)
        self.horizontalLayout.addWidget(self.gbResultsWaypoint1)
        self.gbResultsWaypoint2 = QtGui.QGroupBox(self.gbResults)
        self.gbResultsWaypoint2.setObjectName(_fromUtf8("gbResultsWaypoint2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbResultsWaypoint2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_73 = QtGui.QFrame(self.gbResultsWaypoint2)
        self.frame_73.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_73.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_73.setObjectName(_fromUtf8("frame_73"))
        self.horizontalLayout_78 = QtGui.QHBoxLayout(self.frame_73)
        self.horizontalLayout_78.setSpacing(0)
        self.horizontalLayout_78.setMargin(0)
        self.horizontalLayout_78.setObjectName(_fromUtf8("horizontalLayout_78"))
        self.label_86 = QtGui.QLabel(self.frame_73)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_86.sizePolicy().hasHeightForWidth())
        self.label_86.setSizePolicy(sizePolicy)
        self.label_86.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_86.setFont(font)
#         self.label_86.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_86.setFrameShadow(QtGui.QFrame.Plain)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.horizontalLayout_78.addWidget(self.label_86)
        self.txtXtt2 = QtGui.QLineEdit(self.frame_73)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtXtt2.sizePolicy().hasHeightForWidth())
        self.txtXtt2.setSizePolicy(sizePolicy)
        self.txtXtt2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtXtt2.setFont(font)
        self.txtXtt2.setObjectName(_fromUtf8("txtXtt2"))
        self.horizontalLayout_78.addWidget(self.txtXtt2)
        self.verticalLayout_3.addWidget(self.frame_73)
        self.frame_74 = QtGui.QFrame(self.gbResultsWaypoint2)
        self.frame_74.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_74.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_74.setObjectName(_fromUtf8("frame_74"))
        self.horizontalLayout_79 = QtGui.QHBoxLayout(self.frame_74)
        self.horizontalLayout_79.setSpacing(0)
        self.horizontalLayout_79.setMargin(0)
        self.horizontalLayout_79.setObjectName(_fromUtf8("horizontalLayout_79"))
        self.label_87 = QtGui.QLabel(self.frame_74)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_87.sizePolicy().hasHeightForWidth())
        self.label_87.setSizePolicy(sizePolicy)
        self.label_87.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_87.setFont(font)
        self.label_87.setFrameShadow(QtGui.QFrame.Plain)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.horizontalLayout_79.addWidget(self.label_87)
        self.txtAtt2 = QtGui.QLineEdit(self.frame_74)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAtt2.sizePolicy().hasHeightForWidth())
        self.txtAtt2.setSizePolicy(sizePolicy)
        self.txtAtt2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAtt2.setFont(font)
        self.txtAtt2.setObjectName(_fromUtf8("txtAtt2"))
        self.horizontalLayout_79.addWidget(self.txtAtt2)
        self.verticalLayout_3.addWidget(self.frame_74)
        self.frame_75 = QtGui.QFrame(self.gbResultsWaypoint2)
        self.frame_75.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_75.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_75.setObjectName(_fromUtf8("frame_75"))
        self.horizontalLayout_80 = QtGui.QHBoxLayout(self.frame_75)
        self.horizontalLayout_80.setSpacing(0)
        self.horizontalLayout_80.setMargin(0)
        self.horizontalLayout_80.setObjectName(_fromUtf8("horizontalLayout_80"))
        self.label_88 = QtGui.QLabel(self.frame_75)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_88.sizePolicy().hasHeightForWidth())
        self.label_88.setSizePolicy(sizePolicy)
        self.label_88.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_88.setFont(font)
        self.label_88.setFrameShadow(QtGui.QFrame.Plain)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.horizontalLayout_80.addWidget(self.label_88)
        self.txtAsw2 = QtGui.QLineEdit(self.frame_75)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAsw2.sizePolicy().hasHeightForWidth())
        self.txtAsw2.setSizePolicy(sizePolicy)
        self.txtAsw2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAsw2.setFont(font)
        self.txtAsw2.setObjectName(_fromUtf8("txtAsw2"))
        self.horizontalLayout_80.addWidget(self.txtAsw2)
        self.verticalLayout_3.addWidget(self.frame_75)
        self.horizontalLayout.addWidget(self.gbResultsWaypoint2)
        self.verticalLayout.addWidget(self.gbResults)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.gbParameters.setTitle(_translate("Form", "Parameters", None))
        self.label_66.setText(_translate("Form", "RNAV Specification:", None))
        self.label_67.setText(_translate("Form", "Number of DMEs Used:", None))
        self.chbUse2Waypoints.setText(_translate("Form", "Use 2 Waypoints`", None))
#         self.gbVorDmePosition.setTitle(_translate("Form", "VOR/DME Position", None))
        self.gbWaypoint1.setTitle(_translate("Form", "Waypoint1", None))
        self.label_70.setText(_translate("Form", "Phase of Flight:", None))
        self.label_17.setText(_translate("Form", "Aircraft Altitude (ft):", None))
        self.txtAltitude1.setText(_translate("Form", "27000", None))
        self.gbWaypoint2.setTitle(_translate("Form", "Waypoint2", None))
        self.label_72.setText(_translate("Form", "Phase of Flight:", None))
        self.label_18.setText(_translate("Form", "Aircraft Altitude (ft):", None))
        self.txtAltitude2.setText(_translate("Form", "27000", None))
        self.gbResults.setTitle(_translate("Form", "Results", None))
        self.gbResultsWaypoint1.setTitle(_translate("Form", "Waypoint1", None))
        self.label_83.setText(_translate("Form", "XTT(nm):", None))
        self.txtXtt1.setText(_translate("Form", "0", None))
        self.label_84.setText(_translate("Form", "ATT(nm):", None))
        self.txtAtt1.setText(_translate("Form", "0", None))
        self.label_85.setText(_translate("Form", "1/2 A/W(nm):", None))
        self.txtAsw1.setText(_translate("Form", "0", None))
        self.gbResultsWaypoint2.setTitle(_translate("Form", "Waypoint2", None))
        self.label_86.setText(_translate("Form", "XTT(nm):", None))
        self.txtXtt2.setText(_translate("Form", "0", None))
        self.label_87.setText(_translate("Form", "ATT(nm):", None))
        self.txtAtt2.setText(_translate("Form", "0", None))
        self.label_88.setText(_translate("Form", "1/2 A/W(nm):", None))
        self.txtAsw2.setText(_translate("Form", "0", None))
        self.label_71.setText(_translate("Form", "Nominal Track ():", None))
        self.txtTrack.setText(_translate("Form", "0", None))

