# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ObstacleEvaluator.ui'
#
# Created: Fri Feb 19 18:24:08 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ObstacleEvaluator(object):
    def setupUi(self, ObstacleEvaluator):
        ObstacleEvaluator.setObjectName(_fromUtf8("ObstacleEvaluator"))
        ObstacleEvaluator.resize(546, 722)
        self.horizontalLayout = QtGui.QHBoxLayout(ObstacleEvaluator)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabCtrlGeneral = QtGui.QTabWidget(ObstacleEvaluator)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.tabCtrlGeneral.setFont(font)
        self.tabCtrlGeneral.setAutoFillBackground(True)
        self.tabCtrlGeneral.setStyleSheet(_fromUtf8(""))
        self.tabCtrlGeneral.setObjectName(_fromUtf8("tabCtrlGeneral"))
        self.tab_SecondaryMoc = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_SecondaryMoc.sizePolicy().hasHeightForWidth())
        self.tab_SecondaryMoc.setSizePolicy(sizePolicy)
        self.tab_SecondaryMoc.setObjectName(_fromUtf8("tab_SecondaryMoc"))
        self.hSecondaryMOC = QtGui.QHBoxLayout(self.tab_SecondaryMoc)
        self.hSecondaryMOC.setSpacing(3)
        self.hSecondaryMOC.setMargin(3)
        self.hSecondaryMOC.setObjectName(_fromUtf8("hSecondaryMOC"))
        self.grbParametersSecondaryMoc = QtGui.QGroupBox(self.tab_SecondaryMoc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grbParametersSecondaryMoc.sizePolicy().hasHeightForWidth())
        self.grbParametersSecondaryMoc.setSizePolicy(sizePolicy)
        self.grbParametersSecondaryMoc.setObjectName(_fromUtf8("grbParametersSecondaryMoc"))
        self.vlParametersSecondaryMoc = QtGui.QVBoxLayout(self.grbParametersSecondaryMoc)
        self.vlParametersSecondaryMoc.setMargin(6)
        self.vlParametersSecondaryMoc.setObjectName(_fromUtf8("vlParametersSecondaryMoc"))
        self.frameEvaluationMode = QtGui.QFrame(self.grbParametersSecondaryMoc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameEvaluationMode.sizePolicy().hasHeightForWidth())
        self.frameEvaluationMode.setSizePolicy(sizePolicy)
        self.frameEvaluationMode.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameEvaluationMode.setFrameShadow(QtGui.QFrame.Raised)
        self.frameEvaluationMode.setObjectName(_fromUtf8("frameEvaluationMode"))
        self.horizontalLayout_EvaluationMode = QtGui.QHBoxLayout(self.frameEvaluationMode)
        self.horizontalLayout_EvaluationMode.setSpacing(6)
        self.horizontalLayout_EvaluationMode.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_EvaluationMode.setObjectName(_fromUtf8("horizontalLayout_EvaluationMode"))
        self.label_67 = QtGui.QLabel(self.frameEvaluationMode)
        self.label_67.setMinimumSize(QtCore.QSize(150, 0))
        self.label_67.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.horizontalLayout_EvaluationMode.addWidget(self.label_67)
        self.cmbEvaluationMode = QtGui.QComboBox(self.frameEvaluationMode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEvaluationMode.sizePolicy().hasHeightForWidth())
        self.cmbEvaluationMode.setSizePolicy(sizePolicy)
        self.cmbEvaluationMode.setMinimumSize(QtCore.QSize(79, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbEvaluationMode.setFont(font)
        self.cmbEvaluationMode.setObjectName(_fromUtf8("cmbEvaluationMode"))
        self.horizontalLayout_EvaluationMode.addWidget(self.cmbEvaluationMode)
        self.vlParametersSecondaryMoc.addWidget(self.frameEvaluationMode)
        self.framePrimaryMOC = QtGui.QFrame(self.grbParametersSecondaryMoc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePrimaryMOC.sizePolicy().hasHeightForWidth())
        self.framePrimaryMOC.setSizePolicy(sizePolicy)
        self.framePrimaryMOC.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePrimaryMOC.setFrameShadow(QtGui.QFrame.Raised)
        self.framePrimaryMOC.setObjectName(_fromUtf8("framePrimaryMOC"))
        self.horizontalLayout_71 = QtGui.QHBoxLayout(self.framePrimaryMOC)
        self.horizontalLayout_71.setSpacing(6)
        self.horizontalLayout_71.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_71.setObjectName(_fromUtf8("horizontalLayout_71"))
        self.label_79 = QtGui.QLabel(self.framePrimaryMOC)
        self.label_79.setMinimumSize(QtCore.QSize(150, 0))
        self.label_79.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_79.setFont(font)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.horizontalLayout_71.addWidget(self.label_79)
        self.txtPrimaryMOC = QtGui.QLineEdit(self.framePrimaryMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPrimaryMOC.setFont(font)
        self.txtPrimaryMOC.setObjectName(_fromUtf8("txtPrimaryMOC"))
        self.horizontalLayout_71.addWidget(self.txtPrimaryMOC)
        self.label_3 = QtGui.QLabel(self.framePrimaryMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_71.addWidget(self.label_3)
        self.txtPrimaryMOCFt = QtGui.QLineEdit(self.framePrimaryMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPrimaryMOCFt.setFont(font)
        self.txtPrimaryMOCFt.setText(_fromUtf8(""))
        self.txtPrimaryMOCFt.setObjectName(_fromUtf8("txtPrimaryMOCFt"))
        self.horizontalLayout_71.addWidget(self.txtPrimaryMOCFt)
        self.label_4 = QtGui.QLabel(self.framePrimaryMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_71.addWidget(self.label_4)
        self.vlParametersSecondaryMoc.addWidget(self.framePrimaryMOC)
        self.frameInsertPointAndText = QtGui.QFrame(self.grbParametersSecondaryMoc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameInsertPointAndText.sizePolicy().hasHeightForWidth())
        self.frameInsertPointAndText.setSizePolicy(sizePolicy)
        self.frameInsertPointAndText.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameInsertPointAndText.setFrameShadow(QtGui.QFrame.Raised)
        self.frameInsertPointAndText.setObjectName(_fromUtf8("frameInsertPointAndText"))
        self.horizontalLayout_InsertPointAndText = QtGui.QHBoxLayout(self.frameInsertPointAndText)
        self.horizontalLayout_InsertPointAndText.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_InsertPointAndText.setObjectName(_fromUtf8("horizontalLayout_InsertPointAndText"))
        self.chbInsertPointAndText = QtGui.QCheckBox(self.frameInsertPointAndText)
        self.chbInsertPointAndText.setMinimumSize(QtCore.QSize(150, 0))
        self.chbInsertPointAndText.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbInsertPointAndText.setFont(font)
        self.chbInsertPointAndText.setObjectName(_fromUtf8("chbInsertPointAndText"))
        self.horizontalLayout_InsertPointAndText.addWidget(self.chbInsertPointAndText)
        self.frameTextHeight = QtGui.QFrame(self.frameInsertPointAndText)
        self.frameTextHeight.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameTextHeight.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTextHeight.setObjectName(_fromUtf8("frameTextHeight"))
        self.horizontalLayout_TextHeight = QtGui.QHBoxLayout(self.frameTextHeight)
        self.horizontalLayout_TextHeight.setSpacing(0)
        self.horizontalLayout_TextHeight.setMargin(0)
        self.horizontalLayout_TextHeight.setObjectName(_fromUtf8("horizontalLayout_TextHeight"))
        self.label_74 = QtGui.QLabel(self.frameTextHeight)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_74.sizePolicy().hasHeightForWidth())
        self.label_74.setSizePolicy(sizePolicy)
        self.label_74.setMinimumSize(QtCore.QSize(100, 0))
        self.label_74.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_TextHeight.addWidget(self.label_74)
        self.txtTextHeight = QtGui.QLineEdit(self.frameTextHeight)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtTextHeight.setFont(font)
        self.txtTextHeight.setText(_fromUtf8(""))
        self.txtTextHeight.setObjectName(_fromUtf8("txtTextHeight"))
        self.horizontalLayout_TextHeight.addWidget(self.txtTextHeight)
        self.horizontalLayout_InsertPointAndText.addWidget(self.frameTextHeight)
        self.vlParametersSecondaryMoc.addWidget(self.frameInsertPointAndText)
        self.framePerpendicularToSMC = QtGui.QFrame(self.grbParametersSecondaryMoc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePerpendicularToSMC.sizePolicy().hasHeightForWidth())
        self.framePerpendicularToSMC.setSizePolicy(sizePolicy)
        self.framePerpendicularToSMC.setFrameShape(QtGui.QFrame.StyledPanel)
        self.framePerpendicularToSMC.setFrameShadow(QtGui.QFrame.Raised)
        self.framePerpendicularToSMC.setObjectName(_fromUtf8("framePerpendicularToSMC"))
        self.horizontalLayout_PerpendicularToSMC = QtGui.QHBoxLayout(self.framePerpendicularToSMC)
        self.horizontalLayout_PerpendicularToSMC.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_PerpendicularToSMC.setObjectName(_fromUtf8("horizontalLayout_PerpendicularToSMC"))
        self.chbPerpendicularToSMC = QtGui.QCheckBox(self.framePerpendicularToSMC)
        self.chbPerpendicularToSMC.setMinimumSize(QtCore.QSize(150, 0))
        self.chbPerpendicularToSMC.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbPerpendicularToSMC.setFont(font)
        self.chbPerpendicularToSMC.setObjectName(_fromUtf8("chbPerpendicularToSMC"))
        self.horizontalLayout_PerpendicularToSMC.addWidget(self.chbPerpendicularToSMC)
        self.frameNominalTrackSMC = QtGui.QFrame(self.framePerpendicularToSMC)
        self.frameNominalTrackSMC.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameNominalTrackSMC.setFrameShadow(QtGui.QFrame.Raised)
        self.frameNominalTrackSMC.setObjectName(_fromUtf8("frameNominalTrackSMC"))
        self.horizontalLayout_NominalTrackSMC = QtGui.QHBoxLayout(self.frameNominalTrackSMC)
        self.horizontalLayout_NominalTrackSMC.setSpacing(0)
        self.horizontalLayout_NominalTrackSMC.setMargin(0)
        self.horizontalLayout_NominalTrackSMC.setObjectName(_fromUtf8("horizontalLayout_NominalTrackSMC"))
        self.label_NominalTrack = QtGui.QLabel(self.frameNominalTrackSMC)
        self.label_NominalTrack.setMinimumSize(QtCore.QSize(100, 0))
        self.label_NominalTrack.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_NominalTrack.setFont(font)
        self.label_NominalTrack.setObjectName(_fromUtf8("label_NominalTrack"))
        self.horizontalLayout_NominalTrackSMC.addWidget(self.label_NominalTrack)
        self.frameINominalTrackBtnSMC = QtGui.QFrame(self.frameNominalTrackSMC)
        self.frameINominalTrackBtnSMC.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameINominalTrackBtnSMC.setFrameShadow(QtGui.QFrame.Raised)
        self.frameINominalTrackBtnSMC.setObjectName(_fromUtf8("frameINominalTrackBtnSMC"))
        self.horizontalLayout_NominalTrackBtnSMC = QtGui.QHBoxLayout(self.frameINominalTrackBtnSMC)
        self.horizontalLayout_NominalTrackBtnSMC.setSpacing(0)
        self.horizontalLayout_NominalTrackBtnSMC.setMargin(0)
        self.horizontalLayout_NominalTrackBtnSMC.setObjectName(_fromUtf8("horizontalLayout_NominalTrackBtnSMC"))
        self.txtNominalTrackSMC = QtGui.QLineEdit(self.frameINominalTrackBtnSMC)
        self.txtNominalTrackSMC.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtNominalTrackSMC.sizePolicy().hasHeightForWidth())
        self.txtNominalTrackSMC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtNominalTrackSMC.setFont(font)
        self.txtNominalTrackSMC.setObjectName(_fromUtf8("txtNominalTrackSMC"))
        self.horizontalLayout_NominalTrackBtnSMC.addWidget(self.txtNominalTrackSMC)
        self.btnCaptureNominalTrackSMC = QtGui.QToolButton(self.frameINominalTrackBtnSMC)
        self.btnCaptureNominalTrackSMC.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCaptureNominalTrackSMC.setIcon(icon)
        self.btnCaptureNominalTrackSMC.setObjectName(_fromUtf8("btnCaptureNominalTrackSMC"))
        self.horizontalLayout_NominalTrackBtnSMC.addWidget(self.btnCaptureNominalTrackSMC)
        self.horizontalLayout_NominalTrackSMC.addWidget(self.frameINominalTrackBtnSMC)
        self.horizontalLayout_PerpendicularToSMC.addWidget(self.frameNominalTrackSMC)
        self.vlParametersSecondaryMoc.addWidget(self.framePerpendicularToSMC)
        self.chbMultipleAreasSMC = QtGui.QCheckBox(self.grbParametersSecondaryMoc)
        self.chbMultipleAreasSMC.setMinimumSize(QtCore.QSize(150, 0))
        self.chbMultipleAreasSMC.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbMultipleAreasSMC.setFont(font)
        self.chbMultipleAreasSMC.setObjectName(_fromUtf8("chbMultipleAreasSMC"))
        self.vlParametersSecondaryMoc.addWidget(self.chbMultipleAreasSMC)
        self.hSecondaryMOC.addWidget(self.grbParametersSecondaryMoc)
        self.tabCtrlGeneral.addTab(self.tab_SecondaryMoc, _fromUtf8(""))
        self.tab_TurnAreaObstacleAnalyser = QtGui.QWidget()
        self.tab_TurnAreaObstacleAnalyser.setObjectName(_fromUtf8("tab_TurnAreaObstacleAnalyser"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.tab_TurnAreaObstacleAnalyser)
        self.horizontalLayout_29.setMargin(3)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.grbParametersTurnAreaObstacleAnalyser = QtGui.QGroupBox(self.tab_TurnAreaObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grbParametersTurnAreaObstacleAnalyser.sizePolicy().hasHeightForWidth())
        self.grbParametersTurnAreaObstacleAnalyser.setSizePolicy(sizePolicy)
        self.grbParametersTurnAreaObstacleAnalyser.setObjectName(_fromUtf8("grbParametersTurnAreaObstacleAnalyser"))
        self.vlParametersTurnAreaObstacleAnalyser = QtGui.QVBoxLayout(self.grbParametersTurnAreaObstacleAnalyser)
        self.vlParametersTurnAreaObstacleAnalyser.setMargin(6)
        self.vlParametersTurnAreaObstacleAnalyser.setObjectName(_fromUtf8("vlParametersTurnAreaObstacleAnalyser"))
        self.frameUsedFor = QtGui.QFrame(self.grbParametersTurnAreaObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameUsedFor.sizePolicy().hasHeightForWidth())
        self.frameUsedFor.setSizePolicy(sizePolicy)
        self.frameUsedFor.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameUsedFor.setFrameShadow(QtGui.QFrame.Raised)
        self.frameUsedFor.setObjectName(_fromUtf8("frameUsedFor"))
        self.horizontalLayout_UsedFor = QtGui.QHBoxLayout(self.frameUsedFor)
        self.horizontalLayout_UsedFor.setSpacing(6)
        self.horizontalLayout_UsedFor.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_UsedFor.setObjectName(_fromUtf8("horizontalLayout_UsedFor"))
        self.label_68 = QtGui.QLabel(self.frameUsedFor)
        self.label_68.setMinimumSize(QtCore.QSize(150, 0))
        self.label_68.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_UsedFor.addWidget(self.label_68)
        self.cmbUsedFor = QtGui.QComboBox(self.frameUsedFor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbUsedFor.sizePolicy().hasHeightForWidth())
        self.cmbUsedFor.setSizePolicy(sizePolicy)
        self.cmbUsedFor.setMinimumSize(QtCore.QSize(79, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbUsedFor.setFont(font)
        self.cmbUsedFor.setObjectName(_fromUtf8("cmbUsedFor"))
        self.horizontalLayout_UsedFor.addWidget(self.cmbUsedFor)
        self.vlParametersTurnAreaObstacleAnalyser.addWidget(self.frameUsedFor)
        self.framePortion = QtGui.QFrame(self.grbParametersTurnAreaObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePortion.sizePolicy().hasHeightForWidth())
        self.framePortion.setSizePolicy(sizePolicy)
        self.framePortion.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePortion.setFrameShadow(QtGui.QFrame.Raised)
        self.framePortion.setObjectName(_fromUtf8("framePortion"))
        self.horizontalLayout_Portion = QtGui.QHBoxLayout(self.framePortion)
        self.horizontalLayout_Portion.setSpacing(6)
        self.horizontalLayout_Portion.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_Portion.setObjectName(_fromUtf8("horizontalLayout_Portion"))
        self.label_69 = QtGui.QLabel(self.framePortion)
        self.label_69.setMinimumSize(QtCore.QSize(150, 0))
        self.label_69.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.horizontalLayout_Portion.addWidget(self.label_69)
        self.cmbPortion = QtGui.QComboBox(self.framePortion)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPortion.sizePolicy().hasHeightForWidth())
        self.cmbPortion.setSizePolicy(sizePolicy)
        self.cmbPortion.setMinimumSize(QtCore.QSize(79, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbPortion.setFont(font)
        self.cmbPortion.setObjectName(_fromUtf8("cmbPortion"))
        self.horizontalLayout_Portion.addWidget(self.cmbPortion)
        self.vlParametersTurnAreaObstacleAnalyser.addWidget(self.framePortion)
        self.frameTrack = QtGui.QFrame(self.grbParametersTurnAreaObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameTrack.sizePolicy().hasHeightForWidth())
        self.frameTrack.setSizePolicy(sizePolicy)
        self.frameTrack.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameTrack.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTrack.setObjectName(_fromUtf8("frameTrack"))
        self.horizontalLayout_Track = QtGui.QHBoxLayout(self.frameTrack)
        self.horizontalLayout_Track.setSpacing(6)
        self.horizontalLayout_Track.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_Track.setObjectName(_fromUtf8("horizontalLayout_Track"))
        self.label_76 = QtGui.QLabel(self.frameTrack)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_76.sizePolicy().hasHeightForWidth())
        self.label_76.setSizePolicy(sizePolicy)
        self.label_76.setMinimumSize(QtCore.QSize(150, 0))
        self.label_76.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_76.setFont(font)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.horizontalLayout_Track.addWidget(self.label_76)
        self.txtTrack = QtGui.QLineEdit(self.frameTrack)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtTrack.setFont(font)
        self.txtTrack.setText(_fromUtf8(""))
        self.txtTrack.setObjectName(_fromUtf8("txtTrack"))
        self.horizontalLayout_Track.addWidget(self.txtTrack)
        self.vlParametersTurnAreaObstacleAnalyser.addWidget(self.frameTrack)
        self.frameStartingMOC = QtGui.QFrame(self.grbParametersTurnAreaObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameStartingMOC.sizePolicy().hasHeightForWidth())
        self.frameStartingMOC.setSizePolicy(sizePolicy)
        self.frameStartingMOC.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameStartingMOC.setFrameShadow(QtGui.QFrame.Raised)
        self.frameStartingMOC.setObjectName(_fromUtf8("frameStartingMOC"))
        self.horizontalLayout_StartingMOC = QtGui.QHBoxLayout(self.frameStartingMOC)
        self.horizontalLayout_StartingMOC.setSpacing(6)
        self.horizontalLayout_StartingMOC.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_StartingMOC.setObjectName(_fromUtf8("horizontalLayout_StartingMOC"))
        self.label_80 = QtGui.QLabel(self.frameStartingMOC)
        self.label_80.setMinimumSize(QtCore.QSize(150, 0))
        self.label_80.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_80.setFont(font)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.horizontalLayout_StartingMOC.addWidget(self.label_80)
        self.txtStartingMOC = QtGui.QLineEdit(self.frameStartingMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtStartingMOC.setFont(font)
        self.txtStartingMOC.setObjectName(_fromUtf8("txtStartingMOC"))
        self.horizontalLayout_StartingMOC.addWidget(self.txtStartingMOC)
        self.label_5 = QtGui.QLabel(self.frameStartingMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_StartingMOC.addWidget(self.label_5)
        self.txtStartingMOCFt = QtGui.QLineEdit(self.frameStartingMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtStartingMOCFt.setFont(font)
        self.txtStartingMOCFt.setText(_fromUtf8(""))
        self.txtStartingMOCFt.setObjectName(_fromUtf8("txtStartingMOCFt"))
        self.horizontalLayout_StartingMOC.addWidget(self.txtStartingMOCFt)
        self.label_6 = QtGui.QLabel(self.frameStartingMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_StartingMOC.addWidget(self.label_6)
        self.vlParametersTurnAreaObstacleAnalyser.addWidget(self.frameStartingMOC)
        self.frameDepMocS = QtGui.QFrame(self.grbParametersTurnAreaObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameDepMocS.sizePolicy().hasHeightForWidth())
        self.frameDepMocS.setSizePolicy(sizePolicy)
        self.frameDepMocS.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameDepMocS.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDepMocS.setObjectName(_fromUtf8("frameDepMocS"))
        self.horizontalLayout_DepMocS = QtGui.QHBoxLayout(self.frameDepMocS)
        self.horizontalLayout_DepMocS.setSpacing(6)
        self.horizontalLayout_DepMocS.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_DepMocS.setObjectName(_fromUtf8("horizontalLayout_DepMocS"))
        self.label_77 = QtGui.QLabel(self.frameDepMocS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_77.sizePolicy().hasHeightForWidth())
        self.label_77.setSizePolicy(sizePolicy)
        self.label_77.setMinimumSize(QtCore.QSize(150, 0))
        self.label_77.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.horizontalLayout_DepMocS.addWidget(self.label_77)
        self.txtDepMocS = QtGui.QLineEdit(self.frameDepMocS)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtDepMocS.setFont(font)
        self.txtDepMocS.setText(_fromUtf8(""))
        self.txtDepMocS.setObjectName(_fromUtf8("txtDepMocS"))
        self.horizontalLayout_DepMocS.addWidget(self.txtDepMocS)
        self.vlParametersTurnAreaObstacleAnalyser.addWidget(self.frameDepMocS)
        self.frameDepMocT = QtGui.QFrame(self.grbParametersTurnAreaObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameDepMocT.sizePolicy().hasHeightForWidth())
        self.frameDepMocT.setSizePolicy(sizePolicy)
        self.frameDepMocT.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameDepMocT.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDepMocT.setObjectName(_fromUtf8("frameDepMocT"))
        self.horizontalLayout_DepMocT = QtGui.QHBoxLayout(self.frameDepMocT)
        self.horizontalLayout_DepMocT.setSpacing(6)
        self.horizontalLayout_DepMocT.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_DepMocT.setObjectName(_fromUtf8("horizontalLayout_DepMocT"))
        self.label_78 = QtGui.QLabel(self.frameDepMocT)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_78.sizePolicy().hasHeightForWidth())
        self.label_78.setSizePolicy(sizePolicy)
        self.label_78.setMinimumSize(QtCore.QSize(150, 0))
        self.label_78.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_78.setFont(font)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.horizontalLayout_DepMocT.addWidget(self.label_78)
        self.frameMocDepT_value = QtGui.QFrame(self.frameDepMocT)
        self.frameMocDepT_value.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameMocDepT_value.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMocDepT_value.setObjectName(_fromUtf8("frameMocDepT_value"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frameMocDepT_value)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frameDepMocT1 = QtGui.QFrame(self.frameMocDepT_value)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameDepMocT1.sizePolicy().hasHeightForWidth())
        self.frameDepMocT1.setSizePolicy(sizePolicy)
        self.frameDepMocT1.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameDepMocT1.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDepMocT1.setObjectName(_fromUtf8("frameDepMocT1"))
        self.horizontalLayout_DepMocT1 = QtGui.QHBoxLayout(self.frameDepMocT1)
        self.horizontalLayout_DepMocT1.setSpacing(6)
        self.horizontalLayout_DepMocT1.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_DepMocT1.setObjectName(_fromUtf8("horizontalLayout_DepMocT1"))
        self.label_82 = QtGui.QLabel(self.frameDepMocT1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_82.sizePolicy().hasHeightForWidth())
        self.label_82.setSizePolicy(sizePolicy)
        self.label_82.setMinimumSize(QtCore.QSize(150, 0))
        self.label_82.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_82.setFont(font)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.horizontalLayout_DepMocT1.addWidget(self.label_82)
        self.txtDepMocT1 = QtGui.QLineEdit(self.frameDepMocT1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtDepMocT1.setFont(font)
        self.txtDepMocT1.setText(_fromUtf8(""))
        self.txtDepMocT1.setObjectName(_fromUtf8("txtDepMocT1"))
        self.horizontalLayout_DepMocT1.addWidget(self.txtDepMocT1)
        self.verticalLayout.addWidget(self.frameDepMocT1)
        self.frameDepMocT2 = QtGui.QFrame(self.frameMocDepT_value)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameDepMocT2.sizePolicy().hasHeightForWidth())
        self.frameDepMocT2.setSizePolicy(sizePolicy)
        self.frameDepMocT2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameDepMocT2.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDepMocT2.setObjectName(_fromUtf8("frameDepMocT2"))
        self.horizontalLayout_DepMocT2 = QtGui.QHBoxLayout(self.frameDepMocT2)
        self.horizontalLayout_DepMocT2.setSpacing(6)
        self.horizontalLayout_DepMocT2.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_DepMocT2.setObjectName(_fromUtf8("horizontalLayout_DepMocT2"))
        self.label_83 = QtGui.QLabel(self.frameDepMocT2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_83.sizePolicy().hasHeightForWidth())
        self.label_83.setSizePolicy(sizePolicy)
        self.label_83.setMinimumSize(QtCore.QSize(150, 0))
        self.label_83.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_83.setFont(font)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.horizontalLayout_DepMocT2.addWidget(self.label_83)
        self.txtDepMocT2 = QtGui.QLineEdit(self.frameDepMocT2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtDepMocT2.setFont(font)
        self.txtDepMocT2.setText(_fromUtf8(""))
        self.txtDepMocT2.setObjectName(_fromUtf8("txtDepMocT2"))
        self.horizontalLayout_DepMocT2.addWidget(self.txtDepMocT2)
        self.verticalLayout.addWidget(self.frameDepMocT2)
        self.horizontalLayout_DepMocT.addWidget(self.frameMocDepT_value)
        self.vlParametersTurnAreaObstacleAnalyser.addWidget(self.frameDepMocT)
        self.frameMaMocS = QtGui.QFrame(self.grbParametersTurnAreaObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameMaMocS.sizePolicy().hasHeightForWidth())
        self.frameMaMocS.setSizePolicy(sizePolicy)
        self.frameMaMocS.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMaMocS.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMaMocS.setObjectName(_fromUtf8("frameMaMocS"))
        self.horizontalLayout_MaMocS = QtGui.QHBoxLayout(self.frameMaMocS)
        self.horizontalLayout_MaMocS.setSpacing(6)
        self.horizontalLayout_MaMocS.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_MaMocS.setObjectName(_fromUtf8("horizontalLayout_MaMocS"))
        self.label_81 = QtGui.QLabel(self.frameMaMocS)
        self.label_81.setMinimumSize(QtCore.QSize(150, 0))
        self.label_81.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_81.setFont(font)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.horizontalLayout_MaMocS.addWidget(self.label_81)
        self.txtMaMocS = QtGui.QLineEdit(self.frameMaMocS)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMaMocS.setFont(font)
        self.txtMaMocS.setObjectName(_fromUtf8("txtMaMocS"))
        self.horizontalLayout_MaMocS.addWidget(self.txtMaMocS)
        self.label_7 = QtGui.QLabel(self.frameMaMocS)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_MaMocS.addWidget(self.label_7)
        self.txtMaMocSFt = QtGui.QLineEdit(self.frameMaMocS)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMaMocSFt.setFont(font)
        self.txtMaMocSFt.setText(_fromUtf8(""))
        self.txtMaMocSFt.setObjectName(_fromUtf8("txtMaMocSFt"))
        self.horizontalLayout_MaMocS.addWidget(self.txtMaMocSFt)
        self.label_8 = QtGui.QLabel(self.frameMaMocS)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_MaMocS.addWidget(self.label_8)
        self.vlParametersTurnAreaObstacleAnalyser.addWidget(self.frameMaMocS)
        self.frameMaMocT = QtGui.QFrame(self.grbParametersTurnAreaObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameMaMocT.sizePolicy().hasHeightForWidth())
        self.frameMaMocT.setSizePolicy(sizePolicy)
        self.frameMaMocT.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMaMocT.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMaMocT.setObjectName(_fromUtf8("frameMaMocT"))
        self.horizontalLayout_MaMocT = QtGui.QHBoxLayout(self.frameMaMocT)
        self.horizontalLayout_MaMocT.setSpacing(6)
        self.horizontalLayout_MaMocT.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_MaMocT.setObjectName(_fromUtf8("horizontalLayout_MaMocT"))
        self.label_84 = QtGui.QLabel(self.frameMaMocT)
        self.label_84.setMinimumSize(QtCore.QSize(150, 0))
        self.label_84.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_84.setFont(font)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.horizontalLayout_MaMocT.addWidget(self.label_84)
        self.txtMaMocT = QtGui.QLineEdit(self.frameMaMocT)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMaMocT.setFont(font)
        self.txtMaMocT.setObjectName(_fromUtf8("txtMaMocT"))
        self.horizontalLayout_MaMocT.addWidget(self.txtMaMocT)
        self.label_9 = QtGui.QLabel(self.frameMaMocT)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_MaMocT.addWidget(self.label_9)
        self.txtMaMocTFt = QtGui.QLineEdit(self.frameMaMocT)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMaMocTFt.setFont(font)
        self.txtMaMocTFt.setText(_fromUtf8(""))
        self.txtMaMocTFt.setObjectName(_fromUtf8("txtMaMocTFt"))
        self.horizontalLayout_MaMocT.addWidget(self.txtMaMocTFt)
        self.label_10 = QtGui.QLabel(self.frameMaMocT)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_MaMocT.addWidget(self.label_10)
        self.vlParametersTurnAreaObstacleAnalyser.addWidget(self.frameMaMocT)
        self.framePDG = QtGui.QFrame(self.grbParametersTurnAreaObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePDG.sizePolicy().hasHeightForWidth())
        self.framePDG.setSizePolicy(sizePolicy)
        self.framePDG.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePDG.setFrameShadow(QtGui.QFrame.Raised)
        self.framePDG.setObjectName(_fromUtf8("framePDG"))
        self.horizontalLayout_PDG = QtGui.QHBoxLayout(self.framePDG)
        self.horizontalLayout_PDG.setSpacing(6)
        self.horizontalLayout_PDG.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_PDG.setObjectName(_fromUtf8("horizontalLayout_PDG"))
        self.label_85 = QtGui.QLabel(self.framePDG)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_85.sizePolicy().hasHeightForWidth())
        self.label_85.setSizePolicy(sizePolicy)
        self.label_85.setMinimumSize(QtCore.QSize(150, 0))
        self.label_85.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_85.setFont(font)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.horizontalLayout_PDG.addWidget(self.label_85)
        self.txtPDG = QtGui.QLineEdit(self.framePDG)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPDG.setFont(font)
        self.txtPDG.setText(_fromUtf8(""))
        self.txtPDG.setObjectName(_fromUtf8("txtPDG"))
        self.horizontalLayout_PDG.addWidget(self.txtPDG)
        self.vlParametersTurnAreaObstacleAnalyser.addWidget(self.framePDG)
        self.frameMACG = QtGui.QFrame(self.grbParametersTurnAreaObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameMACG.sizePolicy().hasHeightForWidth())
        self.frameMACG.setSizePolicy(sizePolicy)
        self.frameMACG.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMACG.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMACG.setObjectName(_fromUtf8("frameMACG"))
        self.horizontalLayout_MACG = QtGui.QHBoxLayout(self.frameMACG)
        self.horizontalLayout_MACG.setSpacing(6)
        self.horizontalLayout_MACG.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_MACG.setObjectName(_fromUtf8("horizontalLayout_MACG"))
        self.label_86 = QtGui.QLabel(self.frameMACG)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_86.sizePolicy().hasHeightForWidth())
        self.label_86.setSizePolicy(sizePolicy)
        self.label_86.setMinimumSize(QtCore.QSize(150, 0))
        self.label_86.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_86.setFont(font)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.horizontalLayout_MACG.addWidget(self.label_86)
        self.txtMACG = QtGui.QLineEdit(self.frameMACG)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMACG.setFont(font)
        self.txtMACG.setText(_fromUtf8(""))
        self.txtMACG.setObjectName(_fromUtf8("txtMACG"))
        self.horizontalLayout_MACG.addWidget(self.txtMACG)
        self.vlParametersTurnAreaObstacleAnalyser.addWidget(self.frameMACG)
        self.frameTurningAltitude = QtGui.QFrame(self.grbParametersTurnAreaObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameTurningAltitude.sizePolicy().hasHeightForWidth())
        self.frameTurningAltitude.setSizePolicy(sizePolicy)
        self.frameTurningAltitude.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameTurningAltitude.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTurningAltitude.setObjectName(_fromUtf8("frameTurningAltitude"))
        self.horizontalLayout_TurningAltitude = QtGui.QHBoxLayout(self.frameTurningAltitude)
        self.horizontalLayout_TurningAltitude.setSpacing(6)
        self.horizontalLayout_TurningAltitude.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_TurningAltitude.setObjectName(_fromUtf8("horizontalLayout_TurningAltitude"))
        self.label_87 = QtGui.QLabel(self.frameTurningAltitude)
        self.label_87.setMinimumSize(QtCore.QSize(150, 0))
        self.label_87.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_87.setFont(font)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.horizontalLayout_TurningAltitude.addWidget(self.label_87)
        self.txtTurningAltitudeM = QtGui.QLineEdit(self.frameTurningAltitude)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtTurningAltitudeM.setFont(font)
        self.txtTurningAltitudeM.setText(_fromUtf8(""))
        self.txtTurningAltitudeM.setObjectName(_fromUtf8("txtTurningAltitudeM"))
        self.horizontalLayout_TurningAltitude.addWidget(self.txtTurningAltitudeM)
        self.label_11 = QtGui.QLabel(self.frameTurningAltitude)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_TurningAltitude.addWidget(self.label_11)
        self.txtTurningAltitude = QtGui.QLineEdit(self.frameTurningAltitude)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtTurningAltitude.setFont(font)
        self.txtTurningAltitude.setObjectName(_fromUtf8("txtTurningAltitude"))
        self.horizontalLayout_TurningAltitude.addWidget(self.txtTurningAltitude)
        self.label_12 = QtGui.QLabel(self.frameTurningAltitude)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_TurningAltitude.addWidget(self.label_12)
        self.vlParametersTurnAreaObstacleAnalyser.addWidget(self.frameTurningAltitude)
        self.frameSecondTurn = QtGui.QFrame(self.grbParametersTurnAreaObstacleAnalyser)
        self.frameSecondTurn.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameSecondTurn.setFrameShadow(QtGui.QFrame.Raised)
        self.frameSecondTurn.setObjectName(_fromUtf8("frameSecondTurn"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frameSecondTurn)
        self.verticalLayout_2.setContentsMargins(0, 6, 0, 6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.chbMultipleAreas_2 = QtGui.QCheckBox(self.frameSecondTurn)
        self.chbMultipleAreas_2.setMinimumSize(QtCore.QSize(150, 0))
        self.chbMultipleAreas_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbMultipleAreas_2.setFont(font)
        self.chbMultipleAreas_2.setObjectName(_fromUtf8("chbMultipleAreas_2"))
        self.verticalLayout_2.addWidget(self.chbMultipleAreas_2)
        self.frameDistToEtp = QtGui.QFrame(self.frameSecondTurn)
        self.frameDistToEtp.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameDistToEtp.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDistToEtp.setObjectName(_fromUtf8("frameDistToEtp"))
        self.horizontalLayout_DistToEtp = QtGui.QHBoxLayout(self.frameDistToEtp)
        self.horizontalLayout_DistToEtp.setSpacing(0)
        self.horizontalLayout_DistToEtp.setMargin(0)
        self.horizontalLayout_DistToEtp.setObjectName(_fromUtf8("horizontalLayout_DistToEtp"))
        self.label_NominalTrack_2 = QtGui.QLabel(self.frameDistToEtp)
        self.label_NominalTrack_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_NominalTrack_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_NominalTrack_2.setFont(font)
        self.label_NominalTrack_2.setObjectName(_fromUtf8("label_NominalTrack_2"))
        self.horizontalLayout_DistToEtp.addWidget(self.label_NominalTrack_2)
        self.frameIDistToEtpBtn = QtGui.QFrame(self.frameDistToEtp)
        self.frameIDistToEtpBtn.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameIDistToEtpBtn.setFrameShadow(QtGui.QFrame.Raised)
        self.frameIDistToEtpBtn.setObjectName(_fromUtf8("frameIDistToEtpBtn"))
        self.horizontalLayout_DistToEtpBtn = QtGui.QHBoxLayout(self.frameIDistToEtpBtn)
        self.horizontalLayout_DistToEtpBtn.setSpacing(0)
        self.horizontalLayout_DistToEtpBtn.setMargin(0)
        self.horizontalLayout_DistToEtpBtn.setObjectName(_fromUtf8("horizontalLayout_DistToEtpBtn"))
        self.txtDistToEtp = QtGui.QLineEdit(self.frameIDistToEtpBtn)
        self.txtDistToEtp.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDistToEtp.sizePolicy().hasHeightForWidth())
        self.txtDistToEtp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtDistToEtp.setFont(font)
        self.txtDistToEtp.setObjectName(_fromUtf8("txtDistToEtp"))
        self.horizontalLayout_DistToEtpBtn.addWidget(self.txtDistToEtp)
        self.btnCaptureDistToEtp = QtGui.QToolButton(self.frameIDistToEtpBtn)
        self.btnCaptureDistToEtp.setText(_fromUtf8(""))
        self.btnCaptureDistToEtp.setIcon(icon)
        self.btnCaptureDistToEtp.setObjectName(_fromUtf8("btnCaptureDistToEtp"))
        self.horizontalLayout_DistToEtpBtn.addWidget(self.btnCaptureDistToEtp)
        self.horizontalLayout_DistToEtp.addWidget(self.frameIDistToEtpBtn)
        self.verticalLayout_2.addWidget(self.frameDistToEtp)
        self.vlParametersTurnAreaObstacleAnalyser.addWidget(self.frameSecondTurn)
        self.framePerpendicularToTAOA = QtGui.QFrame(self.grbParametersTurnAreaObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePerpendicularToTAOA.sizePolicy().hasHeightForWidth())
        self.framePerpendicularToTAOA.setSizePolicy(sizePolicy)
        self.framePerpendicularToTAOA.setFrameShape(QtGui.QFrame.StyledPanel)
        self.framePerpendicularToTAOA.setFrameShadow(QtGui.QFrame.Raised)
        self.framePerpendicularToTAOA.setObjectName(_fromUtf8("framePerpendicularToTAOA"))
        self.horizontalLayout_PerpendicularToTAOA = QtGui.QHBoxLayout(self.framePerpendicularToTAOA)
        self.horizontalLayout_PerpendicularToTAOA.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_PerpendicularToTAOA.setObjectName(_fromUtf8("horizontalLayout_PerpendicularToTAOA"))
        self.chbPerpendicularToTAOA = QtGui.QCheckBox(self.framePerpendicularToTAOA)
        self.chbPerpendicularToTAOA.setMinimumSize(QtCore.QSize(150, 0))
        self.chbPerpendicularToTAOA.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbPerpendicularToTAOA.setFont(font)
        self.chbPerpendicularToTAOA.setObjectName(_fromUtf8("chbPerpendicularToTAOA"))
        self.horizontalLayout_PerpendicularToTAOA.addWidget(self.chbPerpendicularToTAOA)
        self.frameNominalTrackTAOA = QtGui.QFrame(self.framePerpendicularToTAOA)
        self.frameNominalTrackTAOA.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameNominalTrackTAOA.setFrameShadow(QtGui.QFrame.Raised)
        self.frameNominalTrackTAOA.setObjectName(_fromUtf8("frameNominalTrackTAOA"))
        self.horizontalLayout_NominalTrackTAOA = QtGui.QHBoxLayout(self.frameNominalTrackTAOA)
        self.horizontalLayout_NominalTrackTAOA.setSpacing(0)
        self.horizontalLayout_NominalTrackTAOA.setMargin(0)
        self.horizontalLayout_NominalTrackTAOA.setObjectName(_fromUtf8("horizontalLayout_NominalTrackTAOA"))
        self.label_NominalTrack_3 = QtGui.QLabel(self.frameNominalTrackTAOA)
        self.label_NominalTrack_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_NominalTrack_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_NominalTrack_3.setFont(font)
        self.label_NominalTrack_3.setObjectName(_fromUtf8("label_NominalTrack_3"))
        self.horizontalLayout_NominalTrackTAOA.addWidget(self.label_NominalTrack_3)
        self.frameINominalTrackBtnTAOA = QtGui.QFrame(self.frameNominalTrackTAOA)
        self.frameINominalTrackBtnTAOA.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameINominalTrackBtnTAOA.setFrameShadow(QtGui.QFrame.Raised)
        self.frameINominalTrackBtnTAOA.setObjectName(_fromUtf8("frameINominalTrackBtnTAOA"))
        self.horizontalLayout_NominalTrackBtnTAOA = QtGui.QHBoxLayout(self.frameINominalTrackBtnTAOA)
        self.horizontalLayout_NominalTrackBtnTAOA.setSpacing(0)
        self.horizontalLayout_NominalTrackBtnTAOA.setMargin(0)
        self.horizontalLayout_NominalTrackBtnTAOA.setObjectName(_fromUtf8("horizontalLayout_NominalTrackBtnTAOA"))
        self.txtNominalTrackTAOA = QtGui.QLineEdit(self.frameINominalTrackBtnTAOA)
        self.txtNominalTrackTAOA.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtNominalTrackTAOA.sizePolicy().hasHeightForWidth())
        self.txtNominalTrackTAOA.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtNominalTrackTAOA.setFont(font)
        self.txtNominalTrackTAOA.setObjectName(_fromUtf8("txtNominalTrackTAOA"))
        self.horizontalLayout_NominalTrackBtnTAOA.addWidget(self.txtNominalTrackTAOA)
        self.btnCaptureNominalTrackTAOA = QtGui.QToolButton(self.frameINominalTrackBtnTAOA)
        self.btnCaptureNominalTrackTAOA.setText(_fromUtf8(""))
        self.btnCaptureNominalTrackTAOA.setIcon(icon)
        self.btnCaptureNominalTrackTAOA.setObjectName(_fromUtf8("btnCaptureNominalTrackTAOA"))
        self.horizontalLayout_NominalTrackBtnTAOA.addWidget(self.btnCaptureNominalTrackTAOA)
        self.horizontalLayout_NominalTrackTAOA.addWidget(self.frameINominalTrackBtnTAOA)
        self.horizontalLayout_PerpendicularToTAOA.addWidget(self.frameNominalTrackTAOA)
        self.vlParametersTurnAreaObstacleAnalyser.addWidget(self.framePerpendicularToTAOA)
        self.chbStoreDistances = QtGui.QCheckBox(self.grbParametersTurnAreaObstacleAnalyser)
        self.chbStoreDistances.setMinimumSize(QtCore.QSize(150, 0))
        self.chbStoreDistances.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbStoreDistances.setFont(font)
        self.chbStoreDistances.setObjectName(_fromUtf8("chbStoreDistances"))
        self.vlParametersTurnAreaObstacleAnalyser.addWidget(self.chbStoreDistances)
        self.chbMultipleAreasTAOA = QtGui.QCheckBox(self.grbParametersTurnAreaObstacleAnalyser)
        self.chbMultipleAreasTAOA.setMinimumSize(QtCore.QSize(150, 0))
        self.chbMultipleAreasTAOA.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbMultipleAreasTAOA.setFont(font)
        self.chbMultipleAreasTAOA.setObjectName(_fromUtf8("chbMultipleAreasTAOA"))
        self.vlParametersTurnAreaObstacleAnalyser.addWidget(self.chbMultipleAreasTAOA)
        self.horizontalLayout_29.addWidget(self.grbParametersTurnAreaObstacleAnalyser)
        self.tabCtrlGeneral.addTab(self.tab_TurnAreaObstacleAnalyser, _fromUtf8(""))
        self.tab_StepDownObstacleAnalyser = QtGui.QWidget()
        self.tab_StepDownObstacleAnalyser.setObjectName(_fromUtf8("tab_StepDownObstacleAnalyser"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_StepDownObstacleAnalyser)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.grbParametersStepDownObstacleAnalyser = QtGui.QGroupBox(self.tab_StepDownObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grbParametersStepDownObstacleAnalyser.sizePolicy().hasHeightForWidth())
        self.grbParametersStepDownObstacleAnalyser.setSizePolicy(sizePolicy)
        self.grbParametersStepDownObstacleAnalyser.setObjectName(_fromUtf8("grbParametersStepDownObstacleAnalyser"))
        self.vlParametersStepDownObstacleAnalyser = QtGui.QVBoxLayout(self.grbParametersStepDownObstacleAnalyser)
        self.vlParametersStepDownObstacleAnalyser.setMargin(6)
        self.vlParametersStepDownObstacleAnalyser.setObjectName(_fromUtf8("vlParametersStepDownObstacleAnalyser"))
        self.frameNominalTrackSDOA = QtGui.QFrame(self.grbParametersStepDownObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameNominalTrackSDOA.sizePolicy().hasHeightForWidth())
        self.frameNominalTrackSDOA.setSizePolicy(sizePolicy)
        self.frameNominalTrackSDOA.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameNominalTrackSDOA.setFrameShadow(QtGui.QFrame.Raised)
        self.frameNominalTrackSDOA.setObjectName(_fromUtf8("frameNominalTrackSDOA"))
        self.horizontalLayout_NominalTrackSDOA = QtGui.QHBoxLayout(self.frameNominalTrackSDOA)
        self.horizontalLayout_NominalTrackSDOA.setSpacing(0)
        self.horizontalLayout_NominalTrackSDOA.setMargin(0)
        self.horizontalLayout_NominalTrackSDOA.setObjectName(_fromUtf8("horizontalLayout_NominalTrackSDOA"))
        self.label_NominalTrack_4 = QtGui.QLabel(self.frameNominalTrackSDOA)
        self.label_NominalTrack_4.setMinimumSize(QtCore.QSize(150, 0))
        self.label_NominalTrack_4.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_NominalTrack_4.setFont(font)
        self.label_NominalTrack_4.setObjectName(_fromUtf8("label_NominalTrack_4"))
        self.horizontalLayout_NominalTrackSDOA.addWidget(self.label_NominalTrack_4)
        self.frameINominalTrackBtnSDOA = QtGui.QFrame(self.frameNominalTrackSDOA)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameINominalTrackBtnSDOA.sizePolicy().hasHeightForWidth())
        self.frameINominalTrackBtnSDOA.setSizePolicy(sizePolicy)
        self.frameINominalTrackBtnSDOA.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameINominalTrackBtnSDOA.setFrameShadow(QtGui.QFrame.Raised)
        self.frameINominalTrackBtnSDOA.setObjectName(_fromUtf8("frameINominalTrackBtnSDOA"))
        self.horizontalLayout_NominalTrackBtnSDOA = QtGui.QHBoxLayout(self.frameINominalTrackBtnSDOA)
        self.horizontalLayout_NominalTrackBtnSDOA.setSpacing(0)
        self.horizontalLayout_NominalTrackBtnSDOA.setMargin(0)
        self.horizontalLayout_NominalTrackBtnSDOA.setObjectName(_fromUtf8("horizontalLayout_NominalTrackBtnSDOA"))
        self.txtNominalTrackSDOA = QtGui.QLineEdit(self.frameINominalTrackBtnSDOA)
        self.txtNominalTrackSDOA.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtNominalTrackSDOA.sizePolicy().hasHeightForWidth())
        self.txtNominalTrackSDOA.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtNominalTrackSDOA.setFont(font)
        self.txtNominalTrackSDOA.setObjectName(_fromUtf8("txtNominalTrackSDOA"))
        self.horizontalLayout_NominalTrackBtnSDOA.addWidget(self.txtNominalTrackSDOA)
        self.btnCaptureNominalTrackSDOA = QtGui.QToolButton(self.frameINominalTrackBtnSDOA)
        self.btnCaptureNominalTrackSDOA.setText(_fromUtf8(""))
        self.btnCaptureNominalTrackSDOA.setIcon(icon)
        self.btnCaptureNominalTrackSDOA.setObjectName(_fromUtf8("btnCaptureNominalTrackSDOA"))
        self.horizontalLayout_NominalTrackBtnSDOA.addWidget(self.btnCaptureNominalTrackSDOA)
        self.horizontalLayout_NominalTrackSDOA.addWidget(self.frameINominalTrackBtnSDOA)
        self.vlParametersStepDownObstacleAnalyser.addWidget(self.frameNominalTrackSDOA)
        self.frameSlope = QtGui.QFrame(self.grbParametersStepDownObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameSlope.sizePolicy().hasHeightForWidth())
        self.frameSlope.setSizePolicy(sizePolicy)
        self.frameSlope.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameSlope.setFrameShadow(QtGui.QFrame.Raised)
        self.frameSlope.setObjectName(_fromUtf8("frameSlope"))
        self.horizontalLayout_Slope = QtGui.QHBoxLayout(self.frameSlope)
        self.horizontalLayout_Slope.setSpacing(6)
        self.horizontalLayout_Slope.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_Slope.setObjectName(_fromUtf8("horizontalLayout_Slope"))
        self.label_90 = QtGui.QLabel(self.frameSlope)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_90.sizePolicy().hasHeightForWidth())
        self.label_90.setSizePolicy(sizePolicy)
        self.label_90.setMinimumSize(QtCore.QSize(150, 0))
        self.label_90.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_90.setFont(font)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.horizontalLayout_Slope.addWidget(self.label_90)
        self.txtSlope = QtGui.QLineEdit(self.frameSlope)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtSlope.setFont(font)
        self.txtSlope.setText(_fromUtf8(""))
        self.txtSlope.setObjectName(_fromUtf8("txtSlope"))
        self.horizontalLayout_Slope.addWidget(self.txtSlope)
        self.vlParametersStepDownObstacleAnalyser.addWidget(self.frameSlope)
        self.framePrevOCA = QtGui.QFrame(self.grbParametersStepDownObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePrevOCA.sizePolicy().hasHeightForWidth())
        self.framePrevOCA.setSizePolicy(sizePolicy)
        self.framePrevOCA.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePrevOCA.setFrameShadow(QtGui.QFrame.Raised)
        self.framePrevOCA.setObjectName(_fromUtf8("framePrevOCA"))
        self.horizontalLayout_PrevOCA = QtGui.QHBoxLayout(self.framePrevOCA)
        self.horizontalLayout_PrevOCA.setSpacing(6)
        self.horizontalLayout_PrevOCA.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_PrevOCA.setObjectName(_fromUtf8("horizontalLayout_PrevOCA"))
        self.label_91 = QtGui.QLabel(self.framePrevOCA)
        self.label_91.setMinimumSize(QtCore.QSize(150, 0))
        self.label_91.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_91.setFont(font)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.horizontalLayout_PrevOCA.addWidget(self.label_91)
        self.txtPrevOCAM = QtGui.QLineEdit(self.framePrevOCA)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPrevOCAM.setFont(font)
        self.txtPrevOCAM.setText(_fromUtf8(""))
        self.txtPrevOCAM.setObjectName(_fromUtf8("txtPrevOCAM"))
        self.horizontalLayout_PrevOCA.addWidget(self.txtPrevOCAM)
        self.label_15 = QtGui.QLabel(self.framePrevOCA)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_PrevOCA.addWidget(self.label_15)
        self.txtPrevOCA = QtGui.QLineEdit(self.framePrevOCA)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPrevOCA.setFont(font)
        self.txtPrevOCA.setObjectName(_fromUtf8("txtPrevOCA"))
        self.horizontalLayout_PrevOCA.addWidget(self.txtPrevOCA)
        self.label_16 = QtGui.QLabel(self.framePrevOCA)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_PrevOCA.addWidget(self.label_16)
        self.vlParametersStepDownObstacleAnalyser.addWidget(self.framePrevOCA)
        self.framePrevMOC = QtGui.QFrame(self.grbParametersStepDownObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePrevMOC.sizePolicy().hasHeightForWidth())
        self.framePrevMOC.setSizePolicy(sizePolicy)
        self.framePrevMOC.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePrevMOC.setFrameShadow(QtGui.QFrame.Raised)
        self.framePrevMOC.setObjectName(_fromUtf8("framePrevMOC"))
        self.horizontalLayout_PrevMOC = QtGui.QHBoxLayout(self.framePrevMOC)
        self.horizontalLayout_PrevMOC.setSpacing(6)
        self.horizontalLayout_PrevMOC.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_PrevMOC.setObjectName(_fromUtf8("horizontalLayout_PrevMOC"))
        self.label_92 = QtGui.QLabel(self.framePrevMOC)
        self.label_92.setMinimumSize(QtCore.QSize(150, 0))
        self.label_92.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_92.setFont(font)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.horizontalLayout_PrevMOC.addWidget(self.label_92)
        self.txtPrevMOC = QtGui.QLineEdit(self.framePrevMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPrevMOC.setFont(font)
        self.txtPrevMOC.setObjectName(_fromUtf8("txtPrevMOC"))
        self.horizontalLayout_PrevMOC.addWidget(self.txtPrevMOC)
        self.label_17 = QtGui.QLabel(self.framePrevMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_PrevMOC.addWidget(self.label_17)
        self.txtPrevMOCFt = QtGui.QLineEdit(self.framePrevMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPrevMOCFt.setFont(font)
        self.txtPrevMOCFt.setText(_fromUtf8(""))
        self.txtPrevMOCFt.setObjectName(_fromUtf8("txtPrevMOCFt"))
        self.horizontalLayout_PrevMOC.addWidget(self.txtPrevMOCFt)
        self.label_18 = QtGui.QLabel(self.framePrevMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_PrevMOC.addWidget(self.label_18)
        self.vlParametersStepDownObstacleAnalyser.addWidget(self.framePrevMOC)
        self.frameNextMOC = QtGui.QFrame(self.grbParametersStepDownObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameNextMOC.sizePolicy().hasHeightForWidth())
        self.frameNextMOC.setSizePolicy(sizePolicy)
        self.frameNextMOC.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameNextMOC.setFrameShadow(QtGui.QFrame.Raised)
        self.frameNextMOC.setObjectName(_fromUtf8("frameNextMOC"))
        self.horizontalLayout_NextMOC = QtGui.QHBoxLayout(self.frameNextMOC)
        self.horizontalLayout_NextMOC.setSpacing(6)
        self.horizontalLayout_NextMOC.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_NextMOC.setObjectName(_fromUtf8("horizontalLayout_NextMOC"))
        self.label_93 = QtGui.QLabel(self.frameNextMOC)
        self.label_93.setMinimumSize(QtCore.QSize(150, 0))
        self.label_93.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_93.setFont(font)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.horizontalLayout_NextMOC.addWidget(self.label_93)
        self.txtNextMOC = QtGui.QLineEdit(self.frameNextMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtNextMOC.setFont(font)
        self.txtNextMOC.setObjectName(_fromUtf8("txtNextMOC"))
        self.horizontalLayout_NextMOC.addWidget(self.txtNextMOC)
        self.label_19 = QtGui.QLabel(self.frameNextMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_NextMOC.addWidget(self.label_19)
        self.txtNextMOCFt = QtGui.QLineEdit(self.frameNextMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtNextMOCFt.setFont(font)
        self.txtNextMOCFt.setText(_fromUtf8(""))
        self.txtNextMOCFt.setObjectName(_fromUtf8("txtNextMOCFt"))
        self.horizontalLayout_NextMOC.addWidget(self.txtNextMOCFt)
        self.label_20 = QtGui.QLabel(self.frameNextMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_NextMOC.addWidget(self.label_20)
        self.vlParametersStepDownObstacleAnalyser.addWidget(self.frameNextMOC)
        self.chbMultipleAreasSDOA = QtGui.QCheckBox(self.grbParametersStepDownObstacleAnalyser)
        self.chbMultipleAreasSDOA.setMinimumSize(QtCore.QSize(150, 0))
        self.chbMultipleAreasSDOA.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbMultipleAreasSDOA.setFont(font)
        self.chbMultipleAreasSDOA.setObjectName(_fromUtf8("chbMultipleAreasSDOA"))
        self.vlParametersStepDownObstacleAnalyser.addWidget(self.chbMultipleAreasSDOA)
        self.verticalLayout_3.addWidget(self.grbParametersStepDownObstacleAnalyser)
        self.tabCtrlGeneral.addTab(self.tab_StepDownObstacleAnalyser, _fromUtf8(""))
        self.tab_InitialMissedApproachObstacleAnalyser = QtGui.QWidget()
        self.tab_InitialMissedApproachObstacleAnalyser.setObjectName(_fromUtf8("tab_InitialMissedApproachObstacleAnalyser"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_InitialMissedApproachObstacleAnalyser)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.grbParametersInitialMissedApproachObstacleAnalyser = QtGui.QGroupBox(self.tab_InitialMissedApproachObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grbParametersInitialMissedApproachObstacleAnalyser.sizePolicy().hasHeightForWidth())
        self.grbParametersInitialMissedApproachObstacleAnalyser.setSizePolicy(sizePolicy)
        self.grbParametersInitialMissedApproachObstacleAnalyser.setObjectName(_fromUtf8("grbParametersInitialMissedApproachObstacleAnalyser"))
        self.vlParametersStepDownObstacleAnalyser_2 = QtGui.QVBoxLayout(self.grbParametersInitialMissedApproachObstacleAnalyser)
        self.vlParametersStepDownObstacleAnalyser_2.setMargin(6)
        self.vlParametersStepDownObstacleAnalyser_2.setObjectName(_fromUtf8("vlParametersStepDownObstacleAnalyser_2"))
        self.frameX = QtGui.QFrame(self.grbParametersInitialMissedApproachObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameX.sizePolicy().hasHeightForWidth())
        self.frameX.setSizePolicy(sizePolicy)
        self.frameX.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameX.setFrameShadow(QtGui.QFrame.Raised)
        self.frameX.setObjectName(_fromUtf8("frameX"))
        self.horizontalLayout_X = QtGui.QHBoxLayout(self.frameX)
        self.horizontalLayout_X.setSpacing(0)
        self.horizontalLayout_X.setMargin(0)
        self.horizontalLayout_X.setObjectName(_fromUtf8("horizontalLayout_X"))
        self.label_X = QtGui.QLabel(self.frameX)
        self.label_X.setMinimumSize(QtCore.QSize(200, 0))
        self.label_X.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_X.setFont(font)
        self.label_X.setObjectName(_fromUtf8("label_X"))
        self.horizontalLayout_X.addWidget(self.label_X)
        self.frameIX = QtGui.QFrame(self.frameX)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameIX.sizePolicy().hasHeightForWidth())
        self.frameIX.setSizePolicy(sizePolicy)
        self.frameIX.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameIX.setFrameShadow(QtGui.QFrame.Raised)
        self.frameIX.setObjectName(_fromUtf8("frameIX"))
        self.horizontalLayout_X_2 = QtGui.QHBoxLayout(self.frameIX)
        self.horizontalLayout_X_2.setSpacing(0)
        self.horizontalLayout_X_2.setMargin(0)
        self.horizontalLayout_X_2.setObjectName(_fromUtf8("horizontalLayout_X_2"))
        self.txtX = QtGui.QLineEdit(self.frameIX)
        self.txtX.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtX.sizePolicy().hasHeightForWidth())
        self.txtX.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtX.setFont(font)
        self.txtX.setObjectName(_fromUtf8("txtX"))
        self.horizontalLayout_X_2.addWidget(self.txtX)
        self.btnCaptureX = QtGui.QToolButton(self.frameIX)
        self.btnCaptureX.setText(_fromUtf8(""))
        self.btnCaptureX.setIcon(icon)
        self.btnCaptureX.setObjectName(_fromUtf8("btnCaptureX"))
        self.horizontalLayout_X_2.addWidget(self.btnCaptureX)
        self.horizontalLayout_X.addWidget(self.frameIX)
        self.vlParametersStepDownObstacleAnalyser_2.addWidget(self.frameX)
        self.frameNominalTrackIMAOA = QtGui.QFrame(self.grbParametersInitialMissedApproachObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameNominalTrackIMAOA.sizePolicy().hasHeightForWidth())
        self.frameNominalTrackIMAOA.setSizePolicy(sizePolicy)
        self.frameNominalTrackIMAOA.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameNominalTrackIMAOA.setFrameShadow(QtGui.QFrame.Raised)
        self.frameNominalTrackIMAOA.setObjectName(_fromUtf8("frameNominalTrackIMAOA"))
        self.horizontalLayout_NominalTrackIMAOA = QtGui.QHBoxLayout(self.frameNominalTrackIMAOA)
        self.horizontalLayout_NominalTrackIMAOA.setSpacing(0)
        self.horizontalLayout_NominalTrackIMAOA.setMargin(0)
        self.horizontalLayout_NominalTrackIMAOA.setObjectName(_fromUtf8("horizontalLayout_NominalTrackIMAOA"))
        self.label_IMAOA = QtGui.QLabel(self.frameNominalTrackIMAOA)
        self.label_IMAOA.setMinimumSize(QtCore.QSize(200, 0))
        self.label_IMAOA.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_IMAOA.setFont(font)
        self.label_IMAOA.setObjectName(_fromUtf8("label_IMAOA"))
        self.horizontalLayout_NominalTrackIMAOA.addWidget(self.label_IMAOA)
        self.frameINominalTrackBtnIMAOA = QtGui.QFrame(self.frameNominalTrackIMAOA)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameINominalTrackBtnIMAOA.sizePolicy().hasHeightForWidth())
        self.frameINominalTrackBtnIMAOA.setSizePolicy(sizePolicy)
        self.frameINominalTrackBtnIMAOA.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameINominalTrackBtnIMAOA.setFrameShadow(QtGui.QFrame.Raised)
        self.frameINominalTrackBtnIMAOA.setObjectName(_fromUtf8("frameINominalTrackBtnIMAOA"))
        self.horizontalLayout_NominalTrackBtnIMAOA = QtGui.QHBoxLayout(self.frameINominalTrackBtnIMAOA)
        self.horizontalLayout_NominalTrackBtnIMAOA.setSpacing(0)
        self.horizontalLayout_NominalTrackBtnIMAOA.setMargin(0)
        self.horizontalLayout_NominalTrackBtnIMAOA.setObjectName(_fromUtf8("horizontalLayout_NominalTrackBtnIMAOA"))
        self.txtNominalTrackIMAOA = QtGui.QLineEdit(self.frameINominalTrackBtnIMAOA)
        self.txtNominalTrackIMAOA.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtNominalTrackIMAOA.sizePolicy().hasHeightForWidth())
        self.txtNominalTrackIMAOA.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtNominalTrackIMAOA.setFont(font)
        self.txtNominalTrackIMAOA.setObjectName(_fromUtf8("txtNominalTrackIMAOA"))
        self.horizontalLayout_NominalTrackBtnIMAOA.addWidget(self.txtNominalTrackIMAOA)
        self.btnCaptureNominalTrackIMAOA = QtGui.QToolButton(self.frameINominalTrackBtnIMAOA)
        self.btnCaptureNominalTrackIMAOA.setText(_fromUtf8(""))
        self.btnCaptureNominalTrackIMAOA.setIcon(icon)
        self.btnCaptureNominalTrackIMAOA.setObjectName(_fromUtf8("btnCaptureNominalTrackIMAOA"))
        self.horizontalLayout_NominalTrackBtnIMAOA.addWidget(self.btnCaptureNominalTrackIMAOA)
        self.horizontalLayout_NominalTrackIMAOA.addWidget(self.frameINominalTrackBtnIMAOA)
        self.vlParametersStepDownObstacleAnalyser_2.addWidget(self.frameNominalTrackIMAOA)
        self.frameFinalMOC = QtGui.QFrame(self.grbParametersInitialMissedApproachObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameFinalMOC.sizePolicy().hasHeightForWidth())
        self.frameFinalMOC.setSizePolicy(sizePolicy)
        self.frameFinalMOC.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameFinalMOC.setFrameShadow(QtGui.QFrame.Raised)
        self.frameFinalMOC.setObjectName(_fromUtf8("frameFinalMOC"))
        self.horizontalLayout_FinalMOC = QtGui.QHBoxLayout(self.frameFinalMOC)
        self.horizontalLayout_FinalMOC.setSpacing(6)
        self.horizontalLayout_FinalMOC.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_FinalMOC.setObjectName(_fromUtf8("horizontalLayout_FinalMOC"))
        self.label_96 = QtGui.QLabel(self.frameFinalMOC)
        self.label_96.setMinimumSize(QtCore.QSize(200, 0))
        self.label_96.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_96.setFont(font)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.horizontalLayout_FinalMOC.addWidget(self.label_96)
        self.txtFinalMOC = QtGui.QLineEdit(self.frameFinalMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtFinalMOC.setFont(font)
        self.txtFinalMOC.setObjectName(_fromUtf8("txtFinalMOC"))
        self.horizontalLayout_FinalMOC.addWidget(self.txtFinalMOC)
        self.label_23 = QtGui.QLabel(self.frameFinalMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_FinalMOC.addWidget(self.label_23)
        self.txtFinalMOCFt = QtGui.QLineEdit(self.frameFinalMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtFinalMOCFt.setFont(font)
        self.txtFinalMOCFt.setText(_fromUtf8(""))
        self.txtFinalMOCFt.setObjectName(_fromUtf8("txtFinalMOCFt"))
        self.horizontalLayout_FinalMOC.addWidget(self.txtFinalMOCFt)
        self.label_24 = QtGui.QLabel(self.frameFinalMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_FinalMOC.addWidget(self.label_24)
        self.vlParametersStepDownObstacleAnalyser_2.addWidget(self.frameFinalMOC)
        self.frameMissedMOC = QtGui.QFrame(self.grbParametersInitialMissedApproachObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameMissedMOC.sizePolicy().hasHeightForWidth())
        self.frameMissedMOC.setSizePolicy(sizePolicy)
        self.frameMissedMOC.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMissedMOC.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMissedMOC.setObjectName(_fromUtf8("frameMissedMOC"))
        self.horizontalLayout_MissedMOC = QtGui.QHBoxLayout(self.frameMissedMOC)
        self.horizontalLayout_MissedMOC.setSpacing(6)
        self.horizontalLayout_MissedMOC.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_MissedMOC.setObjectName(_fromUtf8("horizontalLayout_MissedMOC"))
        self.label_97 = QtGui.QLabel(self.frameMissedMOC)
        self.label_97.setMinimumSize(QtCore.QSize(200, 0))
        self.label_97.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_97.setFont(font)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.horizontalLayout_MissedMOC.addWidget(self.label_97)
        self.txtMissedMOC = QtGui.QLineEdit(self.frameMissedMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMissedMOC.setFont(font)
        self.txtMissedMOC.setObjectName(_fromUtf8("txtMissedMOC"))
        self.horizontalLayout_MissedMOC.addWidget(self.txtMissedMOC)
        self.label_25 = QtGui.QLabel(self.frameMissedMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_MissedMOC.addWidget(self.label_25)
        self.txtMissedMOCFt = QtGui.QLineEdit(self.frameMissedMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMissedMOCFt.setFont(font)
        self.txtMissedMOCFt.setText(_fromUtf8(""))
        self.txtMissedMOCFt.setObjectName(_fromUtf8("txtMissedMOCFt"))
        self.horizontalLayout_MissedMOC.addWidget(self.txtMissedMOCFt)
        self.label_26 = QtGui.QLabel(self.frameMissedMOC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_MissedMOC.addWidget(self.label_26)
        self.vlParametersStepDownObstacleAnalyser_2.addWidget(self.frameMissedMOC)
        self.frameGradient = QtGui.QFrame(self.grbParametersInitialMissedApproachObstacleAnalyser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameGradient.sizePolicy().hasHeightForWidth())
        self.frameGradient.setSizePolicy(sizePolicy)
        self.frameGradient.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameGradient.setFrameShadow(QtGui.QFrame.Raised)
        self.frameGradient.setObjectName(_fromUtf8("frameGradient"))
        self.horizontalLayout_Gradient = QtGui.QHBoxLayout(self.frameGradient)
        self.horizontalLayout_Gradient.setSpacing(6)
        self.horizontalLayout_Gradient.setContentsMargins(0, 6, 0, 6)
        self.horizontalLayout_Gradient.setObjectName(_fromUtf8("horizontalLayout_Gradient"))
        self.label_94 = QtGui.QLabel(self.frameGradient)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_94.sizePolicy().hasHeightForWidth())
        self.label_94.setSizePolicy(sizePolicy)
        self.label_94.setMinimumSize(QtCore.QSize(200, 0))
        self.label_94.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_94.setFont(font)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.horizontalLayout_Gradient.addWidget(self.label_94)
        self.txtGradient = QtGui.QLineEdit(self.frameGradient)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtGradient.setFont(font)
        self.txtGradient.setText(_fromUtf8(""))
        self.txtGradient.setObjectName(_fromUtf8("txtGradient"))
        self.horizontalLayout_Gradient.addWidget(self.txtGradient)
        self.vlParametersStepDownObstacleAnalyser_2.addWidget(self.frameGradient)
        self.chbMultipleAreasIMAOA = QtGui.QCheckBox(self.grbParametersInitialMissedApproachObstacleAnalyser)
        self.chbMultipleAreasIMAOA.setMinimumSize(QtCore.QSize(150, 0))
        self.chbMultipleAreasIMAOA.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbMultipleAreasIMAOA.setFont(font)
        self.chbMultipleAreasIMAOA.setObjectName(_fromUtf8("chbMultipleAreasIMAOA"))
        self.vlParametersStepDownObstacleAnalyser_2.addWidget(self.chbMultipleAreasIMAOA)
        self.verticalLayout_4.addWidget(self.grbParametersInitialMissedApproachObstacleAnalyser)
        self.tabCtrlGeneral.addTab(self.tab_InitialMissedApproachObstacleAnalyser, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabCtrlGeneral)

        self.retranslateUi(ObstacleEvaluator)
        self.tabCtrlGeneral.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ObstacleEvaluator)

    def retranslateUi(self, ObstacleEvaluator):
        ObstacleEvaluator.setWindowTitle(_translate("ObstacleEvaluator", "Obstacle Evaluator”", None))
        self.grbParametersSecondaryMoc.setTitle(_translate("ObstacleEvaluator", "Parameters", None))
        self.label_67.setText(_translate("ObstacleEvaluator", "Evaluation Mode:", None))
        self.label_79.setText(_translate("ObstacleEvaluator", "Primary MOC:", None))
        self.txtPrimaryMOC.setText(_translate("ObstacleEvaluator", "300", None))
        self.label_3.setText(_translate("ObstacleEvaluator", "m", None))
        self.label_4.setText(_translate("ObstacleEvaluator", "ft", None))
        self.chbInsertPointAndText.setText(_translate("ObstacleEvaluator", "Insert Point And Text", None))
        self.label_74.setText(_translate("ObstacleEvaluator", "Text Height:", None))
        self.chbPerpendicularToSMC.setText(_translate("ObstacleEvaluator", "Perpendicular To", None))
        self.label_NominalTrack.setText(_translate("ObstacleEvaluator", "Nominal Trackl(°):", None))
        self.txtNominalTrackSMC.setText(_translate("ObstacleEvaluator", "180", None))
        self.chbMultipleAreasSMC.setText(_translate("ObstacleEvaluator", "Multiple Areas", None))
        self.tabCtrlGeneral.setTabText(self.tabCtrlGeneral.indexOf(self.tab_SecondaryMoc), _translate("ObstacleEvaluator", "Secondary MOC Calculation", None))
        self.grbParametersTurnAreaObstacleAnalyser.setTitle(_translate("ObstacleEvaluator", "Parameters", None))
        self.label_68.setText(_translate("ObstacleEvaluator", "Used For:", None))
        self.label_69.setText(_translate("ObstacleEvaluator", "Portion:", None))
        self.label_76.setText(_translate("ObstacleEvaluator", "Track(°):", None))
        self.label_80.setText(_translate("ObstacleEvaluator", "Initial MOC Value:", None))
        self.txtStartingMOC.setText(_translate("ObstacleEvaluator", "300", None))
        self.label_5.setText(_translate("ObstacleEvaluator", "m", None))
        self.label_6.setText(_translate("ObstacleEvaluator", "ft", None))
        self.label_77.setText(_translate("ObstacleEvaluator", "MOC(%):", None))
        self.label_78.setText(_translate("ObstacleEvaluator", "MOC:", None))
        self.label_82.setText(_translate("ObstacleEvaluator", "Greater of (m):", None))
        self.label_83.setText(_translate("ObstacleEvaluator", "or (%):", None))
        self.label_81.setText(_translate("ObstacleEvaluator", " MOC:", None))
        self.txtMaMocS.setText(_translate("ObstacleEvaluator", "300", None))
        self.label_7.setText(_translate("ObstacleEvaluator", "m", None))
        self.label_8.setText(_translate("ObstacleEvaluator", "ft", None))
        self.label_84.setText(_translate("ObstacleEvaluator", " MOC:", None))
        self.txtMaMocT.setText(_translate("ObstacleEvaluator", "300", None))
        self.label_9.setText(_translate("ObstacleEvaluator", "m", None))
        self.label_10.setText(_translate("ObstacleEvaluator", "ft", None))
        self.label_85.setText(_translate("ObstacleEvaluator", "PDG(%):", None))
        self.label_86.setText(_translate("ObstacleEvaluator", "MACG(%):", None))
        self.label_87.setText(_translate("ObstacleEvaluator", "Turning Altitude:", None))
        self.label_11.setText(_translate("ObstacleEvaluator", "m", None))
        self.txtTurningAltitudeM.setText(_translate("ObstacleEvaluator", "300", None))
        self.label_12.setText(_translate("ObstacleEvaluator", "ft", None))
        self.chbMultipleAreas_2.setText(_translate("ObstacleEvaluator", "Multiple Areas", None))
        self.label_NominalTrack_2.setText(_translate("ObstacleEvaluator", "Dist. DER -&gt; ETP(m):", None))
        self.txtDistToEtp.setText(_translate("ObstacleEvaluator", "180", None))
        self.chbPerpendicularToTAOA.setText(_translate("ObstacleEvaluator", "Perpendicular To", None))
        self.label_NominalTrack_3.setText(_translate("ObstacleEvaluator", "Nominal Trackl(°):", None))
        self.txtNominalTrackTAOA.setText(_translate("ObstacleEvaluator", "180", None))
        self.chbStoreDistances.setText(_translate("ObstacleEvaluator", "Store calculated \"Dz\" / \"Dr\" and \"Do\" distances", None))
        self.chbMultipleAreasTAOA.setText(_translate("ObstacleEvaluator", "Multiple Areas", None))
        self.tabCtrlGeneral.setTabText(self.tabCtrlGeneral.indexOf(self.tab_TurnAreaObstacleAnalyser), _translate("ObstacleEvaluator", "Turn Area Obstacle Analyser", None))
        self.grbParametersStepDownObstacleAnalyser.setTitle(_translate("ObstacleEvaluator", "Parameters", None))
        self.label_NominalTrack_4.setText(_translate("ObstacleEvaluator", "Nominal Trackl(°):", None))
        self.txtNominalTrackSDOA.setText(_translate("ObstacleEvaluator", "180", None))
        self.label_90.setText(_translate("ObstacleEvaluator", "Slope(%):", None))
        self.label_91.setText(_translate("ObstacleEvaluator", "Preceding Segment OCA:", None))
        self.label_15.setText(_translate("ObstacleEvaluator", "m", None))
        self.txtPrevOCAM.setText(_translate("ObstacleEvaluator", "300", None))
        self.label_16.setText(_translate("ObstacleEvaluator", "ft", None))
        self.label_92.setText(_translate("ObstacleEvaluator", "Preceding Segment MOC:", None))
        self.txtPrevMOC.setText(_translate("ObstacleEvaluator", "300", None))
        self.label_17.setText(_translate("ObstacleEvaluator", "m", None))
        self.label_18.setText(_translate("ObstacleEvaluator", "ft", None))
        self.label_93.setText(_translate("ObstacleEvaluator", "Subsequent Segment MOC:", None))
        self.txtNextMOC.setText(_translate("ObstacleEvaluator", "300", None))
        self.label_19.setText(_translate("ObstacleEvaluator", "m", None))
        self.label_20.setText(_translate("ObstacleEvaluator", "ft", None))
        self.chbMultipleAreasSDOA.setText(_translate("ObstacleEvaluator", "Multiple Areas", None))
        self.tabCtrlGeneral.setTabText(self.tabCtrlGeneral.indexOf(self.tab_StepDownObstacleAnalyser), _translate("ObstacleEvaluator", "15% Area Obstacle Analyser", None))
        self.grbParametersInitialMissedApproachObstacleAnalyser.setTitle(_translate("ObstacleEvaluator", "Parameters", None))
        self.label_X.setText(_translate("ObstacleEvaluator", "X [Latest MAPt -&gt; SOC]l(m):", None))
        self.txtX.setText(_translate("ObstacleEvaluator", "180", None))
        self.label_IMAOA.setText(_translate("ObstacleEvaluator", "Nominal Trackl(°):", None))
        self.txtNominalTrackIMAOA.setText(_translate("ObstacleEvaluator", "180", None))
        self.label_96.setText(_translate("ObstacleEvaluator", "Final Approach MOC:", None))
        self.txtFinalMOC.setText(_translate("ObstacleEvaluator", "300", None))
        self.label_23.setText(_translate("ObstacleEvaluator", "m", None))
        self.label_24.setText(_translate("ObstacleEvaluator", "ft", None))
        self.label_97.setText(_translate("ObstacleEvaluator", "Missed Approach MOC:", None))
        self.txtMissedMOC.setText(_translate("ObstacleEvaluator", "300", None))
        self.label_25.setText(_translate("ObstacleEvaluator", "m", None))
        self.label_26.setText(_translate("ObstacleEvaluator", "ft", None))
        self.label_94.setText(_translate("ObstacleEvaluator", "Missed Approach Climb Gradient(%):", None))
        self.chbMultipleAreasIMAOA.setText(_translate("ObstacleEvaluator", "Multiple Areas", None))
        self.tabCtrlGeneral.setTabText(self.tabCtrlGeneral.indexOf(self.tab_InitialMissedApproachObstacleAnalyser), _translate("ObstacleEvaluator", "Initial Missed Approach Obstacle Analyser", None))

