# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RnpRegDlg.ui'
#
# Created: Sat Apr 04 18:01:39 2015
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_RnpRegDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(268, 252)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_Rnd = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Rnd.sizePolicy().hasHeightForWidth())
        self.frame_Rnd.setSizePolicy(sizePolicy)
        self.frame_Rnd.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Rnd.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Rnd.setObjectName(_fromUtf8("frame_Rnd"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.frame_Rnd)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setMargin(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_9 = QtGui.QLabel(self.frame_Rnd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setWeight(50)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_20.addWidget(self.label_9)
        self.txtRnpValue = QtGui.QLineEdit(self.frame_Rnd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtRnpValue.sizePolicy().hasHeightForWidth())
        self.txtRnpValue.setSizePolicy(sizePolicy)
        self.txtRnpValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.txtRnpValue.setFont(font)
        self.txtRnpValue.setObjectName(_fromUtf8("txtRnpValue"))
        self.horizontalLayout_20.addWidget(self.txtRnpValue)
        self.verticalLayout_2.addWidget(self.frame_Rnd)
        self.frame_Altitude = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Altitude.sizePolicy().hasHeightForWidth())
        self.frame_Altitude.setSizePolicy(sizePolicy)
        self.frame_Altitude.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Altitude.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Altitude.setObjectName(_fromUtf8("frame_Altitude"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.frame_Altitude)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setMargin(0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_10 = QtGui.QLabel(self.frame_Altitude)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(70, 0))
        self.label_10.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setWeight(50)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_21.addWidget(self.label_10)
        self.txtAltitude = QtGui.QLineEdit(self.frame_Altitude)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAltitude.sizePolicy().hasHeightForWidth())
        self.txtAltitude.setSizePolicy(sizePolicy)
        self.txtAltitude.setMinimumSize(QtCore.QSize(0, 0))
        self.txtAltitude.setObjectName(_fromUtf8("txtAltitude"))
        self.horizontalLayout_21.addWidget(self.txtAltitude)
        self.btnAltitude = QtGui.QToolButton(self.frame_Altitude)
        self.btnAltitude.setObjectName(_fromUtf8("btnAltitude"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Calculator.bmp")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAltitude.setIcon(icon1)
        self.horizontalLayout_21.addWidget(self.btnAltitude)
        self.verticalLayout_2.addWidget(self.frame_Altitude)
        self.frame_Wind = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Wind.sizePolicy().hasHeightForWidth())
        self.frame_Wind.setSizePolicy(sizePolicy)
        self.frame_Wind.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Wind.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Wind.setObjectName(_fromUtf8("frame_Wind"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.frame_Wind)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setMargin(0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_11 = QtGui.QLabel(self.frame_Wind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setWeight(50)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_22.addWidget(self.label_11)
        self.txtWind = QtGui.QLineEdit(self.frame_Wind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtWind.sizePolicy().hasHeightForWidth())
        self.txtWind.setSizePolicy(sizePolicy)
        self.txtWind.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.txtWind.setFont(font)
        self.txtWind.setObjectName(_fromUtf8("txtWind"))
        self.horizontalLayout_22.addWidget(self.txtWind)
        self.verticalLayout_2.addWidget(self.frame_Wind)
        self.frame_Bank = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Bank.sizePolicy().hasHeightForWidth())
        self.frame_Bank.setSizePolicy(sizePolicy)
        self.frame_Bank.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Bank.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Bank.setObjectName(_fromUtf8("frame_Bank"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.frame_Bank)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setMargin(0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_12 = QtGui.QLabel(self.frame_Bank)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setWeight(50)
        font.setBold(False)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_23.addWidget(self.label_12)
        self.txtBank = QtGui.QLineEdit(self.frame_Bank)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtBank.sizePolicy().hasHeightForWidth())
        self.txtBank.setSizePolicy(sizePolicy)
        self.txtBank.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.txtBank.setFont(font)
        self.txtBank.setObjectName(_fromUtf8("txtBank"))
        self.horizontalLayout_23.addWidget(self.txtBank)
        self.verticalLayout_2.addWidget(self.frame_Bank)
        self.frame_Radius = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Radius.sizePolicy().hasHeightForWidth())
        self.frame_Radius.setSizePolicy(sizePolicy)
        self.frame_Radius.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Radius.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Radius.setObjectName(_fromUtf8("frame_Radius"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.frame_Radius)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setMargin(0)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_13 = QtGui.QLabel(self.frame_Radius)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setWeight(50)
        font.setBold(False)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_24.addWidget(self.label_13)
        self.txtRadius = QtGui.QLineEdit(self.frame_Radius)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtRadius.sizePolicy().hasHeightForWidth())
        self.txtRadius.setSizePolicy(sizePolicy)
        self.txtRadius.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.txtRadius.setFont(font)
        self.txtRadius.setObjectName(_fromUtf8("txtRadius"))
        self.horizontalLayout_24.addWidget(self.txtRadius)
        self.verticalLayout_2.addWidget(self.frame_Radius)
        self.frame_R = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_R.sizePolicy().hasHeightForWidth())
        self.frame_R.setSizePolicy(sizePolicy)
        self.frame_R.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_R.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_R.setObjectName(_fromUtf8("frame_R"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.frame_R)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setMargin(0)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_15 = QtGui.QLabel(self.frame_R)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setWeight(50)
        font.setBold(False)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_26.addWidget(self.label_15)
        self.txtR = QtGui.QLineEdit(self.frame_R)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtR.sizePolicy().hasHeightForWidth())
        self.txtR.setSizePolicy(sizePolicy)
        self.txtR.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.txtR.setFont(font)
        self.txtR.setObjectName(_fromUtf8("txtR"))
        self.horizontalLayout_26.addWidget(self.txtR)
        self.verticalLayout_2.addWidget(self.frame_R)
        self.chbIsFap = QtGui.QCheckBox(self.groupBox)
        self.chbIsFap.setObjectName(_fromUtf8("chbIsFap"))
        self.verticalLayout_2.addWidget(self.chbIsFap)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "RNP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Altitude (ft):", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAltitude.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Wind (kts):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Bank (°):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Radius (m):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "R (°/sec):", None, QtGui.QApplication.UnicodeUTF8))
        self.chbIsFap.setText(QtGui.QApplication.translate("Dialog", "FAP", None, QtGui.QApplication.UnicodeUTF8))

