# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TurnArea.ui'
#
# Created: Wed Jan 27 18:32:25 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from FlightPlanner.Panels.TrackRadialBoxPanel import TrackRadialBoxPanel

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TurnArea(object):
    def setupUi(self, ui_TurnArea):
        ui_TurnArea.setObjectName(_fromUtf8("ui_TurnArea"))
        # ui_TurnArea.resize(269, 293)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ui_TurnArea.sizePolicy().hasHeightForWidth())
        ui_TurnArea.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        ui_TurnArea.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(ui_TurnArea)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbParameters = QtGui.QGroupBox(ui_TurnArea)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.gbParameters.setFont(font)
        self.gbParameters.setObjectName(_fromUtf8("gbParameters"))
        self.vl_gbParameters = QtGui.QVBoxLayout(self.gbParameters)
        self.vl_gbParameters.setObjectName(_fromUtf8("vl_gbParameters"))
        self.frameIas = QtGui.QFrame(self.gbParameters)
        self.frameIas.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameIas.setFrameShadow(QtGui.QFrame.Raised)
        self.frameIas.setObjectName(_fromUtf8("frameIas"))
        self.horizontalLayout_60 = QtGui.QHBoxLayout(self.frameIas)
        self.horizontalLayout_60.setSpacing(0)
        self.horizontalLayout_60.setMargin(0)
        self.horizontalLayout_60.setObjectName(_fromUtf8("horizontalLayout_60"))
        self.label_68 = QtGui.QLabel(self.frameIas)
        self.label_68.setMinimumSize(QtCore.QSize(100, 0))
        self.label_68.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_60.addWidget(self.label_68)
        self.txtIas = QtGui.QLineEdit(self.frameIas)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtIas.setFont(font)
        self.txtIas.setObjectName(_fromUtf8("txtIas"))
        self.horizontalLayout_60.addWidget(self.txtIas)
        self.vl_gbParameters.addWidget(self.frameIas)
        self.frameTas = QtGui.QFrame(self.gbParameters)
        self.frameTas.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameTas.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTas.setObjectName(_fromUtf8("frameTas"))
        self.horizontalLayout_68 = QtGui.QHBoxLayout(self.frameTas)
        self.horizontalLayout_68.setSpacing(0)
        self.horizontalLayout_68.setMargin(0)
        self.horizontalLayout_68.setObjectName(_fromUtf8("horizontalLayout_68"))
        self.label_76 = QtGui.QLabel(self.frameTas)
        self.label_76.setMinimumSize(QtCore.QSize(100, 0))
        self.label_76.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_76.setFont(font)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.horizontalLayout_68.addWidget(self.label_76)
        self.txtTas = QtGui.QLineEdit(self.frameTas)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtTas.setFont(font)
        self.txtTas.setText(_fromUtf8(""))
        self.txtTas.setObjectName(_fromUtf8("txtTas"))
        self.horizontalLayout_68.addWidget(self.txtTas)
        self.vl_gbParameters.addWidget(self.frameTas)
        self.frameAltitude = QtGui.QFrame(self.gbParameters)
        self.frameAltitude.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAltitude.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAltitude.setObjectName(_fromUtf8("frameAltitude"))
        self.horizontalLayout_69 = QtGui.QHBoxLayout(self.frameAltitude)
        self.horizontalLayout_69.setSpacing(0)
        self.horizontalLayout_69.setMargin(0)
        self.horizontalLayout_69.setObjectName(_fromUtf8("horizontalLayout_69"))
        self.label_77 = QtGui.QLabel(self.frameAltitude)
        self.label_77.setMinimumSize(QtCore.QSize(100, 0))
        self.label_77.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.horizontalLayout_69.addWidget(self.label_77)
        self.txtAltitudeM = QtGui.QLineEdit(self.frameAltitude)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitudeM.setFont(font)
        self.txtAltitudeM.setText(_fromUtf8(""))
        self.txtAltitudeM.setObjectName(_fromUtf8("txtAltitudeM"))
        self.horizontalLayout_69.addWidget(self.txtAltitudeM)
        self.label_2 = QtGui.QLabel(self.frameAltitude)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_69.addWidget(self.label_2)
        self.txtAltitudeFt = QtGui.QLineEdit(self.frameAltitude)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitudeFt.setFont(font)
        self.txtAltitudeFt.setObjectName(_fromUtf8("txtAltitudeFt"))
        self.horizontalLayout_69.addWidget(self.txtAltitudeFt)
        self.label = QtGui.QLabel(self.frameAltitude)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_69.addWidget(self.label)
        self.vl_gbParameters.addWidget(self.frameAltitude)
        self.frameIsa = QtGui.QFrame(self.gbParameters)
        self.frameIsa.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameIsa.setFrameShadow(QtGui.QFrame.Raised)
        self.frameIsa.setObjectName(_fromUtf8("frameIsa"))
        self.horizontalLayout_72 = QtGui.QHBoxLayout(self.frameIsa)
        self.horizontalLayout_72.setSpacing(0)
        self.horizontalLayout_72.setMargin(0)
        self.horizontalLayout_72.setObjectName(_fromUtf8("horizontalLayout_72"))
        self.label_80 = QtGui.QLabel(self.frameIsa)
        self.label_80.setMinimumSize(QtCore.QSize(100, 0))
        self.label_80.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_80.setFont(font)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.horizontalLayout_72.addWidget(self.label_80)
        self.txtIsa = QtGui.QLineEdit(self.frameIsa)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtIsa.setFont(font)
        self.txtIsa.setObjectName(_fromUtf8("txtIsa"))
        self.horizontalLayout_72.addWidget(self.txtIsa)
        self.vl_gbParameters.addWidget(self.frameIsa)
        self.frameBankAngle = QtGui.QFrame(self.gbParameters)
        self.frameBankAngle.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameBankAngle.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBankAngle.setObjectName(_fromUtf8("frameBankAngle"))
        self.horizontalLayout_74 = QtGui.QHBoxLayout(self.frameBankAngle)
        self.horizontalLayout_74.setSpacing(0)
        self.horizontalLayout_74.setMargin(0)
        self.horizontalLayout_74.setObjectName(_fromUtf8("horizontalLayout_74"))
        self.label_82 = QtGui.QLabel(self.frameBankAngle)
        self.label_82.setMinimumSize(QtCore.QSize(100, 0))
        self.label_82.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_82.setFont(font)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.horizontalLayout_74.addWidget(self.label_82)
        self.txtBankAngle = QtGui.QLineEdit(self.frameBankAngle)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtBankAngle.setFont(font)
        self.txtBankAngle.setObjectName(_fromUtf8("txtBankAngle"))
        self.horizontalLayout_74.addWidget(self.txtBankAngle)
        self.vl_gbParameters.addWidget(self.frameBankAngle)
        self.chbDeparture = QtGui.QCheckBox(self.gbParameters)
        self.chbDeparture.setObjectName(_fromUtf8("chbDeparture"))
        self.vl_gbParameters.addWidget(self.chbDeparture)
        self.verticalLayout.addWidget(self.gbParameters)
        self.gbOrientation = QtGui.QGroupBox(ui_TurnArea)
        self.gbOrientation.setObjectName(_fromUtf8("gbOrientation"))
        self.vl_gbOrientation = QtGui.QVBoxLayout(self.gbOrientation)
        self.vl_gbOrientation.setObjectName(_fromUtf8("vl_gbOrientation"))

        self.txtTrackRadial = TrackRadialBoxPanel(self.gbOrientation)
        self.txtTrackRadial.Caption = "Track / Radial"
        self.vl_gbOrientation.addWidget(self.txtTrackRadial)
        # self.frameTrackRoot = QtGui.QFrame(self.gbOrientation)
        # self.frameTrackRoot.setFrameShape(QtGui.QFrame.NoFrame)
        # self.frameTrackRoot.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameTrackRoot.setObjectName(_fromUtf8("frameTrackRoot"))
        # self.horizontalLayout_63 = QtGui.QHBoxLayout(self.frameTrackRoot)
        # self.horizontalLayout_63.setSpacing(0)
        # self.horizontalLayout_63.setMargin(0)
        # self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        # self.label_71 = QtGui.QLabel(self.frameTrackRoot)
        # self.label_71.setMinimumSize(QtCore.QSize(100, 0))
        # self.label_71.setMaximumSize(QtCore.QSize(100, 16777215))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_71.setFont(font)
        # self.label_71.setObjectName(_fromUtf8("label_71"))
        # self.horizontalLayout_63.addWidget(self.label_71)
        # self.frameTrack = QtGui.QFrame(self.frameTrackRoot)
        # self.frameTrack.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frameTrack.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameTrack.setObjectName(_fromUtf8("frameTrack"))
        # self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frameTrack)
        # self.horizontalLayout_10.setSpacing(0)
        # self.horizontalLayout_10.setMargin(0)
        # self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        # self.txtTrackRadial = QtGui.QLineEdit(self.frameTrack)
        # self.txtTrackRadial.setEnabled(True)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.txtTrackRadial.setFont(font)
        # self.txtTrackRadial.setObjectName(_fromUtf8("txtTrackRadial"))
        # self.horizontalLayout_10.addWidget(self.txtTrackRadial)
        # self.btnCaptureTrack = QtGui.QToolButton(self.frameTrack)
        # self.btnCaptureTrack.setText(_fromUtf8(""))
        # icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.btnCaptureTrack.setIcon(icon)
        # self.btnCaptureTrack.setObjectName(_fromUtf8("btnCaptureTrack"))
        # self.horizontalLayout_10.addWidget(self.btnCaptureTrack)
        # self.horizontalLayout_63.addWidget(self.frameTrack)
        # self.vl_gbOrientation.addWidget(self.frameTrackRoot)
        self.frameOrientation = QtGui.QFrame(self.gbOrientation)
        self.frameOrientation.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameOrientation.setFrameShadow(QtGui.QFrame.Raised)
        self.frameOrientation.setObjectName(_fromUtf8("frameOrientation"))
        self.horizontalLayout_67 = QtGui.QHBoxLayout(self.frameOrientation)
        self.horizontalLayout_67.setSpacing(0)
        self.horizontalLayout_67.setMargin(0)
        self.horizontalLayout_67.setObjectName(_fromUtf8("horizontalLayout_67"))
        self.label_75 = QtGui.QLabel(self.frameOrientation)
        self.label_75.setMinimumSize(QtCore.QSize(100, 0))
        self.label_75.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.horizontalLayout_67.addWidget(self.label_75)
        self.cmbOrientation = QtGui.QComboBox(self.frameOrientation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrientation.sizePolicy().hasHeightForWidth())
        self.cmbOrientation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbOrientation.setFont(font)
        self.cmbOrientation.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.cmbOrientation.setObjectName(_fromUtf8("cmbOrientation"))
        self.horizontalLayout_67.addWidget(self.cmbOrientation)
        self.vl_gbOrientation.addWidget(self.frameOrientation)
        self.verticalLayout.addWidget(self.gbOrientation)

        self.retranslateUi(ui_TurnArea)
        QtCore.QMetaObject.connectSlotsByName(ui_TurnArea)

    def retranslateUi(self, ui_TurnArea):
        ui_TurnArea.setWindowTitle(_translate("ui_TurnArea", "Form", None))
        self.gbParameters.setTitle(_translate("ui_TurnArea", "Parameters", None))
        self.label_68.setText(_translate("ui_TurnArea", "IAS (kts):", None))
        self.txtIas.setText(_translate("ui_TurnArea", "210", None))
        self.label_76.setText(_translate("ui_TurnArea", "TAS (kts):", None))
        self.label_77.setText(_translate("ui_TurnArea", "Altitude (ft):", None))
        self.label_2.setText(_translate("ui_TurnArea", "m", None))
        self.txtAltitudeFt.setText(_translate("ui_TurnArea", "5000", None))
        self.label.setText(_translate("ui_TurnArea", "ft", None))
        self.label_80.setText(_translate("ui_TurnArea", "ISA (°C):", None))
        self.txtIsa.setText(_translate("ui_TurnArea", "15", None))
        self.label_82.setText(_translate("ui_TurnArea", "Bank Angle (°):", None))
        self.txtBankAngle.setText(_translate("ui_TurnArea", "25", None))
        self.chbDeparture.setText(_translate("ui_TurnArea", "Departure(IAS + 10%)", None))
        self.gbOrientation.setTitle(_translate("ui_TurnArea", "Orientation", None))
        # self.label_71.setText(_translate("ui_TurnArea", "Track / Radial (°):", None))
        # self.txtTrackRadial.setText(_translate("ui_TurnArea", "90", None))
        self.label_75.setText(_translate("ui_TurnArea", "Turn Direction:", None))

