# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DepartureRnav.ui'
#
# Created: Thu Oct 29 10:40:15 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from FlightPlanner.Panels.TrackRadialBoxPanel import TrackRadialBoxPanel

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DepartureRnav(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(478, 664)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbRunway = QtGui.QGroupBox(Form)
        self.gbRunway.setObjectName(_fromUtf8("gbRunway"))
        self.vl_gbRunway = QtGui.QVBoxLayout(self.gbRunway)
        self.vl_gbRunway.setObjectName(_fromUtf8("vl_gbRunway"))

        self.txtDer = TrackRadialBoxPanel(self.gbRunway)
        self.txtDer.Caption = "Direction"
        self.vl_gbRunway.addWidget(self.txtDer)
        # self.frame_TrackFrom_2 = QtGui.QFrame(self.gbRunway)
        # self.frame_TrackFrom_2.setFrameShape(QtGui.QFrame.NoFrame)
        # self.frame_TrackFrom_2.setFrameShadow(QtGui.QFrame.Raised)
        # self.frame_TrackFrom_2.setObjectName(_fromUtf8("frame_TrackFrom_2"))
        # self.horizontalLayout_66 = QtGui.QHBoxLayout(self.frame_TrackFrom_2)
        # self.horizontalLayout_66.setSpacing(0)
        # self.horizontalLayout_66.setMargin(0)
        # self.horizontalLayout_66.setObjectName(_fromUtf8("horizontalLayout_66"))
        # self.label_74 = QtGui.QLabel(self.frame_TrackFrom_2)
        # self.label_74.setMinimumSize(QtCore.QSize(200, 0))
        # self.label_74.setMaximumSize(QtCore.QSize(200, 16777215))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_74.setFont(font)
        # self.label_74.setObjectName(_fromUtf8("label_74"))
        # self.horizontalLayout_66.addWidget(self.label_74)
        # self.frame_APV_9 = QtGui.QFrame(self.frame_TrackFrom_2)
        # self.frame_APV_9.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frame_APV_9.setFrameShadow(QtGui.QFrame.Raised)
        # self.frame_APV_9.setObjectName(_fromUtf8("frame_APV_9"))
        # self.horizontalLayout_13 = QtGui.QHBoxLayout(self.frame_APV_9)
        # self.horizontalLayout_13.setSpacing(0)
        # self.horizontalLayout_13.setMargin(0)
        # self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        # self.txtDer = QtGui.QLineEdit(self.frame_APV_9)
        # self.txtDer.setEnabled(True)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.txtDer.setFont(font)
        # self.txtDer.setObjectName(_fromUtf8("txtDer"))
        # self.horizontalLayout_13.addWidget(self.txtDer)
        # self.btnCaptureDer = QtGui.QToolButton(self.frame_APV_9)
        # self.btnCaptureDer.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.btnCaptureDer.setIcon(icon)
        # self.btnCaptureDer.setObjectName(_fromUtf8("btnCaptureDer"))
        # self.horizontalLayout_13.addWidget(self.btnCaptureDer)
        # self.horizontalLayout_66.addWidget(self.frame_APV_9)
        # self.vl_gbRunway.addWidget(self.frame_TrackFrom_2)
        self.verticalLayout.addWidget(self.gbRunway)
        self.gbParameters = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.gbParameters.setFont(font)
        self.gbParameters.setObjectName(_fromUtf8("gbParameters"))
        self.vl_gbParameters = QtGui.QVBoxLayout(self.gbParameters)
        self.vl_gbParameters.setObjectName(_fromUtf8("vl_gbParameters"))
        self.frameDistance = QtGui.QFrame(self.gbParameters)
        self.frameDistance.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameDistance.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDistance.setObjectName(_fromUtf8("frameDistance"))
        self.hLayoutDistance = QtGui.QHBoxLayout(self.frameDistance)
        self.hLayoutDistance.setSpacing(0)
        self.hLayoutDistance.setMargin(0)
        self.hLayoutDistance.setObjectName(_fromUtf8("hLayoutDistance"))
        self.label_76 = QtGui.QLabel(self.frameDistance)
        self.label_76.setMinimumSize(QtCore.QSize(200, 0))
        self.label_76.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_76.setFont(font)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.hLayoutDistance.addWidget(self.label_76)
        self.frame_APV_11 = QtGui.QFrame(self.frameDistance)
        self.frame_APV_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_11.setObjectName(_fromUtf8("frame_APV_11"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.frame_APV_11)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.txtDistance = QtGui.QLineEdit(self.frame_APV_11)
        self.txtDistance.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtDistance.setFont(font)
        self.txtDistance.setObjectName(_fromUtf8("txtDistance"))
        self.horizontalLayout_15.addWidget(self.txtDistance)
        self.btnCaptureDistance = QtGui.QToolButton(self.frame_APV_11)
        self.btnCaptureDistance.setText(_fromUtf8(""))
        self.btnCaptureDistance.setIcon(icon)
        self.btnCaptureDistance.setObjectName(_fromUtf8("btnCaptureDistance"))
        self.horizontalLayout_15.addWidget(self.btnCaptureDistance)
        self.hLayoutDistance.addWidget(self.frame_APV_11)
        self.vl_gbParameters.addWidget(self.frameDistance)
        self.frameAltitude = QtGui.QFrame(self.gbParameters)
        self.frameAltitude.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAltitude.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAltitude.setObjectName(_fromUtf8("frameAltitude"))
        self.hLayoutPDG_2 = QtGui.QHBoxLayout(self.frameAltitude)
        self.hLayoutPDG_2.setSpacing(0)
        self.hLayoutPDG_2.setMargin(0)
        self.hLayoutPDG_2.setObjectName(_fromUtf8("hLayoutPDG_2"))
        self.label_69 = QtGui.QLabel(self.frameAltitude)
        self.label_69.setMinimumSize(QtCore.QSize(200, 0))
        self.label_69.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.hLayoutPDG_2.addWidget(self.label_69)
        self.txtAltitudeM = QtGui.QLineEdit(self.frameAltitude)
        self.txtAltitudeM.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitudeM.setFont(font)
        self.txtAltitudeM.setObjectName(_fromUtf8("txtAltitudeM"))
        self.hLayoutPDG_2.addWidget(self.txtAltitudeM)
        self.label = QtGui.QLabel(self.frameAltitude)
        self.label.setObjectName(_fromUtf8("label"))
        self.hLayoutPDG_2.addWidget(self.label)
        self.txtAltitudeFt = QtGui.QLineEdit(self.frameAltitude)
        self.txtAltitudeFt.setObjectName(_fromUtf8("txtAltitudeFt"))
        self.hLayoutPDG_2.addWidget(self.txtAltitudeFt)
        self.label_2 = QtGui.QLabel(self.frameAltitude)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.hLayoutPDG_2.addWidget(self.label_2)
        self.vl_gbParameters.addWidget(self.frameAltitude)
        self.frame_58 = QtGui.QFrame(self.gbParameters)
        self.frame_58.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_58.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_58.setObjectName(_fromUtf8("frame_58"))
        self.horizontalLayout_58 = QtGui.QHBoxLayout(self.frame_58)
        self.horizontalLayout_58.setSpacing(0)
        self.horizontalLayout_58.setMargin(0)
        self.horizontalLayout_58.setObjectName(_fromUtf8("horizontalLayout_58"))
        self.label_66 = QtGui.QLabel(self.frame_58)
        self.label_66.setMinimumSize(QtCore.QSize(200, 0))
        self.label_66.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.horizontalLayout_58.addWidget(self.label_66)
        self.cmbSensorType = QtGui.QComboBox(self.frame_58)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSensorType.sizePolicy().hasHeightForWidth())
        self.cmbSensorType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbSensorType.setFont(font)
        self.cmbSensorType.setObjectName(_fromUtf8("cmbSensorType"))
        self.horizontalLayout_58.addWidget(self.cmbSensorType)
        self.vl_gbParameters.addWidget(self.frame_58)
        self.frame_OutBoundLimit = QtGui.QFrame(self.gbParameters)
        self.frame_OutBoundLimit.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_OutBoundLimit.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_OutBoundLimit.setObjectName(_fromUtf8("frame_OutBoundLimit"))
        self.horizontalLayout_59 = QtGui.QHBoxLayout(self.frame_OutBoundLimit)
        self.horizontalLayout_59.setSpacing(0)
        self.horizontalLayout_59.setMargin(0)
        self.horizontalLayout_59.setObjectName(_fromUtf8("horizontalLayout_59"))
        self.label_67 = QtGui.QLabel(self.frame_OutBoundLimit)
        self.label_67.setMinimumSize(QtCore.QSize(200, 0))
        self.label_67.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.horizontalLayout_59.addWidget(self.label_67)
        self.cmbSpecification = QtGui.QComboBox(self.frame_OutBoundLimit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSpecification.sizePolicy().hasHeightForWidth())
        self.cmbSpecification.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbSpecification.setFont(font)
        self.cmbSpecification.setObjectName(_fromUtf8("cmbSpecification"))
        self.horizontalLayout_59.addWidget(self.cmbSpecification)
        self.vl_gbParameters.addWidget(self.frame_OutBoundLimit)
        self.frame_63 = QtGui.QFrame(self.gbParameters)
        self.frame_63.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_63.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_63.setObjectName(_fromUtf8("frame_63"))
        self.horizontalLayout_70 = QtGui.QHBoxLayout(self.frame_63)
        self.horizontalLayout_70.setSpacing(0)
        self.horizontalLayout_70.setMargin(0)
        self.horizontalLayout_70.setObjectName(_fromUtf8("horizontalLayout_70"))
        self.label_78 = QtGui.QLabel(self.frame_63)
        self.label_78.setMinimumSize(QtCore.QSize(200, 0))
        self.label_78.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_78.setFont(font)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.horizontalLayout_70.addWidget(self.label_78)
        self.cmbDmeCount = QtGui.QComboBox(self.frame_63)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDmeCount.sizePolicy().hasHeightForWidth())
        self.cmbDmeCount.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbDmeCount.setFont(font)
        self.cmbDmeCount.setObjectName(_fromUtf8("cmbDmeCount"))
        self.horizontalLayout_70.addWidget(self.cmbDmeCount)
        self.vl_gbParameters.addWidget(self.frame_63)
        self.chbCatH = QtGui.QCheckBox(self.gbParameters)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbCatH.setFont(font)
        self.chbCatH.setObjectName(_fromUtf8("chbCatH"))
        self.vl_gbParameters.addWidget(self.chbCatH)
        self.frame_62 = QtGui.QFrame(self.gbParameters)
        self.frame_62.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_62.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_62.setObjectName(_fromUtf8("frame_62"))
        self.horizontalLayout_69 = QtGui.QHBoxLayout(self.frame_62)
        self.horizontalLayout_69.setSpacing(0)
        self.horizontalLayout_69.setMargin(0)
        self.horizontalLayout_69.setObjectName(_fromUtf8("horizontalLayout_69"))
        self.label_77 = QtGui.QLabel(self.frame_62)
        self.label_77.setMinimumSize(QtCore.QSize(200, 0))
        self.label_77.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.horizontalLayout_69.addWidget(self.label_77)
        self.txtMoc = QtGui.QLineEdit(self.frame_62)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMoc.setFont(font)
        self.txtMoc.setObjectName(_fromUtf8("txtMoc"))
        self.horizontalLayout_69.addWidget(self.txtMoc)
        self.vl_gbParameters.addWidget(self.frame_62)
        self.frame_61 = QtGui.QFrame(self.gbParameters)
        self.frame_61.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_61.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_61.setObjectName(_fromUtf8("frame_61"))
        self.horizontalLayout_60 = QtGui.QHBoxLayout(self.frame_61)
        self.horizontalLayout_60.setSpacing(0)
        self.horizontalLayout_60.setMargin(0)
        self.horizontalLayout_60.setObjectName(_fromUtf8("horizontalLayout_60"))
        self.label_68 = QtGui.QLabel(self.frame_61)
        self.label_68.setMinimumSize(QtCore.QSize(200, 0))
        self.label_68.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_60.addWidget(self.label_68)
        self.txtPdg = QtGui.QLineEdit(self.frame_61)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPdg.setFont(font)
        self.txtPdg.setObjectName(_fromUtf8("txtPdg"))
        self.horizontalLayout_60.addWidget(self.txtPdg)
        self.vl_gbParameters.addWidget(self.frame_61)
        self.frame_66 = QtGui.QFrame(self.gbParameters)
        self.frame_66.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_66.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_66.setObjectName(_fromUtf8("frame_66"))
        self.horizontalLayout_75 = QtGui.QHBoxLayout(self.frame_66)
        self.horizontalLayout_75.setSpacing(0)
        self.horizontalLayout_75.setMargin(0)
        self.horizontalLayout_75.setObjectName(_fromUtf8("horizontalLayout_75"))
        self.label_83 = QtGui.QLabel(self.frame_66)
        self.label_83.setMinimumSize(QtCore.QSize(200, 0))
        self.label_83.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_83.setFont(font)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.horizontalLayout_75.addWidget(self.label_83)
        self.cmbConstruct = QtGui.QComboBox(self.frame_66)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConstruct.sizePolicy().hasHeightForWidth())
        self.cmbConstruct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbConstruct.setFont(font)
        self.cmbConstruct.setObjectName(_fromUtf8("cmbConstruct"))
        self.horizontalLayout_75.addWidget(self.cmbConstruct)
        self.vl_gbParameters.addWidget(self.frame_66)
        self.frame_67 = QtGui.QFrame(self.gbParameters)
        self.frame_67.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_67.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_67.setObjectName(_fromUtf8("frame_67"))
        self.horizontalLayout_76 = QtGui.QHBoxLayout(self.frame_67)
        self.horizontalLayout_76.setSpacing(0)
        self.horizontalLayout_76.setMargin(0)
        self.horizontalLayout_76.setObjectName(_fromUtf8("horizontalLayout_76"))
        self.label_84 = QtGui.QLabel(self.frame_67)
        self.label_84.setMinimumSize(QtCore.QSize(200, 0))
        self.label_84.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_84.setFont(font)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.horizontalLayout_76.addWidget(self.label_84)
        self.mocSpinBox = QtGui.QSpinBox(self.frame_67)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mocSpinBox.sizePolicy().hasHeightForWidth())
        self.mocSpinBox.setSizePolicy(sizePolicy)
        self.mocSpinBox.setObjectName(_fromUtf8("mocSpinBox"))
        self.mocSpinBox.setMinimum(1)
        self.horizontalLayout_76.addWidget(self.mocSpinBox)
        self.vl_gbParameters.addWidget(self.frame_67)
        self.verticalLayout.addWidget(self.gbParameters)
        self.gbResultsVOR = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbResultsVOR.sizePolicy().hasHeightForWidth())
        self.gbResultsVOR.setSizePolicy(sizePolicy)
        self.gbResultsVOR.setObjectName(_fromUtf8("gbResultsVOR"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gbResultsVOR)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gbResultsWaypoint1 = QtGui.QGroupBox(self.gbResultsVOR)
        self.gbResultsWaypoint1.setObjectName(_fromUtf8("gbResultsWaypoint1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbResultsWaypoint1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_70 = QtGui.QFrame(self.gbResultsWaypoint1)
        self.frame_70.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_70.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_70.setObjectName(_fromUtf8("frame_70"))
        self.horizontalLayout_77 = QtGui.QHBoxLayout(self.frame_70)
        self.horizontalLayout_77.setSpacing(0)
        self.horizontalLayout_77.setMargin(0)
        self.horizontalLayout_77.setObjectName(_fromUtf8("horizontalLayout_77"))
        self.label_85 = QtGui.QLabel(self.frame_70)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_85.sizePolicy().hasHeightForWidth())
        self.label_85.setSizePolicy(sizePolicy)
        self.label_85.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_85.setFont(font)
        self.label_85.setFrameShadow(QtGui.QFrame.Plain)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.horizontalLayout_77.addWidget(self.label_85)
        self.txtXtt1V = QtGui.QLineEdit(self.frame_70)
        self.txtXtt1V.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtXtt1V.sizePolicy().hasHeightForWidth())
        self.txtXtt1V.setSizePolicy(sizePolicy)
        self.txtXtt1V.setMinimumSize(QtCore.QSize(0, 0))
        self.txtXtt1V.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtXtt1V.setFont(font)
        self.txtXtt1V.setObjectName(_fromUtf8("txtXtt1V"))
        self.horizontalLayout_77.addWidget(self.txtXtt1V)
        self.verticalLayout_2.addWidget(self.frame_70)
        self.frame_71 = QtGui.QFrame(self.gbResultsWaypoint1)
        self.frame_71.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_71.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_71.setObjectName(_fromUtf8("frame_71"))
        self.horizontalLayout_78 = QtGui.QHBoxLayout(self.frame_71)
        self.horizontalLayout_78.setSpacing(0)
        self.horizontalLayout_78.setMargin(0)
        self.horizontalLayout_78.setObjectName(_fromUtf8("horizontalLayout_78"))
        self.label_86 = QtGui.QLabel(self.frame_71)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_86.sizePolicy().hasHeightForWidth())
        self.label_86.setSizePolicy(sizePolicy)
        self.label_86.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_86.setFont(font)
        self.label_86.setFrameShadow(QtGui.QFrame.Plain)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.horizontalLayout_78.addWidget(self.label_86)
        self.txtAtt1V = QtGui.QLineEdit(self.frame_71)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAtt1V.sizePolicy().hasHeightForWidth())
        self.txtAtt1V.setSizePolicy(sizePolicy)
        self.txtAtt1V.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAtt1V.setFont(font)
        self.txtAtt1V.setObjectName(_fromUtf8("txtAtt1V"))
        self.horizontalLayout_78.addWidget(self.txtAtt1V)
        self.verticalLayout_2.addWidget(self.frame_71)
        self.frame_72 = QtGui.QFrame(self.gbResultsWaypoint1)
        self.frame_72.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_72.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_72.setObjectName(_fromUtf8("frame_72"))
        self.horizontalLayout_79 = QtGui.QHBoxLayout(self.frame_72)
        self.horizontalLayout_79.setSpacing(0)
        self.horizontalLayout_79.setMargin(0)
        self.horizontalLayout_79.setObjectName(_fromUtf8("horizontalLayout_79"))
        self.label_87 = QtGui.QLabel(self.frame_72)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_87.sizePolicy().hasHeightForWidth())
        self.label_87.setSizePolicy(sizePolicy)
        self.label_87.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_87.setFont(font)
        self.label_87.setFrameShadow(QtGui.QFrame.Plain)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.horizontalLayout_79.addWidget(self.label_87)
        self.txtAsw1V = QtGui.QLineEdit(self.frame_72)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAsw1V.sizePolicy().hasHeightForWidth())
        self.txtAsw1V.setSizePolicy(sizePolicy)
        self.txtAsw1V.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAsw1V.setFont(font)
        self.txtAsw1V.setObjectName(_fromUtf8("txtAsw1V"))
        self.horizontalLayout_79.addWidget(self.txtAsw1V)
        self.verticalLayout_2.addWidget(self.frame_72)
        self.horizontalLayout.addWidget(self.gbResultsWaypoint1)
        self.gbResultsWaypoint2 = QtGui.QGroupBox(self.gbResultsVOR)
        self.gbResultsWaypoint2.setObjectName(_fromUtf8("gbResultsWaypoint2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbResultsWaypoint2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_73 = QtGui.QFrame(self.gbResultsWaypoint2)
        self.frame_73.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_73.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_73.setObjectName(_fromUtf8("frame_73"))
        self.horizontalLayout_80 = QtGui.QHBoxLayout(self.frame_73)
        self.horizontalLayout_80.setSpacing(0)
        self.horizontalLayout_80.setMargin(0)
        self.horizontalLayout_80.setObjectName(_fromUtf8("horizontalLayout_80"))
        self.label_88 = QtGui.QLabel(self.frame_73)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_88.sizePolicy().hasHeightForWidth())
        self.label_88.setSizePolicy(sizePolicy)
        self.label_88.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_88.setFont(font)
        self.label_88.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.horizontalLayout_80.addWidget(self.label_88)
        self.txtXtt2V = QtGui.QLineEdit(self.frame_73)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtXtt2V.sizePolicy().hasHeightForWidth())
        self.txtXtt2V.setSizePolicy(sizePolicy)
        self.txtXtt2V.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtXtt2V.setFont(font)
        self.txtXtt2V.setObjectName(_fromUtf8("txtXtt2V"))
        self.horizontalLayout_80.addWidget(self.txtXtt2V)
        self.verticalLayout_3.addWidget(self.frame_73)
        self.frame_74 = QtGui.QFrame(self.gbResultsWaypoint2)
        self.frame_74.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_74.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_74.setObjectName(_fromUtf8("frame_74"))
        self.horizontalLayout_81 = QtGui.QHBoxLayout(self.frame_74)
        self.horizontalLayout_81.setSpacing(0)
        self.horizontalLayout_81.setMargin(0)
        self.horizontalLayout_81.setObjectName(_fromUtf8("horizontalLayout_81"))
        self.label_89 = QtGui.QLabel(self.frame_74)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_89.sizePolicy().hasHeightForWidth())
        self.label_89.setSizePolicy(sizePolicy)
        self.label_89.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_89.setFont(font)
        self.label_89.setFrameShadow(QtGui.QFrame.Plain)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.horizontalLayout_81.addWidget(self.label_89)
        self.txtAtt2V = QtGui.QLineEdit(self.frame_74)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAtt2V.sizePolicy().hasHeightForWidth())
        self.txtAtt2V.setSizePolicy(sizePolicy)
        self.txtAtt2V.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAtt2V.setFont(font)
        self.txtAtt2V.setObjectName(_fromUtf8("txtAtt2V"))
        self.horizontalLayout_81.addWidget(self.txtAtt2V)
        self.verticalLayout_3.addWidget(self.frame_74)
        self.frame_75 = QtGui.QFrame(self.gbResultsWaypoint2)
        self.frame_75.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_75.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_75.setObjectName(_fromUtf8("frame_75"))
        self.horizontalLayout_82 = QtGui.QHBoxLayout(self.frame_75)
        self.horizontalLayout_82.setSpacing(0)
        self.horizontalLayout_82.setMargin(0)
        self.horizontalLayout_82.setObjectName(_fromUtf8("horizontalLayout_82"))
        self.label_90 = QtGui.QLabel(self.frame_75)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_90.sizePolicy().hasHeightForWidth())
        self.label_90.setSizePolicy(sizePolicy)
        self.label_90.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_90.setFont(font)
        self.label_90.setFrameShadow(QtGui.QFrame.Plain)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.horizontalLayout_82.addWidget(self.label_90)
        self.txtAsw2V = QtGui.QLineEdit(self.frame_75)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAsw2V.sizePolicy().hasHeightForWidth())
        self.txtAsw2V.setSizePolicy(sizePolicy)
        self.txtAsw2V.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAsw2V.setFont(font)
        self.txtAsw2V.setObjectName(_fromUtf8("txtAsw2V"))
        self.horizontalLayout_82.addWidget(self.txtAsw2V)
        self.verticalLayout_3.addWidget(self.frame_75)
        self.horizontalLayout.addWidget(self.gbResultsWaypoint2)
        self.verticalLayout.addWidget(self.gbResultsVOR)
        self.gbResultsDME = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbResultsDME.sizePolicy().hasHeightForWidth())
        self.gbResultsDME.setSizePolicy(sizePolicy)
        self.gbResultsDME.setObjectName(_fromUtf8("gbResultsDME"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.gbResultsDME)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gbResultsWaypoint1_2 = QtGui.QGroupBox(self.gbResultsDME)
        self.gbResultsWaypoint1_2.setObjectName(_fromUtf8("gbResultsWaypoint1_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gbResultsWaypoint1_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame_76 = QtGui.QFrame(self.gbResultsWaypoint1_2)
        self.frame_76.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_76.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_76.setObjectName(_fromUtf8("frame_76"))
        self.horizontalLayout_83 = QtGui.QHBoxLayout(self.frame_76)
        self.horizontalLayout_83.setSpacing(0)
        self.horizontalLayout_83.setMargin(0)
        self.horizontalLayout_83.setObjectName(_fromUtf8("horizontalLayout_83"))
        self.label_91 = QtGui.QLabel(self.frame_76)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_91.sizePolicy().hasHeightForWidth())
        self.label_91.setSizePolicy(sizePolicy)
        self.label_91.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_91.setFont(font)
        self.label_91.setFrameShadow(QtGui.QFrame.Plain)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.horizontalLayout_83.addWidget(self.label_91)
        self.txtXtt1D = QtGui.QLineEdit(self.frame_76)
        self.txtXtt1D.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtXtt1D.sizePolicy().hasHeightForWidth())
        self.txtXtt1D.setSizePolicy(sizePolicy)
        self.txtXtt1D.setMinimumSize(QtCore.QSize(0, 0))
        self.txtXtt1D.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtXtt1D.setFont(font)
        self.txtXtt1D.setObjectName(_fromUtf8("txtXtt1D"))
        self.horizontalLayout_83.addWidget(self.txtXtt1D)
        self.verticalLayout_4.addWidget(self.frame_76)
        self.frame_77 = QtGui.QFrame(self.gbResultsWaypoint1_2)
        self.frame_77.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_77.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_77.setObjectName(_fromUtf8("frame_77"))
        self.horizontalLayout_84 = QtGui.QHBoxLayout(self.frame_77)
        self.horizontalLayout_84.setSpacing(0)
        self.horizontalLayout_84.setMargin(0)
        self.horizontalLayout_84.setObjectName(_fromUtf8("horizontalLayout_84"))
        self.label_92 = QtGui.QLabel(self.frame_77)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_92.sizePolicy().hasHeightForWidth())
        self.label_92.setSizePolicy(sizePolicy)
        self.label_92.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_92.setFont(font)
        self.label_92.setFrameShadow(QtGui.QFrame.Plain)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.horizontalLayout_84.addWidget(self.label_92)
        self.txtAtt1D = QtGui.QLineEdit(self.frame_77)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAtt1D.sizePolicy().hasHeightForWidth())
        self.txtAtt1D.setSizePolicy(sizePolicy)
        self.txtAtt1D.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAtt1D.setFont(font)
        self.txtAtt1D.setObjectName(_fromUtf8("txtAtt1D"))
        self.horizontalLayout_84.addWidget(self.txtAtt1D)
        self.verticalLayout_4.addWidget(self.frame_77)
        self.frame_78 = QtGui.QFrame(self.gbResultsWaypoint1_2)
        self.frame_78.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_78.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_78.setObjectName(_fromUtf8("frame_78"))
        self.horizontalLayout_85 = QtGui.QHBoxLayout(self.frame_78)
        self.horizontalLayout_85.setSpacing(0)
        self.horizontalLayout_85.setMargin(0)
        self.horizontalLayout_85.setObjectName(_fromUtf8("horizontalLayout_85"))
        self.label_93 = QtGui.QLabel(self.frame_78)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_93.sizePolicy().hasHeightForWidth())
        self.label_93.setSizePolicy(sizePolicy)
        self.label_93.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_93.setFont(font)
        self.label_93.setFrameShadow(QtGui.QFrame.Plain)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.horizontalLayout_85.addWidget(self.label_93)
        self.txtAsw1D = QtGui.QLineEdit(self.frame_78)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAsw1D.sizePolicy().hasHeightForWidth())
        self.txtAsw1D.setSizePolicy(sizePolicy)
        self.txtAsw1D.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAsw1D.setFont(font)
        self.txtAsw1D.setObjectName(_fromUtf8("txtAsw1D"))
        self.horizontalLayout_85.addWidget(self.txtAsw1D)
        self.verticalLayout_4.addWidget(self.frame_78)
        self.horizontalLayout_2.addWidget(self.gbResultsWaypoint1_2)
        self.gbResultsWaypoint2_2 = QtGui.QGroupBox(self.gbResultsDME)
        self.gbResultsWaypoint2_2.setObjectName(_fromUtf8("gbResultsWaypoint2_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.gbResultsWaypoint2_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frame_79 = QtGui.QFrame(self.gbResultsWaypoint2_2)
        self.frame_79.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_79.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_79.setObjectName(_fromUtf8("frame_79"))
        self.horizontalLayout_86 = QtGui.QHBoxLayout(self.frame_79)
        self.horizontalLayout_86.setSpacing(0)
        self.horizontalLayout_86.setMargin(0)
        self.horizontalLayout_86.setObjectName(_fromUtf8("horizontalLayout_86"))
        self.label_94 = QtGui.QLabel(self.frame_79)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_94.sizePolicy().hasHeightForWidth())
        self.label_94.setSizePolicy(sizePolicy)
        self.label_94.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_94.setFont(font)
        self.label_94.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_94.setFrameShadow(QtGui.QFrame.Plain)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.horizontalLayout_86.addWidget(self.label_94)
        self.txtXtt2D = QtGui.QLineEdit(self.frame_79)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtXtt2D.sizePolicy().hasHeightForWidth())
        self.txtXtt2D.setSizePolicy(sizePolicy)
        self.txtXtt2D.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtXtt2D.setFont(font)
        self.txtXtt2D.setObjectName(_fromUtf8("txtXtt2D"))
        self.horizontalLayout_86.addWidget(self.txtXtt2D)
        self.verticalLayout_5.addWidget(self.frame_79)
        self.frame_80 = QtGui.QFrame(self.gbResultsWaypoint2_2)
        self.frame_80.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_80.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_80.setObjectName(_fromUtf8("frame_80"))
        self.horizontalLayout_87 = QtGui.QHBoxLayout(self.frame_80)
        self.horizontalLayout_87.setSpacing(0)
        self.horizontalLayout_87.setMargin(0)
        self.horizontalLayout_87.setObjectName(_fromUtf8("horizontalLayout_87"))
        self.label_95 = QtGui.QLabel(self.frame_80)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_95.sizePolicy().hasHeightForWidth())
        self.label_95.setSizePolicy(sizePolicy)
        self.label_95.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_95.setFont(font)
        self.label_95.setFrameShadow(QtGui.QFrame.Plain)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.horizontalLayout_87.addWidget(self.label_95)
        self.txtAtt2D = QtGui.QLineEdit(self.frame_80)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAtt2D.sizePolicy().hasHeightForWidth())
        self.txtAtt2D.setSizePolicy(sizePolicy)
        self.txtAtt2D.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAtt2D.setFont(font)
        self.txtAtt2D.setObjectName(_fromUtf8("txtAtt2D"))
        self.horizontalLayout_87.addWidget(self.txtAtt2D)
        self.verticalLayout_5.addWidget(self.frame_80)
        self.frame_81 = QtGui.QFrame(self.gbResultsWaypoint2_2)
        self.frame_81.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_81.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_81.setObjectName(_fromUtf8("frame_81"))
        self.horizontalLayout_88 = QtGui.QHBoxLayout(self.frame_81)
        self.horizontalLayout_88.setSpacing(0)
        self.horizontalLayout_88.setMargin(0)
        self.horizontalLayout_88.setObjectName(_fromUtf8("horizontalLayout_88"))
        self.label_96 = QtGui.QLabel(self.frame_81)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_96.sizePolicy().hasHeightForWidth())
        self.label_96.setSizePolicy(sizePolicy)
        self.label_96.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_96.setFont(font)
        self.label_96.setFrameShadow(QtGui.QFrame.Plain)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.horizontalLayout_88.addWidget(self.label_96)
        self.txtAsw2D = QtGui.QLineEdit(self.frame_81)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAsw2D.sizePolicy().hasHeightForWidth())
        self.txtAsw2D.setSizePolicy(sizePolicy)
        self.txtAsw2D.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAsw2D.setFont(font)
        self.txtAsw2D.setObjectName(_fromUtf8("txtAsw2D"))
        self.horizontalLayout_88.addWidget(self.txtAsw2D)
        self.verticalLayout_5.addWidget(self.frame_81)
        self.horizontalLayout_2.addWidget(self.gbResultsWaypoint2_2)
        self.verticalLayout.addWidget(self.gbResultsDME)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.gbRunway.setTitle(_translate("Form", "Runway", None))
        # self.label_74.setText(_translate("Form", "Direction ():", None))
        # self.txtDer.setText(_translate("Form", "0", None))
        self.gbParameters.setTitle(_translate("Form", "Parameters", None))
        self.label_76.setText(_translate("Form", "Distance(nm):", None))
        self.txtDistance.setText(_translate("Form", "15", None))
        self.label_69.setText(_translate("Form", "Altitude:", None))
        self.txtAltitudeM.setText(_translate("Form", "0", None))
        self.label.setText(_translate("Form", "m", None))
        self.txtAltitudeFt.setText(_translate("Form", "0", None))
        self.label_2.setText(_translate("Form", "ft", None))
        self.label_66.setText(_translate("Form", "Sensor Type:", None))
        self.label_67.setText(_translate("Form", "Rnav Specification:", None))
        self.label_78.setText(_translate("Form", "Number of DMEs Used:", None))
        self.chbCatH.setText(_translate("Form", "Cat. H", None))
        self.label_77.setText(_translate("Form", "MOC(%):", None))
        self.txtMoc.setText(_translate("Form", "0.8", None))
        self.label_68.setText(_translate("Form", "PDG(%):", None))
        self.txtPdg.setText(_translate("Form", "3.3", None))
        self.label_83.setText(_translate("Form", "Construction Type:", None))
        self.label_84.setText(_translate("Form", "MOCmultiplier:", None))
        self.gbResultsVOR.setTitle(_translate("Form", "Results", None))
        self.gbResultsWaypoint1.setTitle(_translate("Form", "Waypoint1", None))
        self.label_85.setText(_translate("Form", "XTT(nm):", None))
        self.txtXtt1V.setText(_translate("Form", "0", None))
        self.label_86.setText(_translate("Form", "ATT(nm):", None))
        self.txtAtt1V.setText(_translate("Form", "0", None))
        self.label_87.setText(_translate("Form", "1/2 A/W(nm):", None))
        self.txtAsw1V.setText(_translate("Form", "0", None))
        self.gbResultsWaypoint2.setTitle(_translate("Form", "Waypoint2", None))
        self.label_88.setText(_translate("Form", "XTT(nm):", None))
        self.txtXtt2V.setText(_translate("Form", "0", None))
        self.label_89.setText(_translate("Form", "ATT(nm):", None))
        self.txtAtt2V.setText(_translate("Form", "0", None))
        self.label_90.setText(_translate("Form", "1/2 A/W(nm):", None))
        self.txtAsw2V.setText(_translate("Form", "0", None))
        self.gbResultsDME.setTitle(_translate("Form", "DME / DME Results", None))
        self.gbResultsWaypoint1_2.setTitle(_translate("Form", "Waypoint1", None))
        self.label_91.setText(_translate("Form", "XTT(nm):", None))
        self.txtXtt1D.setText(_translate("Form", "0", None))
        self.label_92.setText(_translate("Form", "ATT(nm):", None))
        self.txtAtt1D.setText(_translate("Form", "0", None))
        self.label_93.setText(_translate("Form", "1/2 A/W(nm):", None))
        self.txtAsw1D.setText(_translate("Form", "0", None))
        self.gbResultsWaypoint2_2.setTitle(_translate("Form", "Waypoint2", None))
        self.label_94.setText(_translate("Form", "XTT(nm):", None))
        self.txtXtt2D.setText(_translate("Form", "0", None))
        self.label_95.setText(_translate("Form", "ATT(nm):", None))
        self.txtAtt2D.setText(_translate("Form", "0", None))
        self.label_96.setText(_translate("Form", "1/2 A/W(nm):", None))
        self.txtAsw2D.setText(_translate("Form", "0", None))

