# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DmeTolerance.ui'
#
# Created: Wed Nov 25 15:51:33 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from FlightPlanner.Panels.TrackRadialBoxPanel import TrackRadialBoxPanel
from FlightPlanner.Panels.ComboBoxPanel import ComboBoxPanel

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DmeToleranceDlg(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(436, 500)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        Form.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbCalculation = QtGui.QGroupBox(Form)
        self.gbCalculation.setObjectName(_fromUtf8("gbCalculation"))
        self.vl_gbCalculation = QtGui.QVBoxLayout(self.gbCalculation)
        self.vl_gbCalculation.setObjectName(_fromUtf8("vl_gbCalculation"))
        self.frame_66 = QtGui.QFrame(self.gbCalculation)
        self.frame_66.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_66.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_66.setObjectName(_fromUtf8("frame_66"))
        self.horizontalLayout_66 = QtGui.QHBoxLayout(self.frame_66)
        self.horizontalLayout_66.setSpacing(0)
        self.horizontalLayout_66.setMargin(0)
        self.horizontalLayout_66.setObjectName(_fromUtf8("horizontalLayout_66"))
        self.label_74 = QtGui.QLabel(self.frame_66)
        self.label_74.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_66.addWidget(self.label_74)
        self.cmbCalculationType = QtGui.QComboBox(self.frame_66)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCalculationType.sizePolicy().hasHeightForWidth())
        self.cmbCalculationType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbCalculationType.setFont(font)
        self.cmbCalculationType.setObjectName(_fromUtf8("cmbCalculationType"))
        self.cmbCalculationType.setMinimumSize(QtCore.QSize(70, 0))
        self.cmbCalculationType.setMaximumSize(QtCore.QSize(70, 16777215))
        self.horizontalLayout_66.addWidget(self.cmbCalculationType)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_66.addItem(horizontalSpacer)
        self.vl_gbCalculation.addWidget(self.frame_66)
        self.frame_TakeOffSurfaceTrack_4 = QtGui.QFrame(self.gbCalculation)
        self.frame_TakeOffSurfaceTrack_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_TakeOffSurfaceTrack_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_TakeOffSurfaceTrack_4.setObjectName(_fromUtf8("frame_TakeOffSurfaceTrack_4"))
        self.horizontalLayout_68 = QtGui.QHBoxLayout(self.frame_TakeOffSurfaceTrack_4)
        self.horizontalLayout_68.setSpacing(0)
        self.horizontalLayout_68.setMargin(0)
        self.horizontalLayout_68.setObjectName(_fromUtf8("horizontalLayout_68"))
        self.label_76 = QtGui.QLabel(self.frame_TakeOffSurfaceTrack_4)
        self.label_76.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_76.setFont(font)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.horizontalLayout_68.addWidget(self.label_76)
        self.frame_APV_8 = QtGui.QFrame(self.frame_TakeOffSurfaceTrack_4)
        self.frame_APV_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_8.setObjectName(_fromUtf8("frame_APV_8"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.frame_APV_8)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.txtDistance = QtGui.QLineEdit(self.frame_APV_8)
        self.txtDistance.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtDistance.setFont(font)
        self.txtDistance.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txtDistance.setObjectName(_fromUtf8("txtDistance"))
        self.txtDistance.setMinimumSize(QtCore.QSize(70, 0))
        self.txtDistance.setMaximumSize(QtCore.QSize(70, 16777215))
        self.horizontalLayout_12.addWidget(self.txtDistance)
        self.btnMesureDist = QtGui.QToolButton(self.frame_APV_8)
        self.btnMesureDist.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMesureDist.setIcon(icon)
        self.btnMesureDist.setObjectName(_fromUtf8("btnMesureDist"))
        self.horizontalLayout_12.addWidget(self.btnMesureDist)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(horizontalSpacer)
        self.horizontalLayout_68.addWidget(self.frame_APV_8)
        self.vl_gbCalculation.addWidget(self.frame_TakeOffSurfaceTrack_4)
        self.frame_61 = QtGui.QFrame(self.gbCalculation)
        self.frame_61.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_61.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_61.setObjectName(_fromUtf8("frame_61"))
        self.horizontalLayout_60 = QtGui.QHBoxLayout(self.frame_61)
        self.horizontalLayout_60.setSpacing(0)
        self.horizontalLayout_60.setMargin(0)
        self.horizontalLayout_60.setObjectName(_fromUtf8("horizontalLayout_60"))
        self.label_68 = QtGui.QLabel(self.frame_61)
        self.label_68.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_60.addWidget(self.label_68)
        self.txtAcAltitudeM = QtGui.QLineEdit(self.frame_61)
        self.txtAcAltitudeM.setObjectName(_fromUtf8("txtAcAltitudeM"))
        self.txtAcAltitudeM.setMinimumSize(QtCore.QSize(90, 0))
        self.txtAcAltitudeM.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_60.addWidget(self.txtAcAltitudeM)
        self.label_2 = QtGui.QLabel(self.frame_61)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_60.addWidget(self.label_2)
        self.txtAcAltitude = QtGui.QLineEdit(self.frame_61)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAcAltitude.setFont(font)
        self.txtAcAltitude.setObjectName(_fromUtf8("txtAcAltitude"))
        self.txtAcAltitude.setMinimumSize(QtCore.QSize(90, 0))
        self.txtAcAltitude.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_60.addWidget(self.txtAcAltitude)
        self.label = QtGui.QLabel(self.frame_61)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_60.addWidget(self.label)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_60.addItem(horizontalSpacer)
        self.vl_gbCalculation.addWidget(self.frame_61)
        self.frame_TakeOffSurfaceTrack = QtGui.QFrame(self.gbCalculation)
        self.frame_TakeOffSurfaceTrack.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_TakeOffSurfaceTrack.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_TakeOffSurfaceTrack.setObjectName(_fromUtf8("frame_TakeOffSurfaceTrack"))
        self.horizontalLayout_61 = QtGui.QHBoxLayout(self.frame_TakeOffSurfaceTrack)
        self.horizontalLayout_61.setSpacing(0)
        self.horizontalLayout_61.setMargin(0)
        self.horizontalLayout_61.setObjectName(_fromUtf8("horizontalLayout_61"))
        self.lbDmeAltitude = QtGui.QLabel(self.frame_TakeOffSurfaceTrack)
        self.lbDmeAltitude.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbDmeAltitude.setFont(font)
        self.lbDmeAltitude.setObjectName(_fromUtf8("lbDmeAltitude"))
        self.horizontalLayout_61.addWidget(self.lbDmeAltitude)
        self.frame_APV_5 = QtGui.QFrame(self.frame_TakeOffSurfaceTrack)
        self.frame_APV_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_5.setObjectName(_fromUtf8("frame_APV_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_APV_5)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.txtDmeAltitude = QtGui.QLineEdit(self.frame_APV_5)
        self.txtDmeAltitude.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtDmeAltitude.setFont(font)
        self.txtDmeAltitude.setObjectName(_fromUtf8("txtDmeAltitude"))
        self.txtDmeAltitude.setMinimumSize(QtCore.QSize(90, 0))
        self.txtDmeAltitude.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_9.addWidget(self.txtDmeAltitude)
        self.label_6 = QtGui.QLabel(self.frame_APV_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.txtDmeAltitudeFt = QtGui.QLineEdit(self.frame_APV_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtDmeAltitudeFt.setFont(font)
        self.txtDmeAltitudeFt.setText(_fromUtf8(""))
        self.txtDmeAltitudeFt.setObjectName(_fromUtf8("txtDmeAltitudeFt"))
        self.txtDmeAltitudeFt.setMinimumSize(QtCore.QSize(90, 0))
        self.txtDmeAltitudeFt.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_9.addWidget(self.txtDmeAltitudeFt)
        self.labelMocFt = QtGui.QLabel(self.frame_APV_5)
        self.labelMocFt.setObjectName(_fromUtf8("labelMocFt"))
        self.horizontalLayout_9.addWidget(self.labelMocFt)
        self.btnMesureAltitude = QtGui.QToolButton(self.frame_APV_5)
        self.btnMesureAltitude.setText(_fromUtf8(""))
        self.btnMesureAltitude.setIcon(icon)
        self.btnMesureAltitude.setObjectName(_fromUtf8("btnMesureAltitude"))
        self.horizontalLayout_9.addWidget(self.btnMesureAltitude)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(horizontalSpacer)
        self.horizontalLayout_61.addWidget(self.frame_APV_5)
        self.vl_gbCalculation.addWidget(self.frame_TakeOffSurfaceTrack)
        self.gbResult = QtGui.QGroupBox(self.gbCalculation)
        self.gbResult.setObjectName(_fromUtf8("gbResult"))
        self.vl_gbResult = QtGui.QVBoxLayout(self.gbResult)
        self.vl_gbResult.setObjectName(_fromUtf8("vl_gbResult"))
        self.frame_62 = QtGui.QFrame(self.gbResult)
        self.frame_62.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_62.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_62.setObjectName(_fromUtf8("frame_62"))
        self.horizontalLayout_63 = QtGui.QHBoxLayout(self.frame_62)
        self.horizontalLayout_63.setSpacing(0)
        self.horizontalLayout_63.setMargin(0)
        self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        self.lblResultDistance = QtGui.QLabel(self.frame_62)
        self.lblResultDistance.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblResultDistance.setFont(font)
        self.lblResultDistance.setObjectName(_fromUtf8("lblResultDistance"))
        self.horizontalLayout_63.addWidget(self.lblResultDistance)
        self.txtResultDistance = QtGui.QLineEdit(self.frame_62)
        self.txtResultDistance.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtResultDistance.setFont(font)
        self.txtResultDistance.setText(_fromUtf8(""))
        self.txtResultDistance.setObjectName(_fromUtf8("txtResultDistance"))
        self.txtResultDistance.setMinimumSize(QtCore.QSize(130, 0))
        self.txtResultDistance.setMaximumSize(QtCore.QSize(130, 16777215))
        self.horizontalLayout_63.addWidget(self.txtResultDistance)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_63.addItem(horizontalSpacer)
        self.vl_gbResult.addWidget(self.frame_62)
        self.frame_TakeOffSurfaceTrack_2 = QtGui.QFrame(self.gbResult)
        self.frame_TakeOffSurfaceTrack_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_TakeOffSurfaceTrack_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_TakeOffSurfaceTrack_2.setObjectName(_fromUtf8("frame_TakeOffSurfaceTrack_2"))
        self.horizontalLayout_64 = QtGui.QHBoxLayout(self.frame_TakeOffSurfaceTrack_2)
        self.horizontalLayout_64.setSpacing(0)
        self.horizontalLayout_64.setMargin(0)
        self.horizontalLayout_64.setObjectName(_fromUtf8("horizontalLayout_64"))
        self.label_72 = QtGui.QLabel(self.frame_TakeOffSurfaceTrack_2)
        self.label_72.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.horizontalLayout_64.addWidget(self.label_72)
        self.frame_APV_6 = QtGui.QFrame(self.frame_TakeOffSurfaceTrack_2)
        self.frame_APV_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_6.setObjectName(_fromUtf8("frame_APV_6"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frame_APV_6)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.txtResultDmeTol = QtGui.QLineEdit(self.frame_APV_6)
        self.txtResultDmeTol.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtResultDmeTol.setFont(font)
        self.txtResultDmeTol.setText(_fromUtf8(""))
        self.txtResultDmeTol.setObjectName(_fromUtf8("txtResultDmeTol"))
        self.txtResultDmeTol.setMinimumSize(QtCore.QSize(130, 0))
        self.txtResultDmeTol.setMaximumSize(QtCore.QSize(130, 16777215))
        self.horizontalLayout_10.addWidget(self.txtResultDmeTol)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(horizontalSpacer)
        self.btnMesureTolerance = QtGui.QToolButton(self.frame_APV_6)
        self.btnMesureTolerance.setText(_fromUtf8(""))
        self.btnMesureTolerance.setIcon(icon)
        self.btnMesureTolerance.setObjectName(_fromUtf8("btnMesureTolerance"))
        self.horizontalLayout_10.addWidget(self.btnMesureTolerance)
        self.horizontalLayout_64.addWidget(self.frame_APV_6)
        self.vl_gbResult.addWidget(self.frame_TakeOffSurfaceTrack_2)
        self.frame_TakeOffSurfaceTrack_3 = QtGui.QFrame(self.gbResult)
        self.frame_TakeOffSurfaceTrack_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_TakeOffSurfaceTrack_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_TakeOffSurfaceTrack_3.setObjectName(_fromUtf8("frame_TakeOffSurfaceTrack_3"))
        self.horizontalLayout_65 = QtGui.QHBoxLayout(self.frame_TakeOffSurfaceTrack_3)
        self.horizontalLayout_65.setSpacing(0)
        self.horizontalLayout_65.setMargin(0)
        self.horizontalLayout_65.setObjectName(_fromUtf8("horizontalLayout_65"))
        self.label_73 = QtGui.QLabel(self.frame_TakeOffSurfaceTrack_3)
        self.label_73.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.horizontalLayout_65.addWidget(self.label_73)
        self.frame_APV_7 = QtGui.QFrame(self.frame_TakeOffSurfaceTrack_3)
        self.frame_APV_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_7.setObjectName(_fromUtf8("frame_APV_7"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.frame_APV_7)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.txtResultSlantTol = QtGui.QLineEdit(self.frame_APV_7)
        self.txtResultSlantTol.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtResultSlantTol.setFont(font)
        self.txtResultSlantTol.setText(_fromUtf8(""))
        self.txtResultSlantTol.setObjectName(_fromUtf8("txtResultSlantTol"))
        self.txtResultSlantTol.setMinimumSize(QtCore.QSize(130, 0))
        self.txtResultSlantTol.setMaximumSize(QtCore.QSize(130, 16777215))
        self.horizontalLayout_11.addWidget(self.txtResultSlantTol)
        self.btnMesureSlant = QtGui.QToolButton(self.frame_APV_7)
        self.btnMesureSlant.setText(_fromUtf8(""))
        self.btnMesureSlant.setIcon(icon)
        self.btnMesureSlant.setObjectName(_fromUtf8("btnMesureSlant"))
        self.horizontalLayout_11.addWidget(self.btnMesureSlant)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(horizontalSpacer)
        self.horizontalLayout_65.addWidget(self.frame_APV_7)

        self.vl_gbResult.addWidget(self.frame_TakeOffSurfaceTrack_3)
        self.vl_gbCalculation.addWidget(self.gbResult)
        self.verticalLayout.addWidget(self.gbCalculation)
        self.gbConstruction = QtGui.QGroupBox(Form)
        self.gbConstruction.setObjectName(_fromUtf8("gbConstruction"))
        self.vl_gbConstruction = QtGui.QVBoxLayout(self.gbConstruction)
        self.vl_gbConstruction.setObjectName(_fromUtf8("vl_gbConstruction"))

        self.cmbBasedOn = ComboBoxPanel(self.gbConstruction, True)
        self.cmbBasedOn.Caption = "Based On"
        self.cmbBasedOn.LabelWidth = 150
        self.cmbBasedOn.Width = 120
        self.vl_gbConstruction.addWidget(self.cmbBasedOn)

        self.frame_67 = QtGui.QFrame(self.gbConstruction)
        self.frame_67.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_67.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_67.setObjectName(_fromUtf8("frame_67"))
        self.horizontalLayout_67 = QtGui.QHBoxLayout(self.frame_67)
        self.horizontalLayout_67.setSpacing(0)
        self.horizontalLayout_67.setMargin(0)
        self.horizontalLayout_67.setObjectName(_fromUtf8("horizontalLayout_67"))
        self.label_75 = QtGui.QLabel(self.frame_67)
        self.label_75.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.horizontalLayout_67.addWidget(self.label_75)
        self.cmbConstructionType = QtGui.QComboBox(self.frame_67)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConstructionType.sizePolicy().hasHeightForWidth())
        self.cmbConstructionType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbConstructionType.setFont(font)
        self.cmbConstructionType.setObjectName(_fromUtf8("cmbConstructionType"))
        self.cmbConstructionType.setMinimumSize(QtCore.QSize(100, 0))
        self.cmbConstructionType.setMaximumSize(QtCore.QSize(100, 16777215))
        self.horizontalLayout_67.addWidget(self.cmbConstructionType)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_67.addItem(horizontalSpacer)
        self.vl_gbConstruction.addWidget(self.frame_67)

        self.pnlRadial = TrackRadialBoxPanel(self.gbConstruction)
        self.pnlRadial.Caption = "Radial"
        self.vl_gbConstruction.addWidget(self.pnlRadial)
        # self.pnlRadial = QtGui.QFrame(self.gbConstruction)
        # self.pnlRadial.setFrameShape(QtGui.QFrame.NoFrame)
        # self.pnlRadial.setFrameShadow(QtGui.QFrame.Raised)
        # self.pnlRadial.setObjectName(_fromUtf8("pnlRadial"))
        # self.horizontalLayout_69 = QtGui.QHBoxLayout(self.pnlRadial)
        # self.horizontalLayout_69.setSpacing(0)
        # self.horizontalLayout_69.setMargin(0)
        # self.horizontalLayout_69.setObjectName(_fromUtf8("horizontalLayout_69"))
        # self.label_77 = QtGui.QLabel(self.pnlRadial)
        # self.label_77.setMinimumSize(QtCore.QSize(150, 0))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_77.setFont(font)
        # self.label_77.setObjectName(_fromUtf8("label_77"))
        # self.horizontalLayout_69.addWidget(self.label_77)
        # self.frame_APV_9 = QtGui.QFrame(self.pnlRadial)
        # self.frame_APV_9.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frame_APV_9.setFrameShadow(QtGui.QFrame.Raised)
        # self.frame_APV_9.setObjectName(_fromUtf8("frame_APV_9"))
        # self.horizontalLayout_13 = QtGui.QHBoxLayout(self.frame_APV_9)
        # self.horizontalLayout_13.setSpacing(0)
        # self.horizontalLayout_13.setMargin(0)
        # self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        # self.txtRadial = QtGui.QLineEdit(self.frame_APV_9)
        # self.txtRadial.setEnabled(True)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.txtRadial.setFont(font)
        # self.txtRadial.setText(_fromUtf8(""))
        # self.txtRadial.setObjectName(_fromUtf8("txtRadial"))
        # self.horizontalLayout_13.addWidget(self.txtRadial)
        # self.btnCaptureRadial = QtGui.QToolButton(self.frame_APV_9)
        # self.btnCaptureRadial.setText(_fromUtf8(""))
        # self.btnCaptureRadial.setIcon(icon)
        # self.btnCaptureRadial.setObjectName(_fromUtf8("btnCaptureRadial"))
        # self.horizontalLayout_13.addWidget(self.btnCaptureRadial)
        # self.horizontalLayout_69.addWidget(self.frame_APV_9)
        # self.vl_gbConstruction.addWidget(self.pnlRadial)
        self.chbDrawDmeTol = QtGui.QCheckBox(self.gbConstruction)
        self.chbDrawDmeTol.setChecked(True)
        self.chbDrawDmeTol.setObjectName(_fromUtf8("chbDrawDmeTol"))
        self.vl_gbConstruction.addWidget(self.chbDrawDmeTol)
        self.chbDrawSlantTol = QtGui.QCheckBox(self.gbConstruction)
        self.chbDrawSlantTol.setChecked(True)
        self.chbDrawSlantTol.setObjectName(_fromUtf8("chbDrawSlantTol"))
        self.vl_gbConstruction.addWidget(self.chbDrawSlantTol)
        self.chbDrawRadial = QtGui.QCheckBox(self.gbConstruction)
        self.chbDrawRadial.setChecked(True)
        self.chbDrawRadial.setObjectName(_fromUtf8("chbDrawRadial"))
        self.vl_gbConstruction.addWidget(self.chbDrawRadial)
        self.chbWriteText = QtGui.QCheckBox(self.gbConstruction)
        self.chbWriteText.setChecked(True)
        self.chbWriteText.setObjectName(_fromUtf8("chbWriteText"))
        self.vl_gbConstruction.addWidget(self.chbWriteText)
        self.chbInsertSymbol = QtGui.QCheckBox(self.gbConstruction)
        self.chbInsertSymbol.setChecked(True)
        self.chbInsertSymbol.setObjectName(_fromUtf8("chbInsertSymbol"))
        self.vl_gbConstruction.addWidget(self.chbInsertSymbol)
        self.verticalLayout.addWidget(self.gbConstruction)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.gbCalculation.setTitle(_translate("Form", "Calculation", None))
        self.label_74.setText(_translate("Form", "Type:", None))
        self.label_76.setText(_translate("Form", "Pilot Read-out (nm):", None))
        self.txtDistance.setText(_translate("Form", "5", None))
        self.label_68.setText(_translate("Form", "Aircraft Altitude:", None))
        self.label_2.setText(_translate("Form", "m", None))
        self.txtAcAltitude.setText(_translate("Form", "2000", None))
        self.label.setText(_translate("Form", "ft", None))
        self.lbDmeAltitude.setText(_translate("Form", "DME Station Altitude:", None))
        self.txtDmeAltitude.setText(_translate("Form", "10", None))
        self.label_6.setText(_translate("Form", "m", None))
        self.labelMocFt.setText(_translate("Form", "ft", None))
        self.gbResult.setTitle(_translate("Form", "Result", None))
        self.lblResultDistance.setText(_translate("Form", "Ground Distance:", None))
        self.label_72.setText(_translate("Form", "DME Tolerance:", None))
        self.label_73.setText(_translate("Form", "Slant Tolerance:", None))
        self.gbConstruction.setTitle(_translate("Form", "Construction", None))
        self.label_75.setText(_translate("Form", "Type:", None))
        # self.label_77.setText(_translate("Form", "Radial ():", None))
        self.chbDrawDmeTol.setText(_translate("Form", "Draw DME Tolerance", None))
        self.chbDrawSlantTol.setText(_translate("Form", "Draw Slant Tolerance", None))
        self.chbDrawRadial.setText(_translate("Form", "Draw Radial", None))
        self.chbWriteText.setText(_translate("Form", "Write DME Text", None))
        self.chbInsertSymbol.setText(_translate("Form", "Insert DME Symbol", None))

