# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qgsvectorlayerpropertiesbase(style).ui'
#
# Created: Wed Apr 01 15:33:29 2015
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s
import qrc_images
class Ui_VectorLayerProPertyDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(613, 397)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mOptionsSplitter = QtGui.QSplitter(Dialog)
        self.mOptionsSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.mOptionsSplitter.setChildrenCollapsible(False)
        self.mOptionsSplitter.setObjectName(_fromUtf8("mOptionsSplitter"))
        self.mOptionsListFrame = QtGui.QFrame(self.mOptionsSplitter)
        self.mOptionsListFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.mOptionsListFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.mOptionsListFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mOptionsListFrame.setObjectName(_fromUtf8("mOptionsListFrame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.mOptionsListFrame)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mOptionsListWidget = QtGui.QListWidget(self.mOptionsListFrame)
        self.mOptionsListWidget.setMinimumSize(QtCore.QSize(120, 0))
        self.mOptionsListWidget.setMaximumSize(QtCore.QSize(120, 16777215))
        self.mOptionsListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mOptionsListWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.mOptionsListWidget.setIconSize(QtCore.QSize(32, 32))
        self.mOptionsListWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.mOptionsListWidget.setResizeMode(QtGui.QListView.Adjust)
        self.mOptionsListWidget.setWordWrap(True)
        self.mOptionsListWidget.setObjectName(_fromUtf8("mOptionsListWidget"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/general.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.mOptionsListWidget)
        item.setIcon(icon)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/propertyicons/symbology.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.mOptionsListWidget)
        item.setIcon(icon1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionLabeling.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.mOptionsListWidget)
        item.setIcon(icon2)
        self.verticalLayout_2.addWidget(self.mOptionsListWidget)
        self.mOptionsFrame = QtGui.QFrame(self.mOptionsSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mOptionsFrame.sizePolicy().hasHeightForWidth())
        self.mOptionsFrame.setSizePolicy(sizePolicy)
        self.mOptionsFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.mOptionsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mOptionsFrame.setObjectName(_fromUtf8("mOptionsFrame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.mOptionsFrame)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.stackedWidget = QtGui.QStackedWidget(self.mOptionsFrame)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_3 = QtGui.QWidget(Dialog)
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_3 = QtGui.QGroupBox(self.page_3)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblLayerSource = QtGui.QLabel(self.groupBox_3)
        self.lblLayerSource.setObjectName(_fromUtf8("lblLayerSource"))
        self.gridLayout_2.addWidget(self.lblLayerSource, 0, 0, 1, 1)
        self.txtLayerSource = QtGui.QLineEdit(self.groupBox_3)
        self.txtLayerSource.setEnabled(True)
        self.txtLayerSource.setReadOnly(True)
        self.txtLayerSource.setObjectName(_fromUtf8("txtLayerSource"))
        self.gridLayout_2.addWidget(self.txtLayerSource, 0, 1, 1, 1)
        self.textLabel3 = QtGui.QLabel(self.groupBox_3)
        self.textLabel3.setObjectName(_fromUtf8("textLabel3"))
        self.gridLayout_2.addWidget(self.textLabel3, 1, 0, 1, 1)
        self.txtLayerName = QtGui.QLineEdit(self.groupBox_3)
        self.txtLayerName.setEnabled(True)
        self.txtLayerName.setReadOnly(True)
        self.txtLayerName.setObjectName(_fromUtf8("txtLayerName"))
        self.gridLayout_2.addWidget(self.txtLayerName, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.page_3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.txtCrs = QtGui.QLineEdit(self.groupBox_2)
        self.txtCrs.setMinimumSize(QtCore.QSize(100, 0))
        self.txtCrs.setReadOnly(True)
        self.txtCrs.setObjectName(_fromUtf8("txtCrs"))
        self.horizontalLayout_6.addWidget(self.txtCrs)
        self.btnCrsSelect = QtGui.QPushButton(self.groupBox_2)
        self.btnCrsSelect.setObjectName(_fromUtf8("btnCrsSelect"))
        self.horizontalLayout_6.addWidget(self.btnCrsSelect)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget(Dialog)
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.page_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self._2 = QtGui.QHBoxLayout()
        self._2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self._2.setObjectName(_fromUtf8("_2"))
        self.btnLoadStyle = QtGui.QPushButton(self.mOptionsFrame)
        self.btnLoadStyle.setMinimumSize(QtCore.QSize(70, 0))
        self.btnLoadStyle.setObjectName(_fromUtf8("btnLoadStyle"))
        self._2.addWidget(self.btnLoadStyle)
        self.btnSaveDefault = QtGui.QPushButton(self.mOptionsFrame)
        self.btnSaveDefault.setObjectName(_fromUtf8("btnSaveDefault"))
        self._2.addWidget(self.btnSaveDefault)
        self.btnRestoreDefalut = QtGui.QPushButton(self.mOptionsFrame)
        self.btnRestoreDefalut.setObjectName(_fromUtf8("btnRestoreDefalut"))
        self._2.addWidget(self.btnRestoreDefalut)
        self.btnSaveStyleAs = QtGui.QPushButton(self.mOptionsFrame)
        self.btnSaveStyleAs.setMinimumSize(QtCore.QSize(70, 0))
        self.btnSaveStyleAs.setObjectName(_fromUtf8("btnSaveStyleAs"))
        self._2.addWidget(self.btnSaveStyleAs)
        self.verticalLayout_3.addLayout(self._2)
        self.verticalLayout.addWidget(self.mOptionsSplitter)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.mOptionsListWidget.setCurrentRow(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Layer Properties", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.mOptionsListWidget.isSortingEnabled()
        self.mOptionsListWidget.setSortingEnabled(False)
        self.mOptionsListWidget.item(0).setText(QtGui.QApplication.translate("Dialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.mOptionsListWidget.item(1).setText(QtGui.QApplication.translate("Dialog", "Style", None, QtGui.QApplication.UnicodeUTF8))
        self.mOptionsListWidget.item(2).setText(QtGui.QApplication.translate("Dialog", "Labels", None, QtGui.QApplication.UnicodeUTF8))
        self.mOptionsListWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Layer info", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLayerSource.setText(QtGui.QApplication.translate("Dialog", "Layer source", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3.setText(QtGui.QApplication.translate("Dialog", "Layer name", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Coordinate reference system", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCrsSelect.setToolTip(QtGui.QApplication.translate("Dialog", "Specify the coordinate reference system of the layer\'s geometry.", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCrsSelect.setWhatsThis(QtGui.QApplication.translate("Dialog", "Specify the coordinate reference system of the layer\'s geometry.", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCrsSelect.setText(QtGui.QApplication.translate("Dialog", "Specify...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoadStyle.setText(QtGui.QApplication.translate("Dialog", "Load Style ...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaveDefault.setText(QtGui.QApplication.translate("Dialog", "Save As Default", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRestoreDefalut.setText(QtGui.QApplication.translate("Dialog", "Restore Default Style", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaveStyleAs.setText(QtGui.QApplication.translate("Dialog", "Save Style ...", None, QtGui.QApplication.UnicodeUTF8))

