# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RnavStraightSegmentAnalyser.ui'
#
# Created: Wed Nov 25 17:09:23 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from FlightPlanner.Panels.TrackRadialBoxPanel import TrackRadialBoxPanel

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RnavStraightSegmentAnalyser(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(452, 602)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbGeneral = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbGeneral.sizePolicy().hasHeightForWidth())
        self.gbGeneral.setSizePolicy(sizePolicy)
        self.gbGeneral.setObjectName(_fromUtf8("gbGeneral"))
        self.vl_gbGeneral = QtGui.QVBoxLayout(self.gbGeneral)
        self.vl_gbGeneral.setObjectName(_fromUtf8("vl_gbGeneral"))
        self.frameRnavSpecification = QtGui.QFrame(self.gbGeneral)
        self.frameRnavSpecification.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameRnavSpecification.setFrameShadow(QtGui.QFrame.Raised)
        self.frameRnavSpecification.setObjectName(_fromUtf8("frameRnavSpecification"))
        self.hLayoutRnavSpecification = QtGui.QHBoxLayout(self.frameRnavSpecification)
        self.hLayoutRnavSpecification.setSpacing(0)
        self.hLayoutRnavSpecification.setMargin(0)
        self.hLayoutRnavSpecification.setObjectName(_fromUtf8("hLayoutRnavSpecification"))
        self.label_67 = QtGui.QLabel(self.frameRnavSpecification)
        self.label_67.setMinimumSize(QtCore.QSize(180, 0))
        self.label_67.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.hLayoutRnavSpecification.addWidget(self.label_67)
        self.cmbRnavSpecification = QtGui.QComboBox(self.frameRnavSpecification)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRnavSpecification.sizePolicy().hasHeightForWidth())
        self.cmbRnavSpecification.setSizePolicy(sizePolicy)
        self.cmbRnavSpecification.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbRnavSpecification.setFont(font)
        self.cmbRnavSpecification.setObjectName(_fromUtf8("cmbRnavSpecification"))
        self.hLayoutRnavSpecification.addWidget(self.cmbRnavSpecification)
        self.vl_gbGeneral.addWidget(self.frameRnavSpecification)
        self.framePhaseOfFlight = QtGui.QFrame(self.gbGeneral)
        self.framePhaseOfFlight.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePhaseOfFlight.setFrameShadow(QtGui.QFrame.Raised)
        self.framePhaseOfFlight.setObjectName(_fromUtf8("framePhaseOfFlight"))
        self.hLayoutPhaseOfFlight = QtGui.QHBoxLayout(self.framePhaseOfFlight)
        self.hLayoutPhaseOfFlight.setSpacing(0)
        self.hLayoutPhaseOfFlight.setMargin(0)
        self.hLayoutPhaseOfFlight.setObjectName(_fromUtf8("hLayoutPhaseOfFlight"))
        self.label_69 = QtGui.QLabel(self.framePhaseOfFlight)
        self.label_69.setMinimumSize(QtCore.QSize(180, 0))
        self.label_69.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.hLayoutPhaseOfFlight.addWidget(self.label_69)
        self.cmbPhaseOfFlight = QtGui.QComboBox(self.framePhaseOfFlight)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPhaseOfFlight.sizePolicy().hasHeightForWidth())
        self.cmbPhaseOfFlight.setSizePolicy(sizePolicy)
        self.cmbPhaseOfFlight.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbPhaseOfFlight.setFont(font)
        self.cmbPhaseOfFlight.setObjectName(_fromUtf8("cmbPhaseOfFlight"))
        self.hLayoutPhaseOfFlight.addWidget(self.cmbPhaseOfFlight)
        self.vl_gbGeneral.addWidget(self.framePhaseOfFlight)
        self.chbCatH = QtGui.QCheckBox(self.gbGeneral)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbCatH.setFont(font)
        self.chbCatH.setObjectName(_fromUtf8("chbCatH"))
        self.vl_gbGeneral.addWidget(self.chbCatH)
        self.verticalLayout.addWidget(self.gbGeneral)
        self.gbParameters = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbParameters.sizePolicy().hasHeightForWidth())
        self.gbParameters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.gbParameters.setFont(font)
        self.gbParameters.setObjectName(_fromUtf8("gbParameters"))
        self.vl_gbParameters = QtGui.QVBoxLayout(self.gbParameters)
        self.vl_gbParameters.setObjectName(_fromUtf8("vl_gbParameters"))
        self.frameSelectionMode = QtGui.QFrame(self.gbParameters)
        self.frameSelectionMode.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameSelectionMode.setFrameShadow(QtGui.QFrame.Raised)
        self.frameSelectionMode.setObjectName(_fromUtf8("frameSelectionMode"))
        self.hLayoutSelectionMode = QtGui.QHBoxLayout(self.frameSelectionMode)
        self.hLayoutSelectionMode.setSpacing(0)
        self.hLayoutSelectionMode.setMargin(0)
        self.hLayoutSelectionMode.setObjectName(_fromUtf8("hLayoutSelectionMode"))
        self.label_66 = QtGui.QLabel(self.frameSelectionMode)
        self.label_66.setMinimumSize(QtCore.QSize(180, 0))
        self.label_66.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.hLayoutSelectionMode.addWidget(self.label_66)
        self.cmbSelectionMode = QtGui.QComboBox(self.frameSelectionMode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSelectionMode.sizePolicy().hasHeightForWidth())
        self.cmbSelectionMode.setSizePolicy(sizePolicy)
        self.cmbSelectionMode.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbSelectionMode.setFont(font)
        self.cmbSelectionMode.setObjectName(_fromUtf8("cmbSelectionMode"))
        self.hLayoutSelectionMode.addWidget(self.cmbSelectionMode)
        self.vl_gbParameters.addWidget(self.frameSelectionMode)
        self.frameAltitude = QtGui.QFrame(self.gbParameters)
        self.frameAltitude.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAltitude.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAltitude.setObjectName(_fromUtf8("frameAltitude"))
        self.hLayoutAltitude = QtGui.QHBoxLayout(self.frameAltitude)
        self.hLayoutAltitude.setSpacing(0)
        self.hLayoutAltitude.setMargin(0)
        self.hLayoutAltitude.setObjectName(_fromUtf8("hLayoutAltitude"))
        self.label_77 = QtGui.QLabel(self.frameAltitude)
        self.label_77.setMinimumSize(QtCore.QSize(180, 0))
        self.label_77.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.hLayoutAltitude.addWidget(self.label_77)
        self.txtAltitudeM = QtGui.QLineEdit(self.frameAltitude)
        self.txtAltitudeM.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitudeM.setFont(font)
        self.txtAltitudeM.setText(_fromUtf8(""))
        self.txtAltitudeM.setObjectName(_fromUtf8("txtAltitudeM"))
        self.hLayoutAltitude.addWidget(self.txtAltitudeM)
        self.label = QtGui.QLabel(self.frameAltitude)
        self.label.setObjectName(_fromUtf8("label"))
        self.hLayoutAltitude.addWidget(self.label)
        self.txtAltitude = QtGui.QLineEdit(self.frameAltitude)
        self.txtAltitude.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitude.setFont(font)
        self.txtAltitude.setObjectName(_fromUtf8("txtAltitude"))
        self.hLayoutAltitude.addWidget(self.txtAltitude)
        self.label_2 = QtGui.QLabel(self.frameAltitude)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.hLayoutAltitude.addWidget(self.label_2)
        self.vl_gbParameters.addWidget(self.frameAltitude)
        self.framePrimaryMoc = QtGui.QFrame(self.gbParameters)
        self.framePrimaryMoc.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePrimaryMoc.setFrameShadow(QtGui.QFrame.Raised)
        self.framePrimaryMoc.setObjectName(_fromUtf8("framePrimaryMoc"))
        self.hLayoutPrimaryMoc = QtGui.QHBoxLayout(self.framePrimaryMoc)
        self.hLayoutPrimaryMoc.setSpacing(0)
        self.hLayoutPrimaryMoc.setMargin(0)
        self.hLayoutPrimaryMoc.setObjectName(_fromUtf8("hLayoutPrimaryMoc"))
        self.label_68 = QtGui.QLabel(self.framePrimaryMoc)
        self.label_68.setMinimumSize(QtCore.QSize(180, 0))
        self.label_68.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.hLayoutPrimaryMoc.addWidget(self.label_68)
        self.txtPrimaryMoc = QtGui.QLineEdit(self.framePrimaryMoc)
        self.txtPrimaryMoc.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPrimaryMoc.setFont(font)
        self.txtPrimaryMoc.setObjectName(_fromUtf8("txtPrimaryMoc"))
        self.hLayoutPrimaryMoc.addWidget(self.txtPrimaryMoc)
        self.label_6 = QtGui.QLabel(self.framePrimaryMoc)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.hLayoutPrimaryMoc.addWidget(self.label_6)
        self.txtPrimaryMocFt = QtGui.QLineEdit(self.framePrimaryMoc)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPrimaryMocFt.setFont(font)
        self.txtPrimaryMocFt.setText(_fromUtf8(""))
        self.txtPrimaryMocFt.setObjectName(_fromUtf8("txtPrimaryMocFt"))
        self.hLayoutPrimaryMoc.addWidget(self.txtPrimaryMocFt)
        self.labelMocFt = QtGui.QLabel(self.framePrimaryMoc)
        self.labelMocFt.setObjectName(_fromUtf8("labelMocFt"))
        self.hLayoutPrimaryMoc.addWidget(self.labelMocFt)
        self.vl_gbParameters.addWidget(self.framePrimaryMoc)
        self.frameConstruct = QtGui.QFrame(self.gbParameters)
        self.frameConstruct.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameConstruct.setFrameShadow(QtGui.QFrame.Raised)
        self.frameConstruct.setObjectName(_fromUtf8("frameConstruct"))
        self.hLayoutConstruct = QtGui.QHBoxLayout(self.frameConstruct)
        self.hLayoutConstruct.setSpacing(0)
        self.hLayoutConstruct.setMargin(0)
        self.hLayoutConstruct.setObjectName(_fromUtf8("hLayoutConstruct"))
        self.label_83 = QtGui.QLabel(self.frameConstruct)
        self.label_83.setMinimumSize(QtCore.QSize(180, 0))
        self.label_83.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_83.setFont(font)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.hLayoutConstruct.addWidget(self.label_83)
        self.cmbConstruct = QtGui.QComboBox(self.frameConstruct)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConstruct.sizePolicy().hasHeightForWidth())
        self.cmbConstruct.setSizePolicy(sizePolicy)
        self.cmbConstruct.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbConstruct.setFont(font)
        self.cmbConstruct.setObjectName(_fromUtf8("cmbConstruct"))
        self.hLayoutConstruct.addWidget(self.cmbConstruct)
        self.vl_gbParameters.addWidget(self.frameConstruct)
        self.frameMOCmultipiler = QtGui.QFrame(self.gbParameters)
        self.frameMOCmultipiler.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMOCmultipiler.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMOCmultipiler.setObjectName(_fromUtf8("frameMOCmultipiler"))
        self.hLayoutMOCmultipiler = QtGui.QHBoxLayout(self.frameMOCmultipiler)
        self.hLayoutMOCmultipiler.setSpacing(0)
        self.hLayoutMOCmultipiler.setMargin(0)
        self.hLayoutMOCmultipiler.setObjectName(_fromUtf8("hLayoutMOCmultipiler"))
        self.label_84 = QtGui.QLabel(self.frameMOCmultipiler)
        self.label_84.setMinimumSize(QtCore.QSize(180, 0))
        self.label_84.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_84.setFont(font)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.hLayoutMOCmultipiler.addWidget(self.label_84)
        self.mocSpinBox = QtGui.QSpinBox(self.frameMOCmultipiler)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mocSpinBox.sizePolicy().hasHeightForWidth())
        self.mocSpinBox.setSizePolicy(sizePolicy)
        self.mocSpinBox.setMinimumSize(QtCore.QSize(72, 0))
        self.mocSpinBox.setMinimum(1)
        self.mocSpinBox.setObjectName(_fromUtf8("mocSpinBox"))
        self.hLayoutMOCmultipiler.addWidget(self.mocSpinBox)
        self.vl_gbParameters.addWidget(self.frameMOCmultipiler)
        self.chbDrawTolerance = QtGui.QCheckBox(self.gbParameters)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbDrawTolerance.setFont(font)
        self.chbDrawTolerance.setObjectName(_fromUtf8("chbDrawTolerance"))
        self.vl_gbParameters.addWidget(self.chbDrawTolerance)
        self.verticalLayout.addWidget(self.gbParameters)
        self.gbResultsVOR = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbResultsVOR.sizePolicy().hasHeightForWidth())
        self.gbResultsVOR.setSizePolicy(sizePolicy)
        self.gbResultsVOR.setObjectName(_fromUtf8("gbResultsVOR"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gbResultsVOR)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gbResultsWaypoint1 = QtGui.QGroupBox(self.gbResultsVOR)
        self.gbResultsWaypoint1.setObjectName(_fromUtf8("gbResultsWaypoint1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbResultsWaypoint1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_70 = QtGui.QFrame(self.gbResultsWaypoint1)
        self.frame_70.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_70.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_70.setObjectName(_fromUtf8("frame_70"))
        self.horizontalLayout_77 = QtGui.QHBoxLayout(self.frame_70)
        self.horizontalLayout_77.setSpacing(0)
        self.horizontalLayout_77.setMargin(0)
        self.horizontalLayout_77.setObjectName(_fromUtf8("horizontalLayout_77"))
        self.label_85 = QtGui.QLabel(self.frame_70)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_85.sizePolicy().hasHeightForWidth())
        self.label_85.setSizePolicy(sizePolicy)
        self.label_85.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_85.setFont(font)
        self.label_85.setFrameShadow(QtGui.QFrame.Plain)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.horizontalLayout_77.addWidget(self.label_85)
        self.txtXtt1V = QtGui.QLineEdit(self.frame_70)
        self.txtXtt1V.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtXtt1V.sizePolicy().hasHeightForWidth())
        self.txtXtt1V.setSizePolicy(sizePolicy)
        self.txtXtt1V.setMinimumSize(QtCore.QSize(0, 0))
        self.txtXtt1V.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtXtt1V.setFont(font)
        self.txtXtt1V.setObjectName(_fromUtf8("txtXtt1V"))
        self.horizontalLayout_77.addWidget(self.txtXtt1V)
        self.verticalLayout_2.addWidget(self.frame_70)
        self.frame_71 = QtGui.QFrame(self.gbResultsWaypoint1)
        self.frame_71.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_71.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_71.setObjectName(_fromUtf8("frame_71"))
        self.horizontalLayout_78 = QtGui.QHBoxLayout(self.frame_71)
        self.horizontalLayout_78.setSpacing(0)
        self.horizontalLayout_78.setMargin(0)
        self.horizontalLayout_78.setObjectName(_fromUtf8("horizontalLayout_78"))
        self.label_86 = QtGui.QLabel(self.frame_71)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_86.sizePolicy().hasHeightForWidth())
        self.label_86.setSizePolicy(sizePolicy)
        self.label_86.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_86.setFont(font)
        self.label_86.setFrameShadow(QtGui.QFrame.Plain)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.horizontalLayout_78.addWidget(self.label_86)
        self.txtAtt1V = QtGui.QLineEdit(self.frame_71)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAtt1V.sizePolicy().hasHeightForWidth())
        self.txtAtt1V.setSizePolicy(sizePolicy)
        self.txtAtt1V.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAtt1V.setFont(font)
        self.txtAtt1V.setObjectName(_fromUtf8("txtAtt1V"))
        self.horizontalLayout_78.addWidget(self.txtAtt1V)
        self.verticalLayout_2.addWidget(self.frame_71)
        self.frame_72 = QtGui.QFrame(self.gbResultsWaypoint1)
        self.frame_72.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_72.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_72.setObjectName(_fromUtf8("frame_72"))
        self.horizontalLayout_79 = QtGui.QHBoxLayout(self.frame_72)
        self.horizontalLayout_79.setSpacing(0)
        self.horizontalLayout_79.setMargin(0)
        self.horizontalLayout_79.setObjectName(_fromUtf8("horizontalLayout_79"))
        self.label_87 = QtGui.QLabel(self.frame_72)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_87.sizePolicy().hasHeightForWidth())
        self.label_87.setSizePolicy(sizePolicy)
        self.label_87.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_87.setFont(font)
        self.label_87.setFrameShadow(QtGui.QFrame.Plain)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.horizontalLayout_79.addWidget(self.label_87)
        self.txtAsw1V = QtGui.QLineEdit(self.frame_72)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAsw1V.sizePolicy().hasHeightForWidth())
        self.txtAsw1V.setSizePolicy(sizePolicy)
        self.txtAsw1V.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAsw1V.setFont(font)
        self.txtAsw1V.setObjectName(_fromUtf8("txtAsw1V"))
        self.horizontalLayout_79.addWidget(self.txtAsw1V)
        self.verticalLayout_2.addWidget(self.frame_72)
        self.horizontalLayout.addWidget(self.gbResultsWaypoint1)
        self.gbResultsWaypoint2 = QtGui.QGroupBox(self.gbResultsVOR)
        self.gbResultsWaypoint2.setObjectName(_fromUtf8("gbResultsWaypoint2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbResultsWaypoint2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_73 = QtGui.QFrame(self.gbResultsWaypoint2)
        self.frame_73.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_73.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_73.setObjectName(_fromUtf8("frame_73"))
        self.horizontalLayout_80 = QtGui.QHBoxLayout(self.frame_73)
        self.horizontalLayout_80.setSpacing(0)
        self.horizontalLayout_80.setMargin(0)
        self.horizontalLayout_80.setObjectName(_fromUtf8("horizontalLayout_80"))
        self.label_88 = QtGui.QLabel(self.frame_73)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_88.sizePolicy().hasHeightForWidth())
        self.label_88.setSizePolicy(sizePolicy)
        self.label_88.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_88.setFont(font)
        self.label_88.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.horizontalLayout_80.addWidget(self.label_88)
        self.txtXtt2V = QtGui.QLineEdit(self.frame_73)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtXtt2V.sizePolicy().hasHeightForWidth())
        self.txtXtt2V.setSizePolicy(sizePolicy)
        self.txtXtt2V.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtXtt2V.setFont(font)
        self.txtXtt2V.setObjectName(_fromUtf8("txtXtt2V"))
        self.horizontalLayout_80.addWidget(self.txtXtt2V)
        self.verticalLayout_3.addWidget(self.frame_73)
        self.frame_74 = QtGui.QFrame(self.gbResultsWaypoint2)
        self.frame_74.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_74.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_74.setObjectName(_fromUtf8("frame_74"))
        self.horizontalLayout_81 = QtGui.QHBoxLayout(self.frame_74)
        self.horizontalLayout_81.setSpacing(0)
        self.horizontalLayout_81.setMargin(0)
        self.horizontalLayout_81.setObjectName(_fromUtf8("horizontalLayout_81"))
        self.label_89 = QtGui.QLabel(self.frame_74)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_89.sizePolicy().hasHeightForWidth())
        self.label_89.setSizePolicy(sizePolicy)
        self.label_89.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_89.setFont(font)
        self.label_89.setFrameShadow(QtGui.QFrame.Plain)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.horizontalLayout_81.addWidget(self.label_89)
        self.txtAtt2V = QtGui.QLineEdit(self.frame_74)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAtt2V.sizePolicy().hasHeightForWidth())
        self.txtAtt2V.setSizePolicy(sizePolicy)
        self.txtAtt2V.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAtt2V.setFont(font)
        self.txtAtt2V.setObjectName(_fromUtf8("txtAtt2V"))
        self.horizontalLayout_81.addWidget(self.txtAtt2V)
        self.verticalLayout_3.addWidget(self.frame_74)
        self.frame_75 = QtGui.QFrame(self.gbResultsWaypoint2)
        self.frame_75.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_75.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_75.setObjectName(_fromUtf8("frame_75"))
        self.horizontalLayout_82 = QtGui.QHBoxLayout(self.frame_75)
        self.horizontalLayout_82.setSpacing(0)
        self.horizontalLayout_82.setMargin(0)
        self.horizontalLayout_82.setObjectName(_fromUtf8("horizontalLayout_82"))
        self.label_90 = QtGui.QLabel(self.frame_75)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_90.sizePolicy().hasHeightForWidth())
        self.label_90.setSizePolicy(sizePolicy)
        self.label_90.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_90.setFont(font)
        self.label_90.setFrameShadow(QtGui.QFrame.Plain)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.horizontalLayout_82.addWidget(self.label_90)
        self.txtAsw2V = QtGui.QLineEdit(self.frame_75)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAsw2V.sizePolicy().hasHeightForWidth())
        self.txtAsw2V.setSizePolicy(sizePolicy)
        self.txtAsw2V.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAsw2V.setFont(font)
        self.txtAsw2V.setObjectName(_fromUtf8("txtAsw2V"))
        self.horizontalLayout_82.addWidget(self.txtAsw2V)
        self.verticalLayout_3.addWidget(self.frame_75)
        self.horizontalLayout.addWidget(self.gbResultsWaypoint2)
        self.verticalLayout.addWidget(self.gbResultsVOR)
        self.gbResultsDME = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbResultsDME.sizePolicy().hasHeightForWidth())
        self.gbResultsDME.setSizePolicy(sizePolicy)
        self.gbResultsDME.setObjectName(_fromUtf8("gbResultsDME"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.gbResultsDME)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gbResultsWaypoint1_2 = QtGui.QGroupBox(self.gbResultsDME)
        self.gbResultsWaypoint1_2.setObjectName(_fromUtf8("gbResultsWaypoint1_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gbResultsWaypoint1_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame_76 = QtGui.QFrame(self.gbResultsWaypoint1_2)
        self.frame_76.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_76.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_76.setObjectName(_fromUtf8("frame_76"))
        self.horizontalLayout_83 = QtGui.QHBoxLayout(self.frame_76)
        self.horizontalLayout_83.setSpacing(0)
        self.horizontalLayout_83.setMargin(0)
        self.horizontalLayout_83.setObjectName(_fromUtf8("horizontalLayout_83"))
        self.label_91 = QtGui.QLabel(self.frame_76)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_91.sizePolicy().hasHeightForWidth())
        self.label_91.setSizePolicy(sizePolicy)
        self.label_91.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_91.setFont(font)
        self.label_91.setFrameShadow(QtGui.QFrame.Plain)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.horizontalLayout_83.addWidget(self.label_91)
        self.txtXtt1D = QtGui.QLineEdit(self.frame_76)
        self.txtXtt1D.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtXtt1D.sizePolicy().hasHeightForWidth())
        self.txtXtt1D.setSizePolicy(sizePolicy)
        self.txtXtt1D.setMinimumSize(QtCore.QSize(0, 0))
        self.txtXtt1D.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtXtt1D.setFont(font)
        self.txtXtt1D.setObjectName(_fromUtf8("txtXtt1D"))
        self.horizontalLayout_83.addWidget(self.txtXtt1D)
        self.verticalLayout_4.addWidget(self.frame_76)
        self.frame_77 = QtGui.QFrame(self.gbResultsWaypoint1_2)
        self.frame_77.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_77.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_77.setObjectName(_fromUtf8("frame_77"))
        self.horizontalLayout_84 = QtGui.QHBoxLayout(self.frame_77)
        self.horizontalLayout_84.setSpacing(0)
        self.horizontalLayout_84.setMargin(0)
        self.horizontalLayout_84.setObjectName(_fromUtf8("horizontalLayout_84"))
        self.label_92 = QtGui.QLabel(self.frame_77)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_92.sizePolicy().hasHeightForWidth())
        self.label_92.setSizePolicy(sizePolicy)
        self.label_92.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_92.setFont(font)
        self.label_92.setFrameShadow(QtGui.QFrame.Plain)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.horizontalLayout_84.addWidget(self.label_92)
        self.txtAtt1D = QtGui.QLineEdit(self.frame_77)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAtt1D.sizePolicy().hasHeightForWidth())
        self.txtAtt1D.setSizePolicy(sizePolicy)
        self.txtAtt1D.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAtt1D.setFont(font)
        self.txtAtt1D.setObjectName(_fromUtf8("txtAtt1D"))
        self.horizontalLayout_84.addWidget(self.txtAtt1D)
        self.verticalLayout_4.addWidget(self.frame_77)
        self.frame_78 = QtGui.QFrame(self.gbResultsWaypoint1_2)
        self.frame_78.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_78.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_78.setObjectName(_fromUtf8("frame_78"))
        self.horizontalLayout_85 = QtGui.QHBoxLayout(self.frame_78)
        self.horizontalLayout_85.setSpacing(0)
        self.horizontalLayout_85.setMargin(0)
        self.horizontalLayout_85.setObjectName(_fromUtf8("horizontalLayout_85"))
        self.label_93 = QtGui.QLabel(self.frame_78)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_93.sizePolicy().hasHeightForWidth())
        self.label_93.setSizePolicy(sizePolicy)
        self.label_93.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_93.setFont(font)
        self.label_93.setFrameShadow(QtGui.QFrame.Plain)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.horizontalLayout_85.addWidget(self.label_93)
        self.txtAsw1D = QtGui.QLineEdit(self.frame_78)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAsw1D.sizePolicy().hasHeightForWidth())
        self.txtAsw1D.setSizePolicy(sizePolicy)
        self.txtAsw1D.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAsw1D.setFont(font)
        self.txtAsw1D.setObjectName(_fromUtf8("txtAsw1D"))
        self.horizontalLayout_85.addWidget(self.txtAsw1D)
        self.verticalLayout_4.addWidget(self.frame_78)
        self.horizontalLayout_2.addWidget(self.gbResultsWaypoint1_2)
        self.gbResultsWaypoint2_2 = QtGui.QGroupBox(self.gbResultsDME)
        self.gbResultsWaypoint2_2.setObjectName(_fromUtf8("gbResultsWaypoint2_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.gbResultsWaypoint2_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frame_79 = QtGui.QFrame(self.gbResultsWaypoint2_2)
        self.frame_79.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_79.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_79.setObjectName(_fromUtf8("frame_79"))
        self.horizontalLayout_86 = QtGui.QHBoxLayout(self.frame_79)
        self.horizontalLayout_86.setSpacing(0)
        self.horizontalLayout_86.setMargin(0)
        self.horizontalLayout_86.setObjectName(_fromUtf8("horizontalLayout_86"))
        self.label_94 = QtGui.QLabel(self.frame_79)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_94.sizePolicy().hasHeightForWidth())
        self.label_94.setSizePolicy(sizePolicy)
        self.label_94.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_94.setFont(font)
        self.label_94.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_94.setFrameShadow(QtGui.QFrame.Plain)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.horizontalLayout_86.addWidget(self.label_94)
        self.txtXtt2D = QtGui.QLineEdit(self.frame_79)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtXtt2D.sizePolicy().hasHeightForWidth())
        self.txtXtt2D.setSizePolicy(sizePolicy)
        self.txtXtt2D.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtXtt2D.setFont(font)
        self.txtXtt2D.setObjectName(_fromUtf8("txtXtt2D"))
        self.horizontalLayout_86.addWidget(self.txtXtt2D)
        self.verticalLayout_5.addWidget(self.frame_79)
        self.frame_80 = QtGui.QFrame(self.gbResultsWaypoint2_2)
        self.frame_80.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_80.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_80.setObjectName(_fromUtf8("frame_80"))
        self.horizontalLayout_87 = QtGui.QHBoxLayout(self.frame_80)
        self.horizontalLayout_87.setSpacing(0)
        self.horizontalLayout_87.setMargin(0)
        self.horizontalLayout_87.setObjectName(_fromUtf8("horizontalLayout_87"))
        self.label_95 = QtGui.QLabel(self.frame_80)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_95.sizePolicy().hasHeightForWidth())
        self.label_95.setSizePolicy(sizePolicy)
        self.label_95.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_95.setFont(font)
        self.label_95.setFrameShadow(QtGui.QFrame.Plain)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.horizontalLayout_87.addWidget(self.label_95)
        self.txtAtt2D = QtGui.QLineEdit(self.frame_80)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAtt2D.sizePolicy().hasHeightForWidth())
        self.txtAtt2D.setSizePolicy(sizePolicy)
        self.txtAtt2D.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAtt2D.setFont(font)
        self.txtAtt2D.setObjectName(_fromUtf8("txtAtt2D"))
        self.horizontalLayout_87.addWidget(self.txtAtt2D)
        self.verticalLayout_5.addWidget(self.frame_80)
        self.frame_81 = QtGui.QFrame(self.gbResultsWaypoint2_2)
        self.frame_81.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_81.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_81.setObjectName(_fromUtf8("frame_81"))
        self.horizontalLayout_88 = QtGui.QHBoxLayout(self.frame_81)
        self.horizontalLayout_88.setSpacing(0)
        self.horizontalLayout_88.setMargin(0)
        self.horizontalLayout_88.setObjectName(_fromUtf8("horizontalLayout_88"))
        self.label_96 = QtGui.QLabel(self.frame_81)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_96.sizePolicy().hasHeightForWidth())
        self.label_96.setSizePolicy(sizePolicy)
        self.label_96.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_96.setFont(font)
        self.label_96.setFrameShadow(QtGui.QFrame.Plain)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.horizontalLayout_88.addWidget(self.label_96)
        self.txtAsw2D = QtGui.QLineEdit(self.frame_81)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAsw2D.sizePolicy().hasHeightForWidth())
        self.txtAsw2D.setSizePolicy(sizePolicy)
        self.txtAsw2D.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAsw2D.setFont(font)
        self.txtAsw2D.setObjectName(_fromUtf8("txtAsw2D"))
        self.horizontalLayout_88.addWidget(self.txtAsw2D)
        self.verticalLayout_5.addWidget(self.frame_81)
        self.horizontalLayout_2.addWidget(self.gbResultsWaypoint2_2)
        self.verticalLayout.addWidget(self.gbResultsDME)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.gbGeneral.setTitle(_translate("Form", "General", None))
        self.label_67.setText(_translate("Form", "RNAV Specification:", None))
        self.label_69.setText(_translate("Form", "Phase Of Flight:", None))
        self.chbCatH.setText(_translate("Form", "Cat. H", None))
        self.gbParameters.setTitle(_translate("Form", "Parameters", None))
        self.label_66.setText(_translate("Form", "Selection Mode:", None))
        self.label_77.setText(_translate("Form", "Altitude:", None))
        self.label.setText(_translate("Form", "m", None))
        self.txtAltitude.setText(_translate("Form", "1000", None))
        self.label_2.setText(_translate("Form", "ft", None))
        self.label_68.setText(_translate("Form", "Primary Moc:", None))
        self.txtPrimaryMoc.setText(_translate("Form", "300", None))
        self.label_6.setText(_translate("Form", "m", None))
        self.labelMocFt.setText(_translate("Form", "ft", None))
        self.label_83.setText(_translate("Form", "Construction Type:", None))
        self.label_84.setText(_translate("Form", "MOCmultiplier:", None))
        self.chbDrawTolerance.setText(_translate("Form", "Draw Waypoint Tolerance", None))
        self.gbResultsVOR.setTitle(_translate("Form", "VOR / DME Results", None))
        self.gbResultsWaypoint1.setTitle(_translate("Form", "Waypoint1", None))
        self.label_85.setText(_translate("Form", "XTT(nm):", None))
        self.txtXtt1V.setText(_translate("Form", "0", None))
        self.label_86.setText(_translate("Form", "ATT(nm):", None))
        self.txtAtt1V.setText(_translate("Form", "0", None))
        self.label_87.setText(_translate("Form", "1/2 A/W(nm):", None))
        self.txtAsw1V.setText(_translate("Form", "0", None))
        self.gbResultsWaypoint2.setTitle(_translate("Form", "Waypoint2", None))
        self.label_88.setText(_translate("Form", "XTT(nm):", None))
        self.txtXtt2V.setText(_translate("Form", "0", None))
        self.label_89.setText(_translate("Form", "ATT(nm):", None))
        self.txtAtt2V.setText(_translate("Form", "0", None))
        self.label_90.setText(_translate("Form", "1/2 A/W(nm):", None))
        self.txtAsw2V.setText(_translate("Form", "0", None))
        self.gbResultsDME.setTitle(_translate("Form", "Results", None))
        self.gbResultsWaypoint1_2.setTitle(_translate("Form", "Waypoint1", None))
        self.label_91.setText(_translate("Form", "XTT(nm):", None))
        self.txtXtt1D.setText(_translate("Form", "0", None))
        self.label_92.setText(_translate("Form", "ATT(nm):", None))
        self.txtAtt1D.setText(_translate("Form", "0", None))
        self.label_93.setText(_translate("Form", "1/2 A/W(nm):", None))
        self.txtAsw1D.setText(_translate("Form", "0", None))
        self.gbResultsWaypoint2_2.setTitle(_translate("Form", "Waypoint2", None))
        self.label_94.setText(_translate("Form", "XTT(nm):", None))
        self.txtXtt2D.setText(_translate("Form", "0", None))
        self.label_95.setText(_translate("Form", "ATT(nm):", None))
        self.txtAtt2D.setText(_translate("Form", "0", None))
        self.label_96.setText(_translate("Form", "1/2 A/W(nm):", None))
        self.txtAsw2D.setText(_translate("Form", "0", None))

