# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RnavStraightSegmentAnalyser.ui'
#
# Created: Fri Sep 18 15:36:07 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RnavStraightSegmentAnalyser(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(382, 346)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbGeneral = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbGeneral.sizePolicy().hasHeightForWidth())
        self.gbGeneral.setSizePolicy(sizePolicy)
        self.gbGeneral.setObjectName(_fromUtf8("gbGeneral"))
        self.vl_gbGeneral = QtGui.QVBoxLayout(self.gbGeneral)
        self.vl_gbGeneral.setObjectName(_fromUtf8("vl_gbGeneral"))
        self.frameRnavSpecification = QtGui.QFrame(self.gbGeneral)
        self.frameRnavSpecification.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameRnavSpecification.setFrameShadow(QtGui.QFrame.Raised)
        self.frameRnavSpecification.setObjectName(_fromUtf8("frameRnavSpecification"))
        self.hLayoutRnavSpecification = QtGui.QHBoxLayout(self.frameRnavSpecification)
        self.hLayoutRnavSpecification.setSpacing(0)
        self.hLayoutRnavSpecification.setMargin(0)
        self.hLayoutRnavSpecification.setObjectName(_fromUtf8("hLayoutRnavSpecification"))
        self.label_67 = QtGui.QLabel(self.frameRnavSpecification)
        self.label_67.setMinimumSize(QtCore.QSize(180, 0))
        self.label_67.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.hLayoutRnavSpecification.addWidget(self.label_67)
        self.cmbRnavSpecification = QtGui.QComboBox(self.frameRnavSpecification)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRnavSpecification.sizePolicy().hasHeightForWidth())
        self.cmbRnavSpecification.setSizePolicy(sizePolicy)
        self.cmbRnavSpecification.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbRnavSpecification.setFont(font)
        self.cmbRnavSpecification.setObjectName(_fromUtf8("cmbRnavSpecification"))
        self.hLayoutRnavSpecification.addWidget(self.cmbRnavSpecification)
        self.vl_gbGeneral.addWidget(self.frameRnavSpecification)
        self.framePhaseOfFlight = QtGui.QFrame(self.gbGeneral)
        self.framePhaseOfFlight.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePhaseOfFlight.setFrameShadow(QtGui.QFrame.Raised)
        self.framePhaseOfFlight.setObjectName(_fromUtf8("framePhaseOfFlight"))
        self.hLayoutPhaseOfFlight = QtGui.QHBoxLayout(self.framePhaseOfFlight)
        self.hLayoutPhaseOfFlight.setSpacing(0)
        self.hLayoutPhaseOfFlight.setMargin(0)
        self.hLayoutPhaseOfFlight.setObjectName(_fromUtf8("hLayoutPhaseOfFlight"))
        self.label_69 = QtGui.QLabel(self.framePhaseOfFlight)
        self.label_69.setMinimumSize(QtCore.QSize(180, 0))
        self.label_69.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.hLayoutPhaseOfFlight.addWidget(self.label_69)
        self.cmbPhaseOfFlight = QtGui.QComboBox(self.framePhaseOfFlight)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPhaseOfFlight.sizePolicy().hasHeightForWidth())
        self.cmbPhaseOfFlight.setSizePolicy(sizePolicy)
        self.cmbPhaseOfFlight.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbPhaseOfFlight.setFont(font)
        self.cmbPhaseOfFlight.setObjectName(_fromUtf8("cmbPhaseOfFlight"))
        self.hLayoutPhaseOfFlight.addWidget(self.cmbPhaseOfFlight)
        self.vl_gbGeneral.addWidget(self.framePhaseOfFlight)
        self.chbCatH = QtGui.QCheckBox(self.gbGeneral)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbCatH.setFont(font)
        self.chbCatH.setObjectName(_fromUtf8("chbCatH"))
        self.vl_gbGeneral.addWidget(self.chbCatH)
        self.verticalLayout.addWidget(self.gbGeneral)
        self.gbParameters = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbParameters.sizePolicy().hasHeightForWidth())
        self.gbParameters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.gbParameters.setFont(font)
        self.gbParameters.setObjectName(_fromUtf8("gbParameters"))
        self.vl_gbParameters = QtGui.QVBoxLayout(self.gbParameters)
        self.vl_gbParameters.setObjectName(_fromUtf8("vl_gbParameters"))
        self.frameSelectionMode = QtGui.QFrame(self.gbParameters)
        self.frameSelectionMode.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameSelectionMode.setFrameShadow(QtGui.QFrame.Raised)
        self.frameSelectionMode.setObjectName(_fromUtf8("frameSelectionMode"))
        self.hLayoutSelectionMode = QtGui.QHBoxLayout(self.frameSelectionMode)
        self.hLayoutSelectionMode.setSpacing(0)
        self.hLayoutSelectionMode.setMargin(0)
        self.hLayoutSelectionMode.setObjectName(_fromUtf8("hLayoutSelectionMode"))
        self.label_66 = QtGui.QLabel(self.frameSelectionMode)
        self.label_66.setMinimumSize(QtCore.QSize(180, 0))
        self.label_66.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.hLayoutSelectionMode.addWidget(self.label_66)
        self.cmbSelectionMode = QtGui.QComboBox(self.frameSelectionMode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSelectionMode.sizePolicy().hasHeightForWidth())
        self.cmbSelectionMode.setSizePolicy(sizePolicy)
        self.cmbSelectionMode.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbSelectionMode.setFont(font)
        self.cmbSelectionMode.setObjectName(_fromUtf8("cmbSelectionMode"))
        self.hLayoutSelectionMode.addWidget(self.cmbSelectionMode)
        self.vl_gbParameters.addWidget(self.frameSelectionMode)
        self.frameAltitude = QtGui.QFrame(self.gbParameters)
        self.frameAltitude.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAltitude.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAltitude.setObjectName(_fromUtf8("frameAltitude"))
        self.hLayoutAltitude = QtGui.QHBoxLayout(self.frameAltitude)
        self.hLayoutAltitude.setSpacing(0)
        self.hLayoutAltitude.setMargin(0)
        self.hLayoutAltitude.setObjectName(_fromUtf8("hLayoutAltitude"))
        self.label_77 = QtGui.QLabel(self.frameAltitude)
        self.label_77.setMinimumSize(QtCore.QSize(180, 0))
        self.label_77.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.hLayoutAltitude.addWidget(self.label_77)
        self.txtAltitude = QtGui.QLineEdit(self.frameAltitude)
        self.txtAltitude.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitude.setFont(font)
        self.txtAltitude.setObjectName(_fromUtf8("txtAltitude"))
        self.hLayoutAltitude.addWidget(self.txtAltitude)
        self.vl_gbParameters.addWidget(self.frameAltitude)
        self.framePrimaryMoc = QtGui.QFrame(self.gbParameters)
        self.framePrimaryMoc.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePrimaryMoc.setFrameShadow(QtGui.QFrame.Raised)
        self.framePrimaryMoc.setObjectName(_fromUtf8("framePrimaryMoc"))
        self.hLayoutPrimaryMoc = QtGui.QHBoxLayout(self.framePrimaryMoc)
        self.hLayoutPrimaryMoc.setSpacing(0)
        self.hLayoutPrimaryMoc.setMargin(0)
        self.hLayoutPrimaryMoc.setObjectName(_fromUtf8("hLayoutPrimaryMoc"))
        self.label_68 = QtGui.QLabel(self.framePrimaryMoc)
        self.label_68.setMinimumSize(QtCore.QSize(180, 0))
        self.label_68.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.hLayoutPrimaryMoc.addWidget(self.label_68)
        self.txtPrimaryMoc = QtGui.QLineEdit(self.framePrimaryMoc)
        self.txtPrimaryMoc.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPrimaryMoc.setFont(font)
        self.txtPrimaryMoc.setObjectName(_fromUtf8("txtPrimaryMoc"))
        self.hLayoutPrimaryMoc.addWidget(self.txtPrimaryMoc)
        self.vl_gbParameters.addWidget(self.framePrimaryMoc)
        self.frameConstruct = QtGui.QFrame(self.gbParameters)
        self.frameConstruct.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameConstruct.setFrameShadow(QtGui.QFrame.Raised)
        self.frameConstruct.setObjectName(_fromUtf8("frameConstruct"))
        self.hLayoutConstruct = QtGui.QHBoxLayout(self.frameConstruct)
        self.hLayoutConstruct.setSpacing(0)
        self.hLayoutConstruct.setMargin(0)
        self.hLayoutConstruct.setObjectName(_fromUtf8("hLayoutConstruct"))
        self.label_83 = QtGui.QLabel(self.frameConstruct)
        self.label_83.setMinimumSize(QtCore.QSize(180, 0))
        self.label_83.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_83.setFont(font)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.hLayoutConstruct.addWidget(self.label_83)
        self.cmbConstruct = QtGui.QComboBox(self.frameConstruct)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConstruct.sizePolicy().hasHeightForWidth())
        self.cmbConstruct.setSizePolicy(sizePolicy)
        self.cmbConstruct.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbConstruct.setFont(font)
        self.cmbConstruct.setObjectName(_fromUtf8("cmbConstruct"))
        self.hLayoutConstruct.addWidget(self.cmbConstruct)
        self.vl_gbParameters.addWidget(self.frameConstruct)
        self.frameMOCmultipiler = QtGui.QFrame(self.gbParameters)
        self.frameMOCmultipiler.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMOCmultipiler.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMOCmultipiler.setObjectName(_fromUtf8("frameMOCmultipiler"))
        self.hLayoutMOCmultipiler = QtGui.QHBoxLayout(self.frameMOCmultipiler)
        self.hLayoutMOCmultipiler.setSpacing(0)
        self.hLayoutMOCmultipiler.setMargin(0)
        self.hLayoutMOCmultipiler.setObjectName(_fromUtf8("hLayoutMOCmultipiler"))
        self.label_84 = QtGui.QLabel(self.frameMOCmultipiler)
        self.label_84.setMinimumSize(QtCore.QSize(180, 0))
        self.label_84.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_84.setFont(font)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.hLayoutMOCmultipiler.addWidget(self.label_84)
        self.mocSpinBox = QtGui.QSpinBox(self.frameMOCmultipiler)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mocSpinBox.sizePolicy().hasHeightForWidth())
        self.mocSpinBox.setSizePolicy(sizePolicy)
        self.mocSpinBox.setMinimumSize(QtCore.QSize(72, 0))
        self.mocSpinBox.setMinimum(1)
        self.mocSpinBox.setObjectName(_fromUtf8("mocSpinBox"))
        self.hLayoutMOCmultipiler.addWidget(self.mocSpinBox)
        self.vl_gbParameters.addWidget(self.frameMOCmultipiler)
        self.chbDrawTolerance = QtGui.QCheckBox(self.gbParameters)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbDrawTolerance.setFont(font)
        self.chbDrawTolerance.setObjectName(_fromUtf8("chbDrawTolerance"))
        self.vl_gbParameters.addWidget(self.chbDrawTolerance)
        self.verticalLayout.addWidget(self.gbParameters)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.gbGeneral.setTitle(_translate("Form", "General", None))
        self.label_67.setText(_translate("Form", "RNAV Specification:", None))
        self.label_69.setText(_translate("Form", "Phase Of Flight:", None))
        self.chbCatH.setText(_translate("Form", "Cat. H", None))
        self.gbParameters.setTitle(_translate("Form", "Parameters", None))
        self.label_66.setText(_translate("Form", "Selection Mode:", None))
        self.label_77.setText(_translate("Form", "Altitude(ft):", None))
        self.txtAltitude.setText(_translate("Form", "1000", None))
        self.label_68.setText(_translate("Form", "Primary Moc(m):", None))
        self.txtPrimaryMoc.setText(_translate("Form", "300", None))
        self.label_83.setText(_translate("Form", "Construction Type:", None))
        self.label_84.setText(_translate("Form", "MOCmultiplier:", None))
        self.chbDrawTolerance.setText(_translate("Form", "Draw Waypoint Tolerance", None))

