# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EnrouteTurnOverHead.ui'
#
# Created: Thu Jul 30 10:42:44 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from FlightPlanner.Panels.ComboBoxPanel import ComboBoxPanel
from FlightPlanner.Panels.TrackRadialBoxPanel import TrackRadialBoxPanel

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EnrouteTurnOverHead(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(467, 476)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbNavAid = QtGui.QGroupBox(Form)
        self.gbNavAid.setObjectName(_fromUtf8("gbNavAid"))
        self.verticalLayoutNavAid = QtGui.QVBoxLayout(self.gbNavAid)
        self.verticalLayoutNavAid.setObjectName(_fromUtf8("verticalLayoutNavAid"))


        self.cmbNavAidType = ComboBoxPanel(self.gbNavAid)
        self.cmbNavAidType.Caption = "Type"
        self.cmbNavAidType.LabelWidth = 120
        self.verticalLayoutNavAid.addWidget(self.cmbNavAidType)

        self.cmbBasedOn = ComboBoxPanel(self.gbNavAid, True)
        self.cmbBasedOn.Caption = "Based On"
        self.cmbBasedOn.LabelWidth = 120
        self.cmbBasedOn.Width = 120
        self.verticalLayoutNavAid.addWidget(self.cmbBasedOn)
        # self.frameNavAidType = QtGui.QFrame(self.gbNavAid)
        # self.frameNavAidType.setFrameShape(QtGui.QFrame.NoFrame)
        # self.frameNavAidType.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameNavAidType.setObjectName(_fromUtf8("frameNavAidType"))
        # self.horizontalLayout_62 = QtGui.QHBoxLayout(self.frameNavAidType)
        # self.horizontalLayout_62.setSpacing(0)
        # self.horizontalLayout_62.setMargin(0)
        # self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        # self.label_70 = QtGui.QLabel(self.frameNavAidType)
        # self.label_70.setMinimumSize(QtCore.QSize(250, 0))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_70.setFont(font)
        # self.label_70.setObjectName(_fromUtf8("label_70"))
        # self.horizontalLayout_62.addWidget(self.label_70)
        # self.cmbNavAidType = QtGui.QComboBox(self.frameNavAidType)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.cmbNavAidType.sizePolicy().hasHeightForWidth())
        # self.cmbNavAidType.setSizePolicy(sizePolicy)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.cmbNavAidType.setFont(font)
        # self.cmbNavAidType.setObjectName(_fromUtf8("cmbNavAidType"))
        # self.horizontalLayout_62.addWidget(self.cmbNavAidType)
        # self.verticalLayoutNavAid.addWidget(self.frameNavAidType)
        self.verticalLayout.addWidget(self.gbNavAid)
        self.gbParameters = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.gbParameters.setFont(font)
        self.gbParameters.setObjectName(_fromUtf8("gbParameters"))
        self.vl_gbParameters = QtGui.QVBoxLayout(self.gbParameters)
        self.vl_gbParameters.setObjectName(_fromUtf8("vl_gbParameters"))
        self.frameInTrack = QtGui.QFrame(self.gbParameters)
        self.frameInTrack.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameInTrack.setFrameShadow(QtGui.QFrame.Raised)
        self.frameInTrack.setObjectName(_fromUtf8("frameInTrack"))
        self.horizontalLayout_64 = QtGui.QHBoxLayout(self.frameInTrack)
        self.horizontalLayout_64.setSpacing(0)
        self.horizontalLayout_64.setMargin(0)
        self.horizontalLayout_64.setObjectName(_fromUtf8("horizontalLayout_64"))
        self.label_72 = QtGui.QLabel(self.frameInTrack)
        self.label_72.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.horizontalLayout_64.addWidget(self.label_72)
        self.frameTrack_2 = QtGui.QFrame(self.frameInTrack)
        self.frameTrack_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameTrack_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTrack_2.setObjectName(_fromUtf8("frameTrack_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.frameTrack_2)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.txtInBound = QtGui.QLineEdit(self.frameTrack_2)
        self.txtInBound.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtInBound.setFont(font)
        self.txtInBound.setObjectName(_fromUtf8("txtInBound"))
        self.txtInBound.setMinimumSize(QtCore.QSize(90, 0))
        self.txtInBound.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_11.addWidget(self.txtInBound)
        self.btnCaptureInBound = QtGui.QToolButton(self.frameTrack_2)
        self.btnCaptureInBound.setText(_fromUtf8(""))
        self.btnCaptureInBound.setIcon(icon)
        self.btnCaptureInBound.setObjectName(_fromUtf8("btnCaptureInBound"))
        self.horizontalLayout_11.addWidget(self.btnCaptureInBound)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(horizontalSpacer)
        self.horizontalLayout_64.addWidget(self.frameTrack_2)
        self.vl_gbParameters.addWidget(self.frameInTrack)
        self.frameOutTrack = QtGui.QFrame(self.gbParameters)
        self.frameOutTrack.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameOutTrack.setFrameShadow(QtGui.QFrame.Raised)
        self.frameOutTrack.setObjectName(_fromUtf8("frameOutTrack"))
        self.horizontalLayout_65 = QtGui.QHBoxLayout(self.frameOutTrack)
        self.horizontalLayout_65.setSpacing(0)
        self.horizontalLayout_65.setMargin(0)
        self.horizontalLayout_65.setObjectName(_fromUtf8("horizontalLayout_65"))
        self.label_73 = QtGui.QLabel(self.frameOutTrack)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_73.sizePolicy().hasHeightForWidth())
        self.label_73.setSizePolicy(sizePolicy)
        self.label_73.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.horizontalLayout_65.addWidget(self.label_73)
        self.frameTrack_3 = QtGui.QFrame(self.frameOutTrack)
        self.frameTrack_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameTrack_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTrack_3.setObjectName(_fromUtf8("frameTrack_3"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.frameTrack_3)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.txtOutBound = QtGui.QLineEdit(self.frameTrack_3)
        self.txtOutBound.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtOutBound.setFont(font)
        self.txtOutBound.setObjectName(_fromUtf8("txtOutBound"))
        self.txtOutBound.setMinimumSize(QtCore.QSize(90, 0))
        self.txtOutBound.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_12.addWidget(self.txtOutBound)
        self.btnCaptureOutBound = QtGui.QToolButton(self.frameTrack_3)
        self.btnCaptureOutBound.setText(_fromUtf8(""))
        self.btnCaptureOutBound.setIcon(icon)
        self.btnCaptureOutBound.setObjectName(_fromUtf8("btnCaptureOutBound"))
        self.horizontalLayout_12.addWidget(self.btnCaptureOutBound)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(horizontalSpacer)
        self.horizontalLayout_65.addWidget(self.frameTrack_3)
        self.vl_gbParameters.addWidget(self.frameOutTrack)
        self.frameAircraftCategory = QtGui.QFrame(self.gbParameters)
        self.frameAircraftCategory.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAircraftCategory.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAircraftCategory.setObjectName(_fromUtf8("frameAircraftCategory"))
        self.horizontalLayout_61 = QtGui.QHBoxLayout(self.frameAircraftCategory)
        self.horizontalLayout_61.setSpacing(0)
        self.horizontalLayout_61.setMargin(0)
        self.horizontalLayout_61.setObjectName(_fromUtf8("horizontalLayout_61"))
        self.label_69 = QtGui.QLabel(self.frameAircraftCategory)
        self.label_69.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.horizontalLayout_61.addWidget(self.label_69)
        self.cmbAircraftCategory = QtGui.QComboBox(self.frameAircraftCategory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAircraftCategory.sizePolicy().hasHeightForWidth())
        self.cmbAircraftCategory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbAircraftCategory.setFont(font)
        self.cmbAircraftCategory.setObjectName(_fromUtf8("cmbAircraftCategory"))
        self.cmbAircraftCategory.setMinimumSize(QtCore.QSize(60, 0))
        self.cmbAircraftCategory.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_61.addWidget(self.cmbAircraftCategory)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_61.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameAircraftCategory)
        self.frameIas = QtGui.QFrame(self.gbParameters)
        self.frameIas.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameIas.setFrameShadow(QtGui.QFrame.Raised)
        self.frameIas.setObjectName(_fromUtf8("frameIas"))
        self.horizontalLayout_60 = QtGui.QHBoxLayout(self.frameIas)
        self.horizontalLayout_60.setSpacing(0)
        self.horizontalLayout_60.setMargin(0)
        self.horizontalLayout_60.setObjectName(_fromUtf8("horizontalLayout_60"))
        self.label_68 = QtGui.QLabel(self.frameIas)
        self.label_68.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_60.addWidget(self.label_68)
        self.txtIas = QtGui.QLineEdit(self.frameIas)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtIas.setFont(font)
        self.txtIas.setObjectName(_fromUtf8("txtIas"))
        self.txtIas.setMinimumSize(QtCore.QSize(60, 0))
        self.txtIas.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_60.addWidget(self.txtIas)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_60.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameIas)
        self.frameTas = QtGui.QFrame(self.gbParameters)
        self.frameTas.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameTas.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTas.setObjectName(_fromUtf8("frameTas"))
        self.horizontalLayoutTas = QtGui.QHBoxLayout(self.frameTas)
        self.horizontalLayoutTas.setSpacing(0)
        self.horizontalLayoutTas.setMargin(0)
        self.horizontalLayoutTas.setObjectName(_fromUtf8("horizontalLayoutTas"))
        self.label_76 = QtGui.QLabel(self.frameTas)
        self.label_76.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_76.setFont(font)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.horizontalLayoutTas.addWidget(self.label_76)
        self.txtTas = QtGui.QLineEdit(self.frameTas)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtTas.setFont(font)
        self.txtTas.setObjectName(_fromUtf8("txtTas"))
        self.txtTas.setMinimumSize(QtCore.QSize(90, 0))
        self.txtTas.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayoutTas.addWidget(self.txtTas)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutTas.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameTas)
        self.frameIsa = QtGui.QFrame(self.gbParameters)
        self.frameIsa.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameIsa.setFrameShadow(QtGui.QFrame.Raised)
        self.frameIsa.setObjectName(_fromUtf8("frameIsa"))
        self.horizontalLayout_72 = QtGui.QHBoxLayout(self.frameIsa)
        self.horizontalLayout_72.setSpacing(0)
        self.horizontalLayout_72.setMargin(0)
        self.horizontalLayout_72.setObjectName(_fromUtf8("horizontalLayout_72"))
        self.label_80 = QtGui.QLabel(self.frameIsa)
        self.label_80.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_80.setFont(font)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.horizontalLayout_72.addWidget(self.label_80)
        self.txtIsa = QtGui.QLineEdit(self.frameIsa)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtIsa.setFont(font)
        self.txtIsa.setObjectName(_fromUtf8("txtIsa"))
        self.txtIsa.setMinimumSize(QtCore.QSize(60, 0))
        self.txtIsa.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_72.addWidget(self.txtIsa)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_72.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameIsa)
        self.frameBankAngle = QtGui.QFrame(self.gbParameters)
        self.frameBankAngle.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameBankAngle.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBankAngle.setObjectName(_fromUtf8("frameBankAngle"))
        self.horizontalLayoutBankAngle = QtGui.QHBoxLayout(self.frameBankAngle)
        self.horizontalLayoutBankAngle.setSpacing(0)
        self.horizontalLayoutBankAngle.setMargin(0)
        self.horizontalLayoutBankAngle.setObjectName(_fromUtf8("horizontalLayoutBankAngle"))
        self.label_84 = QtGui.QLabel(self.frameBankAngle)
        self.label_84.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_84.setFont(font)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.horizontalLayoutBankAngle.addWidget(self.label_84)
        self.txtBankAngle = QtGui.QLineEdit(self.frameBankAngle)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtBankAngle.setFont(font)
        self.txtBankAngle.setObjectName(_fromUtf8("txtBankAngle"))
        self.txtBankAngle.setMinimumSize(QtCore.QSize(60, 0))
        self.txtBankAngle.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayoutBankAngle.addWidget(self.txtBankAngle)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutBankAngle.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameBankAngle)
        self.framePilotTime = QtGui.QFrame(self.gbParameters)
        self.framePilotTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePilotTime.setFrameShadow(QtGui.QFrame.Raised)
        self.framePilotTime.setObjectName(_fromUtf8("framePilotTime"))
        self.horizontalLayoutPilotTime = QtGui.QHBoxLayout(self.framePilotTime)
        self.horizontalLayoutPilotTime.setSpacing(0)
        self.horizontalLayoutPilotTime.setMargin(0)
        self.horizontalLayoutPilotTime.setObjectName(_fromUtf8("horizontalLayoutPilotTime"))
        self.label_81 = QtGui.QLabel(self.framePilotTime)
        self.label_81.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_81.setFont(font)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.horizontalLayoutPilotTime.addWidget(self.label_81)
        self.txtPilotTime = QtGui.QLineEdit(self.framePilotTime)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPilotTime.setFont(font)
        self.txtPilotTime.setObjectName(_fromUtf8("txtPilotTime"))
        self.txtPilotTime.setMinimumSize(QtCore.QSize(60, 0))
        self.txtPilotTime.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayoutPilotTime.addWidget(self.txtPilotTime)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutPilotTime.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.framePilotTime)
        self.frameBankEstTime = QtGui.QFrame(self.gbParameters)
        self.frameBankEstTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameBankEstTime.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBankEstTime.setObjectName(_fromUtf8("frameBankEstTime"))
        self.horizontalLayoutBankEstTime = QtGui.QHBoxLayout(self.frameBankEstTime)
        self.horizontalLayoutBankEstTime.setSpacing(0)
        self.horizontalLayoutBankEstTime.setMargin(0)
        self.horizontalLayoutBankEstTime.setObjectName(_fromUtf8("horizontalLayoutBankEstTime"))
        self.label_87 = QtGui.QLabel(self.frameBankEstTime)
        self.label_87.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_87.setFont(font)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.horizontalLayoutBankEstTime.addWidget(self.label_87)
        self.txtBankEstTime = QtGui.QLineEdit(self.frameBankEstTime)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtBankEstTime.setFont(font)
        self.txtBankEstTime.setObjectName(_fromUtf8("txtBankEstTime"))
        self.txtBankEstTime.setMinimumSize(QtCore.QSize(60, 0))
        self.txtBankEstTime.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayoutBankEstTime.addWidget(self.txtBankEstTime)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutBankEstTime.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameBankEstTime)
        self.framePrimaryMoc = QtGui.QFrame(self.gbParameters)
        self.framePrimaryMoc.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePrimaryMoc.setFrameShadow(QtGui.QFrame.Raised)
        self.framePrimaryMoc.setObjectName(_fromUtf8("framePrimaryMoc"))
        self.horizontalLayoutPrimaryMoc = QtGui.QHBoxLayout(self.framePrimaryMoc)
        self.horizontalLayoutPrimaryMoc.setSpacing(0)
        self.horizontalLayoutPrimaryMoc.setMargin(0)
        self.horizontalLayoutPrimaryMoc.setObjectName(_fromUtf8("horizontalLayoutPrimaryMoc"))
        self.label_82 = QtGui.QLabel(self.framePrimaryMoc)
        self.label_82.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_82.setFont(font)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.horizontalLayoutPrimaryMoc.addWidget(self.label_82)
        self.txtPrimaryMoc = QtGui.QLineEdit(self.framePrimaryMoc)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPrimaryMoc.setFont(font)
        self.txtPrimaryMoc.setObjectName(_fromUtf8("txtPrimaryMoc"))
        self.txtPrimaryMoc.setMinimumSize(QtCore.QSize(60, 0))
        self.txtPrimaryMoc.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayoutPrimaryMoc.addWidget(self.txtPrimaryMoc)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutPrimaryMoc.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.framePrimaryMoc)
        self.frameEnrouteAltitude = QtGui.QFrame(self.gbParameters)
        self.frameEnrouteAltitude.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameEnrouteAltitude.setFrameShadow(QtGui.QFrame.Raised)
        self.frameEnrouteAltitude.setObjectName(_fromUtf8("frameEnrouteAltitude"))
        self.horizontalLayoutEnrouteAltitude = QtGui.QHBoxLayout(self.frameEnrouteAltitude)
        self.horizontalLayoutEnrouteAltitude.setSpacing(0)
        self.horizontalLayoutEnrouteAltitude.setMargin(0)
        self.horizontalLayoutEnrouteAltitude.setObjectName(_fromUtf8("horizontalLayoutEnrouteAltitude"))
        self.label_88 = QtGui.QLabel(self.frameEnrouteAltitude)
        self.label_88.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_88.setFont(font)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.horizontalLayoutEnrouteAltitude.addWidget(self.label_88)
        self.txtEnrouteAltitude = QtGui.QLineEdit(self.frameEnrouteAltitude)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtEnrouteAltitude.setFont(font)
        self.txtEnrouteAltitude.setObjectName(_fromUtf8("txtEnrouteAltitude"))
        self.txtEnrouteAltitude.setMinimumSize(QtCore.QSize(60, 0))
        self.txtEnrouteAltitude.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayoutEnrouteAltitude.addWidget(self.txtEnrouteAltitude)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutEnrouteAltitude.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameEnrouteAltitude)
        self.frameConstruction = QtGui.QFrame(self.gbParameters)
        self.frameConstruction.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameConstruction.setFrameShadow(QtGui.QFrame.Raised)
        self.frameConstruction.setObjectName(_fromUtf8("frameConstruction"))
        self.horizontalLayout_75 = QtGui.QHBoxLayout(self.frameConstruction)
        self.horizontalLayout_75.setSpacing(0)
        self.horizontalLayout_75.setMargin(0)
        self.horizontalLayout_75.setObjectName(_fromUtf8("horizontalLayout_75"))
        self.label_83 = QtGui.QLabel(self.frameConstruction)
        self.label_83.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_83.setFont(font)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.horizontalLayout_75.addWidget(self.label_83)
        self.cmbConstruction = QtGui.QComboBox(self.frameConstruction)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConstruction.sizePolicy().hasHeightForWidth())
        self.cmbConstruction.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbConstruction.setFont(font)
        self.cmbConstruction.setObjectName(_fromUtf8("cmbConstruction"))
        self.cmbConstruction.setMinimumSize(QtCore.QSize(60, 0))
        self.cmbConstruction.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_75.addWidget(self.cmbConstruction)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_75.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameConstruction)
        self.frameMOCmultipiler = QtGui.QFrame(self.gbParameters)
        self.frameMOCmultipiler.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMOCmultipiler.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMOCmultipiler.setObjectName(_fromUtf8("frameMOCmultipiler"))
        self.horizontalLayoutMOCmultipiler = QtGui.QHBoxLayout(self.frameMOCmultipiler)
        self.horizontalLayoutMOCmultipiler.setSpacing(0)
        self.horizontalLayoutMOCmultipiler.setMargin(0)
        self.horizontalLayoutMOCmultipiler.setObjectName(_fromUtf8("horizontalLayoutMOCmultipiler"))
        self.label_85 = QtGui.QLabel(self.frameMOCmultipiler)
        self.label_85.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_85.setFont(font)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.horizontalLayoutMOCmultipiler.addWidget(self.label_85)
        self.mocSpinBox = QtGui.QSpinBox(self.frameMOCmultipiler)
        self.mocSpinBox.setMinimum(1)
        self.mocSpinBox.setProperty("value", 1)
        self.mocSpinBox.setObjectName(_fromUtf8("mocSpinBox"))
        self.mocSpinBox.setMinimumSize(QtCore.QSize(60, 0))
        self.mocSpinBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayoutMOCmultipiler.addWidget(self.mocSpinBox)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutMOCmultipiler.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameMOCmultipiler)
        self.chbOverhead = QtGui.QCheckBox(self.gbParameters)
        self.chbOverhead.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbOverhead.setFont(font)
        self.chbOverhead.setObjectName(_fromUtf8("chbOverhead"))
        self.vl_gbParameters.addWidget(self.chbOverhead)
        self.verticalLayout.addWidget(self.gbParameters)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.gbNavAid.setTitle(_translate("Form", "Navigational Aid", None))
        # self.label_70.setText(_translate("Form", "Type:", None))
        self.gbParameters.setTitle(_translate("Form", "Parameters", None))
        self.label_72.setText(_translate("Form", "In-bound Track ():", None))
        self.txtInBound.setText(_translate("Form", "0", None))
        self.label_73.setText(_translate("Form", "Out-bound Track ():", None))
        self.txtOutBound.setText(_translate("Form", "0", None))
        self.label_69.setText(_translate("Form", "Aircraft Category:", None))
        self.label_68.setText(_translate("Form", "IAS (kts):", None))
        self.txtIas.setText(_translate("Form", "315", None))
        self.label_76.setText(_translate("Form", "TAS (kts):", None))
        self.txtTas.setText(_translate("Form", "250", None))
        self.label_80.setText(_translate("Form", "ISA (C):", None))
        self.txtIsa.setText(_translate("Form", "15", None))
        self.label_84.setText(_translate("Form", "Bank Angle ():", None))
        self.txtBankAngle.setText(_translate("Form", "15", None))
        self.label_81.setText(_translate("Form", "Pilot Reaction Time (sec):", None))
        self.txtPilotTime.setText(_translate("Form", "10", None))
        self.label_87.setText(_translate("Form", "Bank Establishment Time (sec):", None))
        self.txtBankEstTime.setText(_translate("Form", "5", None))
        self.label_82.setText(_translate("Form", "Primary Moc (m):", None))
        self.txtPrimaryMoc.setText(_translate("Form", "300", None))
        self.label_88.setText(_translate("Form", "Enroute Altitude(ft):", None))
        self.txtEnrouteAltitude.setText(_translate("Form", "10000", None))
        self.label_83.setText(_translate("Form", "Construction Type:", None))
        self.label_85.setText(_translate("Form", "MOCmultipiler:", None))
        self.chbOverhead.setText(_translate("Form", "4nm overhead the VOR", None))

