# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FixConstruction.ui'
#
# Created: Thu Jan 28 10:33:00 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FixConstruction(object):
    def setupUi(self, FixConstruction):
        FixConstruction.setObjectName(_fromUtf8("FixConstruction"))
        FixConstruction.resize(346, 298)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        FixConstruction.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(FixConstruction)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbTrackingAid = QtGui.QGroupBox(FixConstruction)
        self.gbTrackingAid.setObjectName(_fromUtf8("gbTrackingAid"))
        self.vl_gbTrackingAid = QtGui.QVBoxLayout(self.gbTrackingAid)
        self.vl_gbTrackingAid.setObjectName(_fromUtf8("vl_gbTrackingAid"))
        self.frameTrackingType = QtGui.QFrame(self.gbTrackingAid)
        self.frameTrackingType.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameTrackingType.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTrackingType.setObjectName(_fromUtf8("frameTrackingType"))
        self.horizontalLayout_59 = QtGui.QHBoxLayout(self.frameTrackingType)
        self.horizontalLayout_59.setSpacing(0)
        self.horizontalLayout_59.setMargin(0)
        self.horizontalLayout_59.setObjectName(_fromUtf8("horizontalLayout_59"))
        self.label_67 = QtGui.QLabel(self.frameTrackingType)
        self.label_67.setMinimumSize(QtCore.QSize(150, 0))
        self.label_67.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.horizontalLayout_59.addWidget(self.label_67)
        self.cmbTrackingType = QtGui.QComboBox(self.frameTrackingType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTrackingType.sizePolicy().hasHeightForWidth())
        self.cmbTrackingType.setSizePolicy(sizePolicy)
        self.cmbTrackingType.setMinimumSize(QtCore.QSize(79, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbTrackingType.setFont(font)
        self.cmbTrackingType.setObjectName(_fromUtf8("cmbTrackingType"))
        self.horizontalLayout_59.addWidget(self.cmbTrackingType)
        self.vl_gbTrackingAid.addWidget(self.frameTrackingType)
        self.frameTrackingRadialTrack = QtGui.QFrame(self.gbTrackingAid)
        self.frameTrackingRadialTrack.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameTrackingRadialTrack.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTrackingRadialTrack.setObjectName(_fromUtf8("frameTrackingRadialTrack"))
        self.horizontalLayout_Radial1 = QtGui.QHBoxLayout(self.frameTrackingRadialTrack)
        self.horizontalLayout_Radial1.setSpacing(0)
        self.horizontalLayout_Radial1.setMargin(0)
        self.horizontalLayout_Radial1.setObjectName(_fromUtf8("horizontalLayout_Radial1"))
        self.label_TrackingRadial = QtGui.QLabel(self.frameTrackingRadialTrack)
        self.label_TrackingRadial.setMinimumSize(QtCore.QSize(150, 0))
        self.label_TrackingRadial.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_TrackingRadial.setFont(font)
        self.label_TrackingRadial.setObjectName(_fromUtf8("label_TrackingRadial"))
        self.horizontalLayout_Radial1.addWidget(self.label_TrackingRadial)
        self.frameTrack_2 = QtGui.QFrame(self.frameTrackingRadialTrack)
        self.frameTrack_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameTrack_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTrack_2.setObjectName(_fromUtf8("frameTrack_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.frameTrack_2)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.txtTrackingRadialTrack = QtGui.QLineEdit(self.frameTrack_2)
        self.txtTrackingRadialTrack.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtTrackingRadialTrack.sizePolicy().hasHeightForWidth())
        self.txtTrackingRadialTrack.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtTrackingRadialTrack.setFont(font)
        self.txtTrackingRadialTrack.setObjectName(_fromUtf8("txtTrackingRadialTrack"))
        self.horizontalLayout_11.addWidget(self.txtTrackingRadialTrack)
        self.btnCaptureTrackingRadialTrack = QtGui.QToolButton(self.frameTrack_2)
        self.btnCaptureTrackingRadialTrack.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCaptureTrackingRadialTrack.setIcon(icon)
        self.btnCaptureTrackingRadialTrack.setObjectName(_fromUtf8("btnCaptureTrackingRadialTrack"))
        self.horizontalLayout_11.addWidget(self.btnCaptureTrackingRadialTrack)
        self.horizontalLayout_Radial1.addWidget(self.frameTrack_2)
        self.vl_gbTrackingAid.addWidget(self.frameTrackingRadialTrack)
        self.verticalLayout.addWidget(self.gbTrackingAid)
        self.gbIntersectingAid = QtGui.QGroupBox(FixConstruction)
        self.gbIntersectingAid.setObjectName(_fromUtf8("gbIntersectingAid"))
        self.vl_gbIntersectingAid = QtGui.QVBoxLayout(self.gbIntersectingAid)
        self.vl_gbIntersectingAid.setObjectName(_fromUtf8("vl_gbIntersectingAid"))
        self.frameIntersectingType = QtGui.QFrame(self.gbIntersectingAid)
        self.frameIntersectingType.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameIntersectingType.setFrameShadow(QtGui.QFrame.Raised)
        self.frameIntersectingType.setObjectName(_fromUtf8("frameIntersectingType"))
        self.horizontalLayout_60 = QtGui.QHBoxLayout(self.frameIntersectingType)
        self.horizontalLayout_60.setSpacing(0)
        self.horizontalLayout_60.setMargin(0)
        self.horizontalLayout_60.setObjectName(_fromUtf8("horizontalLayout_60"))
        self.label_68 = QtGui.QLabel(self.frameIntersectingType)
        self.label_68.setMinimumSize(QtCore.QSize(150, 0))
        self.label_68.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_60.addWidget(self.label_68)
        self.cmbIntersectingType = QtGui.QComboBox(self.frameIntersectingType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbIntersectingType.sizePolicy().hasHeightForWidth())
        self.cmbIntersectingType.setSizePolicy(sizePolicy)
        self.cmbIntersectingType.setMinimumSize(QtCore.QSize(79, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbIntersectingType.setFont(font)
        self.cmbIntersectingType.setObjectName(_fromUtf8("cmbIntersectingType"))
        self.horizontalLayout_60.addWidget(self.cmbIntersectingType)
        self.vl_gbIntersectingAid.addWidget(self.frameIntersectingType)
        self.frameTrackRoot = QtGui.QFrame(self.gbIntersectingAid)
        self.frameTrackRoot.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameTrackRoot.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTrackRoot.setObjectName(_fromUtf8("frameTrackRoot"))
        self.horizontalLayout_63 = QtGui.QHBoxLayout(self.frameTrackRoot)
        self.horizontalLayout_63.setSpacing(0)
        self.horizontalLayout_63.setMargin(0)
        self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        self.label_IntersectingRadial = QtGui.QLabel(self.frameTrackRoot)
        self.label_IntersectingRadial.setMinimumSize(QtCore.QSize(150, 0))
        self.label_IntersectingRadial.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_IntersectingRadial.setFont(font)
        self.label_IntersectingRadial.setObjectName(_fromUtf8("label_IntersectingRadial"))
        self.horizontalLayout_63.addWidget(self.label_IntersectingRadial)
        self.frameIntersectingRadialTrack = QtGui.QFrame(self.frameTrackRoot)
        self.frameIntersectingRadialTrack.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameIntersectingRadialTrack.setFrameShadow(QtGui.QFrame.Raised)
        self.frameIntersectingRadialTrack.setObjectName(_fromUtf8("frameIntersectingRadialTrack"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frameIntersectingRadialTrack)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.txtIntersectingRadialTrack = QtGui.QLineEdit(self.frameIntersectingRadialTrack)
        self.txtIntersectingRadialTrack.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtIntersectingRadialTrack.sizePolicy().hasHeightForWidth())
        self.txtIntersectingRadialTrack.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtIntersectingRadialTrack.setFont(font)
        self.txtIntersectingRadialTrack.setObjectName(_fromUtf8("txtIntersectingRadialTrack"))
        self.horizontalLayout_10.addWidget(self.txtIntersectingRadialTrack)
        self.btnCaptureIntersectingRadialTrack = QtGui.QToolButton(self.frameIntersectingRadialTrack)
        self.btnCaptureIntersectingRadialTrack.setText(_fromUtf8(""))
        self.btnCaptureIntersectingRadialTrack.setIcon(icon)
        self.btnCaptureIntersectingRadialTrack.setObjectName(_fromUtf8("btnCaptureIntersectingRadialTrack"))
        self.horizontalLayout_10.addWidget(self.btnCaptureIntersectingRadialTrack)
        self.horizontalLayout_63.addWidget(self.frameIntersectingRadialTrack)
        self.vl_gbIntersectingAid.addWidget(self.frameTrackRoot)
        self.frame_IntersectingDistance = QtGui.QFrame(self.gbIntersectingAid)
        self.frame_IntersectingDistance.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_IntersectingDistance.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_IntersectingDistance.setObjectName(_fromUtf8("frame_IntersectingDistance"))
        self.horizontalLayout_65 = QtGui.QHBoxLayout(self.frame_IntersectingDistance)
        self.horizontalLayout_65.setSpacing(0)
        self.horizontalLayout_65.setMargin(0)
        self.horizontalLayout_65.setObjectName(_fromUtf8("horizontalLayout_65"))
        self.label_74 = QtGui.QLabel(self.frame_IntersectingDistance)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_74.sizePolicy().hasHeightForWidth())
        self.label_74.setSizePolicy(sizePolicy)
        self.label_74.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_65.addWidget(self.label_74)
        self.frame_APV_9 = QtGui.QFrame(self.frame_IntersectingDistance)
        self.frame_APV_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_9.setObjectName(_fromUtf8("frame_APV_9"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.frame_APV_9)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.txtIntersectingDistance = QtGui.QLineEdit(self.frame_APV_9)
        self.txtIntersectingDistance.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtIntersectingDistance.setFont(font)
        self.txtIntersectingDistance.setObjectName(_fromUtf8("txtIntersectingDistance"))
        self.horizontalLayout_13.addWidget(self.txtIntersectingDistance)
        self.btnMeasureIntersectingDistance = QtGui.QToolButton(self.frame_APV_9)
        self.btnMeasureIntersectingDistance.setText(_fromUtf8(""))
        self.btnMeasureIntersectingDistance.setIcon(icon)
        self.btnMeasureIntersectingDistance.setObjectName(_fromUtf8("btnMeasureIntersectingDistance"))
        self.horizontalLayout_13.addWidget(self.btnMeasureIntersectingDistance)
        self.horizontalLayout_65.addWidget(self.frame_APV_9)
        self.vl_gbIntersectingAid.addWidget(self.frame_IntersectingDistance)
        self.pnl0dmeAtThr = QtGui.QFrame(self.gbIntersectingAid)
        self.pnl0dmeAtThr.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnl0dmeAtThr.setFrameShadow(QtGui.QFrame.Raised)
        self.pnl0dmeAtThr.setObjectName(_fromUtf8("pnl0dmeAtThr"))
        self.vl_pnl0dmeAtThr = QtGui.QVBoxLayout(self.pnl0dmeAtThr)
        self.vl_pnl0dmeAtThr.setSpacing(0)
        self.vl_pnl0dmeAtThr.setMargin(0)
        self.vl_pnl0dmeAtThr.setObjectName(_fromUtf8("vl_pnl0dmeAtThr"))
        self.chb0dmeAtThr = QtGui.QCheckBox(self.pnl0dmeAtThr)
        self.chb0dmeAtThr.setObjectName(_fromUtf8("chb0dmeAtThr"))
        self.vl_pnl0dmeAtThr.addWidget(self.chb0dmeAtThr)
        self.frame_DmeOffset = QtGui.QFrame(self.pnl0dmeAtThr)
        self.frame_DmeOffset.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_DmeOffset.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_DmeOffset.setObjectName(_fromUtf8("frame_DmeOffset"))
        self.horizontalLayout_64 = QtGui.QHBoxLayout(self.frame_DmeOffset)
        self.horizontalLayout_64.setSpacing(0)
        self.horizontalLayout_64.setMargin(0)
        self.horizontalLayout_64.setObjectName(_fromUtf8("horizontalLayout_64"))
        self.label_73 = QtGui.QLabel(self.frame_DmeOffset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_73.sizePolicy().hasHeightForWidth())
        self.label_73.setSizePolicy(sizePolicy)
        self.label_73.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.horizontalLayout_64.addWidget(self.label_73)
        self.frame_APV_8 = QtGui.QFrame(self.frame_DmeOffset)
        self.frame_APV_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_8.setObjectName(_fromUtf8("frame_APV_8"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.frame_APV_8)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.txtDmeOffset = QtGui.QLineEdit(self.frame_APV_8)
        self.txtDmeOffset.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtDmeOffset.setFont(font)
        self.txtDmeOffset.setObjectName(_fromUtf8("txtDmeOffset"))
        self.horizontalLayout_12.addWidget(self.txtDmeOffset)
        self.btnMeasureDmeOffset = QtGui.QToolButton(self.frame_APV_8)
        self.btnMeasureDmeOffset.setText(_fromUtf8(""))
        self.btnMeasureDmeOffset.setIcon(icon)
        self.btnMeasureDmeOffset.setObjectName(_fromUtf8("btnMeasureDmeOffset"))
        self.horizontalLayout_12.addWidget(self.btnMeasureDmeOffset)
        self.horizontalLayout_64.addWidget(self.frame_APV_8)
        self.vl_pnl0dmeAtThr.addWidget(self.frame_DmeOffset)
        self.vl_gbIntersectingAid.addWidget(self.pnl0dmeAtThr)
        self.frameMOCMultipiler = QtGui.QFrame(self.gbIntersectingAid)
        self.frameMOCMultipiler.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMOCMultipiler.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMOCMultipiler.setObjectName(_fromUtf8("frameMOCMultipiler"))
        self.horizontalLayout_62 = QtGui.QHBoxLayout(self.frameMOCMultipiler)
        self.horizontalLayout_62.setSpacing(0)
        self.horizontalLayout_62.setMargin(0)
        self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        self.label_70 = QtGui.QLabel(self.frameMOCMultipiler)
        self.label_70.setMinimumSize(QtCore.QSize(150, 0))
        self.label_70.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.horizontalLayout_62.addWidget(self.label_70)
        self.spinBoxMocmulipiler = QtGui.QSpinBox(self.frameMOCMultipiler)
        self.spinBoxMocmulipiler.setProperty("value", 1)
        self.spinBoxMocmulipiler.setObjectName(_fromUtf8("spinBoxMocmulipiler"))
        self.horizontalLayout_62.addWidget(self.spinBoxMocmulipiler)
        self.vl_gbIntersectingAid.addWidget(self.frameMOCMultipiler)
        self.verticalLayout.addWidget(self.gbIntersectingAid)

        self.retranslateUi(FixConstruction)
        QtCore.QMetaObject.connectSlotsByName(FixConstruction)

    def retranslateUi(self, FixConstruction):
        FixConstruction.setWindowTitle(_translate("FixConstruction", "Form", None))
        self.gbTrackingAid.setTitle(_translate("FixConstruction", "Tracking Aid", None))
        self.label_67.setText(_translate("FixConstruction", "Type:", None))
        self.label_TrackingRadial.setText(_translate("FixConstruction", "Radial(°):", None))
        self.txtTrackingRadialTrack.setText(_translate("FixConstruction", "0", None))
        self.gbIntersectingAid.setTitle(_translate("FixConstruction", "Intersecting Aid", None))
        self.label_68.setText(_translate("FixConstruction", "Type:", None))
        self.label_IntersectingRadial.setText(_translate("FixConstruction", "Radial(°):", None))
        self.txtIntersectingRadialTrack.setText(_translate("FixConstruction", "180", None))
        self.label_74.setText(_translate("FixConstruction", "DME Distance (nm):", None))
        self.txtIntersectingDistance.setText(_translate("FixConstruction", "5", None))
        self.chb0dmeAtThr.setText(_translate("FixConstruction", "0 DME at THR", None))
        self.label_73.setText(_translate("FixConstruction", "DME to THR Distance (m):", None))
        self.txtDmeOffset.setText(_translate("FixConstruction", "5", None))
        self.label_70.setText(_translate("FixConstruction", "MOCmultipiler:", None))

