# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CaculaterDlgSimple.ui'
#
# Created: Mon Feb 23 10:35:24 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class CalcSimpleDlg(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(317, 182)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lbl1 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        self.lbl1.setFont(font)
        self.lbl1.setText(_fromUtf8(""))
        self.lbl1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl1.setWordWrap(False)
        self.lbl1.setMargin(0)
        self.lbl1.setObjectName(_fromUtf8("lbl1"))
        self.verticalLayout_2.addWidget(self.lbl1)
        self.lbl2 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
#         font.setWeight(75)
        self.lbl2.setFont(font)
        self.lbl2.setText(_fromUtf8(""))
        self.lbl2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl2.setObjectName(_fromUtf8("lbl2"))
        self.verticalLayout_2.addWidget(self.lbl2)
        self.frame_26 = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_26.sizePolicy().hasHeightForWidth())
        self.frame_26.setSizePolicy(sizePolicy)
        self.frame_26.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_26.setObjectName(_fromUtf8("frame_26"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.frame_26)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setMargin(0)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_13 = QtGui.QLabel(self.frame_26)
        self.label_13.setMinimumSize(QtCore.QSize(150, 0))
        self.label_13.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_25.addWidget(self.label_13)
        self.txtForm = QtGui.QLineEdit(self.frame_26)
        self.txtForm.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtForm.sizePolicy().hasHeightForWidth())
        self.txtForm.setSizePolicy(sizePolicy)
        self.txtForm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        self.txtForm.setFont(font)
        self.txtForm.setObjectName(_fromUtf8("txtForm"))
        self.horizontalLayout_25.addWidget(self.txtForm)
        self.verticalLayout_2.addWidget(self.frame_26)
        self.frame_27 = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_27.sizePolicy().hasHeightForWidth())
        self.frame_27.setSizePolicy(sizePolicy)
        self.frame_27.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_27.setObjectName(_fromUtf8("frame_27"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.frame_27)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setMargin(0)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_14 = QtGui.QLabel(self.frame_27)
        self.label_14.setMinimumSize(QtCore.QSize(150, 0))
        self.label_14.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_26.addWidget(self.label_14)
        self.txtBearing = QtGui.QLineEdit(self.frame_27)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtBearing.sizePolicy().hasHeightForWidth())
        self.txtBearing.setSizePolicy(sizePolicy)
        self.txtBearing.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        self.txtBearing.setFont(font)
        self.txtBearing.setObjectName(_fromUtf8("txtBearing"))
        self.horizontalLayout_26.addWidget(self.txtBearing)
        self.btnCaptureBearing = QtGui.QToolButton(self.frame_27)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCaptureBearing.sizePolicy().hasHeightForWidth())
        self.btnCaptureBearing.setSizePolicy(sizePolicy)
        self.btnCaptureBearing.setMaximumSize(QtCore.QSize(16777215, 23))
        self.btnCaptureBearing.setStyleSheet(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCaptureBearing.setIcon(icon)
        self.btnCaptureBearing.setObjectName(_fromUtf8("btnCaptureBearing"))
        self.horizontalLayout_26.addWidget(self.btnCaptureBearing)
        self.verticalLayout_2.addWidget(self.frame_27)
        self.frame_28 = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_28.sizePolicy().hasHeightForWidth())
        self.frame_28.setSizePolicy(sizePolicy)
        self.frame_28.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_28.setObjectName(_fromUtf8("frame_28"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.frame_28)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setMargin(0)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.lblDistance = QtGui.QLabel(self.frame_28)
        self.lblDistance.setMinimumSize(QtCore.QSize(150, 0))
        self.lblDistance.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.lblDistance.setFont(font)
        self.lblDistance.setObjectName(_fromUtf8("lblDistance"))
        self.horizontalLayout_27.addWidget(self.lblDistance)
        self.txtDistance = QtGui.QLineEdit(self.frame_28)
#         self.txtDistance.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDistance.sizePolicy().hasHeightForWidth())
        self.txtDistance.setSizePolicy(sizePolicy)
        self.txtDistance.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        self.txtDistance.setFont(font)
        self.txtDistance.setObjectName(_fromUtf8("txtDistance"))
        self.horizontalLayout_27.addWidget(self.txtDistance)
        self.btnCaptureDistance = QtGui.QToolButton(self.frame_28)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCaptureDistance.sizePolicy().hasHeightForWidth())
        self.btnCaptureDistance.setSizePolicy(sizePolicy)
        self.btnCaptureDistance.setMaximumSize(QtCore.QSize(16777215, 23))
        self.btnCaptureDistance.setStyleSheet(_fromUtf8(""))
        self.btnCaptureDistance.setIcon(icon)
        self.btnCaptureDistance.setObjectName(_fromUtf8("btnCaptureDistance"))
        self.horizontalLayout_27.addWidget(self.btnCaptureDistance)
        self.verticalLayout_2.addWidget(self.frame_28)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
#         QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_13.setText(_translate("Dialog", "Form:", None))
        self.txtForm.setText(_translate("Dialog", "FAWP", None))
        self.label_14.setText(_translate("Dialog", "Bearing :", None))
        self.txtBearing.setText(_translate("Dialog", "188.25", None))
        self.btnCaptureBearing.setText(_translate("Dialog", "...", None))
        self.lblDistance.setText(_translate("Dialog", "Distance  (nm):", None))
        self.txtDistance.setText(_translate("Dialog", "Abeam THR", None))
        self.btnCaptureDistance.setText(_translate("Dialog", "...", None))

# import Resources_rc
