# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FixToleranceArea.ui'
#
# Created: Fri Jan 29 09:59:51 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from FlightPlanner.Panels.TrackRadialBoxPanel import TrackRadialBoxPanel

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FixToleranceArea(object):
    def setupUi(self, FixToleranceArea):
        FixToleranceArea.setObjectName(_fromUtf8("FixToleranceArea"))
        FixToleranceArea.resize(464, 314)
        self.horizontalLayout = QtGui.QHBoxLayout(FixToleranceArea)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabCtrlGeneral = QtGui.QTabWidget(FixToleranceArea)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.tabCtrlGeneral.setFont(font)
        self.tabCtrlGeneral.setAutoFillBackground(False)
        self.tabCtrlGeneral.setStyleSheet(_fromUtf8(""))
        self.tabCtrlGeneral.setObjectName(_fromUtf8("tabCtrlGeneral"))
        self.tab_Results = QtGui.QWidget(FixToleranceArea)
        self.tab_Results.setObjectName(_fromUtf8("tab_Results"))
        self.hlResults = QtGui.QHBoxLayout(self.tab_Results)
        self.hlResults.setSpacing(3)
        self.hlResults.setMargin(3)
        self.hlResults.setObjectName(_fromUtf8("hlResults"))
        self.grbResult = QtGui.QGroupBox(self.tab_Results)
        self.grbResult.setTitle(_fromUtf8(""))
        self.grbResult.setObjectName(_fromUtf8("grbResult"))
        self.vlResultGroup = QtGui.QVBoxLayout(self.grbResult)
        self.vlResultGroup.setMargin(3)
        self.vlResultGroup.setObjectName(_fromUtf8("vlResultGroup"))
        self.gbTrackingAid = QtGui.QGroupBox(self.grbResult)
        self.gbTrackingAid.setObjectName(_fromUtf8("gbTrackingAid"))
        self.vl_gbTrackingAid = QtGui.QVBoxLayout(self.gbTrackingAid)
        self.vl_gbTrackingAid.setObjectName(_fromUtf8("vl_gbTrackingAid"))
        self.frameTrackingType = QtGui.QFrame(self.gbTrackingAid)
        self.frameTrackingType.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameTrackingType.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTrackingType.setObjectName(_fromUtf8("frameTrackingType"))
        self.horizontalLayout_59 = QtGui.QHBoxLayout(self.frameTrackingType)
        self.horizontalLayout_59.setSpacing(0)
        self.horizontalLayout_59.setMargin(0)
        self.horizontalLayout_59.setObjectName(_fromUtf8("horizontalLayout_59"))
        self.label_67 = QtGui.QLabel(self.frameTrackingType)
        self.label_67.setMinimumSize(QtCore.QSize(150, 0))
        self.label_67.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.horizontalLayout_59.addWidget(self.label_67)
        self.cmbTrackingType = QtGui.QComboBox(self.frameTrackingType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTrackingType.sizePolicy().hasHeightForWidth())
        self.cmbTrackingType.setSizePolicy(sizePolicy)
        self.cmbTrackingType.setMinimumSize(QtCore.QSize(79, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbTrackingType.setFont(font)
        self.cmbTrackingType.setObjectName(_fromUtf8("cmbTrackingType"))
        self.horizontalLayout_59.addWidget(self.cmbTrackingType)
        self.vl_gbTrackingAid.addWidget(self.frameTrackingType)

        self.txtTrackingRadialTrack = TrackRadialBoxPanel(self.gbTrackingAid)
        self.txtTrackingRadialTrack.Caption = "Radial"
        self.vl_gbTrackingAid.addWidget(self.txtTrackingRadialTrack)
        # self.frameTrackingRadialTrack = QtGui.QFrame(self.gbTrackingAid)
        # self.frameTrackingRadialTrack.setFrameShape(QtGui.QFrame.NoFrame)
        # self.frameTrackingRadialTrack.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameTrackingRadialTrack.setObjectName(_fromUtf8("frameTrackingRadialTrack"))
        # self.horizontalLayout_Radial1 = QtGui.QHBoxLayout(self.frameTrackingRadialTrack)
        # self.horizontalLayout_Radial1.setSpacing(0)
        # self.horizontalLayout_Radial1.setMargin(0)
        # self.horizontalLayout_Radial1.setObjectName(_fromUtf8("horizontalLayout_Radial1"))
        # self.label_TrackingRadial = QtGui.QLabel(self.frameTrackingRadialTrack)
        # self.label_TrackingRadial.setMinimumSize(QtCore.QSize(150, 0))
        # self.label_TrackingRadial.setMaximumSize(QtCore.QSize(150, 16777215))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_TrackingRadial.setFont(font)
        # self.label_TrackingRadial.setObjectName(_fromUtf8("label_TrackingRadial"))
        # self.horizontalLayout_Radial1.addWidget(self.label_TrackingRadial)
        # self.frameTrack_2 = QtGui.QFrame(self.frameTrackingRadialTrack)
        # self.frameTrack_2.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frameTrack_2.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameTrack_2.setObjectName(_fromUtf8("frameTrack_2"))
        # self.horizontalLayout_11 = QtGui.QHBoxLayout(self.frameTrack_2)
        # self.horizontalLayout_11.setSpacing(0)
        # self.horizontalLayout_11.setMargin(0)
        # self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        # self.txtTrackingRadialTrack = QtGui.QLineEdit(self.frameTrack_2)
        # self.txtTrackingRadialTrack.setEnabled(True)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.txtTrackingRadialTrack.sizePolicy().hasHeightForWidth())
        # self.txtTrackingRadialTrack.setSizePolicy(sizePolicy)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.txtTrackingRadialTrack.setFont(font)
        # self.txtTrackingRadialTrack.setObjectName(_fromUtf8("txtTrackingRadialTrack"))
        # self.horizontalLayout_11.addWidget(self.txtTrackingRadialTrack)
        # self.btnCaptureTrackingRadialTrack = QtGui.QToolButton(self.frameTrack_2)
        # self.btnCaptureTrackingRadialTrack.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.btnCaptureTrackingRadialTrack.setIcon(icon)
        # self.btnCaptureTrackingRadialTrack.setObjectName(_fromUtf8("btnCaptureTrackingRadialTrack"))
        # self.horizontalLayout_11.addWidget(self.btnCaptureTrackingRadialTrack)
        # self.horizontalLayout_Radial1.addWidget(self.frameTrack_2)
        # self.vl_gbTrackingAid.addWidget(self.frameTrackingRadialTrack)
        self.vlResultGroup.addWidget(self.gbTrackingAid)
        self.gbIntersectingAid = QtGui.QGroupBox(self.grbResult)
        self.gbIntersectingAid.setObjectName(_fromUtf8("gbIntersectingAid"))
        self.vl_gbIntersectingAid = QtGui.QVBoxLayout(self.gbIntersectingAid)
        self.vl_gbIntersectingAid.setObjectName(_fromUtf8("vl_gbIntersectingAid"))
        self.frameIntersectingType = QtGui.QFrame(self.gbIntersectingAid)
        self.frameIntersectingType.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameIntersectingType.setFrameShadow(QtGui.QFrame.Raised)
        self.frameIntersectingType.setObjectName(_fromUtf8("frameIntersectingType"))
        self.horizontalLayout_60 = QtGui.QHBoxLayout(self.frameIntersectingType)
        self.horizontalLayout_60.setSpacing(0)
        self.horizontalLayout_60.setMargin(0)
        self.horizontalLayout_60.setObjectName(_fromUtf8("horizontalLayout_60"))
        self.label_68 = QtGui.QLabel(self.frameIntersectingType)
        self.label_68.setMinimumSize(QtCore.QSize(150, 0))
        self.label_68.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_60.addWidget(self.label_68)
        self.cmbIntersectingType = QtGui.QComboBox(self.frameIntersectingType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbIntersectingType.sizePolicy().hasHeightForWidth())
        self.cmbIntersectingType.setSizePolicy(sizePolicy)
        self.cmbIntersectingType.setMinimumSize(QtCore.QSize(79, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbIntersectingType.setFont(font)
        self.cmbIntersectingType.setObjectName(_fromUtf8("cmbIntersectingType"))
        self.horizontalLayout_60.addWidget(self.cmbIntersectingType)
        self.vl_gbIntersectingAid.addWidget(self.frameIntersectingType)

        self.txtIntersectingRadialTrack = TrackRadialBoxPanel(self.gbIntersectingAid)
        self.txtIntersectingRadialTrack.Caption = "Radial"
        self.vl_gbIntersectingAid.addWidget(self.txtIntersectingRadialTrack)
        # self.frameTrackRoot_2 = QtGui.QFrame(self.gbIntersectingAid)
        # self.frameTrackRoot_2.setFrameShape(QtGui.QFrame.NoFrame)
        # self.frameTrackRoot_2.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameTrackRoot_2.setObjectName(_fromUtf8("frameTrackRoot_2"))
        # self.horizontalLayout_64 = QtGui.QHBoxLayout(self.frameTrackRoot_2)
        # self.horizontalLayout_64.setSpacing(0)
        # self.horizontalLayout_64.setMargin(0)
        # self.horizontalLayout_64.setObjectName(_fromUtf8("horizontalLayout_64"))
        # self.label_IntersectingRadial = QtGui.QLabel(self.frameTrackRoot_2)
        # self.label_IntersectingRadial.setMinimumSize(QtCore.QSize(150, 0))
        # self.label_IntersectingRadial.setMaximumSize(QtCore.QSize(150, 16777215))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_IntersectingRadial.setFont(font)
        # self.label_IntersectingRadial.setObjectName(_fromUtf8("label_IntersectingRadial"))
        # self.horizontalLayout_64.addWidget(self.label_IntersectingRadial)
        # self.frameIntersectingRadialTrack = QtGui.QFrame(self.frameTrackRoot_2)
        # self.frameIntersectingRadialTrack.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frameIntersectingRadialTrack.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameIntersectingRadialTrack.setObjectName(_fromUtf8("frameIntersectingRadialTrack"))
        # self.horizontalLayout_12 = QtGui.QHBoxLayout(self.frameIntersectingRadialTrack)
        # self.horizontalLayout_12.setSpacing(0)
        # self.horizontalLayout_12.setMargin(0)
        # self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        # self.txtIntersectingRadialTrack = QtGui.QLineEdit(self.frameIntersectingRadialTrack)
        # self.txtIntersectingRadialTrack.setEnabled(True)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.txtIntersectingRadialTrack.sizePolicy().hasHeightForWidth())
        # self.txtIntersectingRadialTrack.setSizePolicy(sizePolicy)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.txtIntersectingRadialTrack.setFont(font)
        # self.txtIntersectingRadialTrack.setObjectName(_fromUtf8("txtIntersectingRadialTrack"))
        # self.horizontalLayout_12.addWidget(self.txtIntersectingRadialTrack)
        # self.btnCaptureIntersectingRadialTrack = QtGui.QToolButton(self.frameIntersectingRadialTrack)
        # self.btnCaptureIntersectingRadialTrack.setText(_fromUtf8(""))
        # self.btnCaptureIntersectingRadialTrack.setIcon(icon)
        # self.btnCaptureIntersectingRadialTrack.setObjectName(_fromUtf8("btnCaptureIntersectingRadialTrack"))
        # self.horizontalLayout_12.addWidget(self.btnCaptureIntersectingRadialTrack)
        # self.horizontalLayout_64.addWidget(self.frameIntersectingRadialTrack)
        # self.vl_gbIntersectingAid.addWidget(self.frameTrackRoot_2)
        self.frame_IntersectingDistance = QtGui.QFrame(self.gbIntersectingAid)
        self.frame_IntersectingDistance.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_IntersectingDistance.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_IntersectingDistance.setObjectName(_fromUtf8("frame_IntersectingDistance"))
        self.horizontalLayout_65 = QtGui.QHBoxLayout(self.frame_IntersectingDistance)
        self.horizontalLayout_65.setSpacing(0)
        self.horizontalLayout_65.setMargin(0)
        self.horizontalLayout_65.setObjectName(_fromUtf8("horizontalLayout_65"))
        self.label_74 = QtGui.QLabel(self.frame_IntersectingDistance)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_74.sizePolicy().hasHeightForWidth())
        self.label_74.setSizePolicy(sizePolicy)
        self.label_74.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_65.addWidget(self.label_74)
        self.frame_APV_9 = QtGui.QFrame(self.frame_IntersectingDistance)
        self.frame_APV_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_9.setObjectName(_fromUtf8("frame_APV_9"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.frame_APV_9)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.txtIntersectingDistance = QtGui.QLineEdit(self.frame_APV_9)
        self.txtIntersectingDistance.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtIntersectingDistance.setFont(font)
        self.txtIntersectingDistance.setObjectName(_fromUtf8("txtIntersectingDistance"))
        self.horizontalLayout_13.addWidget(self.txtIntersectingDistance)
        self.btnMeasureIntersectingDistance = QtGui.QToolButton(self.frame_APV_9)
        self.btnMeasureIntersectingDistance.setText(_fromUtf8(""))
        self.btnMeasureIntersectingDistance.setIcon(icon)
        self.btnMeasureIntersectingDistance.setObjectName(_fromUtf8("btnMeasureIntersectingDistance"))
        self.horizontalLayout_13.addWidget(self.btnMeasureIntersectingDistance)
        self.horizontalLayout_65.addWidget(self.frame_APV_9)
        self.vl_gbIntersectingAid.addWidget(self.frame_IntersectingDistance)
        self.pnl0dmeAtThr = QtGui.QFrame(self.gbIntersectingAid)
        self.pnl0dmeAtThr.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnl0dmeAtThr.setFrameShadow(QtGui.QFrame.Raised)
        self.pnl0dmeAtThr.setObjectName(_fromUtf8("pnl0dmeAtThr"))
        self.vl_pnl0dmeAtThr = QtGui.QVBoxLayout(self.pnl0dmeAtThr)
        self.vl_pnl0dmeAtThr.setSpacing(0)
        self.vl_pnl0dmeAtThr.setMargin(0)
        self.vl_pnl0dmeAtThr.setObjectName(_fromUtf8("vl_pnl0dmeAtThr"))
        self.chb0dmeAtThr = QtGui.QCheckBox(self.pnl0dmeAtThr)
        self.chb0dmeAtThr.setObjectName(_fromUtf8("chb0dmeAtThr"))
        self.vl_pnl0dmeAtThr.addWidget(self.chb0dmeAtThr)
        self.frame_DmeOffset = QtGui.QFrame(self.pnl0dmeAtThr)
        self.frame_DmeOffset.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_DmeOffset.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_DmeOffset.setObjectName(_fromUtf8("frame_DmeOffset"))
        self.horizontalLayout_66 = QtGui.QHBoxLayout(self.frame_DmeOffset)
        self.horizontalLayout_66.setSpacing(0)
        self.horizontalLayout_66.setMargin(0)
        self.horizontalLayout_66.setObjectName(_fromUtf8("horizontalLayout_66"))
        self.label_73 = QtGui.QLabel(self.frame_DmeOffset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_73.sizePolicy().hasHeightForWidth())
        self.label_73.setSizePolicy(sizePolicy)
        self.label_73.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.horizontalLayout_66.addWidget(self.label_73)
        self.frame_APV_8 = QtGui.QFrame(self.frame_DmeOffset)
        self.frame_APV_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_8.setObjectName(_fromUtf8("frame_APV_8"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.frame_APV_8)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.txtDmeOffset = QtGui.QLineEdit(self.frame_APV_8)
        self.txtDmeOffset.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtDmeOffset.setFont(font)
        self.txtDmeOffset.setObjectName(_fromUtf8("txtDmeOffset"))
        self.horizontalLayout_14.addWidget(self.txtDmeOffset)
        self.btnMeasureDmeOffset = QtGui.QToolButton(self.frame_APV_8)
        self.btnMeasureDmeOffset.setText(_fromUtf8(""))
        self.btnMeasureDmeOffset.setIcon(icon)
        self.btnMeasureDmeOffset.setObjectName(_fromUtf8("btnMeasureDmeOffset"))
        self.horizontalLayout_14.addWidget(self.btnMeasureDmeOffset)
        self.horizontalLayout_66.addWidget(self.frame_APV_8)
        self.vl_pnl0dmeAtThr.addWidget(self.frame_DmeOffset)
        self.vl_gbIntersectingAid.addWidget(self.pnl0dmeAtThr)
        self.vlResultGroup.addWidget(self.gbIntersectingAid)
        self.hlResults.addWidget(self.grbResult)
        self.frmGeneralButtons_2 = QtGui.QFrame(self.tab_Results)
        self.frmGeneralButtons_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frmGeneralButtons_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmGeneralButtons_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frmGeneralButtons_2.setObjectName(_fromUtf8("frmGeneralButtons_2"))
        self.vlGeneralBtns_2 = QtGui.QVBoxLayout(self.frmGeneralButtons_2)
        self.vlGeneralBtns_2.setObjectName(_fromUtf8("vlGeneralBtns_2"))
        self.btnOpenData_2 = QtGui.QPushButton(self.frmGeneralButtons_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnOpenData_2.setFont(font)
        self.btnOpenData_2.setObjectName(_fromUtf8("btnOpenData_2"))
        self.vlGeneralBtns_2.addWidget(self.btnOpenData_2)
        self.btnSaveData_2 = QtGui.QPushButton(self.frmGeneralButtons_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnSaveData_2.setFont(font)
        self.btnSaveData_2.setObjectName(_fromUtf8("btnSaveData_2"))
        self.vlGeneralBtns_2.addWidget(self.btnSaveData_2)
        self.btnConstruct_2 = QtGui.QPushButton(self.frmGeneralButtons_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnConstruct_2.setFont(font)
        self.btnConstruct_2.setObjectName(_fromUtf8("btnConstruct_2"))
        self.vlGeneralBtns_2.addWidget(self.btnConstruct_2)
        self.btnEvaluate_2 = QtGui.QPushButton(self.frmGeneralButtons_2)
        self.btnEvaluate_2.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnEvaluate_2.setFont(font)
        self.btnEvaluate_2.setObjectName(_fromUtf8("btnEvaluate_2"))
        self.vlGeneralBtns_2.addWidget(self.btnEvaluate_2)
        self.btnExportResult_2 = QtGui.QPushButton(self.frmGeneralButtons_2)
        self.btnExportResult_2.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnExportResult_2.setFont(font)
        self.btnExportResult_2.setObjectName(_fromUtf8("btnExportResult_2"))
        self.vlGeneralBtns_2.addWidget(self.btnExportResult_2)
        self.btnClose_2 = QtGui.QPushButton(self.frmGeneralButtons_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnClose_2.setFont(font)
        self.btnClose_2.setObjectName(_fromUtf8("btnClose_2"))
        self.vlGeneralBtns_2.addWidget(self.btnClose_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vlGeneralBtns_2.addItem(spacerItem)
        self.hlResults.addWidget(self.frmGeneralButtons_2)
        self.tabCtrlGeneral.addTab(self.tab_Results, _fromUtf8(""))
        self.tab_General = QtGui.QWidget(FixToleranceArea)
        self.tab_General.setObjectName(_fromUtf8("tab_General"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.tab_General)
        self.horizontalLayout_29.setMargin(3)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.grbGeneral = QtGui.QGroupBox(self.tab_General)
        self.grbGeneral.setTitle(_fromUtf8(""))
        self.grbGeneral.setObjectName(_fromUtf8("grbGeneral"))
        self.vlGeneral = QtGui.QVBoxLayout(self.grbGeneral)
        self.vlGeneral.setMargin(5)
        self.vlGeneral.setObjectName(_fromUtf8("vlGeneral"))
        self.gbNavAid = QtGui.QGroupBox(self.grbGeneral)
        self.gbNavAid.setObjectName(_fromUtf8("gbNavAid"))
        self.vl_NavAid = QtGui.QVBoxLayout(self.gbNavAid)
        self.vl_NavAid.setObjectName(_fromUtf8("vl_NavAid"))
        self.frameNavAidType = QtGui.QFrame(self.gbNavAid)
        self.frameNavAidType.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameNavAidType.setFrameShadow(QtGui.QFrame.Raised)
        self.frameNavAidType.setObjectName(_fromUtf8("frameNavAidType"))
        self.horizontalLayout_61 = QtGui.QHBoxLayout(self.frameNavAidType)
        self.horizontalLayout_61.setSpacing(0)
        self.horizontalLayout_61.setMargin(0)
        self.horizontalLayout_61.setObjectName(_fromUtf8("horizontalLayout_61"))
        self.label_69 = QtGui.QLabel(self.frameNavAidType)
        self.label_69.setMinimumSize(QtCore.QSize(100, 0))
        self.label_69.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.horizontalLayout_61.addWidget(self.label_69)
        self.cmbNavAidType = QtGui.QComboBox(self.frameNavAidType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbNavAidType.sizePolicy().hasHeightForWidth())
        self.cmbNavAidType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbNavAidType.setFont(font)
        self.cmbNavAidType.setObjectName(_fromUtf8("cmbNavAidType"))
        self.horizontalLayout_61.addWidget(self.cmbNavAidType)
        self.vl_NavAid.addWidget(self.frameNavAidType)
        self.vlGeneral.addWidget(self.gbNavAid)
        self.gbParameters = QtGui.QGroupBox(self.grbGeneral)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.gbParameters.setFont(font)
        self.gbParameters.setObjectName(_fromUtf8("gbParameters"))
        self.vl_gbParameters = QtGui.QVBoxLayout(self.gbParameters)
        self.vl_gbParameters.setObjectName(_fromUtf8("vl_gbParameters"))

        self.txtTrackRadial = TrackRadialBoxPanel(self.gbParameters)
        self.txtTrackRadial.Caption = "In-bound Track"
        self.vl_gbParameters.addWidget(self.txtTrackRadial)
        # self.frameTrackRoot = QtGui.QFrame(self.gbParameters)
        # self.frameTrackRoot.setFrameShape(QtGui.QFrame.NoFrame)
        # self.frameTrackRoot.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameTrackRoot.setObjectName(_fromUtf8("frameTrackRoot"))
        # self.horizontalLayout_63 = QtGui.QHBoxLayout(self.frameTrackRoot)
        # self.horizontalLayout_63.setSpacing(0)
        # self.horizontalLayout_63.setMargin(0)
        # self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        # self.label_71 = QtGui.QLabel(self.frameTrackRoot)
        # self.label_71.setMinimumSize(QtCore.QSize(100, 0))
        # self.label_71.setMaximumSize(QtCore.QSize(100, 16777215))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_71.setFont(font)
        # self.label_71.setObjectName(_fromUtf8("label_71"))
        # self.horizontalLayout_63.addWidget(self.label_71)
        # self.frameTrack = QtGui.QFrame(self.frameTrackRoot)
        # self.frameTrack.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frameTrack.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameTrack.setObjectName(_fromUtf8("frameTrack"))
        # self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frameTrack)
        # self.horizontalLayout_10.setSpacing(0)
        # self.horizontalLayout_10.setMargin(0)
        # self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        # self.txtTrackRadial = QtGui.QLineEdit(self.frameTrack)
        # self.txtTrackRadial.setEnabled(True)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.txtTrackRadial.setFont(font)
        # self.txtTrackRadial.setObjectName(_fromUtf8("txtTrackRadial"))
        # self.horizontalLayout_10.addWidget(self.txtTrackRadial)
        # self.btnCaptureTrack = QtGui.QToolButton(self.frameTrack)
        # self.btnCaptureTrack.setText(_fromUtf8(""))
        # self.btnCaptureTrack.setIcon(icon)
        # self.btnCaptureTrack.setObjectName(_fromUtf8("btnCaptureTrack"))
        # self.horizontalLayout_10.addWidget(self.btnCaptureTrack)
        # self.horizontalLayout_63.addWidget(self.frameTrack)
        # self.vl_gbParameters.addWidget(self.frameTrackRoot)
        self.frameAltitude_2 = QtGui.QFrame(self.gbParameters)
        self.frameAltitude_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAltitude_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAltitude_2.setObjectName(_fromUtf8("frameAltitude_2"))
        self.horizontalLayout_70 = QtGui.QHBoxLayout(self.frameAltitude_2)
        self.horizontalLayout_70.setSpacing(0)
        self.horizontalLayout_70.setMargin(0)
        self.horizontalLayout_70.setObjectName(_fromUtf8("horizontalLayout_70"))
        self.label_78 = QtGui.QLabel(self.frameAltitude_2)
        self.label_78.setMinimumSize(QtCore.QSize(100, 0))
        self.label_78.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_78.setFont(font)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.horizontalLayout_70.addWidget(self.label_78)
        self.txtAltitudeM = QtGui.QLineEdit(self.frameAltitude_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitudeM.setFont(font)
        self.txtAltitudeM.setText(_fromUtf8(""))
        self.txtAltitudeM.setObjectName(_fromUtf8("txtAltitudeM"))
        self.horizontalLayout_70.addWidget(self.txtAltitudeM)
        self.label_2 = QtGui.QLabel(self.frameAltitude_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_70.addWidget(self.label_2)
        self.txtAltitude = QtGui.QLineEdit(self.frameAltitude_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitude.setFont(font)
        self.txtAltitude.setObjectName(_fromUtf8("txtAltitude"))
        self.horizontalLayout_70.addWidget(self.txtAltitude)
        self.label = QtGui.QLabel(self.frameAltitude_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_70.addWidget(self.label)
        self.vl_gbParameters.addWidget(self.frameAltitude_2)
        self.frameMoc = QtGui.QFrame(self.gbParameters)
        self.frameMoc.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMoc.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMoc.setObjectName(_fromUtf8("frameMoc"))
        self.horizontalLayout_74 = QtGui.QHBoxLayout(self.frameMoc)
        self.horizontalLayout_74.setSpacing(0)
        self.horizontalLayout_74.setMargin(0)
        self.horizontalLayout_74.setObjectName(_fromUtf8("horizontalLayout_74"))
        self.label_82 = QtGui.QLabel(self.frameMoc)
        self.label_82.setMinimumSize(QtCore.QSize(100, 0))
        self.label_82.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_82.setFont(font)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.horizontalLayout_74.addWidget(self.label_82)
        self.txtMoc = QtGui.QLineEdit(self.frameMoc)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMoc.setFont(font)
        self.txtMoc.setObjectName(_fromUtf8("txtMoc"))
        self.horizontalLayout_74.addWidget(self.txtMoc)
        self.vl_gbParameters.addWidget(self.frameMoc)
        self.frameMOCMultipiler = QtGui.QFrame(self.gbParameters)
        self.frameMOCMultipiler.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMOCMultipiler.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMOCMultipiler.setObjectName(_fromUtf8("frameMOCMultipiler"))
        self.horizontalLayout_62 = QtGui.QHBoxLayout(self.frameMOCMultipiler)
        self.horizontalLayout_62.setSpacing(0)
        self.horizontalLayout_62.setMargin(0)
        self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        self.label_70 = QtGui.QLabel(self.frameMOCMultipiler)
        self.label_70.setMinimumSize(QtCore.QSize(100, 0))
        self.label_70.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.horizontalLayout_62.addWidget(self.label_70)
        self.spinBoxMocmulipiler = QtGui.QSpinBox(self.frameMOCMultipiler)
        self.spinBoxMocmulipiler.setProperty("value", 1)
        self.spinBoxMocmulipiler.setObjectName(_fromUtf8("spinBoxMocmulipiler"))
        self.horizontalLayout_62.addWidget(self.spinBoxMocmulipiler)
        self.vl_gbParameters.addWidget(self.frameMOCMultipiler)
        self.vlGeneral.addWidget(self.gbParameters)
        self.horizontalLayout_29.addWidget(self.grbGeneral)
        self.frmGeneralButtons = QtGui.QFrame(self.tab_General)
        self.frmGeneralButtons.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frmGeneralButtons.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmGeneralButtons.setFrameShadow(QtGui.QFrame.Raised)
        self.frmGeneralButtons.setObjectName(_fromUtf8("frmGeneralButtons"))
        self.vlGeneralBtns = QtGui.QVBoxLayout(self.frmGeneralButtons)
        self.vlGeneralBtns.setObjectName(_fromUtf8("vlGeneralBtns"))
        self.btnOpenData = QtGui.QPushButton(self.frmGeneralButtons)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnOpenData.setFont(font)
        self.btnOpenData.setObjectName(_fromUtf8("btnOpenData"))
        self.vlGeneralBtns.addWidget(self.btnOpenData)
        self.btnSaveData = QtGui.QPushButton(self.frmGeneralButtons)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnSaveData.setFont(font)
        self.btnSaveData.setObjectName(_fromUtf8("btnSaveData"))
        self.vlGeneralBtns.addWidget(self.btnSaveData)
        self.btnConstruct = QtGui.QPushButton(self.frmGeneralButtons)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnConstruct.setFont(font)
        self.btnConstruct.setObjectName(_fromUtf8("btnConstruct"))
        self.vlGeneralBtns.addWidget(self.btnConstruct)
        self.btnPDTCheck = QtGui.QPushButton(self.frmGeneralButtons)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnPDTCheck.setFont(font)
        self.btnPDTCheck.setObjectName(_fromUtf8("btnPDTCheck"))
        self.vlGeneralBtns.addWidget(self.btnPDTCheck)
        self.btnEvaluate = QtGui.QPushButton(self.frmGeneralButtons)
        self.btnEvaluate.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnEvaluate.setFont(font)
        self.btnEvaluate.setObjectName(_fromUtf8("btnEvaluate"))
        self.vlGeneralBtns.addWidget(self.btnEvaluate)
        self.btnExportResult = QtGui.QPushButton(self.frmGeneralButtons)
        self.btnExportResult.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnExportResult.setFont(font)
        self.btnExportResult.setObjectName(_fromUtf8("btnExportResult"))
        self.vlGeneralBtns.addWidget(self.btnExportResult)
        self.btnClose = QtGui.QPushButton(self.frmGeneralButtons)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnClose.setFont(font)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.vlGeneralBtns.addWidget(self.btnClose)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vlGeneralBtns.addItem(spacerItem1)
        self.horizontalLayout_29.addWidget(self.frmGeneralButtons)
        self.tabCtrlGeneral.addTab(self.tab_General, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabCtrlGeneral)

        self.retranslateUi(FixToleranceArea)
        self.tabCtrlGeneral.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FixToleranceArea)

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/openData.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpenData.setIcon(icon)
        self.btnOpenData_2.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/saveData.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveData.setIcon(icon)
        self.btnSaveData_2.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/construct.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConstruct.setIcon(icon)
        self.btnConstruct_2.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/evaluate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEvaluate.setIcon(icon)
        # self.btnEvaluate.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon)
        self.btnClose_2.setIcon(icon)


        self.btnClose.setToolTip(_fromUtf8("Close"))
        self.btnClose_2.setToolTip(_fromUtf8("Close"))
        self.btnConstruct.setToolTip(_fromUtf8("Construct"))
        self.btnConstruct_2.setToolTip(_fromUtf8("Construct"))
        self.btnEvaluate.setToolTip(_fromUtf8("Evaluate"))
        self.btnOpenData.setToolTip(_fromUtf8("Open Data"))
        self.btnOpenData_2.setToolTip(_fromUtf8("Open Data"))
        self.btnSaveData.setToolTip(_fromUtf8("Save Data"))
        self.btnSaveData_2.setToolTip(_fromUtf8("Save Data"))

    def retranslateUi(self, FixToleranceArea):
        FixToleranceArea.setWindowTitle(_translate("FixToleranceArea", "FixToleranceArea", None))
        self.gbTrackingAid.setTitle(_translate("FixToleranceArea", "Tracking Aid", None))
        self.label_67.setText(_translate("FixToleranceArea", "Type:", None))
        # self.label_TrackingRadial.setText(_translate("FixToleranceArea", "Radial(°):", None))
        # self.txtTrackingRadialTrack.setText(_translate("FixToleranceArea", "0", None))
        self.gbIntersectingAid.setTitle(_translate("FixToleranceArea", "Intersecting Aid", None))
        self.label_68.setText(_translate("FixToleranceArea", "Type:", None))
        # self.label_IntersectingRadial.setText(_translate("FixToleranceArea", "Radial(°):", None))
        # self.txtIntersectingRadialTrack.setText(_translate("FixToleranceArea", "180", None))
        self.label_74.setText(_translate("FixToleranceArea", "DME Distance (nm):", None))
        self.txtIntersectingDistance.setText(_translate("FixToleranceArea", "5", None))
        self.chb0dmeAtThr.setText(_translate("FixToleranceArea", "0 DME at THR", None))
        self.label_73.setText(_translate("FixToleranceArea", "DME to THR Distance (m):", None))
        self.txtDmeOffset.setText(_translate("FixToleranceArea", "5", None))
        # self.btnOpenData_2.setText(_translate("FixToleranceArea", "Open Data", None))
        # self.btnSaveData_2.setText(_translate("FixToleranceArea", "Save Data", None))
        # self.btnConstruct_2.setText(_translate("FixToleranceArea", "Construct", None))
        # self.btnEvaluate_2.setText(_translate("FixToleranceArea", "Evaluate", None))
        # self.btnExportResult_2.setText(_translate("FixToleranceArea", "Export Result", None))
        # self.btnClose_2.setText(_translate("FixToleranceArea", "Close", None))
        self.tabCtrlGeneral.setTabText(self.tabCtrlGeneral.indexOf(self.tab_Results), _translate("FixToleranceArea", "Fix Construction", None))
        self.gbNavAid.setTitle(_translate("FixToleranceArea", "Navigational Aid", None))
        self.label_69.setText(_translate("FixToleranceArea", "Type:", None))
        self.gbParameters.setTitle(_translate("FixToleranceArea", "Parameters", None))
        # self.label_71.setText(_translate("FixToleranceArea", "In-bound Track (°):", None))
        # self.txtTrackRadial.setText(_translate("FixToleranceArea", "0", None))
        self.label_78.setText(_translate("FixToleranceArea", "Altitude:", None))
        self.label_2.setText(_translate("FixToleranceArea", "m", None))
        self.txtAltitude.setText(_translate("FixToleranceArea", "5000", None))
        self.label.setText(_translate("FixToleranceArea", "ft", None))
        self.label_82.setText(_translate("FixToleranceArea", "Moc (m):", None))
        self.txtMoc.setText(_translate("FixToleranceArea", "300", None))
        self.label_70.setText(_translate("FixToleranceArea", "MOCmultipiler:", None))
        # self.btnOpenData.setText(_translate("FixToleranceArea", "Open Data", None))
        # self.btnSaveData.setText(_translate("FixToleranceArea", "Save Data", None))
        # self.btnConstruct.setText(_translate("FixToleranceArea", "Construct", None))
        # self.btnPDTCheck.setText(_translate("FixToleranceArea", "PDT Check", None))
        # self.btnEvaluate.setText(_translate("FixToleranceArea", "Evaluate", None))
        # self.btnExportResult.setText(_translate("FixToleranceArea", "Export Result", None))
        # self.btnClose.setText(_translate("FixToleranceArea", "Close", None))
        self.tabCtrlGeneral.setTabText(self.tabCtrlGeneral.indexOf(self.tab_General), _translate("FixToleranceArea", "Over-head Tolerance Construction", None))


