# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OverheadTolerance.ui'
#
# Created: Thu Jan 28 09:22:18 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from FlightPlanner.Panels.TrackRadialBoxPanel import TrackRadialBoxPanel

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OverheadTolerance(object):
    def setupUi(self, OverheadTolerance):
        OverheadTolerance.setObjectName(_fromUtf8("OverheadTolerance"))
        OverheadTolerance.resize(323, 242)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OverheadTolerance.sizePolicy().hasHeightForWidth())
        OverheadTolerance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        OverheadTolerance.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(OverheadTolerance)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbNavAid = QtGui.QGroupBox(OverheadTolerance)
        self.gbNavAid.setObjectName(_fromUtf8("gbNavAid"))
        self.vl_NavAid = QtGui.QVBoxLayout(self.gbNavAid)
        self.vl_NavAid.setObjectName(_fromUtf8("vl_NavAid"))
        self.frameNavAidType = QtGui.QFrame(self.gbNavAid)
        self.frameNavAidType.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameNavAidType.setFrameShadow(QtGui.QFrame.Raised)
        self.frameNavAidType.setObjectName(_fromUtf8("frameNavAidType"))
        self.horizontalLayout_61 = QtGui.QHBoxLayout(self.frameNavAidType)
        self.horizontalLayout_61.setSpacing(0)
        self.horizontalLayout_61.setMargin(0)
        self.horizontalLayout_61.setObjectName(_fromUtf8("horizontalLayout_61"))
        self.label_69 = QtGui.QLabel(self.frameNavAidType)
        self.label_69.setMinimumSize(QtCore.QSize(100, 0))
        self.label_69.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.horizontalLayout_61.addWidget(self.label_69)
        self.cmbNavAidType = QtGui.QComboBox(self.frameNavAidType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbNavAidType.sizePolicy().hasHeightForWidth())
        self.cmbNavAidType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbNavAidType.setFont(font)
        self.cmbNavAidType.setObjectName(_fromUtf8("cmbNavAidType"))
        self.horizontalLayout_61.addWidget(self.cmbNavAidType)
        self.vl_NavAid.addWidget(self.frameNavAidType)
        self.verticalLayout.addWidget(self.gbNavAid)
        self.gbParameters = QtGui.QGroupBox(OverheadTolerance)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.gbParameters.setFont(font)
        self.gbParameters.setObjectName(_fromUtf8("gbParameters"))
        self.vl_gbParameters = QtGui.QVBoxLayout(self.gbParameters)
        self.vl_gbParameters.setObjectName(_fromUtf8("vl_gbParameters"))

        self.txtTrackRadial = TrackRadialBoxPanel(self.gbParameters)
        self.txtTrackRadial.Caption = "Radial"
        self.vl_gbParameters.addWidget(self.txtTrackRadial)
        # self.frameTrackRoot = QtGui.QFrame(self.gbParameters)
        # self.frameTrackRoot.setFrameShape(QtGui.QFrame.NoFrame)
        # self.frameTrackRoot.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameTrackRoot.setObjectName(_fromUtf8("frameTrackRoot"))
        # self.horizontalLayout_63 = QtGui.QHBoxLayout(self.frameTrackRoot)
        # self.horizontalLayout_63.setSpacing(0)
        # self.horizontalLayout_63.setMargin(0)
        # self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        # self.label_71 = QtGui.QLabel(self.frameTrackRoot)
        # self.label_71.setMinimumSize(QtCore.QSize(100, 0))
        # self.label_71.setMaximumSize(QtCore.QSize(100, 16777215))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_71.setFont(font)
        # self.label_71.setObjectName(_fromUtf8("label_71"))
        # self.horizontalLayout_63.addWidget(self.label_71)
        # self.frameTrack = QtGui.QFrame(self.frameTrackRoot)
        # self.frameTrack.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frameTrack.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameTrack.setObjectName(_fromUtf8("frameTrack"))
        # self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frameTrack)
        # self.horizontalLayout_10.setSpacing(0)
        # self.horizontalLayout_10.setMargin(0)
        # self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        # self.txtTrackRadial = QtGui.QLineEdit(self.frameTrack)
        # self.txtTrackRadial.setEnabled(True)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.txtTrackRadial.setFont(font)
        # self.txtTrackRadial.setObjectName(_fromUtf8("txtTrackRadial"))
        # self.horizontalLayout_10.addWidget(self.txtTrackRadial)
        # self.btnCaptureTrack = QtGui.QToolButton(self.frameTrack)
        # self.btnCaptureTrack.setText(_fromUtf8(""))
        # icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.btnCaptureTrack.setIcon(icon)
        # self.btnCaptureTrack.setObjectName(_fromUtf8("btnCaptureTrack"))
        # self.horizontalLayout_10.addWidget(self.btnCaptureTrack)
        # self.horizontalLayout_63.addWidget(self.frameTrack)
        # self.vl_gbParameters.addWidget(self.frameTrackRoot)
        self.frameAltitude_2 = QtGui.QFrame(self.gbParameters)
        self.frameAltitude_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAltitude_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAltitude_2.setObjectName(_fromUtf8("frameAltitude_2"))
        self.horizontalLayout_70 = QtGui.QHBoxLayout(self.frameAltitude_2)
        self.horizontalLayout_70.setSpacing(0)
        self.horizontalLayout_70.setMargin(0)
        self.horizontalLayout_70.setObjectName(_fromUtf8("horizontalLayout_70"))
        self.label_78 = QtGui.QLabel(self.frameAltitude_2)
        self.label_78.setMinimumSize(QtCore.QSize(100, 0))
        self.label_78.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_78.setFont(font)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.horizontalLayout_70.addWidget(self.label_78)
        self.txtAltitudeM = QtGui.QLineEdit(self.frameAltitude_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitudeM.setFont(font)
        self.txtAltitudeM.setText(_fromUtf8(""))
        self.txtAltitudeM.setObjectName(_fromUtf8("txtAltitudeM"))
        self.horizontalLayout_70.addWidget(self.txtAltitudeM)
        self.label_2 = QtGui.QLabel(self.frameAltitude_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_70.addWidget(self.label_2)
        self.txtAltitude = QtGui.QLineEdit(self.frameAltitude_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitude.setFont(font)
        self.txtAltitude.setObjectName(_fromUtf8("txtAltitude"))
        self.horizontalLayout_70.addWidget(self.txtAltitude)
        self.label = QtGui.QLabel(self.frameAltitude_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_70.addWidget(self.label)
        self.vl_gbParameters.addWidget(self.frameAltitude_2)
        self.frameMoc = QtGui.QFrame(self.gbParameters)
        self.frameMoc.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMoc.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMoc.setObjectName(_fromUtf8("frameMoc"))
        self.horizontalLayout_74 = QtGui.QHBoxLayout(self.frameMoc)
        self.horizontalLayout_74.setSpacing(0)
        self.horizontalLayout_74.setMargin(0)
        self.horizontalLayout_74.setObjectName(_fromUtf8("horizontalLayout_74"))
        self.label_82 = QtGui.QLabel(self.frameMoc)
        self.label_82.setMinimumSize(QtCore.QSize(100, 0))
        self.label_82.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_82.setFont(font)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.horizontalLayout_74.addWidget(self.label_82)
        self.txtMoc = QtGui.QLineEdit(self.frameMoc)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMoc.setFont(font)
        self.txtMoc.setObjectName(_fromUtf8("txtMoc"))
        self.horizontalLayout_74.addWidget(self.txtMoc)
        self.vl_gbParameters.addWidget(self.frameMoc)
        self.frameMOCMultipiler = QtGui.QFrame(self.gbParameters)
        self.frameMOCMultipiler.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMOCMultipiler.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMOCMultipiler.setObjectName(_fromUtf8("frameMOCMultipiler"))
        self.horizontalLayout_62 = QtGui.QHBoxLayout(self.frameMOCMultipiler)
        self.horizontalLayout_62.setSpacing(0)
        self.horizontalLayout_62.setMargin(0)
        self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        self.label_70 = QtGui.QLabel(self.frameMOCMultipiler)
        self.label_70.setMinimumSize(QtCore.QSize(100, 0))
        self.label_70.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.horizontalLayout_62.addWidget(self.label_70)
        self.spinBoxMocmulipiler = QtGui.QSpinBox(self.frameMOCMultipiler)
        self.spinBoxMocmulipiler.setProperty("value", 1)
        self.spinBoxMocmulipiler.setObjectName(_fromUtf8("spinBoxMocmulipiler"))
        self.horizontalLayout_62.addWidget(self.spinBoxMocmulipiler)
        self.vl_gbParameters.addWidget(self.frameMOCMultipiler)
        self.verticalLayout.addWidget(self.gbParameters)

        self.retranslateUi(OverheadTolerance)
        QtCore.QMetaObject.connectSlotsByName(OverheadTolerance)

    def retranslateUi(self, OverheadTolerance):
        OverheadTolerance.setWindowTitle(_translate("OverheadTolerance", "Form", None))
        self.gbNavAid.setTitle(_translate("OverheadTolerance", "Navigational Aid", None))
        self.label_69.setText(_translate("OverheadTolerance", "Type:", None))
        self.gbParameters.setTitle(_translate("OverheadTolerance", "Parameters", None))
        # self.label_71.setText(_translate("OverheadTolerance", "In-bound Track (°):", None))
        # self.txtTrackRadial.setText(_translate("OverheadTolerance", "0", None))
        self.label_78.setText(_translate("OverheadTolerance", "Altitude:", None))
        self.label_2.setText(_translate("OverheadTolerance", "m", None))
        self.txtAltitude.setText(_translate("OverheadTolerance", "5000", None))
        self.label.setText(_translate("OverheadTolerance", "ft", None))
        self.label_82.setText(_translate("OverheadTolerance", "Moc (m):", None))
        self.txtMoc.setText(_translate("OverheadTolerance", "300", None))
        self.label_70.setText(_translate("OverheadTolerance", "MOCmultipiler:", None))

