# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_RnavVorDme.ui'
#
# Created: Mon Nov 09 10:59:52 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RnavVorDme(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(484, 556)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbParameters = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.gbParameters.setFont(font)
        self.gbParameters.setObjectName(_fromUtf8("gbParameters"))
        self.vl_gbParameters = QtGui.QVBoxLayout(self.gbParameters)
        self.vl_gbParameters.setObjectName(_fromUtf8("vl_gbParameters"))
        self.frame_58 = QtGui.QFrame(self.gbParameters)
        self.frame_58.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_58.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_58.setObjectName(_fromUtf8("frame_58"))
        self.horizontalLayout_58 = QtGui.QHBoxLayout(self.frame_58)
        self.horizontalLayout_58.setSpacing(0)
        self.horizontalLayout_58.setMargin(0)
        self.horizontalLayout_58.setObjectName(_fromUtf8("horizontalLayout_58"))
        self.label_66 = QtGui.QLabel(self.frame_58)
        self.label_66.setMinimumSize(QtCore.QSize(260, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.horizontalLayout_58.addWidget(self.label_66)
        self.cmbRnavSpecification = QtGui.QComboBox(self.frame_58)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRnavSpecification.sizePolicy().hasHeightForWidth())
        self.cmbRnavSpecification.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbRnavSpecification.setFont(font)
        self.cmbRnavSpecification.setObjectName(_fromUtf8("cmbRnavSpecification"))
        self.horizontalLayout_58.addWidget(self.cmbRnavSpecification)
        self.vl_gbParameters.addWidget(self.frame_58)
        self.chbUse2Waypoints = QtGui.QCheckBox(self.gbParameters)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbUse2Waypoints.setFont(font)
        self.chbUse2Waypoints.setObjectName(_fromUtf8("chbUse2Waypoints"))
        self.vl_gbParameters.addWidget(self.chbUse2Waypoints)
        self.gbVorDmePosition = QtGui.QGroupBox(self.gbParameters)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.gbVorDmePosition.setFont(font)
        self.gbVorDmePosition.setObjectName(_fromUtf8("gbVorDmePosition"))
        self.verticalLayoutVoeDmePosition = QtGui.QVBoxLayout(self.gbVorDmePosition)
        self.verticalLayoutVoeDmePosition.setObjectName(_fromUtf8("verticalLayoutVoeDmePosition"))
        self.vl_gbParameters.addWidget(self.gbVorDmePosition)
        self.gbWaypoint1 = QtGui.QGroupBox(self.gbParameters)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.gbWaypoint1.setFont(font)
        self.gbWaypoint1.setObjectName(_fromUtf8("gbWaypoint1"))
        self.verticalLayoutWaypoint1 = QtGui.QVBoxLayout(self.gbWaypoint1)
        self.verticalLayoutWaypoint1.setObjectName(_fromUtf8("verticalLayoutWaypoint1"))
        self.frame_60 = QtGui.QFrame(self.gbWaypoint1)
        self.frame_60.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_60.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_60.setObjectName(_fromUtf8("frame_60"))
        self.horizontalLayout_62 = QtGui.QHBoxLayout(self.frame_60)
        self.horizontalLayout_62.setSpacing(0)
        self.horizontalLayout_62.setMargin(0)
        self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        self.label_70 = QtGui.QLabel(self.frame_60)
        self.label_70.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.horizontalLayout_62.addWidget(self.label_70)
        self.cmbFlightPhase1 = QtGui.QComboBox(self.frame_60)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFlightPhase1.sizePolicy().hasHeightForWidth())
        self.cmbFlightPhase1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbFlightPhase1.setFont(font)
        self.cmbFlightPhase1.setObjectName(_fromUtf8("cmbFlightPhase1"))
        self.horizontalLayout_62.addWidget(self.cmbFlightPhase1)
        self.verticalLayoutWaypoint1.addWidget(self.frame_60)
        self.vl_gbParameters.addWidget(self.gbWaypoint1)
        self.gbWaypoint2 = QtGui.QGroupBox(self.gbParameters)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.gbWaypoint2.setFont(font)
        self.gbWaypoint2.setObjectName(_fromUtf8("gbWaypoint2"))
        self.verticalLayoutWaypoint2 = QtGui.QVBoxLayout(self.gbWaypoint2)
        self.verticalLayoutWaypoint2.setObjectName(_fromUtf8("verticalLayoutWaypoint2"))
        self.frame_61 = QtGui.QFrame(self.gbWaypoint2)
        self.frame_61.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_61.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_61.setObjectName(_fromUtf8("frame_61"))
        self.horizontalLayout_64 = QtGui.QHBoxLayout(self.frame_61)
        self.horizontalLayout_64.setSpacing(0)
        self.horizontalLayout_64.setMargin(0)
        self.horizontalLayout_64.setObjectName(_fromUtf8("horizontalLayout_64"))
        self.label_72 = QtGui.QLabel(self.frame_61)
        self.label_72.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.horizontalLayout_64.addWidget(self.label_72)
        self.cmbFlightPhase2 = QtGui.QComboBox(self.frame_61)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFlightPhase2.sizePolicy().hasHeightForWidth())
        self.cmbFlightPhase2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbFlightPhase2.setFont(font)
        self.cmbFlightPhase2.setObjectName(_fromUtf8("cmbFlightPhase2"))
        self.horizontalLayout_64.addWidget(self.cmbFlightPhase2)
        self.verticalLayoutWaypoint2.addWidget(self.frame_61)
        self.vl_gbParameters.addWidget(self.gbWaypoint2)

        self.frame_TrackFrom = QtGui.QFrame(self.gbParameters)
        self.frame_TrackFrom.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_TrackFrom.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_TrackFrom.setObjectName(_fromUtf8("frame_TrackFrom"))
        self.horizontalLayout_63 = QtGui.QHBoxLayout(self.frame_TrackFrom)
        self.horizontalLayout_63.setSpacing(0)
        self.horizontalLayout_63.setMargin(0)
        self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        self.label_71 = QtGui.QLabel(self.frame_TrackFrom)
        self.label_71.setMinimumSize(QtCore.QSize(180, 0))
        self.label_71.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_71.setFont(font)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.horizontalLayout_63.addWidget(self.label_71)
        self.frame_APV_6 = QtGui.QFrame(self.frame_TrackFrom)
        self.frame_APV_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_6.setObjectName(_fromUtf8("frame_APV_6"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frame_APV_6)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.txtTrack = QtGui.QLineEdit(self.frame_APV_6)
        self.txtTrack.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtTrack.setFont(font)
        self.txtTrack.setObjectName(_fromUtf8("txtTrack"))
        self.horizontalLayout_10.addWidget(self.txtTrack)
        self.btnCaptureTrack = QtGui.QToolButton(self.frame_APV_6)
        self.btnCaptureTrack.setText(_fromUtf8(""))
        self.btnCaptureTrack.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCaptureTrack.setIcon(icon)
        self.btnCaptureTrack.setObjectName(_fromUtf8("btnCaptureTrack"))
        self.horizontalLayout_10.addWidget(self.btnCaptureTrack)
        self.horizontalLayout_63.addWidget(self.frame_APV_6)
        self.vl_gbParameters.addWidget(self.frame_TrackFrom)




        self.frameSelectionMode = QtGui.QFrame(self.gbParameters)
        self.frameSelectionMode.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameSelectionMode.setFrameShadow(QtGui.QFrame.Raised)
        self.frameSelectionMode.setObjectName(_fromUtf8("frameSelectionMode"))
        self.hLayoutSelectionMode = QtGui.QHBoxLayout(self.frameSelectionMode)
        self.hLayoutSelectionMode.setSpacing(0)
        self.hLayoutSelectionMode.setMargin(0)
        self.hLayoutSelectionMode.setObjectName(_fromUtf8("hLayoutSelectionMode"))
        self.label_67 = QtGui.QLabel(self.frameSelectionMode)
        self.label_67.setMinimumSize(QtCore.QSize(180, 0))
        self.label_67.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.hLayoutSelectionMode.addWidget(self.label_67)
        self.cmbSelectionMode = QtGui.QComboBox(self.frameSelectionMode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSelectionMode.sizePolicy().hasHeightForWidth())
        self.cmbSelectionMode.setSizePolicy(sizePolicy)
        self.cmbSelectionMode.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbSelectionMode.setFont(font)
        self.cmbSelectionMode.setObjectName(_fromUtf8("cmbSelectionMode"))
        self.hLayoutSelectionMode.addWidget(self.cmbSelectionMode)
        self.vl_gbParameters.addWidget(self.frameSelectionMode)
        self.frameAltitude = QtGui.QFrame(self.gbParameters)
        self.frameAltitude.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAltitude.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAltitude.setObjectName(_fromUtf8("frameAltitude"))
        self.hLayoutAltitude = QtGui.QHBoxLayout(self.frameAltitude)
        self.hLayoutAltitude.setSpacing(0)
        self.hLayoutAltitude.setMargin(0)
        self.hLayoutAltitude.setObjectName(_fromUtf8("hLayoutAltitude"))
        self.label_77 = QtGui.QLabel(self.frameAltitude)
        self.label_77.setMinimumSize(QtCore.QSize(180, 0))
        self.label_77.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.hLayoutAltitude.addWidget(self.label_77)
        self.txtAltitude = QtGui.QLineEdit(self.frameAltitude)
        self.txtAltitude.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitude.setFont(font)
        self.txtAltitude.setObjectName(_fromUtf8("txtAltitude"))
        self.hLayoutAltitude.addWidget(self.txtAltitude)
        self.vl_gbParameters.addWidget(self.frameAltitude)
        self.framePrimaryMoc = QtGui.QFrame(self.gbParameters)
        self.framePrimaryMoc.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePrimaryMoc.setFrameShadow(QtGui.QFrame.Raised)
        self.framePrimaryMoc.setObjectName(_fromUtf8("framePrimaryMoc"))
        self.hLayoutPrimaryMoc = QtGui.QHBoxLayout(self.framePrimaryMoc)
        self.hLayoutPrimaryMoc.setSpacing(0)
        self.hLayoutPrimaryMoc.setMargin(0)
        self.hLayoutPrimaryMoc.setObjectName(_fromUtf8("hLayoutPrimaryMoc"))
        self.label_68 = QtGui.QLabel(self.framePrimaryMoc)
        self.label_68.setMinimumSize(QtCore.QSize(180, 0))
        self.label_68.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.hLayoutPrimaryMoc.addWidget(self.label_68)
        self.txtPrimaryMoc = QtGui.QLineEdit(self.framePrimaryMoc)
        self.txtPrimaryMoc.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPrimaryMoc.setFont(font)
        self.txtPrimaryMoc.setObjectName(_fromUtf8("txtPrimaryMoc"))
        self.hLayoutPrimaryMoc.addWidget(self.txtPrimaryMoc)
        self.vl_gbParameters.addWidget(self.framePrimaryMoc)
        self.frameConstruct = QtGui.QFrame(self.gbParameters)
        self.frameConstruct.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameConstruct.setFrameShadow(QtGui.QFrame.Raised)
        self.frameConstruct.setObjectName(_fromUtf8("frameConstruct"))
        self.hLayoutConstruct = QtGui.QHBoxLayout(self.frameConstruct)
        self.hLayoutConstruct.setSpacing(0)
        self.hLayoutConstruct.setMargin(0)
        self.hLayoutConstruct.setObjectName(_fromUtf8("hLayoutConstruct"))
        self.label_89 = QtGui.QLabel(self.frameConstruct)
        self.label_89.setMinimumSize(QtCore.QSize(180, 0))
        self.label_89.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_89.setFont(font)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.hLayoutConstruct.addWidget(self.label_89)
        self.cmbConstruct = QtGui.QComboBox(self.frameConstruct)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConstruct.sizePolicy().hasHeightForWidth())
        self.cmbConstruct.setSizePolicy(sizePolicy)
        self.cmbConstruct.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbConstruct.setFont(font)
        self.cmbConstruct.setObjectName(_fromUtf8("cmbConstruct"))
        self.hLayoutConstruct.addWidget(self.cmbConstruct)
        self.vl_gbParameters.addWidget(self.frameConstruct)
        self.frameMOCmultipiler = QtGui.QFrame(self.gbParameters)
        self.frameMOCmultipiler.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMOCmultipiler.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMOCmultipiler.setObjectName(_fromUtf8("frameMOCmultipiler"))
        self.hLayoutMOCmultipiler = QtGui.QHBoxLayout(self.frameMOCmultipiler)
        self.hLayoutMOCmultipiler.setSpacing(0)
        self.hLayoutMOCmultipiler.setMargin(0)
        self.hLayoutMOCmultipiler.setObjectName(_fromUtf8("hLayoutMOCmultipiler"))
        self.label_90 = QtGui.QLabel(self.frameMOCmultipiler)
        self.label_90.setMinimumSize(QtCore.QSize(180, 0))
        self.label_90.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_90.setFont(font)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.hLayoutMOCmultipiler.addWidget(self.label_90)
        self.mocSpinBox = QtGui.QSpinBox(self.frameMOCmultipiler)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mocSpinBox.sizePolicy().hasHeightForWidth())
        self.mocSpinBox.setSizePolicy(sizePolicy)
        self.mocSpinBox.setMinimumSize(QtCore.QSize(72, 0))
        self.mocSpinBox.setMinimum(1)
        self.mocSpinBox.setObjectName(_fromUtf8("mocSpinBox"))
        self.hLayoutMOCmultipiler.addWidget(self.mocSpinBox)
        self.vl_gbParameters.addWidget(self.frameMOCmultipiler)
        self.chbDrawTolerance = QtGui.QCheckBox(self.gbParameters)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbDrawTolerance.setFont(font)
        self.chbDrawTolerance.setObjectName(_fromUtf8("chbDrawTolerance"))
        self.vl_gbParameters.addWidget(self.chbDrawTolerance)
        self.verticalLayout.addWidget(self.gbParameters)
        self.gbResults = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbResults.sizePolicy().hasHeightForWidth())
        self.gbResults.setSizePolicy(sizePolicy)
        self.gbResults.setObjectName(_fromUtf8("gbResults"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gbResults)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gbResultsWaypoint1 = QtGui.QGroupBox(self.gbResults)
        self.gbResultsWaypoint1.setObjectName(_fromUtf8("gbResultsWaypoint1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbResultsWaypoint1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_70 = QtGui.QFrame(self.gbResultsWaypoint1)
        self.frame_70.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_70.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_70.setObjectName(_fromUtf8("frame_70"))
        self.horizontalLayout_75 = QtGui.QHBoxLayout(self.frame_70)
        self.horizontalLayout_75.setSpacing(0)
        self.horizontalLayout_75.setMargin(0)
        self.horizontalLayout_75.setObjectName(_fromUtf8("horizontalLayout_75"))
        self.label_83 = QtGui.QLabel(self.frame_70)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_83.sizePolicy().hasHeightForWidth())
        self.label_83.setSizePolicy(sizePolicy)
        self.label_83.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_83.setFont(font)
        self.label_83.setFrameShadow(QtGui.QFrame.Plain)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.horizontalLayout_75.addWidget(self.label_83)
        self.txtXtt1 = QtGui.QLineEdit(self.frame_70)
        self.txtXtt1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtXtt1.sizePolicy().hasHeightForWidth())
        self.txtXtt1.setSizePolicy(sizePolicy)
        self.txtXtt1.setMinimumSize(QtCore.QSize(0, 0))
        self.txtXtt1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtXtt1.setFont(font)
        self.txtXtt1.setObjectName(_fromUtf8("txtXtt1"))
        self.horizontalLayout_75.addWidget(self.txtXtt1)
        self.verticalLayout_2.addWidget(self.frame_70)
        self.frame_71 = QtGui.QFrame(self.gbResultsWaypoint1)
        self.frame_71.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_71.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_71.setObjectName(_fromUtf8("frame_71"))
        self.horizontalLayout_76 = QtGui.QHBoxLayout(self.frame_71)
        self.horizontalLayout_76.setSpacing(0)
        self.horizontalLayout_76.setMargin(0)
        self.horizontalLayout_76.setObjectName(_fromUtf8("horizontalLayout_76"))
        self.label_84 = QtGui.QLabel(self.frame_71)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_84.sizePolicy().hasHeightForWidth())
        self.label_84.setSizePolicy(sizePolicy)
        self.label_84.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_84.setFont(font)
        self.label_84.setFrameShadow(QtGui.QFrame.Plain)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.horizontalLayout_76.addWidget(self.label_84)
        self.txtAtt1 = QtGui.QLineEdit(self.frame_71)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAtt1.sizePolicy().hasHeightForWidth())
        self.txtAtt1.setSizePolicy(sizePolicy)
        self.txtAtt1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAtt1.setFont(font)
        self.txtAtt1.setObjectName(_fromUtf8("txtAtt1"))
        self.horizontalLayout_76.addWidget(self.txtAtt1)
        self.verticalLayout_2.addWidget(self.frame_71)
        self.frame_72 = QtGui.QFrame(self.gbResultsWaypoint1)
        self.frame_72.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_72.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_72.setObjectName(_fromUtf8("frame_72"))
        self.horizontalLayout_77 = QtGui.QHBoxLayout(self.frame_72)
        self.horizontalLayout_77.setSpacing(0)
        self.horizontalLayout_77.setMargin(0)
        self.horizontalLayout_77.setObjectName(_fromUtf8("horizontalLayout_77"))
        self.label_85 = QtGui.QLabel(self.frame_72)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_85.sizePolicy().hasHeightForWidth())
        self.label_85.setSizePolicy(sizePolicy)
        self.label_85.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_85.setFont(font)
        self.label_85.setFrameShadow(QtGui.QFrame.Plain)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.horizontalLayout_77.addWidget(self.label_85)
        self.txtAsw1 = QtGui.QLineEdit(self.frame_72)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAsw1.sizePolicy().hasHeightForWidth())
        self.txtAsw1.setSizePolicy(sizePolicy)
        self.txtAsw1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAsw1.setFont(font)
        self.txtAsw1.setObjectName(_fromUtf8("txtAsw1"))
        self.horizontalLayout_77.addWidget(self.txtAsw1)
        self.verticalLayout_2.addWidget(self.frame_72)
        self.horizontalLayout.addWidget(self.gbResultsWaypoint1)
        self.gbResultsWaypoint2 = QtGui.QGroupBox(self.gbResults)
        self.gbResultsWaypoint2.setObjectName(_fromUtf8("gbResultsWaypoint2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbResultsWaypoint2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_73 = QtGui.QFrame(self.gbResultsWaypoint2)
        self.frame_73.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_73.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_73.setObjectName(_fromUtf8("frame_73"))
        self.horizontalLayout_78 = QtGui.QHBoxLayout(self.frame_73)
        self.horizontalLayout_78.setSpacing(0)
        self.horizontalLayout_78.setMargin(0)
        self.horizontalLayout_78.setObjectName(_fromUtf8("horizontalLayout_78"))
        self.label_86 = QtGui.QLabel(self.frame_73)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_86.sizePolicy().hasHeightForWidth())
        self.label_86.setSizePolicy(sizePolicy)
        self.label_86.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_86.setFont(font)
        self.label_86.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_86.setFrameShadow(QtGui.QFrame.Plain)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.horizontalLayout_78.addWidget(self.label_86)
        self.txtXtt2 = QtGui.QLineEdit(self.frame_73)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtXtt2.sizePolicy().hasHeightForWidth())
        self.txtXtt2.setSizePolicy(sizePolicy)
        self.txtXtt2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtXtt2.setFont(font)
        self.txtXtt2.setObjectName(_fromUtf8("txtXtt2"))
        self.horizontalLayout_78.addWidget(self.txtXtt2)
        self.verticalLayout_3.addWidget(self.frame_73)
        self.frame_74 = QtGui.QFrame(self.gbResultsWaypoint2)
        self.frame_74.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_74.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_74.setObjectName(_fromUtf8("frame_74"))
        self.horizontalLayout_79 = QtGui.QHBoxLayout(self.frame_74)
        self.horizontalLayout_79.setSpacing(0)
        self.horizontalLayout_79.setMargin(0)
        self.horizontalLayout_79.setObjectName(_fromUtf8("horizontalLayout_79"))
        self.label_87 = QtGui.QLabel(self.frame_74)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_87.sizePolicy().hasHeightForWidth())
        self.label_87.setSizePolicy(sizePolicy)
        self.label_87.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_87.setFont(font)
        self.label_87.setFrameShadow(QtGui.QFrame.Plain)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.horizontalLayout_79.addWidget(self.label_87)
        self.txtAtt2 = QtGui.QLineEdit(self.frame_74)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAtt2.sizePolicy().hasHeightForWidth())
        self.txtAtt2.setSizePolicy(sizePolicy)
        self.txtAtt2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAtt2.setFont(font)
        self.txtAtt2.setObjectName(_fromUtf8("txtAtt2"))
        self.horizontalLayout_79.addWidget(self.txtAtt2)
        self.verticalLayout_3.addWidget(self.frame_74)
        self.frame_75 = QtGui.QFrame(self.gbResultsWaypoint2)
        self.frame_75.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_75.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_75.setObjectName(_fromUtf8("frame_75"))
        self.horizontalLayout_80 = QtGui.QHBoxLayout(self.frame_75)
        self.horizontalLayout_80.setSpacing(0)
        self.horizontalLayout_80.setMargin(0)
        self.horizontalLayout_80.setObjectName(_fromUtf8("horizontalLayout_80"))
        self.label_88 = QtGui.QLabel(self.frame_75)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_88.sizePolicy().hasHeightForWidth())
        self.label_88.setSizePolicy(sizePolicy)
        self.label_88.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_88.setFont(font)
        self.label_88.setFrameShadow(QtGui.QFrame.Plain)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.horizontalLayout_80.addWidget(self.label_88)
        self.txtAsw2 = QtGui.QLineEdit(self.frame_75)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAsw2.sizePolicy().hasHeightForWidth())
        self.txtAsw2.setSizePolicy(sizePolicy)
        self.txtAsw2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAsw2.setFont(font)
        self.txtAsw2.setObjectName(_fromUtf8("txtAsw2"))
        self.horizontalLayout_80.addWidget(self.txtAsw2)
        self.verticalLayout_3.addWidget(self.frame_75)
        self.horizontalLayout.addWidget(self.gbResultsWaypoint2)
        self.verticalLayout.addWidget(self.gbResults)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.gbParameters.setTitle(_translate("Form", "Parameters", None))
        self.label_66.setText(_translate("Form", "RNAV Specification:", None))
        self.chbUse2Waypoints.setText(_translate("Form", "Use 2 Waypoints`", None))
        self.gbVorDmePosition.setTitle(_translate("Form", "VOR/DME Position", None))
        self.gbWaypoint1.setTitle(_translate("Form", "Waypoint 1", None))
        self.label_70.setText(_translate("Form", "Phase of Flight:", None))
        self.gbWaypoint2.setTitle(_translate("Form", "Waypoint 2", None))
        self.label_72.setText(_translate("Form", "Phase of Flight:", None))
        self.label_67.setText(_translate("Form", "Selection Mode:", None))
        self.label_77.setText(_translate("Form", "Altitude(ft):", None))
        self.txtAltitude.setText(_translate("Form", "1000", None))
        self.label_68.setText(_translate("Form", "Primary Moc(m):", None))
        self.txtPrimaryMoc.setText(_translate("Form", "300", None))
        self.label_89.setText(_translate("Form", "Construction Type:", None))
        self.label_90.setText(_translate("Form", "MOCmultiplier:", None))
        self.chbDrawTolerance.setText(_translate("Form", "Draw Waypoint Tolerance", None))
        self.gbResults.setTitle(_translate("Form", "Results", None))
        self.gbResultsWaypoint1.setTitle(_translate("Form", "Waypoint1", None))
        self.label_83.setText(_translate("Form", "XTT(nm):", None))
        self.txtXtt1.setText(_translate("Form", "0", None))
        self.label_84.setText(_translate("Form", "ATT(nm):", None))
        self.txtAtt1.setText(_translate("Form", "0", None))
        self.label_85.setText(_translate("Form", "1/2 A/W(nm):", None))
        self.txtAsw1.setText(_translate("Form", "0", None))
        self.gbResultsWaypoint2.setTitle(_translate("Form", "Waypoint2", None))
        self.label_86.setText(_translate("Form", "XTT(nm):", None))
        self.txtXtt2.setText(_translate("Form", "0", None))
        self.label_87.setText(_translate("Form", "ATT(nm):", None))
        self.txtAtt2.setText(_translate("Form", "0", None))
        self.label_88.setText(_translate("Form", "1/2 A/W(nm):", None))
        self.txtAsw2.setText(_translate("Form", "0", None))
        self.label_71.setText(_translate("Form", "Nominal Track ():", None))
        self.txtTrack.setText(_translate("Form", "0", None))

