# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HoldingVorDme.ui'
#
# Created: Wed Nov 25 14:56:58 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from FlightPlanner.Panels.TrackRadialBoxPanel import TrackRadialBoxPanel
from FlightPlanner.Panels.ComboBoxPanel import ComboBoxPanel

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HoldingVorDme(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(467, 556)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))

        self.gbVorDmePosition = QtGui.QGroupBox(Form)
        self.gbVorDmePosition.setObjectName(_fromUtf8("gbVorDmePosition"))
        self.vl_VorDmePosition = QtGui.QVBoxLayout(self.gbVorDmePosition)
        self.vl_VorDmePosition.setObjectName(_fromUtf8("vl_VorDmePosition"))
        self.verticalLayout.addWidget(self.gbVorDmePosition)

        self.cmbBasedOn = ComboBoxPanel(self.gbVorDmePosition, True)
        self.cmbBasedOn.Caption = "Based On"
        self.cmbBasedOn.LabelWidth = 120
        self.cmbBasedOn.Width = 120
        self.vl_VorDmePosition.addWidget(self.cmbBasedOn)

        self.gbParameters = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.gbParameters.setFont(font)
        self.gbParameters.setObjectName(_fromUtf8("gbParameters"))
        self.vl_gbParameters = QtGui.QVBoxLayout(self.gbParameters)
        self.vl_gbParameters.setObjectName(_fromUtf8("vl_gbParameters"))
        self.frameUsedFor = QtGui.QFrame(self.gbParameters)
        self.frameUsedFor.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameUsedFor.setFrameShadow(QtGui.QFrame.Raised)
        self.frameUsedFor.setObjectName(_fromUtf8("frameUsedFor"))
        self.horizontalLayout_58 = QtGui.QHBoxLayout(self.frameUsedFor)
        self.horizontalLayout_58.setSpacing(0)
        self.horizontalLayout_58.setMargin(0)
        self.horizontalLayout_58.setObjectName(_fromUtf8("horizontalLayout_58"))
        self.label_66 = QtGui.QLabel(self.frameUsedFor)
        self.label_66.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.horizontalLayout_58.addWidget(self.label_66)
        self.cmbUsedFor = QtGui.QComboBox(self.frameUsedFor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbUsedFor.sizePolicy().hasHeightForWidth())
        self.cmbUsedFor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbUsedFor.setFont(font)
        self.cmbUsedFor.setObjectName(_fromUtf8("cmbUsedFor"))
        self.cmbUsedFor.setMinimumSize(QtCore.QSize(80, 0))
        self.cmbUsedFor.setMaximumSize(QtCore.QSize(80, 16777215))
        self.horizontalLayout_58.addWidget(self.cmbUsedFor)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameUsedFor)
        self.frameType = QtGui.QFrame(self.gbParameters)
        self.frameType.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameType.setFrameShadow(QtGui.QFrame.Raised)
        self.frameType.setObjectName(_fromUtf8("frameType"))
        self.horizontalLayout_59 = QtGui.QHBoxLayout(self.frameType)
        self.horizontalLayout_59.setSpacing(0)
        self.horizontalLayout_59.setMargin(0)
        self.horizontalLayout_59.setObjectName(_fromUtf8("horizontalLayout_59"))
        self.label_67 = QtGui.QLabel(self.frameType)
        self.label_67.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.horizontalLayout_59.addWidget(self.label_67)
        self.cmbType = QtGui.QComboBox(self.frameType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbType.sizePolicy().hasHeightForWidth())
        self.cmbType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbType.setFont(font)
        self.cmbType.setObjectName(_fromUtf8("cmbType"))
        self.cmbType.setMinimumSize(QtCore.QSize(140, 0))
        self.cmbType.setMaximumSize(QtCore.QSize(140, 16777215))
        self.horizontalLayout_59.addWidget(self.cmbType)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameType)
        self.frameAircraftCategory = QtGui.QFrame(self.gbParameters)
        self.frameAircraftCategory.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAircraftCategory.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAircraftCategory.setObjectName(_fromUtf8("frameAircraftCategory"))
        self.horizontalLayout_61 = QtGui.QHBoxLayout(self.frameAircraftCategory)
        self.horizontalLayout_61.setSpacing(0)
        self.horizontalLayout_61.setMargin(0)
        self.horizontalLayout_61.setObjectName(_fromUtf8("horizontalLayout_61"))
        self.label_69 = QtGui.QLabel(self.frameAircraftCategory)
        self.label_69.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.horizontalLayout_61.addWidget(self.label_69)
        self.cmbAircraftCategory = QtGui.QComboBox(self.frameAircraftCategory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAircraftCategory.sizePolicy().hasHeightForWidth())
        self.cmbAircraftCategory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbAircraftCategory.setFont(font)
        self.cmbAircraftCategory.setObjectName(_fromUtf8("cmbAircraftCategory"))
        self.horizontalLayout_61.addWidget(self.cmbAircraftCategory)
        self.vl_gbParameters.addWidget(self.frameAircraftCategory)
        self.frameIas = QtGui.QFrame(self.gbParameters)
        self.frameIas.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameIas.setFrameShadow(QtGui.QFrame.Raised)
        self.frameIas.setObjectName(_fromUtf8("frameIas"))
        self.horizontalLayout_60 = QtGui.QHBoxLayout(self.frameIas)
        self.horizontalLayout_60.setSpacing(0)
        self.horizontalLayout_60.setMargin(0)
        self.horizontalLayout_60.setObjectName(_fromUtf8("horizontalLayout_60"))
        self.label_68 = QtGui.QLabel(self.frameIas)
        self.label_68.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_60.addWidget(self.label_68)
        self.txtIas = QtGui.QLineEdit(self.frameIas)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtIas.setFont(font)
        self.txtIas.setObjectName(_fromUtf8("txtIas"))
        self.txtIas.setMinimumSize(QtCore.QSize(60, 0))
        self.txtIas.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_60.addWidget(self.txtIas)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_60.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameIas)
        self.frameTas = QtGui.QFrame(self.gbParameters)
        self.frameTas.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameTas.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTas.setObjectName(_fromUtf8("frameTas"))
        self.horizontalLayout_68 = QtGui.QHBoxLayout(self.frameTas)
        self.horizontalLayout_68.setSpacing(0)
        self.horizontalLayout_68.setMargin(0)
        self.horizontalLayout_68.setObjectName(_fromUtf8("horizontalLayout_68"))
        self.label_76 = QtGui.QLabel(self.frameTas)
        self.label_76.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_76.setFont(font)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.horizontalLayout_68.addWidget(self.label_76)
        self.txtTas = QtGui.QLineEdit(self.frameTas)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtTas.setFont(font)
        self.txtTas.setText(_fromUtf8(""))
        self.txtTas.setObjectName(_fromUtf8("txtTas"))
        self.txtTas.setMinimumSize(QtCore.QSize(90, 0))
        self.txtTas.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_68.addWidget(self.txtTas)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_68.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameTas)
        self.frameAltitude = QtGui.QFrame(self.gbParameters)
        self.frameAltitude.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAltitude.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAltitude.setObjectName(_fromUtf8("frameAltitude"))
        self.horizontalLayout_69 = QtGui.QHBoxLayout(self.frameAltitude)
        self.horizontalLayout_69.setSpacing(0)
        self.horizontalLayout_69.setMargin(0)
        self.horizontalLayout_69.setObjectName(_fromUtf8("horizontalLayout_69"))
        self.label_77 = QtGui.QLabel(self.frameAltitude)
        self.label_77.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.horizontalLayout_69.addWidget(self.label_77)
        self.txtAltitudeM = QtGui.QLineEdit(self.frameAltitude)
        self.txtAltitudeM.setObjectName(_fromUtf8("txtAltitudeM"))
        self.txtAltitudeM.setMinimumSize(QtCore.QSize(90, 0))
        self.txtAltitudeM.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_69.addWidget(self.txtAltitudeM)
        self.label_2 = QtGui.QLabel(self.frameAltitude)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_69.addWidget(self.label_2)
        self.txtAltitude = QtGui.QLineEdit(self.frameAltitude)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitude.setFont(font)
        self.txtAltitude.setObjectName(_fromUtf8("txtAltitude"))
        self.txtAltitude.setMinimumSize(QtCore.QSize(90, 0))
        self.txtAltitude.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_69.addWidget(self.txtAltitude)
        self.label = QtGui.QLabel(self.frameAltitude)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_69.addWidget(self.label)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_69.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameAltitude)
        self.frameIsa = QtGui.QFrame(self.gbParameters)
        self.frameIsa.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameIsa.setFrameShadow(QtGui.QFrame.Raised)
        self.frameIsa.setObjectName(_fromUtf8("frameIsa"))
        self.horizontalLayout_72 = QtGui.QHBoxLayout(self.frameIsa)
        self.horizontalLayout_72.setSpacing(0)
        self.horizontalLayout_72.setMargin(0)
        self.horizontalLayout_72.setObjectName(_fromUtf8("horizontalLayout_72"))
        self.label_80 = QtGui.QLabel(self.frameIsa)
        self.label_80.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_80.setFont(font)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.horizontalLayout_72.addWidget(self.label_80)
        self.txtIsa = QtGui.QLineEdit(self.frameIsa)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtIsa.setFont(font)
        self.txtIsa.setObjectName(_fromUtf8("txtIsa"))
        self.txtIsa.setMinimumSize(QtCore.QSize(60, 0))
        self.txtIsa.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_72.addWidget(self.txtIsa)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_72.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameIsa)
        self.frameHoldingDme = QtGui.QFrame(self.gbParameters)
        self.frameHoldingDme.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameHoldingDme.setFrameShadow(QtGui.QFrame.Raised)
        self.frameHoldingDme.setObjectName(_fromUtf8("frameHoldingDme"))
        self.horizontalLayout_66 = QtGui.QHBoxLayout(self.frameHoldingDme)
        self.horizontalLayout_66.setSpacing(0)
        self.horizontalLayout_66.setMargin(0)
        self.horizontalLayout_66.setObjectName(_fromUtf8("horizontalLayout_66"))
        self.label_74 = QtGui.QLabel(self.frameHoldingDme)
        self.label_74.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_66.addWidget(self.label_74)
        self.frameTrack_4 = QtGui.QFrame(self.frameHoldingDme)
        self.frameTrack_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameTrack_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTrack_4.setObjectName(_fromUtf8("frameTrack_4"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.frameTrack_4)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.txtHoldingDme = QtGui.QLineEdit(self.frameTrack_4)
        self.txtHoldingDme.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtHoldingDme.setFont(font)
        self.txtHoldingDme.setObjectName(_fromUtf8("txtHoldingDme"))
        self.txtHoldingDme.setMinimumSize(QtCore.QSize(60, 0))
        self.txtHoldingDme.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_13.addWidget(self.txtHoldingDme)
        self.btnCaptureHoldingDme = QtGui.QToolButton(self.frameTrack_4)
        self.btnCaptureHoldingDme.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCaptureHoldingDme.setIcon(icon)
        self.btnCaptureHoldingDme.setObjectName(_fromUtf8("btnCaptureHoldingDme"))
        self.horizontalLayout_13.addWidget(self.btnCaptureHoldingDme)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(horizontalSpacer)
        self.horizontalLayout_66.addWidget(self.frameTrack_4)
        self.vl_gbParameters.addWidget(self.frameHoldingDme)
        self.frameLimitingDme = QtGui.QFrame(self.gbParameters)
        self.frameLimitingDme.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameLimitingDme.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLimitingDme.setObjectName(_fromUtf8("frameLimitingDme"))
        self.horizontalLayout_65 = QtGui.QHBoxLayout(self.frameLimitingDme)
        self.horizontalLayout_65.setSpacing(0)
        self.horizontalLayout_65.setMargin(0)
        self.horizontalLayout_65.setObjectName(_fromUtf8("horizontalLayout_65"))
        self.label_73 = QtGui.QLabel(self.frameLimitingDme)
        self.label_73.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.horizontalLayout_65.addWidget(self.label_73)
        self.frameTrack_3 = QtGui.QFrame(self.frameLimitingDme)
        self.frameTrack_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameTrack_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTrack_3.setObjectName(_fromUtf8("frameTrack_3"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.frameTrack_3)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.txtLimitingDme = QtGui.QLineEdit(self.frameTrack_3)
        self.txtLimitingDme.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtLimitingDme.setFont(font)
        self.txtLimitingDme.setObjectName(_fromUtf8("txtLimitingDme"))
        self.txtLimitingDme.setMinimumSize(QtCore.QSize(60, 0))
        self.txtLimitingDme.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_12.addWidget(self.txtLimitingDme)
        self.btnCaptureLimitingDme = QtGui.QToolButton(self.frameTrack_3)
        self.btnCaptureLimitingDme.setText(_fromUtf8(""))
        self.btnCaptureLimitingDme.setIcon(icon)
        self.btnCaptureLimitingDme.setObjectName(_fromUtf8("btnCaptureLimitingDme"))
        self.horizontalLayout_12.addWidget(self.btnCaptureLimitingDme)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(horizontalSpacer)
        self.horizontalLayout_65.addWidget(self.frameTrack_3)
        self.vl_gbParameters.addWidget(self.frameLimitingDme)
        self.frameMoc = QtGui.QFrame(self.gbParameters)
        self.frameMoc.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMoc.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMoc.setObjectName(_fromUtf8("frameMoc"))
        self.horizontalLayout_74 = QtGui.QHBoxLayout(self.frameMoc)
        self.horizontalLayout_74.setSpacing(0)
        self.horizontalLayout_74.setMargin(0)
        self.horizontalLayout_74.setObjectName(_fromUtf8("horizontalLayout_74"))
        self.label_82 = QtGui.QLabel(self.frameMoc)
        self.label_82.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_82.setFont(font)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.horizontalLayout_74.addWidget(self.label_82)
        self.txtMoc = QtGui.QLineEdit(self.frameMoc)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMoc.setFont(font)
        self.txtMoc.setObjectName(_fromUtf8("txtMoc"))
        self.txtMoc.setMinimumSize(QtCore.QSize(90, 0))
        self.txtMoc.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_74.addWidget(self.txtMoc)
        self.label_3 = QtGui.QLabel(self.frameMoc)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_74.addWidget(self.label_3)
        self.txtMocFt = QtGui.QLineEdit(self.frameMoc)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMocFt.setFont(font)
        self.txtMocFt.setText(_fromUtf8(""))
        self.txtMocFt.setObjectName(_fromUtf8("txtMocFt"))
        self.txtMocFt.setMinimumSize(QtCore.QSize(90, 0))
        self.txtMocFt.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_74.addWidget(self.txtMocFt)
        self.labelMocFt = QtGui.QLabel(self.frameMoc)
        self.labelMocFt.setObjectName(_fromUtf8("labelMocFt"))
        self.horizontalLayout_74.addWidget(self.labelMocFt)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_74.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameMoc)
        self.gbEntryAreas = QtGui.QGroupBox(self.gbParameters)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.gbEntryAreas.setFont(font)
        self.gbEntryAreas.setObjectName(_fromUtf8("gbEntryAreas"))
        self.vl_gbEntryAreas = QtGui.QVBoxLayout(self.gbEntryAreas)
        self.vl_gbEntryAreas.setObjectName(_fromUtf8("vl_gbEntryAreas"))
        self.frameEntryAreas = QtGui.QFrame(self.gbEntryAreas)
        self.frameEntryAreas.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameEntryAreas.setFrameShadow(QtGui.QFrame.Raised)
        self.frameEntryAreas.setObjectName(_fromUtf8("frameEntryAreas"))
        self.hl_EntryAreas = QtGui.QHBoxLayout(self.frameEntryAreas)
        self.hl_EntryAreas.setMargin(0)
        self.hl_EntryAreas.setObjectName(_fromUtf8("hl_EntryAreas"))
        self.chbSector1 = QtGui.QCheckBox(self.frameEntryAreas)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbSector1.setFont(font)
        self.chbSector1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chbSector1.setObjectName(_fromUtf8("chbSector1"))
        self.hl_EntryAreas.addWidget(self.chbSector1)
        self.chbSector2 = QtGui.QCheckBox(self.frameEntryAreas)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbSector2.setFont(font)
        self.chbSector2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chbSector2.setObjectName(_fromUtf8("chbSector2"))
        self.hl_EntryAreas.addWidget(self.chbSector2)
        self.chbReciprocalEntry = QtGui.QCheckBox(self.frameEntryAreas)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbReciprocalEntry.setFont(font)
        self.chbReciprocalEntry.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chbReciprocalEntry.setObjectName(_fromUtf8("chbReciprocalEntry"))
        self.hl_EntryAreas.addWidget(self.chbReciprocalEntry)

        self.chbLimitingRadial = QtGui.QCheckBox(self.frameEntryAreas)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbLimitingRadial.setFont(font)
        self.chbLimitingRadial.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chbLimitingRadial.setObjectName(_fromUtf8("chbLimitingRadial"))
        self.hl_EntryAreas.addWidget(self.chbLimitingRadial)

        self.vl_gbEntryAreas.addWidget(self.frameEntryAreas)
        self.vl_gbParameters.addWidget(self.gbEntryAreas)
        self.frameConstruction = QtGui.QFrame(self.gbParameters)
        self.frameConstruction.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameConstruction.setFrameShadow(QtGui.QFrame.Raised)
        self.frameConstruction.setObjectName(_fromUtf8("frameConstruction"))
        self.horizontalLayout_75 = QtGui.QHBoxLayout(self.frameConstruction)
        self.horizontalLayout_75.setSpacing(0)
        self.horizontalLayout_75.setMargin(0)
        self.horizontalLayout_75.setObjectName(_fromUtf8("horizontalLayout_75"))
        self.label_83 = QtGui.QLabel(self.frameConstruction)
        self.label_83.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_83.setFont(font)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.horizontalLayout_75.addWidget(self.label_83)
        self.cmbConstruction = QtGui.QComboBox(self.frameConstruction)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConstruction.sizePolicy().hasHeightForWidth())
        self.cmbConstruction.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbConstruction.setFont(font)
        self.cmbConstruction.setObjectName(_fromUtf8("cmbConstruction"))
        self.cmbConstruction.setMinimumSize(QtCore.QSize(60, 0))
        self.cmbConstruction.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_75.addWidget(self.cmbConstruction)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_75.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameConstruction)
        self.frameIas_2 = QtGui.QFrame(self.gbParameters)
        self.frameIas_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameIas_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frameIas_2.setObjectName(_fromUtf8("frameIas_2"))
        self.horizontalLayout_62 = QtGui.QHBoxLayout(self.frameIas_2)
        self.horizontalLayout_62.setSpacing(0)
        self.horizontalLayout_62.setMargin(0)
        self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        self.label_70 = QtGui.QLabel(self.frameIas_2)
        self.label_70.setMinimumSize(QtCore.QSize(120, 0))
        self.label_70.setMaximumSize(QtCore.QSize(120, 1221212))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.horizontalLayout_62.addWidget(self.label_70)
        self.spinBoxMocmulipiler = QtGui.QSpinBox(self.frameIas_2)
        self.spinBoxMocmulipiler.setProperty("value", 1)
        self.spinBoxMocmulipiler.setObjectName(_fromUtf8("spinBoxMocmulipiler"))
        self.spinBoxMocmulipiler.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBoxMocmulipiler.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_62.addWidget(self.spinBoxMocmulipiler)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_62.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameIas_2)
        self.verticalLayout.addWidget(self.gbParameters)
        self.gbOrientation = QtGui.QGroupBox(Form)
        self.gbOrientation.setObjectName(_fromUtf8("gbOrientation"))
        self.vl_gbOrientation = QtGui.QVBoxLayout(self.gbOrientation)
        self.vl_gbOrientation.setObjectName(_fromUtf8("vl_gbOrientation"))

        self.txtTrack = TrackRadialBoxPanel(self.gbOrientation)
        self.txtTrack.Caption = "In-bound Track"
        self.txtTrack.LabelWidth = 120
        self.vl_gbOrientation.addWidget(self.txtTrack)
        # self.frameTrackRoot = QtGui.QFrame(self.gbOrientation)
        # self.frameTrackRoot.setFrameShape(QtGui.QFrame.NoFrame)
        # self.frameTrackRoot.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameTrackRoot.setObjectName(_fromUtf8("frameTrackRoot"))
        # self.horizontalLayout_63 = QtGui.QHBoxLayout(self.frameTrackRoot)
        # self.horizontalLayout_63.setSpacing(0)
        # self.horizontalLayout_63.setMargin(0)
        # self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        # self.label_71 = QtGui.QLabel(self.frameTrackRoot)
        # self.label_71.setMinimumSize(QtCore.QSize(120, 0))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_71.setFont(font)
        # self.label_71.setObjectName(_fromUtf8("label_71"))
        # self.horizontalLayout_63.addWidget(self.label_71)
        # self.frameTrack = QtGui.QFrame(self.frameTrackRoot)
        # self.frameTrack.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frameTrack.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameTrack.setObjectName(_fromUtf8("frameTrack"))
        # self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frameTrack)
        # self.horizontalLayout_10.setSpacing(0)
        # self.horizontalLayout_10.setMargin(0)
        # self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        # self.txtTrack = QtGui.QLineEdit(self.frameTrack)
        # self.txtTrack.setEnabled(True)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.txtTrack.setFont(font)
        # self.txtTrack.setObjectName(_fromUtf8("txtTrack"))
        # self.horizontalLayout_10.addWidget(self.txtTrack)
        # self.btnCaptureTrack = QtGui.QToolButton(self.frameTrack)
        # self.btnCaptureTrack.setText(_fromUtf8(""))
        # self.btnCaptureTrack.setIcon(icon)
        # self.btnCaptureTrack.setObjectName(_fromUtf8("btnCaptureTrack"))
        # self.horizontalLayout_10.addWidget(self.btnCaptureTrack)
        # self.horizontalLayout_63.addWidget(self.frameTrack)
        # self.vl_gbOrientation.addWidget(self.frameTrackRoot)
        self.frameOrientation = QtGui.QFrame(self.gbOrientation)
        self.frameOrientation.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameOrientation.setFrameShadow(QtGui.QFrame.Raised)
        self.frameOrientation.setObjectName(_fromUtf8("frameOrientation"))
        self.horizontalLayout_67 = QtGui.QHBoxLayout(self.frameOrientation)
        self.horizontalLayout_67.setSpacing(0)
        self.horizontalLayout_67.setMargin(0)
        self.horizontalLayout_67.setObjectName(_fromUtf8("horizontalLayout_67"))
        self.label_75 = QtGui.QLabel(self.frameOrientation)
        self.label_75.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.horizontalLayout_67.addWidget(self.label_75)
        self.cmbOrientation = QtGui.QComboBox(self.frameOrientation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrientation.sizePolicy().hasHeightForWidth())
        self.cmbOrientation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbOrientation.setFont(font)
        self.cmbOrientation.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.cmbOrientation.setObjectName(_fromUtf8("cmbOrientation"))
        self.cmbOrientation.setMinimumSize(QtCore.QSize(70, 0))
        self.cmbOrientation.setMaximumSize(QtCore.QSize(70, 16777215))
        self.horizontalLayout_67.addWidget(self.cmbOrientation)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_67.addItem(horizontalSpacer)
        self.vl_gbOrientation.addWidget(self.frameOrientation)
        self.verticalLayout.addWidget(self.gbOrientation)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.gbVorDmePosition.setTitle(_translate("Form", "VOR/DME Position", None))
        self.gbParameters.setTitle(_translate("Form", "Parameters", None))
        self.label_66.setText(_translate("Form", "Used For:", None))
        self.label_67.setText(_translate("Form", "Type:", None))
        self.label_69.setText(_translate("Form", "Aircraft Category:", None))
        self.label_68.setText(_translate("Form", "IAS (kts):", None))
        self.txtIas.setText(_translate("Form", "230", None))
        self.label_76.setText(_translate("Form", "TAS (kts):", None))
        self.label_77.setText(_translate("Form", "Altitude:", None))
        self.label_2.setText(_translate("Form", "m", None))
        self.txtAltitude.setText(_translate("Form", "1000", None))
        self.label.setText(_translate("Form", "ft", None))
        self.label_80.setText(_translate("Form", "ISA (C):", None))
        self.txtIsa.setText(_translate("Form", "15", None))
        self.label_74.setText(_translate("Form", "Holding DME(nm):", None))
        self.txtHoldingDme.setText(_translate("Form", "3", None))
        self.label_73.setText(_translate("Form", "Limiting DME(nm):", None))
        self.txtLimitingDme.setText(_translate("Form", "10", None))
        self.label_82.setText(_translate("Form", "Moc:", None))
        self.txtMoc.setText(_translate("Form", "300", None))
        self.label_3.setText(_translate("Form", "m", None))
        self.labelMocFt.setText(_translate("Form", "ft", None))
        self.gbEntryAreas.setTitle(_translate("Form", "Entry Areas", None))
        self.chbSector1.setText(_translate("Form", "Sector 1 ", None))
        self.chbSector2.setText(_translate("Form", "Sector 2", None))
        self.chbReciprocalEntry.setText(_translate("Form", "Reciprocal Entry", None))
        self.label_83.setText(_translate("Form", "Construction Type:", None))
        self.label_70.setText(_translate("Form", "MOCmultipiler:", None))
        self.gbOrientation.setTitle(_translate("Form", "Orientation", None))
        # self.label_71.setText(_translate("Form", "In-bound Track ():", None))
        # self.txtTrack.setText(_translate("Form", "180", None))
        self.label_75.setText(_translate("Form", "Turns:", None))

