# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Licensing.ui'
#
# Created: Thu May 19 12:45:18 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from ctypes import windll
from Licensing.DlgLicenseValidation import DlgLicenseValidation
from FlightPlanner.Dialogs.DlgRequestActivationCode import DlgRequestActivationCode


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class DlgLicensing(QtGui.QDialog):
    def __init__(self, parent = None):
        QtGui.QDialog.__init__(self, parent)
        self.setObjectName(_fromUtf8("DlgLicensing"))
        self.setWindowTitle("FlightPlanner Licensing")
        self.resize(747, 388)
        self.setMinimumSize(QtCore.QSize(747, 450))
        self.setMaximumSize(QtCore.QSize(747, 450))
        self.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtGui.QVBoxLayout(self)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pnlHeader = QtGui.QFrame(self)
        self.pnlHeader.setMinimumSize(QtCore.QSize(742, 63))
        self.pnlHeader.setMaximumSize(QtCore.QSize(16777215, 63))
        self.pnlHeader.setStyleSheet(_fromUtf8("background-color: rgb(192, 187, 255);"))
        self.pnlHeader.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlHeader.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlHeader.setObjectName(_fromUtf8("pnlHeader"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pnlHeader)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelHeader = QtGui.QLabel(self.pnlHeader)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.labelHeader.setFont(font)
        self.labelHeader.setFrameShape(QtGui.QFrame.NoFrame)
        self.labelHeader.setFrameShadow(QtGui.QFrame.Plain)
        self.labelHeader.setObjectName(_fromUtf8("labelHeader"))
        self.verticalLayout_2.addWidget(self.labelHeader)
        self.verticalLayout.addWidget(self.pnlHeader)



        self.pnlBody = QtGui.QFrame(self)
        self.pnlBody.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlBody.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlBody.setObjectName(_fromUtf8("pnlBody"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pnlBody)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        verticalSpacer = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding);
        self.verticalLayout_3.addItem(verticalSpacer);
        self.frame = QtGui.QFrame(self.pnlBody)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labelHeader_2 = QtGui.QLabel(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelHeader_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.labelHeader_2.setFont(font)
        self.labelHeader_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeader_2.setObjectName(_fromUtf8("labelHeader_2"))
        self.verticalLayout_4.addWidget(self.labelHeader_2)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.pnlBody)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame_4 = QtGui.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.labelHeader_3 = QtGui.QLabel(self.frame_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelHeader_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.labelHeader_3.setFont(font)
        self.labelHeader_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeader_3.setObjectName(_fromUtf8("labelHeader_3"))
        self.verticalLayout_6.addWidget(self.labelHeader_3)
        self.frame_5 = QtGui.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.labelCreatedDate = QtGui.QLabel(self.frame_5)
        self.labelCreatedDate.setObjectName(_fromUtf8("labelCreatedDate"))
        self.verticalLayout_7.addWidget(self.labelCreatedDate)
        self.labelRemainingDays = QtGui.QLabel(self.frame_5)
        self.labelRemainingDays.setObjectName(_fromUtf8("labelRemainingDays"))
        self.verticalLayout_7.addWidget(self.labelRemainingDays)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame_4)
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.pnlBody)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btnActivate = QtGui.QPushButton(self.frame_3)
        self.btnActivate.setMinimumSize(QtCore.QSize(130, 0))
        self.btnActivate.setObjectName(_fromUtf8("btnActivate"))
        self.horizontalLayout_2.addWidget(self.btnActivate)
        self.btnRequest = QtGui.QPushButton(self.frame_3)
        self.btnRequest.setMinimumSize(QtCore.QSize(130, 0))
        self.btnRequest.setObjectName(_fromUtf8("btnRequest"))
        self.horizontalLayout_2.addWidget(self.btnRequest)
        self.btnBuy = QtGui.QPushButton(self.frame_3)
        self.btnBuy.setMinimumSize(QtCore.QSize(130, 0))
        self.btnBuy.setObjectName(_fromUtf8("btnBuy"))

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/buy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBuy.setIcon(icon)

        self.horizontalLayout_2.addWidget(self.btnBuy)
        spacerItem3 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.frame_3)

        verticalSpacer = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding);
        self.verticalLayout_3.addItem(verticalSpacer);

        self.verticalLayout.addWidget(self.pnlBody)
        self.pnlFooter = QtGui.QFrame(self)
        self.pnlFooter.setMinimumSize(QtCore.QSize(0, 40))
        self.pnlFooter.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pnlFooter.setStyleSheet(_fromUtf8("background-color: rgb(192, 187, 255);"))
        self.pnlFooter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlFooter.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlFooter.setObjectName(_fromUtf8("pnlFooter"))
        self.btnClose = QtGui.QPushButton(self.pnlFooter)
        self.btnClose.setGeometry(QtCore.QRect(666, 8, 75, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(209, 194, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 194, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 194, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnClose.setPalette(palette)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.btnHelp = QtGui.QPushButton(self.pnlFooter)
        self.btnHelp.setGeometry(QtCore.QRect(10, 10, 41, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 20, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 20, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnHelp.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.btnHelp.setFont(font)
        self.btnHelp.setFlat(True)
        self.btnHelp.setObjectName(_fromUtf8("btnHelp"))
        self.btnEndUserLicenceAgreement = QtGui.QPushButton(self.pnlFooter)
        self.btnEndUserLicenceAgreement.setGeometry(QtCore.QRect(60, 10, 190, 23))
        self.btnEndUserLicenceAgreement.setMinimumHeight(23)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 20, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 20, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnEndUserLicenceAgreement.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.btnEndUserLicenceAgreement.setFont(font)
        self.btnEndUserLicenceAgreement.setFlat(True)
        self.btnEndUserLicenceAgreement.setObjectName(_fromUtf8("btnEndUserLicenceAgreement"))
        self.verticalLayout.addWidget(self.pnlFooter)

        self.btnClose.clicked.connect(self.btnClose_clicked)
        self.btnActivate.clicked.connect(self.btnActivate_clicked)
        self.btnBuy.clicked.connect(self.btnBuy_clicked)
        self.btnHelp.clicked.connect(self.btnHelp_clicked)
        self.btnRequest.clicked.connect(self.btnRequest_clicked)
        self.btnEndUserLicenceAgreement.clicked.connect(self.btnEndUserLicenceAgreement_clicked)
        

        # self.btnRequest.setVisible(False)
        self.frame_2.setVisible(False)

        self.btnBuy.setMinimumWidth(130)
        self.btnActivate.setMinimumWidth(130)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.setWindowFlags(QtCore.Qt.SplashScreen)

        # dll = windll[r'E:\CholNam\FlightPlanner\Resource\dlls\SKGL.DLL']
        # result = dll.DllRegisterServer()
        # print result

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.labelHeader.setText(_translate("Form", "FlightPlanner Licensing", None))
        self.labelHeader_2.setText(_translate("Form", "Application is not activated.", None))
        self.labelHeader_3.setText(_translate("Form", "Application is activated.", None))
        self.labelCreatedDate.setText(_translate("Form", "CreatedDate : ", None))
        self.labelRemainingDays.setText(_translate("Form", "Remaining Days : ", None))
        self.btnActivate.setText(_translate("Form", "Activate this Application", None))
        self.btnRequest.setText(_translate("Form", "Request Activation Code", None))
        self.btnBuy.setText(_translate("Form", "Buy Application Code", None))
        self.btnHelp.setText(_translate("Form", "Help", None))
        self.btnEndUserLicenceAgreement.setText(_translate("Form", "End User Licence Agreement", None))
        self.btnClose.setText(_translate("Form", "Close", None))
    def btnHelp_clicked(self):
        path = "http://www.flightplanner.se/help.html"
        QtGui.QDesktopServices.openUrl(QtCore.QUrl(path))
    def btnEndUserLicenceAgreement_clicked(self):
        path = "http://www.flightplanner.se/eula.html"
        QtGui.QDesktopServices.openUrl(QtCore.QUrl(path))
    def btnClose_clicked(self):
        self.reject()
    def btnBuy_clicked(self):
        path = "http://www.flightplanner.se"
        QtGui.QDesktopServices.openUrl(QtCore.QUrl(path))
    def btnActivate_clicked(self):
        self.hide()
        validationDlg = DlgLicenseValidation(self)
        resultDlg = validationDlg.exec_()
        if resultDlg:
            self.accept()
        else:
            self.show()

    def btnRequest_clicked(self):
        dlgRequestActivationCode = DlgRequestActivationCode(self)
        dlgRequestActivationCode.exec_()
