# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_LicenseValidation.ui'
#
# Created: Mon May 30 09:30:22 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(747, 388)
        Form.setMinimumSize(QtCore.QSize(747, 388))
        Form.setMaximumSize(QtCore.QSize(747, 388))
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pnlHeader = QtGui.QFrame(Form)
        self.pnlHeader.setMinimumSize(QtCore.QSize(742, 63))
        self.pnlHeader.setMaximumSize(QtCore.QSize(16777215, 63))
        self.pnlHeader.setStyleSheet(_fromUtf8("background-color: rgb(192, 187, 255);"))
        self.pnlHeader.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlHeader.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlHeader.setObjectName(_fromUtf8("pnlHeader"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pnlHeader)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelHeader = QtGui.QLabel(self.pnlHeader)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.labelHeader.setFont(font)
        self.labelHeader.setFrameShape(QtGui.QFrame.NoFrame)
        self.labelHeader.setFrameShadow(QtGui.QFrame.Plain)
        self.labelHeader.setObjectName(_fromUtf8("labelHeader"))
        self.verticalLayout_2.addWidget(self.labelHeader)
        self.verticalLayout.addWidget(self.pnlHeader)
        self.pnlBody = QtGui.QFrame(Form)
        self.pnlBody.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlBody.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlBody.setObjectName(_fromUtf8("pnlBody"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pnlBody)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.frame_2 = QtGui.QFrame(self.pnlBody)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame_4 = QtGui.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.frame_6 = QtGui.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelHeader_3 = QtGui.QLabel(self.frame_6)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelHeader_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.labelHeader_3.setFont(font)
        self.labelHeader_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeader_3.setObjectName(_fromUtf8("labelHeader_3"))
        self.horizontalLayout_3.addWidget(self.labelHeader_3)
        self.inkWhatItIs = QtGui.QLabel(self.frame_6)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.inkWhatItIs.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(True)
        self.inkWhatItIs.setFont(font)
        self.inkWhatItIs.setObjectName(_fromUtf8("inkWhatItIs"))
        self.horizontalLayout_3.addWidget(self.inkWhatItIs)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.frame_5 = QtGui.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frame = QtGui.QFrame(self.frame_5)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.txtKeyPart1 = QtGui.QLineEdit(self.frame)
        self.txtKeyPart1.setObjectName(_fromUtf8("txtKeyPart1"))
        self.horizontalLayout_5.addWidget(self.txtKeyPart1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.txtKeyPart2 = QtGui.QLineEdit(self.frame)
        self.txtKeyPart2.setObjectName(_fromUtf8("txtKeyPart2"))
        self.horizontalLayout_5.addWidget(self.txtKeyPart2)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.txtKeyPart3 = QtGui.QLineEdit(self.frame)
        self.txtKeyPart3.setObjectName(_fromUtf8("txtKeyPart3"))
        self.horizontalLayout_5.addWidget(self.txtKeyPart3)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.btnActivateNow = QtGui.QLineEdit(self.frame)
        self.btnActivateNow.setObjectName(_fromUtf8("btnActivateNow"))
        self.horizontalLayout_5.addWidget(self.btnActivateNow)
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(160, 0))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout_7.addWidget(self.frame)
        self.label = QtGui.QLabel(self.frame_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_7.addWidget(self.label)
        self.frame_7 = QtGui.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lnkBuyActivationCode = QtGui.QLabel(self.frame_7)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lnkBuyActivationCode.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(True)
        self.lnkBuyActivationCode.setFont(font)
        self.lnkBuyActivationCode.setObjectName(_fromUtf8("lnkBuyActivationCode"))
        self.horizontalLayout_4.addWidget(self.lnkBuyActivationCode)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_7.addWidget(self.frame_7)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout_3.addWidget(self.frame_2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.pnlBody)
        self.pnlFooter = QtGui.QFrame(Form)
        self.pnlFooter.setMinimumSize(QtCore.QSize(0, 40))
        self.pnlFooter.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pnlFooter.setStyleSheet(_fromUtf8("background-color: rgb(192, 187, 255);"))
        self.pnlFooter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlFooter.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlFooter.setObjectName(_fromUtf8("pnlFooter"))
        self.btnClose = QtGui.QPushButton(self.pnlFooter)
        self.btnClose.setGeometry(QtCore.QRect(666, 8, 75, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnClose.setPalette(palette)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.btnHelp = QtGui.QPushButton(self.pnlFooter)
        self.btnHelp.setGeometry(QtCore.QRect(10, 10, 41, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 20, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 20, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnHelp.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.btnHelp.setFont(font)
        self.btnHelp.setFlat(True)
        self.btnHelp.setObjectName(_fromUtf8("btnHelp"))
        self.btnEndUserLicenceAgreement = QtGui.QPushButton(self.pnlFooter)
        self.btnEndUserLicenceAgreement.setGeometry(QtCore.QRect(60, 10, 171, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 20, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 20, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 187, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnEndUserLicenceAgreement.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.btnEndUserLicenceAgreement.setFont(font)
        self.btnEndUserLicenceAgreement.setFlat(True)
        self.btnEndUserLicenceAgreement.setObjectName(_fromUtf8("btnEndUserLicenceAgreement"))
        self.verticalLayout.addWidget(self.pnlFooter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.labelHeader.setText(_translate("Form", "FlightPlanner Licensing", None))
        self.labelHeader_3.setText(_translate("Form", "Enter activation code.", None))
        self.inkWhatItIs.setText(_translate("Form", "What it is?", None))
        self.label_2.setText(_translate("Form", "-", None))
        self.label_3.setText(_translate("Form", "-", None))
        self.label_4.setText(_translate("Form", "-", None))
        self.pushButton.setText(_translate("Form", "Activate this application", None))
        self.label.setText(_translate("Form", "    If you do not have an activation code, you can purchse on online store.", None))
        self.lnkBuyActivationCode.setText(_translate("Form", "Buy activation code", None))
        self.btnClose.setText(_translate("Form", "Close", None))
        self.btnHelp.setText(_translate("Form", "Help", None))
        self.btnEndUserLicenceAgreement.setText(_translate("Form", "End User Licence Agreement", None))

