# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EnrouteStraight.ui'
#
# Created: Thu Jul 30 14:07:22 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from FlightPlanner.Panels.ComboBoxPanel import ComboBoxPanel
from FlightPlanner.Panels.PositionPanel import PositionPanel
from FlightPlanner.Panels.OCAHPanel import OCAHPanel
from FlightPlanner.Panels.SpeedBoxPanel import SpeedBoxPanel, SpeedUnits, Speed
from FlightPlanner.Panels.DistanceBoxPanel import DistanceBoxPanel, DistanceUnits, Distance
from FlightPlanner.Panels.NumberBoxPanel import NumberBoxPanel
from FlightPlanner.Panels.TrackRadialBoxPanel import TrackRadialBoxPanel
from FlightPlanner.Panels.AltitudeBoxPanel import AltitudeBoxPanel, Altitude
from FlightPlanner.types import AltitudeUnits

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EnrouteStraight(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(442, 383)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))

        self.gbNavAid1 = QtGui.QGroupBox(Form)
        self.gbNavAid1.setObjectName(_fromUtf8("gbNavAid1"))
        self.verticalLayoutNavAid1 = QtGui.QVBoxLayout(self.gbNavAid1)
        self.verticalLayoutNavAid1.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayoutNavAid1.setObjectName(_fromUtf8("verticalLayoutNavAid1"))

        self.cmbNavAidType1 = ComboBoxPanel(self.gbNavAid1)
        self.cmbNavAidType1.Caption = "Type"
        self.cmbNavAidType1.LabelWidth = 120
        self.verticalLayoutNavAid1.addWidget(self.cmbNavAidType1)

        self.cmbBasedOn1 = ComboBoxPanel(self.gbNavAid1, True)
        self.cmbBasedOn1.Caption = "Based On"
        self.cmbBasedOn1.LabelWidth = 120
        self.cmbBasedOn1.Width = 120
        self.verticalLayoutNavAid1.addWidget(self.cmbBasedOn1)
        # self.frameNavAidType = QtGui.QFrame(self.gbNavAid1)
        # self.frameNavAidType.setFrameShape(QtGui.QFrame.NoFrame)
        # self.frameNavAidType.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameNavAidType.setObjectName(_fromUtf8("frameNavAidType"))
        # self.horizontalLayout_62 = QtGui.QHBoxLayout(self.frameNavAidType)
        # self.horizontalLayout_62.setSpacing(0)
        # self.horizontalLayout_62.setMargin(0)
        # self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        # self.label_70 = QtGui.QLabel(self.frameNavAidType)
        # self.label_70.setMinimumSize(QtCore.QSize(250, 0))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_70.setFont(font)
        # self.label_70.setObjectName(_fromUtf8("label_70"))
        # self.horizontalLayout_62.addWidget(self.label_70)
        # self.cmbNavAidType1 = QtGui.QComboBox(self.frameNavAidType)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.cmbNavAidType1.sizePolicy().hasHeightForWidth())
        # self.cmbNavAidType1.setSizePolicy(sizePolicy)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.cmbNavAidType1.setFont(font)
        # self.cmbNavAidType1.setObjectName(_fromUtf8("cmbNavAidType1"))
        # self.horizontalLayout_62.addWidget(self.cmbNavAidType1)
        # self.verticalLayoutNavAid1.addWidget(self.frameNavAidType)

        self.verticalLayout.addWidget(self.gbNavAid1)

        self.gbNavAid12 = QtGui.QGroupBox(Form)
        self.gbNavAid12.setObjectName(_fromUtf8("gbNavAid12"))
        self.verticalLayoutNavAid2 = QtGui.QVBoxLayout(self.gbNavAid12)
        self.verticalLayoutNavAid2.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayoutNavAid2.setObjectName(_fromUtf8("verticalLayoutNavAid2"))


        self.cmbNavAidType2 = ComboBoxPanel(self.gbNavAid12)
        self.cmbNavAidType2.Caption = "Type"
        self.cmbNavAidType2.LabelWidth = 120
        self.verticalLayoutNavAid2.addWidget(self.cmbNavAidType2)

        self.cmbBasedOn2 = ComboBoxPanel(self.gbNavAid12, True)
        self.cmbBasedOn2.Caption = "Based On"
        self.cmbBasedOn2.LabelWidth = 120
        self.cmbBasedOn2.Width = 120
        self.verticalLayoutNavAid2.addWidget(self.cmbBasedOn2)
        # self.frameNavAidType_3 = QtGui.QFrame(self.gbNavAid12)
        # self.frameNavAidType_3.setFrameShape(QtGui.QFrame.NoFrame)
        # self.frameNavAidType_3.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameNavAidType_3.setObjectName(_fromUtf8("frameNavAidType_3"))
        # self.horizontalLayout_64 = QtGui.QHBoxLayout(self.frameNavAidType_3)
        # self.horizontalLayout_64.setSpacing(0)
        # self.horizontalLayout_64.setMargin(0)
        # self.horizontalLayout_64.setObjectName(_fromUtf8("horizontalLayout_64"))
        # self.label_72 = QtGui.QLabel(self.frameNavAidType_3)
        # self.label_72.setMinimumSize(QtCore.QSize(250, 0))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_72.setFont(font)
        # self.label_72.setObjectName(_fromUtf8("label_72"))
        # self.horizontalLayout_64.addWidget(self.label_72)
        # self.cmbNavAidType2 = QtGui.QComboBox(self.frameNavAidType_3)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.cmbNavAidType2.sizePolicy().hasHeightForWidth())
        # self.cmbNavAidType2.setSizePolicy(sizePolicy)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.cmbNavAidType2.setFont(font)
        # self.cmbNavAidType2.setObjectName(_fromUtf8("cmbNavAidType2"))
        # self.horizontalLayout_64.addWidget(self.cmbNavAidType2)
        # self.verticalLayoutNavAid2.addWidget(self.frameNavAidType_3)
        self.verticalLayout.addWidget(self.gbNavAid12)
        self.gbParameters = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.gbParameters.setFont(font)
        self.gbParameters.setObjectName(_fromUtf8("gbParameters"))
        self.vl_gbParameters = QtGui.QVBoxLayout(self.gbParameters)
        self.vl_gbParameters.setObjectName(_fromUtf8("vl_gbParameters"))
        self.gbCOP = QtGui.QGroupBox(self.gbParameters)
        self.gbCOP.setObjectName(_fromUtf8("gbCOP"))
        self.verticalLayoutCOP = QtGui.QVBoxLayout(self.gbCOP)
        self.verticalLayoutCOP.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayoutCOP.setObjectName(_fromUtf8("verticalLayoutCOP"))
        self.lblNA = QtGui.QLabel(self.gbCOP)
        self.lblNA.setMinimumSize(QtCore.QSize(215, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblNA.setFont(font)
        self.lblNA.setText(_fromUtf8(""))
        self.lblNA.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNA.setObjectName(_fromUtf8("lblNA"))
        self.verticalLayoutCOP.addWidget(self.lblNA)
        self.frameCOP = QtGui.QFrame(self.gbCOP)
        self.frameCOP.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameCOP.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCOP.setObjectName(_fromUtf8("frameCOP"))
        self.horizontalLayout_65 = QtGui.QHBoxLayout(self.frameCOP)
        self.horizontalLayout_65.setSpacing(0)
        self.horizontalLayout_65.setMargin(0)
        self.horizontalLayout_65.setObjectName(_fromUtf8("horizontalLayout_65"))
        self.lblLeft = QtGui.QLabel(self.frameCOP)
        self.lblLeft.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblLeft.setFont(font)
        self.lblLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLeft.setObjectName(_fromUtf8("lblLeft"))
        self.horizontalLayout_65.addWidget(self.lblLeft)
        self.scrollBar = QtGui.QScrollBar(self.frameCOP)
        self.scrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar.setObjectName(_fromUtf8("scrollBar"))
        self.horizontalLayout_65.addWidget(self.scrollBar)
        self.lblRight = QtGui.QLabel(self.frameCOP)
        self.lblRight.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblRight.setFont(font)
        self.lblRight.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRight.setObjectName(_fromUtf8("lblRight"))
        self.horizontalLayout_65.addWidget(self.lblRight)
        self.verticalLayoutCOP.addWidget(self.frameCOP)
        self.vl_gbParameters.addWidget(self.gbCOP)

        self.txtPrimaryMoc = AltitudeBoxPanel(self.gbParameters)
        self.txtPrimaryMoc.Caption = "Primary Moc"
        self.txtPrimaryMoc.Value = Altitude(300)
        self.txtPrimaryMoc.LabelWidth = 120
        self.vl_gbParameters.addWidget(self.txtPrimaryMoc)
        # self.framePrimaryMoc = QtGui.QFrame(self.gbParameters)
        # self.framePrimaryMoc.setFrameShape(QtGui.QFrame.NoFrame)
        # self.framePrimaryMoc.setFrameShadow(QtGui.QFrame.Raised)
        # self.framePrimaryMoc.setObjectName(_fromUtf8("framePrimaryMoc"))
        # self.horizontalLayoutPrimaryMoc = QtGui.QHBoxLayout(self.framePrimaryMoc)
        # self.horizontalLayoutPrimaryMoc.setSpacing(0)
        # self.horizontalLayoutPrimaryMoc.setMargin(0)
        # self.horizontalLayoutPrimaryMoc.setObjectName(_fromUtf8("horizontalLayoutPrimaryMoc"))
        # self.label_82 = QtGui.QLabel(self.framePrimaryMoc)
        # self.label_82.setMinimumSize(QtCore.QSize(250, 0))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_82.setFont(font)
        # self.label_82.setObjectName(_fromUtf8("label_82"))
        # self.horizontalLayoutPrimaryMoc.addWidget(self.label_82)
        # self.txtPrimaryMoc = QtGui.QLineEdit(self.framePrimaryMoc)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.txtPrimaryMoc.setFont(font)
        # self.txtPrimaryMoc.setObjectName(_fromUtf8("txtPrimaryMoc"))
        # self.horizontalLayoutPrimaryMoc.addWidget(self.txtPrimaryMoc)
        # self.vl_gbParameters.addWidget(self.framePrimaryMoc)

        self.txtEnrouteAltitude = AltitudeBoxPanel(self.gbParameters)
        self.txtEnrouteAltitude.Caption = "Enroute Altitude"
        self.txtEnrouteAltitude.Value = Altitude(9000, AltitudeUnits.FT)
        self.txtEnrouteAltitude.LabelWidth = 120
        self.vl_gbParameters.addWidget(self.txtEnrouteAltitude)
        # self.frameEnrouteAltitude = QtGui.QFrame(self.gbParameters)
        # self.frameEnrouteAltitude.setFrameShape(QtGui.QFrame.NoFrame)
        # self.frameEnrouteAltitude.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameEnrouteAltitude.setObjectName(_fromUtf8("frameEnrouteAltitude"))
        # self.horizontalLayoutEnrouteAltitude = QtGui.QHBoxLayout(self.frameEnrouteAltitude)
        # self.horizontalLayoutEnrouteAltitude.setSpacing(0)
        # self.horizontalLayoutEnrouteAltitude.setMargin(0)
        # self.horizontalLayoutEnrouteAltitude.setObjectName(_fromUtf8("horizontalLayoutEnrouteAltitude"))
        # self.label_88 = QtGui.QLabel(self.frameEnrouteAltitude)
        # self.label_88.setMinimumSize(QtCore.QSize(250, 0))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_88.setFont(font)
        # self.label_88.setObjectName(_fromUtf8("label_88"))
        # self.horizontalLayoutEnrouteAltitude.addWidget(self.label_88)
        # self.txtEnrouteAltitude = QtGui.QLineEdit(self.frameEnrouteAltitude)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.txtEnrouteAltitude.setFont(font)
        # self.txtEnrouteAltitude.setObjectName(_fromUtf8("txtEnrouteAltitude"))
        # self.horizontalLayoutEnrouteAltitude.addWidget(self.txtEnrouteAltitude)
        # self.vl_gbParameters.addWidget(self.frameEnrouteAltitude)
        self.frameConstruction = QtGui.QFrame(self.gbParameters)
        self.frameConstruction.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameConstruction.setFrameShadow(QtGui.QFrame.Raised)
        self.frameConstruction.setObjectName(_fromUtf8("frameConstruction"))
        self.horizontalLayout_75 = QtGui.QHBoxLayout(self.frameConstruction)
        self.horizontalLayout_75.setSpacing(0)
        self.horizontalLayout_75.setMargin(0)
        self.horizontalLayout_75.setObjectName(_fromUtf8("horizontalLayout_75"))
        self.label_83 = QtGui.QLabel(self.frameConstruction)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_83.setFont(font)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.label_83.setMinimumSize(QtCore.QSize(120, 0))
        self.label_83.setMaximumSize(QtCore.QSize(120, 16777215))
        self.horizontalLayout_75.addWidget(self.label_83)
        self.cmbConstruction = QtGui.QComboBox(self.frameConstruction)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConstruction.sizePolicy().hasHeightForWidth())
        self.cmbConstruction.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbConstruction.setFont(font)
        self.cmbConstruction.setObjectName(_fromUtf8("cmbConstruction"))
        self.cmbConstruction.setMinimumSize(QtCore.QSize(60, 0))
        self.cmbConstruction.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_75.addWidget(self.cmbConstruction)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_75.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameConstruction)
        self.frameMOCmultipiler = QtGui.QFrame(self.gbParameters)
        self.frameMOCmultipiler.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMOCmultipiler.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMOCmultipiler.setObjectName(_fromUtf8("frameMOCmultipiler"))
        self.horizontalLayoutMOCmultipiler = QtGui.QHBoxLayout(self.frameMOCmultipiler)
        self.horizontalLayoutMOCmultipiler.setSpacing(0)
        self.horizontalLayoutMOCmultipiler.setMargin(0)
        self.horizontalLayoutMOCmultipiler.setObjectName(_fromUtf8("horizontalLayoutMOCmultipiler"))
        self.label_85 = QtGui.QLabel(self.frameMOCmultipiler)
        self.label_85.setMinimumSize(QtCore.QSize(120, 0))
        self.label_85.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_85.setFont(font)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.horizontalLayoutMOCmultipiler.addWidget(self.label_85)
        self.mocSpinBox = QtGui.QSpinBox(self.frameMOCmultipiler)
        self.mocSpinBox.setMinimum(1)
        self.mocSpinBox.setProperty("value", 1)
        self.mocSpinBox.setObjectName(_fromUtf8("mocSpinBox"))
        self.mocSpinBox.setMinimumSize(QtCore.QSize(60, 0))
        self.mocSpinBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayoutMOCmultipiler.addWidget(self.mocSpinBox)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutMOCmultipiler.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameMOCmultipiler)
        self.chbOverhead = QtGui.QCheckBox(self.gbParameters)
        self.chbOverhead.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbOverhead.setFont(font)
        self.chbOverhead.setObjectName(_fromUtf8("chbOverhead"))
        self.vl_gbParameters.addWidget(self.chbOverhead)
        self.verticalLayout.addWidget(self.gbParameters)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.gbNavAid1.setTitle(_translate("Form", "Navigational Aid 1", None))
        # self.label_70.setText(_translate("Form", "Type:", None))
        self.gbNavAid12.setTitle(_translate("Form", "Navigational Aid 2", None))
        # self.label_72.setText(_translate("Form", "Type:", None))
        self.gbParameters.setTitle(_translate("Form", "Parameters", None))
        self.gbCOP.setTitle(_translate("Form", "Change Over Point", None))
        self.lblLeft.setText(_translate("Form", "25nm", None))
        self.lblRight.setText(_translate("Form", "25nm", None))
        # self.label_82.setText(_translate("Form", "Primary Moc (m):", None))
        # self.txtPrimaryMoc.setText(_translate("Form", "300", None))
        # self.label_88.setText(_translate("Form", "Enroute Altitude(ft):", None))
        # self.txtEnrouteAltitude.setText(_translate("Form", "9000", None))
        self.label_83.setText(_translate("Form", "Construction Type:", None))
        self.label_85.setText(_translate("Form", "MOCmultipiler:", None))
        self.chbOverhead.setText(_translate("Form", "4nm overhead the VOR", None))

