# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaaCalc.ui'
#
# Created: Wed Jun 04 18:16:10 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_form_TAA(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(534, 485)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        Form.setFont(font)
        self.form = Form
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_1 = QtGui.QHBoxLayout()
        self.horizontalLayout_1.setObjectName(_fromUtf8("horizontalLayout_1"))
        self.frame_5 = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_1.addWidget(self.frame_5)
        self.frame_6 = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_1.addWidget(self.frame_6)
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame_3 = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)


        self.gbIAWP1 = QtGui.QGroupBox(Form)
        self.gbIAWP1.setObjectName(_fromUtf8("gbIAWP1"))
        self.vl_gbIAWP1 = QtGui.QVBoxLayout(self.gbIAWP1)
        self.vl_gbIAWP1.setObjectName(_fromUtf8("vl_gbIAWP1"))
        self.frame_TakeOffSurfaceTrack_3 = QtGui.QFrame(self.gbIAWP1)
        self.frame_TakeOffSurfaceTrack_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_TakeOffSurfaceTrack_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_TakeOffSurfaceTrack_3.setObjectName(_fromUtf8("frame_TakeOffSurfaceTrack_3"))
        self.horizontalLayout_65 = QtGui.QHBoxLayout(self.frame_TakeOffSurfaceTrack_3)
        self.horizontalLayout_65.setSpacing(0)
        self.horizontalLayout_65.setMargin(0)
        self.horizontalLayout_65.setObjectName(_fromUtf8("horizontalLayout_65"))
        self.label_73 = QtGui.QLabel(self.frame_TakeOffSurfaceTrack_3)
        self.label_73.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.horizontalLayout_65.addWidget(self.label_73)
        self.frame_APV_7 = QtGui.QFrame(self.frame_TakeOffSurfaceTrack_3)
        self.frame_APV_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_7.setObjectName(_fromUtf8("frame_APV_7"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.frame_APV_7)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.txtRadiusIAWP1 = QtGui.QLineEdit(self.frame_APV_7)
        self.txtRadiusIAWP1.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtRadiusIAWP1.setFont(font)
        self.txtRadiusIAWP1.setText(_fromUtf8(""))
        self.txtRadiusIAWP1.setObjectName(_fromUtf8("txtRadiusIAWP1"))
        self.horizontalLayout_11.addWidget(self.txtRadiusIAWP1)
        self.btnMeasureI1 = QtGui.QToolButton(self.frame_APV_7)
        self.btnMeasureI1.setText(_fromUtf8(""))
        self.btnMeasureI1.setIcon(icon)
        self.btnMeasureI1.setObjectName(_fromUtf8("btnMeasureI1"))
        self.horizontalLayout_11.addWidget(self.btnMeasureI1)
        self.horizontalLayout_65.addWidget(self.frame_APV_7)
        self.vl_gbIAWP1.addWidget(self.frame_TakeOffSurfaceTrack_3)
        self.horizontalLayout_4.addWidget(self.gbIAWP1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)


        self.gbIAWP3 = QtGui.QGroupBox(Form)
        self.gbIAWP3.setObjectName(_fromUtf8("gbIAWP3"))
        self.vl_gbIAWP3 = QtGui.QVBoxLayout(self.gbIAWP3)
        self.vl_gbIAWP3.setObjectName(_fromUtf8("vl_gbIAWP3"))
        self.frame_TakeOffSurfaceTrack_2 = QtGui.QFrame(self.gbIAWP3)
        self.frame_TakeOffSurfaceTrack_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_TakeOffSurfaceTrack_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_TakeOffSurfaceTrack_2.setObjectName(_fromUtf8("frame_TakeOffSurfaceTrack_2"))
        self.horizontalLayout_64 = QtGui.QHBoxLayout(self.frame_TakeOffSurfaceTrack_2)
        self.horizontalLayout_64.setSpacing(0)
        self.horizontalLayout_64.setMargin(0)
        self.horizontalLayout_64.setObjectName(_fromUtf8("horizontalLayout_64"))
        self.label_72 = QtGui.QLabel(self.frame_TakeOffSurfaceTrack_2)
        self.label_72.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.horizontalLayout_64.addWidget(self.label_72)
        self.frame_APV_6 = QtGui.QFrame(self.frame_TakeOffSurfaceTrack_2)
        self.frame_APV_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_6.setObjectName(_fromUtf8("frame_APV_6"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frame_APV_6)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.txtRadiusIAWP3 = QtGui.QLineEdit(self.frame_APV_6)
        self.txtRadiusIAWP3.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtRadiusIAWP3.setFont(font)
        self.txtRadiusIAWP3.setText(_fromUtf8(""))
        self.txtRadiusIAWP3.setObjectName(_fromUtf8("txtRadiusIAWP3"))
        self.horizontalLayout_10.addWidget(self.txtRadiusIAWP3)
        self.btnMeasureI3 = QtGui.QToolButton(self.frame_APV_6)
        self.btnMeasureI3.setText(_fromUtf8(""))
        self.btnMeasureI3.setIcon(icon)
        self.btnMeasureI3.setObjectName(_fromUtf8("btnMeasureI3"))
        self.horizontalLayout_10.addWidget(self.btnMeasureI3)
        self.horizontalLayout_64.addWidget(self.frame_APV_6)
        self.vl_gbIAWP3.addWidget(self.frame_TakeOffSurfaceTrack_2)
        self.horizontalLayout_4.addWidget(self.gbIAWP3)

        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.frame = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(100, 0))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_3.addWidget(self.frame)
        self.gbIAWP2 = QtGui.QGroupBox(Form)
        self.gbIAWP2.setObjectName(_fromUtf8("gbIAWP2"))
        self.vl_gbIAWP2 = QtGui.QVBoxLayout(self.gbIAWP2)
        self.vl_gbIAWP2.setObjectName(_fromUtf8("vl_gbIAWP2"))
        self.frame_TakeOffSurfaceTrack_4 = QtGui.QFrame(self.gbIAWP2)
        self.frame_TakeOffSurfaceTrack_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_TakeOffSurfaceTrack_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_TakeOffSurfaceTrack_4.setObjectName(_fromUtf8("frame_TakeOffSurfaceTrack_4"))
        self.horizontalLayout_66 = QtGui.QHBoxLayout(self.frame_TakeOffSurfaceTrack_4)
        self.horizontalLayout_66.setSpacing(0)
        self.horizontalLayout_66.setMargin(0)
        self.horizontalLayout_66.setObjectName(_fromUtf8("horizontalLayout_66"))
        self.label_74 = QtGui.QLabel(self.frame_TakeOffSurfaceTrack_4)
        self.label_74.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_66.addWidget(self.label_74)
        self.frame_APV_8 = QtGui.QFrame(self.frame_TakeOffSurfaceTrack_4)
        self.frame_APV_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_8.setObjectName(_fromUtf8("frame_APV_8"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.frame_APV_8)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.txtRadiusIAWP2 = QtGui.QLineEdit(self.frame_APV_8)
        self.txtRadiusIAWP2.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtRadiusIAWP2.setFont(font)
        self.txtRadiusIAWP2.setText(_fromUtf8(""))
        self.txtRadiusIAWP2.setObjectName(_fromUtf8("txtRadiusIAWP2"))
        self.horizontalLayout_12.addWidget(self.txtRadiusIAWP2)
        self.btnMeasureI2 = QtGui.QToolButton(self.frame_APV_8)
        self.btnMeasureI2.setText(_fromUtf8(""))
        self.btnMeasureI2.setIcon(icon)
        self.btnMeasureI2.setObjectName(_fromUtf8("btnMeasureI2"))
        self.horizontalLayout_12.addWidget(self.btnMeasureI2)
        self.horizontalLayout_66.addWidget(self.frame_APV_8)
        self.vl_gbIAWP2.addWidget(self.frame_TakeOffSurfaceTrack_4)
        self.horizontalLayout_4.insertWidget(1, self.gbIAWP2)
        self.frame_2 = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.gbIAWP3.setTitle(_translate("Form", "IAFL", None))
        self.label_72.setText(_translate("Form", "Step-down Radius (nm):", None))
        self.gbIAWP1.setTitle(_translate("Form", "IAFR", None))
        self.label_73.setText(_translate("Form", "Step-down Radius (nm):", None))
        self.gbIAWP2.setTitle(_translate("Form", "IAFC", None))
        self.label_74.setText(_translate("Form", "Step-down Radius (nm):", None))

