# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RnavNominal.ui'
#
# Created: Wed Feb 03 10:40:12 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from FlightPlanner.Panels.TrackRadialBoxPanel import TrackRadialBoxPanel

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RnavNominal(object):
    def setupUi(self, RnavNominal):
        RnavNominal.setObjectName(_fromUtf8("RnavNominal"))
        RnavNominal.resize(445, 714)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        RnavNominal.setFont(font)
        self.verticalLayout_2 = QtGui.QVBoxLayout(RnavNominal)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gbGeneral = QtGui.QGroupBox(RnavNominal)
        self.gbGeneral.setObjectName(_fromUtf8("gbGeneral"))
        self.vl_gbGeneral = QtGui.QVBoxLayout(self.gbGeneral)
        self.vl_gbGeneral.setObjectName(_fromUtf8("vl_gbGeneral"))
        self.frame_Type1_2 = QtGui.QFrame(self.gbGeneral)
        self.frame_Type1_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Type1_2.sizePolicy().hasHeightForWidth())
        self.frame_Type1_2.setSizePolicy(sizePolicy)
        self.frame_Type1_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Type1_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Type1_2.setObjectName(_fromUtf8("frame_Type1_2"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.frame_Type1_2)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setMargin(0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_13 = QtGui.QLabel(self.frame_Type1_2)
        self.label_13.setMinimumSize(QtCore.QSize(100, 0))
        self.label_13.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_21.addWidget(self.label_13)
        self.cmbPhaseOfFlight = QtGui.QComboBox(self.frame_Type1_2)
        self.cmbPhaseOfFlight.setMinimumSize(QtCore.QSize(120, 0))
        self.cmbPhaseOfFlight.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.cmbPhaseOfFlight.setFont(font)
        self.cmbPhaseOfFlight.setFrame(True)
        self.cmbPhaseOfFlight.setObjectName(_fromUtf8("cmbPhaseOfFlight"))
        self.horizontalLayout_21.addWidget(self.cmbPhaseOfFlight)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(horizontalSpacer)
        self.vl_gbGeneral.addWidget(self.frame_Type1_2)
        self.frame_DerAltitude = QtGui.QFrame(self.gbGeneral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_DerAltitude.sizePolicy().hasHeightForWidth())
        self.frame_DerAltitude.setSizePolicy(sizePolicy)
        self.frame_DerAltitude.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_DerAltitude.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_DerAltitude.setObjectName(_fromUtf8("frame_DerAltitude"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.frame_DerAltitude)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setMargin(0)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_14 = QtGui.QLabel(self.frame_DerAltitude)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(100, 0))
        self.label_14.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_29.addWidget(self.label_14)
        self.txtDerAltitude = QtGui.QLineEdit(self.frame_DerAltitude)
        self.txtDerAltitude.setEnabled(True)
        self.txtDerAltitude.setText(_fromUtf8(""))
        self.txtDerAltitude.setObjectName(_fromUtf8("txtDerAltitude"))
        self.txtDerAltitude.setMinimumSize(QtCore.QSize(90, 0))
        self.txtDerAltitude.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_29.addWidget(self.txtDerAltitude)
        self.label_25 = QtGui.QLabel(self.frame_DerAltitude)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_29.addWidget(self.label_25)
        self.txtDerAltitudeFt = QtGui.QLineEdit(self.frame_DerAltitude)
        self.txtDerAltitudeFt.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDerAltitudeFt.sizePolicy().hasHeightForWidth())
        self.txtDerAltitudeFt.setSizePolicy(sizePolicy)
        self.txtDerAltitudeFt.setMinimumSize(QtCore.QSize(90, 0))
        self.txtDerAltitudeFt.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtDerAltitudeFt.setFont(font)
        self.txtDerAltitudeFt.setObjectName(_fromUtf8("txtDerAltitudeFt"))
        self.horizontalLayout_29.addWidget(self.txtDerAltitudeFt)
        self.label_26 = QtGui.QLabel(self.frame_DerAltitude)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_29.addWidget(self.label_26)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(horizontalSpacer)
        self.vl_gbGeneral.addWidget(self.frame_DerAltitude)
        self.frame_Isa = QtGui.QFrame(self.gbGeneral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Isa.sizePolicy().hasHeightForWidth())
        self.frame_Isa.setSizePolicy(sizePolicy)
        self.frame_Isa.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Isa.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Isa.setObjectName(_fromUtf8("frame_Isa"))
        self.horizontalLayout_39 = QtGui.QHBoxLayout(self.frame_Isa)
        self.horizontalLayout_39.setSpacing(0)
        self.horizontalLayout_39.setMargin(0)
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.label_21 = QtGui.QLabel(self.frame_Isa)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(100, 0))
        self.label_21.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_39.addWidget(self.label_21)
        self.txtIsa = QtGui.QLineEdit(self.frame_Isa)
        self.txtIsa.setEnabled(True)
        self.txtIsa.setObjectName(_fromUtf8("txtIsa"))
        self.txtIsa.setMinimumSize(QtCore.QSize(60, 0))
        self.txtIsa.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_39.addWidget(self.txtIsa)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(horizontalSpacer)
        self.vl_gbGeneral.addWidget(self.frame_Isa)
        self.frame_Tas = QtGui.QFrame(self.gbGeneral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Tas.sizePolicy().hasHeightForWidth())
        self.frame_Tas.setSizePolicy(sizePolicy)
        self.frame_Tas.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Tas.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Tas.setObjectName(_fromUtf8("frame_Tas"))
        self.horizontalLayout_40 = QtGui.QHBoxLayout(self.frame_Tas)
        self.horizontalLayout_40.setSpacing(0)
        self.horizontalLayout_40.setMargin(0)
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.label_22 = QtGui.QLabel(self.frame_Tas)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(100, 0))
        self.label_22.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_40.addWidget(self.label_22)
        self.txtTas = QtGui.QLineEdit(self.frame_Tas)
        self.txtTas.setEnabled(False)
        self.txtTas.setObjectName(_fromUtf8("txtTas"))
        self.txtTas.setMinimumSize(QtCore.QSize(90, 0))
        self.txtTas.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_40.addWidget(self.txtTas)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(horizontalSpacer)
        self.vl_gbGeneral.addWidget(self.frame_Tas)
        self.pnlOptions = QtGui.QFrame(self.gbGeneral)
        self.pnlOptions.setMinimumSize(QtCore.QSize(150, 0))
        self.pnlOptions.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlOptions.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlOptions.setObjectName(_fromUtf8("pnlOptions"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.pnlOptions)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.chbUse2Waypoints = QtGui.QCheckBox(self.pnlOptions)
        self.chbUse2Waypoints.setChecked(True)
        self.chbUse2Waypoints.setObjectName(_fromUtf8("chbUse2Waypoints"))
        self.horizontalLayout_5.addWidget(self.chbUse2Waypoints)
        self.chbInsertSymbols = QtGui.QCheckBox(self.pnlOptions)
        self.chbInsertSymbols.setChecked(True)
        self.chbInsertSymbols.setObjectName(_fromUtf8("chbInsertSymbols"))
        self.horizontalLayout_5.addWidget(self.chbInsertSymbols)
        self.chbIAS = QtGui.QCheckBox(self.pnlOptions)
        self.chbIAS.setChecked(True)
        self.chbIAS.setObjectName(_fromUtf8("chbIAS"))
        self.horizontalLayout_5.addWidget(self.chbIAS)
        self.chbCatH = QtGui.QCheckBox(self.pnlOptions)
        self.chbCatH.setChecked(True)
        self.chbCatH.setObjectName(_fromUtf8("chbCatH"))
        self.horizontalLayout_5.addWidget(self.chbCatH)
        self.vl_gbGeneral.addWidget(self.pnlOptions)
        self.pnlWaypoint1_2 = QtGui.QFrame(self.gbGeneral)
        self.pnlWaypoint1_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlWaypoint1_2.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlWaypoint1_2.setObjectName(_fromUtf8("pnlWaypoint1_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.pnlWaypoint1_2)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.vl_gbGeneral.addWidget(self.pnlWaypoint1_2)
        self.verticalLayout_2.addWidget(self.gbGeneral)
        self.gbWaypoint1 = QtGui.QGroupBox(RnavNominal)
        self.gbWaypoint1.setObjectName(_fromUtf8("gbWaypoint1"))
        self.vl_gbWaypoint1 = QtGui.QVBoxLayout(self.gbWaypoint1)
        self.vl_gbWaypoint1.setObjectName(_fromUtf8("vl_gbWaypoint1"))
        self.frame_Type1 = QtGui.QFrame(self.gbWaypoint1)
        self.frame_Type1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Type1.sizePolicy().hasHeightForWidth())
        self.frame_Type1.setSizePolicy(sizePolicy)
        self.frame_Type1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Type1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Type1.setObjectName(_fromUtf8("frame_Type1"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.frame_Type1)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_11 = QtGui.QLabel(self.frame_Type1)
        self.label_11.setMinimumSize(QtCore.QSize(100, 0))
        self.label_11.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_19.addWidget(self.label_11)
        self.cmbType1 = QtGui.QComboBox(self.frame_Type1)
        self.cmbType1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.cmbType1.setFont(font)
        self.cmbType1.setFrame(True)
        self.cmbType1.setObjectName(_fromUtf8("cmbType1"))
        self.cmbType1.setMinimumSize(QtCore.QSize(90, 0))
        self.cmbType1.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_19.addWidget(self.cmbType1)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(horizontalSpacer)
        self.vl_gbWaypoint1.addWidget(self.frame_Type1)
        self.pnlWaypoint1 = QtGui.QFrame(self.gbWaypoint1)
        self.pnlWaypoint1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlWaypoint1.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlWaypoint1.setObjectName(_fromUtf8("pnlWaypoint1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.pnlWaypoint1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pnlAttL1 = QtGui.QFrame(self.pnlWaypoint1)
        self.pnlAttL1.setMinimumSize(QtCore.QSize(150, 0))
        self.pnlAttL1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlAttL1.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlAttL1.setObjectName(_fromUtf8("pnlAttL1"))
        self.vl_AttL1 = QtGui.QVBoxLayout(self.pnlAttL1)
        self.vl_AttL1.setSpacing(9)
        self.vl_AttL1.setMargin(9)
        self.vl_AttL1.setObjectName(_fromUtf8("vl_AttL1"))
        self.frame_Ias1 = QtGui.QFrame(self.pnlAttL1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Ias1.sizePolicy().hasHeightForWidth())
        self.frame_Ias1.setSizePolicy(sizePolicy)
        self.frame_Ias1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Ias1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Ias1.setObjectName(_fromUtf8("frame_Ias1"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.frame_Ias1)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setMargin(0)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_15 = QtGui.QLabel(self.frame_Ias1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(100, 0))
        self.label_15.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_31.addWidget(self.label_15)
        self.txtIas1 = QtGui.QLineEdit(self.frame_Ias1)
        self.txtIas1.setEnabled(True)
        self.txtIas1.setObjectName(_fromUtf8("txtIas1"))
        self.txtIas1.setMinimumSize(QtCore.QSize(60, 0))
        self.txtIas1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_31.addWidget(self.txtIas1)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(horizontalSpacer)
        self.vl_AttL1.addWidget(self.frame_Ias1)
        self.frame_Tas1 = QtGui.QFrame(self.pnlAttL1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Tas1.sizePolicy().hasHeightForWidth())
        self.frame_Tas1.setSizePolicy(sizePolicy)
        self.frame_Tas1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Tas1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Tas1.setObjectName(_fromUtf8("frame_Tas1"))
        self.horizontalLayout_37 = QtGui.QHBoxLayout(self.frame_Tas1)
        self.horizontalLayout_37.setSpacing(0)
        self.horizontalLayout_37.setMargin(0)
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_19 = QtGui.QLabel(self.frame_Tas1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(100, 0))
        self.label_19.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_37.addWidget(self.label_19)
        self.txtTas1 = QtGui.QLineEdit(self.frame_Tas1)
        self.txtTas1.setEnabled(False)
        self.txtTas1.setObjectName(_fromUtf8("txtTas1"))
        self.txtTas1.setMinimumSize(QtCore.QSize(90, 0))
        self.txtTas1.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_37.addWidget(self.txtTas1)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(horizontalSpacer)
        self.vl_AttL1.addWidget(self.frame_Tas1)
        self.frame_Altitude1 = QtGui.QFrame(self.pnlAttL1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Altitude1.sizePolicy().hasHeightForWidth())
        self.frame_Altitude1.setSizePolicy(sizePolicy)
        self.frame_Altitude1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Altitude1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Altitude1.setObjectName(_fromUtf8("frame_Altitude1"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.frame_Altitude1)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setMargin(0)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_4 = QtGui.QLabel(self.frame_Altitude1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_27.addWidget(self.label_4)
        self.txtAltitudeM1 = QtGui.QLineEdit(self.frame_Altitude1)
        self.txtAltitudeM1.setEnabled(True)
        self.txtAltitudeM1.setObjectName(_fromUtf8("txtAltitudeM1"))
        self.horizontalLayout_27.addWidget(self.txtAltitudeM1)
        self.label_5 = QtGui.QLabel(self.frame_Altitude1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_27.addWidget(self.label_5)
        self.txtAltitude1 = QtGui.QLineEdit(self.frame_Altitude1)
        self.txtAltitude1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAltitude1.sizePolicy().hasHeightForWidth())
        self.txtAltitude1.setSizePolicy(sizePolicy)
        self.txtAltitude1.setMinimumSize(QtCore.QSize(0, 0))
        self.txtAltitude1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitude1.setFont(font)
        self.txtAltitude1.setObjectName(_fromUtf8("txtAltitude1"))
        self.horizontalLayout_27.addWidget(self.txtAltitude1)
        self.label_6 = QtGui.QLabel(self.frame_Altitude1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_27.addWidget(self.label_6)
        self.vl_AttL1.addWidget(self.frame_Altitude1)
        self.frame_Bank1 = QtGui.QFrame(self.pnlAttL1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Bank1.sizePolicy().hasHeightForWidth())
        self.frame_Bank1.setSizePolicy(sizePolicy)
        self.frame_Bank1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Bank1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Bank1.setObjectName(_fromUtf8("frame_Bank1"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout(self.frame_Bank1)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setMargin(0)
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.label_17 = QtGui.QLabel(self.frame_Bank1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(100, 0))
        self.label_17.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_33.addWidget(self.label_17)
        self.txtBank1 = QtGui.QLineEdit(self.frame_Bank1)
        self.txtBank1.setEnabled(True)
        self.txtBank1.setObjectName(_fromUtf8("txtBank1"))
        self.txtBank1.setMinimumSize(QtCore.QSize(60, 0))
        self.txtBank1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_33.addWidget(self.txtBank1)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(horizontalSpacer)
        self.vl_AttL1.addWidget(self.frame_Bank1)
        self.horizontalLayout.addWidget(self.pnlAttL1)
        self.pnlAttR1 = QtGui.QFrame(self.pnlWaypoint1)
        self.pnlAttR1.setMinimumSize(QtCore.QSize(150, 0))
        self.pnlAttR1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlAttR1.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlAttR1.setObjectName(_fromUtf8("pnlAttR1"))
        self.vl_pnlAttR1 = QtGui.QVBoxLayout(self.pnlAttR1)
        self.vl_pnlAttR1.setObjectName(_fromUtf8("vl_pnlAttR1"))
        self.chbFirstWaypoint = QtGui.QCheckBox(self.pnlAttR1)
        self.chbFirstWaypoint.setChecked(True)
        self.chbFirstWaypoint.setObjectName(_fromUtf8("chbFirstWaypoint"))
        self.vl_pnlAttR1.addWidget(self.chbFirstWaypoint)
        self.horizontalLayout.addWidget(self.pnlAttR1)
        self.vl_gbWaypoint1.addWidget(self.pnlWaypoint1)
        self.verticalLayout_2.addWidget(self.gbWaypoint1)
        self.gbWaypoint2 = QtGui.QGroupBox(RnavNominal)
        self.gbWaypoint2.setObjectName(_fromUtf8("gbWaypoint2"))
        self.vl_gbWaypoint2 = QtGui.QVBoxLayout(self.gbWaypoint2)
        self.vl_gbWaypoint2.setObjectName(_fromUtf8("vl_gbWaypoint2"))
        self.frame_Type2 = QtGui.QFrame(self.gbWaypoint2)
        self.frame_Type2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Type2.sizePolicy().hasHeightForWidth())
        self.frame_Type2.setSizePolicy(sizePolicy)
        self.frame_Type2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Type2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Type2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Type2.setObjectName(_fromUtf8("frame_Type2"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.frame_Type2)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setMargin(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_12 = QtGui.QLabel(self.frame_Type2)
        self.label_12.setMinimumSize(QtCore.QSize(100, 0))
        self.label_12.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_20.addWidget(self.label_12)
        self.cmbType2 = QtGui.QComboBox(self.frame_Type2)
        self.cmbType2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.cmbType2.setFont(font)
        self.cmbType2.setFrame(True)
        self.cmbType2.setObjectName(_fromUtf8("cmbType2"))
        self.cmbType2.setMinimumSize(QtCore.QSize(90, 0))
        self.cmbType2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_20.addWidget(self.cmbType2)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(horizontalSpacer)
        self.vl_gbWaypoint2.addWidget(self.frame_Type2)
        self.pnlWaypoint2 = QtGui.QFrame(self.gbWaypoint2)
        self.pnlWaypoint2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlWaypoint2.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlWaypoint2.setObjectName(_fromUtf8("pnlWaypoint2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.pnlWaypoint2)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pnlAttL2 = QtGui.QFrame(self.pnlWaypoint2)
        self.pnlAttL2.setMinimumSize(QtCore.QSize(150, 0))
        self.pnlAttL2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlAttL2.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlAttL2.setObjectName(_fromUtf8("pnlAttL2"))
        self.vl_AttL1_2 = QtGui.QVBoxLayout(self.pnlAttL2)
        self.vl_AttL1_2.setSpacing(9)
        self.vl_AttL1_2.setMargin(9)
        self.vl_AttL1_2.setObjectName(_fromUtf8("vl_AttL1_2"))
        self.frame_Ias2 = QtGui.QFrame(self.pnlAttL2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Ias2.sizePolicy().hasHeightForWidth())
        self.frame_Ias2.setSizePolicy(sizePolicy)
        self.frame_Ias2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Ias2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Ias2.setObjectName(_fromUtf8("frame_Ias2"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout(self.frame_Ias2)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setMargin(0)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_16 = QtGui.QLabel(self.frame_Ias2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(100, 0))
        self.label_16.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_32.addWidget(self.label_16)
        self.txtIas2 = QtGui.QLineEdit(self.frame_Ias2)
        self.txtIas2.setEnabled(True)
        self.txtIas2.setObjectName(_fromUtf8("txtIas2"))
        self.txtIas2.setMinimumSize(QtCore.QSize(60, 0))
        self.txtIas2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_32.addWidget(self.txtIas2)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(horizontalSpacer)
        self.vl_AttL1_2.addWidget(self.frame_Ias2)
        self.frame_Tas2 = QtGui.QFrame(self.pnlAttL2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Tas2.sizePolicy().hasHeightForWidth())
        self.frame_Tas2.setSizePolicy(sizePolicy)
        self.frame_Tas2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Tas2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Tas2.setObjectName(_fromUtf8("frame_Tas2"))
        self.horizontalLayout_38 = QtGui.QHBoxLayout(self.frame_Tas2)
        self.horizontalLayout_38.setSpacing(0)
        self.horizontalLayout_38.setMargin(0)
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.label_20 = QtGui.QLabel(self.frame_Tas2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(100, 0))
        self.label_20.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_38.addWidget(self.label_20)
        self.txtTas2 = QtGui.QLineEdit(self.frame_Tas2)
        self.txtTas2.setEnabled(False)
        self.txtTas2.setObjectName(_fromUtf8("txtTas2"))
        self.txtTas2.setMinimumSize(QtCore.QSize(90, 0))
        self.txtTas2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalLayout_38.addWidget(self.txtTas2)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(horizontalSpacer)
        self.vl_AttL1_2.addWidget(self.frame_Tas2)
        self.frame_Altitude2 = QtGui.QFrame(self.pnlAttL2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Altitude2.sizePolicy().hasHeightForWidth())
        self.frame_Altitude2.setSizePolicy(sizePolicy)
        self.frame_Altitude2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Altitude2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Altitude2.setObjectName(_fromUtf8("frame_Altitude2"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.frame_Altitude2)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setMargin(0)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_7 = QtGui.QLabel(self.frame_Altitude2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_28.addWidget(self.label_7)
        self.txtAltitudeM2 = QtGui.QLineEdit(self.frame_Altitude2)
        self.txtAltitudeM2.setEnabled(True)
        self.txtAltitudeM2.setObjectName(_fromUtf8("txtAltitudeM2"))
        self.horizontalLayout_28.addWidget(self.txtAltitudeM2)
        self.label_8 = QtGui.QLabel(self.frame_Altitude2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_28.addWidget(self.label_8)
        self.txtAltitude2 = QtGui.QLineEdit(self.frame_Altitude2)
        self.txtAltitude2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAltitude2.sizePolicy().hasHeightForWidth())
        self.txtAltitude2.setSizePolicy(sizePolicy)
        self.txtAltitude2.setMinimumSize(QtCore.QSize(0, 0))
        self.txtAltitude2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitude2.setFont(font)
        self.txtAltitude2.setObjectName(_fromUtf8("txtAltitude2"))
        self.horizontalLayout_28.addWidget(self.txtAltitude2)
        self.label_9 = QtGui.QLabel(self.frame_Altitude2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_28.addWidget(self.label_9)
        self.vl_AttL1_2.addWidget(self.frame_Altitude2)
        self.frame_Bank2 = QtGui.QFrame(self.pnlAttL2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Bank2.sizePolicy().hasHeightForWidth())
        self.frame_Bank2.setSizePolicy(sizePolicy)
        self.frame_Bank2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Bank2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Bank2.setObjectName(_fromUtf8("frame_Bank2"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout(self.frame_Bank2)
        self.horizontalLayout_34.setSpacing(0)
        self.horizontalLayout_34.setMargin(0)
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_18 = QtGui.QLabel(self.frame_Bank2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(100, 0))
        self.label_18.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_34.addWidget(self.label_18)
        self.txtBank2 = QtGui.QLineEdit(self.frame_Bank2)
        self.txtBank2.setEnabled(True)
        self.txtBank2.setObjectName(_fromUtf8("txtBank2"))
        self.txtBank2.setMinimumSize(QtCore.QSize(60, 0))
        self.txtBank2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_34.addWidget(self.txtBank2)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(horizontalSpacer)
        self.vl_AttL1_2.addWidget(self.frame_Bank2)
        self.horizontalLayout_3.addWidget(self.pnlAttL2)
        self.pnlAttR2 = QtGui.QFrame(self.pnlWaypoint2)
        self.pnlAttR2.setMinimumSize(QtCore.QSize(150, 0))
        self.pnlAttR2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pnlAttR2.setFrameShadow(QtGui.QFrame.Raised)
        self.pnlAttR2.setObjectName(_fromUtf8("pnlAttR2"))
        self.vl_pnlAttR2 = QtGui.QVBoxLayout(self.pnlAttR2)
        self.vl_pnlAttR2.setObjectName(_fromUtf8("vl_pnlAttR2"))
        self.chbFirstWaypoint2 = QtGui.QCheckBox(self.pnlAttR2)
        self.chbFirstWaypoint2.setChecked(True)
        self.chbFirstWaypoint2.setObjectName(_fromUtf8("chbFirstWaypoint2"))
        self.vl_pnlAttR2.addWidget(self.chbFirstWaypoint2)
        self.horizontalLayout_3.addWidget(self.pnlAttR2)
        self.vl_gbWaypoint2.addWidget(self.pnlWaypoint2)
        self.verticalLayout_2.addWidget(self.gbWaypoint2)
        self.gbParameters = QtGui.QGroupBox(RnavNominal)
        self.gbParameters.setObjectName(_fromUtf8("gbParameters"))
        self.vl_gbParameters = QtGui.QVBoxLayout(self.gbParameters)
        self.vl_gbParameters.setObjectName(_fromUtf8("vl_gbParameters"))

        self.txtTrackTo = TrackRadialBoxPanel(self.gbParameters)
        self.txtTrackTo.Caption = "Track To Waypoint 1"
        self.txtTrackTo.LabelWidth = 150
        self.vl_gbParameters.addWidget(self.txtTrackTo)

        # self.pnlTrackTo = QtGui.QFrame(self.gbParameters)
        # self.pnlTrackTo.setFrameShape(QtGui.QFrame.NoFrame)
        # self.pnlTrackTo.setFrameShadow(QtGui.QFrame.Raised)
        # self.pnlTrackTo.setObjectName(_fromUtf8("pnlTrackTo"))
        # self.horizontalLayout_66 = QtGui.QHBoxLayout(self.pnlTrackTo)
        # self.horizontalLayout_66.setSpacing(0)
        # self.horizontalLayout_66.setMargin(0)
        # self.horizontalLayout_66.setObjectName(_fromUtf8("horizontalLayout_66"))
        # self.label_74 = QtGui.QLabel(self.pnlTrackTo)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.label_74.sizePolicy().hasHeightForWidth())
        # self.label_74.setSizePolicy(sizePolicy)
        # self.label_74.setMinimumSize(QtCore.QSize(150, 0))
        # self.label_74.setMaximumSize(QtCore.QSize(150, 16777215))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_74.setFont(font)
        # self.label_74.setObjectName(_fromUtf8("label_74"))
        # self.horizontalLayout_66.addWidget(self.label_74)
        # self.frame_APV_11 = QtGui.QFrame(self.pnlTrackTo)
        # self.frame_APV_11.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frame_APV_11.setFrameShadow(QtGui.QFrame.Raised)
        # self.frame_APV_11.setObjectName(_fromUtf8("frame_APV_11"))
        # self.horizontalLayout_15 = QtGui.QHBoxLayout(self.frame_APV_11)
        # self.horizontalLayout_15.setSpacing(0)
        # self.horizontalLayout_15.setMargin(0)
        # self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        # self.txtTrackTo = QtGui.QLineEdit(self.frame_APV_11)
        # self.txtTrackTo.setEnabled(True)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.txtTrackTo.setFont(font)
        # self.txtTrackTo.setObjectName(_fromUtf8("txtTrackTo"))
        # self.horizontalLayout_15.addWidget(self.txtTrackTo)
        # self.btnCaptureTrackTo = QtGui.QToolButton(self.frame_APV_11)
        # self.btnCaptureTrackTo.setText(_fromUtf8(""))
        # icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.btnCaptureTrackTo.setIcon(icon)
        # self.btnCaptureTrackTo.setObjectName(_fromUtf8("btnCaptureTrackTo"))
        # self.horizontalLayout_15.addWidget(self.btnCaptureTrackTo)
        # self.horizontalLayout_66.addWidget(self.frame_APV_11)
        # self.vl_gbParameters.addWidget(self.pnlTrackTo)


        self.txtTrackFrom = TrackRadialBoxPanel(self.gbParameters)
        self.txtTrackFrom.Caption = "Track From Waypoint 2"
        self.txtTrackFrom.LabelWidth = 150
        self.vl_gbParameters.addWidget(self.txtTrackFrom)
        # self.pnlTrackFrom = QtGui.QFrame(self.gbParameters)
        # self.pnlTrackFrom.setFrameShape(QtGui.QFrame.NoFrame)
        # self.pnlTrackFrom.setFrameShadow(QtGui.QFrame.Raised)
        # self.pnlTrackFrom.setObjectName(_fromUtf8("pnlTrackFrom"))
        # self.horizontalLayout_65 = QtGui.QHBoxLayout(self.pnlTrackFrom)
        # self.horizontalLayout_65.setSpacing(0)
        # self.horizontalLayout_65.setMargin(0)
        # self.horizontalLayout_65.setObjectName(_fromUtf8("horizontalLayout_65"))
        # self.label_73 = QtGui.QLabel(self.pnlTrackFrom)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.label_73.sizePolicy().hasHeightForWidth())
        # self.label_73.setSizePolicy(sizePolicy)
        # self.label_73.setMinimumSize(QtCore.QSize(150, 0))
        # self.label_73.setMaximumSize(QtCore.QSize(150, 16777215))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_73.setFont(font)
        # self.label_73.setObjectName(_fromUtf8("label_73"))
        # self.horizontalLayout_65.addWidget(self.label_73)
        # self.frame_Tra = QtGui.QFrame(self.pnlTrackFrom)
        # self.frame_Tra.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frame_Tra.setFrameShadow(QtGui.QFrame.Raised)
        # self.frame_Tra.setObjectName(_fromUtf8("frame_Tra"))
        # self.horizontalLayout_14 = QtGui.QHBoxLayout(self.frame_Tra)
        # self.horizontalLayout_14.setSpacing(0)
        # self.horizontalLayout_14.setMargin(0)
        # self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        # self.txtTrackFrom = QtGui.QLineEdit(self.frame_Tra)
        # self.txtTrackFrom.setEnabled(True)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.txtTrackFrom.setFont(font)
        # self.txtTrackFrom.setObjectName(_fromUtf8("txtTrackFrom"))
        # self.horizontalLayout_14.addWidget(self.txtTrackFrom)
        # self.btnCaptureTrackFrom = QtGui.QToolButton(self.frame_Tra)
        # self.btnCaptureTrackFrom.setText(_fromUtf8(""))
        # self.btnCaptureTrackFrom.setIcon(icon)
        # self.btnCaptureTrackFrom.setObjectName(_fromUtf8("btnCaptureTrackFrom"))
        # self.horizontalLayout_14.addWidget(self.btnCaptureTrackFrom)
        # self.horizontalLayout_65.addWidget(self.frame_Tra)
        # self.vl_gbParameters.addWidget(self.pnlTrackFrom)

        self.verticalLayout_2.addWidget(self.gbParameters)

        self.retranslateUi(RnavNominal)
        QtCore.QMetaObject.connectSlotsByName(RnavNominal)

    def retranslateUi(self, RnavNominal):
        RnavNominal.setWindowTitle(_translate("RnavNominal", "Form", None))
        self.gbGeneral.setTitle(_translate("RnavNominal", "General", None))
        self.label_13.setText(_translate("RnavNominal", "Phase of Flight:", None))
        self.label_14.setText(_translate("RnavNominal", "DER Altitude:", None))
        self.label_25.setText(_translate("RnavNominal", "m", None))
        self.txtDerAltitudeFt.setText(_translate("RnavNominal", "1000", None))
        self.label_26.setText(_translate("RnavNominal", "ft", None))
        self.label_21.setText(_translate("RnavNominal", "ISA (°):", None))
        self.txtIsa.setText(_translate("RnavNominal", "15", None))
        self.label_22.setText(_translate("RnavNominal", "TAS (kts):", None))
        self.chbUse2Waypoints.setText(_translate("RnavNominal", "Use 2 Waypoints", None))
        self.chbInsertSymbols.setText(_translate("RnavNominal", "Insert Symbol(s)", None))
        self.chbIAS.setText(_translate("RnavNominal", "IAS + 10%", None))
        self.chbCatH.setText(_translate("RnavNominal", "Cat. H", None))
        self.gbWaypoint1.setTitle(_translate("RnavNominal", "Waypoint 1", None))
        self.label_11.setText(_translate("RnavNominal", "Type:", None))
        self.label_15.setText(_translate("RnavNominal", "IAS (kts):", None))
        self.txtIas1.setText(_translate("RnavNominal", "220", None))
        self.label_19.setText(_translate("RnavNominal", "TAS (kts):", None))
        self.label_4.setText(_translate("RnavNominal", "Altitude:", None))
        self.label_5.setText(_translate("RnavNominal", "m", None))
        self.txtAltitude1.setText(_translate("RnavNominal", "3000", None))
        self.label_6.setText(_translate("RnavNominal", "ft", None))
        self.label_17.setText(_translate("RnavNominal", "Bank Angle (°):", None))
        self.txtBank1.setText(_translate("RnavNominal", "15", None))
        self.chbFirstWaypoint.setText(_translate("RnavNominal", "1st Waypoint", None))
        self.gbWaypoint2.setTitle(_translate("RnavNominal", "Waypoint 2", None))
        self.label_12.setText(_translate("RnavNominal", "Type:", None))
        self.label_16.setText(_translate("RnavNominal", "IAS (kts):", None))
        self.txtIas2.setText(_translate("RnavNominal", "220", None))
        self.label_20.setText(_translate("RnavNominal", "TAS (kts):", None))
        self.label_7.setText(_translate("RnavNominal", "Altitude:", None))
        self.label_8.setText(_translate("RnavNominal", "m", None))
        self.txtAltitude2.setText(_translate("RnavNominal", "3000", None))
        self.label_9.setText(_translate("RnavNominal", "ft", None))
        self.label_18.setText(_translate("RnavNominal", "Bank Angle (°):", None))
        self.txtBank2.setText(_translate("RnavNominal", "15", None))
        self.chbFirstWaypoint2.setText(_translate("RnavNominal", "1st Waypoint", None))
        self.gbParameters.setTitle(_translate("RnavNominal", "Parameters", None))
        # self.label_73.setText(_translate("RnavNominal", "Track From Waypoint 2(°):", None))
        # self.txtTrackFrom.setText(_translate("RnavNominal", "0", None))
        # self.label_74.setText(_translate("RnavNominal", "Track To Waypoint 1(°):", None))
        # self.txtTrackTo.setText(_translate("RnavNominal", "0", None))

