# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_SplitSector.ui'
#
# Created: Wed Jul 15 15:32:22 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SplitSector(object):
    def setupUi(self, ui_SplitSector):
        ui_SplitSector.setObjectName(_fromUtf8("ui_SplitSector"))
        ui_SplitSector.resize(338, 151)
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        
        self.verticalLayout = QtGui.QVBoxLayout(ui_SplitSector)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(ui_SplitSector)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_Length = QtGui.QFrame(self.frame)
        self.frame_Length.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_Length.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Length.setObjectName(_fromUtf8("frame_Length"))
        self.horizontalLayout_65 = QtGui.QHBoxLayout(self.frame_Length)
        self.horizontalLayout_65.setSpacing(0)
        self.horizontalLayout_65.setMargin(0)
        self.horizontalLayout_65.setObjectName(_fromUtf8("horizontalLayout_65"))
        self.label_73 = QtGui.QLabel(self.frame_Length)
        self.label_73.setMinimumSize(QtCore.QSize(150, 0))
        self.label_73.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.horizontalLayout_65.addWidget(self.label_73)
        self.frame_APV_8 = QtGui.QFrame(self.frame_Length)
        self.frame_APV_8.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_APV_8.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_APV_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_8.setObjectName(_fromUtf8("frame_APV_8"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.frame_APV_8)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.txtFrom = QtGui.QLineEdit(self.frame_APV_8)
        self.txtFrom.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtFrom.setFont(font)
        self.txtFrom.setObjectName(_fromUtf8("txtFrom"))
        self.horizontalLayout_12.addWidget(self.txtFrom)
        self.btnMeasureDegreeFrom = QtGui.QToolButton(self.frame_APV_8)
        self.btnMeasureDegreeFrom.setText(_fromUtf8(""))
        self.btnMeasureDegreeFrom.setIcon(icon)
        self.btnMeasureDegreeFrom.setObjectName(_fromUtf8("btnMeasureDegreeFrom"))
        self.horizontalLayout_12.addWidget(self.btnMeasureDegreeFrom)
        self.horizontalLayout_65.addWidget(self.frame_APV_8)
        self.verticalLayout_2.addWidget(self.frame_Length)
        self.frame_Length_2 = QtGui.QFrame(self.frame)
        self.frame_Length_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_Length_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Length_2.setObjectName(_fromUtf8("frame_Length_2"))
        self.horizontalLayout_66 = QtGui.QHBoxLayout(self.frame_Length_2)
        self.horizontalLayout_66.setSpacing(0)
        self.horizontalLayout_66.setMargin(0)
        self.horizontalLayout_66.setObjectName(_fromUtf8("horizontalLayout_66"))
        self.label_74 = QtGui.QLabel(self.frame_Length_2)
        self.label_74.setMinimumSize(QtCore.QSize(150, 0))
        self.label_74.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_66.addWidget(self.label_74)
        self.frame_APV_9 = QtGui.QFrame(self.frame_Length_2)
        self.frame_APV_9.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_APV_9.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_APV_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_9.setObjectName(_fromUtf8("frame_APV_9"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.frame_APV_9)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.txtTo = QtGui.QLineEdit(self.frame_APV_9)
        self.txtTo.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtTo.setFont(font)
        self.txtTo.setObjectName(_fromUtf8("txtTo"))
        self.horizontalLayout_13.addWidget(self.txtTo)
        self.btnMeasureDegreeTo = QtGui.QToolButton(self.frame_APV_9)
        self.btnMeasureDegreeTo.setText(_fromUtf8(""))
        self.btnMeasureDegreeTo.setIcon(icon)
        self.btnMeasureDegreeTo.setObjectName(_fromUtf8("btnMeasureDegreeTo"))
        self.horizontalLayout_13.addWidget(self.btnMeasureDegreeTo)
        self.horizontalLayout_66.addWidget(self.frame_APV_9)
        self.verticalLayout_2.addWidget(self.frame_Length_2)
        self.frame_Length_3 = QtGui.QFrame(self.frame)
        self.frame_Length_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_Length_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Length_3.setObjectName(_fromUtf8("frame_Length_3"))
        self.horizontalLayout_67 = QtGui.QHBoxLayout(self.frame_Length_3)
        self.horizontalLayout_67.setSpacing(0)
        self.horizontalLayout_67.setMargin(0)
        self.horizontalLayout_67.setObjectName(_fromUtf8("horizontalLayout_67"))
        self.label_75 = QtGui.QLabel(self.frame_Length_3)
        self.label_75.setMinimumSize(QtCore.QSize(150, 0))
        self.label_75.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.horizontalLayout_67.addWidget(self.label_75)
        self.frame_APV_10 = QtGui.QFrame(self.frame_Length_3)
        self.frame_APV_10.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_APV_10.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_APV_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_10.setObjectName(_fromUtf8("frame_APV_10"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.frame_APV_10)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.txtRadius = QtGui.QLineEdit(self.frame_APV_10)
        self.txtRadius.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtRadius.setFont(font)
        self.txtRadius.setObjectName(_fromUtf8("txtRadius"))
        self.horizontalLayout_14.addWidget(self.txtRadius)
        self.btnMeasureRadius = QtGui.QToolButton(self.frame_APV_10)
        self.btnMeasureRadius.setText(_fromUtf8(""))
        self.btnMeasureRadius.setIcon(icon)
        self.btnMeasureRadius.setObjectName(_fromUtf8("btnMeasureRadius"))
        self.horizontalLayout_14.addWidget(self.btnMeasureRadius)
        self.horizontalLayout_67.addWidget(self.frame_APV_10)
        self.verticalLayout_2.addWidget(self.frame_Length_3)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtGui.QDialogButtonBox(ui_SplitSector)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ui_SplitSector)
#         QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ui_SplitSector.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ui_SplitSector.reject)
        QtCore.QMetaObject.connectSlotsByName(ui_SplitSector)

    def retranslateUi(self, ui_SplitSector):
        ui_SplitSector.setWindowTitle(_translate("ui_SplitSector", "Split Sector", None))
        self.label_73.setText(_translate("ui_SplitSector", "From(°):", None))
        self.txtFrom.setText(_translate("ui_SplitSector", "", None))
        self.label_74.setText(_translate("ui_SplitSector", "TO(°):", None))
        self.txtTo.setText(_translate("ui_SplitSector", "", None))
        self.label_75.setText(_translate("ui_SplitSector", "Step-down Radius (nm):", None))
        self.txtRadius.setText(_translate("ui_SplitSector", "", None))

