# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OasDlg.ui'
#
# Created: Wed Apr 30 16:51:17 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from FlightPlanner.Panels.PositionPanel import PositionPanel
from FlightPlanner.Panels.TrackRadialBoxPanel import TrackRadialBoxPanel
from FlightPlanner.Panels.ComboBoxPanel import ComboBoxPanel
from FlightPlanner.Panels.OCAHPanel import OCAHPanel, AltitudeUnits, Altitude
from FlightPlanner.Panels.AltitudeBoxPanel import AltitudeBoxPanel
from FlightPlanner.Panels.NumberBoxPanel import NumberBoxPanel
from FlightPlanner.Panels.DistanceBoxPanel import Distance, DistanceBoxPanel, DistanceUnits
from FlightPlanner.Panels.TableViewObstacle import TableViewObstacle
import define

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OsaDlg(object):
    def setupUi(self, Dialog, catType):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(300, 300)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout_11 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.tabControls = QtGui.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.tabControls.setFont(font)
        self.tabControls.setAutoFillBackground(False)
        self.tabControls.setStyleSheet(_fromUtf8(""))
        self.tabControls.setObjectName(_fromUtf8("tabControls"))
        self.tab_General = QtGui.QWidget(Dialog)
        self.tab_General.setObjectName(_fromUtf8("tab_General"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.tab_General)
        self.horizontalLayout_29.setMargin(3)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))

        self.tabCtrlGeneral = QtGui.QTabWidget(self.tab_General)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.tabCtrlGeneral.setFont(font)
        self.tabCtrlGeneral.setAutoFillBackground(False)
        self.tabCtrlGeneral.setStyleSheet(_fromUtf8(""))
        self.tabCtrlGeneral.setObjectName(_fromUtf8("tabCtrlGeneral"))
        self.horizontalLayout_29.addWidget(self.tabCtrlGeneral)

        self.tabInputData = QtGui.QWidget(self.tabCtrlGeneral)
        self.tabInputData.setObjectName(_fromUtf8("tabInputData"))

        self.vLayoutTabInputData = QtGui.QVBoxLayout(self.tabInputData)
        self.vLayoutTabInputData.setMargin(3)
        self.vLayoutTabInputData.setObjectName(_fromUtf8("vLayoutTabInputData"))
        self.tabCtrlGeneral.addTab(self.tabInputData, "Input Data")

        self.tabOasIls = QtGui.QWidget(self.tabCtrlGeneral)
        self.tabOasIls.setObjectName(_fromUtf8("tabOasIls"))
        self.vLayoutTabOasIls = QtGui.QHBoxLayout(self.tabOasIls)
        self.vLayoutTabOasIls.setMargin(3)
        self.vLayoutTabOasIls.setObjectName(_fromUtf8("vLayoutTabOasIls"))
        if catType == "ILS":
            self.tabCtrlGeneral.addTab(self.tabOasIls, "OAS ILS")
        else:
            self.tabCtrlGeneral.addTab(self.tabOasIls, "OAS SBAS")



        self.groupBox_11 = QtGui.QGroupBox(self.tabInputData)
        self.groupBox_11.setTitle(_fromUtf8(""))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_5.setMargin(5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))

        self.cmbAerodrome = ComboBoxPanel(self.groupBox_11, True)
        self.cmbAerodrome.Caption = "Aerodrome"
        self.cmbAerodrome.LabelWidth = 120
        # self.cmbAerodrome.Editable = True
        self.verticalLayout_5.addWidget(self.cmbAerodrome)

        self.cmbRwyDir = ComboBoxPanel(self.groupBox_11, True)
        self.cmbRwyDir.Caption = "Runway Direction"
        self.cmbRwyDir.LabelWidth = 120
        self.cmbRwyDir.Width = 120
        self.verticalLayout_5.addWidget(self.cmbRwyDir)

        self.pnlThr = PositionPanel(self.groupBox_11)
        self.pnlThr.groupBox.setTitle("Threshold Position")
        self.pnlThr.btnCalculater.setVisible(False)
        self.verticalLayout_5.addWidget(self.pnlThr)

        self.pnlRwyEnd = PositionPanel(self.groupBox_11)
        self.pnlRwyEnd.groupBox.setTitle("Runway End Position")
        self.pnlRwyEnd.btnCalculater.setVisible(False)
        self.pnlRwyEnd.hideframe_Altitude()
        self.verticalLayout_5.addWidget(self.pnlRwyEnd)

        self.txtTrack = TrackRadialBoxPanel(self.groupBox_11)
        self.txtTrack.Caption = "In-Bound Track"
        self.txtTrack.LabelWidth = 120
        self.verticalLayout_5.addWidget(self.txtTrack)

        self.frame_37 = QtGui.QFrame(self.tabOasIls)
        self.frame_37.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_37.setObjectName(_fromUtf8("frame_37"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_37)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_20 = QtGui.QGroupBox(self.frame_37)
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_20)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))

        self.cmbSelectionMode = ComboBoxPanel(self.groupBox_20)
        self.cmbSelectionMode.Caption = "Selection Mode"
        self.verticalLayout_3.addWidget(self.cmbSelectionMode)



        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.txtOCAH = OCAHPanel(self.groupBox_20)
        self.txtOCAH.Value = Altitude(2000, AltitudeUnits.FT)
        self.verticalLayout_3.addWidget(self.txtOCAH)

        self.txtMOC = AltitudeBoxPanel(self.groupBox_20)
        self.txtMOC.Caption = "Intermediate Segment MOC"
        self.txtMOC.CaptionUnits = "m"
        self.txtMOC.Value = Altitude(150)
        self.verticalLayout_3.addWidget(self.txtMOC)

        self.cmbConstructionType = ComboBoxPanel(self.groupBox_20)
        self.cmbConstructionType.Caption = "Construction Type"
        self.verticalLayout_3.addWidget(self.cmbConstructionType)

        self.verticalLayout_2.addWidget(self.groupBox_20)
        self.groupBox_2 = QtGui.QGroupBox(self.frame_37)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_5 = QtGui.QFrame(self.groupBox_2)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame_6 = QtGui.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))

        self.cmbOasCategory = ComboBoxPanel(self.frame_6)
        self.cmbOasCategory.Caption = "Category"
        self.cmbOasCategory.LabelWidth = 150
        self.verticalLayout_9.addWidget(self.cmbOasCategory)

        self.cmbGPA = ComboBoxPanel(self.frame_6)
        self.cmbGPA.CaptionUnits = define._degreeStr
        self.cmbGPA.Caption = "Glide Path Angle"
        self.cmbGPA.LabelWidth = 150
        self.verticalLayout_9.addWidget(self.cmbGPA)

        self.cmbMACG = ComboBoxPanel(self.frame_6)
        self.cmbMACG.CaptionUnits = "%"
        self.cmbMACG.Caption = "MA Climb Gradient"
        self.cmbMACG.LabelWidth = 150
        self.verticalLayout_9.addWidget(self.cmbMACG)

        self.txtRDH = NumberBoxPanel(self.frame_6)
        self.txtRDH.CaptionUnits = "m"
        self.txtRDH.Caption = "RDH at Threshold"
        self.txtRDH.LabelWidth = 150
        self.txtRDH.Value = 15
        self.verticalLayout_9.addWidget(self.txtRDH)

        self.horizontalLayout.addWidget(self.frame_6)

        self.frame_7 = QtGui.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.frame_7)
        self.verticalLayout_13.setContentsMargins(9, -1, -1, 0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))

        self.txtCW = NumberBoxPanel(self.frame_7)
        self.txtCW.CaptionUnits = "m"
        self.txtCW.Caption = "LOC Course Width at THR"
        self.txtCW.LabelWidth = 175
        self.txtCW.Value = 210
        self.verticalLayout_13.addWidget(self.txtCW)

        self.txtDLT = DistanceBoxPanel(self.frame_7, DistanceUnits.M)
        self.txtDLT.Caption = "LOC to THR Distance"
        self.txtDLT.LabelWidth = 175
        self.txtDLT.Value = Distance(2000)
        self.verticalLayout_13.addWidget(self.txtDLT)

        self.txtContourHeight = NumberBoxPanel(self.frame_7)
        self.txtContourHeight.CaptionUnits = "m"
        self.txtContourHeight.Caption = "OCA Contour Height AGL"
        self.txtContourHeight.LabelWidth = 175
        self.txtContourHeight.Value = 300
        self.verticalLayout_13.addWidget(self.txtContourHeight)

        self.cmbMAMethod = ComboBoxPanel(self.frame_7)
        self.cmbMAMethod.Caption = "MA Obstacles Evaluation"
        self.cmbMAMethod.LabelWidth = 175
        self.verticalLayout_13.addWidget(self.cmbMAMethod)

        self.horizontalLayout.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_5)

        self.frame_4 = QtGui.QFrame(self.groupBox_2)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.frame_4)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.frame_8 = QtGui.QFrame(self.groupBox_3)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_14.setContentsMargins(6, 0, -1, -1)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))

        self.cmbAcCategory = ComboBoxPanel(self.frame_8)
        self.cmbAcCategory.Caption = "Category"
        self.cmbAcCategory.LabelWidth = 150
        self.verticalLayout_14.addWidget(self.cmbAcCategory)

        self.txtHL = NumberBoxPanel(self.frame_8)
        self.txtHL.CaptionUnits = "m"
        self.txtHL.Caption = "Height Loss"
        self.txtHL.LabelWidth = 150
        self.txtHL.Value = 40
        self.verticalLayout_14.addWidget(self.txtHL)

        self.horizontalLayout_6.addWidget(self.frame_8)
        self.frame_9 = QtGui.QFrame(self.groupBox_3)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.frame_9)
        self.verticalLayout_15.setContentsMargins(3, 0, -1, -1)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))

        self.txtWSS = NumberBoxPanel(self.frame_9, "0.0")
        self.txtWSS.CaptionUnits = "m"
        self.txtWSS.Caption = "Wing Semi Span"
        self.txtWSS.LabelWidth = 175
        self.txtWSS.Value = 30
        self.verticalLayout_15.addWidget(self.txtWSS)

        self.txtWH = NumberBoxPanel(self.frame_9, "0")
        self.txtWH.CaptionUnits = "m"
        self.txtWH.Caption = "Wheel Height"
        self.txtWH.LabelWidth = 175
        self.txtWH.Value = 6
        self.verticalLayout_15.addWidget(self.txtWH)

        self.horizontalLayout_6.addWidget(self.frame_9)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout.addWidget(self.frame_4)
        self.lblConstants = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lblConstants.setFont(font)
        self.lblConstants.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblConstants.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.lblConstants.setAlignment(QtCore.Qt.AlignCenter)
        self.lblConstants.setObjectName(_fromUtf8("lblConstants"))
        self.verticalLayout.addWidget(self.lblConstants)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.vLayoutTabOasIls.addWidget(self.frame_37)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.vLayoutTabInputData.addWidget(self.groupBox_11)
        self.frame_38 = QtGui.QFrame(self.tab_General)
        self.frame_38.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_38.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_38.setObjectName(_fromUtf8("frame_38"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_38)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.btnOpenData = QtGui.QPushButton(self.frame_38)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnOpenData.setFont(font)
        self.btnOpenData.setObjectName(_fromUtf8("btnOpenData"))
        self.verticalLayout_7.addWidget(self.btnOpenData)
        self.btnSaveData = QtGui.QPushButton(self.frame_38)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnSaveData.setFont(font)
        self.btnSaveData.setObjectName(_fromUtf8("btnSaveData"))
        self.verticalLayout_7.addWidget(self.btnSaveData)
        self.btnConstruct = QtGui.QPushButton(self.frame_38)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnConstruct.setFont(font)
        self.btnConstruct.setObjectName(_fromUtf8("btnConstruct"))
        self.verticalLayout_7.addWidget(self.btnConstruct)
        self.btnEvaluate = QtGui.QPushButton(self.frame_38)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnEvaluate.setFont(font)
        self.btnEvaluate.setObjectName(_fromUtf8("btnEvaluate"))
        self.verticalLayout_7.addWidget(self.btnEvaluate)
        self.btnUpdateQA = QtGui.QPushButton(self.frame_38)
        self.btnUpdateQA.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnUpdateQA.setFont(font)
        self.btnUpdateQA.setObjectName(_fromUtf8("btnUpdateQA"))
        self.verticalLayout_7.addWidget(self.btnUpdateQA)
        self.btnClose = QtGui.QPushButton(self.frame_38)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnClose.setFont(font)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.verticalLayout_7.addWidget(self.btnClose)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_29.addWidget(self.frame_38)
        self.tabControls.addTab(self.tab_General, _fromUtf8(""))
        self.tab_Results = QtGui.QWidget(Dialog)
        self.tab_Results.setObjectName(_fromUtf8("tab_Results"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_Results)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setMargin(3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.tab_Results)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setMargin(3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_32 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_32.setObjectName(_fromUtf8("groupBox_32"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_32)
        self.verticalLayout_16.setContentsMargins(-1, 0, -1, 3)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.frame_2 = QtGui.QFrame(self.groupBox_32)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_19.setMargin(0)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.frame_107 = QtGui.QFrame(self.frame_3)
        self.frame_107.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_107.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_107.setObjectName(_fromUtf8("frame_107"))
        self.horizontalLayout_94 = QtGui.QHBoxLayout(self.frame_107)
        self.horizontalLayout_94.setSpacing(0)
        self.horizontalLayout_94.setMargin(0)
        self.horizontalLayout_94.setObjectName(_fromUtf8("horizontalLayout_94"))
        self.label_115 = QtGui.QLabel(self.frame_107)
        self.label_115.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_115.setFont(font)
        self.label_115.setObjectName(_fromUtf8("label_115"))
        self.horizontalLayout_94.addWidget(self.label_115)
        self.txtID = QtGui.QLineEdit(self.frame_107)
        self.txtID.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtID.setFont(font)
        self.txtID.setText(_fromUtf8(""))
        self.txtID.setObjectName(_fromUtf8("txtID"))
        self.horizontalLayout_94.addWidget(self.txtID)
        self.verticalLayout_19.addWidget(self.frame_107)
        self.frame_109 = QtGui.QFrame(self.frame_3)
        self.frame_109.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_109.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_109.setObjectName(_fromUtf8("frame_109"))
        self.horizontalLayout_96 = QtGui.QHBoxLayout(self.frame_109)
        self.horizontalLayout_96.setSpacing(0)
        self.horizontalLayout_96.setMargin(0)
        self.horizontalLayout_96.setObjectName(_fromUtf8("horizontalLayout_96"))
        self.label_119 = QtGui.QLabel(self.frame_109)
        self.label_119.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_119.setFont(font)
        self.label_119.setObjectName(_fromUtf8("label_119"))
        self.horizontalLayout_96.addWidget(self.label_119)
        self.txtX = QtGui.QLineEdit(self.frame_109)
        self.txtX.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtX.setFont(font)
        self.txtX.setObjectName(_fromUtf8("txtX"))
        self.horizontalLayout_96.addWidget(self.txtX)
        self.verticalLayout_19.addWidget(self.frame_109)
        self.frame_110 = QtGui.QFrame(self.frame_3)
        self.frame_110.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_110.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_110.setObjectName(_fromUtf8("frame_110"))
        self.horizontalLayout_97 = QtGui.QHBoxLayout(self.frame_110)
        self.horizontalLayout_97.setSpacing(0)
        self.horizontalLayout_97.setMargin(0)
        self.horizontalLayout_97.setObjectName(_fromUtf8("horizontalLayout_97"))
        self.label_120 = QtGui.QLabel(self.frame_110)
        self.label_120.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_120.setFont(font)
        self.label_120.setObjectName(_fromUtf8("label_120"))
        self.horizontalLayout_97.addWidget(self.label_120)
        self.txtY = QtGui.QLineEdit(self.frame_110)
        self.txtY.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtY.setFont(font)
        self.txtY.setObjectName(_fromUtf8("txtY"))
        self.horizontalLayout_97.addWidget(self.txtY)
        self.verticalLayout_19.addWidget(self.frame_110)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.toolButton = QtGui.QToolButton(self.frame_2)
        self.toolButton.setMaximumSize(QtCore.QSize(25, 250))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/mActionZoomFullExtent.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon2)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_4.addWidget(self.toolButton)
        self.verticalLayout_16.addWidget(self.frame_2)
        self.frame_108 = QtGui.QFrame(self.groupBox_32)
        self.frame_108.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_108.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_108.setObjectName(_fromUtf8("frame_108"))
        self.horizontalLayout_95 = QtGui.QHBoxLayout(self.frame_108)
        self.horizontalLayout_95.setSpacing(0)
        self.horizontalLayout_95.setMargin(0)
        self.horizontalLayout_95.setObjectName(_fromUtf8("horizontalLayout_95"))
        self.label_116 = QtGui.QLabel(self.frame_108)
        self.label_116.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_116.setFont(font)
        self.label_116.setObjectName(_fromUtf8("label_116"))
        self.horizontalLayout_95.addWidget(self.label_116)
        self.txtAltitude = QtGui.QLineEdit(self.frame_108)
        self.txtAltitude.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitude.setFont(font)
        self.txtAltitude.setObjectName(_fromUtf8("txtAltitude"))
        self.horizontalLayout_95.addWidget(self.txtAltitude)
        self.label_117 = QtGui.QLabel(self.frame_108)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_117.setFont(font)
        self.label_117.setObjectName(_fromUtf8("label_117"))
        self.horizontalLayout_95.addWidget(self.label_117)
        self.txtAltitudeM = QtGui.QLineEdit(self.frame_108)
        self.txtAltitudeM.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitudeM.setFont(font)
        self.txtAltitudeM.setObjectName(_fromUtf8("txtAltitudeM"))
        self.horizontalLayout_95.addWidget(self.txtAltitudeM)
        self.label_118 = QtGui.QLabel(self.frame_108)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_118.setFont(font)
        self.label_118.setObjectName(_fromUtf8("label_118"))
        self.horizontalLayout_95.addWidget(self.label_118)
        self.verticalLayout_16.addWidget(self.frame_108)
        self.frame_111 = QtGui.QFrame(self.groupBox_32)
        self.frame_111.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_111.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_111.setObjectName(_fromUtf8("frame_111"))
        self.horizontalLayout_98 = QtGui.QHBoxLayout(self.frame_111)
        self.horizontalLayout_98.setSpacing(0)
        self.horizontalLayout_98.setMargin(0)
        self.horizontalLayout_98.setObjectName(_fromUtf8("horizontalLayout_98"))
        self.label_121 = QtGui.QLabel(self.frame_111)
        self.label_121.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_121.setFont(font)
        self.label_121.setObjectName(_fromUtf8("label_121"))
        self.horizontalLayout_98.addWidget(self.label_121)
        self.txtSurface = QtGui.QLineEdit(self.frame_111)
        self.txtSurface.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtSurface.setFont(font)
        self.txtSurface.setObjectName(_fromUtf8("txtSurface"))
        self.horizontalLayout_98.addWidget(self.txtSurface)
        self.verticalLayout_16.addWidget(self.frame_111)
        self.verticalLayout_6.addWidget(self.groupBox_32)
        self.groupBox_33 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_33.setObjectName(_fromUtf8("groupBox_33"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.groupBox_33)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setContentsMargins(-1, 0, -1, 3)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.frame_112 = QtGui.QFrame(self.groupBox_33)
        self.frame_112.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_112.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_112.setObjectName(_fromUtf8("frame_112"))
        self.horizontalLayout_99 = QtGui.QHBoxLayout(self.frame_112)
        self.horizontalLayout_99.setSpacing(0)
        self.horizontalLayout_99.setMargin(0)
        self.horizontalLayout_99.setObjectName(_fromUtf8("horizontalLayout_99"))
        self.label_122 = QtGui.QLabel(self.frame_112)
        self.label_122.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_122.setFont(font)
        self.label_122.setObjectName(_fromUtf8("label_122"))
        self.horizontalLayout_99.addWidget(self.label_122)
        self.cmbUnits = QtGui.QComboBox(self.frame_112)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbUnits.sizePolicy().hasHeightForWidth())
        self.cmbUnits.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.cmbUnits.setFont(font)
        self.cmbUnits.setEditable(False)
        self.cmbUnits.setObjectName(_fromUtf8("cmbUnits"))
        self.horizontalLayout_99.addWidget(self.cmbUnits)
        self.verticalLayout_17.addWidget(self.frame_112)
        self.frame_113 = QtGui.QFrame(self.groupBox_33)
        self.frame_113.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_113.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_113.setObjectName(_fromUtf8("frame_113"))
        self.horizontalLayout_100 = QtGui.QHBoxLayout(self.frame_113)
        self.horizontalLayout_100.setSpacing(0)
        self.horizontalLayout_100.setMargin(0)
        self.horizontalLayout_100.setObjectName(_fromUtf8("horizontalLayout_100"))
        self.txtOCH = QtGui.QLineEdit(self.frame_113)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtOCH.setFont(font)
        self.txtOCH.setObjectName(_fromUtf8("txtOCH"))
        self.horizontalLayout_100.addWidget(self.txtOCH)
        self.txtOCHResults = QtGui.QLineEdit(self.frame_113)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtOCHResults.setFont(font)
        self.txtOCHResults.setObjectName(_fromUtf8("txtOCHResults"))
        self.horizontalLayout_100.addWidget(self.txtOCHResults)
        self.verticalLayout_17.addWidget(self.frame_113)
        self.frame_114 = QtGui.QFrame(self.groupBox_33)
        self.frame_114.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_114.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_114.setObjectName(_fromUtf8("frame_114"))
        self.horizontalLayout_101 = QtGui.QHBoxLayout(self.frame_114)
        self.horizontalLayout_101.setSpacing(0)
        self.horizontalLayout_101.setMargin(0)
        self.horizontalLayout_101.setObjectName(_fromUtf8("horizontalLayout_101"))
        self.txtOCA = QtGui.QLineEdit(self.frame_114)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtOCA.setFont(font)
        self.txtOCA.setObjectName(_fromUtf8("txtOCA"))
        self.horizontalLayout_101.addWidget(self.txtOCA)
        self.txtOCAResults = QtGui.QLineEdit(self.frame_114)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtOCAResults.setFont(font)
        self.txtOCAResults.setObjectName(_fromUtf8("txtOCAResults"))
        self.horizontalLayout_101.addWidget(self.txtOCAResults)
        self.verticalLayout_17.addWidget(self.frame_114)
        self.frame_116 = QtGui.QFrame(self.groupBox_33)
        self.frame_116.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_116.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_116.setObjectName(_fromUtf8("frame_116"))
        self.horizontalLayout_103 = QtGui.QHBoxLayout(self.frame_116)
        self.horizontalLayout_103.setSpacing(0)
        self.horizontalLayout_103.setMargin(0)
        self.horizontalLayout_103.setObjectName(_fromUtf8("horizontalLayout_103"))
        self.txtOCA_2 = QtGui.QLineEdit(self.frame_116)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtOCA_2.setFont(font)
        self.txtOCA_2.setObjectName(_fromUtf8("txtOCA_2"))
        self.horizontalLayout_103.addWidget(self.txtOCA_2)
        self.txtResultSocText = QtGui.QLineEdit(self.frame_116)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtResultSocText.setFont(font)
        self.txtResultSocText.setObjectName(_fromUtf8("txtResultSocText"))
        self.horizontalLayout_103.addWidget(self.txtResultSocText)
        self.verticalLayout_17.addWidget(self.frame_116)
        self.verticalLayout_6.addWidget(self.groupBox_33)
        self.groupBox_34 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_34.setObjectName(_fromUtf8("groupBox_34"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.groupBox_34)
        self.verticalLayout_18.setContentsMargins(-1, 0, -1, 3)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.frame_115 = QtGui.QFrame(self.groupBox_34)
        self.frame_115.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_115.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_115.setObjectName(_fromUtf8("frame_115"))
        self.horizontalLayout_102 = QtGui.QHBoxLayout(self.frame_115)
        self.horizontalLayout_102.setSpacing(0)
        self.horizontalLayout_102.setMargin(0)
        self.horizontalLayout_102.setObjectName(_fromUtf8("horizontalLayout_102"))
        self.label_123 = QtGui.QLabel(self.frame_115)
        self.label_123.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_123.setFont(font)
        self.label_123.setObjectName(_fromUtf8("label_123"))
        self.horizontalLayout_102.addWidget(self.label_123)
        self.cmbSurface = QtGui.QComboBox(self.frame_115)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSurface.sizePolicy().hasHeightForWidth())
        self.cmbSurface.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.cmbSurface.setFont(font)
        self.cmbSurface.setObjectName(_fromUtf8("cmbSurface"))
        self.horizontalLayout_102.addWidget(self.cmbSurface)
        self.verticalLayout_18.addWidget(self.frame_115)
        self.tblObstacles = TableViewObstacle(self.groupBox_34)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.tblObstacles.setFont(font)
        self.tblObstacles.setObjectName(_fromUtf8("tblObstacles"))
        self.verticalLayout_18.addWidget(self.tblObstacles)
        self.verticalLayout_6.addWidget(self.groupBox_34)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.frame = QtGui.QFrame(self.tab_Results)
#         self.frame.setMinimumSize(QtCore.QSize(105, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.btnMarkSoc = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnMarkSoc.setFont(font)
        self.btnMarkSoc.setObjectName(_fromUtf8("btnMarkSoc"))
        self.verticalLayout_4.addWidget(self.btnMarkSoc)
        self.btnLocate = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnLocate.setFont(font)
        self.btnLocate.setObjectName(_fromUtf8("btnLocate"))
        self.verticalLayout_4.addWidget(self.btnLocate)
        self.btnUpdateQA_2 = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnUpdateQA_2.setFont(font)
        self.btnUpdateQA_2.setObjectName(_fromUtf8("btnUpdateQA_2"))
        self.verticalLayout_4.addWidget(self.btnUpdateQA_2)
        self.btnClose_2 = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnClose_2.setFont(font)
        self.btnClose_2.setObjectName(_fromUtf8("btnClose_2"))
        self.verticalLayout_4.addWidget(self.btnClose_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_3.addWidget(self.frame)
        self.tabControls.addTab(self.tab_Results, _fromUtf8(""))
        self.verticalLayout_11.addWidget(self.tabControls)

        self.retranslateUi(Dialog)
        self.tabControls.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/openData.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpenData.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/saveData.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveData.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/construct.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConstruct.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/evaluate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEvaluate.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/locate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLocate.setIcon(icon)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/pdtCheck.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.btnPDCheck.setIcon(icon)
        icon = QtGui.QIcon()        
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose_2.setIcon(icon)
        self.iconExport = QtGui.QIcon()        
        self.iconExport.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/exportResult.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.btnExportResult.setIcon(icon)
        self.iconMark = QtGui.QIcon()        
        self.iconMark.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/btnImage/locate0.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMarkSoc.setIcon(self.iconMark)
        
        self.btnClose.setToolTip(_fromUtf8("Close"))
        self.btnClose_2.setToolTip(_fromUtf8("Close"))
        self.btnConstruct.setToolTip(_fromUtf8("Construct"))
        self.btnEvaluate.setToolTip(_fromUtf8("Evaluate"))
        self.btnLocate.setToolTip(_fromUtf8("Locate"))
#         self.btnExportResult.setToolTip(_fromUtf8("Export Result"))
        self.btnOpenData.setToolTip(_fromUtf8("Open Data"))
        self.btnSaveData.setToolTip(_fromUtf8("Save Data"))
        self.btnMarkSoc.setToolTip(_fromUtf8("Mark SOC"))

        self.btnClose.setIconSize(QtCore.QSize(32,32))
        self.btnClose_2.setIconSize(QtCore.QSize(32,32))
        self.btnConstruct.setIconSize(QtCore.QSize(32,32))
        self.btnEvaluate.setIconSize(QtCore.QSize(32,32))
        self.btnLocate.setIconSize(QtCore.QSize(32,32))
        self.btnMarkSoc.setIconSize(QtCore.QSize(32,32))
        self.btnOpenData.setIconSize(QtCore.QSize(32,32))
        self.btnSaveData.setIconSize(QtCore.QSize(32,32))
        # self.btnPDTCheck.setIconSize(QtCore.QSize(32,32))

    def retranslateUi(self, Dialog):
        # Dialog.setWindowTitle(_translate("Dialog", "Obstacle Assessment Surfaces (OAS)", None))
        self.groupBox_20.setTitle(_translate("Dialog", "Parameters", None))

        self.groupBox_2.setTitle(_translate("Dialog", "Additional Parameters / Constants", None))
        # self.lblDLT.setText(_translate("Dialog", "LOC to THR Distance (m):", None))
        # self.txtDLT.setText(_translate("Dialog", "2000", None))
        # self.btnCaptureDLT.setText(_translate("Dialog", "...", None))
        # self.label_82.setText(_translate("Dialog", "OCA Contour Height AGL (m):", None))
        # self.txtContourHeight.setText(_translate("Dialog", "300", None))
        # self.label_83.setText(_translate("Dialog", "MA Obstacles Evaluation:", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Aircraft", None))
        # self.label_84.setText(_translate("Dialog", "Category:", None))
        # self.label_85.setText(_translate("Dialog", "Height Loss (m):", None))
        # self.txtHL.setText(_translate("Dialog", "40", None))
        # self.label_86.setText(_translate("Dialog", "Wing Semi Span (m):", None))
        # self.txtWSS.setText(_translate("Dialog", "30", None))
        # self.label_87.setText(_translate("Dialog", "Wheel Height (m):", None))
        # self.txtWH.setText(_translate("Dialog", "6", None))
        self.lblConstants.setText(_translate("Dialog", "Constants", None))
        self.tabControls.setTabText(self.tabControls.indexOf(self.tab_General), _translate("Dialog", "General", None))
        self.groupBox_32.setTitle(_translate("Dialog", "The Most Critical Obstacle", None))
        self.label_115.setText(_translate("Dialog", "ID:", None))
        self.label_119.setText(_translate("Dialog", "X:", None))
        self.label_120.setText(_translate("Dialog", "Y:", None))
        self.toolButton.setText(_translate("Dialog", "...", None))
        self.label_116.setText(_translate("Dialog", "Altitude:", None))
        self.label_117.setText(_translate("Dialog", " m ", None))
        self.label_118.setText(_translate("Dialog", "ft", None))
        self.label_121.setText(_translate("Dialog", "Surface:", None))
        self.groupBox_33.setTitle(_translate("Dialog", "Results", None))
        self.label_122.setText(_translate("Dialog", "Units:", None))
        self.txtOCH.setText(_translate("Dialog", "OCH", None))
        self.txtOCA.setText(_translate("Dialog", "OCA", None))
        self.txtOCA_2.setText(_translate("Dialog", "Start of Climb", None))
        self.groupBox_34.setTitle(_translate("Dialog", "Checked Ostacles", None))
        self.label_123.setText(_translate("Dialog", "Surface:", None))
#         self.btnMarkSoc.setText(_translate("Dialog", "Mark Soc", None))
#         self.btnLocate.setText(_translate("Dialog", "Locate", None))
#         self.btnUpdateQA_2.setText(_translate("Dialog", "Update QA", None))
#         self.btnClose_2.setText(_translate("Dialog", "Close", None))
        self.tabControls.setTabText(self.tabControls.indexOf(self.tab_Results), _translate("Dialog", "Results/Checked Obstacles", None))

