# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qgscomposeritemwidgetbase.ui'
#
# Created: Tue Sep 20 17:44:20 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QgsComposerItemWidgetBase(object):
    def setupUi(self, QgsComposerItemWidgetBase):
        QgsComposerItemWidgetBase.setObjectName(_fromUtf8("QgsComposerItemWidgetBase"))
        QgsComposerItemWidgetBase.resize(290, 847)
        self.verticalLayout_2 = QtGui.QVBoxLayout(QgsComposerItemWidgetBase)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mGeneralOptionsGroupBox = QgsCollapsibleGroupBoxBasic(QgsComposerItemWidgetBase)
        self.mGeneralOptionsGroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mGeneralOptionsGroupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mGeneralOptionsGroupBox.setProperty("collapsed", True)
        self.mGeneralOptionsGroupBox.setObjectName(_fromUtf8("mGeneralOptionsGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.mGeneralOptionsGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.mWidthLabel = QtGui.QLabel(self.mGeneralOptionsGroupBox)
        self.mWidthLabel.setObjectName(_fromUtf8("mWidthLabel"))
        self.gridLayout_3.addWidget(self.mWidthLabel, 3, 0, 1, 1)
        self.mXLabel = QtGui.QLabel(self.mGeneralOptionsGroupBox)
        self.mXLabel.setObjectName(_fromUtf8("mXLabel"))
        self.gridLayout_3.addWidget(self.mXLabel, 1, 0, 1, 1)
        self.mHeightLabel = QtGui.QLabel(self.mGeneralOptionsGroupBox)
        self.mHeightLabel.setObjectName(_fromUtf8("mHeightLabel"))
        self.gridLayout_3.addWidget(self.mHeightLabel, 4, 0, 1, 1)
        self.mYLabel = QtGui.QLabel(self.mGeneralOptionsGroupBox)
        self.mYLabel.setObjectName(_fromUtf8("mYLabel"))
        self.gridLayout_3.addWidget(self.mYLabel, 2, 0, 1, 1)
        self.mPageLabel = QtGui.QLabel(self.mGeneralOptionsGroupBox)
        self.mPageLabel.setObjectName(_fromUtf8("mPageLabel"))
        self.gridLayout_3.addWidget(self.mPageLabel, 0, 0, 1, 1)
        self.mXPositionDDBtn = QgsDataDefinedButton(self.mGeneralOptionsGroupBox)
        self.mXPositionDDBtn.setObjectName(_fromUtf8("mXPositionDDBtn"))
        self.gridLayout_3.addWidget(self.mXPositionDDBtn, 1, 3, 1, 1)
        self.mYPositionDDBtn = QgsDataDefinedButton(self.mGeneralOptionsGroupBox)
        self.mYPositionDDBtn.setObjectName(_fromUtf8("mYPositionDDBtn"))
        self.gridLayout_3.addWidget(self.mYPositionDDBtn, 2, 3, 1, 1)
        self.mWidthDDBtn = QgsDataDefinedButton(self.mGeneralOptionsGroupBox)
        self.mWidthDDBtn.setObjectName(_fromUtf8("mWidthDDBtn"))
        self.gridLayout_3.addWidget(self.mWidthDDBtn, 3, 3, 1, 1)
        self.mHeightDDBtn = QgsDataDefinedButton(self.mGeneralOptionsGroupBox)
        self.mHeightDDBtn.setObjectName(_fromUtf8("mHeightDDBtn"))
        self.gridLayout_3.addWidget(self.mHeightDDBtn, 4, 3, 1, 1)
        self.mPageSpinBox = QgsSpinBox(self.mGeneralOptionsGroupBox)
        self.mPageSpinBox.setMinimum(1)
        self.mPageSpinBox.setProperty("showClearButton", False)
        self.mPageSpinBox.setObjectName(_fromUtf8("mPageSpinBox"))
        self.gridLayout_3.addWidget(self.mPageSpinBox, 0, 1, 1, 3)
        self.mWidthSpin = QgsDoubleSpinBox(self.mGeneralOptionsGroupBox)
        self.mWidthSpin.setDecimals(3)
        self.mWidthSpin.setMaximum(9999999.0)
        self.mWidthSpin.setProperty("showClearButton", False)
        self.mWidthSpin.setObjectName(_fromUtf8("mWidthSpin"))
        self.gridLayout_3.addWidget(self.mWidthSpin, 3, 1, 1, 2)
        self.mHeightSpin = QgsDoubleSpinBox(self.mGeneralOptionsGroupBox)
        self.mHeightSpin.setDecimals(3)
        self.mHeightSpin.setMaximum(9999999.0)
        self.mHeightSpin.setProperty("showClearButton", False)
        self.mHeightSpin.setObjectName(_fromUtf8("mHeightSpin"))
        self.gridLayout_3.addWidget(self.mHeightSpin, 4, 1, 1, 2)
        self.mYPosSpin = QgsDoubleSpinBox(self.mGeneralOptionsGroupBox)
        self.mYPosSpin.setDecimals(3)
        self.mYPosSpin.setMinimum(-9999999.0)
        self.mYPosSpin.setMaximum(9999999.0)
        self.mYPosSpin.setProperty("showClearButton", False)
        self.mYPosSpin.setObjectName(_fromUtf8("mYPosSpin"))
        self.gridLayout_3.addWidget(self.mYPosSpin, 2, 1, 1, 2)
        self.mXPosSpin = QgsDoubleSpinBox(self.mGeneralOptionsGroupBox)
        self.mXPosSpin.setDecimals(3)
        self.mXPosSpin.setMinimum(-9999999.0)
        self.mXPosSpin.setMaximum(9999999.0)
        self.mXPosSpin.setProperty("showClearButton", False)
        self.mXPosSpin.setObjectName(_fromUtf8("mXPosSpin"))
        self.gridLayout_3.addWidget(self.mXPosSpin, 1, 1, 1, 2)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.gridLayout_3.setColumnStretch(3, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_2 = QtGui.QLabel(self.mGeneralOptionsGroupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mUpperMiddleCheckBox = QtGui.QCheckBox(self.mGeneralOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mUpperMiddleCheckBox.sizePolicy().hasHeightForWidth())
        self.mUpperMiddleCheckBox.setSizePolicy(sizePolicy)
        self.mUpperMiddleCheckBox.setText(_fromUtf8(""))
        self.mUpperMiddleCheckBox.setObjectName(_fromUtf8("mUpperMiddleCheckBox"))
        self.gridLayout.addWidget(self.mUpperMiddleCheckBox, 0, 1, 1, 1)
        self.mMiddleRightCheckBox = QtGui.QCheckBox(self.mGeneralOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mMiddleRightCheckBox.sizePolicy().hasHeightForWidth())
        self.mMiddleRightCheckBox.setSizePolicy(sizePolicy)
        self.mMiddleRightCheckBox.setText(_fromUtf8(""))
        self.mMiddleRightCheckBox.setObjectName(_fromUtf8("mMiddleRightCheckBox"))
        self.gridLayout.addWidget(self.mMiddleRightCheckBox, 1, 2, 1, 1)
        self.mMiddleCheckBox = QtGui.QCheckBox(self.mGeneralOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mMiddleCheckBox.sizePolicy().hasHeightForWidth())
        self.mMiddleCheckBox.setSizePolicy(sizePolicy)
        self.mMiddleCheckBox.setText(_fromUtf8(""))
        self.mMiddleCheckBox.setObjectName(_fromUtf8("mMiddleCheckBox"))
        self.gridLayout.addWidget(self.mMiddleCheckBox, 1, 1, 1, 1)
        self.mUpperRightCheckBox = QtGui.QCheckBox(self.mGeneralOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mUpperRightCheckBox.sizePolicy().hasHeightForWidth())
        self.mUpperRightCheckBox.setSizePolicy(sizePolicy)
        self.mUpperRightCheckBox.setText(_fromUtf8(""))
        self.mUpperRightCheckBox.setObjectName(_fromUtf8("mUpperRightCheckBox"))
        self.gridLayout.addWidget(self.mUpperRightCheckBox, 0, 2, 1, 1)
        self.mLowerMiddleCheckBox = QtGui.QCheckBox(self.mGeneralOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mLowerMiddleCheckBox.sizePolicy().hasHeightForWidth())
        self.mLowerMiddleCheckBox.setSizePolicy(sizePolicy)
        self.mLowerMiddleCheckBox.setText(_fromUtf8(""))
        self.mLowerMiddleCheckBox.setObjectName(_fromUtf8("mLowerMiddleCheckBox"))
        self.gridLayout.addWidget(self.mLowerMiddleCheckBox, 2, 1, 1, 1)
        self.mLowerRightCheckBox = QtGui.QCheckBox(self.mGeneralOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mLowerRightCheckBox.sizePolicy().hasHeightForWidth())
        self.mLowerRightCheckBox.setSizePolicy(sizePolicy)
        self.mLowerRightCheckBox.setText(_fromUtf8(""))
        self.mLowerRightCheckBox.setObjectName(_fromUtf8("mLowerRightCheckBox"))
        self.gridLayout.addWidget(self.mLowerRightCheckBox, 2, 2, 1, 1)
        self.mUpperLeftCheckBox = QtGui.QCheckBox(self.mGeneralOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mUpperLeftCheckBox.sizePolicy().hasHeightForWidth())
        self.mUpperLeftCheckBox.setSizePolicy(sizePolicy)
        self.mUpperLeftCheckBox.setText(_fromUtf8(""))
        self.mUpperLeftCheckBox.setObjectName(_fromUtf8("mUpperLeftCheckBox"))
        self.gridLayout.addWidget(self.mUpperLeftCheckBox, 0, 0, 1, 1)
        self.mLowerLeftCheckBox = QtGui.QCheckBox(self.mGeneralOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mLowerLeftCheckBox.sizePolicy().hasHeightForWidth())
        self.mLowerLeftCheckBox.setSizePolicy(sizePolicy)
        self.mLowerLeftCheckBox.setText(_fromUtf8(""))
        self.mLowerLeftCheckBox.setObjectName(_fromUtf8("mLowerLeftCheckBox"))
        self.gridLayout.addWidget(self.mLowerLeftCheckBox, 2, 0, 1, 1)
        self.mMiddleLeftCheckBox = QtGui.QCheckBox(self.mGeneralOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mMiddleLeftCheckBox.sizePolicy().hasHeightForWidth())
        self.mMiddleLeftCheckBox.setSizePolicy(sizePolicy)
        self.mMiddleLeftCheckBox.setText(_fromUtf8(""))
        self.mMiddleLeftCheckBox.setObjectName(_fromUtf8("mMiddleLeftCheckBox"))
        self.gridLayout.addWidget(self.mMiddleLeftCheckBox, 1, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addWidget(self.mGeneralOptionsGroupBox)
        self.mTransformsGroupBox = QgsCollapsibleGroupBoxBasic(QgsComposerItemWidgetBase)
        self.mTransformsGroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mTransformsGroupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mTransformsGroupBox.setProperty("collapsed", True)
        self.mTransformsGroupBox.setObjectName(_fromUtf8("mTransformsGroupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.mTransformsGroupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label = QtGui.QLabel(self.mTransformsGroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.mItemRotationSpinBox = QgsDoubleSpinBox(self.mTransformsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mItemRotationSpinBox.sizePolicy().hasHeightForWidth())
        self.mItemRotationSpinBox.setSizePolicy(sizePolicy)
        self.mItemRotationSpinBox.setMaximum(360.0)
        self.mItemRotationSpinBox.setObjectName(_fromUtf8("mItemRotationSpinBox"))
        self.horizontalLayout_4.addWidget(self.mItemRotationSpinBox)
        self.mItemRotationDDBtn = QgsDataDefinedButton(self.mTransformsGroupBox)
        self.mItemRotationDDBtn.setObjectName(_fromUtf8("mItemRotationDDBtn"))
        self.horizontalLayout_4.addWidget(self.mItemRotationDDBtn)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.verticalLayout_2.addWidget(self.mTransformsGroupBox)
        self.mFrameGroupBox = QgsCollapsibleGroupBoxBasic(QgsComposerItemWidgetBase)
        self.mFrameGroupBox.setCheckable(True)
        self.mFrameGroupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mFrameGroupBox.setProperty("collapsed", True)
        self.mFrameGroupBox.setObjectName(_fromUtf8("mFrameGroupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.mFrameGroupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_3 = QtGui.QLabel(self.mFrameGroupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.mFrameColorButton = QgsColorButtonV2(self.mFrameGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mFrameColorButton.sizePolicy().hasHeightForWidth())
        self.mFrameColorButton.setSizePolicy(sizePolicy)
        self.mFrameColorButton.setMinimumSize(QtCore.QSize(120, 0))
        self.mFrameColorButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.mFrameColorButton.setText(_fromUtf8(""))
        self.mFrameColorButton.setObjectName(_fromUtf8("mFrameColorButton"))
        self.horizontalLayout_6.addWidget(self.mFrameColorButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.gridLayout_6.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.mOutlineWidthLabel = QtGui.QLabel(self.mFrameGroupBox)
        self.mOutlineWidthLabel.setWordWrap(True)
        self.mOutlineWidthLabel.setObjectName(_fromUtf8("mOutlineWidthLabel"))
        self.gridLayout_6.addWidget(self.mOutlineWidthLabel, 1, 0, 1, 1)
        self.mOutlineWidthSpinBox = QgsDoubleSpinBox(self.mFrameGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mOutlineWidthSpinBox.sizePolicy().hasHeightForWidth())
        self.mOutlineWidthSpinBox.setSizePolicy(sizePolicy)
        self.mOutlineWidthSpinBox.setSingleStep(0.1)
        self.mOutlineWidthSpinBox.setProperty("showClearButton", False)
        self.mOutlineWidthSpinBox.setObjectName(_fromUtf8("mOutlineWidthSpinBox"))
        self.gridLayout_6.addWidget(self.mOutlineWidthSpinBox, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.mFrameGroupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 2, 0, 1, 1)
        self.mFrameJoinStyleCombo = QgsPenJoinStyleComboBox(self.mFrameGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mFrameJoinStyleCombo.sizePolicy().hasHeightForWidth())
        self.mFrameJoinStyleCombo.setSizePolicy(sizePolicy)
        self.mFrameJoinStyleCombo.setObjectName(_fromUtf8("mFrameJoinStyleCombo"))
        self.gridLayout_6.addWidget(self.mFrameJoinStyleCombo, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.mFrameGroupBox)
        self.mBackgroundGroupBox = QgsCollapsibleGroupBoxBasic(QgsComposerItemWidgetBase)
        self.mBackgroundGroupBox.setCheckable(True)
        self.mBackgroundGroupBox.setChecked(True)
        self.mBackgroundGroupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mBackgroundGroupBox.setProperty("collapsed", True)
        self.mBackgroundGroupBox.setObjectName(_fromUtf8("mBackgroundGroupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.mBackgroundGroupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_4 = QtGui.QLabel(self.mBackgroundGroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.mBackgroundColorButton = QgsColorButtonV2(self.mBackgroundGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mBackgroundColorButton.sizePolicy().hasHeightForWidth())
        self.mBackgroundColorButton.setSizePolicy(sizePolicy)
        self.mBackgroundColorButton.setMinimumSize(QtCore.QSize(120, 0))
        self.mBackgroundColorButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.mBackgroundColorButton.setText(_fromUtf8(""))
        self.mBackgroundColorButton.setObjectName(_fromUtf8("mBackgroundColorButton"))
        self.horizontalLayout_5.addWidget(self.mBackgroundColorButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.mBackgroundGroupBox)
        self.groupBox = QgsCollapsibleGroupBoxBasic(QgsComposerItemWidgetBase)
        self.groupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.groupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.groupBox.setProperty("collapsed", True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.mItemIdLabel = QtGui.QLabel(self.groupBox)
        self.mItemIdLabel.setObjectName(_fromUtf8("mItemIdLabel"))
        self.gridLayout_8.addWidget(self.mItemIdLabel, 0, 0, 1, 1)
        self.mItemIdLineEdit = QtGui.QLineEdit(self.groupBox)
        self.mItemIdLineEdit.setObjectName(_fromUtf8("mItemIdLineEdit"))
        self.gridLayout_8.addWidget(self.mItemIdLineEdit, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupRendering = QgsCollapsibleGroupBoxBasic(QgsComposerItemWidgetBase)
        self.groupRendering.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.groupRendering.setProperty("collapsed", True)
        self.groupRendering.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.groupRendering.setObjectName(_fromUtf8("groupRendering"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupRendering)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.labelBlendMode = QtGui.QLabel(self.groupRendering)
        self.labelBlendMode.setObjectName(_fromUtf8("labelBlendMode"))
        self.gridLayout_4.addWidget(self.labelBlendMode, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.mBlendModeCombo = QgsBlendModeComboBox(self.groupRendering)
        self.mBlendModeCombo.setObjectName(_fromUtf8("mBlendModeCombo"))
        self.horizontalLayout_3.addWidget(self.mBlendModeCombo)
        self.mBlendModeDDBtn = QgsDataDefinedButton(self.groupRendering)
        self.mBlendModeDDBtn.setObjectName(_fromUtf8("mBlendModeDDBtn"))
        self.horizontalLayout_3.addWidget(self.mBlendModeDDBtn)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.labelTransparency = QtGui.QLabel(self.groupRendering)
        self.labelTransparency.setObjectName(_fromUtf8("labelTransparency"))
        self.gridLayout_4.addWidget(self.labelTransparency, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.mTransparencySlider = QtGui.QSlider(self.groupRendering)
        self.mTransparencySlider.setMaximum(100)
        self.mTransparencySlider.setOrientation(QtCore.Qt.Horizontal)
        self.mTransparencySlider.setObjectName(_fromUtf8("mTransparencySlider"))
        self.horizontalLayout_2.addWidget(self.mTransparencySlider)
        self.mTransparencySpnBx = QgsSpinBox(self.groupRendering)
        self.mTransparencySpnBx.setMinimumSize(QtCore.QSize(80, 25))
        self.mTransparencySpnBx.setMaximum(100)
        self.mTransparencySpnBx.setObjectName(_fromUtf8("mTransparencySpnBx"))
        self.horizontalLayout_2.addWidget(self.mTransparencySpnBx)
        self.mTransparencyDDBtn = QgsDataDefinedButton(self.groupRendering)
        self.mTransparencyDDBtn.setObjectName(_fromUtf8("mTransparencyDDBtn"))
        self.horizontalLayout_2.addWidget(self.mTransparencyDDBtn)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mExcludeFromPrintsCheckBox = QtGui.QCheckBox(self.groupRendering)
        self.mExcludeFromPrintsCheckBox.setObjectName(_fromUtf8("mExcludeFromPrintsCheckBox"))
        self.horizontalLayout.addWidget(self.mExcludeFromPrintsCheckBox)
        self.mExcludePrintsDDBtn = QgsDataDefinedButton(self.groupRendering)
        self.mExcludePrintsDDBtn.setObjectName(_fromUtf8("mExcludePrintsDDBtn"))
        self.horizontalLayout.addWidget(self.mExcludePrintsDDBtn)
        self.gridLayout_4.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupRendering)
        self.groupBox_3 = QgsCollapsibleGroupBox(QgsComposerItemWidgetBase)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.mVariableEditor = QgsVariableEditorWidget(self.groupBox_3)
        self.mVariableEditor.setMinimumSize(QtCore.QSize(0, 200))
        self.mVariableEditor.setObjectName(_fromUtf8("mVariableEditor"))
        self.verticalLayout_4.addWidget(self.mVariableEditor)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.mOutlineWidthLabel.setBuddy(self.mOutlineWidthSpinBox)

        self.retranslateUi(QgsComposerItemWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(QgsComposerItemWidgetBase)
        QgsComposerItemWidgetBase.setTabOrder(self.mGeneralOptionsGroupBox, self.mPageSpinBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mPageSpinBox, self.mXPosSpin)
        QgsComposerItemWidgetBase.setTabOrder(self.mXPosSpin, self.mXPositionDDBtn)
        QgsComposerItemWidgetBase.setTabOrder(self.mXPositionDDBtn, self.mYPosSpin)
        QgsComposerItemWidgetBase.setTabOrder(self.mYPosSpin, self.mYPositionDDBtn)
        QgsComposerItemWidgetBase.setTabOrder(self.mYPositionDDBtn, self.mWidthSpin)
        QgsComposerItemWidgetBase.setTabOrder(self.mWidthSpin, self.mWidthDDBtn)
        QgsComposerItemWidgetBase.setTabOrder(self.mWidthDDBtn, self.mHeightSpin)
        QgsComposerItemWidgetBase.setTabOrder(self.mHeightSpin, self.mHeightDDBtn)
        QgsComposerItemWidgetBase.setTabOrder(self.mHeightDDBtn, self.mUpperLeftCheckBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mUpperLeftCheckBox, self.mUpperMiddleCheckBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mUpperMiddleCheckBox, self.mUpperRightCheckBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mUpperRightCheckBox, self.mMiddleLeftCheckBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mMiddleLeftCheckBox, self.mMiddleCheckBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mMiddleCheckBox, self.mMiddleRightCheckBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mMiddleRightCheckBox, self.mLowerLeftCheckBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mLowerLeftCheckBox, self.mLowerMiddleCheckBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mLowerMiddleCheckBox, self.mLowerRightCheckBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mLowerRightCheckBox, self.mTransformsGroupBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mTransformsGroupBox, self.mItemRotationSpinBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mItemRotationSpinBox, self.mItemRotationDDBtn)
        QgsComposerItemWidgetBase.setTabOrder(self.mItemRotationDDBtn, self.mFrameGroupBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mFrameGroupBox, self.mFrameColorButton)
        QgsComposerItemWidgetBase.setTabOrder(self.mFrameColorButton, self.mOutlineWidthSpinBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mOutlineWidthSpinBox, self.mFrameJoinStyleCombo)
        QgsComposerItemWidgetBase.setTabOrder(self.mFrameJoinStyleCombo, self.mBackgroundGroupBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mBackgroundGroupBox, self.mBackgroundColorButton)
        QgsComposerItemWidgetBase.setTabOrder(self.mBackgroundColorButton, self.groupBox)
        QgsComposerItemWidgetBase.setTabOrder(self.groupBox, self.mItemIdLineEdit)
        QgsComposerItemWidgetBase.setTabOrder(self.mItemIdLineEdit, self.groupRendering)
        QgsComposerItemWidgetBase.setTabOrder(self.groupRendering, self.mBlendModeCombo)
        QgsComposerItemWidgetBase.setTabOrder(self.mBlendModeCombo, self.mBlendModeDDBtn)
        QgsComposerItemWidgetBase.setTabOrder(self.mBlendModeDDBtn, self.mTransparencySlider)
        QgsComposerItemWidgetBase.setTabOrder(self.mTransparencySlider, self.mTransparencySpnBx)
        QgsComposerItemWidgetBase.setTabOrder(self.mTransparencySpnBx, self.mTransparencyDDBtn)
        QgsComposerItemWidgetBase.setTabOrder(self.mTransparencyDDBtn, self.mExcludeFromPrintsCheckBox)
        QgsComposerItemWidgetBase.setTabOrder(self.mExcludeFromPrintsCheckBox, self.mExcludePrintsDDBtn)

    def retranslateUi(self, QgsComposerItemWidgetBase):
        QgsComposerItemWidgetBase.setWindowTitle(_translate("QgsComposerItemWidgetBase", "Global Options", None))
        self.mGeneralOptionsGroupBox.setTitle(_translate("QgsComposerItemWidgetBase", "Position and size", None))
        self.mWidthLabel.setText(_translate("QgsComposerItemWidgetBase", "Width", None))
        self.mXLabel.setText(_translate("QgsComposerItemWidgetBase", "X", None))
        self.mHeightLabel.setText(_translate("QgsComposerItemWidgetBase", "Height", None))
        self.mYLabel.setText(_translate("QgsComposerItemWidgetBase", "Y", None))
        self.mPageLabel.setText(_translate("QgsComposerItemWidgetBase", "Page", None))
        self.mXPositionDDBtn.setText(_translate("QgsComposerItemWidgetBase", "...", None))
        self.mYPositionDDBtn.setText(_translate("QgsComposerItemWidgetBase", "...", None))
        self.mWidthDDBtn.setText(_translate("QgsComposerItemWidgetBase", "...", None))
        self.mHeightDDBtn.setText(_translate("QgsComposerItemWidgetBase", "...", None))
        self.mWidthSpin.setSuffix(_translate("QgsComposerItemWidgetBase", " mm", None))
        self.mHeightSpin.setSuffix(_translate("QgsComposerItemWidgetBase", " mm", None))
        self.mYPosSpin.setSuffix(_translate("QgsComposerItemWidgetBase", " mm", None))
        self.mXPosSpin.setSuffix(_translate("QgsComposerItemWidgetBase", " mm", None))
        self.label_2.setText(_translate("QgsComposerItemWidgetBase", "Reference point", None))
        self.mTransformsGroupBox.setTitle(_translate("QgsComposerItemWidgetBase", "Rotation", None))
        self.label.setText(_translate("QgsComposerItemWidgetBase", "Rotation", None))
        self.mItemRotationSpinBox.setSuffix(_translate("QgsComposerItemWidgetBase", " °", None))
        self.mItemRotationDDBtn.setText(_translate("QgsComposerItemWidgetBase", "...", None))
        self.mFrameGroupBox.setTitle(_translate("QgsComposerItemWidgetBase", "Frame", None))
        self.label_3.setText(_translate("QgsComposerItemWidgetBase", "Frame color", None))
        self.mOutlineWidthLabel.setText(_translate("QgsComposerItemWidgetBase", "Thickness", None))
        self.mOutlineWidthSpinBox.setSuffix(_translate("QgsComposerItemWidgetBase", " mm", None))
        self.label_8.setText(_translate("QgsComposerItemWidgetBase", "Join style", None))
        self.mBackgroundGroupBox.setTitle(_translate("QgsComposerItemWidgetBase", "Background", None))
        self.label_4.setText(_translate("QgsComposerItemWidgetBase", "Background color", None))
        self.groupBox.setTitle(_translate("QgsComposerItemWidgetBase", "Item ID", None))
        self.mItemIdLabel.setText(_translate("QgsComposerItemWidgetBase", "Id", None))
        self.groupRendering.setTitle(_translate("QgsComposerItemWidgetBase", "Rendering", None))
        self.labelBlendMode.setText(_translate("QgsComposerItemWidgetBase", "Blending mode", None))
        self.mBlendModeDDBtn.setText(_translate("QgsComposerItemWidgetBase", "...", None))
        self.labelTransparency.setText(_translate("QgsComposerItemWidgetBase", "Transparency", None))
        self.mTransparencyDDBtn.setText(_translate("QgsComposerItemWidgetBase", "...", None))
        self.mExcludeFromPrintsCheckBox.setText(_translate("QgsComposerItemWidgetBase", "Exclude item from exports", None))
        self.mExcludePrintsDDBtn.setText(_translate("QgsComposerItemWidgetBase", "...", None))
        self.groupBox_3.setTitle(_translate("QgsComposerItemWidgetBase", "Variables", None))

from qgsspinbox import QgsSpinBox
from qgsblendmodecombobox import QgsBlendModeComboBox
from qgsdatadefinedbutton import QgsDataDefinedButton
from qgscollapsiblegroupbox import QgsCollapsibleGroupBox, QgsCollapsibleGroupBoxBasic
from qgspenstylecombobox import QgsPenJoinStyleComboBox
from qgsdoublespinbox import QgsDoubleSpinBox
from qgsvariableeditorwidget import QgsVariableEditorWidget
from qgscolorbuttonv2 import QgsColorButtonV2
