# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qgscomposerlegendwidgetbase.ui'
#
# Created: Tue Sep 27 08:40:48 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QgsComposerLegendWidgetBase(object):
    def setupUi(self, QgsComposerLegendWidgetBase):
        QgsComposerLegendWidgetBase.setObjectName(_fromUtf8("QgsComposerLegendWidgetBase"))
        QgsComposerLegendWidgetBase.resize(393, 995)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QgsComposerLegendWidgetBase.sizePolicy().hasHeightForWidth())
        QgsComposerLegendWidgetBase.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(QgsComposerLegendWidgetBase)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_11 = QtGui.QLabel(QgsComposerLegendWidgetBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setStyleSheet(_fromUtf8("padding: 2px; font-weight: bold; background-color: rgb(200, 200, 200);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.scrollArea = QtGui.QScrollArea(QgsComposerLegendWidgetBase)
        self.scrollArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 375, 1478))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.mainLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.mainLayout.setObjectName(_fromUtf8("mainLayout"))
        self.mMainPropertiesColGroupBox = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.mMainPropertiesColGroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mMainPropertiesColGroupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mMainPropertiesColGroupBox.setProperty("collapsed", False)
        self.mMainPropertiesColGroupBox.setObjectName(_fromUtf8("mMainPropertiesColGroupBox"))
        self.formLayout = QtGui.QFormLayout(self.mMainPropertiesColGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.mTitleLabel = QtGui.QLabel(self.mMainPropertiesColGroupBox)
        self.mTitleLabel.setObjectName(_fromUtf8("mTitleLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.mTitleLabel)
        self.mTitleLineEdit = QtGui.QLineEdit(self.mMainPropertiesColGroupBox)
        self.mTitleLineEdit.setObjectName(_fromUtf8("mTitleLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.mTitleLineEdit)
        self.mMapLabel = QtGui.QLabel(self.mMainPropertiesColGroupBox)
        self.mMapLabel.setObjectName(_fromUtf8("mMapLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.mMapLabel)
        self.mMapComboBox = QtGui.QComboBox(self.mMainPropertiesColGroupBox)
        self.mMapComboBox.setObjectName(_fromUtf8("mMapComboBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.mMapComboBox)
        self.label = QtGui.QLabel(self.mMainPropertiesColGroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label)
        self.mWrapCharLineEdit = QtGui.QLineEdit(self.mMainPropertiesColGroupBox)
        self.mWrapCharLineEdit.setFrame(True)
        self.mWrapCharLineEdit.setObjectName(_fromUtf8("mWrapCharLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.mWrapCharLineEdit)
        self.label_15 = QtGui.QLabel(self.mMainPropertiesColGroupBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.mTitleAlignCombo = QtGui.QComboBox(self.mMainPropertiesColGroupBox)
        self.mTitleAlignCombo.setObjectName(_fromUtf8("mTitleAlignCombo"))
        self.mTitleAlignCombo.addItem(_fromUtf8(""))
        self.mTitleAlignCombo.addItem(_fromUtf8(""))
        self.mTitleAlignCombo.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.mTitleAlignCombo)
        self.mainLayout.addWidget(self.mMainPropertiesColGroupBox)
        self.mLegendItemColGroupBox = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.mLegendItemColGroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mLegendItemColGroupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mLegendItemColGroupBox.setProperty("collapsed", False)
        self.mLegendItemColGroupBox.setObjectName(_fromUtf8("mLegendItemColGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.mLegendItemColGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mCheckBoxAutoUpdate = QtGui.QCheckBox(self.mLegendItemColGroupBox)
        self.mCheckBoxAutoUpdate.setChecked(True)
        self.mCheckBoxAutoUpdate.setObjectName(_fromUtf8("mCheckBoxAutoUpdate"))
        self.horizontalLayout.addWidget(self.mCheckBoxAutoUpdate)
        spacerItem = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mUpdateAllPushButton = QtGui.QToolButton(self.mLegendItemColGroupBox)
        self.mUpdateAllPushButton.setObjectName(_fromUtf8("mUpdateAllPushButton"))
        self.horizontalLayout.addWidget(self.mUpdateAllPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.mItemTreeView = QgsLayerTreeView(self.mLegendItemColGroupBox)
        self.mItemTreeView.setMinimumSize(QtCore.QSize(0, 250))
        self.mItemTreeView.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.mItemTreeView.setHeaderHidden(True)
        self.mItemTreeView.setObjectName(_fromUtf8("mItemTreeView"))
        self.mItemTreeView.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.mItemTreeView)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.mMoveDownToolButton = QtGui.QToolButton(self.mLegendItemColGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mMoveDownToolButton.sizePolicy().hasHeightForWidth())
        self.mMoveDownToolButton.setSizePolicy(sizePolicy)
        self.mMoveDownToolButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionArrowDown.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mMoveDownToolButton.setIcon(icon)
        self.mMoveDownToolButton.setIconSize(QtCore.QSize(20, 20))
        self.mMoveDownToolButton.setObjectName(_fromUtf8("mMoveDownToolButton"))
        self.horizontalLayout_2.addWidget(self.mMoveDownToolButton)
        self.mMoveUpToolButton = QtGui.QToolButton(self.mLegendItemColGroupBox)
        self.mMoveUpToolButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionArrowUp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mMoveUpToolButton.setIcon(icon1)
        self.mMoveUpToolButton.setIconSize(QtCore.QSize(20, 20))
        self.mMoveUpToolButton.setObjectName(_fromUtf8("mMoveUpToolButton"))
        self.horizontalLayout_2.addWidget(self.mMoveUpToolButton)
        self.mAddGroupToolButton = QtGui.QToolButton(self.mLegendItemColGroupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionAddGroup.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mAddGroupToolButton.setIcon(icon2)
        self.mAddGroupToolButton.setIconSize(QtCore.QSize(20, 20))
        self.mAddGroupToolButton.setObjectName(_fromUtf8("mAddGroupToolButton"))
        self.horizontalLayout_2.addWidget(self.mAddGroupToolButton)
        self.mAddToolButton = QtGui.QToolButton(self.mLegendItemColGroupBox)
        self.mAddToolButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/symbologyAdd.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mAddToolButton.setIcon(icon3)
        self.mAddToolButton.setIconSize(QtCore.QSize(20, 20))
        self.mAddToolButton.setObjectName(_fromUtf8("mAddToolButton"))
        self.horizontalLayout_2.addWidget(self.mAddToolButton)
        self.mRemoveToolButton = QtGui.QToolButton(self.mLegendItemColGroupBox)
        self.mRemoveToolButton.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/symbologyRemove.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mRemoveToolButton.setIcon(icon4)
        self.mRemoveToolButton.setIconSize(QtCore.QSize(20, 20))
        self.mRemoveToolButton.setObjectName(_fromUtf8("mRemoveToolButton"))
        self.horizontalLayout_2.addWidget(self.mRemoveToolButton)
        self.mEditPushButton = QtGui.QToolButton(self.mLegendItemColGroupBox)
        self.mEditPushButton.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/symbologyEdit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mEditPushButton.setIcon(icon5)
        self.mEditPushButton.setIconSize(QtCore.QSize(20, 20))
        self.mEditPushButton.setObjectName(_fromUtf8("mEditPushButton"))
        self.horizontalLayout_2.addWidget(self.mEditPushButton)
        self.mCountToolButton = QtGui.QToolButton(self.mLegendItemColGroupBox)
        self.mCountToolButton.setEnabled(False)
        self.mCountToolButton.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionSum.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mCountToolButton.setIcon(icon6)
        self.mCountToolButton.setIconSize(QtCore.QSize(20, 20))
        self.mCountToolButton.setCheckable(True)
        self.mCountToolButton.setObjectName(_fromUtf8("mCountToolButton"))
        self.horizontalLayout_2.addWidget(self.mCountToolButton)
        self.mFilterByMapToolButton = QtGui.QToolButton(self.mLegendItemColGroupBox)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionFilter2.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mFilterByMapToolButton.setIcon(icon7)
        self.mFilterByMapToolButton.setIconSize(QtCore.QSize(20, 20))
        self.mFilterByMapToolButton.setCheckable(True)
        self.mFilterByMapToolButton.setObjectName(_fromUtf8("mFilterByMapToolButton"))
        self.horizontalLayout_2.addWidget(self.mFilterByMapToolButton)
        self.mExpressionFilterButton = QgsLegendFilterButton(self.mLegendItemColGroupBox)
        self.mExpressionFilterButton.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mIconExpressionFilter.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mExpressionFilterButton.setIcon(icon8)
        self.mExpressionFilterButton.setIconSize(QtCore.QSize(20, 20))
        self.mExpressionFilterButton.setObjectName(_fromUtf8("mExpressionFilterButton"))
        self.horizontalLayout_2.addWidget(self.mExpressionFilterButton)
        spacerItem1 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.mFilterLegendByAtlasCheckBox = QtGui.QCheckBox(self.mLegendItemColGroupBox)
        self.mFilterLegendByAtlasCheckBox.setObjectName(_fromUtf8("mFilterLegendByAtlasCheckBox"))
        self.verticalLayout_2.addWidget(self.mFilterLegendByAtlasCheckBox)
        self.mainLayout.addWidget(self.mLegendItemColGroupBox)
        self.mFontsColGroupBox = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.mFontsColGroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mFontsColGroupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mFontsColGroupBox.setProperty("collapsed", True)
        self.mFontsColGroupBox.setObjectName(_fromUtf8("mFontsColGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.mFontsColGroupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.mTitleFontButton = QtGui.QPushButton(self.mFontsColGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mTitleFontButton.sizePolicy().hasHeightForWidth())
        self.mTitleFontButton.setSizePolicy(sizePolicy)
        self.mTitleFontButton.setObjectName(_fromUtf8("mTitleFontButton"))
        self.verticalLayout_3.addWidget(self.mTitleFontButton)
        self.mLayerFontButton = QtGui.QPushButton(self.mFontsColGroupBox)
        self.mLayerFontButton.setObjectName(_fromUtf8("mLayerFontButton"))
        self.verticalLayout_3.addWidget(self.mLayerFontButton)
        self.mGroupFontButton = QtGui.QPushButton(self.mFontsColGroupBox)
        self.mGroupFontButton.setObjectName(_fromUtf8("mGroupFontButton"))
        self.verticalLayout_3.addWidget(self.mGroupFontButton)
        self.mItemFontButton = QtGui.QPushButton(self.mFontsColGroupBox)
        self.mItemFontButton.setObjectName(_fromUtf8("mItemFontButton"))
        self.verticalLayout_3.addWidget(self.mItemFontButton)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_16 = QtGui.QLabel(self.mFontsColGroupBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_3.addWidget(self.label_16)
        self.mFontColorButton = QgsColorButtonV2(self.mFontsColGroupBox)
        self.mFontColorButton.setMinimumSize(QtCore.QSize(120, 0))
        self.mFontColorButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.mFontColorButton.setText(_fromUtf8(""))
        self.mFontColorButton.setObjectName(_fromUtf8("mFontColorButton"))
        self.horizontalLayout_3.addWidget(self.mFontColorButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.mainLayout.addWidget(self.mFontsColGroupBox)
        self.mColumnsColGroupBox = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.mColumnsColGroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mColumnsColGroupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mColumnsColGroupBox.setProperty("collapsed", True)
        self.mColumnsColGroupBox.setObjectName(_fromUtf8("mColumnsColGroupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.mColumnsColGroupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.mColumnsColGroupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.mColumnCountSpinBox = QgsSpinBox(self.mColumnsColGroupBox)
        self.mColumnCountSpinBox.setPrefix(_fromUtf8(""))
        self.mColumnCountSpinBox.setMinimum(1)
        self.mColumnCountSpinBox.setMaximum(1000)
        self.mColumnCountSpinBox.setObjectName(_fromUtf8("mColumnCountSpinBox"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.mColumnCountSpinBox)
        self.mEqualColumnWidthCheckBox = QtGui.QCheckBox(self.mColumnsColGroupBox)
        self.mEqualColumnWidthCheckBox.setObjectName(_fromUtf8("mEqualColumnWidthCheckBox"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.SpanningRole, self.mEqualColumnWidthCheckBox)
        self.mSplitLayerCheckBox = QtGui.QCheckBox(self.mColumnsColGroupBox)
        self.mSplitLayerCheckBox.setObjectName(_fromUtf8("mSplitLayerCheckBox"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.SpanningRole, self.mSplitLayerCheckBox)
        self.mainLayout.addWidget(self.mColumnsColGroupBox)
        self.mSymbolsColGroupBox = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.mSymbolsColGroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mSymbolsColGroupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mSymbolsColGroupBox.setProperty("collapsed", True)
        self.mSymbolsColGroupBox.setObjectName(_fromUtf8("mSymbolsColGroupBox"))
        self.formLayout_3 = QtGui.QFormLayout(self.mSymbolsColGroupBox)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_3 = QtGui.QLabel(self.mSymbolsColGroupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.mSymbolWidthSpinBox = QgsDoubleSpinBox(self.mSymbolsColGroupBox)
        self.mSymbolWidthSpinBox.setPrefix(_fromUtf8(""))
        self.mSymbolWidthSpinBox.setProperty("showClearButton", False)
        self.mSymbolWidthSpinBox.setObjectName(_fromUtf8("mSymbolWidthSpinBox"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.mSymbolWidthSpinBox)
        self.label_4 = QtGui.QLabel(self.mSymbolsColGroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.mSymbolHeightSpinBox = QgsDoubleSpinBox(self.mSymbolsColGroupBox)
        self.mSymbolHeightSpinBox.setPrefix(_fromUtf8(""))
        self.mSymbolHeightSpinBox.setProperty("showClearButton", False)
        self.mSymbolHeightSpinBox.setObjectName(_fromUtf8("mSymbolHeightSpinBox"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.mSymbolHeightSpinBox)
        self.mRasterBorderGroupBox = QgsCollapsibleGroupBoxBasic(self.mSymbolsColGroupBox)
        self.mRasterBorderGroupBox.setCheckable(True)
        self.mRasterBorderGroupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mRasterBorderGroupBox.setProperty("collapsed", True)
        self.mRasterBorderGroupBox.setObjectName(_fromUtf8("mRasterBorderGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.mRasterBorderGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_17 = QtGui.QLabel(self.mRasterBorderGroupBox)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.mRasterBorderColorButton = QgsColorButtonV2(self.mRasterBorderGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mRasterBorderColorButton.sizePolicy().hasHeightForWidth())
        self.mRasterBorderColorButton.setSizePolicy(sizePolicy)
        self.mRasterBorderColorButton.setMinimumSize(QtCore.QSize(120, 0))
        self.mRasterBorderColorButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.mRasterBorderColorButton.setText(_fromUtf8(""))
        self.mRasterBorderColorButton.setObjectName(_fromUtf8("mRasterBorderColorButton"))
        self.horizontalLayout_6.addWidget(self.mRasterBorderColorButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.mOutlineWidthLabel = QtGui.QLabel(self.mRasterBorderGroupBox)
        self.mOutlineWidthLabel.setObjectName(_fromUtf8("mOutlineWidthLabel"))
        self.gridLayout.addWidget(self.mOutlineWidthLabel, 1, 0, 1, 1)
        self.mRasterBorderWidthSpinBox = QgsDoubleSpinBox(self.mRasterBorderGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mRasterBorderWidthSpinBox.sizePolicy().hasHeightForWidth())
        self.mRasterBorderWidthSpinBox.setSizePolicy(sizePolicy)
        self.mRasterBorderWidthSpinBox.setSingleStep(0.1)
        self.mRasterBorderWidthSpinBox.setProperty("showClearButton", False)
        self.mRasterBorderWidthSpinBox.setObjectName(_fromUtf8("mRasterBorderWidthSpinBox"))
        self.gridLayout.addWidget(self.mRasterBorderWidthSpinBox, 1, 1, 1, 1)
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.SpanningRole, self.mRasterBorderGroupBox)
        self.mainLayout.addWidget(self.mSymbolsColGroupBox)
        self.mSymbolsColGroupBox_2 = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.mSymbolsColGroupBox_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mSymbolsColGroupBox_2.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mSymbolsColGroupBox_2.setProperty("collapsed", True)
        self.mSymbolsColGroupBox_2.setObjectName(_fromUtf8("mSymbolsColGroupBox_2"))
        self.formLayout_5 = QtGui.QFormLayout(self.mSymbolsColGroupBox_2)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_13 = QtGui.QLabel(self.mSymbolsColGroupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_13)
        self.mWmsLegendWidthSpinBox = QgsDoubleSpinBox(self.mSymbolsColGroupBox_2)
        self.mWmsLegendWidthSpinBox.setPrefix(_fromUtf8(""))
        self.mWmsLegendWidthSpinBox.setMaximum(9999.0)
        self.mWmsLegendWidthSpinBox.setProperty("showClearButton", False)
        self.mWmsLegendWidthSpinBox.setObjectName(_fromUtf8("mWmsLegendWidthSpinBox"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.mWmsLegendWidthSpinBox)
        self.label_14 = QtGui.QLabel(self.mSymbolsColGroupBox_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_14)
        self.mWmsLegendHeightSpinBox = QgsDoubleSpinBox(self.mSymbolsColGroupBox_2)
        self.mWmsLegendHeightSpinBox.setPrefix(_fromUtf8(""))
        self.mWmsLegendHeightSpinBox.setMaximum(9999.0)
        self.mWmsLegendHeightSpinBox.setProperty("showClearButton", False)
        self.mWmsLegendHeightSpinBox.setObjectName(_fromUtf8("mWmsLegendHeightSpinBox"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.mWmsLegendHeightSpinBox)
        self.mainLayout.addWidget(self.mSymbolsColGroupBox_2)
        self.mSpacingColGroupBox = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.mSpacingColGroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mSpacingColGroupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mSpacingColGroupBox.setProperty("collapsed", True)
        self.mSpacingColGroupBox.setObjectName(_fromUtf8("mSpacingColGroupBox"))
        self.formLayout_4 = QtGui.QFormLayout(self.mSpacingColGroupBox)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_5 = QtGui.QLabel(self.mSpacingColGroupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.mGroupSpaceSpinBox = QgsDoubleSpinBox(self.mSpacingColGroupBox)
        self.mGroupSpaceSpinBox.setPrefix(_fromUtf8(""))
        self.mGroupSpaceSpinBox.setObjectName(_fromUtf8("mGroupSpaceSpinBox"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.mGroupSpaceSpinBox)
        self.label_6 = QtGui.QLabel(self.mSpacingColGroupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.mLayerSpaceSpinBox = QgsDoubleSpinBox(self.mSpacingColGroupBox)
        self.mLayerSpaceSpinBox.setPrefix(_fromUtf8(""))
        self.mLayerSpaceSpinBox.setObjectName(_fromUtf8("mLayerSpaceSpinBox"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.mLayerSpaceSpinBox)
        self.label_7 = QtGui.QLabel(self.mSpacingColGroupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.mSymbolSpaceSpinBox = QgsDoubleSpinBox(self.mSpacingColGroupBox)
        self.mSymbolSpaceSpinBox.setPrefix(_fromUtf8(""))
        self.mSymbolSpaceSpinBox.setObjectName(_fromUtf8("mSymbolSpaceSpinBox"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.mSymbolSpaceSpinBox)
        self.label_8 = QtGui.QLabel(self.mSpacingColGroupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.mIconLabelSpaceSpinBox = QgsDoubleSpinBox(self.mSpacingColGroupBox)
        self.mIconLabelSpaceSpinBox.setPrefix(_fromUtf8(""))
        self.mIconLabelSpaceSpinBox.setObjectName(_fromUtf8("mIconLabelSpaceSpinBox"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.mIconLabelSpaceSpinBox)
        self.label_9 = QtGui.QLabel(self.mSpacingColGroupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_9)
        self.mBoxSpaceSpinBox = QgsDoubleSpinBox(self.mSpacingColGroupBox)
        self.mBoxSpaceSpinBox.setPrefix(_fromUtf8(""))
        self.mBoxSpaceSpinBox.setObjectName(_fromUtf8("mBoxSpaceSpinBox"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.mBoxSpaceSpinBox)
        self.label_12 = QtGui.QLabel(self.mSpacingColGroupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_12)
        self.mColumnSpaceSpinBox = QgsDoubleSpinBox(self.mSpacingColGroupBox)
        self.mColumnSpaceSpinBox.setPrefix(_fromUtf8(""))
        self.mColumnSpaceSpinBox.setObjectName(_fromUtf8("mColumnSpaceSpinBox"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.FieldRole, self.mColumnSpaceSpinBox)
        self.label_10 = QtGui.QLabel(self.mSpacingColGroupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.mTitleSpaceBottomSpinBox = QgsDoubleSpinBox(self.mSpacingColGroupBox)
        self.mTitleSpaceBottomSpinBox.setObjectName(_fromUtf8("mTitleSpaceBottomSpinBox"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.mTitleSpaceBottomSpinBox)
        self.mainLayout.addWidget(self.mSpacingColGroupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.mTitleLabel.setBuddy(self.mTitleLineEdit)
        self.mOutlineWidthLabel.setBuddy(self.mRasterBorderWidthSpinBox)

        self.retranslateUi(QgsComposerLegendWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(QgsComposerLegendWidgetBase)
        QgsComposerLegendWidgetBase.setTabOrder(self.scrollArea, self.mMainPropertiesColGroupBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mMainPropertiesColGroupBox, self.mTitleLineEdit)
        QgsComposerLegendWidgetBase.setTabOrder(self.mTitleLineEdit, self.mTitleAlignCombo)
        QgsComposerLegendWidgetBase.setTabOrder(self.mTitleAlignCombo, self.mMapComboBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mMapComboBox, self.mWrapCharLineEdit)
        QgsComposerLegendWidgetBase.setTabOrder(self.mWrapCharLineEdit, self.mLegendItemColGroupBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mLegendItemColGroupBox, self.mCheckBoxAutoUpdate)
        QgsComposerLegendWidgetBase.setTabOrder(self.mCheckBoxAutoUpdate, self.mUpdateAllPushButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mUpdateAllPushButton, self.mItemTreeView)
        QgsComposerLegendWidgetBase.setTabOrder(self.mItemTreeView, self.mMoveDownToolButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mMoveDownToolButton, self.mMoveUpToolButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mMoveUpToolButton, self.mAddGroupToolButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mAddGroupToolButton, self.mAddToolButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mAddToolButton, self.mRemoveToolButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mRemoveToolButton, self.mEditPushButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mEditPushButton, self.mCountToolButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mCountToolButton, self.mFilterByMapToolButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mFilterByMapToolButton, self.mExpressionFilterButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mExpressionFilterButton, self.mFilterLegendByAtlasCheckBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mFilterLegendByAtlasCheckBox, self.mFontsColGroupBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mFontsColGroupBox, self.mTitleFontButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mTitleFontButton, self.mLayerFontButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mLayerFontButton, self.mGroupFontButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mGroupFontButton, self.mItemFontButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mItemFontButton, self.mFontColorButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mFontColorButton, self.mColumnsColGroupBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mColumnsColGroupBox, self.mColumnCountSpinBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mColumnCountSpinBox, self.mEqualColumnWidthCheckBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mEqualColumnWidthCheckBox, self.mSplitLayerCheckBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mSplitLayerCheckBox, self.mSymbolsColGroupBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mSymbolsColGroupBox, self.mSymbolWidthSpinBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mSymbolWidthSpinBox, self.mSymbolHeightSpinBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mSymbolHeightSpinBox, self.mRasterBorderGroupBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mRasterBorderGroupBox, self.mRasterBorderColorButton)
        QgsComposerLegendWidgetBase.setTabOrder(self.mRasterBorderColorButton, self.mRasterBorderWidthSpinBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mRasterBorderWidthSpinBox, self.mSymbolsColGroupBox_2)
        QgsComposerLegendWidgetBase.setTabOrder(self.mSymbolsColGroupBox_2, self.mWmsLegendWidthSpinBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mWmsLegendWidthSpinBox, self.mWmsLegendHeightSpinBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mWmsLegendHeightSpinBox, self.mSpacingColGroupBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mSpacingColGroupBox, self.mTitleSpaceBottomSpinBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mTitleSpaceBottomSpinBox, self.mGroupSpaceSpinBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mGroupSpaceSpinBox, self.mLayerSpaceSpinBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mLayerSpaceSpinBox, self.mSymbolSpaceSpinBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mSymbolSpaceSpinBox, self.mIconLabelSpaceSpinBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mIconLabelSpaceSpinBox, self.mBoxSpaceSpinBox)
        QgsComposerLegendWidgetBase.setTabOrder(self.mBoxSpaceSpinBox, self.mColumnSpaceSpinBox)

    def retranslateUi(self, QgsComposerLegendWidgetBase):
        QgsComposerLegendWidgetBase.setWindowTitle(_translate("QgsComposerLegendWidgetBase", "Legend Options", None))
        self.label_11.setText(_translate("QgsComposerLegendWidgetBase", "Legend", None))
        self.mMainPropertiesColGroupBox.setTitle(_translate("QgsComposerLegendWidgetBase", "Main properties", None))
        self.mTitleLabel.setText(_translate("QgsComposerLegendWidgetBase", "&Title", None))
        self.mMapLabel.setText(_translate("QgsComposerLegendWidgetBase", "Map", None))
        self.label.setText(_translate("QgsComposerLegendWidgetBase", "Wrap text on", None))
        self.label_15.setText(_translate("QgsComposerLegendWidgetBase", "Title alignment:", None))
        self.mTitleAlignCombo.setItemText(0, _translate("QgsComposerLegendWidgetBase", "Left", None))
        self.mTitleAlignCombo.setItemText(1, _translate("QgsComposerLegendWidgetBase", "Center", None))
        self.mTitleAlignCombo.setItemText(2, _translate("QgsComposerLegendWidgetBase", "Right", None))
        self.mLegendItemColGroupBox.setTitle(_translate("QgsComposerLegendWidgetBase", "Legend items", None))
        self.mCheckBoxAutoUpdate.setText(_translate("QgsComposerLegendWidgetBase", "Auto update", None))
        self.mUpdateAllPushButton.setToolTip(_translate("QgsComposerLegendWidgetBase", "Update whole legend. Layers are added/removed according to main application legend. User defined labels will be deleted.", None))
        self.mUpdateAllPushButton.setText(_translate("QgsComposerLegendWidgetBase", "Update all", None))
        self.mAddGroupToolButton.setToolTip(_translate("QgsComposerLegendWidgetBase", "Add group", None))
        self.mAddGroupToolButton.setText(_translate("QgsComposerLegendWidgetBase", "...", None))
        self.mCountToolButton.setToolTip(_translate("QgsComposerLegendWidgetBase", "Show feature count for each class of vector layer.", None))
        self.mFilterByMapToolButton.setToolTip(_translate("QgsComposerLegendWidgetBase", "Filter Legend By Map Content", None))
        self.mFilterLegendByAtlasCheckBox.setToolTip(_translate("QgsComposerLegendWidgetBase", "Filter out legend elements that lie outside the current atlas feature.", None))
        self.mFilterLegendByAtlasCheckBox.setText(_translate("QgsComposerLegendWidgetBase", "Only show items inside current atlas feature", None))
        self.mFontsColGroupBox.setTitle(_translate("QgsComposerLegendWidgetBase", "Fonts", None))
        self.mTitleFontButton.setText(_translate("QgsComposerLegendWidgetBase", "Title font...", None))
        self.mLayerFontButton.setText(_translate("QgsComposerLegendWidgetBase", "Subgroup font...", None))
        self.mGroupFontButton.setText(_translate("QgsComposerLegendWidgetBase", "Group font...", None))
        self.mItemFontButton.setText(_translate("QgsComposerLegendWidgetBase", "Item font...", None))
        self.label_16.setText(_translate("QgsComposerLegendWidgetBase", "Font color", None))
        self.mColumnsColGroupBox.setTitle(_translate("QgsComposerLegendWidgetBase", "Columns", None))
        self.label_2.setText(_translate("QgsComposerLegendWidgetBase", "Count", None))
        self.mEqualColumnWidthCheckBox.setText(_translate("QgsComposerLegendWidgetBase", "Equal column widths", None))
        self.mSplitLayerCheckBox.setToolTip(_translate("QgsComposerLegendWidgetBase", "Allow splitting layer items into multiple columns.", None))
        self.mSplitLayerCheckBox.setText(_translate("QgsComposerLegendWidgetBase", "Split layers", None))
        self.mSymbolsColGroupBox.setTitle(_translate("QgsComposerLegendWidgetBase", "Symbol", None))
        self.label_3.setText(_translate("QgsComposerLegendWidgetBase", "Symbol width", None))
        self.mSymbolWidthSpinBox.setSuffix(_translate("QgsComposerLegendWidgetBase", " mm", None))
        self.label_4.setText(_translate("QgsComposerLegendWidgetBase", "Symbol height", None))
        self.mSymbolHeightSpinBox.setSuffix(_translate("QgsComposerLegendWidgetBase", " mm", None))
        self.mRasterBorderGroupBox.setTitle(_translate("QgsComposerLegendWidgetBase", "Draw border for raster symbols", None))
        self.label_17.setText(_translate("QgsComposerLegendWidgetBase", "Border color", None))
        self.mOutlineWidthLabel.setText(_translate("QgsComposerLegendWidgetBase", "Thickness", None))
        self.mRasterBorderWidthSpinBox.setSpecialValueText(_translate("QgsComposerLegendWidgetBase", "Hairline", None))
        self.mRasterBorderWidthSpinBox.setSuffix(_translate("QgsComposerLegendWidgetBase", " mm", None))
        self.mSymbolsColGroupBox_2.setTitle(_translate("QgsComposerLegendWidgetBase", "WMS LegendGraphic", None))
        self.label_13.setText(_translate("QgsComposerLegendWidgetBase", "Legend width", None))
        self.mWmsLegendWidthSpinBox.setSuffix(_translate("QgsComposerLegendWidgetBase", " mm", None))
        self.label_14.setText(_translate("QgsComposerLegendWidgetBase", "Legend height", None))
        self.mWmsLegendHeightSpinBox.setSuffix(_translate("QgsComposerLegendWidgetBase", " mm", None))
        self.mSpacingColGroupBox.setTitle(_translate("QgsComposerLegendWidgetBase", "Spacing", None))
        self.label_5.setToolTip(_translate("QgsComposerLegendWidgetBase", "Space above text using group style.", None))
        self.label_5.setText(_translate("QgsComposerLegendWidgetBase", "Group Space", None))
        self.mGroupSpaceSpinBox.setSuffix(_translate("QgsComposerLegendWidgetBase", " mm", None))
        self.label_6.setToolTip(_translate("QgsComposerLegendWidgetBase", "Space above text using subgroup style.", None))
        self.label_6.setText(_translate("QgsComposerLegendWidgetBase", "Subgroup space", None))
        self.mLayerSpaceSpinBox.setSuffix(_translate("QgsComposerLegendWidgetBase", " mm", None))
        self.label_7.setToolTip(_translate("QgsComposerLegendWidgetBase", "Space above symbol and symbol label.", None))
        self.label_7.setText(_translate("QgsComposerLegendWidgetBase", "Symbol space", None))
        self.mSymbolSpaceSpinBox.setSuffix(_translate("QgsComposerLegendWidgetBase", " mm", None))
        self.label_8.setToolTip(_translate("QgsComposerLegendWidgetBase", "Space between symbol icon and symbol label (symbol label left margin).", None))
        self.label_8.setText(_translate("QgsComposerLegendWidgetBase", "Icon label space", None))
        self.mIconLabelSpaceSpinBox.setSuffix(_translate("QgsComposerLegendWidgetBase", " mm", None))
        self.label_9.setText(_translate("QgsComposerLegendWidgetBase", "Box space", None))
        self.mBoxSpaceSpinBox.setSuffix(_translate("QgsComposerLegendWidgetBase", " mm", None))
        self.label_12.setText(_translate("QgsComposerLegendWidgetBase", "Column space", None))
        self.mColumnSpaceSpinBox.setSuffix(_translate("QgsComposerLegendWidgetBase", " mm", None))
        self.label_10.setToolTip(_translate("QgsComposerLegendWidgetBase", "Space below title.", None))
        self.label_10.setText(_translate("QgsComposerLegendWidgetBase", "Title space", None))
        self.mTitleSpaceBottomSpinBox.setToolTip(_translate("QgsComposerLegendWidgetBase", "Space below title.", None))
        self.mTitleSpaceBottomSpinBox.setSuffix(_translate("QgsComposerLegendWidgetBase", " mm", None))

from qgsspinbox import QgsSpinBox
from qgscollapsiblegroupbox import QgsCollapsibleGroupBoxBasic
from qgslayertreeview import QgsLayerTreeView
from qgsdoublespinbox import QgsDoubleSpinBox
from qgslegendfilterbutton import QgsLegendFilterButton
from qgscolorbuttonv2 import QgsColorButtonV2
import images_rc
