# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qgscomposerlabelwidgetbase.ui'
#
# Created: Thu Sep 22 11:06:44 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QgsComposerLabelWidgetBase(object):
    def setupUi(self, QgsComposerLabelWidgetBase):
        QgsComposerLabelWidgetBase.setObjectName(_fromUtf8("QgsComposerLabelWidgetBase"))
        QgsComposerLabelWidgetBase.resize(304, 705)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QgsComposerLabelWidgetBase.sizePolicy().hasHeightForWidth())
        QgsComposerLabelWidgetBase.setSizePolicy(sizePolicy)
        self._2 = QtGui.QVBoxLayout(QgsComposerLabelWidgetBase)
        self._2.setSpacing(0)
        self._2.setMargin(0)
        self._2.setObjectName(_fromUtf8("_2"))
        self.label = QtGui.QLabel(QgsComposerLabelWidgetBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet(_fromUtf8("padding: 2px; font-weight: bold; background-color: rgb(200, 200, 200);"))
        self.label.setObjectName(_fromUtf8("label"))
        self._2.addWidget(self.label)
        self.scrollArea = QtGui.QScrollArea(QgsComposerLabelWidgetBase)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 302, 682))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.mainLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.mainLayout.setObjectName(_fromUtf8("mainLayout"))
        self.mTextGroupBox = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.mTextGroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mTextGroupBox.setCheckable(False)
        self.mTextGroupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mTextGroupBox.setProperty("collapsed", False)
        self.mTextGroupBox.setObjectName(_fromUtf8("mTextGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.mTextGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mTextEdit = QtGui.QPlainTextEdit(self.mTextGroupBox)
        self.mTextEdit.setTabStopWidth(10)
        self.mTextEdit.setObjectName(_fromUtf8("mTextEdit"))
        self.gridLayout_2.addWidget(self.mTextEdit, 0, 0, 1, 1)
        self.mHtmlCheckBox = QtGui.QCheckBox(self.mTextGroupBox)
        self.mHtmlCheckBox.setObjectName(_fromUtf8("mHtmlCheckBox"))
        self.gridLayout_2.addWidget(self.mHtmlCheckBox, 1, 0, 1, 1)
        self.mInsertExpressionButton = QtGui.QPushButton(self.mTextGroupBox)
        self.mInsertExpressionButton.setObjectName(_fromUtf8("mInsertExpressionButton"))
        self.gridLayout_2.addWidget(self.mInsertExpressionButton, 2, 0, 1, 1)
        self.mainLayout.addWidget(self.mTextGroupBox)
        self.mAppearanceGroup = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.mAppearanceGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mAppearanceGroup.setCheckable(False)
        self.mAppearanceGroup.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mAppearanceGroup.setProperty("collapsed", False)
        self.mAppearanceGroup.setObjectName(_fromUtf8("mAppearanceGroup"))
        self.gridLayout = QtGui.QGridLayout(self.mAppearanceGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.mAppearanceGroup)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.mTopRadioButton = QtGui.QRadioButton(self.mAppearanceGroup)
        self.mTopRadioButton.setObjectName(_fromUtf8("mTopRadioButton"))
        self.buttonGroup = QtGui.QButtonGroup(QgsComposerLabelWidgetBase)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.mTopRadioButton)
        self.horizontalLayout_6.addWidget(self.mTopRadioButton)
        self.mMiddleRadioButton = QtGui.QRadioButton(self.mAppearanceGroup)
        self.mMiddleRadioButton.setObjectName(_fromUtf8("mMiddleRadioButton"))
        self.buttonGroup.addButton(self.mMiddleRadioButton)
        self.horizontalLayout_6.addWidget(self.mMiddleRadioButton)
        self.mBottomRadioButton = QtGui.QRadioButton(self.mAppearanceGroup)
        self.mBottomRadioButton.setObjectName(_fromUtf8("mBottomRadioButton"))
        self.buttonGroup.addButton(self.mBottomRadioButton)
        self.horizontalLayout_6.addWidget(self.mBottomRadioButton)
        spacerItem = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_6, 7, 0, 1, 2)
        self.mMarginXDoubleSpinBox = QgsDoubleSpinBox(self.mAppearanceGroup)
        self.mMarginXDoubleSpinBox.setPrefix(_fromUtf8(""))
        self.mMarginXDoubleSpinBox.setMinimum(-99.99)
        self.mMarginXDoubleSpinBox.setObjectName(_fromUtf8("mMarginXDoubleSpinBox"))
        self.gridLayout.addWidget(self.mMarginXDoubleSpinBox, 2, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.mLeftRadioButton = QtGui.QRadioButton(self.mAppearanceGroup)
        self.mLeftRadioButton.setObjectName(_fromUtf8("mLeftRadioButton"))
        self.buttonGroup_2 = QtGui.QButtonGroup(QgsComposerLabelWidgetBase)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.mLeftRadioButton)
        self.horizontalLayout_5.addWidget(self.mLeftRadioButton)
        self.mCenterRadioButton = QtGui.QRadioButton(self.mAppearanceGroup)
        self.mCenterRadioButton.setObjectName(_fromUtf8("mCenterRadioButton"))
        self.buttonGroup_2.addButton(self.mCenterRadioButton)
        self.horizontalLayout_5.addWidget(self.mCenterRadioButton)
        self.mRightRadioButton = QtGui.QRadioButton(self.mAppearanceGroup)
        self.mRightRadioButton.setObjectName(_fromUtf8("mRightRadioButton"))
        self.buttonGroup_2.addButton(self.mRightRadioButton)
        self.horizontalLayout_5.addWidget(self.mRightRadioButton)
        spacerItem1 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 0, 1, 2)
        self.mHorizontalAlignementLabel = QtGui.QLabel(self.mAppearanceGroup)
        self.mHorizontalAlignementLabel.setObjectName(_fromUtf8("mHorizontalAlignementLabel"))
        self.gridLayout.addWidget(self.mHorizontalAlignementLabel, 4, 0, 1, 2)
        self.mVerticalAlignementLabel = QtGui.QLabel(self.mAppearanceGroup)
        self.mVerticalAlignementLabel.setObjectName(_fromUtf8("mVerticalAlignementLabel"))
        self.gridLayout.addWidget(self.mVerticalAlignementLabel, 6, 0, 1, 2)
        self.mFontButton = QtGui.QPushButton(self.mAppearanceGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mFontButton.sizePolicy().hasHeightForWidth())
        self.mFontButton.setSizePolicy(sizePolicy)
        self.mFontButton.setObjectName(_fromUtf8("mFontButton"))
        self.gridLayout.addWidget(self.mFontButton, 0, 0, 1, 2)
        self.mMarginXLabel = QtGui.QLabel(self.mAppearanceGroup)
        self.mMarginXLabel.setObjectName(_fromUtf8("mMarginXLabel"))
        self.gridLayout.addWidget(self.mMarginXLabel, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mFontColorButton = QgsColorButtonV2(self.mAppearanceGroup)
        self.mFontColorButton.setMinimumSize(QtCore.QSize(120, 0))
        self.mFontColorButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.mFontColorButton.setText(_fromUtf8(""))
        self.mFontColorButton.setObjectName(_fromUtf8("mFontColorButton"))
        self.horizontalLayout.addWidget(self.mFontColorButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.mMarginYDoubleSpinBox = QgsDoubleSpinBox(self.mAppearanceGroup)
        self.mMarginYDoubleSpinBox.setMinimum(-99.99)
        self.mMarginYDoubleSpinBox.setObjectName(_fromUtf8("mMarginYDoubleSpinBox"))
        self.gridLayout.addWidget(self.mMarginYDoubleSpinBox, 3, 1, 1, 1)
        self.mMarginYLabel = QtGui.QLabel(self.mAppearanceGroup)
        self.mMarginYLabel.setObjectName(_fromUtf8("mMarginYLabel"))
        self.gridLayout.addWidget(self.mMarginYLabel, 3, 0, 1, 1)
        self.mainLayout.addWidget(self.mAppearanceGroup)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self._2.addWidget(self.scrollArea)

        self.retranslateUi(QgsComposerLabelWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(QgsComposerLabelWidgetBase)
        QgsComposerLabelWidgetBase.setTabOrder(self.scrollArea, self.mTextGroupBox)
        QgsComposerLabelWidgetBase.setTabOrder(self.mTextGroupBox, self.mTextEdit)
        QgsComposerLabelWidgetBase.setTabOrder(self.mTextEdit, self.mHtmlCheckBox)
        QgsComposerLabelWidgetBase.setTabOrder(self.mHtmlCheckBox, self.mInsertExpressionButton)
        QgsComposerLabelWidgetBase.setTabOrder(self.mInsertExpressionButton, self.mAppearanceGroup)
        QgsComposerLabelWidgetBase.setTabOrder(self.mAppearanceGroup, self.mFontButton)
        QgsComposerLabelWidgetBase.setTabOrder(self.mFontButton, self.mFontColorButton)
        QgsComposerLabelWidgetBase.setTabOrder(self.mFontColorButton, self.mMarginXDoubleSpinBox)
        QgsComposerLabelWidgetBase.setTabOrder(self.mMarginXDoubleSpinBox, self.mMarginYDoubleSpinBox)
        QgsComposerLabelWidgetBase.setTabOrder(self.mMarginYDoubleSpinBox, self.mLeftRadioButton)
        QgsComposerLabelWidgetBase.setTabOrder(self.mLeftRadioButton, self.mCenterRadioButton)
        QgsComposerLabelWidgetBase.setTabOrder(self.mCenterRadioButton, self.mRightRadioButton)
        QgsComposerLabelWidgetBase.setTabOrder(self.mRightRadioButton, self.mTopRadioButton)
        QgsComposerLabelWidgetBase.setTabOrder(self.mTopRadioButton, self.mMiddleRadioButton)
        QgsComposerLabelWidgetBase.setTabOrder(self.mMiddleRadioButton, self.mBottomRadioButton)

    def retranslateUi(self, QgsComposerLabelWidgetBase):
        QgsComposerLabelWidgetBase.setWindowTitle(_translate("QgsComposerLabelWidgetBase", "Label Options", None))
        self.label.setText(_translate("QgsComposerLabelWidgetBase", "Label", None))
        self.mTextGroupBox.setTitle(_translate("QgsComposerLabelWidgetBase", "Main properties", None))
        self.mHtmlCheckBox.setText(_translate("QgsComposerLabelWidgetBase", "Render as HTML", None))
        self.mInsertExpressionButton.setText(_translate("QgsComposerLabelWidgetBase", "Insert an expression...", None))
        self.mAppearanceGroup.setTitle(_translate("QgsComposerLabelWidgetBase", "Appearance", None))
        self.label_2.setText(_translate("QgsComposerLabelWidgetBase", "Font color", None))
        self.mTopRadioButton.setText(_translate("QgsComposerLabelWidgetBase", "Top", None))
        self.mMiddleRadioButton.setText(_translate("QgsComposerLabelWidgetBase", "Middle", None))
        self.mBottomRadioButton.setText(_translate("QgsComposerLabelWidgetBase", "Bottom", None))
        self.mMarginXDoubleSpinBox.setSuffix(_translate("QgsComposerLabelWidgetBase", " mm", None))
        self.mLeftRadioButton.setText(_translate("QgsComposerLabelWidgetBase", "Left", None))
        self.mCenterRadioButton.setText(_translate("QgsComposerLabelWidgetBase", "Center", None))
        self.mRightRadioButton.setText(_translate("QgsComposerLabelWidgetBase", "Right", None))
        self.mHorizontalAlignementLabel.setText(_translate("QgsComposerLabelWidgetBase", "Horizontal alignment", None))
        self.mVerticalAlignementLabel.setText(_translate("QgsComposerLabelWidgetBase", "Vertical alignment", None))
        self.mFontButton.setText(_translate("QgsComposerLabelWidgetBase", "Font...", None))
        self.mMarginXLabel.setText(_translate("QgsComposerLabelWidgetBase", "Horizontal margin", None))
        self.mMarginYDoubleSpinBox.setSuffix(_translate("QgsComposerLabelWidgetBase", " mm", None))
        self.mMarginYLabel.setText(_translate("QgsComposerLabelWidgetBase", "Vertical margin", None))

from qgscollapsiblegroupbox import QgsCollapsibleGroupBoxBasic
from qgsdoublespinbox import QgsDoubleSpinBox
from qgscolorbuttonv2 import QgsColorButtonV2
