# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qgscomposerbase.ui'
#
# Created: Tue Sep 20 17:45:03 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ComposerBase(object):
    def setupUi(self, ComposerBase):
        ComposerBase.setObjectName(_fromUtf8("ComposerBase"))
        ComposerBase.resize(1333, 609)
        ComposerBase.setMouseTracking(True)
        self.centralwidget = QtGui.QWidget(ComposerBase)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mViewFrame = QtGui.QFrame(self.centralwidget)
        self.mViewFrame.setMouseTracking(True)
        self.mViewFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mViewFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mViewFrame.setObjectName(_fromUtf8("mViewFrame"))
        self.scrollArea = QtGui.QScrollArea(self.mViewFrame)
        self.scrollArea.setGeometry(QtCore.QRect(280, 110, 120, 80))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 118, 78))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.mViewFrame, 0, 0, 1, 1)
        ComposerBase.setCentralWidget(self.centralwidget)
        self.mStatusBar = QtGui.QStatusBar(ComposerBase)
        self.mStatusBar.setObjectName(_fromUtf8("mStatusBar"))
        ComposerBase.setStatusBar(self.mStatusBar)
        self.mComposerToolbar = QtGui.QToolBar(ComposerBase)
        self.mComposerToolbar.setObjectName(_fromUtf8("mComposerToolbar"))
        ComposerBase.addToolBar(QtCore.Qt.TopToolBarArea, self.mComposerToolbar)
        self.mPaperNavToolbar = QtGui.QToolBar(ComposerBase)
        self.mPaperNavToolbar.setObjectName(_fromUtf8("mPaperNavToolbar"))
        ComposerBase.addToolBar(QtCore.Qt.TopToolBarArea, self.mPaperNavToolbar)
        ComposerBase.insertToolBarBreak(self.mPaperNavToolbar)
        self.mItemActionToolbar = QtGui.QToolBar(ComposerBase)
        self.mItemActionToolbar.setObjectName(_fromUtf8("mItemActionToolbar"))
        ComposerBase.addToolBar(QtCore.Qt.TopToolBarArea, self.mItemActionToolbar)
        ComposerBase.insertToolBarBreak(self.mItemActionToolbar)
        self.mItemToolbar = QtGui.QToolBar(ComposerBase)
        self.mItemToolbar.setObjectName(_fromUtf8("mItemToolbar"))
        ComposerBase.addToolBar(QtCore.Qt.TopToolBarArea, self.mItemToolbar)
        ComposerBase.insertToolBarBreak(self.mItemToolbar)
        self.mAtlasToolbar = QtGui.QToolBar(ComposerBase)
        self.mAtlasToolbar.setObjectName(_fromUtf8("mAtlasToolbar"))
        ComposerBase.addToolBar(QtCore.Qt.TopToolBarArea, self.mAtlasToolbar)
        ComposerBase.insertToolBarBreak(self.mAtlasToolbar)
        self.mActionPrint = QtGui.QAction(ComposerBase)
        self.mActionPrint.setCheckable(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionFilePrint.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionPrint.setIcon(icon)
        self.mActionPrint.setObjectName(_fromUtf8("mActionPrint"))
        self.mActionZoomAll = QtGui.QAction(ComposerBase)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionZoomFullExtent.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionZoomAll.setIcon(icon1)
        self.mActionZoomAll.setObjectName(_fromUtf8("mActionZoomAll"))
        self.mActionZoomIn = QtGui.QAction(ComposerBase)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionZoomIn.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionZoomIn.setIcon(icon2)
        self.mActionZoomIn.setObjectName(_fromUtf8("mActionZoomIn"))
        self.mActionZoomOut = QtGui.QAction(ComposerBase)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionZoomOut.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionZoomOut.setIcon(icon3)
        self.mActionZoomOut.setObjectName(_fromUtf8("mActionZoomOut"))
        self.mActionZoomActual = QtGui.QAction(ComposerBase)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionZoomActual.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionZoomActual.setIcon(icon4)
        self.mActionZoomActual.setObjectName(_fromUtf8("mActionZoomActual"))
        self.mActionMouseZoom = QtGui.QAction(ComposerBase)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionZoomToSelected.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionMouseZoom.setIcon(icon5)
        self.mActionMouseZoom.setObjectName(_fromUtf8("mActionMouseZoom"))
        self.mActionAddNewMap = QtGui.QAction(ComposerBase)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionAddMap.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionAddNewMap.setIcon(icon6)
        self.mActionAddNewMap.setObjectName(_fromUtf8("mActionAddNewMap"))
        self.mActionAddNewLabel = QtGui.QAction(ComposerBase)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionLabel.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionAddNewLabel.setIcon(icon7)
        self.mActionAddNewLabel.setObjectName(_fromUtf8("mActionAddNewLabel"))
        self.mActionAddNewLegend = QtGui.QAction(ComposerBase)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionAddLegend.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionAddNewLegend.setIcon(icon8)
        self.mActionAddNewLegend.setObjectName(_fromUtf8("mActionAddNewLegend"))
        self.mActionSelectMoveItem = QtGui.QAction(ComposerBase)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionPan.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionSelectMoveItem.setIcon(icon9)
        self.mActionSelectMoveItem.setObjectName(_fromUtf8("mActionSelectMoveItem"))
        self.mActionExportAsImage = QtGui.QAction(ComposerBase)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionSaveMapAsImage.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionExportAsImage.setIcon(icon10)
        self.mActionExportAsImage.setObjectName(_fromUtf8("mActionExportAsImage"))
        self.mActionExportAsPDF = QtGui.QAction(ComposerBase)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionSaveAsPDF.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionExportAsPDF.setIcon(icon11)
        self.mActionExportAsPDF.setObjectName(_fromUtf8("mActionExportAsPDF"))
        self.mActionExportAsSVG = QtGui.QAction(ComposerBase)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionSaveAsSVG.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionExportAsSVG.setIcon(icon12)
        self.mActionExportAsSVG.setObjectName(_fromUtf8("mActionExportAsSVG"))
        self.mActionAddNewScalebar = QtGui.QAction(ComposerBase)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionScaleBar.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionAddNewScalebar.setIcon(icon13)
        self.mActionAddNewScalebar.setObjectName(_fromUtf8("mActionAddNewScalebar"))
        self.mActionRefreshView = QtGui.QAction(ComposerBase)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionDraw.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionRefreshView.setIcon(icon14)
        self.mActionRefreshView.setObjectName(_fromUtf8("mActionRefreshView"))
        self.mActionShowGrid = QtGui.QAction(ComposerBase)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/default/vector_grid.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionShowGrid.setIcon(icon15)
        self.mActionShowGrid.setObjectName(_fromUtf8("mActionShowGrid"))
        self.mActionSnapGrid = QtGui.QAction(ComposerBase)
        self.mActionSnapGrid.setObjectName(_fromUtf8("mActionSnapGrid"))
        self.mActionShowGuides = QtGui.QAction(ComposerBase)
        self.mActionShowGuides.setObjectName(_fromUtf8("mActionShowGuides"))
        self.mActionSnapGuides = QtGui.QAction(ComposerBase)
        self.mActionSnapGuides.setObjectName(_fromUtf8("mActionSnapGuides"))
        self.mActionSmartGuides = QtGui.QAction(ComposerBase)
        self.mActionSmartGuides.setObjectName(_fromUtf8("mActionSmartGuides"))
        self.mActionClearGuides = QtGui.QAction(ComposerBase)
        self.mActionClearGuides.setObjectName(_fromUtf8("mActionClearGuides"))
        self.mActionAddImage = QtGui.QAction(ComposerBase)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionAddImage.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionAddImage.setIcon(icon16)
        self.mActionAddImage.setObjectName(_fromUtf8("mActionAddImage"))
        self.mActionMoveItemContent = QtGui.QAction(ComposerBase)
        self.mActionMoveItemContent.setObjectName(_fromUtf8("mActionMoveItemContent"))
        self.mActionGroupItems = QtGui.QAction(ComposerBase)
        self.mActionGroupItems.setObjectName(_fromUtf8("mActionGroupItems"))
        self.mActionUngroupItems = QtGui.QAction(ComposerBase)
        self.mActionUngroupItems.setObjectName(_fromUtf8("mActionUngroupItems"))
        self.mActionRaiseItems = QtGui.QAction(ComposerBase)
        self.mActionRaiseItems.setObjectName(_fromUtf8("mActionRaiseItems"))
        self.mActionLowerItems = QtGui.QAction(ComposerBase)
        self.mActionLowerItems.setObjectName(_fromUtf8("mActionLowerItems"))
        self.mActionMoveItemsToTop = QtGui.QAction(ComposerBase)
        self.mActionMoveItemsToTop.setObjectName(_fromUtf8("mActionMoveItemsToTop"))
        self.mActionMoveItemsToBottom = QtGui.QAction(ComposerBase)
        self.mActionMoveItemsToBottom.setObjectName(_fromUtf8("mActionMoveItemsToBottom"))
        self.mActionLoadFromTemplate = QtGui.QAction(ComposerBase)
        self.mActionLoadFromTemplate.setObjectName(_fromUtf8("mActionLoadFromTemplate"))
        self.mActionSaveAsTemplate = QtGui.QAction(ComposerBase)
        self.mActionSaveAsTemplate.setObjectName(_fromUtf8("mActionSaveAsTemplate"))
        self.mActionAlignLeft = QtGui.QAction(ComposerBase)
        self.mActionAlignLeft.setObjectName(_fromUtf8("mActionAlignLeft"))
        self.mActionAlignHCenter = QtGui.QAction(ComposerBase)
        self.mActionAlignHCenter.setObjectName(_fromUtf8("mActionAlignHCenter"))
        self.mActionAlignRight = QtGui.QAction(ComposerBase)
        self.mActionAlignRight.setObjectName(_fromUtf8("mActionAlignRight"))
        self.mActionAlignTop = QtGui.QAction(ComposerBase)
        self.mActionAlignTop.setObjectName(_fromUtf8("mActionAlignTop"))
        self.mActionAlignVCenter = QtGui.QAction(ComposerBase)
        self.mActionAlignVCenter.setObjectName(_fromUtf8("mActionAlignVCenter"))
        self.mActionAlignBottom = QtGui.QAction(ComposerBase)
        self.mActionAlignBottom.setObjectName(_fromUtf8("mActionAlignBottom"))
        self.mActionQuit = QtGui.QAction(ComposerBase)
        self.mActionQuit.setObjectName(_fromUtf8("mActionQuit"))
        self.mActionAddArrow = QtGui.QAction(ComposerBase)
        self.mActionAddArrow.setCheckable(True)
        self.mActionAddArrow.setObjectName(_fromUtf8("mActionAddArrow"))
        self.mActionAddTable = QtGui.QAction(ComposerBase)
        self.mActionAddTable.setCheckable(True)
        self.mActionAddTable.setObjectName(_fromUtf8("mActionAddTable"))
        self.mActionAddAttributeTable = QtGui.QAction(ComposerBase)
        self.mActionAddAttributeTable.setCheckable(True)
        self.mActionAddAttributeTable.setObjectName(_fromUtf8("mActionAddAttributeTable"))
        self.mActionPageSetup = QtGui.QAction(ComposerBase)
        self.mActionPageSetup.setObjectName(_fromUtf8("mActionPageSetup"))
        self.mActionUndo = QtGui.QAction(ComposerBase)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionUndo.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.mActionUndo.setIcon(icon17)
        self.mActionUndo.setObjectName(_fromUtf8("mActionUndo"))
        self.mActionRedo = QtGui.QAction(ComposerBase)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionRedo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionRedo.setIcon(icon18)
        self.mActionRedo.setObjectName(_fromUtf8("mActionRedo"))
        self.mActionAddRectangle = QtGui.QAction(ComposerBase)
        self.mActionAddRectangle.setCheckable(True)
        self.mActionAddRectangle.setObjectName(_fromUtf8("mActionAddRectangle"))
        self.mActionAddTriangle = QtGui.QAction(ComposerBase)
        self.mActionAddTriangle.setCheckable(True)
        self.mActionAddTriangle.setObjectName(_fromUtf8("mActionAddTriangle"))
        self.mActionAddEllipse = QtGui.QAction(ComposerBase)
        self.mActionAddEllipse.setCheckable(True)
        self.mActionAddEllipse.setObjectName(_fromUtf8("mActionAddEllipse"))
        self.mActionAddHtml = QtGui.QAction(ComposerBase)
        self.mActionAddHtml.setCheckable(True)
        self.mActionAddHtml.setObjectName(_fromUtf8("mActionAddHtml"))
        self.mActionComposerManager = QtGui.QAction(ComposerBase)
        self.mActionComposerManager.setObjectName(_fromUtf8("mActionComposerManager"))
        self.mActionNewComposer = QtGui.QAction(ComposerBase)
        self.mActionNewComposer.setObjectName(_fromUtf8("mActionNewComposer"))
        self.mActionSaveProject = QtGui.QAction(ComposerBase)
        self.mActionSaveProject.setObjectName(_fromUtf8("mActionSaveProject"))
        self.mActionDuplicateComposer = QtGui.QAction(ComposerBase)
        self.mActionDuplicateComposer.setObjectName(_fromUtf8("mActionDuplicateComposer"))
        self.mActionLockItems = QtGui.QAction(ComposerBase)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/locked.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionLockItems.setIcon(icon19)
        self.mActionLockItems.setObjectName(_fromUtf8("mActionLockItems"))
        self.mActionUnlockAll = QtGui.QAction(ComposerBase)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/unlocked.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionUnlockAll.setIcon(icon20)
        self.mActionUnlockAll.setObjectName(_fromUtf8("mActionUnlockAll"))
        self.mActionPasteInPlace = QtGui.QAction(ComposerBase)
        self.mActionPasteInPlace.setObjectName(_fromUtf8("mActionPasteInPlace"))
        self.mActionDeleteSelection = QtGui.QAction(ComposerBase)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionDeleteSelected.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionDeleteSelection.setIcon(icon21)
        self.mActionDeleteSelection.setObjectName(_fromUtf8("mActionDeleteSelection"))
        self.mActionDeselectAll = QtGui.QAction(ComposerBase)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionDeselectAll.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionDeselectAll.setIcon(icon22)
        self.mActionDeselectAll.setObjectName(_fromUtf8("mActionDeselectAll"))
        self.mActionSelectAll = QtGui.QAction(ComposerBase)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionSelectAll.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionSelectAll.setIcon(icon23)
        self.mActionSelectAll.setObjectName(_fromUtf8("mActionSelectAll"))
        self.mActionInvertSelection = QtGui.QAction(ComposerBase)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionInvertSelection.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionInvertSelection.setIcon(icon24)
        self.mActionInvertSelection.setObjectName(_fromUtf8("mActionInvertSelection"))
        self.mActionSelectNextBelow = QtGui.QAction(ComposerBase)
        self.mActionSelectNextBelow.setObjectName(_fromUtf8("mActionSelectNextBelow"))
        self.mActionSelectNextAbove = QtGui.QAction(ComposerBase)
        self.mActionSelectNextAbove.setObjectName(_fromUtf8("mActionSelectNextAbove"))
        self.mActionPan = QtGui.QAction(ComposerBase)
        self.mActionPan.setIcon(icon9)
        self.mActionPan.setObjectName(_fromUtf8("mActionPan"))
        self.mActionOptions = QtGui.QAction(ComposerBase)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionOptions.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionOptions.setIcon(icon25)
        self.mActionOptions.setMenuRole(QtGui.QAction.PreferencesRole)
        self.mActionOptions.setObjectName(_fromUtf8("mActionOptions"))
        self.mActionShowRulers = QtGui.QAction(ComposerBase)
        self.mActionShowRulers.setObjectName(_fromUtf8("mActionShowRulers"))
        self.mActionAtlasFirst = QtGui.QAction(ComposerBase)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionAtlasFirst.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionAtlasFirst.setIcon(icon26)
        self.mActionAtlasFirst.setObjectName(_fromUtf8("mActionAtlasFirst"))
        self.mActionAtlasPrev = QtGui.QAction(ComposerBase)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionAtlasPrev.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionAtlasPrev.setIcon(icon27)
        self.mActionAtlasPrev.setObjectName(_fromUtf8("mActionAtlasPrev"))
        self.mActionAtlasNext = QtGui.QAction(ComposerBase)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionAtlasNext.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionAtlasNext.setIcon(icon28)
        self.mActionAtlasNext.setObjectName(_fromUtf8("mActionAtlasNext"))
        self.mActionAtlasLast = QtGui.QAction(ComposerBase)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionAtlasLast.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionAtlasLast.setIcon(icon29)
        self.mActionAtlasLast.setObjectName(_fromUtf8("mActionAtlasLast"))
        self.mActionAtlasPreview = QtGui.QAction(ComposerBase)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mIconAtlas.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionAtlasPreview.setIcon(icon30)
        self.mActionAtlasPreview.setObjectName(_fromUtf8("mActionAtlasPreview"))
        self.mActionPrintAtlas = QtGui.QAction(ComposerBase)
        self.mActionPrintAtlas.setIcon(icon)
        self.mActionPrintAtlas.setObjectName(_fromUtf8("mActionPrintAtlas"))
        self.mActionExportAtlasAsImage = QtGui.QAction(ComposerBase)
        self.mActionExportAtlasAsImage.setIcon(icon10)
        self.mActionExportAtlasAsImage.setObjectName(_fromUtf8("mActionExportAtlasAsImage"))
        self.mActionExportAtlasAsSVG = QtGui.QAction(ComposerBase)
        self.mActionExportAtlasAsSVG.setIcon(icon12)
        self.mActionExportAtlasAsSVG.setObjectName(_fromUtf8("mActionExportAtlasAsSVG"))
        self.mActionExportAtlasAsPDF = QtGui.QAction(ComposerBase)
        self.mActionExportAtlasAsPDF.setIcon(icon11)
        self.mActionExportAtlasAsPDF.setObjectName(_fromUtf8("mActionExportAtlasAsPDF"))
        self.mActionAtlasSettings = QtGui.QAction(ComposerBase)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mActionAtlasSettings.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mActionAtlasSettings.setIcon(icon31)
        self.mActionAtlasSettings.setObjectName(_fromUtf8("mActionAtlasSettings"))
        self.mActionShowBoxes = QtGui.QAction(ComposerBase)
        self.mActionShowBoxes.setObjectName(_fromUtf8("mActionShowBoxes"))
        self.mActionToggleFullScreen = QtGui.QAction(ComposerBase)
        self.mActionToggleFullScreen.setCheckable(True)
        self.mActionToggleFullScreen.setObjectName(_fromUtf8("mActionToggleFullScreen"))
        self.mActionHidePanels = QtGui.QAction(ComposerBase)
        self.mActionHidePanels.setCheckable(True)
        self.mActionHidePanels.setObjectName(_fromUtf8("mActionHidePanels"))
        self.mActionShowPage = QtGui.QAction(ComposerBase)
        self.mActionShowPage.setCheckable(True)
        self.mActionShowPage.setObjectName(_fromUtf8("mActionShowPage"))
        self.mComposerToolbar.addAction(self.mActionSaveProject)
        self.mComposerToolbar.addSeparator()
        self.mComposerToolbar.addAction(self.mActionNewComposer)
        self.mComposerToolbar.addAction(self.mActionDuplicateComposer)
        self.mComposerToolbar.addAction(self.mActionComposerManager)
        self.mComposerToolbar.addAction(self.mActionLoadFromTemplate)
        self.mComposerToolbar.addAction(self.mActionSaveAsTemplate)
        self.mComposerToolbar.addSeparator()
        self.mComposerToolbar.addAction(self.mActionPrint)
        self.mComposerToolbar.addAction(self.mActionExportAsImage)
        self.mComposerToolbar.addAction(self.mActionExportAsSVG)
        self.mComposerToolbar.addAction(self.mActionExportAsPDF)
        self.mComposerToolbar.addAction(self.mActionUndo)
        self.mComposerToolbar.addAction(self.mActionRedo)
        self.mPaperNavToolbar.addAction(self.mActionZoomAll)
        self.mPaperNavToolbar.addAction(self.mActionZoomActual)
        self.mPaperNavToolbar.addAction(self.mActionZoomIn)
        self.mPaperNavToolbar.addAction(self.mActionZoomOut)
        self.mPaperNavToolbar.addAction(self.mActionRefreshView)
        self.mItemActionToolbar.addAction(self.mActionGroupItems)
        self.mItemActionToolbar.addAction(self.mActionUngroupItems)
        self.mItemActionToolbar.addAction(self.mActionLockItems)
        self.mItemActionToolbar.addAction(self.mActionUnlockAll)
        self.mItemToolbar.addAction(self.mActionPan)
        self.mItemToolbar.addAction(self.mActionMouseZoom)
        self.mItemToolbar.addAction(self.mActionSelectMoveItem)
        self.mItemToolbar.addAction(self.mActionMoveItemContent)
        self.mItemToolbar.addSeparator()
        self.mItemToolbar.addAction(self.mActionAddNewMap)
        self.mItemToolbar.addAction(self.mActionAddImage)
        self.mItemToolbar.addAction(self.mActionAddNewLabel)
        self.mItemToolbar.addAction(self.mActionAddNewLegend)
        self.mItemToolbar.addAction(self.mActionAddNewScalebar)
        self.mItemToolbar.addAction(self.mActionAddArrow)
        self.mItemToolbar.addAction(self.mActionAddAttributeTable)
        self.mItemToolbar.addAction(self.mActionAddHtml)
        self.mAtlasToolbar.addAction(self.mActionAtlasPreview)
        self.mAtlasToolbar.addAction(self.mActionAtlasFirst)
        self.mAtlasToolbar.addAction(self.mActionAtlasPrev)
        self.mAtlasToolbar.addAction(self.mActionAtlasNext)
        self.mAtlasToolbar.addAction(self.mActionAtlasLast)
        self.mAtlasToolbar.addAction(self.mActionPrintAtlas)
        self.mAtlasToolbar.addAction(self.mActionAtlasSettings)

        self.retranslateUi(ComposerBase)
        QtCore.QMetaObject.connectSlotsByName(ComposerBase)

    def retranslateUi(self, ComposerBase):
        ComposerBase.setWindowTitle(_translate("ComposerBase", "MainWindow", None))
        self.mComposerToolbar.setWindowTitle(_translate("ComposerBase", "Composer", None))
        self.mPaperNavToolbar.setWindowTitle(_translate("ComposerBase", "Navigation", None))
        self.mItemActionToolbar.setWindowTitle(_translate("ComposerBase", "Actions", None))
        self.mItemToolbar.setWindowTitle(_translate("ComposerBase", "Toolbox", None))
        self.mAtlasToolbar.setWindowTitle(_translate("ComposerBase", "Atlas", None))
        self.mActionPrint.setText(_translate("ComposerBase", "&Print...", None))
        self.mActionPrint.setShortcut(_translate("ComposerBase", "Ctrl+P", None))
        self.mActionZoomAll.setText(_translate("ComposerBase", "Zoom &Full", None))
        self.mActionZoomAll.setToolTip(_translate("ComposerBase", "Zoom full", None))
        self.mActionZoomAll.setShortcut(_translate("ComposerBase", "Ctrl+0", None))
        self.mActionZoomIn.setText(_translate("ComposerBase", "Zoom &In", None))
        self.mActionZoomIn.setToolTip(_translate("ComposerBase", "Zoom in", None))
        self.mActionZoomIn.setShortcut(_translate("ComposerBase", "Ctrl++", None))
        self.mActionZoomOut.setText(_translate("ComposerBase", "Zoom &Out", None))
        self.mActionZoomOut.setToolTip(_translate("ComposerBase", "Zoom out", None))
        self.mActionZoomOut.setShortcut(_translate("ComposerBase", "Ctrl+-", None))
        self.mActionZoomActual.setText(_translate("ComposerBase", "Zoom to &100%", None))
        self.mActionZoomActual.setToolTip(_translate("ComposerBase", "Zoom to 100%", None))
        self.mActionZoomActual.setShortcut(_translate("ComposerBase", "Ctrl+1", None))
        self.mActionMouseZoom.setText(_translate("ComposerBase", "Zoom", None))
        self.mActionMouseZoom.setToolTip(_translate("ComposerBase", "Zoom", None))
        self.mActionMouseZoom.setShortcut(_translate("ComposerBase", "Z", None))
        self.mActionAddNewMap.setText(_translate("ComposerBase", "Add &Map", None))
        self.mActionAddNewMap.setToolTip(_translate("ComposerBase", "Add new map", None))
        self.mActionAddNewLabel.setText(_translate("ComposerBase", "Add Lab&el", None))
        self.mActionAddNewLabel.setToolTip(_translate("ComposerBase", "Add new label", None))
        self.mActionAddNewLegend.setText(_translate("ComposerBase", "Add Legen&d", None))
        self.mActionAddNewLegend.setToolTip(_translate("ComposerBase", "Add new legend", None))
        self.mActionSelectMoveItem.setText(_translate("ComposerBase", "Move &Item", None))
        self.mActionSelectMoveItem.setToolTip(_translate("ComposerBase", "Select/Move item", None))
        self.mActionSelectMoveItem.setShortcut(_translate("ComposerBase", "V", None))
        self.mActionExportAsImage.setText(_translate("ComposerBase", "Export as &Image...", None))
        self.mActionExportAsImage.setToolTip(_translate("ComposerBase", "Export as image", None))
        self.mActionExportAsPDF.setText(_translate("ComposerBase", "&Export as PDF...", None))
        self.mActionExportAsSVG.setText(_translate("ComposerBase", "Export as S&VG...", None))
        self.mActionAddNewScalebar.setText(_translate("ComposerBase", "Add &Scalebar", None))
        self.mActionAddNewScalebar.setToolTip(_translate("ComposerBase", "Add new scalebar", None))
        self.mActionRefreshView.setText(_translate("ComposerBase", "&Refresh", None))
        self.mActionRefreshView.setToolTip(_translate("ComposerBase", "Refresh view", None))
        self.mActionRefreshView.setShortcut(_translate("ComposerBase", "F5", None))
        self.mActionShowGrid.setText(_translate("ComposerBase", "Show &Grid", None))
        self.mActionShowGrid.setToolTip(_translate("ComposerBase", "Show grid", None))
        self.mActionShowGrid.setShortcut(_translate("ComposerBase", "Ctrl+\'", None))
        self.mActionSnapGrid.setText(_translate("ComposerBase", "S&nap to Grid", None))
        self.mActionSnapGrid.setToolTip(_translate("ComposerBase", "Snap to grid", None))
        self.mActionSnapGrid.setShortcut(_translate("ComposerBase", "Ctrl+Shift+\'", None))
        self.mActionShowGuides.setText(_translate("ComposerBase", "Show G&uides", None))
        self.mActionShowGuides.setToolTip(_translate("ComposerBase", "Show guides", None))
        self.mActionShowGuides.setShortcut(_translate("ComposerBase", "Ctrl+;", None))
        self.mActionSnapGuides.setText(_translate("ComposerBase", "&Snap to Guides", None))
        self.mActionSnapGuides.setToolTip(_translate("ComposerBase", "Snap to guides", None))
        self.mActionSnapGuides.setShortcut(_translate("ComposerBase", "Ctrl+Shift+;", None))
        self.mActionSmartGuides.setText(_translate("ComposerBase", "S&mart Guides", None))
        self.mActionSmartGuides.setToolTip(_translate("ComposerBase", "Smart guides", None))
        self.mActionSmartGuides.setShortcut(_translate("ComposerBase", "Ctrl+Alt+;", None))
        self.mActionClearGuides.setText(_translate("ComposerBase", "&Clear Guides", None))
        self.mActionClearGuides.setToolTip(_translate("ComposerBase", "Clear guides", None))
        self.mActionAddImage.setText(_translate("ComposerBase", "Add Im&age", None))
        self.mActionAddImage.setToolTip(_translate("ComposerBase", "Add image", None))
        self.mActionMoveItemContent.setText(_translate("ComposerBase", "Move &Content", None))
        self.mActionMoveItemContent.setToolTip(_translate("ComposerBase", "Move item content", None))
        self.mActionMoveItemContent.setShortcut(_translate("ComposerBase", "C", None))
        self.mActionGroupItems.setText(_translate("ComposerBase", "&Group", None))
        self.mActionGroupItems.setToolTip(_translate("ComposerBase", "Group items", None))
        self.mActionGroupItems.setShortcut(_translate("ComposerBase", "Ctrl+G", None))
        self.mActionUngroupItems.setText(_translate("ComposerBase", "&Ungroup", None))
        self.mActionUngroupItems.setToolTip(_translate("ComposerBase", "Ungroup items", None))
        self.mActionUngroupItems.setShortcut(_translate("ComposerBase", "Ctrl+Shift+G", None))
        self.mActionRaiseItems.setText(_translate("ComposerBase", "&Raise", None))
        self.mActionRaiseItems.setToolTip(_translate("ComposerBase", "Raise selected items", None))
        self.mActionRaiseItems.setShortcut(_translate("ComposerBase", "Ctrl+]", None))
        self.mActionLowerItems.setText(_translate("ComposerBase", "&Lower", None))
        self.mActionLowerItems.setToolTip(_translate("ComposerBase", "Lower selected items", None))
        self.mActionLowerItems.setShortcut(_translate("ComposerBase", "Ctrl+[", None))
        self.mActionMoveItemsToTop.setText(_translate("ComposerBase", "Bring to &Front", None))
        self.mActionMoveItemsToTop.setToolTip(_translate("ComposerBase", "Move selected items to top", None))
        self.mActionMoveItemsToTop.setShortcut(_translate("ComposerBase", "Ctrl+Shift+]", None))
        self.mActionMoveItemsToBottom.setText(_translate("ComposerBase", "Send to &Back", None))
        self.mActionMoveItemsToBottom.setToolTip(_translate("ComposerBase", "Move selected items to bottom", None))
        self.mActionMoveItemsToBottom.setShortcut(_translate("ComposerBase", "Ctrl+Shift+[", None))
        self.mActionLoadFromTemplate.setText(_translate("ComposerBase", "&Add Items from Template...", None))
        self.mActionLoadFromTemplate.setToolTip(_translate("ComposerBase", "Add items from template", None))
        self.mActionSaveAsTemplate.setText(_translate("ComposerBase", "Save as &Template...", None))
        self.mActionSaveAsTemplate.setToolTip(_translate("ComposerBase", "Save as template", None))
        self.mActionAlignLeft.setText(_translate("ComposerBase", "Align Left", None))
        self.mActionAlignLeft.setToolTip(_translate("ComposerBase", "Align selected items left", None))
        self.mActionAlignHCenter.setText(_translate("ComposerBase", "Align Center", None))
        self.mActionAlignHCenter.setToolTip(_translate("ComposerBase", "Align center horizontal", None))
        self.mActionAlignRight.setText(_translate("ComposerBase", "Align Right", None))
        self.mActionAlignRight.setToolTip(_translate("ComposerBase", "Align selected items right", None))
        self.mActionAlignTop.setText(_translate("ComposerBase", "Align Top", None))
        self.mActionAlignTop.setToolTip(_translate("ComposerBase", "Align selected items to top", None))
        self.mActionAlignVCenter.setText(_translate("ComposerBase", "Align Center Vertical", None))
        self.mActionAlignVCenter.setToolTip(_translate("ComposerBase", "Align center vertical", None))
        self.mActionAlignBottom.setText(_translate("ComposerBase", "Align Bottom", None))
        self.mActionAlignBottom.setToolTip(_translate("ComposerBase", "Align selected items bottom", None))
        self.mActionQuit.setText(_translate("ComposerBase", "&Quit", None))
        self.mActionQuit.setToolTip(_translate("ComposerBase", "Quit", None))
        self.mActionQuit.setShortcut(_translate("ComposerBase", "Ctrl+Q", None))
        self.mActionAddArrow.setText(_translate("ComposerBase", "Add Arro&w", None))
        self.mActionAddArrow.setToolTip(_translate("ComposerBase", "Add arrow", None))
        self.mActionAddTable.setText(_translate("ComposerBase", "Add Table", None))
        self.mActionAddTable.setToolTip(_translate("ComposerBase", "Add table", None))
        self.mActionAddAttributeTable.setText(_translate("ComposerBase", "Add Attribute &Table", None))
        self.mActionAddAttributeTable.setToolTip(_translate("ComposerBase", "Add attribute table", None))
        self.mActionPageSetup.setText(_translate("ComposerBase", "Pa&ge Setup...", None))
        self.mActionPageSetup.setToolTip(_translate("ComposerBase", "Page setup", None))
        self.mActionPageSetup.setShortcut(_translate("ComposerBase", "Ctrl+Shift+P", None))
        self.mActionUndo.setText(_translate("ComposerBase", "&Undo", None))
        self.mActionUndo.setToolTip(_translate("ComposerBase", "Revert last change", None))
        self.mActionUndo.setShortcut(_translate("ComposerBase", "Ctrl+Z", None))
        self.mActionRedo.setText(_translate("ComposerBase", "&Redo", None))
        self.mActionRedo.setToolTip(_translate("ComposerBase", "Restore last change", None))
        self.mActionRedo.setShortcut(_translate("ComposerBase", "Ctrl+Shift+Z", None))
        self.mActionAddRectangle.setText(_translate("ComposerBase", "Add Rectangle", None))
        self.mActionAddRectangle.setToolTip(_translate("ComposerBase", "Add rectangle", None))
        self.mActionAddTriangle.setText(_translate("ComposerBase", "Add Triangle", None))
        self.mActionAddTriangle.setToolTip(_translate("ComposerBase", "Add triangle", None))
        self.mActionAddEllipse.setText(_translate("ComposerBase", "Add Ellipse", None))
        self.mActionAddEllipse.setToolTip(_translate("ComposerBase", "Add ellipse", None))
        self.mActionAddHtml.setText(_translate("ComposerBase", "Add &HTML", None))
        self.mActionAddHtml.setToolTip(_translate("ComposerBase", "Add HTML frame", None))
        self.mActionComposerManager.setText(_translate("ComposerBase", "Composer &Manager...", None))
        self.mActionComposerManager.setToolTip(_translate("ComposerBase", "Composer manager", None))
        self.mActionNewComposer.setText(_translate("ComposerBase", "&New Composer...", None))
        self.mActionNewComposer.setToolTip(_translate("ComposerBase", "New composer", None))
        self.mActionNewComposer.setShortcut(_translate("ComposerBase", "Ctrl+N", None))
        self.mActionSaveProject.setText(_translate("ComposerBase", "&Save Project", None))
        self.mActionSaveProject.setToolTip(_translate("ComposerBase", "Save project", None))
        self.mActionSaveProject.setShortcut(_translate("ComposerBase", "Ctrl+S", None))
        self.mActionDuplicateComposer.setText(_translate("ComposerBase", "&Duplicate Composer...", None))
        self.mActionDuplicateComposer.setToolTip(_translate("ComposerBase", "Duplicate composer", None))
        self.mActionLockItems.setText(_translate("ComposerBase", "Loc&k Selected Items", None))
        self.mActionLockItems.setShortcut(_translate("ComposerBase", "Ctrl+L", None))
        self.mActionUnlockAll.setText(_translate("ComposerBase", "Unl&ock All", None))
        self.mActionUnlockAll.setToolTip(_translate("ComposerBase", "Unlock All Items", None))
        self.mActionUnlockAll.setShortcut(_translate("ComposerBase", "Ctrl+Shift+L", None))
        self.mActionPasteInPlace.setText(_translate("ComposerBase", "Paste in P&lace", None))
        self.mActionPasteInPlace.setToolTip(_translate("ComposerBase", "Paste in place", None))
        self.mActionPasteInPlace.setShortcut(_translate("ComposerBase", "Ctrl+Shift+V", None))
        self.mActionDeleteSelection.setText(_translate("ComposerBase", "&Delete", None))
        self.mActionDeleteSelection.setToolTip(_translate("ComposerBase", "Delete selected items", None))
        self.mActionDeleteSelection.setShortcut(_translate("ComposerBase", "Del", None))
        self.mActionDeselectAll.setText(_translate("ComposerBase", "D&eselect All", None))
        self.mActionDeselectAll.setToolTip(_translate("ComposerBase", "Deselect all", None))
        self.mActionDeselectAll.setShortcut(_translate("ComposerBase", "Ctrl+Shift+A", None))
        self.mActionSelectAll.setText(_translate("ComposerBase", "&Select All", None))
        self.mActionSelectAll.setToolTip(_translate("ComposerBase", "Select all items", None))
        self.mActionSelectAll.setShortcut(_translate("ComposerBase", "Ctrl+A", None))
        self.mActionInvertSelection.setText(_translate("ComposerBase", "&Invert Selection", None))
        self.mActionInvertSelection.setToolTip(_translate("ComposerBase", "Invert selection", None))
        self.mActionSelectNextBelow.setText(_translate("ComposerBase", "Select Next Item &Below", None))
        self.mActionSelectNextBelow.setToolTip(_translate("ComposerBase", "Select next item below", None))
        self.mActionSelectNextBelow.setShortcut(_translate("ComposerBase", "Ctrl+Alt+[", None))
        self.mActionSelectNextAbove.setText(_translate("ComposerBase", "Select Next Item &Above", None))
        self.mActionSelectNextAbove.setToolTip(_translate("ComposerBase", "Select next item above", None))
        self.mActionSelectNextAbove.setShortcut(_translate("ComposerBase", "Ctrl+Alt+]", None))
        self.mActionPan.setText(_translate("ComposerBase", "Pan Composer", None))
        self.mActionPan.setShortcut(_translate("ComposerBase", "P", None))
        self.mActionOptions.setText(_translate("ComposerBase", "Composer &Options...", None))
        self.mActionShowRulers.setText(_translate("ComposerBase", "Show Ru&lers", None))
        self.mActionShowRulers.setToolTip(_translate("ComposerBase", "Show rulers", None))
        self.mActionShowRulers.setShortcut(_translate("ComposerBase", "Ctrl+R", None))
        self.mActionAtlasFirst.setText(_translate("ComposerBase", "&First Feature", None))
        self.mActionAtlasFirst.setShortcut(_translate("ComposerBase", "Ctrl+<", None))
        self.mActionAtlasPrev.setText(_translate("ComposerBase", "P&revious Feature", None))
        self.mActionAtlasPrev.setShortcut(_translate("ComposerBase", "Ctrl+,", None))
        self.mActionAtlasNext.setText(_translate("ComposerBase", "&Next Feature", None))
        self.mActionAtlasNext.setShortcut(_translate("ComposerBase", "Ctrl+.", None))
        self.mActionAtlasLast.setText(_translate("ComposerBase", "&Last Feature", None))
        self.mActionAtlasLast.setShortcut(_translate("ComposerBase", "Ctrl+>", None))
        self.mActionAtlasPreview.setText(_translate("ComposerBase", "Preview &Atlas", None))
        self.mActionAtlasPreview.setShortcut(_translate("ComposerBase", "Ctrl+Alt+/", None))
        self.mActionPrintAtlas.setText(_translate("ComposerBase", "&Print Atlas...", None))
        self.mActionExportAtlasAsImage.setText(_translate("ComposerBase", "Export Atlas as &Images...", None))
        self.mActionExportAtlasAsSVG.setText(_translate("ComposerBase", "Export Atlas as S&VG...", None))
        self.mActionExportAtlasAsPDF.setText(_translate("ComposerBase", "&Export Atlas as PDF...", None))
        self.mActionExportAtlasAsPDF.setToolTip(_translate("ComposerBase", "Export Atlas as PDF", None))
        self.mActionAtlasSettings.setText(_translate("ComposerBase", "Atlas &Settings", None))
        self.mActionShowBoxes.setText(_translate("ComposerBase", "Show Bounding Boxes", None))
        self.mActionShowBoxes.setToolTip(_translate("ComposerBase", "Show bounding boxes", None))
        self.mActionShowBoxes.setShortcut(_translate("ComposerBase", "Ctrl+Shift+B", None))
        self.mActionToggleFullScreen.setText(_translate("ComposerBase", "Toggle Full Scr&een", None))
        self.mActionToggleFullScreen.setToolTip(_translate("ComposerBase", "Toggle full screen mode", None))
        self.mActionToggleFullScreen.setShortcut(_translate("ComposerBase", "F11", None))
        self.mActionHidePanels.setText(_translate("ComposerBase", "&Hide Panels", None))
        self.mActionHidePanels.setToolTip(_translate("ComposerBase", "Hide panels", None))
        self.mActionHidePanels.setShortcut(_translate("ComposerBase", "F10", None))
        self.mActionShowPage.setText(_translate("ComposerBase", "Show Pages", None))
        self.mActionShowPage.setToolTip(_translate("ComposerBase", "Show pages", None))

