# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'self.ui'
#
# Created: Tue Jun 21 15:00:34 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from qgis.gui import QgsFieldComboBox, QgsCollapsibleGroupBoxBasic, QgsFieldExpressionWidget, QgsMapLayerComboBox

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class QgsAtlasCompositionWidgetBase(QtGui.QWidget):
    def __init__(self, parent):
        QtGui.QWidget.__init__(self, parent)
        # self.setObjectName(_fromUtf8("QgsAtlasCompositionWidgetBase"))
        self.resize(435, 359)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(self)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalFrame = QtGui.QFrame(self)
        self.verticalFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.verticalFrame.setObjectName(_fromUtf8("verticalFrame"))
        self.gridLayout = QtGui.QGridLayout(self.verticalFrame)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mUseAtlasCheckBox = QtGui.QCheckBox(self.verticalFrame)
        self.mUseAtlasCheckBox.setObjectName(_fromUtf8("mUseAtlasCheckBox"))
        self.gridLayout.addWidget(self.mUseAtlasCheckBox, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(12, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.verticalFrame)
        self.scrollArea.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 431, 332))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.mainLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.mainLayout.setContentsMargins(-1, -1, -1, 0)
        self.mainLayout.setObjectName(_fromUtf8("mainLayout"))
        self.mConfigurationGroup = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.mConfigurationGroup.setEnabled(False)
        self.mConfigurationGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mConfigurationGroup.setCheckable(False)
        self.mConfigurationGroup.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mConfigurationGroup.setProperty("collapsed", False)
        self.mConfigurationGroup.setObjectName(_fromUtf8("mConfigurationGroup"))
        self.gridLayout_2 = QtGui.QGridLayout(self.mConfigurationGroup)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mAtlasSortFeatureDirectionButton = QtGui.QToolButton(self.mConfigurationGroup)
        self.mAtlasSortFeatureDirectionButton.setArrowType(QtCore.Qt.UpArrow)
        self.mAtlasSortFeatureDirectionButton.setObjectName(_fromUtf8("mAtlasSortFeatureDirectionButton"))
        self.gridLayout_2.addWidget(self.mAtlasSortFeatureDirectionButton, 4, 2, 1, 1)
        self.mAtlasSortFeatureKeyComboBox = QgsFieldComboBox(self.mConfigurationGroup)
        self.mAtlasSortFeatureKeyComboBox.setObjectName(_fromUtf8("mAtlasSortFeatureKeyComboBox"))
        self.gridLayout_2.addWidget(self.mAtlasSortFeatureKeyComboBox, 4, 1, 1, 1)
        self.mAtlasFeatureFilterCheckBox = QtGui.QCheckBox(self.mConfigurationGroup)
        self.mAtlasFeatureFilterCheckBox.setObjectName(_fromUtf8("mAtlasFeatureFilterCheckBox"))
        self.gridLayout_2.addWidget(self.mAtlasFeatureFilterCheckBox, 3, 0, 1, 1)
        self.mAtlasFeatureFilterButton = QtGui.QToolButton(self.mConfigurationGroup)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mIconExpression.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mAtlasFeatureFilterButton.setIcon(icon)
        self.mAtlasFeatureFilterButton.setObjectName(_fromUtf8("mAtlasFeatureFilterButton"))
        self.gridLayout_2.addWidget(self.mAtlasFeatureFilterButton, 3, 2, 1, 1)
        self.mAtlasHideCoverageCheckBox = QtGui.QCheckBox(self.mConfigurationGroup)
        self.mAtlasHideCoverageCheckBox.setObjectName(_fromUtf8("mAtlasHideCoverageCheckBox"))
        self.gridLayout_2.addWidget(self.mAtlasHideCoverageCheckBox, 1, 0, 1, 3)
        self.mHorizontalAlignementLabel = QtGui.QLabel(self.mConfigurationGroup)
        self.mHorizontalAlignementLabel.setObjectName(_fromUtf8("mHorizontalAlignementLabel"))
        self.gridLayout_2.addWidget(self.mHorizontalAlignementLabel, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.mConfigurationGroup)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.mAtlasFeatureFilterEdit = QtGui.QLineEdit(self.mConfigurationGroup)
        self.mAtlasFeatureFilterEdit.setObjectName(_fromUtf8("mAtlasFeatureFilterEdit"))
        self.gridLayout_2.addWidget(self.mAtlasFeatureFilterEdit, 3, 1, 1, 1)
        self.mAtlasCoverageLayerComboBox = QgsMapLayerComboBox(self.mConfigurationGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mAtlasCoverageLayerComboBox.sizePolicy().hasHeightForWidth())
        self.mAtlasCoverageLayerComboBox.setSizePolicy(sizePolicy)
        self.mAtlasCoverageLayerComboBox.setObjectName(_fromUtf8("mAtlasCoverageLayerComboBox"))
        self.gridLayout_2.addWidget(self.mAtlasCoverageLayerComboBox, 0, 1, 1, 2)
        self.mPageNameWidget = QgsFieldExpressionWidget(self.mConfigurationGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mPageNameWidget.sizePolicy().hasHeightForWidth())
        self.mPageNameWidget.setSizePolicy(sizePolicy)
        self.mPageNameWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mPageNameWidget.setObjectName(_fromUtf8("mPageNameWidget"))
        self.gridLayout_2.addWidget(self.mPageNameWidget, 2, 1, 1, 2)
        self.mAtlasSortFeatureCheckBox = QtGui.QCheckBox(self.mConfigurationGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mAtlasSortFeatureCheckBox.sizePolicy().hasHeightForWidth())
        self.mAtlasSortFeatureCheckBox.setSizePolicy(sizePolicy)
        self.mAtlasSortFeatureCheckBox.setObjectName(_fromUtf8("mAtlasSortFeatureCheckBox"))
        self.gridLayout_2.addWidget(self.mAtlasSortFeatureCheckBox, 4, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.mainLayout.addWidget(self.mConfigurationGroup)
        self.mOutputGroup = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.mOutputGroup.setEnabled(False)
        self.mOutputGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mOutputGroup.setCheckable(False)
        self.mOutputGroup.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mOutputGroup.setProperty("collapsed", False)
        self.mOutputGroup.setObjectName(_fromUtf8("mOutputGroup"))
        self.gridLayout_3 = QtGui.QGridLayout(self.mOutputGroup)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.mOutputGroup)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 2)
        self.mAtlasFilenameExpressionButton = QtGui.QToolButton(self.mOutputGroup)
        self.mAtlasFilenameExpressionButton.setIcon(icon)
        self.mAtlasFilenameExpressionButton.setObjectName(_fromUtf8("mAtlasFilenameExpressionButton"))
        self.gridLayout_3.addWidget(self.mAtlasFilenameExpressionButton, 1, 2, 1, 1)
        self.mAtlasFilenamePatternEdit = QtGui.QLineEdit(self.mOutputGroup)
        self.mAtlasFilenamePatternEdit.setObjectName(_fromUtf8("mAtlasFilenamePatternEdit"))
        self.gridLayout_3.addWidget(self.mAtlasFilenamePatternEdit, 1, 0, 1, 2)
        self.mAtlasSingleFileCheckBox = QtGui.QCheckBox(self.mOutputGroup)
        self.mAtlasSingleFileCheckBox.setObjectName(_fromUtf8("mAtlasSingleFileCheckBox"))
        self.gridLayout_3.addWidget(self.mAtlasSingleFileCheckBox, 2, 0, 1, 3)
        self.mainLayout.addWidget(self.mOutputGroup)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 3)
        self.verticalLayout.addWidget(self.verticalFrame)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self.setTabOrder(self.mUseAtlasCheckBox, self.mConfigurationGroup)
        self.setTabOrder(self.mConfigurationGroup, self.mAtlasCoverageLayerComboBox)
        self.setTabOrder(self.mAtlasCoverageLayerComboBox, self.mAtlasHideCoverageCheckBox)
        self.setTabOrder(self.mAtlasHideCoverageCheckBox, self.mAtlasFeatureFilterCheckBox)
        self.setTabOrder(self.mAtlasFeatureFilterCheckBox, self.mAtlasFeatureFilterEdit)
        self.setTabOrder(self.mAtlasFeatureFilterEdit, self.mAtlasFeatureFilterButton)
        self.setTabOrder(self.mAtlasFeatureFilterButton, self.mAtlasSortFeatureCheckBox)
        self.setTabOrder(self.mAtlasSortFeatureCheckBox, self.mAtlasSortFeatureKeyComboBox)
        self.setTabOrder(self.mAtlasSortFeatureKeyComboBox, self.mAtlasSortFeatureDirectionButton)
        self.setTabOrder(self.mAtlasSortFeatureDirectionButton, self.mOutputGroup)
        self.setTabOrder(self.mOutputGroup, self.mAtlasFilenamePatternEdit)
        self.setTabOrder(self.mAtlasFilenamePatternEdit, self.mAtlasFilenameExpressionButton)
        self.setTabOrder(self.mAtlasFilenameExpressionButton, self.mAtlasSingleFileCheckBox)
        self.setTabOrder(self.mAtlasSingleFileCheckBox, self.scrollArea)

    def retranslateUi(self):
        self.setWindowTitle(_translate("self", "Atlas Generation", None))
        self.mUseAtlasCheckBox.setText(_translate("self", "Generate an atlas", None))
        self.mConfigurationGroup.setTitle(_translate("self", "Configuration", None))
        self.mAtlasSortFeatureDirectionButton.setToolTip(_translate("self", "Sort direction", None))
        self.mAtlasSortFeatureDirectionButton.setText(_translate("self", "...", None))
        self.mAtlasFeatureFilterCheckBox.setText(_translate("self", "Filter with", None))
        self.mAtlasFeatureFilterButton.setText(_translate("self", "...", None))
        self.mAtlasHideCoverageCheckBox.setText(_translate("self", "Hidden coverage layer", None))
        self.mHorizontalAlignementLabel.setText(_translate("self", "Coverage layer ", None))
        self.label.setText(_translate("self", "Page name", None))
        self.mAtlasSortFeatureCheckBox.setText(_translate("self", "Sort by", None))
        self.mOutputGroup.setTitle(_translate("self", "Output", None))
        self.label_4.setText(_translate("self", "Output filename expression", None))
        self.mAtlasFilenameExpressionButton.setText(_translate("self", "...", None))
        self.mAtlasSingleFileCheckBox.setText(_translate("self", "Single file export when possible", None))


