# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableEditWidget.ui'
#
# Created: Tue Oct 04 13:02:57 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class TableEditWidget(QtGui.QWidget):
    def __init__(self, parent):
        QtGui.QWidget.__init__(self, parent)
        self.setObjectName(_fromUtf8("Ui_TableEditWidget"))
        self.resize(320, 309)
        self.vLayoutForm = QtGui.QVBoxLayout(self)
        self.vLayoutForm.setObjectName(_fromUtf8("vLayoutForm"))

        self.frmLocation = QtGui.QFrame(self)
        self.frmLocation.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmLocation.setFrameShadow(QtGui.QFrame.Raised)
        self.frmLocation.setObjectName(_fromUtf8("frmLocation"))
        self.vLayoutLocation = QtGui.QVBoxLayout(self.frmLocation)
        self.vLayoutLocation.setObjectName(_fromUtf8("vLayoutLocation"))
        self.frmX = QtGui.QFrame(self.frmLocation)
        self.frmX.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmX.setFrameShadow(QtGui.QFrame.Raised)
        self.frmX.setObjectName(_fromUtf8("frmX"))
        self.hLayoutX = QtGui.QHBoxLayout(self.frmX)
        self.hLayoutX.setSpacing(0)
        self.hLayoutX.setMargin(0)
        self.hLayoutX.setObjectName(_fromUtf8("hLayoutX"))
        self.labelX = QtGui.QLabel(self.frmX)
        self.labelX.setMinimumSize(QtCore.QSize(70, 0))
        self.labelX.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelX.setFont(font)
        self.labelX.setObjectName(_fromUtf8("labelX"))
        self.hLayoutX.addWidget(self.labelX)
        self.spinBoxX = QtGui.QSpinBox(self.frmX)
        self.spinBoxX.setMaximum(9999)
        self.spinBoxX.setObjectName(_fromUtf8("spinBoxX"))
        self.hLayoutX.addWidget(self.spinBoxX)
        self.vLayoutLocation.addWidget(self.frmX)
        self.frmY = QtGui.QFrame(self.frmLocation)
        self.frmY.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmY.setFrameShadow(QtGui.QFrame.Raised)
        self.frmY.setObjectName(_fromUtf8("frmY"))
        self.hLayoutY = QtGui.QHBoxLayout(self.frmY)
        self.hLayoutY.setSpacing(0)
        self.hLayoutY.setMargin(0)
        self.hLayoutY.setObjectName(_fromUtf8("hLayoutY"))
        self.labelY = QtGui.QLabel(self.frmY)
        self.labelY.setMinimumSize(QtCore.QSize(70, 0))
        self.labelY.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelY.setFont(font)
        self.labelY.setObjectName(_fromUtf8("labelY"))
        self.hLayoutY.addWidget(self.labelY)
        self.spinBoxY = QtGui.QSpinBox(self.frmY)
        self.spinBoxY.setMaximum(9999)
        self.spinBoxY.setObjectName(_fromUtf8("spinBoxY"))
        self.hLayoutY.addWidget(self.spinBoxY)
        self.vLayoutLocation.addWidget(self.frmY)
        self.frmWidth = QtGui.QFrame(self.frmLocation)
        self.frmWidth.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmWidth.setFrameShadow(QtGui.QFrame.Raised)
        self.frmWidth.setObjectName(_fromUtf8("frmWidth"))
        self.hLayoutWidth = QtGui.QHBoxLayout(self.frmWidth)
        self.hLayoutWidth.setSpacing(0)
        self.hLayoutWidth.setMargin(0)
        self.hLayoutWidth.setObjectName(_fromUtf8("hLayoutWidth"))
        self.labelWidth = QtGui.QLabel(self.frmWidth)
        self.labelWidth.setMinimumSize(QtCore.QSize(70, 0))
        self.labelWidth.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelWidth.setFont(font)
        self.labelWidth.setObjectName(_fromUtf8("labelWidth"))
        self.hLayoutWidth.addWidget(self.labelWidth)
        self.spinBoxWidth = QtGui.QSpinBox(self.frmWidth)
        self.spinBoxWidth.setMaximum(9999)
        self.spinBoxWidth.setObjectName(_fromUtf8("spinBoxWidth"))
        self.hLayoutWidth.addWidget(self.spinBoxWidth)
        self.vLayoutLocation.addWidget(self.frmWidth)
        self.frmHeight = QtGui.QFrame(self.frmLocation)
        self.frmHeight.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmHeight.setFrameShadow(QtGui.QFrame.Raised)
        self.frmHeight.setObjectName(_fromUtf8("frmHeight"))
        self.hLayoutHeight = QtGui.QHBoxLayout(self.frmHeight)
        self.hLayoutHeight.setSpacing(0)
        self.hLayoutHeight.setMargin(0)
        self.hLayoutHeight.setObjectName(_fromUtf8("hLayoutHeight"))
        self.labelHeight = QtGui.QLabel(self.frmHeight)
        self.labelHeight.setMinimumSize(QtCore.QSize(70, 0))
        self.labelHeight.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelHeight.setFont(font)
        self.labelHeight.setObjectName(_fromUtf8("labelHeight"))
        self.hLayoutHeight.addWidget(self.labelHeight)
        self.spinBoxHeight = QtGui.QSpinBox(self.frmHeight)
        self.spinBoxHeight.setMaximum(9999)
        self.spinBoxHeight.setObjectName(_fromUtf8("spinBoxHeight"))
        self.hLayoutHeight.addWidget(self.spinBoxHeight)
        self.vLayoutLocation.addWidget(self.frmHeight)
        self.vLayoutForm.addWidget(self.frmLocation)

        self.frmFont = QtGui.QFrame(self)
        self.frmFont.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmFont.setFrameShadow(QtGui.QFrame.Raised)
        self.frmFont.setObjectName(_fromUtf8("frmFont"))
        self.vLayoutFont = QtGui.QVBoxLayout(self.frmFont)
        self.vLayoutFont.setObjectName(_fromUtf8("vLayoutFont"))
        self.frmFontVal = QtGui.QFrame(self.frmFont)
        self.frmFontVal.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmFontVal.setFrameShadow(QtGui.QFrame.Raised)
        self.frmFontVal.setObjectName(_fromUtf8("frmFontVal"))
        self.hLayoutFontVal = QtGui.QHBoxLayout(self.frmFontVal)
        self.hLayoutFontVal.setSpacing(0)
        self.hLayoutFontVal.setMargin(0)
        self.hLayoutFontVal.setObjectName(_fromUtf8("hLayoutFontVal"))
        self.labelFont = QtGui.QLabel(self.frmFontVal)
        self.labelFont.setMinimumSize(QtCore.QSize(70, 0))
        self.labelFont.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelFont.setFont(font)
        self.labelFont.setObjectName(_fromUtf8("labelFont"))
        self.hLayoutFontVal.addWidget(self.labelFont)
        self.txtFontSize = QtGui.QLineEdit(self.frmFontVal)
        self.txtFontSize.setObjectName(_fromUtf8("txtFontSize"))
        self.txtFontSize.setText("6")
        self.hLayoutFontVal.addWidget(self.txtFontSize)
        self.vLayoutFont.addWidget(self.frmFontVal)
        self.vLayoutForm.addWidget(self.frmFont)

        self.mTableView = QtGui.QTableView(self)
        self.mTableView.setObjectName(_fromUtf8("mTableView"))
        self.vLayoutForm.addWidget(self.mTableView)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        self.setWindowTitle(_translate("Form", "Table Edit", None))
        self.labelX.setText(_translate("Form", "X:", None))
        self.labelY.setText(_translate("Form", "Y:", None))
        self.labelWidth.setText(_translate("Form", "width:", None))
        self.labelHeight.setText(_translate("Form", "height:", None))
        self.labelFont.setText(_translate("Form", "Font Size:", None))

