# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qgscomposermapwidgetbase.ui'
#
# Created: Tue Sep 20 17:44:56 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from qgis.gui import QgsSpinBox, QgsBlendModeComboBox, QgsDataDefinedButton, QgsCollapsibleGroupBoxBasic,\
    QgsDoubleSpinBox, QgsColorButtonV2
# from qgsspinbox import QgsSpinBox
# from qgsblendmodecombobox import QgsBlendModeComboBox
# from qgsdatadefinedbutton import QgsDataDefinedButton
# from qgscollapsiblegroupbox import QgsCollapsibleGroupBoxBasic
# from qgsdoublespinbox import QgsDoubleSpinBox
# from qgscolorbuttonv2 import QgsColorButtonV2
# import images_rc
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QgsComposerMapWidgetBase(QtGui.QWidget):
    def __init__(self, parent):
        QtGui.QWidget.__init__(self, parent)
        self.setObjectName(_fromUtf8("self"))
        self.resize(457, 1086)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtGui.QVBoxLayout(self)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mLabel = QtGui.QLabel(self)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mLabel.sizePolicy().hasHeightForWidth())
        self.mLabel.setSizePolicy(sizePolicy)
        self.mLabel.setStyleSheet(_fromUtf8("padding: 2px; font-weight: bold; background-color: rgb(200, 200, 200);"))
        self.mLabel.setObjectName(_fromUtf8("mLabel"))
        self.verticalLayout_2.addWidget(self.mLabel)
        self.scrollArea = QtGui.QScrollArea(self)
        self.scrollArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -1446, 444, 2493))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.mainLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.mainLayout.setObjectName(_fromUtf8("mainLayout"))
        self.groupBox = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.groupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.groupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.groupBox.setProperty("collapsed", False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.mPreviewModeComboBox = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mPreviewModeComboBox.sizePolicy().hasHeightForWidth())
        self.mPreviewModeComboBox.setSizePolicy(sizePolicy)
        self.mPreviewModeComboBox.setObjectName(_fromUtf8("mPreviewModeComboBox"))
        self.horizontalLayout_2.addWidget(self.mPreviewModeComboBox)
        self.mUpdatePreviewButton = QtGui.QPushButton(self.groupBox)
        self.mUpdatePreviewButton.setObjectName(_fromUtf8("mUpdatePreviewButton"))
        self.horizontalLayout_2.addWidget(self.mUpdatePreviewButton)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 3)
        self.mDrawCanvasItemsCheckBox = QtGui.QCheckBox(self.groupBox)
        self.mDrawCanvasItemsCheckBox.setObjectName(_fromUtf8("mDrawCanvasItemsCheckBox"))
        self.gridLayout_5.addWidget(self.mDrawCanvasItemsCheckBox, 4, 0, 1, 3)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.mScaleLineEdit = QtGui.QLineEdit(self.groupBox)
        self.mScaleLineEdit.setInputMask(_fromUtf8(""))
        self.mScaleLineEdit.setObjectName(_fromUtf8("mScaleLineEdit"))
        self.horizontalLayout_6.addWidget(self.mScaleLineEdit)
        self.mScaleDDBtn = QgsDataDefinedButton(self.groupBox)
        self.mScaleDDBtn.setObjectName(_fromUtf8("mScaleDDBtn"))
        self.horizontalLayout_6.addWidget(self.mScaleDDBtn)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 1, 2, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.mKeepLayerListCheckBox = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mKeepLayerListCheckBox.sizePolicy().hasHeightForWidth())
        self.mKeepLayerListCheckBox.setSizePolicy(sizePolicy)
        self.mKeepLayerListCheckBox.setObjectName(_fromUtf8("mKeepLayerListCheckBox"))
        self.horizontalLayout_10.addWidget(self.mKeepLayerListCheckBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.mLayerListFromPresetButton = QtGui.QToolButton(self.groupBox)
        self.mLayerListFromPresetButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.mLayerListFromPresetButton.setObjectName(_fromUtf8("mLayerListFromPresetButton"))
        self.horizontalLayout_10.addWidget(self.mLayerListFromPresetButton)
        self.mLayersDDBtn = QgsDataDefinedButton(self.groupBox)
        self.mLayersDDBtn.setObjectName(_fromUtf8("mLayersDDBtn"))
        self.horizontalLayout_10.addWidget(self.mLayersDDBtn)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 5, 0, 1, 3)
        self.mMapRotationLabel = QtGui.QLabel(self.groupBox)
        self.mMapRotationLabel.setObjectName(_fromUtf8("mMapRotationLabel"))
        self.gridLayout_5.addWidget(self.mMapRotationLabel, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.mMapRotationSpinBox = QgsDoubleSpinBox(self.groupBox)
        self.mMapRotationSpinBox.setMaximum(360.0)
        self.mMapRotationSpinBox.setObjectName(_fromUtf8("mMapRotationSpinBox"))
        self.horizontalLayout_7.addWidget(self.mMapRotationSpinBox)
        self.mMapRotationDDBtn = QgsDataDefinedButton(self.groupBox)
        self.mMapRotationDDBtn.setObjectName(_fromUtf8("mMapRotationDDBtn"))
        self.horizontalLayout_7.addWidget(self.mMapRotationDDBtn)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 2, 2, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.mKeepLayerStylesCheckBox = QtGui.QCheckBox(self.groupBox)
        self.mKeepLayerStylesCheckBox.setObjectName(_fromUtf8("mKeepLayerStylesCheckBox"))
        self.horizontalLayout_12.addWidget(self.mKeepLayerStylesCheckBox)
        self.mStylePresetsDDBtn = QgsDataDefinedButton(self.groupBox)
        self.mStylePresetsDDBtn.setObjectName(_fromUtf8("mStylePresetsDDBtn"))
        self.horizontalLayout_12.addWidget(self.mStylePresetsDDBtn)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 8, 0, 1, 3)
        self.mainLayout.addWidget(self.groupBox)
        self.mExtentsCheckBox = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.mExtentsCheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mExtentsCheckBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mExtentsCheckBox.setProperty("collapsed", False)
        self.mExtentsCheckBox.setObjectName(_fromUtf8("mExtentsCheckBox"))
        self.gridLayout = QtGui.QGridLayout(self.mExtentsCheckBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mXMinLabel = QtGui.QLabel(self.mExtentsCheckBox)
        self.mXMinLabel.setEnabled(True)
        self.mXMinLabel.setWordWrap(False)
        self.mXMinLabel.setObjectName(_fromUtf8("mXMinLabel"))
        self.gridLayout.addWidget(self.mXMinLabel, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mXMinLineEdit = QtGui.QLineEdit(self.mExtentsCheckBox)
        self.mXMinLineEdit.setObjectName(_fromUtf8("mXMinLineEdit"))
        self.horizontalLayout.addWidget(self.mXMinLineEdit)
        self.mXMinDDBtn = QgsDataDefinedButton(self.mExtentsCheckBox)
        self.mXMinDDBtn.setObjectName(_fromUtf8("mXMinDDBtn"))
        self.horizontalLayout.addWidget(self.mXMinDDBtn)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.mYMinLabel = QtGui.QLabel(self.mExtentsCheckBox)
        self.mYMinLabel.setWordWrap(False)
        self.mYMinLabel.setObjectName(_fromUtf8("mYMinLabel"))
        self.gridLayout.addWidget(self.mYMinLabel, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.mYMinLineEdit = QtGui.QLineEdit(self.mExtentsCheckBox)
        self.mYMinLineEdit.setObjectName(_fromUtf8("mYMinLineEdit"))
        self.horizontalLayout_3.addWidget(self.mYMinLineEdit)
        self.mYMinDDBtn = QgsDataDefinedButton(self.mExtentsCheckBox)
        self.mYMinDDBtn.setObjectName(_fromUtf8("mYMinDDBtn"))
        self.horizontalLayout_3.addWidget(self.mYMinDDBtn)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.mXMaxLabel = QtGui.QLabel(self.mExtentsCheckBox)
        self.mXMaxLabel.setWordWrap(False)
        self.mXMaxLabel.setObjectName(_fromUtf8("mXMaxLabel"))
        self.gridLayout.addWidget(self.mXMaxLabel, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.mXMaxLineEdit = QtGui.QLineEdit(self.mExtentsCheckBox)
        self.mXMaxLineEdit.setObjectName(_fromUtf8("mXMaxLineEdit"))
        self.horizontalLayout_4.addWidget(self.mXMaxLineEdit)
        self.mXMaxDDBtn = QgsDataDefinedButton(self.mExtentsCheckBox)
        self.mXMaxDDBtn.setObjectName(_fromUtf8("mXMaxDDBtn"))
        self.horizontalLayout_4.addWidget(self.mXMaxDDBtn)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.mYMaxLabel = QtGui.QLabel(self.mExtentsCheckBox)
        self.mYMaxLabel.setWordWrap(False)
        self.mYMaxLabel.setObjectName(_fromUtf8("mYMaxLabel"))
        self.gridLayout.addWidget(self.mYMaxLabel, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.mYMaxLineEdit = QtGui.QLineEdit(self.mExtentsCheckBox)
        self.mYMaxLineEdit.setObjectName(_fromUtf8("mYMaxLineEdit"))
        self.horizontalLayout_5.addWidget(self.mYMaxLineEdit)
        self.mYMaxDDBtn = QgsDataDefinedButton(self.mExtentsCheckBox)
        self.mYMaxDDBtn.setObjectName(_fromUtf8("mYMaxDDBtn"))
        self.horizontalLayout_5.addWidget(self.mYMaxDDBtn)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 1, 1, 1)
        self.mSetToMapCanvasExtentButton = QtGui.QPushButton(self.mExtentsCheckBox)
        self.mSetToMapCanvasExtentButton.setObjectName(_fromUtf8("mSetToMapCanvasExtentButton"))
        self.gridLayout.addWidget(self.mSetToMapCanvasExtentButton, 4, 0, 1, 2)
        self.mViewExtentInCanvasButton = QtGui.QPushButton(self.mExtentsCheckBox)
        self.mViewExtentInCanvasButton.setObjectName(_fromUtf8("mViewExtentInCanvasButton"))
        self.gridLayout.addWidget(self.mViewExtentInCanvasButton, 5, 0, 1, 2)
        self.mainLayout.addWidget(self.mExtentsCheckBox)
        self.mAtlasCheckBox = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.mAtlasCheckBox.setCheckable(True)
        self.mAtlasCheckBox.setChecked(False)
        self.mAtlasCheckBox.setProperty("collapsed", True)
        self.mAtlasCheckBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mAtlasCheckBox.setObjectName(_fromUtf8("mAtlasCheckBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.mAtlasCheckBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mAtlasMarginRadio = QtGui.QRadioButton(self.mAtlasCheckBox)
        self.mAtlasMarginRadio.setEnabled(False)
        self.mAtlasMarginRadio.setObjectName(_fromUtf8("mAtlasMarginRadio"))
        self.gridLayout_2.addWidget(self.mAtlasMarginRadio, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.mAtlasMarginSpinBox = QgsSpinBox(self.mAtlasCheckBox)
        self.mAtlasMarginSpinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mAtlasMarginSpinBox.sizePolicy().hasHeightForWidth())
        self.mAtlasMarginSpinBox.setSizePolicy(sizePolicy)
        self.mAtlasMarginSpinBox.setMaximum(9999)
        self.mAtlasMarginSpinBox.setProperty("value", 10)
        self.mAtlasMarginSpinBox.setObjectName(_fromUtf8("mAtlasMarginSpinBox"))
        self.horizontalLayout_11.addWidget(self.mAtlasMarginSpinBox)
        self.mAtlasMarginDDBtn = QgsDataDefinedButton(self.mAtlasCheckBox)
        self.mAtlasMarginDDBtn.setObjectName(_fromUtf8("mAtlasMarginDDBtn"))
        self.horizontalLayout_11.addWidget(self.mAtlasMarginDDBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 0, 1, 1, 1)
        self.mAtlasPredefinedScaleRadio = QtGui.QRadioButton(self.mAtlasCheckBox)
        self.mAtlasPredefinedScaleRadio.setObjectName(_fromUtf8("mAtlasPredefinedScaleRadio"))
        self.gridLayout_2.addWidget(self.mAtlasPredefinedScaleRadio, 1, 0, 1, 1)
        self.mAtlasFixedScaleRadio = QtGui.QRadioButton(self.mAtlasCheckBox)
        self.mAtlasFixedScaleRadio.setEnabled(False)
        self.mAtlasFixedScaleRadio.setObjectName(_fromUtf8("mAtlasFixedScaleRadio"))
        self.gridLayout_2.addWidget(self.mAtlasFixedScaleRadio, 2, 0, 1, 1)
        self.mainLayout.addWidget(self.mAtlasCheckBox)
        self.mGridGroupBox = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.mGridGroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mGridGroupBox.setProperty("collapsed", True)
        self.mGridGroupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mGridGroupBox.setObjectName(_fromUtf8("mGridGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.mGridGroupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.mAddGridPushButton = QtGui.QPushButton(self.mGridGroupBox)
        self.mAddGridPushButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/symbologyAdd.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mAddGridPushButton.setIcon(icon)
        self.mAddGridPushButton.setObjectName(_fromUtf8("mAddGridPushButton"))
        self.horizontalLayout_8.addWidget(self.mAddGridPushButton)
        self.mRemoveGridPushButton = QtGui.QPushButton(self.mGridGroupBox)
        self.mRemoveGridPushButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/symbologyRemove.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mRemoveGridPushButton.setIcon(icon1)
        self.mRemoveGridPushButton.setObjectName(_fromUtf8("mRemoveGridPushButton"))
        self.horizontalLayout_8.addWidget(self.mRemoveGridPushButton)
        self.mGridUpButton = QtGui.QPushButton(self.mGridGroupBox)
        self.mGridUpButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/symbologyUp.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mGridUpButton.setIcon(icon2)
        self.mGridUpButton.setObjectName(_fromUtf8("mGridUpButton"))
        self.horizontalLayout_8.addWidget(self.mGridUpButton)
        self.mGridDownButton = QtGui.QPushButton(self.mGridGroupBox)
        self.mGridDownButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/symbologyDown.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mGridDownButton.setIcon(icon3)
        self.mGridDownButton.setObjectName(_fromUtf8("mGridDownButton"))
        self.horizontalLayout_8.addWidget(self.mGridDownButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.mGridListWidget = QtGui.QListWidget(self.mGridGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGridListWidget.sizePolicy().hasHeightForWidth())
        self.mGridListWidget.setSizePolicy(sizePolicy)
        self.mGridListWidget.setMaximumSize(QtCore.QSize(16777215, 90))
        self.mGridListWidget.setObjectName(_fromUtf8("mGridListWidget"))
        self.verticalLayout_3.addWidget(self.mGridListWidget)
        self.mGridCheckBox = QgsCollapsibleGroupBoxBasic(self.mGridGroupBox)
        self.mGridCheckBox.setCheckable(True)
        self.mGridCheckBox.setChecked(True)
        self.mGridCheckBox.setProperty("syncGroup", _fromUtf8("composermapgrid"))
        self.mGridCheckBox.setProperty("collapsed", False)
        self.mGridCheckBox.setObjectName(_fromUtf8("mGridCheckBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.mGridCheckBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.mGridTypeLabel_2 = QtGui.QLabel(self.mGridCheckBox)
        self.mGridTypeLabel_2.setAccessibleName(_fromUtf8(""))
        self.mGridTypeLabel_2.setWordWrap(False)
        self.mGridTypeLabel_2.setObjectName(_fromUtf8("mGridTypeLabel_2"))
        self.gridLayout_6.addWidget(self.mGridTypeLabel_2, 0, 0, 1, 1)
        self.mGridTypeComboBox = QtGui.QComboBox(self.mGridCheckBox)
        self.mGridTypeComboBox.setObjectName(_fromUtf8("mGridTypeComboBox"))
        self.gridLayout_6.addWidget(self.mGridTypeComboBox, 0, 1, 1, 1)
        self.mMapGridCRSLabel = QtGui.QLabel(self.mGridCheckBox)
        self.mMapGridCRSLabel.setObjectName(_fromUtf8("mMapGridCRSLabel"))
        self.gridLayout_6.addWidget(self.mMapGridCRSLabel, 1, 0, 1, 1)
        self.mMapGridCRSButton = QtGui.QPushButton(self.mGridCheckBox)
        self.mMapGridCRSButton.setObjectName(_fromUtf8("mMapGridCRSButton"))
        self.gridLayout_6.addWidget(self.mMapGridCRSButton, 1, 1, 1, 1)
        self.mMapGridUnitLabel = QtGui.QLabel(self.mGridCheckBox)
        self.mMapGridUnitLabel.setObjectName(_fromUtf8("mMapGridUnitLabel"))
        self.gridLayout_6.addWidget(self.mMapGridUnitLabel, 2, 0, 1, 1)
        self.mMapGridUnitComboBox = QtGui.QComboBox(self.mGridCheckBox)
        self.mMapGridUnitComboBox.setObjectName(_fromUtf8("mMapGridUnitComboBox"))
        self.mMapGridUnitComboBox.addItem(_fromUtf8(""))
        self.mMapGridUnitComboBox.addItem(_fromUtf8(""))
        self.mMapGridUnitComboBox.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.mMapGridUnitComboBox, 2, 1, 1, 1)
        self.mIntervalXLabel_2 = QtGui.QLabel(self.mGridCheckBox)
        self.mIntervalXLabel_2.setWordWrap(False)
        self.mIntervalXLabel_2.setObjectName(_fromUtf8("mIntervalXLabel_2"))
        self.gridLayout_6.addWidget(self.mIntervalXLabel_2, 3, 0, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.mIntervalXSpinBox = QgsDoubleSpinBox(self.mGridCheckBox)
        self.mIntervalXSpinBox.setDecimals(12)
        self.mIntervalXSpinBox.setMaximum(9999999.0)
        self.mIntervalXSpinBox.setObjectName(_fromUtf8("mIntervalXSpinBox"))
        self.verticalLayout_9.addWidget(self.mIntervalXSpinBox)
        self.mIntervalYSpinBox = QgsDoubleSpinBox(self.mGridCheckBox)
        self.mIntervalYSpinBox.setDecimals(12)
        self.mIntervalYSpinBox.setMaximum(9999999.0)
        self.mIntervalYSpinBox.setObjectName(_fromUtf8("mIntervalYSpinBox"))
        self.verticalLayout_9.addWidget(self.mIntervalYSpinBox)
        self.gridLayout_6.addLayout(self.verticalLayout_9, 3, 1, 1, 1)
        self.mOffsetXLabel_2 = QtGui.QLabel(self.mGridCheckBox)
        self.mOffsetXLabel_2.setWordWrap(False)
        self.mOffsetXLabel_2.setObjectName(_fromUtf8("mOffsetXLabel_2"))
        self.gridLayout_6.addWidget(self.mOffsetXLabel_2, 4, 0, 1, 1)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.mOffsetXSpinBox = QgsDoubleSpinBox(self.mGridCheckBox)
        self.mOffsetXSpinBox.setDecimals(12)
        self.mOffsetXSpinBox.setMaximum(9999999.0)
        self.mOffsetXSpinBox.setObjectName(_fromUtf8("mOffsetXSpinBox"))
        self.verticalLayout_10.addWidget(self.mOffsetXSpinBox)
        self.mOffsetYSpinBox = QgsDoubleSpinBox(self.mGridCheckBox)
        self.mOffsetYSpinBox.setDecimals(12)
        self.mOffsetYSpinBox.setMaximum(9999999.0)
        self.mOffsetYSpinBox.setObjectName(_fromUtf8("mOffsetYSpinBox"))
        self.verticalLayout_10.addWidget(self.mOffsetYSpinBox)
        self.gridLayout_6.addLayout(self.verticalLayout_10, 4, 1, 1, 1)
        self.mCrossWidthLabel = QtGui.QLabel(self.mGridCheckBox)
        self.mCrossWidthLabel.setWordWrap(False)
        self.mCrossWidthLabel.setObjectName(_fromUtf8("mCrossWidthLabel"))
        self.gridLayout_6.addWidget(self.mCrossWidthLabel, 5, 0, 1, 1)
        self.mCrossWidthSpinBox = QgsDoubleSpinBox(self.mGridCheckBox)
        self.mCrossWidthSpinBox.setDecimals(2)
        self.mCrossWidthSpinBox.setProperty("showClearButton", False)
        self.mCrossWidthSpinBox.setObjectName(_fromUtf8("mCrossWidthSpinBox"))
        self.gridLayout_6.addWidget(self.mCrossWidthSpinBox, 5, 1, 1, 1)
        self.mLineStyleLabel = QtGui.QLabel(self.mGridCheckBox)
        self.mLineStyleLabel.setWordWrap(False)
        self.mLineStyleLabel.setObjectName(_fromUtf8("mLineStyleLabel"))
        self.gridLayout_6.addWidget(self.mLineStyleLabel, 6, 0, 1, 1)
        self.mGridLineStyleButton = QtGui.QPushButton(self.mGridCheckBox)
        self.mGridLineStyleButton.setObjectName(_fromUtf8("mGridLineStyleButton"))
        self.gridLayout_6.addWidget(self.mGridLineStyleButton, 6, 1, 1, 1)
        self.mMarkerStyleLabel = QtGui.QLabel(self.mGridCheckBox)
        self.mMarkerStyleLabel.setWordWrap(False)
        self.mMarkerStyleLabel.setObjectName(_fromUtf8("mMarkerStyleLabel"))
        self.gridLayout_6.addWidget(self.mMarkerStyleLabel, 7, 0, 1, 1)
        self.mGridMarkerStyleButton = QtGui.QPushButton(self.mGridCheckBox)
        self.mGridMarkerStyleButton.setObjectName(_fromUtf8("mGridMarkerStyleButton"))
        self.gridLayout_6.addWidget(self.mGridMarkerStyleButton, 7, 1, 1, 1)
        self.mGridBlendLabel = QtGui.QLabel(self.mGridCheckBox)
        self.mGridBlendLabel.setObjectName(_fromUtf8("mGridBlendLabel"))
        self.gridLayout_6.addWidget(self.mGridBlendLabel, 8, 0, 1, 1)
        self.mGridBlendComboBox = QgsBlendModeComboBox(self.mGridCheckBox)
        self.mGridBlendComboBox.setObjectName(_fromUtf8("mGridBlendComboBox"))
        self.gridLayout_6.addWidget(self.mGridBlendComboBox, 8, 1, 1, 1)
        self.mGridFrameGroupBox = QgsCollapsibleGroupBoxBasic(self.mGridCheckBox)
        self.mGridFrameGroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mGridFrameGroupBox.setProperty("syncGroup", _fromUtf8("composermapgrid"))
        self.mGridFrameGroupBox.setObjectName(_fromUtf8("mGridFrameGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.mGridFrameGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.mFrameStyleLabel_2 = QtGui.QLabel(self.mGridFrameGroupBox)
        self.mFrameStyleLabel_2.setWordWrap(False)
        self.mFrameStyleLabel_2.setObjectName(_fromUtf8("mFrameStyleLabel_2"))
        self.gridLayout_3.addWidget(self.mFrameStyleLabel_2, 0, 0, 1, 1)
        self.mFrameWidthLabel = QtGui.QLabel(self.mGridFrameGroupBox)
        self.mFrameWidthLabel.setWordWrap(False)
        self.mFrameWidthLabel.setObjectName(_fromUtf8("mFrameWidthLabel"))
        self.gridLayout_3.addWidget(self.mFrameWidthLabel, 1, 0, 1, 1)
        self.mFramePenLabel = QtGui.QLabel(self.mGridFrameGroupBox)
        self.mFramePenLabel.setObjectName(_fromUtf8("mFramePenLabel"))
        self.gridLayout_3.addWidget(self.mFramePenLabel, 2, 0, 1, 1)
        self.mGridFramePenSizeSpinBox = QgsDoubleSpinBox(self.mGridFrameGroupBox)
        self.mGridFramePenSizeSpinBox.setProperty("showClearButton", False)
        self.mGridFramePenSizeSpinBox.setObjectName(_fromUtf8("mGridFramePenSizeSpinBox"))
        self.gridLayout_3.addWidget(self.mGridFramePenSizeSpinBox, 2, 1, 1, 1)
        self.mGridFramePenColorButton = QgsColorButtonV2(self.mGridFrameGroupBox)
        self.mGridFramePenColorButton.setMinimumSize(QtCore.QSize(100, 0))
        self.mGridFramePenColorButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mGridFramePenColorButton.setText(_fromUtf8(""))
        self.mGridFramePenColorButton.setObjectName(_fromUtf8("mGridFramePenColorButton"))
        self.gridLayout_3.addWidget(self.mGridFramePenColorButton, 2, 2, 1, 1)
        self.mFrameFillLabel = QtGui.QLabel(self.mGridFrameGroupBox)
        self.mFrameFillLabel.setObjectName(_fromUtf8("mFrameFillLabel"))
        self.gridLayout_3.addWidget(self.mFrameFillLabel, 3, 0, 1, 1)
        self.mGridFrameFill1ColorButton = QgsColorButtonV2(self.mGridFrameGroupBox)
        self.mGridFrameFill1ColorButton.setMinimumSize(QtCore.QSize(100, 0))
        self.mGridFrameFill1ColorButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mGridFrameFill1ColorButton.setText(_fromUtf8(""))
        self.mGridFrameFill1ColorButton.setObjectName(_fromUtf8("mGridFrameFill1ColorButton"))
        self.gridLayout_3.addWidget(self.mGridFrameFill1ColorButton, 3, 1, 1, 1)
        self.mGridFrameFill2ColorButton = QgsColorButtonV2(self.mGridFrameGroupBox)
        self.mGridFrameFill2ColorButton.setMinimumSize(QtCore.QSize(100, 0))
        self.mGridFrameFill2ColorButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mGridFrameFill2ColorButton.setText(_fromUtf8(""))
        self.mGridFrameFill2ColorButton.setObjectName(_fromUtf8("mGridFrameFill2ColorButton"))
        self.gridLayout_3.addWidget(self.mGridFrameFill2ColorButton, 3, 2, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.mCheckGridLeftSide = QtGui.QCheckBox(self.mGridFrameGroupBox)
        self.mCheckGridLeftSide.setObjectName(_fromUtf8("mCheckGridLeftSide"))
        self.gridLayout_4.addWidget(self.mCheckGridLeftSide, 0, 0, 1, 1)
        self.mCheckGridRightSide = QtGui.QCheckBox(self.mGridFrameGroupBox)
        self.mCheckGridRightSide.setObjectName(_fromUtf8("mCheckGridRightSide"))
        self.gridLayout_4.addWidget(self.mCheckGridRightSide, 0, 1, 1, 1)
        self.mCheckGridTopSide = QtGui.QCheckBox(self.mGridFrameGroupBox)
        self.mCheckGridTopSide.setObjectName(_fromUtf8("mCheckGridTopSide"))
        self.gridLayout_4.addWidget(self.mCheckGridTopSide, 1, 0, 1, 1)
        self.mCheckGridBottomSide = QtGui.QCheckBox(self.mGridFrameGroupBox)
        self.mCheckGridBottomSide.setObjectName(_fromUtf8("mCheckGridBottomSide"))
        self.gridLayout_4.addWidget(self.mCheckGridBottomSide, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 8, 0, 1, 3)
        self.mFrameStyleComboBox = QtGui.QComboBox(self.mGridFrameGroupBox)
        self.mFrameStyleComboBox.setObjectName(_fromUtf8("mFrameStyleComboBox"))
        self.mFrameStyleComboBox.addItem(_fromUtf8(""))
        self.mFrameStyleComboBox.addItem(_fromUtf8(""))
        self.mFrameStyleComboBox.addItem(_fromUtf8(""))
        self.mFrameStyleComboBox.addItem(_fromUtf8(""))
        self.mFrameStyleComboBox.addItem(_fromUtf8(""))
        self.mFrameStyleComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.mFrameStyleComboBox, 0, 1, 1, 2)
        self.mFrameWidthSpinBox = QgsDoubleSpinBox(self.mGridFrameGroupBox)
        self.mFrameWidthSpinBox.setProperty("showClearButton", False)
        self.mFrameWidthSpinBox.setObjectName(_fromUtf8("mFrameWidthSpinBox"))
        self.gridLayout_3.addWidget(self.mFrameWidthSpinBox, 1, 1, 1, 2)
        self.mRightDivisionsLabel = QtGui.QLabel(self.mGridFrameGroupBox)
        self.mRightDivisionsLabel.setObjectName(_fromUtf8("mRightDivisionsLabel"))
        self.gridLayout_3.addWidget(self.mRightDivisionsLabel, 5, 0, 1, 1)
        self.mLeftDivisionsLabel = QtGui.QLabel(self.mGridFrameGroupBox)
        self.mLeftDivisionsLabel.setObjectName(_fromUtf8("mLeftDivisionsLabel"))
        self.gridLayout_3.addWidget(self.mLeftDivisionsLabel, 4, 0, 1, 1)
        self.mTopDivisionsLabel = QtGui.QLabel(self.mGridFrameGroupBox)
        self.mTopDivisionsLabel.setObjectName(_fromUtf8("mTopDivisionsLabel"))
        self.gridLayout_3.addWidget(self.mTopDivisionsLabel, 6, 0, 1, 1)
        self.mBottomDivisionsLabel = QtGui.QLabel(self.mGridFrameGroupBox)
        self.mBottomDivisionsLabel.setObjectName(_fromUtf8("mBottomDivisionsLabel"))
        self.gridLayout_3.addWidget(self.mBottomDivisionsLabel, 7, 0, 1, 1)
        self.mFrameDivisionsLeftComboBox = QtGui.QComboBox(self.mGridFrameGroupBox)
        self.mFrameDivisionsLeftComboBox.setObjectName(_fromUtf8("mFrameDivisionsLeftComboBox"))
        self.gridLayout_3.addWidget(self.mFrameDivisionsLeftComboBox, 4, 1, 1, 2)
        self.mFrameDivisionsRightComboBox = QtGui.QComboBox(self.mGridFrameGroupBox)
        self.mFrameDivisionsRightComboBox.setObjectName(_fromUtf8("mFrameDivisionsRightComboBox"))
        self.gridLayout_3.addWidget(self.mFrameDivisionsRightComboBox, 5, 1, 1, 2)
        self.mFrameDivisionsTopComboBox = QtGui.QComboBox(self.mGridFrameGroupBox)
        self.mFrameDivisionsTopComboBox.setObjectName(_fromUtf8("mFrameDivisionsTopComboBox"))
        self.gridLayout_3.addWidget(self.mFrameDivisionsTopComboBox, 6, 1, 1, 2)
        self.mFrameDivisionsBottomComboBox = QtGui.QComboBox(self.mGridFrameGroupBox)
        self.mFrameDivisionsBottomComboBox.setObjectName(_fromUtf8("mFrameDivisionsBottomComboBox"))
        self.gridLayout_3.addWidget(self.mFrameDivisionsBottomComboBox, 7, 1, 1, 2)
        self.gridLayout_6.addWidget(self.mGridFrameGroupBox, 9, 0, 1, 2)
        self.mDrawAnnotationGroupBox = QgsCollapsibleGroupBoxBasic(self.mGridCheckBox)
        self.mDrawAnnotationGroupBox.setEnabled(True)
        self.mDrawAnnotationGroupBox.setCheckable(True)
        self.mDrawAnnotationGroupBox.setChecked(False)
        self.mDrawAnnotationGroupBox.setProperty("syncGroup", _fromUtf8("composermapgrid"))
        self.mDrawAnnotationGroupBox.setProperty("collapsed", False)
        self.mDrawAnnotationGroupBox.setObjectName(_fromUtf8("mDrawAnnotationGroupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.mDrawAnnotationGroupBox)
        self.gridLayout_7.setContentsMargins(6, -1, 6, -1)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.mAnnotationPositionLabelRight = QtGui.QLabel(self.mDrawAnnotationGroupBox)
        self.mAnnotationPositionLabelRight.setWordWrap(True)
        self.mAnnotationPositionLabelRight.setObjectName(_fromUtf8("mAnnotationPositionLabelRight"))
        self.gridLayout_7.addWidget(self.mAnnotationPositionLabelRight, 4, 0, 1, 1)
        self.mAnnotationDisplayRightComboBox = QtGui.QComboBox(self.mDrawAnnotationGroupBox)
        self.mAnnotationDisplayRightComboBox.setObjectName(_fromUtf8("mAnnotationDisplayRightComboBox"))
        self.gridLayout_7.addWidget(self.mAnnotationDisplayRightComboBox, 4, 1, 1, 1)
        self.mAnnotationPositionLabelLeft = QtGui.QLabel(self.mDrawAnnotationGroupBox)
        self.mAnnotationPositionLabelLeft.setWordWrap(True)
        self.mAnnotationPositionLabelLeft.setObjectName(_fromUtf8("mAnnotationPositionLabelLeft"))
        self.gridLayout_7.addWidget(self.mAnnotationPositionLabelLeft, 1, 0, 1, 1)
        self.mAnnotationFormatLabel = QtGui.QLabel(self.mDrawAnnotationGroupBox)
        self.mAnnotationFormatLabel.setObjectName(_fromUtf8("mAnnotationFormatLabel"))
        self.gridLayout_7.addWidget(self.mAnnotationFormatLabel, 0, 0, 1, 1)
        self.mAnnotationPositionLeftComboBox = QtGui.QComboBox(self.mDrawAnnotationGroupBox)
        self.mAnnotationPositionLeftComboBox.setObjectName(_fromUtf8("mAnnotationPositionLeftComboBox"))
        self.gridLayout_7.addWidget(self.mAnnotationPositionLeftComboBox, 2, 1, 1, 1)
        self.mAnnotationDirectionComboBoxLeft = QtGui.QComboBox(self.mDrawAnnotationGroupBox)
        self.mAnnotationDirectionComboBoxLeft.setObjectName(_fromUtf8("mAnnotationDirectionComboBoxLeft"))
        self.gridLayout_7.addWidget(self.mAnnotationDirectionComboBoxLeft, 3, 1, 1, 1)
        self.mAnnotationPositionRightComboBox = QtGui.QComboBox(self.mDrawAnnotationGroupBox)
        self.mAnnotationPositionRightComboBox.setObjectName(_fromUtf8("mAnnotationPositionRightComboBox"))
        self.gridLayout_7.addWidget(self.mAnnotationPositionRightComboBox, 5, 1, 1, 1)
        self.mAnnotationDirectionComboBoxRight = QtGui.QComboBox(self.mDrawAnnotationGroupBox)
        self.mAnnotationDirectionComboBoxRight.setObjectName(_fromUtf8("mAnnotationDirectionComboBoxRight"))
        self.gridLayout_7.addWidget(self.mAnnotationDirectionComboBoxRight, 6, 1, 1, 1)
        self.mAnnotationPositionTopComboBox = QtGui.QComboBox(self.mDrawAnnotationGroupBox)
        self.mAnnotationPositionTopComboBox.setObjectName(_fromUtf8("mAnnotationPositionTopComboBox"))
        self.gridLayout_7.addWidget(self.mAnnotationPositionTopComboBox, 8, 1, 1, 1)
        self.mAnnotationDirectionComboBoxTop = QtGui.QComboBox(self.mDrawAnnotationGroupBox)
        self.mAnnotationDirectionComboBoxTop.setObjectName(_fromUtf8("mAnnotationDirectionComboBoxTop"))
        self.gridLayout_7.addWidget(self.mAnnotationDirectionComboBoxTop, 9, 1, 1, 1)
        self.mAnnotationPositionBottomComboBox = QtGui.QComboBox(self.mDrawAnnotationGroupBox)
        self.mAnnotationPositionBottomComboBox.setObjectName(_fromUtf8("mAnnotationPositionBottomComboBox"))
        self.gridLayout_7.addWidget(self.mAnnotationPositionBottomComboBox, 11, 1, 1, 1)
        self.mAnnotationDirectionComboBoxBottom = QtGui.QComboBox(self.mDrawAnnotationGroupBox)
        self.mAnnotationDirectionComboBoxBottom.setObjectName(_fromUtf8("mAnnotationDirectionComboBoxBottom"))
        self.gridLayout_7.addWidget(self.mAnnotationDirectionComboBoxBottom, 12, 1, 1, 1)
        self.label = QtGui.QLabel(self.mDrawAnnotationGroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 13, 0, 1, 1)
        self.mAnnotationFontButton = QtGui.QPushButton(self.mDrawAnnotationGroupBox)
        self.mAnnotationFontButton.setObjectName(_fromUtf8("mAnnotationFontButton"))
        self.gridLayout_7.addWidget(self.mAnnotationFontButton, 13, 1, 1, 1)
        self.mFontColorLabel = QtGui.QLabel(self.mDrawAnnotationGroupBox)
        self.mFontColorLabel.setObjectName(_fromUtf8("mFontColorLabel"))
        self.gridLayout_7.addWidget(self.mFontColorLabel, 14, 0, 1, 1)
        self.mAnnotationFontColorButton = QgsColorButtonV2(self.mDrawAnnotationGroupBox)
        self.mAnnotationFontColorButton.setMinimumSize(QtCore.QSize(120, 0))
        self.mAnnotationFontColorButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.mAnnotationFontColorButton.setText(_fromUtf8(""))
        self.mAnnotationFontColorButton.setObjectName(_fromUtf8("mAnnotationFontColorButton"))
        self.gridLayout_7.addWidget(self.mAnnotationFontColorButton, 14, 1, 1, 1)
        self.mDistanceToFrameLabel = QtGui.QLabel(self.mDrawAnnotationGroupBox)
        self.mDistanceToFrameLabel.setWordWrap(True)
        self.mDistanceToFrameLabel.setObjectName(_fromUtf8("mDistanceToFrameLabel"))
        self.gridLayout_7.addWidget(self.mDistanceToFrameLabel, 15, 0, 1, 1)
        self.mDistanceToMapFrameSpinBox = QgsDoubleSpinBox(self.mDrawAnnotationGroupBox)
        self.mDistanceToMapFrameSpinBox.setObjectName(_fromUtf8("mDistanceToMapFrameSpinBox"))
        self.gridLayout_7.addWidget(self.mDistanceToMapFrameSpinBox, 15, 1, 1, 1)
        self.mCoordinatePrecisionLabel = QtGui.QLabel(self.mDrawAnnotationGroupBox)
        self.mCoordinatePrecisionLabel.setWordWrap(True)
        self.mCoordinatePrecisionLabel.setObjectName(_fromUtf8("mCoordinatePrecisionLabel"))
        self.gridLayout_7.addWidget(self.mCoordinatePrecisionLabel, 16, 0, 1, 1)
        self.mCoordinatePrecisionSpinBox = QgsSpinBox(self.mDrawAnnotationGroupBox)
        self.mCoordinatePrecisionSpinBox.setProperty("showClearButton", False)
        self.mCoordinatePrecisionSpinBox.setObjectName(_fromUtf8("mCoordinatePrecisionSpinBox"))
        self.gridLayout_7.addWidget(self.mCoordinatePrecisionSpinBox, 16, 1, 1, 1)
        self.mAnnotationDisplayLeftComboBox = QtGui.QComboBox(self.mDrawAnnotationGroupBox)
        self.mAnnotationDisplayLeftComboBox.setObjectName(_fromUtf8("mAnnotationDisplayLeftComboBox"))
        self.gridLayout_7.addWidget(self.mAnnotationDisplayLeftComboBox, 1, 1, 1, 1)
        self.mAnnotationPositionLabelTop = QtGui.QLabel(self.mDrawAnnotationGroupBox)
        self.mAnnotationPositionLabelTop.setWordWrap(True)
        self.mAnnotationPositionLabelTop.setObjectName(_fromUtf8("mAnnotationPositionLabelTop"))
        self.gridLayout_7.addWidget(self.mAnnotationPositionLabelTop, 7, 0, 1, 1)
        self.mAnnotationDisplayTopComboBox = QtGui.QComboBox(self.mDrawAnnotationGroupBox)
        self.mAnnotationDisplayTopComboBox.setObjectName(_fromUtf8("mAnnotationDisplayTopComboBox"))
        self.gridLayout_7.addWidget(self.mAnnotationDisplayTopComboBox, 7, 1, 1, 1)
        self.mAnnotationDisplayBottomComboBox = QtGui.QComboBox(self.mDrawAnnotationGroupBox)
        self.mAnnotationDisplayBottomComboBox.setObjectName(_fromUtf8("mAnnotationDisplayBottomComboBox"))
        self.gridLayout_7.addWidget(self.mAnnotationDisplayBottomComboBox, 10, 1, 1, 1)
        self.mAnnotationPositionLabelBottom = QtGui.QLabel(self.mDrawAnnotationGroupBox)
        self.mAnnotationPositionLabelBottom.setWordWrap(True)
        self.mAnnotationPositionLabelBottom.setObjectName(_fromUtf8("mAnnotationPositionLabelBottom"))
        self.gridLayout_7.addWidget(self.mAnnotationPositionLabelBottom, 10, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.mAnnotationFormatComboBox = QtGui.QComboBox(self.mDrawAnnotationGroupBox)
        self.mAnnotationFormatComboBox.setObjectName(_fromUtf8("mAnnotationFormatComboBox"))
        self.horizontalLayout_13.addWidget(self.mAnnotationFormatComboBox)
        self.mAnnotationFormatButton = QtGui.QToolButton(self.mDrawAnnotationGroupBox)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/images/themes/default/mIconExpression.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mAnnotationFormatButton.setIcon(icon4)
        self.mAnnotationFormatButton.setObjectName(_fromUtf8("mAnnotationFormatButton"))
        self.horizontalLayout_13.addWidget(self.mAnnotationFormatButton)
        self.gridLayout_7.addLayout(self.horizontalLayout_13, 0, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(1, 1)
        self.gridLayout_6.addWidget(self.mDrawAnnotationGroupBox, 10, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.mGridCheckBox)
        self.mainLayout.addWidget(self.mGridGroupBox)
        self.mOverviewsGroupBox = QgsCollapsibleGroupBoxBasic(self.scrollAreaWidgetContents)
        self.mOverviewsGroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mOverviewsGroupBox.setProperty("syncGroup", _fromUtf8("composeritem"))
        self.mOverviewsGroupBox.setProperty("collapsed", True)
        self.mOverviewsGroupBox.setObjectName(_fromUtf8("mOverviewsGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.mOverviewsGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.mAddOverviewPushButton = QtGui.QPushButton(self.mOverviewsGroupBox)
        self.mAddOverviewPushButton.setText(_fromUtf8(""))
        self.mAddOverviewPushButton.setIcon(icon)
        self.mAddOverviewPushButton.setObjectName(_fromUtf8("mAddOverviewPushButton"))
        self.horizontalLayout_9.addWidget(self.mAddOverviewPushButton)
        self.mRemoveOverviewPushButton = QtGui.QPushButton(self.mOverviewsGroupBox)
        self.mRemoveOverviewPushButton.setText(_fromUtf8(""))
        self.mRemoveOverviewPushButton.setIcon(icon1)
        self.mRemoveOverviewPushButton.setObjectName(_fromUtf8("mRemoveOverviewPushButton"))
        self.horizontalLayout_9.addWidget(self.mRemoveOverviewPushButton)
        self.mOverviewUpButton = QtGui.QPushButton(self.mOverviewsGroupBox)
        self.mOverviewUpButton.setText(_fromUtf8(""))
        self.mOverviewUpButton.setIcon(icon2)
        self.mOverviewUpButton.setObjectName(_fromUtf8("mOverviewUpButton"))
        self.horizontalLayout_9.addWidget(self.mOverviewUpButton)
        self.mOverviewDownButton = QtGui.QPushButton(self.mOverviewsGroupBox)
        self.mOverviewDownButton.setText(_fromUtf8(""))
        self.mOverviewDownButton.setIcon(icon3)
        self.mOverviewDownButton.setObjectName(_fromUtf8("mOverviewDownButton"))
        self.horizontalLayout_9.addWidget(self.mOverviewDownButton)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.mOverviewListWidget = QtGui.QListWidget(self.mOverviewsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mOverviewListWidget.sizePolicy().hasHeightForWidth())
        self.mOverviewListWidget.setSizePolicy(sizePolicy)
        self.mOverviewListWidget.setMaximumSize(QtCore.QSize(16777215, 90))
        self.mOverviewListWidget.setObjectName(_fromUtf8("mOverviewListWidget"))
        self.verticalLayout.addWidget(self.mOverviewListWidget)
        self.mOverviewCheckBox = QgsCollapsibleGroupBoxBasic(self.mOverviewsGroupBox)
        self.mOverviewCheckBox.setCheckable(True)
        self.mOverviewCheckBox.setChecked(True)
        self.mOverviewCheckBox.setProperty("syncGroup", _fromUtf8("composermapoverview"))
        self.mOverviewCheckBox.setProperty("collapsed", False)
        self.mOverviewCheckBox.setObjectName(_fromUtf8("mOverviewCheckBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.mOverviewCheckBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.mOverviewFrameMapLabel = QtGui.QLabel(self.mOverviewCheckBox)
        self.mOverviewFrameMapLabel.setObjectName(_fromUtf8("mOverviewFrameMapLabel"))
        self.gridLayout_8.addWidget(self.mOverviewFrameMapLabel, 0, 0, 1, 1)
        self.mOverviewFrameMapComboBox = QtGui.QComboBox(self.mOverviewCheckBox)
        self.mOverviewFrameMapComboBox.setObjectName(_fromUtf8("mOverviewFrameMapComboBox"))
        self.gridLayout_8.addWidget(self.mOverviewFrameMapComboBox, 0, 1, 1, 1)
        self.mOverviewFrameStyleLabel = QtGui.QLabel(self.mOverviewCheckBox)
        self.mOverviewFrameStyleLabel.setObjectName(_fromUtf8("mOverviewFrameStyleLabel"))
        self.gridLayout_8.addWidget(self.mOverviewFrameStyleLabel, 1, 0, 1, 1)
        self.mOverviewFrameStyleButton = QtGui.QPushButton(self.mOverviewCheckBox)
        self.mOverviewFrameStyleButton.setObjectName(_fromUtf8("mOverviewFrameStyleButton"))
        self.gridLayout_8.addWidget(self.mOverviewFrameStyleButton, 1, 1, 1, 1)
        self.mOverviewBlendModeLabel = QtGui.QLabel(self.mOverviewCheckBox)
        self.mOverviewBlendModeLabel.setObjectName(_fromUtf8("mOverviewBlendModeLabel"))
        self.gridLayout_8.addWidget(self.mOverviewBlendModeLabel, 2, 0, 1, 1)
        self.mOverviewBlendModeComboBox = QgsBlendModeComboBox(self.mOverviewCheckBox)
        self.mOverviewBlendModeComboBox.setObjectName(_fromUtf8("mOverviewBlendModeComboBox"))
        self.gridLayout_8.addWidget(self.mOverviewBlendModeComboBox, 2, 1, 1, 1)
        self.mOverviewInvertCheckbox = QtGui.QCheckBox(self.mOverviewCheckBox)
        self.mOverviewInvertCheckbox.setObjectName(_fromUtf8("mOverviewInvertCheckbox"))
        self.gridLayout_8.addWidget(self.mOverviewInvertCheckbox, 3, 0, 1, 2)
        self.mOverviewCenterCheckbox = QtGui.QCheckBox(self.mOverviewCheckBox)
        self.mOverviewCenterCheckbox.setObjectName(_fromUtf8("mOverviewCenterCheckbox"))
        self.gridLayout_8.addWidget(self.mOverviewCenterCheckbox, 4, 0, 1, 2)
        self.gridLayout_8.setColumnStretch(1, 1)
        self.verticalLayout.addWidget(self.mOverviewCheckBox)
        self.mainLayout.addWidget(self.mOverviewsGroupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.label_2.setBuddy(self.mScaleLineEdit)
        self.mXMinLabel.setBuddy(self.mXMinLineEdit)
        self.mYMinLabel.setBuddy(self.mYMinLineEdit)
        self.mXMaxLabel.setBuddy(self.mXMaxLineEdit)
        self.mYMaxLabel.setBuddy(self.mYMaxLineEdit)
        self.mAnnotationPositionLabelRight.setBuddy(self.mAnnotationPositionRightComboBox)
        self.mAnnotationPositionLabelLeft.setBuddy(self.mAnnotationPositionLeftComboBox)
        self.mDistanceToFrameLabel.setBuddy(self.mDistanceToMapFrameSpinBox)
        self.mCoordinatePrecisionLabel.setBuddy(self.mCoordinatePrecisionSpinBox)
        self.mAnnotationPositionLabelTop.setBuddy(self.mAnnotationPositionTopComboBox)
        self.mAnnotationPositionLabelBottom.setBuddy(self.mAnnotationPositionRightComboBox)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self.setTabOrder(self.scrollArea, self.groupBox)
        self.setTabOrder(self.groupBox, self.mPreviewModeComboBox)
        self.setTabOrder(self.mPreviewModeComboBox, self.mUpdatePreviewButton)
        self.setTabOrder(self.mUpdatePreviewButton, self.mScaleLineEdit)
        self.setTabOrder(self.mScaleLineEdit, self.mScaleDDBtn)
        self.setTabOrder(self.mScaleDDBtn, self.mMapRotationSpinBox)
        self.setTabOrder(self.mMapRotationSpinBox, self.mMapRotationDDBtn)
        self.setTabOrder(self.mMapRotationDDBtn, self.mDrawCanvasItemsCheckBox)
        self.setTabOrder(self.mDrawCanvasItemsCheckBox, self.mKeepLayerListCheckBox)
        self.setTabOrder(self.mKeepLayerListCheckBox, self.mLayerListFromPresetButton)
        self.setTabOrder(self.mLayerListFromPresetButton, self.mLayersDDBtn)
        self.setTabOrder(self.mLayersDDBtn, self.mKeepLayerStylesCheckBox)
        self.setTabOrder(self.mKeepLayerStylesCheckBox, self.mStylePresetsDDBtn)
        self.setTabOrder(self.mStylePresetsDDBtn, self.mExtentsCheckBox)
        self.setTabOrder(self.mExtentsCheckBox, self.mXMinLineEdit)
        self.setTabOrder(self.mXMinLineEdit, self.mXMinDDBtn)
        self.setTabOrder(self.mXMinDDBtn, self.mYMinLineEdit)
        self.setTabOrder(self.mYMinLineEdit, self.mYMinDDBtn)
        self.setTabOrder(self.mYMinDDBtn, self.mXMaxLineEdit)
        self.setTabOrder(self.mXMaxLineEdit, self.mXMaxDDBtn)
        self.setTabOrder(self.mXMaxDDBtn, self.mYMaxLineEdit)
        self.setTabOrder(self.mYMaxLineEdit, self.mYMaxDDBtn)
        self.setTabOrder(self.mYMaxDDBtn, self.mSetToMapCanvasExtentButton)
        self.setTabOrder(self.mSetToMapCanvasExtentButton, self.mViewExtentInCanvasButton)
        self.setTabOrder(self.mViewExtentInCanvasButton, self.mAtlasCheckBox)
        self.setTabOrder(self.mAtlasCheckBox, self.mAtlasMarginRadio)
        self.setTabOrder(self.mAtlasMarginRadio, self.mAtlasMarginSpinBox)
        self.setTabOrder(self.mAtlasMarginSpinBox, self.mAtlasMarginDDBtn)
        self.setTabOrder(self.mAtlasMarginDDBtn, self.mAtlasPredefinedScaleRadio)
        self.setTabOrder(self.mAtlasPredefinedScaleRadio, self.mAtlasFixedScaleRadio)
        self.setTabOrder(self.mAtlasFixedScaleRadio, self.mGridGroupBox)
        self.setTabOrder(self.mGridGroupBox, self.mAddGridPushButton)
        self.setTabOrder(self.mAddGridPushButton, self.mRemoveGridPushButton)
        self.setTabOrder(self.mRemoveGridPushButton, self.mGridUpButton)
        self.setTabOrder(self.mGridUpButton, self.mGridDownButton)
        self.setTabOrder(self.mGridDownButton, self.mGridListWidget)
        self.setTabOrder(self.mGridListWidget, self.mGridCheckBox)
        self.setTabOrder(self.mGridCheckBox, self.mGridTypeComboBox)
        self.setTabOrder(self.mGridTypeComboBox, self.mMapGridCRSButton)
        self.setTabOrder(self.mMapGridCRSButton, self.mMapGridUnitComboBox)
        self.setTabOrder(self.mMapGridUnitComboBox, self.mIntervalXSpinBox)
        self.setTabOrder(self.mIntervalXSpinBox, self.mIntervalYSpinBox)
        self.setTabOrder(self.mIntervalYSpinBox, self.mOffsetXSpinBox)
        self.setTabOrder(self.mOffsetXSpinBox, self.mOffsetYSpinBox)
        self.setTabOrder(self.mOffsetYSpinBox, self.mCrossWidthSpinBox)
        self.setTabOrder(self.mCrossWidthSpinBox, self.mGridLineStyleButton)
        self.setTabOrder(self.mGridLineStyleButton, self.mGridMarkerStyleButton)
        self.setTabOrder(self.mGridMarkerStyleButton, self.mGridBlendComboBox)
        self.setTabOrder(self.mGridBlendComboBox, self.mGridFrameGroupBox)
        self.setTabOrder(self.mGridFrameGroupBox, self.mFrameStyleComboBox)
        self.setTabOrder(self.mFrameStyleComboBox, self.mFrameWidthSpinBox)
        self.setTabOrder(self.mFrameWidthSpinBox, self.mGridFramePenSizeSpinBox)
        self.setTabOrder(self.mGridFramePenSizeSpinBox, self.mGridFramePenColorButton)
        self.setTabOrder(self.mGridFramePenColorButton, self.mGridFrameFill1ColorButton)
        self.setTabOrder(self.mGridFrameFill1ColorButton, self.mGridFrameFill2ColorButton)
        self.setTabOrder(self.mGridFrameFill2ColorButton, self.mFrameDivisionsLeftComboBox)
        self.setTabOrder(self.mFrameDivisionsLeftComboBox, self.mFrameDivisionsRightComboBox)
        self.setTabOrder(self.mFrameDivisionsRightComboBox, self.mFrameDivisionsTopComboBox)
        self.setTabOrder(self.mFrameDivisionsTopComboBox, self.mFrameDivisionsBottomComboBox)
        self.setTabOrder(self.mFrameDivisionsBottomComboBox, self.mCheckGridLeftSide)
        self.setTabOrder(self.mCheckGridLeftSide, self.mCheckGridRightSide)
        self.setTabOrder(self.mCheckGridRightSide, self.mCheckGridTopSide)
        self.setTabOrder(self.mCheckGridTopSide, self.mCheckGridBottomSide)
        self.setTabOrder(self.mCheckGridBottomSide, self.mDrawAnnotationGroupBox)
        self.setTabOrder(self.mDrawAnnotationGroupBox, self.mAnnotationFormatComboBox)
        self.setTabOrder(self.mAnnotationFormatComboBox, self.mAnnotationFormatButton)
        self.setTabOrder(self.mAnnotationFormatButton, self.mAnnotationDisplayLeftComboBox)
        self.setTabOrder(self.mAnnotationDisplayLeftComboBox, self.mAnnotationPositionLeftComboBox)
        self.setTabOrder(self.mAnnotationPositionLeftComboBox, self.mAnnotationDirectionComboBoxLeft)
        self.setTabOrder(self.mAnnotationDirectionComboBoxLeft, self.mAnnotationDisplayRightComboBox)
        self.setTabOrder(self.mAnnotationDisplayRightComboBox, self.mAnnotationPositionRightComboBox)
        self.setTabOrder(self.mAnnotationPositionRightComboBox, self.mAnnotationDirectionComboBoxRight)
        self.setTabOrder(self.mAnnotationDirectionComboBoxRight, self.mAnnotationDisplayTopComboBox)
        self.setTabOrder(self.mAnnotationDisplayTopComboBox, self.mAnnotationPositionTopComboBox)
        self.setTabOrder(self.mAnnotationPositionTopComboBox, self.mAnnotationDirectionComboBoxTop)
        self.setTabOrder(self.mAnnotationDirectionComboBoxTop, self.mAnnotationDisplayBottomComboBox)
        self.setTabOrder(self.mAnnotationDisplayBottomComboBox, self.mAnnotationPositionBottomComboBox)
        self.setTabOrder(self.mAnnotationPositionBottomComboBox, self.mAnnotationDirectionComboBoxBottom)
        self.setTabOrder(self.mAnnotationDirectionComboBoxBottom, self.mAnnotationFontButton)
        self.setTabOrder(self.mAnnotationFontButton, self.mAnnotationFontColorButton)
        self.setTabOrder(self.mAnnotationFontColorButton, self.mDistanceToMapFrameSpinBox)
        self.setTabOrder(self.mDistanceToMapFrameSpinBox, self.mCoordinatePrecisionSpinBox)
        self.setTabOrder(self.mCoordinatePrecisionSpinBox, self.mOverviewsGroupBox)
        self.setTabOrder(self.mOverviewsGroupBox, self.mAddOverviewPushButton)
        self.setTabOrder(self.mAddOverviewPushButton, self.mRemoveOverviewPushButton)
        self.setTabOrder(self.mRemoveOverviewPushButton, self.mOverviewUpButton)
        self.setTabOrder(self.mOverviewUpButton, self.mOverviewDownButton)
        self.setTabOrder(self.mOverviewDownButton, self.mOverviewListWidget)
        self.setTabOrder(self.mOverviewListWidget, self.mOverviewCheckBox)
        self.setTabOrder(self.mOverviewCheckBox, self.mOverviewFrameMapComboBox)
        self.setTabOrder(self.mOverviewFrameMapComboBox, self.mOverviewFrameStyleButton)
        self.setTabOrder(self.mOverviewFrameStyleButton, self.mOverviewBlendModeComboBox)
        self.setTabOrder(self.mOverviewBlendModeComboBox, self.mOverviewInvertCheckbox)
        self.setTabOrder(self.mOverviewInvertCheckbox, self.mOverviewCenterCheckbox)

    def retranslateUi(self):
        self.setWindowTitle(_translate("QgsComposerMapWidgetBase", "Map Options", None))
        self.mLabel.setText(_translate("QgsComposerMapWidgetBase", "Map", None))
        self.groupBox.setTitle(_translate("QgsComposerMapWidgetBase", "Main properties", None))
        self.mUpdatePreviewButton.setText(_translate("QgsComposerMapWidgetBase", "Update preview", None))
        self.mDrawCanvasItemsCheckBox.setText(_translate("QgsComposerMapWidgetBase", "Draw map canvas items", None))
        self.label_2.setText(_translate("QgsComposerMapWidgetBase", "Scale", None))
        self.mScaleDDBtn.setText(_translate("QgsComposerMapWidgetBase", "...", None))
        self.mKeepLayerListCheckBox.setText(_translate("QgsComposerMapWidgetBase", "Lock layers for map item", None))
        self.mLayerListFromPresetButton.setText(_translate("QgsComposerMapWidgetBase", "...", None))
        self.mLayersDDBtn.setText(_translate("QgsComposerMapWidgetBase", "...", None))
        self.mMapRotationLabel.setText(_translate("QgsComposerMapWidgetBase", "Map rotation", None))
        self.mMapRotationSpinBox.setSuffix(_translate("QgsComposerMapWidgetBase", " °", None))
        self.mMapRotationDDBtn.setText(_translate("QgsComposerMapWidgetBase", "...", None))
        self.mKeepLayerStylesCheckBox.setText(_translate("QgsComposerMapWidgetBase", "Lock layer styles for map item", None))
        self.mStylePresetsDDBtn.setText(_translate("QgsComposerMapWidgetBase", "...", None))
        self.mExtentsCheckBox.setTitle(_translate("QgsComposerMapWidgetBase", "Extents", None))
        self.mXMinLabel.setText(_translate("QgsComposerMapWidgetBase", "X min", None))
        self.mXMinDDBtn.setText(_translate("QgsComposerMapWidgetBase", "...", None))
        self.mYMinLabel.setText(_translate("QgsComposerMapWidgetBase", "Y min", None))
        self.mYMinDDBtn.setText(_translate("QgsComposerMapWidgetBase", "...", None))
        self.mXMaxLabel.setText(_translate("QgsComposerMapWidgetBase", "X max", None))
        self.mXMaxDDBtn.setText(_translate("QgsComposerMapWidgetBase", "...", None))
        self.mYMaxLabel.setText(_translate("QgsComposerMapWidgetBase", "Y max", None))
        self.mYMaxDDBtn.setText(_translate("QgsComposerMapWidgetBase", "...", None))
        self.mSetToMapCanvasExtentButton.setText(_translate("QgsComposerMapWidgetBase", "Set to map canvas extent", None))
        self.mViewExtentInCanvasButton.setText(_translate("QgsComposerMapWidgetBase", "View extent in map canvas", None))
        self.mAtlasCheckBox.setTitle(_translate("QgsComposerMapWidgetBase", "Controlled by atlas", None))
        self.mAtlasMarginRadio.setText(_translate("QgsComposerMapWidgetBase", "Margin around feature", None))
        self.mAtlasMarginSpinBox.setSuffix(_translate("QgsComposerMapWidgetBase", "%", None))
        self.mAtlasMarginDDBtn.setText(_translate("QgsComposerMapWidgetBase", "...", None))
        self.mAtlasPredefinedScaleRadio.setToolTip(_translate("QgsComposerMapWidgetBase", "Use one of the predefined scales of the project where the atlas feature best fits.", None))
        self.mAtlasPredefinedScaleRadio.setText(_translate("QgsComposerMapWidgetBase", "Predefined scale (best fit)", None))
        self.mAtlasFixedScaleRadio.setText(_translate("QgsComposerMapWidgetBase", "Fixed scale", None))
        self.mGridGroupBox.setTitle(_translate("QgsComposerMapWidgetBase", "Grids", None))
        self.mAddGridPushButton.setToolTip(_translate("QgsComposerMapWidgetBase", "Add a new grid", None))
        self.mRemoveGridPushButton.setToolTip(_translate("QgsComposerMapWidgetBase", "Remove selected grid", None))
        self.mGridUpButton.setToolTip(_translate("QgsComposerMapWidgetBase", "Move selected grid up", None))
        self.mGridDownButton.setToolTip(_translate("QgsComposerMapWidgetBase", "Move selected grid down", None))
        self.mGridCheckBox.setTitle(_translate("QgsComposerMapWidgetBase", "Draw grid", None))
        self.mGridTypeLabel_2.setText(_translate("QgsComposerMapWidgetBase", "Grid type", None))
        self.mMapGridCRSLabel.setText(_translate("QgsComposerMapWidgetBase", "CRS", None))
        self.mMapGridCRSButton.setText(_translate("QgsComposerMapWidgetBase", "change...", None))
        self.mMapGridUnitLabel.setText(_translate("QgsComposerMapWidgetBase", "Interval units", None))
        self.mMapGridUnitComboBox.setItemText(0, _translate("QgsComposerMapWidgetBase", "Map unit", None))
        self.mMapGridUnitComboBox.setItemText(1, _translate("QgsComposerMapWidgetBase", "Millimeter", None))
        self.mMapGridUnitComboBox.setItemText(2, _translate("QgsComposerMapWidgetBase", "Centimeter", None))
        self.mIntervalXLabel_2.setText(_translate("QgsComposerMapWidgetBase", "Interval", None))
        self.mIntervalXSpinBox.setPrefix(_translate("QgsComposerMapWidgetBase", "X ", None))
        self.mIntervalYSpinBox.setPrefix(_translate("QgsComposerMapWidgetBase", "Y ", None))
        self.mOffsetXLabel_2.setText(_translate("QgsComposerMapWidgetBase", "Offset", None))
        self.mOffsetXSpinBox.setPrefix(_translate("QgsComposerMapWidgetBase", "X ", None))
        self.mOffsetYSpinBox.setPrefix(_translate("QgsComposerMapWidgetBase", "Y ", None))
        self.mCrossWidthLabel.setText(_translate("QgsComposerMapWidgetBase", "Cross width", None))
        self.mCrossWidthSpinBox.setSuffix(_translate("QgsComposerMapWidgetBase", " mm", None))
        self.mLineStyleLabel.setText(_translate("QgsComposerMapWidgetBase", "Line style", None))
        self.mGridLineStyleButton.setText(_translate("QgsComposerMapWidgetBase", "change...", None))
        self.mMarkerStyleLabel.setText(_translate("QgsComposerMapWidgetBase", "Marker style", None))
        self.mGridMarkerStyleButton.setText(_translate("QgsComposerMapWidgetBase", "change...", None))
        self.mGridBlendLabel.setText(_translate("QgsComposerMapWidgetBase", "Blend mode", None))
        self.mGridFrameGroupBox.setTitle(_translate("QgsComposerMapWidgetBase", "Grid frame", None))
        self.mFrameStyleLabel_2.setText(_translate("QgsComposerMapWidgetBase", "Frame style", None))
        self.mFrameWidthLabel.setText(_translate("QgsComposerMapWidgetBase", "Frame size", None))
        self.mFramePenLabel.setText(_translate("QgsComposerMapWidgetBase", "Frame line thickness", None))
        self.mGridFramePenSizeSpinBox.setSuffix(_translate("QgsComposerMapWidgetBase", " mm", None))
        self.mFrameFillLabel.setText(_translate("QgsComposerMapWidgetBase", "Frame fill colors", None))
        self.mCheckGridLeftSide.setText(_translate("QgsComposerMapWidgetBase", "Left side", None))
        self.mCheckGridRightSide.setText(_translate("QgsComposerMapWidgetBase", "Right side", None))
        self.mCheckGridTopSide.setText(_translate("QgsComposerMapWidgetBase", "Top side", None))
        self.mCheckGridBottomSide.setText(_translate("QgsComposerMapWidgetBase", "Bottom side", None))
        self.mFrameStyleComboBox.setItemText(0, _translate("QgsComposerMapWidgetBase", "No frame", None))
        self.mFrameStyleComboBox.setItemText(1, _translate("QgsComposerMapWidgetBase", "Zebra", None))
        self.mFrameStyleComboBox.setItemText(2, _translate("QgsComposerMapWidgetBase", "Interior ticks", None))
        self.mFrameStyleComboBox.setItemText(3, _translate("QgsComposerMapWidgetBase", "Exterior ticks", None))
        self.mFrameStyleComboBox.setItemText(4, _translate("QgsComposerMapWidgetBase", "Interior and exterior ticks", None))
        self.mFrameStyleComboBox.setItemText(5, _translate("QgsComposerMapWidgetBase", "Line border", None))
        self.mFrameWidthSpinBox.setSuffix(_translate("QgsComposerMapWidgetBase", " mm", None))
        self.mRightDivisionsLabel.setText(_translate("QgsComposerMapWidgetBase", "Right divisions", None))
        self.mLeftDivisionsLabel.setText(_translate("QgsComposerMapWidgetBase", "Left divisions", None))
        self.mTopDivisionsLabel.setText(_translate("QgsComposerMapWidgetBase", "Top divisions", None))
        self.mBottomDivisionsLabel.setText(_translate("QgsComposerMapWidgetBase", "Bottom divisions", None))
        self.mDrawAnnotationGroupBox.setTitle(_translate("QgsComposerMapWidgetBase", "Draw coordinates", None))
        self.mAnnotationPositionLabelRight.setText(_translate("QgsComposerMapWidgetBase", "Right", None))
        self.mAnnotationPositionLabelLeft.setText(_translate("QgsComposerMapWidgetBase", "Left", None))
        self.mAnnotationFormatLabel.setText(_translate("QgsComposerMapWidgetBase", "Format", None))
        self.label.setText(_translate("QgsComposerMapWidgetBase", "Font", None))
        self.mAnnotationFontButton.setText(_translate("QgsComposerMapWidgetBase", "Font...", None))
        self.mFontColorLabel.setText(_translate("QgsComposerMapWidgetBase", "Font color", None))
        self.mDistanceToFrameLabel.setText(_translate("QgsComposerMapWidgetBase", "Distance to map frame", None))
        self.mDistanceToMapFrameSpinBox.setSuffix(_translate("QgsComposerMapWidgetBase", " mm", None))
        self.mCoordinatePrecisionLabel.setText(_translate("QgsComposerMapWidgetBase", "Coordinate precision", None))
        self.mAnnotationPositionLabelTop.setText(_translate("QgsComposerMapWidgetBase", "Top", None))
        self.mAnnotationPositionLabelBottom.setText(_translate("QgsComposerMapWidgetBase", "Bottom", None))
        self.mAnnotationFormatButton.setText(_translate("QgsComposerMapWidgetBase", "...", None))
        self.mOverviewsGroupBox.setTitle(_translate("QgsComposerMapWidgetBase", "Overviews", None))
        self.mAddOverviewPushButton.setToolTip(_translate("QgsComposerMapWidgetBase", "Add a new overview", None))
        self.mRemoveOverviewPushButton.setToolTip(_translate("QgsComposerMapWidgetBase", "Remove selected overview", None))
        self.mOverviewUpButton.setToolTip(_translate("QgsComposerMapWidgetBase", "Move selected overview up", None))
        self.mOverviewDownButton.setToolTip(_translate("QgsComposerMapWidgetBase", "Move selected overview down", None))
        self.mOverviewCheckBox.setTitle(_translate("QgsComposerMapWidgetBase", "Draw overview", None))
        self.mOverviewFrameMapLabel.setText(_translate("QgsComposerMapWidgetBase", "Map frame", None))
        self.mOverviewFrameStyleLabel.setText(_translate("QgsComposerMapWidgetBase", "Frame style", None))
        self.mOverviewFrameStyleButton.setText(_translate("QgsComposerMapWidgetBase", "Change...", None))
        self.mOverviewBlendModeLabel.setText(_translate("QgsComposerMapWidgetBase", "Blending mode", None))
        self.mOverviewInvertCheckbox.setText(_translate("QgsComposerMapWidgetBase", "Invert overview", None))
        self.mOverviewCenterCheckbox.setText(_translate("QgsComposerMapWidgetBase", "Center on overview", None))


