# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CRM.ui'
#
# Created: Mon May 26 09:06:26 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from FlightPlanner.Panels.PositionPanel import PositionPanel
from FlightPlanner.Panels.ComboBoxPanel import ComboBoxPanel

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CrmDlg(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(549, 1019)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.verticalLayout_AAC = QtGui.QVBoxLayout(Form)
        self.verticalLayout_AAC.setObjectName(_fromUtf8("verticalLayout_AAC"))

        self.tabCtrlGeneral = QtGui.QTabWidget(Form)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.tabCtrlGeneral.setFont(font)
        self.tabCtrlGeneral.setAutoFillBackground(False)
        self.tabCtrlGeneral.setStyleSheet(_fromUtf8(""))
        self.tabCtrlGeneral.setObjectName(_fromUtf8("tabCtrlGeneral"))
        self.verticalLayout_AAC.addWidget(self.tabCtrlGeneral)

        self.tabInputData = QtGui.QWidget(self.tabCtrlGeneral)
        self.tabInputData.setObjectName(_fromUtf8("tabInputData"))

        self.vLayoutTabInputData = QtGui.QVBoxLayout(self.tabInputData)
        self.vLayoutTabInputData.setMargin(3)
        self.vLayoutTabInputData.setObjectName(_fromUtf8("vLayoutTabInputData"))
        self.tabCtrlGeneral.addTab(self.tabInputData, "Input Data")

        self.gbSettings = QtGui.QGroupBox(self.tabInputData)
        self.gbSettings.setObjectName(_fromUtf8("gbSettings"))
        self.verticalLayout_gbSetting = QtGui.QVBoxLayout(self.gbSettings)
        self.verticalLayout_gbSetting.setObjectName(_fromUtf8("verticalLayout_gbSetting"))
        self.frame_ThrFaf_2 = QtGui.QFrame(self.gbSettings)
        self.frame_ThrFaf_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_ThrFaf_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_ThrFaf_2.setObjectName(_fromUtf8("frame_ThrFaf_2"))
        self.horizontalLayout_67 = QtGui.QHBoxLayout(self.frame_ThrFaf_2)
        self.horizontalLayout_67.setSpacing(0)
        self.horizontalLayout_67.setMargin(0)
        self.horizontalLayout_67.setObjectName(_fromUtf8("horizontalLayout_67"))
        self.label_75 = QtGui.QLabel(self.frame_ThrFaf_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_75.sizePolicy().hasHeightForWidth())
        self.label_75.setSizePolicy(sizePolicy)
        self.label_75.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.horizontalLayout_67.addWidget(self.label_75)
        self.frame_APV_11 = QtGui.QFrame(self.frame_ThrFaf_2)
        self.frame_APV_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_11.setObjectName(_fromUtf8("frame_APV_11"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.frame_APV_11)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.txtFile = QtGui.QLineEdit(self.frame_APV_11)
        self.txtFile.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtFile.setFont(font)
        self.txtFile.setText(_fromUtf8(""))
        self.txtFile.setObjectName(_fromUtf8("txtFile"))
        self.horizontalLayout_19.addWidget(self.txtFile)
        self.btnBrowser = QtGui.QToolButton(self.frame_APV_11)
        self.btnBrowser.setObjectName(_fromUtf8("btnBrowser"))
        self.horizontalLayout_19.addWidget(self.btnBrowser)
        self.horizontalLayout_67.addWidget(self.frame_APV_11)
        self.verticalLayout_gbSetting.addWidget(self.frame_ThrFaf_2)
        self.chbAutoRun = QtGui.QCheckBox(self.gbSettings)
        self.chbAutoRun.setObjectName(_fromUtf8("chbAutoRun"))
        self.verticalLayout_gbSetting.addWidget(self.chbAutoRun)
        self.vLayoutTabInputData.addWidget(self.gbSettings)

        self.gbCoordSystem = QtGui.QGroupBox(self.tabInputData)
        self.gbCoordSystem.setObjectName(_fromUtf8("gbCoordSystem"))
        self.verticalLayout_gbCoordSystem = QtGui.QVBoxLayout(self.gbCoordSystem)
        self.verticalLayout_gbCoordSystem.setObjectName(_fromUtf8("verticalLayout_gbCoordSystem"))
        self.vLayoutTabInputData.addWidget(self.gbCoordSystem)

        self.cmbAerodrome = ComboBoxPanel(self.gbCoordSystem, True)
        self.cmbAerodrome.Caption = "Aerodrome"
        self.cmbAerodrome.LabelWidth = 120
        self.verticalLayout_gbCoordSystem.addWidget(self.cmbAerodrome)

        self.cmbRwyDir = ComboBoxPanel(self.gbCoordSystem, True)
        self.cmbRwyDir.Caption = "Runway Direction"
        self.cmbRwyDir.LabelWidth = 120
        self.cmbRwyDir.Width = 120
        self.verticalLayout_gbCoordSystem.addWidget(self.cmbRwyDir)

        self.cmbLocalizer = ComboBoxPanel(self.gbCoordSystem)
        self.cmbLocalizer.Caption = "Localizer"
        self.cmbLocalizer.LabelWidth = 120
        self.cmbLocalizer.Width = 120
        self.verticalLayout_gbCoordSystem.addWidget(self.cmbLocalizer)

        self.pnlThr = PositionPanel(self.gbCoordSystem)
        self.pnlThr.groupBox.setTitle("Threshold Position")
        self.pnlThr.btnCalculater.hide()
        self.pnlThr.setObjectName("positionThr")
        self.verticalLayout_gbCoordSystem.addWidget(self.pnlThr)

        self.pnlLoc = PositionPanel(self.gbCoordSystem)
        self.pnlLoc.groupBox.setTitle("Localizer Position")
        self.pnlLoc.btnCalculater.hide()
        self.pnlLoc.hideframe_Altitude()
        self.pnlLoc.setObjectName("positionLoc")
        self.verticalLayout_gbCoordSystem.addWidget( self.pnlLoc)

        verticalSpacer = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding);
        self.vLayoutTabInputData.addItem(verticalSpacer);

        self.tabCrm = QtGui.QWidget(self.tabCtrlGeneral)
        self.tabCrm.setObjectName(_fromUtf8("tabOasIls"))
        self.vLayoutTabIlsCrm = QtGui.QVBoxLayout(self.tabCrm)
        self.vLayoutTabIlsCrm.setMargin(3)
        self.vLayoutTabIlsCrm.setObjectName(_fromUtf8("vLayoutTabIlsCrm"))
        self.tabCtrlGeneral.addTab(self.tabCrm, "CRM")



        self.gbAdminData = QtGui.QGroupBox(self.tabCrm)
        self.gbAdminData.setObjectName(_fromUtf8("gbAdminData"))
        self.verticalLayout_gbAdminData = QtGui.QVBoxLayout(self.gbAdminData)
        self.verticalLayout_gbAdminData.setObjectName(_fromUtf8("verticalLayout_gbAdminData"))
        self.frame_IasMA_2 = QtGui.QFrame(self.gbAdminData)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_IasMA_2.sizePolicy().hasHeightForWidth())
        self.frame_IasMA_2.setSizePolicy(sizePolicy)
        self.frame_IasMA_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_IasMA_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_IasMA_2.setObjectName(_fromUtf8("frame_IasMA_2"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.frame_IasMA_2)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_4 = QtGui.QLabel(self.frame_IasMA_2)
        self.label_4.setMinimumSize(QtCore.QSize(140, 0))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_12.addWidget(self.label_4)
        self.txtC02 = QtGui.QLineEdit(self.frame_IasMA_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtC02.sizePolicy().hasHeightForWidth())
        self.txtC02.setSizePolicy(sizePolicy)
        self.txtC02.setMinimumSize(QtCore.QSize(105, 0))
        self.txtC02.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtC02.setFont(font)
        self.txtC02.setObjectName(_fromUtf8("txtC02"))
        self.horizontalLayout_12.addWidget(self.txtC02)
        self.verticalLayout_gbAdminData.addWidget(self.frame_IasMA_2)
        self.frame_IasMA_4 = QtGui.QFrame(self.gbAdminData)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_IasMA_4.sizePolicy().hasHeightForWidth())
        self.frame_IasMA_4.setSizePolicy(sizePolicy)
        self.frame_IasMA_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_IasMA_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_IasMA_4.setObjectName(_fromUtf8("frame_IasMA_4"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.frame_IasMA_4)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_6 = QtGui.QLabel(self.frame_IasMA_4)
        self.label_6.setMinimumSize(QtCore.QSize(140, 0))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_13.addWidget(self.label_6)
        self.txtC03 = QtGui.QLineEdit(self.frame_IasMA_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtC03.sizePolicy().hasHeightForWidth())
        self.txtC03.setSizePolicy(sizePolicy)
        self.txtC03.setMinimumSize(QtCore.QSize(105, 0))
        self.txtC03.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtC03.setFont(font)
        self.txtC03.setObjectName(_fromUtf8("txtC03"))
        self.horizontalLayout_13.addWidget(self.txtC03)
        self.verticalLayout_gbAdminData.addWidget(self.frame_IasMA_4)
        self.vLayoutTabIlsCrm.addWidget(self.gbAdminData)
        self.gbGroundData = QtGui.QGroupBox(self.tabCrm)
        self.gbGroundData.setObjectName(_fromUtf8("gbGroundData"))
        self.vLayout_gbGroundData = QtGui.QVBoxLayout(self.gbGroundData)
        self.vLayout_gbGroundData.setObjectName(_fromUtf8("vLayout_gbGroundData"))
        self.frame_IasIA1 = QtGui.QFrame(self.gbGroundData)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_IasIA1.sizePolicy().hasHeightForWidth())
        self.frame_IasIA1.setSizePolicy(sizePolicy)
        self.frame_IasIA1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_IasIA1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_IasIA1.setObjectName(_fromUtf8("frame_IasIA1"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.frame_IasIA1)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_7 = QtGui.QLabel(self.frame_IasIA1)
        self.label_7.setMinimumSize(QtCore.QSize(300, 0))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_16.addWidget(self.label_7)
        self.txtC07 = QtGui.QLineEdit(self.frame_IasIA1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtC07.sizePolicy().hasHeightForWidth())
        self.txtC07.setSizePolicy(sizePolicy)
        self.txtC07.setMinimumSize(QtCore.QSize(105, 0))
        self.txtC07.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtC07.setFont(font)
        self.txtC07.setObjectName(_fromUtf8("txtC07"))
        self.horizontalLayout_16.addWidget(self.txtC07)
        self.vLayout_gbGroundData.addWidget(self.frame_IasIA1)
        self.frame_AltitudeIA1 = QtGui.QFrame(self.gbGroundData)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_AltitudeIA1.sizePolicy().hasHeightForWidth())
        self.frame_AltitudeIA1.setSizePolicy(sizePolicy)
        self.frame_AltitudeIA1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_AltitudeIA1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_AltitudeIA1.setObjectName(_fromUtf8("frame_AltitudeIA1"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.frame_AltitudeIA1)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setMargin(0)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_17 = QtGui.QLabel(self.frame_AltitudeIA1)
        self.label_17.setMinimumSize(QtCore.QSize(300, 0))
        self.label_17.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_27.addWidget(self.label_17)
        self.txtC08 = QtGui.QLineEdit(self.frame_AltitudeIA1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtC08.sizePolicy().hasHeightForWidth())
        self.txtC08.setSizePolicy(sizePolicy)
        self.txtC08.setMinimumSize(QtCore.QSize(105, 0))
        self.txtC08.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtC08.setFont(font)
        self.txtC08.setObjectName(_fromUtf8("txtC08"))
        self.horizontalLayout_27.addWidget(self.txtC08)
        self.vLayout_gbGroundData.addWidget(self.frame_AltitudeIA1)
        self.frame_IasMA = QtGui.QFrame(self.gbGroundData)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_IasMA.sizePolicy().hasHeightForWidth())
        self.frame_IasMA.setSizePolicy(sizePolicy)
        self.frame_IasMA.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_IasMA.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_IasMA.setObjectName(_fromUtf8("frame_IasMA"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.frame_IasMA)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_3 = QtGui.QLabel(self.frame_IasMA)
        self.label_3.setMinimumSize(QtCore.QSize(300, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_11.addWidget(self.label_3)
        self.txtC10 = QtGui.QLineEdit(self.frame_IasMA)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtC10.sizePolicy().hasHeightForWidth())
        self.txtC10.setSizePolicy(sizePolicy)
        self.txtC10.setMinimumSize(QtCore.QSize(105, 0))
        self.txtC10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtC10.setFont(font)
        self.txtC10.setObjectName(_fromUtf8("txtC10"))
        self.horizontalLayout_11.addWidget(self.txtC10)
        self.vLayout_gbGroundData.addWidget(self.frame_IasMA)
        self.frame_IasMA_5 = QtGui.QFrame(self.gbGroundData)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_IasMA_5.sizePolicy().hasHeightForWidth())
        self.frame_IasMA_5.setSizePolicy(sizePolicy)
        self.frame_IasMA_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_IasMA_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_IasMA_5.setObjectName(_fromUtf8("frame_IasMA_5"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.frame_IasMA_5)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_9 = QtGui.QLabel(self.frame_IasMA_5)
        self.label_9.setMinimumSize(QtCore.QSize(300, 0))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_15.addWidget(self.label_9)
        self.txtC12 = QtGui.QLineEdit(self.frame_IasMA_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtC12.sizePolicy().hasHeightForWidth())
        self.txtC12.setSizePolicy(sizePolicy)
        self.txtC12.setMinimumSize(QtCore.QSize(105, 0))
        self.txtC12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtC12.setFont(font)
        self.txtC12.setObjectName(_fromUtf8("txtC12"))
        self.horizontalLayout_15.addWidget(self.txtC12)
        
        self.btnCapture12 = QtGui.QToolButton(self.frame_IasMA_5)
        self.btnCapture12.setMaximumSize(QtCore.QSize(23, 16777215))
        self.btnCapture12.setText(_fromUtf8(""))
        self.btnCapture12.setObjectName(_fromUtf8("btnCapture12"))
        self.btnCapture12.setIcon(icon)
        self.horizontalLayout_15.addWidget(self.btnCapture12)
        
        self.vLayout_gbGroundData.addWidget(self.frame_IasMA_5)
        self.frame_RNVA_2 = QtGui.QFrame(self.gbGroundData)
        self.frame_RNVA_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_RNVA_2.sizePolicy().hasHeightForWidth())
        self.frame_RNVA_2.setSizePolicy(sizePolicy)
        self.frame_RNVA_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_RNVA_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_RNVA_2.setObjectName(_fromUtf8("frame_RNVA_2"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.frame_RNVA_2)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_8 = QtGui.QLabel(self.frame_RNVA_2)
        self.label_8.setMinimumSize(QtCore.QSize(300, 0))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_17.addWidget(self.label_8)
        self.cmbC13 = QtGui.QComboBox(self.frame_RNVA_2)
        self.cmbC13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.cmbC13.setFont(font)
        self.cmbC13.setFrame(True)
        self.cmbC13.setObjectName(_fromUtf8("cmbC13"))
        self.horizontalLayout_17.addWidget(self.cmbC13)
        self.vLayout_gbGroundData.addWidget(self.frame_RNVA_2)
        self.frame_C13a = QtGui.QFrame(self.gbGroundData)
        self.frame_C13a.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_C13a.sizePolicy().hasHeightForWidth())
        self.frame_C13a.setSizePolicy(sizePolicy)
        self.frame_C13a.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_C13a.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_C13a.setObjectName(_fromUtf8("frame_C13a"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.frame_C13a)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setMargin(0)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_15 = QtGui.QLabel(self.frame_C13a)
        self.label_15.setMinimumSize(QtCore.QSize(300, 0))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_24.addWidget(self.label_15)
        self.cmbC13a = QtGui.QComboBox(self.frame_C13a)
        self.cmbC13a.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.cmbC13a.setFont(font)
        self.cmbC13a.setFrame(True)
        self.cmbC13a.setObjectName(_fromUtf8("cmbC13a"))
        self.horizontalLayout_24.addWidget(self.cmbC13a)
        self.vLayout_gbGroundData.addWidget(self.frame_C13a)
        self.frame_C13b = QtGui.QFrame(self.gbGroundData)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_C13b.sizePolicy().hasHeightForWidth())
        self.frame_C13b.setSizePolicy(sizePolicy)
        self.frame_C13b.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_C13b.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_C13b.setObjectName(_fromUtf8("frame_C13b"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.frame_C13b)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setMargin(0)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_16 = QtGui.QLabel(self.frame_C13b)
        self.label_16.setMinimumSize(QtCore.QSize(300, 0))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_25.addWidget(self.label_16)
        self.txtC13b = QtGui.QLineEdit(self.frame_C13b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtC13b.sizePolicy().hasHeightForWidth())
        self.txtC13b.setSizePolicy(sizePolicy)
        self.txtC13b.setMinimumSize(QtCore.QSize(105, 0))
        self.txtC13b.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtC13b.setFont(font)
        self.txtC13b.setObjectName(_fromUtf8("txtC13b"))
        self.horizontalLayout_25.addWidget(self.txtC13b)
        
        self.btnCaptureC13b = QtGui.QToolButton(self.frame_C13b)
        self.btnCaptureC13b.setMaximumSize(QtCore.QSize(23, 16777215))
        self.btnCaptureC13b.setText(_fromUtf8(""))
        self.btnCaptureC13b.setObjectName(_fromUtf8("btnCaptureC13b"))
        self.btnCaptureC13b.setIcon(icon)
        self.horizontalLayout_25.addWidget(self.btnCaptureC13b)
        
        self.vLayout_gbGroundData.addWidget(self.frame_C13b)
        self.vLayoutTabIlsCrm.addWidget(self.gbGroundData)
        self.gbAeroData = QtGui.QGroupBox(self.tabCrm)
        self.gbAeroData.setObjectName(_fromUtf8("gbAeroData"))
        self.verticalLayout_gbAeroData = QtGui.QVBoxLayout(self.gbAeroData)
        self.verticalLayout_gbAeroData.setObjectName(_fromUtf8("verticalLayout_gbAeroData"))
        self.frame_RNVA_3 = QtGui.QFrame(self.gbAeroData)
        self.frame_RNVA_3.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_RNVA_3.sizePolicy().hasHeightForWidth())
        self.frame_RNVA_3.setSizePolicy(sizePolicy)
        self.frame_RNVA_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_RNVA_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_RNVA_3.setObjectName(_fromUtf8("frame_RNVA_3"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.frame_RNVA_3)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_10 = QtGui.QLabel(self.frame_RNVA_3)
        self.label_10.setMinimumSize(QtCore.QSize(300, 0))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_18.addWidget(self.label_10)
        self.cmbC14 = QtGui.QComboBox(self.frame_RNVA_3)
        self.cmbC14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.cmbC14.setFont(font)
        self.cmbC14.setFrame(True)
        self.cmbC14.setObjectName(_fromUtf8("cmbC14"))
        self.horizontalLayout_18.addWidget(self.cmbC14)
        self.verticalLayout_gbAeroData.addWidget(self.frame_RNVA_3)
        self.frame_C14a = QtGui.QFrame(self.gbAeroData)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_C14a.sizePolicy().hasHeightForWidth())
        self.frame_C14a.setSizePolicy(sizePolicy)
        self.frame_C14a.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_C14a.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_C14a.setObjectName(_fromUtf8("frame_C14a"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.frame_C14a)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setMargin(0)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_18 = QtGui.QLabel(self.frame_C14a)
        self.label_18.setMinimumSize(QtCore.QSize(300, 0))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_26.addWidget(self.label_18)
        self.txtC14a = QtGui.QLineEdit(self.frame_C14a)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtC14a.sizePolicy().hasHeightForWidth())
        self.txtC14a.setSizePolicy(sizePolicy)
        self.txtC14a.setMinimumSize(QtCore.QSize(105, 0))
        self.txtC14a.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtC14a.setFont(font)
        self.txtC14a.setObjectName(_fromUtf8("txtC14a"))
        self.horizontalLayout_26.addWidget(self.txtC14a)
        self.verticalLayout_gbAeroData.addWidget(self.frame_C14a)
        self.frame_C14b = QtGui.QFrame(self.gbAeroData)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_C14b.sizePolicy().hasHeightForWidth())
        self.frame_C14b.setSizePolicy(sizePolicy)
        self.frame_C14b.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_C14b.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_C14b.setObjectName(_fromUtf8("frame_C14b"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.frame_C14b)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setMargin(0)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_19 = QtGui.QLabel(self.frame_C14b)
        self.label_19.setMinimumSize(QtCore.QSize(300, 0))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_28.addWidget(self.label_19)
        self.txtC14b = QtGui.QLineEdit(self.frame_C14b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtC14b.sizePolicy().hasHeightForWidth())
        self.txtC14b.setSizePolicy(sizePolicy)
        self.txtC14b.setMinimumSize(QtCore.QSize(105, 0))
        self.txtC14b.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtC14b.setFont(font)
        self.txtC14b.setObjectName(_fromUtf8("txtC14b"))
        self.horizontalLayout_28.addWidget(self.txtC14b)
        self.verticalLayout_gbAeroData.addWidget(self.frame_C14b)
        self.frame_RNVA_4 = QtGui.QFrame(self.gbAeroData)
        self.frame_RNVA_4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_RNVA_4.sizePolicy().hasHeightForWidth())
        self.frame_RNVA_4.setSizePolicy(sizePolicy)
        self.frame_RNVA_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_RNVA_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_RNVA_4.setObjectName(_fromUtf8("frame_RNVA_4"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.frame_RNVA_4)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setMargin(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_11 = QtGui.QLabel(self.frame_RNVA_4)
        self.label_11.setMinimumSize(QtCore.QSize(300, 0))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_20.addWidget(self.label_11)
        self.cmbC15 = QtGui.QComboBox(self.frame_RNVA_4)
        self.cmbC15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.cmbC15.setFont(font)
        self.cmbC15.setFrame(True)
        self.cmbC15.setObjectName(_fromUtf8("cmbC15"))
        self.horizontalLayout_20.addWidget(self.cmbC15)
        self.verticalLayout_gbAeroData.addWidget(self.frame_RNVA_4)
        self.frame_C15a = QtGui.QFrame(self.gbAeroData)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_C15a.sizePolicy().hasHeightForWidth())
        self.frame_C15a.setSizePolicy(sizePolicy)
        self.frame_C15a.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_C15a.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_C15a.setObjectName(_fromUtf8("frame_C15a"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.frame_C15a)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setMargin(0)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_20 = QtGui.QLabel(self.frame_C15a)
        self.label_20.setMinimumSize(QtCore.QSize(300, 0))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_29.addWidget(self.label_20)
        self.txtC15a = QtGui.QLineEdit(self.frame_C15a)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtC15a.sizePolicy().hasHeightForWidth())
        self.txtC15a.setSizePolicy(sizePolicy)
        self.txtC15a.setMinimumSize(QtCore.QSize(105, 0))
        self.txtC15a.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtC15a.setFont(font)
        self.txtC15a.setObjectName(_fromUtf8("txtC15a"))
        self.horizontalLayout_29.addWidget(self.txtC15a)
        self.verticalLayout_gbAeroData.addWidget(self.frame_C15a)
        self.frame_RNVA_5 = QtGui.QFrame(self.gbAeroData)
        self.frame_RNVA_5.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_RNVA_5.sizePolicy().hasHeightForWidth())
        self.frame_RNVA_5.setSizePolicy(sizePolicy)
        self.frame_RNVA_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_RNVA_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_RNVA_5.setObjectName(_fromUtf8("frame_RNVA_5"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.frame_RNVA_5)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setMargin(0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_12 = QtGui.QLabel(self.frame_RNVA_5)
        self.label_12.setMinimumSize(QtCore.QSize(300, 0))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_21.addWidget(self.label_12)
        self.cmbC16 = QtGui.QComboBox(self.frame_RNVA_5)
        self.cmbC16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.cmbC16.setFont(font)
        self.cmbC16.setFrame(True)
        self.cmbC16.setObjectName(_fromUtf8("cmbC16"))
        self.horizontalLayout_21.addWidget(self.cmbC16)
        self.verticalLayout_gbAeroData.addWidget(self.frame_RNVA_5)
        self.vLayoutTabIlsCrm.addWidget(self.gbAeroData)
        self.gbReqCase = QtGui.QGroupBox(self.tabCrm)
        self.gbReqCase.setObjectName(_fromUtf8("gbReqCase"))
        self.verticalLayout_gbReqCase = QtGui.QVBoxLayout(self.gbReqCase)
        self.verticalLayout_gbReqCase.setObjectName(_fromUtf8("verticalLayout_gbReqCase"))
        self.frame_RNVA_6 = QtGui.QFrame(self.gbReqCase)
        self.frame_RNVA_6.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_RNVA_6.sizePolicy().hasHeightForWidth())
        self.frame_RNVA_6.setSizePolicy(sizePolicy)
        self.frame_RNVA_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_RNVA_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_RNVA_6.setObjectName(_fromUtf8("frame_RNVA_6"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.frame_RNVA_6)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setMargin(0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_13 = QtGui.QLabel(self.frame_RNVA_6)
        self.label_13.setMinimumSize(QtCore.QSize(300, 0))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_22.addWidget(self.label_13)
        self.cmbC17 = QtGui.QComboBox(self.frame_RNVA_6)
        self.cmbC17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.cmbC17.setFont(font)
        self.cmbC17.setFrame(True)
        self.cmbC17.setObjectName(_fromUtf8("cmbC17"))
        self.horizontalLayout_22.addWidget(self.cmbC17)
        self.verticalLayout_gbReqCase.addWidget(self.frame_RNVA_6)
        self.frame_RNVA_7 = QtGui.QFrame(self.gbReqCase)
        self.frame_RNVA_7.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_RNVA_7.sizePolicy().hasHeightForWidth())
        self.frame_RNVA_7.setSizePolicy(sizePolicy)
        self.frame_RNVA_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_RNVA_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_RNVA_7.setObjectName(_fromUtf8("frame_RNVA_7"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.frame_RNVA_7)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setMargin(0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_14 = QtGui.QLabel(self.frame_RNVA_7)
        self.label_14.setMinimumSize(QtCore.QSize(300, 0))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_23.addWidget(self.label_14)
        self.cmbC18 = QtGui.QComboBox(self.frame_RNVA_7)
        self.cmbC18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.cmbC18.setFont(font)
        self.cmbC18.setFrame(True)
        self.cmbC18.setObjectName(_fromUtf8("cmbC18"))
        self.horizontalLayout_23.addWidget(self.cmbC18)
        self.verticalLayout_gbReqCase.addWidget(self.frame_RNVA_7)
        self.frame = QtGui.QFrame(self.gbReqCase)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame_2 = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame_2)
        self.groupBox_3 = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_3.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(self.groupBox_3)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_3.addWidget(self.label_22)
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_3.addWidget(self.label_23)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMaximumSize(QtCore.QSize(220, 16777215))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_24 = QtGui.QLabel(self.groupBox_4)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_5.addWidget(self.label_24)
        self.frame_3 = QtGui.QFrame(self.groupBox_4)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cmbC19XA = QtGui.QComboBox(self.frame_3)
        self.cmbC19XA.setObjectName(_fromUtf8("cmbC19XA"))
        self.horizontalLayout_2.addWidget(self.cmbC19XA)
        self.label_25 = QtGui.QLabel(self.frame_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_2.addWidget(self.label_25)
        self.txtC19ZA = QtGui.QLineEdit(self.frame_3)
        self.txtC19ZA.setEnabled(False)
        self.txtC19ZA.setObjectName(_fromUtf8("txtC19ZA"))
        self.horizontalLayout_2.addWidget(self.txtC19ZA)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(self.groupBox_4)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cmbC19XB = QtGui.QComboBox(self.frame_4)
        self.cmbC19XB.setObjectName(_fromUtf8("cmbC19XB"))
        self.horizontalLayout_3.addWidget(self.cmbC19XB)
        self.label_26 = QtGui.QLabel(self.frame_4)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_3.addWidget(self.label_26)
        self.txtC19ZB = QtGui.QLineEdit(self.frame_4)
        self.txtC19ZB.setEnabled(False)
        self.txtC19ZB.setObjectName(_fromUtf8("txtC19ZB"))
        self.horizontalLayout_3.addWidget(self.txtC19ZB)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.frame_5 = QtGui.QFrame(self.groupBox_4)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cmbC19XC = QtGui.QComboBox(self.frame_5)
        self.cmbC19XC.setObjectName(_fromUtf8("cmbC19XC"))
        self.horizontalLayout_4.addWidget(self.cmbC19XC)
        self.label_27 = QtGui.QLabel(self.frame_5)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_4.addWidget(self.label_27)
        self.txtC19ZC = QtGui.QLineEdit(self.frame_5)
        self.txtC19ZC.setEnabled(False)
        self.txtC19ZC.setObjectName(_fromUtf8("txtC19ZC"))
        self.horizontalLayout_4.addWidget(self.txtC19ZC)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.frame_6 = QtGui.QFrame(self.groupBox_4)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.cmbC19XD = QtGui.QComboBox(self.frame_6)
        self.cmbC19XD.setObjectName(_fromUtf8("cmbC19XD"))
        self.horizontalLayout_5.addWidget(self.cmbC19XD)
        self.label_28 = QtGui.QLabel(self.frame_6)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_5.addWidget(self.label_28)
        self.txtC19ZD = QtGui.QLineEdit(self.frame_6)
        self.txtC19ZD.setEnabled(False)
        self.txtC19ZD.setObjectName(_fromUtf8("txtC19ZD"))
        self.horizontalLayout_5.addWidget(self.txtC19ZD)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_29 = QtGui.QLabel(self.groupBox_5)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_6.addWidget(self.label_29)
        self.frame_7 = QtGui.QFrame(self.groupBox_5)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.cmbC19YA = QtGui.QComboBox(self.frame_7)
        self.cmbC19YA.setObjectName(_fromUtf8("cmbC19YA"))
        self.verticalLayout_7.addWidget(self.cmbC19YA)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.frame_8 = QtGui.QFrame(self.groupBox_5)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.cmbC19YB = QtGui.QComboBox(self.frame_8)
        self.cmbC19YB.setObjectName(_fromUtf8("cmbC19YB"))
        self.verticalLayout_9.addWidget(self.cmbC19YB)
        self.verticalLayout_6.addWidget(self.frame_8)
        self.frame_9 = QtGui.QFrame(self.groupBox_5)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.cmbC19YC = QtGui.QComboBox(self.frame_9)
        self.cmbC19YC.setObjectName(_fromUtf8("cmbC19YC"))
        self.verticalLayout_8.addWidget(self.cmbC19YC)
        self.verticalLayout_6.addWidget(self.frame_9)
        self.frame_10 = QtGui.QFrame(self.groupBox_5)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame_10)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.cmbC19YD = QtGui.QComboBox(self.frame_10)
        self.cmbC19YD.setObjectName(_fromUtf8("cmbC19YD"))
        self.verticalLayout_10.addWidget(self.cmbC19YD)
        self.verticalLayout_6.addWidget(self.frame_10)
        self.horizontalLayout.addWidget(self.groupBox_5)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_gbReqCase.addWidget(self.frame)
        self.vLayoutTabIlsCrm.addWidget(self.gbReqCase)
        self.gbRepFormat = QtGui.QGroupBox(self.tabCrm)
        self.gbRepFormat.setObjectName(_fromUtf8("gbRepFormat"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.gbRepFormat)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.frame_RNVA_9 = QtGui.QFrame(self.gbRepFormat)
        self.frame_RNVA_9.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_RNVA_9.sizePolicy().hasHeightForWidth())
        self.frame_RNVA_9.setSizePolicy(sizePolicy)
        self.frame_RNVA_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_RNVA_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_RNVA_9.setObjectName(_fromUtf8("frame_RNVA_9"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.frame_RNVA_9)
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setMargin(0)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_30 = QtGui.QLabel(self.frame_RNVA_9)
        self.label_30.setMinimumSize(QtCore.QSize(300, 0))
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_30.addWidget(self.label_30)
        self.cmbC22 = QtGui.QComboBox(self.frame_RNVA_9)
        self.cmbC22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.cmbC22.setFont(font)
        self.cmbC22.setFrame(True)
        self.cmbC22.setObjectName(_fromUtf8("cmbC22"))
        self.horizontalLayout_30.addWidget(self.cmbC22)
        self.verticalLayout_11.addWidget(self.frame_RNVA_9)
        self.vLayoutTabIlsCrm.addWidget(self.gbRepFormat)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.gbSettings.setTitle(_translate("Form", "Save CRM Obstacle File", None))
        self.label_75.setText(_translate("Form", "Obstacle File:", None))
        self.btnBrowser.setText(_translate("Form", "...", None))
        self.chbAutoRun.setText(_translate("Form", "Automatically run the ICAO CRM after a successful obstacle file creation", None))
        self.gbAdminData.setTitle(_translate("Form", "Administrative Data", None))
        self.label_4.setText(_translate("Form", "[02] User Reference:", None))
        self.txtC02.setText(_translate("Form", "Name", None))
        self.label_6.setText(_translate("Form", "[03] Title:", None))
        self.txtC03.setText(_translate("Form", "...", None))
        self.gbGroundData.setTitle(_translate("Form", "Ground Data", None))
        self.label_7.setText(_translate("Form", "[07] ILS Glide Path Angle (°):", None))
        self.txtC07.setText(_translate("Form", "3.0", None))
        self.label_17.setText(_translate("Form", "[08] ILS Reference Datum Height (m):", None))
        self.txtC08.setText(_translate("Form", "15", None))
        self.label_3.setText(_translate("Form", "[10] LOC cource Width at THR (m):", None))
        self.txtC10.setText(_translate("Form", "210", None))
        self.label_9.setText(_translate("Form", "[12] Distance FAP to THR (m):", None))
        self.txtC12.setText(_translate("Form", "10807", None))
        self.label_8.setText(_translate("Form", "[13] Standard Termination of Precision Segment:", None))
        self.label_15.setText(_translate("Form", "          a) Turmination Point Before THR:", None))
        self.label_16.setText(_translate("Form", "          b) Distance Turmination Point to THR (m):", None))
        self.txtC13b.setText(_translate("Form", "1852", None))
        self.gbAeroData.setTitle(_translate("Form", "Aeroplane Data", None))
        self.label_10.setText(_translate("Form", "[14] Standard Dimensions:", None))
        self.label_18.setText(_translate("Form", "          a) GP Wheel / Antenna Height (m):", None))
        self.txtC14a.setText(_translate("Form", "6", None))
        self.label_19.setText(_translate("Form", "          b) Wing Semispan (m):", None))
        self.txtC14b.setText(_translate("Form", "30", None))
        self.label_11.setText(_translate("Form", "[15] Standard Missed Approach Climb Gradient:", None))
        self.label_20.setText(_translate("Form", "          Climb Gradient (%):", None))
        self.txtC15a.setText(_translate("Form", "2.5", None))
        self.label_12.setText(_translate("Form", "[16] ILS Approach Category: ", None))
        self.gbReqCase.setTitle(_translate("Form", "Requested Case (Cont)", None))
        self.label_13.setText(_translate("Form", "[17] Select Choice of OCA or OCH: ", None))
        self.label_14.setText(_translate("Form", "[18] Select Unit of Measurement for OCA/H:", None))
        self.label.setText(_translate("Form", "[19]", None))
        self.label_2.setText(_translate("Form", "Category", None))
        self.label_5.setText(_translate("Form", "A", None))
        self.label_21.setText(_translate("Form", "B", None))
        self.label_22.setText(_translate("Form", "C", None))
        self.label_23.setText(_translate("Form", "D", None))
        self.label_24.setText(_translate("Form", "Risk for Specified OCA/H Requested?", None))
        self.label_25.setText(_translate("Form", "OCA (m):", None))
        self.txtC19ZA.setText(_translate("Form", "61", None))
        self.label_26.setText(_translate("Form", "OCA (m):", None))
        self.txtC19ZB.setText(_translate("Form", "61", None))
        self.label_27.setText(_translate("Form", "OCA (m):", None))
        self.txtC19ZC.setText(_translate("Form", "61", None))
        self.label_28.setText(_translate("Form", "OCA (m):", None))
        self.txtC19ZD.setText(_translate("Form", "61", None))
        self.label_29.setText(_translate("Form", "Minimum Acceptable OCA/H Requested?", None))
        self.gbRepFormat.setTitle(_translate("Form", "Report Format", None))
        self.label_30.setText(_translate("Form", "[22] Individual Obstacle Risk Requested For:", None))
        self.gbCoordSystem.setTitle(_translate("Form", "Aerodrome Data", None))

