# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chartingBase.ui'
#
# Created: Tue Sep 13 14:44:21 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from FlightPlanner.Panels.GroupBox import GroupBox
from FlightPlanner.Panels.ComboBoxPanel import ComboBoxPanel

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ChartingBase(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(694, 695)

        self.horizontalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -335, 1053, 1003))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        # self.stackedWidget = QtGui.QStackedWidget(self.scrollAreaWidgetContents_2)
        # self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        # self.page = QtGui.QWidget(Dialog)
        # self.page.setObjectName(_fromUtf8("page"))
        # self.verticalLayout_3 = QtGui.QVBoxLayout(self.page)
        # self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        # self.frame_13 = QtGui.QFrame(self.page)
        # self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        # self.frame_13.setObjectName(_fromUtf8("frame_13"))
        # self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_13)
        # self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        # spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        # self.horizontalLayout_6.addItem(spacerItem)
        # self.frame_3 = QtGui.QFrame(self.frame_13)
        # self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        # self.frame_3.setObjectName(_fromUtf8("frame_3"))
        # self.verticalLayout_9 = QtGui.QVBoxLayout(self.frame_3)
        # self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        #
        # spacerItem111 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        # self.verticalLayout_9.addItem(spacerItem111);
        #
        # self.gbTemplate = QtGui.QGroupBox(self.frame_3);
        # self.gbTemplate.setObjectName("gbTemplate");
        # self.verticalLayoutgbTemplate = QtGui.QVBoxLayout(self.gbTemplate);
        # self.verticalLayoutgbTemplate.setObjectName("self.verticalLayoutgbTemplate");
        # self.cmbTemplate = QtGui.QComboBox(self.gbTemplate);
        # self.cmbTemplate.setObjectName("cmbTemplate")
        #
        # self.verticalLayoutgbTemplate.addWidget(self.cmbTemplate);
        #
        #
        # self.verticalLayout_9.addWidget(self.gbTemplate);
        # self.gbTemplate.setTitle("Template")
        #
        # # self.cmbTemplate = ComboBoxPanel(self.gbTemplate)
        # # self.cmbTemplate.LabelWidth = 0
        # self.cmbTemplate.addItems(["ILS or LOC","LOC", "VOR", "NDB", "TACAN", "RNP BAROVNAV, SBAS, LNAV",
        #                           "RNP BAROVNAV, LNAV", "RNP SBAS, LNAV", "RNP LNAV", "RNP AR", "RNAV STAR",
        #                           "RNAV SID", "CONV STAR", "CONV SID"])
        # # self.verticalLayoutgbTemplate.addWidget(self.cmbTemplate)
        #
        # self.frmState = QtGui.QFrame(self.frame_3)
        # self.frmState.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frmState.setFrameShadow(QtGui.QFrame.Raised)
        # self.frmState.setObjectName(_fromUtf8("frmState"))
        # self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frmState)
        # self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        # self.lblState = QtGui.QLabel(self.frmState)
        # self.lblState.setMinimumSize(QtCore.QSize(90, 0))
        # self.lblState.setMaximumSize(QtCore.QSize(90, 16777215))
        # self.lblState.setObjectName(_fromUtf8("lblState"))
        # self.horizontalLayout_3.addWidget(self.lblState)
        # self.ddlState = QtGui.QComboBox(self.frmState)
        # self.ddlState.setObjectName(_fromUtf8("ddlState"))
        # self.horizontalLayout_3.addWidget(self.ddlState)
        # self.verticalLayout_9.addWidget(self.frmState)
        # self.frmAerodrome = QtGui.QFrame(self.frame_3)
        # self.frmAerodrome.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frmAerodrome.setFrameShadow(QtGui.QFrame.Raised)
        # self.frmAerodrome.setObjectName(_fromUtf8("frmAerodrome"))
        # self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frmAerodrome)
        # self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        # self.lblAerodrome = QtGui.QLabel(self.frmAerodrome)
        # self.lblAerodrome.setMinimumSize(QtCore.QSize(90, 0))
        # self.lblAerodrome.setMaximumSize(QtCore.QSize(90, 16777215))
        # self.lblAerodrome.setObjectName(_fromUtf8("lblAerodrome"))
        # self.horizontalLayout_4.addWidget(self.lblAerodrome)
        # self.ddlAerodrome = QtGui.QComboBox(self.frmAerodrome)
        # self.ddlAerodrome.setObjectName(_fromUtf8("ddlAerodrome"))
        # self.horizontalLayout_4.addWidget(self.ddlAerodrome)
        # self.verticalLayout_9.addWidget(self.frmAerodrome)
        # self.frmRunway = QtGui.QFrame(self.frame_3)
        # self.frmRunway.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frmRunway.setFrameShadow(QtGui.QFrame.Raised)
        # self.frmRunway.setObjectName(_fromUtf8("frmRunway"))
        # self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frmRunway)
        # self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        # self.lblRunway = QtGui.QLabel(self.frmRunway)
        # self.lblRunway.setMinimumSize(QtCore.QSize(90, 0))
        # self.lblRunway.setMaximumSize(QtCore.QSize(90, 16777215))
        # self.lblRunway.setObjectName(_fromUtf8("lblRunway"))
        # self.horizontalLayout_5.addWidget(self.lblRunway)
        # self.ddlRunway1 = QtGui.QComboBox(self.frmRunway)
        # self.ddlRunway1.setObjectName(_fromUtf8("ddlRunway1"))
        # self.horizontalLayout_5.addWidget(self.ddlRunway1)
        # self.ddlRunway2 = QtGui.QComboBox(self.frmRunway)
        # self.ddlRunway2.setObjectName(_fromUtf8("ddlRunway2"))
        # self.horizontalLayout_5.addWidget(self.ddlRunway2)
        # self.verticalLayout_9.addWidget(self.frmRunway)
        # self.frmSlope = QtGui.QFrame(self.frame_3)
        # self.frmSlope.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frmSlope.setFrameShadow(QtGui.QFrame.Raised)
        # self.frmSlope.setObjectName(_fromUtf8("frmSlope"))
        # self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frmSlope)
        # self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        # self.lblSlope = QtGui.QLabel(self.frmSlope)
        # self.lblSlope.setMinimumSize(QtCore.QSize(90, 0))
        # self.lblSlope.setMaximumSize(QtCore.QSize(90, 16777215))
        # self.lblSlope.setObjectName(_fromUtf8("lblSlope"))
        # self.horizontalLayout_7.addWidget(self.lblSlope)
        # self.ddlSlope = QtGui.QComboBox(self.frmSlope)
        # self.ddlSlope.setObjectName(_fromUtf8("ddlSlope"))
        # self.horizontalLayout_7.addWidget(self.ddlSlope)
        # self.verticalLayout_9.addWidget(self.frmSlope)
        # self.frmPrintScale = QtGui.QFrame(self.frame_3)
        # self.frmPrintScale.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frmPrintScale.setFrameShadow(QtGui.QFrame.Raised)
        # self.frmPrintScale.setObjectName(_fromUtf8("frmPrintScale"))
        # self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frmPrintScale)
        # self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        # self.lblPrintScale = QtGui.QLabel(self.frmPrintScale)
        # self.lblPrintScale.setMinimumSize(QtCore.QSize(90, 0))
        # self.lblPrintScale.setMaximumSize(QtCore.QSize(90, 16777215))
        # self.lblPrintScale.setObjectName(_fromUtf8("lblPrintScale"))
        # self.horizontalLayout_8.addWidget(self.lblPrintScale)
        # self.txtPrintScale = QtGui.QLineEdit(self.frmPrintScale)
        # self.txtPrintScale.setObjectName(_fromUtf8("txtPrintScale"))
        # self.horizontalLayout_8.addWidget(self.txtPrintScale)
        # self.verticalLayout_9.addWidget(self.frmPrintScale)
        # self.frmFontSize = QtGui.QFrame(self.frame_3)
        # self.frmFontSize.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frmFontSize.setFrameShadow(QtGui.QFrame.Raised)
        # self.frmFontSize.setObjectName(_fromUtf8("frmFontSize"))
        # self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frmFontSize)
        # self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        # self.lblFontSize = QtGui.QLabel(self.frmFontSize)
        # self.lblFontSize.setMinimumSize(QtCore.QSize(90, 0))
        # self.lblFontSize.setMaximumSize(QtCore.QSize(90, 16777215))
        # self.lblFontSize.setObjectName(_fromUtf8("lblFontSize"))
        # self.horizontalLayout_9.addWidget(self.lblFontSize)
        # self.txtFontSize = QtGui.QLineEdit(self.frmFontSize)
        # self.txtFontSize.setObjectName(_fromUtf8("txtFontSize"))
        # self.horizontalLayout_9.addWidget(self.txtFontSize)
        # self.verticalLayout_9.addWidget(self.frmFontSize)
        # self.gbSizes = QtGui.QGroupBox(self.frame_3)
        # self.gbSizes.setObjectName(_fromUtf8("gbSizes"))
        # self.verticalLayout_10 = QtGui.QVBoxLayout(self.gbSizes)
        # self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        # self.ddlPageSizes = QtGui.QComboBox(self.gbSizes)
        # self.ddlPageSizes.setObjectName(_fromUtf8("ddlPageSizes"))
        # self.verticalLayout_10.addWidget(self.ddlPageSizes)
        # self.frame_11 = QtGui.QFrame(self.gbSizes)
        # self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        # self.frame_11.setObjectName(_fromUtf8("frame_11"))
        # self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frame_11)
        # self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        # self.rbtnInch = QtGui.QRadioButton(self.frame_11)
        # self.rbtnInch.setChecked(True)
        # self.rbtnInch.setObjectName(_fromUtf8("rbtnInch"))
        # self.horizontalLayout_10.addWidget(self.rbtnInch)
        # self.rbtnmm = QtGui.QRadioButton(self.frame_11)
        # self.rbtnmm.setObjectName(_fromUtf8("rbtnmm"))
        # self.horizontalLayout_10.addWidget(self.rbtnmm)
        # self.verticalLayout_10.addWidget(self.frame_11)
        # self.frmWidth = QtGui.QFrame(self.gbSizes)
        # self.frmWidth.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frmWidth.setFrameShadow(QtGui.QFrame.Raised)
        # self.frmWidth.setObjectName(_fromUtf8("frmWidth"))
        # self.horizontalLayout_12 = QtGui.QHBoxLayout(self.frmWidth)
        # self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        # self.lblWidth = QtGui.QLabel(self.frmWidth)
        # self.lblWidth.setMinimumSize(QtCore.QSize(81, 0))
        # self.lblWidth.setMaximumSize(QtCore.QSize(81, 16777215))
        # self.lblWidth.setObjectName(_fromUtf8("lblWidth"))
        # self.horizontalLayout_12.addWidget(self.lblWidth)
        # self.txtWidth = QtGui.QLineEdit(self.frmWidth)
        # self.txtWidth.setObjectName(_fromUtf8("txtWidth"))
        # self.horizontalLayout_12.addWidget(self.txtWidth)
        # self.verticalLayout_10.addWidget(self.frmWidth)
        # self.frmHeight = QtGui.QFrame(self.gbSizes)
        # self.frmHeight.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frmHeight.setFrameShadow(QtGui.QFrame.Raised)
        # self.frmHeight.setObjectName(_fromUtf8("frmHeight"))
        # self.horizontalLayout_13 = QtGui.QHBoxLayout(self.frmHeight)
        # self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        # self.lblHeight = QtGui.QLabel(self.frmHeight)
        # self.lblHeight.setMinimumSize(QtCore.QSize(81, 0))
        # self.lblHeight.setMaximumSize(QtCore.QSize(81, 16777215))
        # self.lblHeight.setObjectName(_fromUtf8("lblHeight"))
        # self.horizontalLayout_13.addWidget(self.lblHeight)
        # self.txtHeight = QtGui.QLineEdit(self.frmHeight)
        # self.txtHeight.setObjectName(_fromUtf8("txtHeight"))
        # self.horizontalLayout_13.addWidget(self.txtHeight)
        # self.verticalLayout_10.addWidget(self.frmHeight)
        # self.verticalLayout_9.addWidget(self.gbSizes)
        # self.gbPageOrientation = QtGui.QGroupBox(self.frame_3)
        # self.gbPageOrientation.setObjectName(_fromUtf8("gbPageOrientation"))
        # self.horizontalLayout_14 = QtGui.QHBoxLayout(self.gbPageOrientation)
        # self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        # self.rbtLandscape = QtGui.QRadioButton(self.gbPageOrientation)
        # self.rbtLandscape.setObjectName(_fromUtf8("radioButton"))
        # self.horizontalLayout_14.addWidget(self.rbtLandscape)
        # self.rbtPortrait = QtGui.QRadioButton(self.gbPageOrientation)
        # self.rbtPortrait.setChecked(True)
        # self.rbtPortrait.setObjectName(_fromUtf8("rblLandscape"))
        # self.horizontalLayout_14.addWidget(self.rbtPortrait)
        # self.verticalLayout_9.addWidget(self.gbPageOrientation)
        # self.horizontalLayout_6.addWidget(self.frame_3)
        # spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        # self.horizontalLayout_6.addItem(spacerItem1)
        # self.verticalLayout_3.addWidget(self.frame_13)
        # self.stackedWidget.addWidget(self.page)
        # self.page_2 = QtGui.QWidget()
        # self.page_2.setObjectName(_fromUtf8("page_2"))
        # self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_2)
        # self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame_2 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_4 = QtGui.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frame_6 = QtGui.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_18.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem2)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.frame_5 = QtGui.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.frmState_2 = QtGui.QFrame(self.frame_5)
        self.frmState_2.setMaximumSize(QtCore.QSize(210, 16777215))
        self.frmState_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmState_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frmState_2.setObjectName(_fromUtf8("frmState_2"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.frmState_2)
        self.horizontalLayout_15.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.lblState_4 = QtGui.QLabel(self.frmState_2)
        self.lblState_4.setMinimumSize(QtCore.QSize(60, 0))
        self.lblState_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblState_4.setObjectName(_fromUtf8("lblState_4"))
        self.horizontalLayout_15.addWidget(self.lblState_4)
        self.txtText1 = QtGui.QLineEdit(self.frmState_2)
        self.txtText1.setMinimumSize(QtCore.QSize(130, 0))
        self.txtText1.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txtText1.setObjectName(_fromUtf8("txtText1"))
        self.horizontalLayout_15.addWidget(self.txtText1)
        self.horizontalLayout_16.addWidget(self.frmState_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.frmState_4 = QtGui.QFrame(self.frame_5)
        self.frmState_4.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frmState_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmState_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frmState_4.setObjectName(_fromUtf8("frmState_4"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.frmState_4)
        self.horizontalLayout_21.setContentsMargins(19, 0, -1, 0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.lblState_6 = QtGui.QLabel(self.frmState_4)
        self.lblState_6.setMinimumSize(QtCore.QSize(60, 0))
        self.lblState_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblState_6.setObjectName(_fromUtf8("lblState_6"))
        self.horizontalLayout_21.addWidget(self.lblState_6)
        self.txtText2 = QtGui.QLineEdit(self.frmState_4)
        self.txtText2.setMinimumSize(QtCore.QSize(130, 0))
        self.txtText2.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txtText2.setObjectName(_fromUtf8("txtText2"))
        self.horizontalLayout_21.addWidget(self.txtText2)
        self.horizontalLayout_16.addWidget(self.frmState_4)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.frmState_5 = QtGui.QFrame(self.frame_5)
        self.frmState_5.setMaximumSize(QtCore.QSize(210, 16777215))
        self.frmState_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmState_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frmState_5.setObjectName(_fromUtf8("frmState_5"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.frmState_5)
        self.horizontalLayout_20.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.lblState_7 = QtGui.QLabel(self.frmState_5)
        self.lblState_7.setMinimumSize(QtCore.QSize(60, 0))
        self.lblState_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblState_7.setObjectName(_fromUtf8("lblState_7"))
        self.horizontalLayout_20.addWidget(self.lblState_7)
        self.txtText3 = QtGui.QLineEdit(self.frmState_5)
        self.txtText3.setMinimumSize(QtCore.QSize(130, 0))
        self.txtText3.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txtText3.setObjectName(_fromUtf8("txtText3"))
        self.horizontalLayout_20.addWidget(self.txtText3)
        self.horizontalLayout_16.addWidget(self.frmState_5)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.frame_7 = QtGui.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_19.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.frmState_3 = QtGui.QFrame(self.frame_7)
        self.frmState_3.setMaximumSize(QtCore.QSize(210, 16777215))
        self.frmState_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmState_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frmState_3.setObjectName(_fromUtf8("frmState_3"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.frmState_3)
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.lblState_5 = QtGui.QLabel(self.frmState_3)
        self.lblState_5.setMinimumSize(QtCore.QSize(60, 0))
        self.lblState_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblState_5.setObjectName(_fromUtf8("lblState_5"))
        self.horizontalLayout_17.addWidget(self.lblState_5)
        self.txtText4 = QtGui.QTextEdit(self.frmState_3)
        self.txtText4.setMinimumSize(QtCore.QSize(130, 0))
        self.txtText4.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txtText4.setObjectName(_fromUtf8("txtText4"))
        self.horizontalLayout_17.addWidget(self.txtText4)
        self.horizontalLayout_19.addWidget(self.frmState_3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.frmState_6 = QtGui.QFrame(self.frame_7)
        self.frmState_6.setMaximumSize(QtCore.QSize(210, 16777215))
        self.frmState_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmState_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frmState_6.setObjectName(_fromUtf8("frmState_6"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.frmState_6)
        self.horizontalLayout_22.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.lblState_8 = QtGui.QLabel(self.frmState_6)
        self.lblState_8.setMinimumSize(QtCore.QSize(60, 0))
        self.lblState_8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblState_8.setObjectName(_fromUtf8("lblState_8"))
        self.horizontalLayout_22.addWidget(self.lblState_8)
        self.txtText5 = QtGui.QTextEdit(self.frmState_6)
        self.txtText5.setMinimumSize(QtCore.QSize(130, 0))
        self.txtText5.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txtText5.setObjectName(_fromUtf8("txtText5"))
        self.horizontalLayout_22.addWidget(self.txtText5)
        self.horizontalLayout_19.addWidget(self.frmState_6)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.frmState_9 = QtGui.QFrame(self.frame_7)
        self.frmState_9.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frmState_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmState_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frmState_9.setObjectName(_fromUtf8("frmState_9"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.frmState_9)
        self.horizontalLayout_27.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.lblState_11 = QtGui.QLabel(self.frmState_9)
        self.lblState_11.setMinimumSize(QtCore.QSize(60, 0))
        self.lblState_11.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblState_11.setObjectName(_fromUtf8("lblState_11"))
        self.horizontalLayout_27.addWidget(self.lblState_11)
        self.txtText6 = QtGui.QTextEdit(self.frmState_9)
        self.txtText6.setMinimumSize(QtCore.QSize(130, 0))
        self.txtText6.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txtText6.setObjectName(_fromUtf8("txtText6"))
        self.horizontalLayout_27.addWidget(self.txtText6)
        self.horizontalLayout_19.addWidget(self.frmState_9)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem7)
        self.frmState_7 = QtGui.QFrame(self.frame_7)
        self.frmState_7.setMaximumSize(QtCore.QSize(210, 16777215))
        self.frmState_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmState_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frmState_7.setObjectName(_fromUtf8("frmState_7"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.frmState_7)
        self.horizontalLayout_24.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.lblState_9 = QtGui.QLabel(self.frmState_7)
        self.lblState_9.setMinimumSize(QtCore.QSize(60, 0))
        self.lblState_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblState_9.setObjectName(_fromUtf8("lblState_9"))
        self.horizontalLayout_24.addWidget(self.lblState_9)
        self.txtText7 = QtGui.QTextEdit(self.frmState_7)
        self.txtText7.setMinimumSize(QtCore.QSize(130, 0))
        self.txtText7.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txtText7.setObjectName(_fromUtf8("txtText7"))
        self.horizontalLayout_24.addWidget(self.txtText7)
        self.horizontalLayout_19.addWidget(self.frmState_7)
        self.verticalLayout_5.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_9 = QtGui.QFrame(self.frame_2)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.frame_9)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.frame_12 = QtGui.QFrame(self.frame_9)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_12)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem8 = QtGui.QSpacerItem(20, 430, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.frmState_11 = QtGui.QFrame(self.frame_12)
        self.frmState_11.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frmState_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmState_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frmState_11.setObjectName(_fromUtf8("frmState_11"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.frmState_11)
        self.horizontalLayout_30.setContentsMargins(19, 0, -1, 0)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.lblState_14 = QtGui.QLabel(self.frmState_11)
        self.lblState_14.setMinimumSize(QtCore.QSize(60, 0))
        self.lblState_14.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblState_14.setObjectName(_fromUtf8("lblState_14"))
        self.horizontalLayout_30.addWidget(self.lblState_14)
        self.txtText8 = QtGui.QLineEdit(self.frmState_11)
        self.txtText8.setMinimumSize(QtCore.QSize(130, 0))
        self.txtText8.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txtText8.setObjectName(_fromUtf8("txtText8"))
        self.horizontalLayout_30.addWidget(self.txtText8)
        self.verticalLayout.addWidget(self.frmState_11)
        self.frmState_10 = QtGui.QFrame(self.frame_12)
        self.frmState_10.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frmState_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmState_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frmState_10.setObjectName(_fromUtf8("frmState_10"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.frmState_10)
        self.horizontalLayout_31.setContentsMargins(19, 0, -1, 0)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.lblState_15 = QtGui.QLabel(self.frmState_10)
        self.lblState_15.setMinimumSize(QtCore.QSize(60, 0))
        self.lblState_15.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblState_15.setObjectName(_fromUtf8("lblState_15"))
        self.horizontalLayout_31.addWidget(self.lblState_15)
        self.txtText9 = QtGui.QLineEdit(self.frmState_10)
        self.txtText9.setMinimumSize(QtCore.QSize(130, 0))
        self.txtText9.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txtText9.setObjectName(_fromUtf8("txtText9"))
        self.horizontalLayout_31.addWidget(self.txtText9)
        self.verticalLayout.addWidget(self.frmState_10)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_26.addWidget(self.frame_12)
        self.pictureBox1 = QtGui.QFrame(self.frame_9)
        self.pictureBox1.setMinimumSize(QtCore.QSize(479, 671))
        self.pictureBox1.setMaximumSize(QtCore.QSize(479, 671))
        self.pictureBox1.setStyleSheet(_fromUtf8("background-image: url(Resource/chartingImage/chartingTemp.png);"))
        self.pictureBox1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pictureBox1.setFrameShadow(QtGui.QFrame.Raised)
        self.pictureBox1.setObjectName(_fromUtf8("pictureBox1"))
        self.horizontalLayout_26.addWidget(self.pictureBox1)
        self.frame_10 = QtGui.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        spacerItem10 = QtGui.QSpacerItem(20, 430, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem10)
        self.frmState_12 = QtGui.QFrame(self.frame_10)
        self.frmState_12.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frmState_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmState_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frmState_12.setObjectName(_fromUtf8("frmState_12"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout(self.frmState_12)
        self.horizontalLayout_32.setContentsMargins(19, 0, -1, 0)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.lblState_16 = QtGui.QLabel(self.frmState_12)
        self.lblState_16.setMinimumSize(QtCore.QSize(60, 0))
        self.lblState_16.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblState_16.setObjectName(_fromUtf8("lblState_16"))
        self.horizontalLayout_32.addWidget(self.lblState_16)
        self.txtText10 = QtGui.QLineEdit(self.frmState_12)
        self.txtText10.setMinimumSize(QtCore.QSize(130, 0))
        self.txtText10.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txtText10.setObjectName(_fromUtf8("txtText10"))
        self.horizontalLayout_32.addWidget(self.txtText10)
        self.verticalLayout_7.addWidget(self.frmState_12)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem11)
        self.horizontalLayout_26.addWidget(self.frame_10)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem12)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.frame_8 = QtGui.QFrame(self.frame_2)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.frame_8)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.frmState_13 = QtGui.QFrame(self.frame_8)
        self.frmState_13.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frmState_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmState_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frmState_13.setObjectName(_fromUtf8("frmState_13"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout(self.frmState_13)
        self.horizontalLayout_33.setContentsMargins(19, 0, -1, 0)
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.lblState_17 = QtGui.QLabel(self.frmState_13)
        self.lblState_17.setMinimumSize(QtCore.QSize(60, 0))
        self.lblState_17.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblState_17.setObjectName(_fromUtf8("lblState_17"))
        self.horizontalLayout_33.addWidget(self.lblState_17)
        self.txtText11 = QtGui.QLineEdit(self.frmState_13)
        self.txtText11.setMinimumSize(QtCore.QSize(130, 0))
        self.txtText11.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txtText11.setObjectName(_fromUtf8("txtText11"))
        self.horizontalLayout_33.addWidget(self.txtText11)
        self.horizontalLayout_23.addWidget(self.frmState_13)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem13)
        self.frmState_14 = QtGui.QFrame(self.frame_8)
        self.frmState_14.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frmState_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmState_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frmState_14.setObjectName(_fromUtf8("frmState_14"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout(self.frmState_14)
        self.horizontalLayout_34.setContentsMargins(19, 0, -1, 0)
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.lblState_18 = QtGui.QLabel(self.frmState_14)
        self.lblState_18.setMinimumSize(QtCore.QSize(60, 0))
        self.lblState_18.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblState_18.setObjectName(_fromUtf8("lblState_18"))
        self.horizontalLayout_34.addWidget(self.lblState_18)
        self.txtText12 = QtGui.QLineEdit(self.frmState_14)
        self.txtText12.setMinimumSize(QtCore.QSize(130, 0))
        self.txtText12.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txtText12.setObjectName(_fromUtf8("txtText12"))
        self.horizontalLayout_34.addWidget(self.txtText12)
        self.horizontalLayout_23.addWidget(self.frmState_14)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem14)
        self.frmState_8 = QtGui.QFrame(self.frame_8)
        self.frmState_8.setMaximumSize(QtCore.QSize(210, 16777215))
        self.frmState_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmState_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frmState_8.setObjectName(_fromUtf8("frmState_8"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.frmState_8)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.lblState_10 = QtGui.QLabel(self.frmState_8)
        self.lblState_10.setMinimumSize(QtCore.QSize(60, 0))
        self.lblState_10.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblState_10.setObjectName(_fromUtf8("lblState_10"))
        self.horizontalLayout_25.addWidget(self.lblState_10)
        self.txtText13 = QtGui.QLineEdit(self.frmState_8)
        self.txtText13.setMinimumSize(QtCore.QSize(130, 0))
        self.txtText13.setMaximumSize(QtCore.QSize(130, 16777215))
        self.txtText13.setObjectName(_fromUtf8("txtText13"))
        self.horizontalLayout_25.addWidget(self.txtText13)
        self.horizontalLayout_23.addWidget(self.frmState_8)
        self.verticalLayout_2.addWidget(self.frame_8)
        self.verticalLayout_8.addWidget(self.frame_2)
        # self.stackedWidget.addWidget(self.page_2)
        # self.verticalLayout_8.addWidget(self.stackedWidget)
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.btnPrevious = QtGui.QPushButton(self.frame)
        self.btnPrevious.setObjectName(_fromUtf8("btnPrevious"))
        self.horizontalLayout.addWidget(self.btnPrevious)
        self.btnNext = QtGui.QPushButton(self.frame)
        self.btnNext.setObjectName(_fromUtf8("btnNext"))
        self.horizontalLayout.addWidget(self.btnNext)
        self.btnExit = QtGui.QPushButton(self.frame)
        self.btnExit.setObjectName(_fromUtf8("btnExit"))
        self.horizontalLayout.addWidget(self.btnExit)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem16)
        self.verticalLayout_8.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.addWidget(self.scrollArea)

        # self.frmState.setVisible(False)
        # self.frmAerodrome.setVisible(False)
        # self.frmRunway.setVisible(False)
        # self.frmSlope.setVisible(False)
        # self.ddlPageSizes.setVisible(False)
        #
        # self.txtPrintScale.setText("10")
        # self.txtFontSize.setText("10")
        # self.txtWidth.setText("210")
        # self.txtHeight.setText("290")
        self.txtText1.setText("AIP SWEDEN")
        self.txtText2.setText("18 AUG 2016")
        self.txtText3.setText("AD 2 ESMX 5-1")
        self.txtText4.setText("INSTRUMENT\n APPROACH\n CHART-ICAO")
        self.txtText5.setText("THR ELEV 563.1 ft, AD ELEV 610 ft")
        self.txtText6.setText("KRONOBERG TOWER   118.150")
        self.txtText7.setText("ILS OR LOC RWY 19")
        self.txtText8.setText("TA 5000 ft AMSL")
        self.txtText9.setText("RDH 56.1 ft")
        self.txtText10.setText("Timing not authorized for defining thr MAPt")
        self.txtText11.setText("LFV")
        self.txtText12.setText("CHANGE:EBIXI removed from IAC but is still valid see Area chart, RDH, editorial")
        self.txtText13.setText("AIRAC AMDT 5/2016")

        # self.rbtnmm.setChecked(True)
        self.retranslateUi(Dialog)
        # self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.btnNext.setEnabled(False)

    # def btnPrevious_clicked(self):

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        # self.lblState.setText(_translate("Dialog", "State: ", None))
        # self.lblAerodrome.setText(_translate("Dialog", "Aerodrome: ", None))
        # self.lblRunway.setText(_translate("Dialog", "Runway: ", None))
        # self.lblSlope.setText(_translate("Dialog", "Slope: ", None))
        # self.lblPrintScale.setText(_translate("Dialog", "Print Scale: ", None))
        # self.lblFontSize.setText(_translate("Dialog", "Font Size(Point): ", None))
        # self.gbSizes.setTitle(_translate("Dialog", "Sizes", None))
        # self.rbtnInch.setText(_translate("Dialog", "Inch", None))
        # self.rbtnmm.setText(_translate("Dialog", "MM", None))
        # self.lblWidth.setText(_translate("Dialog", "Width:", None))
        # self.lblHeight.setText(_translate("Dialog", "Height: ", None))
        # self.gbPageOrientation.setTitle(_translate("Dialog", "Page Orientation", None))
        # self.rbtLandscape.setText(_translate("Dialog", "Landscape", None))
        # self.rbtPortrait.setText(_translate("Dialog", "Portrait", None))
        self.lblState_4.setText(_translate("Dialog", "Text1:", None))
        self.lblState_6.setText(_translate("Dialog", "Text2:", None))
        self.lblState_7.setText(_translate("Dialog", "Text3:", None))
        self.lblState_5.setText(_translate("Dialog", "Text4:", None))
        self.lblState_8.setText(_translate("Dialog", "Text5:", None))
        self.lblState_11.setText(_translate("Dialog", "Text6:", None))
        self.lblState_9.setText(_translate("Dialog", "Text7:", None))
        self.lblState_14.setText(_translate("Dialog", "Text8:", None))
        self.lblState_15.setText(_translate("Dialog", "Text9:", None))
        self.lblState_16.setText(_translate("Dialog", "Text10:", None))
        self.lblState_17.setText(_translate("Dialog", "Text11:", None))
        self.lblState_18.setText(_translate("Dialog", "Text12:", None))
        self.lblState_10.setText(_translate("Dialog", "Text13:", None))
        self.btnPrevious.setText(_translate("Dialog", "Previous", None))
        self.btnNext.setText(_translate("Dialog", "Next", None))
        self.btnExit.setText(_translate("Dialog", "Finish", None))

