# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RnavTurningSegmentAnalyser.ui'
#
# Created: Tue Sep 22 11:11:13 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RnavTurningSegmentAnalyser(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(420, 584)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbGeneral = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbGeneral.sizePolicy().hasHeightForWidth())
        self.gbGeneral.setSizePolicy(sizePolicy)
        self.gbGeneral.setObjectName(_fromUtf8("gbGeneral"))
        self.vl_gbGeneral = QtGui.QVBoxLayout(self.gbGeneral)
        self.vl_gbGeneral.setObjectName(_fromUtf8("vl_gbGeneral"))
        self.frameRnavSpecification = QtGui.QFrame(self.gbGeneral)
        self.frameRnavSpecification.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameRnavSpecification.setFrameShadow(QtGui.QFrame.Raised)
        self.frameRnavSpecification.setObjectName(_fromUtf8("frameRnavSpecification"))
        self.hLayoutRnavSpecification = QtGui.QHBoxLayout(self.frameRnavSpecification)
        self.hLayoutRnavSpecification.setSpacing(0)
        self.hLayoutRnavSpecification.setMargin(0)
        self.hLayoutRnavSpecification.setObjectName(_fromUtf8("hLayoutRnavSpecification"))
        self.label_67 = QtGui.QLabel(self.frameRnavSpecification)
        self.label_67.setMinimumSize(QtCore.QSize(180, 0))
        self.label_67.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.hLayoutRnavSpecification.addWidget(self.label_67)
        self.cmbRnavSpecification = QtGui.QComboBox(self.frameRnavSpecification)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRnavSpecification.sizePolicy().hasHeightForWidth())
        self.cmbRnavSpecification.setSizePolicy(sizePolicy)
        self.cmbRnavSpecification.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbRnavSpecification.setFont(font)
        self.cmbRnavSpecification.setObjectName(_fromUtf8("cmbRnavSpecification"))
        self.hLayoutRnavSpecification.addWidget(self.cmbRnavSpecification)
        self.vl_gbGeneral.addWidget(self.frameRnavSpecification)
        self.framePhaseOfFlight = QtGui.QFrame(self.gbGeneral)
        self.framePhaseOfFlight.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePhaseOfFlight.setFrameShadow(QtGui.QFrame.Raised)
        self.framePhaseOfFlight.setObjectName(_fromUtf8("framePhaseOfFlight"))
        self.hLayoutPhaseOfFlight = QtGui.QHBoxLayout(self.framePhaseOfFlight)
        self.hLayoutPhaseOfFlight.setSpacing(0)
        self.hLayoutPhaseOfFlight.setMargin(0)
        self.hLayoutPhaseOfFlight.setObjectName(_fromUtf8("hLayoutPhaseOfFlight"))
        self.label_69 = QtGui.QLabel(self.framePhaseOfFlight)
        self.label_69.setMinimumSize(QtCore.QSize(180, 0))
        self.label_69.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.hLayoutPhaseOfFlight.addWidget(self.label_69)
        self.cmbPhaseOfFlight = QtGui.QComboBox(self.framePhaseOfFlight)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPhaseOfFlight.sizePolicy().hasHeightForWidth())
        self.cmbPhaseOfFlight.setSizePolicy(sizePolicy)
        self.cmbPhaseOfFlight.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbPhaseOfFlight.setFont(font)
        self.cmbPhaseOfFlight.setObjectName(_fromUtf8("cmbPhaseOfFlight"))
        self.hLayoutPhaseOfFlight.addWidget(self.cmbPhaseOfFlight)
        self.vl_gbGeneral.addWidget(self.framePhaseOfFlight)
        self.gbWaypoint = QtGui.QGroupBox(self.gbGeneral)
        self.gbWaypoint.setObjectName(_fromUtf8("gbWaypoint"))
        self.vLayoutGbWaypoint = QtGui.QVBoxLayout(self.gbWaypoint)
        self.vLayoutGbWaypoint.setObjectName(_fromUtf8("vLayoutGbWaypoint"))
        self.frameType = QtGui.QFrame(self.gbWaypoint)
        self.frameType.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameType.setFrameShadow(QtGui.QFrame.Raised)
        self.frameType.setObjectName(_fromUtf8("frameType"))
        self.hLayoutType = QtGui.QHBoxLayout(self.frameType)
        self.hLayoutType.setSpacing(0)
        self.hLayoutType.setMargin(0)
        self.hLayoutType.setObjectName(_fromUtf8("hLayoutType"))
        self.label_70 = QtGui.QLabel(self.frameType)
        self.label_70.setMinimumSize(QtCore.QSize(180, 0))
        self.label_70.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.hLayoutType.addWidget(self.label_70)
        self.cmbType = QtGui.QComboBox(self.frameType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbType.sizePolicy().hasHeightForWidth())
        self.cmbType.setSizePolicy(sizePolicy)
        self.cmbType.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbType.setFont(font)
        self.cmbType.setObjectName(_fromUtf8("cmbType"))
        self.hLayoutType.addWidget(self.cmbType)
        self.vLayoutGbWaypoint.addWidget(self.frameType)
        self.vl_gbGeneral.addWidget(self.gbWaypoint)
        self.chbCatH = QtGui.QCheckBox(self.gbGeneral)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbCatH.setFont(font)
        self.chbCatH.setObjectName(_fromUtf8("chbCatH"))
        self.vl_gbGeneral.addWidget(self.chbCatH)
        self.chbCircularArcs = QtGui.QCheckBox(self.gbGeneral)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbCircularArcs.setFont(font)
        self.chbCircularArcs.setObjectName(_fromUtf8("chbCircularArcs"))
        self.vl_gbGeneral.addWidget(self.chbCircularArcs)
        self.gbParameters = QtGui.QGroupBox(self.gbGeneral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbParameters.sizePolicy().hasHeightForWidth())
        self.gbParameters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.gbParameters.setFont(font)
        self.gbParameters.setObjectName(_fromUtf8("gbParameters"))
        self.vl_gbParameters = QtGui.QVBoxLayout(self.gbParameters)
        self.vl_gbParameters.setObjectName(_fromUtf8("vl_gbParameters"))
        self.frameSelectionMode = QtGui.QFrame(self.gbParameters)
        self.frameSelectionMode.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameSelectionMode.setFrameShadow(QtGui.QFrame.Raised)
        self.frameSelectionMode.setObjectName(_fromUtf8("frameSelectionMode"))
        self.hLayoutSelectionMode = QtGui.QHBoxLayout(self.frameSelectionMode)
        self.hLayoutSelectionMode.setSpacing(0)
        self.hLayoutSelectionMode.setMargin(0)
        self.hLayoutSelectionMode.setObjectName(_fromUtf8("hLayoutSelectionMode"))
        self.label_66 = QtGui.QLabel(self.frameSelectionMode)
        self.label_66.setMinimumSize(QtCore.QSize(180, 0))
        self.label_66.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.hLayoutSelectionMode.addWidget(self.label_66)
        self.cmbSelectionMode = QtGui.QComboBox(self.frameSelectionMode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSelectionMode.sizePolicy().hasHeightForWidth())
        self.cmbSelectionMode.setSizePolicy(sizePolicy)
        self.cmbSelectionMode.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbSelectionMode.setFont(font)
        self.cmbSelectionMode.setObjectName(_fromUtf8("cmbSelectionMode"))
        self.hLayoutSelectionMode.addWidget(self.cmbSelectionMode)
        self.vl_gbParameters.addWidget(self.frameSelectionMode)
        self.frame_Track = QtGui.QFrame(self.gbParameters)
        self.frame_Track.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_Track.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Track.setObjectName(_fromUtf8("frame_Track"))
        self.hLayoutTrack = QtGui.QHBoxLayout(self.frame_Track)
        self.hLayoutTrack.setSpacing(0)
        self.hLayoutTrack.setMargin(0)
        self.hLayoutTrack.setObjectName(_fromUtf8("hLayoutTrack"))
        self.label_75 = QtGui.QLabel(self.frame_Track)
        self.label_75.setMinimumSize(QtCore.QSize(180, 0))
        self.label_75.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.hLayoutTrack.addWidget(self.label_75)
        self.frame_APV_10 = QtGui.QFrame(self.frame_Track)
        self.frame_APV_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_10.setObjectName(_fromUtf8("frame_APV_10"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.frame_APV_10)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.txtInbound = QtGui.QLineEdit(self.frame_APV_10)
        self.txtInbound.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtInbound.setFont(font)
        self.txtInbound.setObjectName(_fromUtf8("txtInbound"))
        self.horizontalLayout_14.addWidget(self.txtInbound)
        self.btnCaptureInboundTrack = QtGui.QToolButton(self.frame_APV_10)
        self.btnCaptureInboundTrack.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCaptureInboundTrack.setIcon(icon)
        self.btnCaptureInboundTrack.setObjectName(_fromUtf8("btnCaptureInboundTrack"))
        self.horizontalLayout_14.addWidget(self.btnCaptureInboundTrack)
        self.hLayoutTrack.addWidget(self.frame_APV_10)
        self.vl_gbParameters.addWidget(self.frame_Track)
        self.frameDistance = QtGui.QFrame(self.gbParameters)
        self.frameDistance.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameDistance.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDistance.setObjectName(_fromUtf8("frameDistance"))
        self.hLayoutDistance = QtGui.QHBoxLayout(self.frameDistance)
        self.hLayoutDistance.setSpacing(0)
        self.hLayoutDistance.setMargin(0)
        self.hLayoutDistance.setObjectName(_fromUtf8("hLayoutDistance"))
        self.label_76 = QtGui.QLabel(self.frameDistance)
        self.label_76.setMinimumSize(QtCore.QSize(180, 0))
        self.label_76.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_76.setFont(font)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.hLayoutDistance.addWidget(self.label_76)
        self.frame_APV_11 = QtGui.QFrame(self.frameDistance)
        self.frame_APV_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_11.setObjectName(_fromUtf8("frame_APV_11"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.frame_APV_11)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.txtOutbound = QtGui.QLineEdit(self.frame_APV_11)
        self.txtOutbound.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtOutbound.setFont(font)
        self.txtOutbound.setObjectName(_fromUtf8("txtOutbound"))
        self.horizontalLayout_15.addWidget(self.txtOutbound)
        self.btnCaptureOutboundTrack = QtGui.QToolButton(self.frame_APV_11)
        self.btnCaptureOutboundTrack.setText(_fromUtf8(""))
        self.btnCaptureOutboundTrack.setIcon(icon)
        self.btnCaptureOutboundTrack.setObjectName(_fromUtf8("btnCaptureOutboundTrack"))
        self.horizontalLayout_15.addWidget(self.btnCaptureOutboundTrack)
        self.hLayoutDistance.addWidget(self.frame_APV_11)
        self.vl_gbParameters.addWidget(self.frameDistance)
        self.framePDG = QtGui.QFrame(self.gbParameters)
        self.framePDG.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePDG.setFrameShadow(QtGui.QFrame.Raised)
        self.framePDG.setObjectName(_fromUtf8("framePDG"))
        self.hLayoutPDG = QtGui.QHBoxLayout(self.framePDG)
        self.hLayoutPDG.setSpacing(0)
        self.hLayoutPDG.setMargin(0)
        self.hLayoutPDG.setObjectName(_fromUtf8("hLayoutPDG"))
        self.label_71 = QtGui.QLabel(self.framePDG)
        self.label_71.setMinimumSize(QtCore.QSize(180, 0))
        self.label_71.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_71.setFont(font)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.hLayoutPDG.addWidget(self.label_71)
        self.txtIas = QtGui.QLineEdit(self.framePDG)
        self.txtIas.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtIas.setFont(font)
        self.txtIas.setObjectName(_fromUtf8("txtIas"))
        self.hLayoutPDG.addWidget(self.txtIas)
        self.vl_gbParameters.addWidget(self.framePDG)
        self.frameAltitude = QtGui.QFrame(self.gbParameters)
        self.frameAltitude.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAltitude.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAltitude.setObjectName(_fromUtf8("frameAltitude"))
        self.hLayoutAltitude = QtGui.QHBoxLayout(self.frameAltitude)
        self.hLayoutAltitude.setSpacing(0)
        self.hLayoutAltitude.setMargin(0)
        self.hLayoutAltitude.setObjectName(_fromUtf8("hLayoutAltitude"))
        self.label_77 = QtGui.QLabel(self.frameAltitude)
        self.label_77.setMinimumSize(QtCore.QSize(180, 0))
        self.label_77.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.hLayoutAltitude.addWidget(self.label_77)
        self.txtAltitude = QtGui.QLineEdit(self.frameAltitude)
        self.txtAltitude.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitude.setFont(font)
        self.txtAltitude.setObjectName(_fromUtf8("txtAltitude"))
        self.hLayoutAltitude.addWidget(self.txtAltitude)
        self.vl_gbParameters.addWidget(self.frameAltitude)
        self.frameMoc = QtGui.QFrame(self.gbParameters)
        self.frameMoc.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMoc.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMoc.setObjectName(_fromUtf8("frameMoc"))
        self.hLayoutMoc = QtGui.QHBoxLayout(self.frameMoc)
        self.hLayoutMoc.setSpacing(0)
        self.hLayoutMoc.setMargin(0)
        self.hLayoutMoc.setObjectName(_fromUtf8("hLayoutMoc"))
        self.label_78 = QtGui.QLabel(self.frameMoc)
        self.label_78.setMinimumSize(QtCore.QSize(180, 0))
        self.label_78.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_78.setFont(font)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.hLayoutMoc.addWidget(self.label_78)
        self.txtIsa = QtGui.QLineEdit(self.frameMoc)
        self.txtIsa.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtIsa.setFont(font)
        self.txtIsa.setObjectName(_fromUtf8("txtIsa"))
        self.hLayoutMoc.addWidget(self.txtIsa)
        self.vl_gbParameters.addWidget(self.frameMoc)
        self.frameMoc_2 = QtGui.QFrame(self.gbParameters)
        self.frameMoc_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMoc_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMoc_2.setObjectName(_fromUtf8("frameMoc_2"))
        self.hLayoutMoc_2 = QtGui.QHBoxLayout(self.frameMoc_2)
        self.hLayoutMoc_2.setSpacing(0)
        self.hLayoutMoc_2.setMargin(0)
        self.hLayoutMoc_2.setObjectName(_fromUtf8("hLayoutMoc_2"))
        self.label_79 = QtGui.QLabel(self.frameMoc_2)
        self.label_79.setMinimumSize(QtCore.QSize(180, 0))
        self.label_79.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_79.setFont(font)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.hLayoutMoc_2.addWidget(self.label_79)
        self.txtBankAngle = QtGui.QLineEdit(self.frameMoc_2)
        self.txtBankAngle.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtBankAngle.setFont(font)
        self.txtBankAngle.setObjectName(_fromUtf8("txtBankAngle"))
        self.hLayoutMoc_2.addWidget(self.txtBankAngle)
        self.vl_gbParameters.addWidget(self.frameMoc_2)
        self.frameMoc_3 = QtGui.QFrame(self.gbParameters)
        self.frameMoc_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMoc_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMoc_3.setObjectName(_fromUtf8("frameMoc_3"))
        self.hLayoutMoc_3 = QtGui.QHBoxLayout(self.frameMoc_3)
        self.hLayoutMoc_3.setSpacing(0)
        self.hLayoutMoc_3.setMargin(0)
        self.hLayoutMoc_3.setObjectName(_fromUtf8("hLayoutMoc_3"))
        self.label_80 = QtGui.QLabel(self.frameMoc_3)
        self.label_80.setMinimumSize(QtCore.QSize(180, 0))
        self.label_80.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_80.setFont(font)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.hLayoutMoc_3.addWidget(self.label_80)
        self.txtBankEstTime = QtGui.QLineEdit(self.frameMoc_3)
        self.txtBankEstTime.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtBankEstTime.setFont(font)
        self.txtBankEstTime.setObjectName(_fromUtf8("txtBankEstTime"))
        self.hLayoutMoc_3.addWidget(self.txtBankEstTime)
        self.vl_gbParameters.addWidget(self.frameMoc_3)
        self.frameMoc_4 = QtGui.QFrame(self.gbParameters)
        self.frameMoc_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMoc_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMoc_4.setObjectName(_fromUtf8("frameMoc_4"))
        self.hLayoutMoc_4 = QtGui.QHBoxLayout(self.frameMoc_4)
        self.hLayoutMoc_4.setSpacing(0)
        self.hLayoutMoc_4.setMargin(0)
        self.hLayoutMoc_4.setObjectName(_fromUtf8("hLayoutMoc_4"))
        self.label_81 = QtGui.QLabel(self.frameMoc_4)
        self.label_81.setMinimumSize(QtCore.QSize(180, 0))
        self.label_81.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_81.setFont(font)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.hLayoutMoc_4.addWidget(self.label_81)
        self.txtPilotTime = QtGui.QLineEdit(self.frameMoc_4)
        self.txtPilotTime.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPilotTime.setFont(font)
        self.txtPilotTime.setObjectName(_fromUtf8("txtPilotTime"))
        self.hLayoutMoc_4.addWidget(self.txtPilotTime)
        self.vl_gbParameters.addWidget(self.frameMoc_4)
        self.framePrimaryMoc = QtGui.QFrame(self.gbParameters)
        self.framePrimaryMoc.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePrimaryMoc.setFrameShadow(QtGui.QFrame.Raised)
        self.framePrimaryMoc.setObjectName(_fromUtf8("framePrimaryMoc"))
        self.hLayoutPrimaryMoc = QtGui.QHBoxLayout(self.framePrimaryMoc)
        self.hLayoutPrimaryMoc.setSpacing(0)
        self.hLayoutPrimaryMoc.setMargin(0)
        self.hLayoutPrimaryMoc.setObjectName(_fromUtf8("hLayoutPrimaryMoc"))
        self.label_68 = QtGui.QLabel(self.framePrimaryMoc)
        self.label_68.setMinimumSize(QtCore.QSize(180, 0))
        self.label_68.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.hLayoutPrimaryMoc.addWidget(self.label_68)
        self.txtPrimaryMoc = QtGui.QLineEdit(self.framePrimaryMoc)
        self.txtPrimaryMoc.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPrimaryMoc.setFont(font)
        self.txtPrimaryMoc.setObjectName(_fromUtf8("txtPrimaryMoc"))
        self.hLayoutPrimaryMoc.addWidget(self.txtPrimaryMoc)
        self.vl_gbParameters.addWidget(self.framePrimaryMoc)
        self.frameConstruct = QtGui.QFrame(self.gbParameters)
        self.frameConstruct.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameConstruct.setFrameShadow(QtGui.QFrame.Raised)
        self.frameConstruct.setObjectName(_fromUtf8("frameConstruct"))
        self.hLayoutConstruct = QtGui.QHBoxLayout(self.frameConstruct)
        self.hLayoutConstruct.setSpacing(0)
        self.hLayoutConstruct.setMargin(0)
        self.hLayoutConstruct.setObjectName(_fromUtf8("hLayoutConstruct"))
        self.label_83 = QtGui.QLabel(self.frameConstruct)
        self.label_83.setMinimumSize(QtCore.QSize(180, 0))
        self.label_83.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_83.setFont(font)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.hLayoutConstruct.addWidget(self.label_83)
        self.cmbConstructionType = QtGui.QComboBox(self.frameConstruct)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConstructionType.sizePolicy().hasHeightForWidth())
        self.cmbConstructionType.setSizePolicy(sizePolicy)
        self.cmbConstructionType.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbConstructionType.setFont(font)
        self.cmbConstructionType.setObjectName(_fromUtf8("cmbConstructionType"))
        self.hLayoutConstruct.addWidget(self.cmbConstructionType)
        self.vl_gbParameters.addWidget(self.frameConstruct)
        self.frameMOCmultipiler = QtGui.QFrame(self.gbParameters)
        self.frameMOCmultipiler.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMOCmultipiler.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMOCmultipiler.setObjectName(_fromUtf8("frameMOCmultipiler"))
        self.hLayoutMOCmultipiler = QtGui.QHBoxLayout(self.frameMOCmultipiler)
        self.hLayoutMOCmultipiler.setSpacing(0)
        self.hLayoutMOCmultipiler.setMargin(0)
        self.hLayoutMOCmultipiler.setObjectName(_fromUtf8("hLayoutMOCmultipiler"))
        self.label_84 = QtGui.QLabel(self.frameMOCmultipiler)
        self.label_84.setMinimumSize(QtCore.QSize(180, 0))
        self.label_84.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_84.setFont(font)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.hLayoutMOCmultipiler.addWidget(self.label_84)
        self.mocSpinBox = QtGui.QSpinBox(self.frameMOCmultipiler)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mocSpinBox.sizePolicy().hasHeightForWidth())
        self.mocSpinBox.setSizePolicy(sizePolicy)
        self.mocSpinBox.setMinimumSize(QtCore.QSize(72, 0))
        self.mocSpinBox.setMinimum(1)
        self.mocSpinBox.setObjectName(_fromUtf8("mocSpinBox"))
        self.hLayoutMOCmultipiler.addWidget(self.mocSpinBox)
        self.vl_gbParameters.addWidget(self.frameMOCmultipiler)
        self.chbDrawTolerance = QtGui.QCheckBox(self.gbParameters)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbDrawTolerance.setFont(font)
        self.chbDrawTolerance.setObjectName(_fromUtf8("chbDrawTolerance"))
        self.vl_gbParameters.addWidget(self.chbDrawTolerance)
        self.vl_gbGeneral.addWidget(self.gbParameters)
        self.verticalLayout.addWidget(self.gbGeneral)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.gbGeneral.setTitle(_translate("Form", "General", None))
        self.label_67.setText(_translate("Form", "RNAV Specification:", None))
        self.label_69.setText(_translate("Form", "Phase Of Flight:", None))
        self.gbWaypoint.setTitle(_translate("Form", "Waypoint", None))
        self.label_70.setText(_translate("Form", "Type:", None))
        self.chbCatH.setText(_translate("Form", "Cat. H", None))
        self.chbCircularArcs.setText(_translate("Form", "Use Circular Arcs Method for Turns <= 30", None))
        self.gbParameters.setTitle(_translate("Form", "Parameters", None))
        self.label_66.setText(_translate("Form", "Selection Mode:", None))
        self.label_75.setText(_translate("Form", "In-bound Track ():", None))
        self.txtInbound.setText(_translate("Form", "0", None))
        self.label_76.setText(_translate("Form", "Out-bound Track():", None))
        self.txtOutbound.setText(_translate("Form", "0", None))
        self.label_71.setText(_translate("Form", "IAS(kts):", None))
        self.txtIas.setText(_translate("Form", "315", None))
        self.label_77.setText(_translate("Form", "Altitude(ft):", None))
        self.txtAltitude.setText(_translate("Form", "9000", None))
        self.label_78.setText(_translate("Form", "ISA(C):", None))
        self.txtIsa.setText(_translate("Form", "15", None))
        self.label_79.setText(_translate("Form", "Bank Angle():", None))
        self.txtBankAngle.setText(_translate("Form", "15", None))
        self.label_80.setText(_translate("Form", "Bank Estimate Time:", None))
        self.txtBankEstTime.setText(_translate("Form", "1", None))
        self.label_81.setText(_translate("Form", "Pilot Time:", None))
        self.txtPilotTime.setText(_translate("Form", "1", None))
        self.label_68.setText(_translate("Form", "Primary Moc(m):", None))
        self.txtPrimaryMoc.setText(_translate("Form", "300", None))
        self.label_83.setText(_translate("Form", "Construction Type:", None))
        self.label_84.setText(_translate("Form", "MOCmultiplier:", None))
        self.chbDrawTolerance.setText(_translate("Form", "Draw Waypoint Tolerance", None))

