# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_DataImport.ui'
#
# Created: Sat Aug 22 17:58:34 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from FlightPlanner.Panels.Frame import Frame

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DataImport(object):
    def setupUi(self, ui_DatabaseImport):
        ui_DatabaseImport.setObjectName(_fromUtf8("ui_DatabaseImport"))
        ui_DatabaseImport.resize(500, 527)
        self.verticalLayout = QtGui.QVBoxLayout(ui_DatabaseImport)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbDatabaseFile = QtGui.QGroupBox(ui_DatabaseImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbDatabaseFile.sizePolicy().hasHeightForWidth())
        self.gbDatabaseFile.setSizePolicy(sizePolicy)
        self.gbDatabaseFile.setObjectName(_fromUtf8("gbDatabaseFile"))
        self.verticalLayout_gbSetting = QtGui.QVBoxLayout(self.gbDatabaseFile)
        self.verticalLayout_gbSetting.setObjectName(_fromUtf8("verticalLayout_gbSetting"))
        self.frame_ThrFaf_2 = QtGui.QFrame(self.gbDatabaseFile)
        self.frame_ThrFaf_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_ThrFaf_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_ThrFaf_2.setObjectName(_fromUtf8("frame_ThrFaf_2"))
        self.horizontalLayout_67 = QtGui.QHBoxLayout(self.frame_ThrFaf_2)
        self.horizontalLayout_67.setSpacing(0)
        self.horizontalLayout_67.setMargin(0)
        self.horizontalLayout_67.setObjectName(_fromUtf8("horizontalLayout_67"))
        self.frame_File = QtGui.QFrame(self.frame_ThrFaf_2)
        self.frame_File.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_File.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_File.setObjectName(_fromUtf8("frame_File"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.frame_File)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.txtFile = QtGui.QLineEdit(self.frame_File)
        self.txtFile.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtFile.setFont(font)
        self.txtFile.setText(_fromUtf8(""))
        self.txtFile.setObjectName(_fromUtf8("txtFile"))
        self.horizontalLayout_19.addWidget(self.txtFile)
        self.btnFile = QtGui.QToolButton(self.frame_File)
        self.btnFile.setObjectName(_fromUtf8("btnFile"))
        self.horizontalLayout_19.addWidget(self.btnFile)
        self.horizontalLayout_67.addWidget(self.frame_File)
        self.verticalLayout_gbSetting.addWidget(self.frame_ThrFaf_2)
        self.verticalLayout.addWidget(self.gbDatabaseFile)
        self.gbContent = QtGui.QGroupBox(ui_DatabaseImport)
        self.gbContent.setObjectName(_fromUtf8("gbContent"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gbContent)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame_ThrFaf_3 = QtGui.QFrame(self.gbContent)
        self.frame_ThrFaf_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_ThrFaf_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_ThrFaf_3.setObjectName(_fromUtf8("frame_ThrFaf_3"))
        self.horizontalLayout_68 = QtGui.QHBoxLayout(self.frame_ThrFaf_3)
        self.horizontalLayout_68.setSpacing(0)
        self.horizontalLayout_68.setMargin(0)
        self.horizontalLayout_68.setObjectName(_fromUtf8("horizontalLayout_68"))
        self.frame_Content = QtGui.QFrame(self.frame_ThrFaf_3)
        self.frame_Content.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Content.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Content.setObjectName(_fromUtf8("frame_Content"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.frame_Content)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setMargin(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.frame = QtGui.QFrame(self.frame_Content)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(160, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.labelSymbol_2 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSymbol_2.sizePolicy().hasHeightForWidth())
        self.labelSymbol_2.setSizePolicy(sizePolicy)
        self.labelSymbol_2.setTextFormat(QtCore.Qt.AutoText)
        self.labelSymbol_2.setObjectName(_fromUtf8("labelSymbol_2"))
        self.verticalLayout_3.addWidget(self.labelSymbol_2)
        self.tree = QtGui.QTreeView(self.frame)
        self.tree.setMaximumSize(QtCore.QSize(161, 16777215))
        self.tree.setObjectName(_fromUtf8("tree"))
        self.verticalLayout_3.addWidget(self.tree)
        self.horizontalLayout_20.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.frame_Content)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame_AltitudeIA1 = QtGui.QFrame(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_AltitudeIA1.sizePolicy().hasHeightForWidth())
        self.frame_AltitudeIA1.setSizePolicy(sizePolicy)
        self.frame_AltitudeIA1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_AltitudeIA1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_AltitudeIA1.setObjectName(_fromUtf8("frame_AltitudeIA1"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.frame_AltitudeIA1)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setMargin(0)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_17 = QtGui.QLabel(self.frame_AltitudeIA1)
        self.label_17.setMinimumSize(QtCore.QSize(50, 0))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_27.addWidget(self.label_17)
        self.txtName = QtGui.QLineEdit(self.frame_AltitudeIA1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtName.sizePolicy().hasHeightForWidth())
        self.txtName.setSizePolicy(sizePolicy)
        self.txtName.setMinimumSize(QtCore.QSize(105, 0))
        self.txtName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.txtName.setFont(font)
        self.txtName.setText(_fromUtf8(""))
        self.txtName.setObjectName(_fromUtf8("txtName"))
        self.horizontalLayout_27.addWidget(self.txtName)
        self.horizontalLayout_2.addWidget(self.frame_AltitudeIA1)
        self.frame_4 = QtGui.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.frame_AltitudeIA1_2 = QtGui.QFrame(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_AltitudeIA1_2.sizePolicy().hasHeightForWidth())
        self.frame_AltitudeIA1_2.setSizePolicy(sizePolicy)
        self.frame_AltitudeIA1_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_AltitudeIA1_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_AltitudeIA1_2.setObjectName(_fromUtf8("frame_AltitudeIA1_2"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.frame_AltitudeIA1_2)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setMargin(0)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_18 = QtGui.QLabel(self.frame_AltitudeIA1_2)
        self.label_18.setMinimumSize(QtCore.QSize(50, 0))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_28.addWidget(self.label_18)
        self.cmbType = QtGui.QComboBox(self.frame_AltitudeIA1_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbType.sizePolicy().hasHeightForWidth())
        self.cmbType.setSizePolicy(sizePolicy)
        self.cmbType.setObjectName(_fromUtf8("cmbType"))
        self.horizontalLayout_28.addWidget(self.cmbType)
        self.horizontalLayout_3.addWidget(self.frame_AltitudeIA1_2)
        
        self.frameAlFieldName = QtGui.QFrame(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameAlFieldName.sizePolicy().hasHeightForWidth())
        self.frameAlFieldName.setSizePolicy(sizePolicy)
        self.frameAlFieldName.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameAlFieldName.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAlFieldName.setObjectName(_fromUtf8("frameAlFieldName"))
        self.horizontalLayoutAlFieldName = QtGui.QHBoxLayout(self.frameAlFieldName)
        self.horizontalLayoutAlFieldName.setSpacing(0)
        self.horizontalLayoutAlFieldName.setMargin(0)
        self.horizontalLayoutAlFieldName.setObjectName(_fromUtf8("horizontalLayoutAlFieldName"))
        self.labelAlFieldName = QtGui.QLabel(self.frameAlFieldName)
        self.labelAlFieldName.setMinimumSize(QtCore.QSize(80, 0))
        self.labelAlFieldName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.labelAlFieldName.setFont(font)
        self.labelAlFieldName.setObjectName(_fromUtf8("labelAlFieldName"))
        self.labelAlFieldName.setText(_fromUtf8("    Altitude Field:"))
        self.horizontalLayoutAlFieldName.addWidget(self.labelAlFieldName)
        self.cmbAlFieldName = QtGui.QComboBox(self.frameAlFieldName)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAlFieldName.sizePolicy().hasHeightForWidth())
        self.cmbAlFieldName.setSizePolicy(sizePolicy)
        self.cmbAlFieldName.setObjectName(_fromUtf8("cmbAlFieldName"))
        self.horizontalLayoutAlFieldName.addWidget(self.cmbAlFieldName)
        self.horizontalLayout_3.addWidget(self.frameAlFieldName)
        
        
        self.frameAlUnit = QtGui.QFrame(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameAlUnit.sizePolicy().hasHeightForWidth())
        self.frameAlUnit.setSizePolicy(sizePolicy)
        self.frameAlUnit.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameAlUnit.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAlUnit.setObjectName(_fromUtf8("frameAlUnit"))
        self.horizontalLayoutAlUnit = QtGui.QHBoxLayout(self.frameAlUnit)
        self.horizontalLayoutAlUnit.setSpacing(0)
        self.horizontalLayoutAlUnit.setMargin(0)
        self.horizontalLayoutAlUnit.setObjectName(_fromUtf8("horizontalLayoutAlUnit"))
        self.labelAlUnit = QtGui.QLabel(self.frameAlUnit)
        self.labelAlUnit.setMinimumSize(QtCore.QSize(80, 0))
        self.labelAlUnit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.labelAlUnit.setFont(font)
        self.labelAlUnit.setObjectName(_fromUtf8("labelAlUnit"))
        self.labelAlUnit.setText(_fromUtf8("    Altitude Unit:"))
        self.horizontalLayoutAlUnit.addWidget(self.labelAlUnit)
        self.cmbAlUnit = QtGui.QComboBox(self.frameAlUnit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAlUnit.sizePolicy().hasHeightForWidth())
        self.cmbAlUnit.setSizePolicy(sizePolicy)
        self.cmbAlUnit.setObjectName(_fromUtf8("cmbAlUnit"))
        self.horizontalLayoutAlUnit.addWidget(self.cmbAlUnit)
        self.horizontalLayout_3.addWidget(self.frameAlUnit)

        
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_3)

        self.frmTableView = QtGui.QFrame(self.frame_2)
        self.frmTableView.setObjectName("frmTableView")
        self.vLayoutTabeView = QtGui.QHBoxLayout(self.frmTableView)
        self.vLayoutTabeView.setObjectName("vLayoutTabeView")
        self.verticalLayout_2.addWidget(self.frmTableView)

        self.tableView = QtGui.QTableView(self.frmTableView)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.vLayoutTabeView.addWidget(self.tableView)
        
        
        self.pnlProcButtons = Frame(self.frmTableView)
        self.vLayoutTabeView.addWidget(self.pnlProcButtons)


        self.btnProcAdd = QtGui.QPushButton(self.pnlProcButtons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resource/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnProcAdd.setIcon(icon)
        self.btnProcAdd.setToolTip("Add")
        self.pnlProcButtons.Add = self.btnProcAdd

        self.btnProcEdit = QtGui.QPushButton(self.pnlProcButtons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resource/mIconEditableEdits.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnProcEdit.setIcon(icon)
        self.btnProcEdit.setToolTip("Modify")
        self.pnlProcButtons.Add = self.btnProcEdit

        self.btnProcRemove = QtGui.QPushButton(self.pnlProcButtons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resource/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnProcRemove.setIcon(icon)
        self.btnProcRemove.setToolTip("Remove")
        self.pnlProcButtons.Add = self.btnProcRemove


        self.groupBox = QtGui.QGroupBox(self.frame_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tableViewDetail = QtGui.QTableView(self.groupBox)
        self.tableViewDetail.setObjectName(_fromUtf8("tableViewDetail"))
        self.verticalLayout_4.addWidget(self.tableViewDetail)

        self.pnlDetailButtons = Frame(self.frmTableView)
        self.verticalLayout_4.addWidget(self.pnlDetailButtons)


        self.btnDetailAdd = QtGui.QPushButton(self.pnlDetailButtons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resource/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDetailAdd.setIcon(icon)
        self.btnDetailAdd.setToolTip("Add")
        self.pnlDetailButtons.Add = self.btnDetailAdd

        self.btnDetailEdit = QtGui.QPushButton(self.pnlDetailButtons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resource/mIconEditableEdits.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDetailEdit.setIcon(icon)
        self.btnDetailEdit.setToolTip("Modify")
        self.pnlDetailButtons.Add = self.btnDetailEdit

        self.btnDetailRemove = QtGui.QPushButton(self.pnlDetailButtons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resource/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDetailRemove.setIcon(icon)
        self.btnDetailRemove.setToolTip("Remove")
        self.pnlDetailButtons.Add = self.btnDetailRemove
        
        
        
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_20.addWidget(self.frame_2)
        self.horizontalLayout_68.addWidget(self.frame_Content)
        self.horizontalLayout.addWidget(self.frame_ThrFaf_3)
        self.verticalLayout.addWidget(self.gbContent)

        self.retranslateUi(ui_DatabaseImport)
        QtCore.QMetaObject.connectSlotsByName(ui_DatabaseImport)

    def retranslateUi(self, ui_DatabaseImport):
        ui_DatabaseImport.setWindowTitle(_translate("ui_DatabaseImport", "Database Import", None))
        self.gbDatabaseFile.setTitle(_translate("ui_DatabaseImport", "Database File", None))
        self.btnFile.setText(_translate("ui_DatabaseImport", "...", None))
        self.gbContent.setTitle(_translate("ui_DatabaseImport", "Content", None))
        self.labelSymbol_2.setText(_translate("ui_DatabaseImport", "Symbols", None))
        self.label_17.setText(_translate("ui_DatabaseImport", "Filter:", None))
        self.label_18.setText(_translate("ui_DatabaseImport", "Type:", None))
        self.groupBox.setTitle(_translate("ui_DatabaseImport", "Detail", None))

