# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DepartureStandard.ui'
#
# Created: Tue Oct 27 16:38:07 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from FlightPlanner.Panels.TrackRadialBoxPanel import TrackRadialBoxPanel

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DepartureStandard(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(417, 350)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbRunway = QtGui.QGroupBox(Form)
        self.gbRunway.setObjectName(_fromUtf8("gbRunway"))
        self.vl_gbRunway = QtGui.QVBoxLayout(self.gbRunway)
        self.vl_gbRunway.setObjectName(_fromUtf8("vl_gbRunway"))

        self.txtRwyDir = TrackRadialBoxPanel(self.gbRunway)
        self.txtRwyDir.Caption = "Direction"
        self.txtRwyDir.LabelWidth = 130
        self.vl_gbRunway.addWidget(self.txtRwyDir)
        # self.frameRwyDir = QtGui.QFrame(self.gbRunway)
        # self.frameRwyDir.setFrameShape(QtGui.QFrame.NoFrame)
        # self.frameRwyDir.setFrameShadow(QtGui.QFrame.Raised)
        # self.frameRwyDir.setObjectName(_fromUtf8("frameRwyDir"))
        # self.hLayoutRwyDir = QtGui.QHBoxLayout(self.frameRwyDir)
        # self.hLayoutRwyDir.setSpacing(0)
        # self.hLayoutRwyDir.setMargin(0)
        # self.hLayoutRwyDir.setObjectName(_fromUtf8("hLayoutRwyDir"))
        # self.label_74 = QtGui.QLabel(self.frameRwyDir)
        # self.label_74.setMinimumSize(QtCore.QSize(180, 0))
        # self.label_74.setMaximumSize(QtCore.QSize(180, 16777215))
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.label_74.setFont(font)
        # self.label_74.setObjectName(_fromUtf8("label_74"))
        # self.hLayoutRwyDir.addWidget(self.label_74)
        # self.frame_APV_9 = QtGui.QFrame(self.frameRwyDir)
        # self.frame_APV_9.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.frame_APV_9.setFrameShadow(QtGui.QFrame.Raised)
        # self.frame_APV_9.setObjectName(_fromUtf8("frame_APV_9"))
        # self.horizontalLayout_13 = QtGui.QHBoxLayout(self.frame_APV_9)
        # self.horizontalLayout_13.setSpacing(0)
        # self.horizontalLayout_13.setMargin(0)
        # self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        # self.txtRwyDir = QtGui.QLineEdit(self.frame_APV_9)
        # self.txtRwyDir.setEnabled(True)
        # font = QtGui.QFont()
        # font.setBold(False)
        # font.setWeight(50)
        # self.txtRwyDir.setFont(font)
        # self.txtRwyDir.setObjectName(_fromUtf8("txtRwyDir"))
        # self.horizontalLayout_13.addWidget(self.txtRwyDir)
        # self.btnCaptureRwyDir = QtGui.QToolButton(self.frame_APV_9)
        # self.btnCaptureRwyDir.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/coordinate_capture.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.btnCaptureRwyDir.setIcon(icon)
        # self.btnCaptureRwyDir.setObjectName(_fromUtf8("btnCaptureRwyDir"))
        # self.horizontalLayout_13.addWidget(self.btnCaptureRwyDir)
        # self.hLayoutRwyDir.addWidget(self.frame_APV_9)
        # self.vl_gbRunway.addWidget(self.frameRwyDir)
        self.verticalLayout.addWidget(self.gbRunway)
        self.gbParameters = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.gbParameters.setFont(font)
        self.gbParameters.setObjectName(_fromUtf8("gbParameters"))
        self.vl_gbParameters = QtGui.QVBoxLayout(self.gbParameters)
        self.vl_gbParameters.setObjectName(_fromUtf8("vl_gbParameters"))
        self.frameType = QtGui.QFrame(self.gbParameters)
        self.frameType.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameType.setFrameShadow(QtGui.QFrame.Raised)
        self.frameType.setObjectName(_fromUtf8("frameType"))
        self.hLayoutType = QtGui.QHBoxLayout(self.frameType)
        self.hLayoutType.setSpacing(0)
        self.hLayoutType.setMargin(0)
        self.hLayoutType.setObjectName(_fromUtf8("hLayoutType"))
        self.label_66 = QtGui.QLabel(self.frameType)
        self.label_66.setMinimumSize(QtCore.QSize(130, 0))
        self.label_66.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.hLayoutType.addWidget(self.label_66)
        self.cmbType = QtGui.QComboBox(self.frameType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbType.sizePolicy().hasHeightForWidth())
        self.cmbType.setSizePolicy(sizePolicy)
        self.cmbType.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbType.setFont(font)
        self.cmbType.setObjectName(_fromUtf8("cmbType"))
        self.cmbType.setMinimumSize(QtCore.QSize(130, 0))
        self.cmbType.setMaximumSize(QtCore.QSize(130, 16777215))
        self.hLayoutType.addWidget(self.cmbType)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hLayoutType.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameType)

        self.txtTrack = TrackRadialBoxPanel(self.gbParameters)
        self.txtTrack.Caption = "Track"
        self.txtTrack.LabelWidth = 130
        self.vl_gbParameters.addWidget(self.txtTrack)

        self.frameDistance = QtGui.QFrame(self.gbParameters)
        self.frameDistance.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameDistance.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDistance.setObjectName(_fromUtf8("frameDistance"))
        self.hLayoutDistance = QtGui.QHBoxLayout(self.frameDistance)
        self.hLayoutDistance.setSpacing(0)
        self.hLayoutDistance.setMargin(0)
        self.hLayoutDistance.setObjectName(_fromUtf8("hLayoutDistance"))
        self.label_76 = QtGui.QLabel(self.frameDistance)
        self.label_76.setMinimumSize(QtCore.QSize(130, 0))
        self.label_76.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_76.setFont(font)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.hLayoutDistance.addWidget(self.label_76)
        self.frame_APV_11 = QtGui.QFrame(self.frameDistance)
        self.frame_APV_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_APV_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_APV_11.setObjectName(_fromUtf8("frame_APV_11"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.frame_APV_11)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.txtDistance = QtGui.QLineEdit(self.frame_APV_11)
        self.txtDistance.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtDistance.setFont(font)
        self.txtDistance.setObjectName(_fromUtf8("txtDistance"))
        self.txtDistance.setMinimumSize(QtCore.QSize(60, 0))
        self.txtDistance.setMaximumSize(QtCore.QSize(60, 16777215))
        self.horizontalLayout_15.addWidget(self.txtDistance)
        self.btnCaptureDistance = QtGui.QToolButton(self.frame_APV_11)
        self.btnCaptureDistance.setText(_fromUtf8(""))
        self.btnCaptureDistance.setIcon(icon)
        self.btnCaptureDistance.setObjectName(_fromUtf8("btnCaptureDistance"))
        self.horizontalLayout_15.addWidget(self.btnCaptureDistance)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(horizontalSpacer)
        self.hLayoutDistance.addWidget(self.frame_APV_11)
        self.vl_gbParameters.addWidget(self.frameDistance)
        self.frameAltitude = QtGui.QFrame(self.gbParameters)
        self.frameAltitude.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAltitude.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAltitude.setObjectName(_fromUtf8("frameAltitude"))
        self.hLayoutPDG_2 = QtGui.QHBoxLayout(self.frameAltitude)
        self.hLayoutPDG_2.setSpacing(0)
        self.hLayoutPDG_2.setMargin(0)
        self.hLayoutPDG_2.setObjectName(_fromUtf8("hLayoutPDG_2"))
        self.label_69 = QtGui.QLabel(self.frameAltitude)
        self.label_69.setMinimumSize(QtCore.QSize(130, 0))
        self.label_69.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.hLayoutPDG_2.addWidget(self.label_69)
        self.txtAltitudeM = QtGui.QLineEdit(self.frameAltitude)
        self.txtAltitudeM.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAltitudeM.setFont(font)
        self.txtAltitudeM.setObjectName(_fromUtf8("txtAltitudeM"))
        self.txtAltitudeM.setMinimumSize(QtCore.QSize(90, 0))
        self.txtAltitudeM.setMaximumSize(QtCore.QSize(90, 16777215))
        self.hLayoutPDG_2.addWidget(self.txtAltitudeM)
        self.label = QtGui.QLabel(self.frameAltitude)
        self.label.setObjectName(_fromUtf8("label"))
        self.hLayoutPDG_2.addWidget(self.label)
        self.txtAltitudeFt = QtGui.QLineEdit(self.frameAltitude)
        self.txtAltitudeFt.setObjectName(_fromUtf8("txtAltitudeFt"))
        self.txtAltitudeFt.setMinimumSize(QtCore.QSize(90, 0))
        self.txtAltitudeFt.setMaximumSize(QtCore.QSize(90, 16777215))
        self.hLayoutPDG_2.addWidget(self.txtAltitudeFt)
        self.label_2 = QtGui.QLabel(self.frameAltitude)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.hLayoutPDG_2.addWidget(self.label_2)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hLayoutPDG_2.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameAltitude)
        self.chbCatH = QtGui.QCheckBox(self.gbParameters)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbCatH.setFont(font)
        self.chbCatH.setObjectName(_fromUtf8("chbCatH"))
        self.vl_gbParameters.addWidget(self.chbCatH)
        self.frameMoc = QtGui.QFrame(self.gbParameters)
        self.frameMoc.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMoc.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMoc.setObjectName(_fromUtf8("frameMoc"))
        self.hLayoutMoc = QtGui.QHBoxLayout(self.frameMoc)
        self.hLayoutMoc.setSpacing(0)
        self.hLayoutMoc.setMargin(0)
        self.hLayoutMoc.setObjectName(_fromUtf8("hLayoutMoc"))
        self.label_77 = QtGui.QLabel(self.frameMoc)
        self.label_77.setMinimumSize(QtCore.QSize(130, 0))
        self.label_77.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.hLayoutMoc.addWidget(self.label_77)
        self.txtMoc = QtGui.QLineEdit(self.frameMoc)
        self.txtMoc.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtMoc.setFont(font)
        self.txtMoc.setObjectName(_fromUtf8("txtMoc"))
        self.txtMoc.setMinimumSize(QtCore.QSize(60, 0))
        self.txtMoc.setMaximumSize(QtCore.QSize(60, 16777215))
        self.hLayoutMoc.addWidget(self.txtMoc)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hLayoutMoc.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameMoc)
        self.framePDG = QtGui.QFrame(self.gbParameters)
        self.framePDG.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePDG.setFrameShadow(QtGui.QFrame.Raised)
        self.framePDG.setObjectName(_fromUtf8("framePDG"))
        self.hLayoutPDG = QtGui.QHBoxLayout(self.framePDG)
        self.hLayoutPDG.setSpacing(0)
        self.hLayoutPDG.setMargin(0)
        self.hLayoutPDG.setObjectName(_fromUtf8("hLayoutPDG"))
        self.label_68 = QtGui.QLabel(self.framePDG)
        self.label_68.setMinimumSize(QtCore.QSize(130, 0))
        self.label_68.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.hLayoutPDG.addWidget(self.label_68)
        self.txtPdg = QtGui.QLineEdit(self.framePDG)
        self.txtPdg.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtPdg.setFont(font)
        self.txtPdg.setObjectName(_fromUtf8("txtPdg"))
        self.txtPdg.setMinimumSize(QtCore.QSize(60, 0))
        self.txtPdg.setMaximumSize(QtCore.QSize(60, 16777215))
        self.hLayoutPDG.addWidget(self.txtPdg)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hLayoutPDG.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.framePDG)
        self.frameConstruct = QtGui.QFrame(self.gbParameters)
        self.frameConstruct.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameConstruct.setFrameShadow(QtGui.QFrame.Raised)
        self.frameConstruct.setObjectName(_fromUtf8("frameConstruct"))
        self.hLayoutConstruct = QtGui.QHBoxLayout(self.frameConstruct)
        self.hLayoutConstruct.setSpacing(0)
        self.hLayoutConstruct.setMargin(0)
        self.hLayoutConstruct.setObjectName(_fromUtf8("hLayoutConstruct"))
        self.label_83 = QtGui.QLabel(self.frameConstruct)
        self.label_83.setMinimumSize(QtCore.QSize(130, 0))
        self.label_83.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_83.setFont(font)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.hLayoutConstruct.addWidget(self.label_83)
        self.cmbConstruct = QtGui.QComboBox(self.frameConstruct)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConstruct.sizePolicy().hasHeightForWidth())
        self.cmbConstruct.setSizePolicy(sizePolicy)
        self.cmbConstruct.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbConstruct.setFont(font)
        self.cmbConstruct.setObjectName(_fromUtf8("cmbConstruct"))
        self.cmbConstruct.setMinimumSize(QtCore.QSize(60, 0))
        self.cmbConstruct.setMaximumSize(QtCore.QSize(60, 16777215))
        self.hLayoutConstruct.addWidget(self.cmbConstruct)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hLayoutConstruct.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameConstruct)
        self.frameMOCmultipiler = QtGui.QFrame(self.gbParameters)
        self.frameMOCmultipiler.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMOCmultipiler.setFrameShadow(QtGui.QFrame.Raised)
        self.frameMOCmultipiler.setObjectName(_fromUtf8("frameMOCmultipiler"))
        self.hLayoutMOCmultipiler = QtGui.QHBoxLayout(self.frameMOCmultipiler)
        self.hLayoutMOCmultipiler.setSpacing(0)
        self.hLayoutMOCmultipiler.setMargin(0)
        self.hLayoutMOCmultipiler.setObjectName(_fromUtf8("hLayoutMOCmultipiler"))
        self.label_84 = QtGui.QLabel(self.frameMOCmultipiler)
        self.label_84.setMinimumSize(QtCore.QSize(130, 0))
        self.label_84.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_84.setFont(font)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.hLayoutMOCmultipiler.addWidget(self.label_84)
        self.mocSpinBox = QtGui.QSpinBox(self.frameMOCmultipiler)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mocSpinBox.sizePolicy().hasHeightForWidth())
        self.mocSpinBox.setSizePolicy(sizePolicy)
        self.mocSpinBox.setMinimumSize(QtCore.QSize(72, 0))
        self.mocSpinBox.setMinimum(1)
        self.mocSpinBox.setObjectName(_fromUtf8("mocSpinBox"))
        self.mocSpinBox.setMinimumSize(QtCore.QSize(60, 0))
        self.mocSpinBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.hLayoutMOCmultipiler.addWidget(self.mocSpinBox)
        horizontalSpacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hLayoutMOCmultipiler.addItem(horizontalSpacer)
        self.vl_gbParameters.addWidget(self.frameMOCmultipiler)
        self.verticalLayout.addWidget(self.gbParameters)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.gbRunway.setTitle(_translate("Form", "Runway", None))
        # self.label_74.setText(_translate("Form", "Direction ():", None))
        # self.txtRwyDir.setText(_translate("Form", "0", None))
        self.gbParameters.setTitle(_translate("Form", "Parameters", None))
        self.label_66.setText(_translate("Form", "Type:", None))
        # self.label_75.setText(_translate("Form", "Track ():", None))
        # self.txtTrack.setText(_translate("Form", "0", None))
        self.label_76.setText(_translate("Form", "Distance(nm):", None))
        self.txtDistance.setText(_translate("Form", "10", None))
        self.label_69.setText(_translate("Form", "Altitude:", None))
        self.txtAltitudeM.setText(_translate("Form", "0", None))
        self.label.setText(_translate("Form", "m", None))
        self.txtAltitudeFt.setText(_translate("Form", "0", None))
        self.label_2.setText(_translate("Form", "ft", None))
        self.chbCatH.setText(_translate("Form", "Cat. H", None))
        self.label_77.setText(_translate("Form", "MOC(%):", None))
        self.txtMoc.setText(_translate("Form", "0.8", None))
        self.label_68.setText(_translate("Form", "PDG(%):", None))
        self.txtPdg.setText(_translate("Form", "3.3", None))
        self.label_83.setText(_translate("Form", "Construction Type:", None))
        self.label_84.setText(_translate("Form", "MOCmultiplier:", None))

